[package]
name = "collaboration_migrate"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/collaboration_migrate.rs"

[dependencies]
async-trait.workspace = true
collab.workspace = true
collaboration_domain.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
uuid.workspace = true
