// @generated by `cargo xtask products`; do not edit.
/// The stable selected product ID.
pub const ID: &str = "rust";
/// The selected product's user-facing name.
pub const DISPLAY_NAME: &str = "Copper";
/// Error title shown when installing the product CLI fails.
pub const INSTALL_CLI_ERROR_TITLE: &str = "Cannot install the Copper CLI";
/// Error title shown when registering the product URL scheme fails.
pub const REGISTER_SCHEME_ERROR_TITLE: &str = "Error registering ide-rust scheme";
/// Development-channel display name.
pub const DEV_DISPLAY_NAME: &str = "Copper Dev";
/// Nightly-channel display name.
pub const NIGHTLY_DISPLAY_NAME: &str = "Copper Nightly";
/// Preview-channel display name.
pub const PREVIEW_DISPLAY_NAME: &str = "Copper Preview";
/// The selected product's installed executable basename.
pub const EXECUTABLE_NAME: &str = "copper";
/// The selected product's reverse-DNS bundle identifier.
pub const BUNDLE_IDENTIFIER: &str = "dev.ideflavors.rust";
/// Development-channel application identifier.
pub const DEV_BUNDLE_IDENTIFIER: &str = "dev.ideflavors.rust.dev";
/// Nightly-channel application identifier.
pub const NIGHTLY_BUNDLE_IDENTIFIER: &str = "dev.ideflavors.rust.nightly";
/// Preview-channel application identifier.
pub const PREVIEW_BUNDLE_IDENTIFIER: &str = "dev.ideflavors.rust.preview";
/// The selected product's registered URL scheme.
pub const URL_SCHEME: &str = "ide-rust";
/// Public deep-link prefix.
pub const URL_PREFIX: &str = "ide-rust://";
/// Private CLI transport prefix.
pub const CLI_URL_PREFIX: &str = "ide-rust-cli://";
/// Private dock-action transport prefix.
pub const DOCK_ACTION_URL_PREFIX: &str = "ide-rust-dock-action://";
/// The selected product's stable global data namespace.
pub const DATA_NAMESPACE: &str = "ide-rust";
/// Development-channel data namespace.
pub const DEV_DATA_NAMESPACE: &str = "ide-rust-dev";
/// Nightly-channel data namespace.
pub const NIGHTLY_DATA_NAMESPACE: &str = "ide-rust-nightly";
/// Preview-channel data namespace.
pub const PREVIEW_DATA_NAMESPACE: &str = "ide-rust-preview";
/// Prefix for temporary update directories.
pub const AUTO_UPDATE_DIR_PREFIX: &str = "ide-rust-auto-update";
/// Development-channel update directory prefix.
pub const DEV_AUTO_UPDATE_DIR_PREFIX: &str = "ide-rust-dev-auto-update";
/// Nightly-channel update directory prefix.
pub const NIGHTLY_AUTO_UPDATE_DIR_PREFIX: &str = "ide-rust-nightly-auto-update";
/// Preview-channel update directory prefix.
pub const PREVIEW_AUTO_UPDATE_DIR_PREFIX: &str = "ide-rust-preview-auto-update";
/// Remote-server installation directory name.
pub const REMOTE_SERVER_DIR: &str = ".ide-rust_server";
/// Development-channel remote-server directory name.
pub const DEV_REMOTE_SERVER_DIR: &str = ".ide-rust-dev_server";
/// Nightly-channel remote-server directory name.
pub const NIGHTLY_REMOTE_SERVER_DIR: &str = ".ide-rust-nightly_server";
/// Preview-channel remote-server directory name.
pub const PREVIEW_REMOTE_SERVER_DIR: &str = ".ide-rust-preview_server";
/// WSL remote-server installation directory name.
pub const REMOTE_WSL_SERVER_DIR: &str = ".ide-rust_wsl_server";
/// Development-channel WSL remote-server directory name.
pub const DEV_REMOTE_WSL_SERVER_DIR: &str = ".ide-rust-dev_wsl_server";
/// Nightly-channel WSL remote-server directory name.
pub const NIGHTLY_REMOTE_WSL_SERVER_DIR: &str = ".ide-rust-nightly_wsl_server";
/// Preview-channel WSL remote-server directory name.
pub const PREVIEW_REMOTE_WSL_SERVER_DIR: &str = ".ide-rust-preview_wsl_server";
/// The selected product's update-feed namespace.
pub const UPDATE_NAMESPACE: &str = "rust";
/// Product-specific offset for loopback single-instance coordination.
pub const INSTANCE_PORT_OFFSET: u16 = 4000;
/// The selected product's agent profile ID.
pub const AGENT_PROFILE: &str = "rust-engineer";
/// The selected product's agent profile display name.
pub const AGENT_PROFILE_NAME: &str = "Rust Engineer";
/// The selected product's Rust-focused agent instructions.
pub const AGENT_INSTRUCTIONS: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../assets/product_flavors/rust/agent-instructions.md"));
/// Product Cargo features for the application package.
pub const CARGO_FEATURES: &[&str] = &["multiplayer-tools", "rust-tools"];
/// Product Cargo features for the remote server package.
pub const REMOTE_SERVER_FEATURES: &[&str] = &["rust-tools"];
/// Product language-server defaults.
pub const DEFAULT_LANGUAGE_SERVERS: &[&str] = &["rust-analyzer"];
/// Product extension defaults.
pub const DEFAULT_EXTENSIONS: &[&str] = &[];
/// Product toolchain onboarding handler ID.
pub const TOOLCHAIN_ONBOARDING: &str = "rustup";
