use crate::actions::{CommandAvailability, NativeAction};

pub const GENERATED_KEY_CONTEXT: &str = "ComfyGraph";
pub const GENERATED_TEXT_INPUT_KEY_CONTEXT: &str = "ComfyTextInput";
pub const GENERATED_KEYMAP_CONTEXT: &str = "ComfyGraph && !ComfyTextInput";

#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize)]
pub struct GeneratedKeybindingCatalogRow {
    pub feature_id: &'static str,
    pub source_combo: &'static str,
    pub keystroke: &'static str,
    pub command_id: &'static str,
    pub native_action: NativeAction,
    pub availability: CommandAvailability,
}

pub static GENERATED_KEYBINDING_CATALOG: [GeneratedKeybindingCatalogRow; 34] = [
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-069",
        source_combo: "Ctrl + Enter",
        keystroke: "ctrl-enter",
        command_id: "Comfy.QueuePrompt",
        native_action: NativeAction::QueuePrompt,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-070",
        source_combo: "Ctrl + Shift + Enter",
        keystroke: "ctrl-shift-enter",
        command_id: "Comfy.QueuePromptFront",
        native_action: NativeAction::QueuePromptFront,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-071",
        source_combo: "Ctrl + Alt + Enter",
        keystroke: "ctrl-alt-enter",
        command_id: "Comfy.Interrupt",
        native_action: NativeAction::Interrupt,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-072",
        source_combo: "r",
        keystroke: "r",
        command_id: "Comfy.RefreshNodeDefinitions",
        native_action: NativeAction::RefreshNodeDefinitions,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-073",
        source_combo: "w",
        keystroke: "w",
        command_id: "Workspace.ToggleSidebarTab.workflows",
        native_action: NativeAction::ToggleWorkflowsSidebar,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-074",
        source_combo: "n",
        keystroke: "n",
        command_id: "Workspace.ToggleSidebarTab.node-library",
        native_action: NativeAction::ToggleNodeLibrarySidebar,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-075",
        source_combo: "m",
        keystroke: "m",
        command_id: "Workspace.ToggleSidebarTab.model-library",
        native_action: NativeAction::ToggleModelLibrarySidebar,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-076",
        source_combo: "a",
        keystroke: "a",
        command_id: "Workspace.ToggleSidebarTab.assets",
        native_action: NativeAction::ToggleAssetsSidebar,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-077",
        source_combo: "Alt + m",
        keystroke: "alt-m",
        command_id: "Comfy.ToggleLinear",
        native_action: NativeAction::ToggleLinear,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-078",
        source_combo: "Alt + µ",
        keystroke: "alt-µ",
        command_id: "Comfy.ToggleLinear",
        native_action: NativeAction::ToggleLinear,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-079",
        source_combo: "Ctrl + s",
        keystroke: "ctrl-s",
        command_id: "Comfy.SaveWorkflow",
        native_action: NativeAction::SaveWorkflow,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-080",
        source_combo: "Ctrl + o",
        keystroke: "ctrl-o",
        command_id: "Comfy.OpenWorkflow",
        native_action: NativeAction::OpenWorkflow,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-081",
        source_combo: "Ctrl + g",
        keystroke: "ctrl-g",
        command_id: "Comfy.Graph.GroupSelectedNodes",
        native_action: NativeAction::GroupSelectedNodes,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-082",
        source_combo: "Ctrl + ,",
        keystroke: "ctrl-,",
        command_id: "Comfy.ShowSettingsDialog",
        native_action: NativeAction::ShowSettings,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-083",
        source_combo: "Alt + =",
        keystroke: "alt-=",
        command_id: "Comfy.Canvas.ZoomIn",
        native_action: NativeAction::GraphZoomIn,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-084",
        source_combo: "Alt + Shift + +",
        keystroke: "alt-shift-+",
        command_id: "Comfy.Canvas.ZoomIn",
        native_action: NativeAction::GraphZoomIn,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-085",
        source_combo: "Alt + +",
        keystroke: "alt-+",
        command_id: "Comfy.Canvas.ZoomIn",
        native_action: NativeAction::GraphZoomIn,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-086",
        source_combo: "Alt + -",
        keystroke: "alt--",
        command_id: "Comfy.Canvas.ZoomOut",
        native_action: NativeAction::GraphZoomOut,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-087",
        source_combo: ".",
        keystroke: ".",
        command_id: "Comfy.Canvas.FitView",
        native_action: NativeAction::GraphFitView,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-088",
        source_combo: "p",
        keystroke: "p",
        command_id: "Comfy.Canvas.ToggleSelected.Pin",
        native_action: NativeAction::ToggleSelectedItemsPin,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-089",
        source_combo: "Alt + c",
        keystroke: "alt-c",
        command_id: "Comfy.Canvas.ToggleSelectedNodes.Collapse",
        native_action: NativeAction::ToggleSelectedCollapse,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-090",
        source_combo: "Ctrl + b",
        keystroke: "ctrl-b",
        command_id: "Comfy.Canvas.ToggleSelectedNodes.Bypass",
        native_action: NativeAction::ToggleSelectedBypass,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-091",
        source_combo: "Ctrl + m",
        keystroke: "ctrl-m",
        command_id: "Comfy.Canvas.ToggleSelectedNodes.Mute",
        native_action: NativeAction::ToggleSelectedMute,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-092",
        source_combo: "Ctrl + `",
        keystroke: "ctrl-`",
        command_id: "Workspace.ToggleBottomPanelTab.logs-terminal",
        native_action: NativeAction::ToggleLogsPanel,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-093",
        source_combo: "Ctrl + Shift + e",
        keystroke: "ctrl-shift-e",
        command_id: "Comfy.Graph.ConvertToSubgraph",
        native_action: NativeAction::ConvertToSubgraph,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-094",
        source_combo: "Alt + Shift + m",
        keystroke: "alt-shift-m",
        command_id: "Comfy.Canvas.ToggleMinimap",
        native_action: NativeAction::ToggleMinimap,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-095",
        source_combo: "Ctrl + Shift + k",
        keystroke: "ctrl-shift-k",
        command_id: "Workspace.ToggleBottomPanel.Shortcuts",
        native_action: NativeAction::ShowKeybindings,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-096",
        source_combo: "v",
        keystroke: "v",
        command_id: "Comfy.Canvas.Unlock",
        native_action: NativeAction::UnlockCanvas,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-097",
        source_combo: "h",
        keystroke: "h",
        command_id: "Comfy.Canvas.Lock",
        native_action: NativeAction::LockCanvas,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-A11Y-003",
        source_combo: "Escape",
        keystroke: "escape",
        command_id: "Comfy.Graph.ExitSubgraph",
        native_action: NativeAction::ExitSubgraph,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-098",
        source_combo: "Ctrl + a",
        keystroke: "ctrl-a",
        command_id: "Comfy.Canvas.SelectAll",
        native_action: NativeAction::GraphSelectAll,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-SETTING-099",
        source_combo: "Ctrl + Shift + v",
        keystroke: "ctrl-shift-v",
        command_id: "Comfy.Canvas.PasteFromClipboardWithConnect",
        native_action: NativeAction::PasteWithConnect,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-A11Y-004",
        source_combo: "Delete",
        keystroke: "delete",
        command_id: "Comfy.Canvas.DeleteSelectedItems",
        native_action: NativeAction::GraphDelete,
        availability: CommandAvailability::Active,
    },
    GeneratedKeybindingCatalogRow {
        feature_id: "COMFY-A11Y-005",
        source_combo: "Backspace",
        keystroke: "backspace",
        command_id: "Comfy.Canvas.DeleteSelectedItems",
        native_action: NativeAction::GraphDelete,
        availability: CommandAvailability::Active,
    },
];
