use crate::actions::{CommandAvailability, CommandNativeStatus, NativeAction, NativePlacement};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct GeneratedCommandCatalogRow {
    pub feature_id: &'static str,
    pub command_id: &'static str,
    pub label: &'static str,
    pub availability: CommandAvailability,
    pub placement: NativePlacement,
    pub owner: &'static str,
    pub status: CommandNativeStatus,
    pub native_action: Option<NativeAction>,
}

pub static GENERATED_COMMAND_CATALOG: [GeneratedCommandCatalogRow; 118] = [
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-056",
        command_id: "Comfy-Desktop.CheckForUpdates",
        label: "Check for Updates",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-updates-snapshots",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-updates-snapshots",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-FRONTEXT-EXT-086",
        command_id: "Comfy-Desktop.Folders.OpenCustomNodesFolder",
        label: "Open Custom Nodes Folder",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-desktop-native-ui",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-desktop-native-ui",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-057",
        command_id: "Comfy-Desktop.Folders.OpenInputsFolder",
        label: "Open Inputs Folder",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-desktop-native-ui",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-desktop-native-ui",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-058",
        command_id: "Comfy-Desktop.Folders.OpenLogsFolder",
        label: "Open Logs Folder",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-desktop-native-ui",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-desktop-native-ui",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-059",
        command_id: "Comfy-Desktop.Folders.OpenModelConfig",
        label: "Open extra_model_paths.yaml",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-desktop-native-ui",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-desktop-native-ui",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-060",
        command_id: "Comfy-Desktop.Folders.OpenModelsFolder",
        label: "Open Models Folder",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-desktop-native-ui",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-desktop-native-ui",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-061",
        command_id: "Comfy-Desktop.Folders.OpenOutputsFolder",
        label: "Open Outputs Folder",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-desktop-native-ui",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-desktop-native-ui",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-062",
        command_id: "Comfy-Desktop.OpenDevTools",
        label: "Open DevTools",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-desktop-native-ui",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-desktop-native-ui",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-063",
        command_id: "Comfy-Desktop.OpenUserGuide",
        label: "Desktop User Guide",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-desktop-native-ui",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-desktop-native-ui",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-064",
        command_id: "Comfy-Desktop.Quit",
        label: "Quit",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-desktop-native-ui",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-desktop-native-ui",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-065",
        command_id: "Comfy-Desktop.Reinstall",
        label: "Reinstall",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-updates-snapshots",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-updates-snapshots",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-066",
        command_id: "Comfy-Desktop.Restart",
        label: "Restart",
        availability: CommandAvailability::PlatformSpecific,
        placement: NativePlacement::DesktopIntegration,
        owner: "comfy-parity-desktop-native-ui",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-desktop-native-ui",
            gate: "platform-specific",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-053",
        command_id: "Comfy.3DViewer.Open3DViewer",
        label: "Open 3D Viewer (Beta) for Selected Node",
        availability: CommandAvailability::Experimental,
        placement: NativePlacement::MediaEditor,
        owner: "comfy-parity-three-d-latent-content",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-three-d-latent-content",
            gate: "experimental",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-054",
        command_id: "Comfy.BrowseModelAssets",
        label: "Experimental: Browse Model Assets",
        availability: CommandAvailability::Experimental,
        placement: NativePlacement::AssetBrowser,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-assets-editors-viewers",
            gate: "experimental",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-074",
        command_id: "Comfy.BrowseTemplates",
        label: "Browse Templates",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-087",
        command_id: "Comfy.Canvas.CopySelected",
        label: "Copy",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::GraphCopy),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-088",
        command_id: "Comfy.Canvas.DeleteSelectedItems",
        label: "Delete Selected Items",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::GraphDelete),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-089",
        command_id: "Comfy.Canvas.FitView",
        label: "Fit view to selected nodes",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::GraphFitView),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-090",
        command_id: "Comfy.Canvas.Lock",
        label: "Lock Canvas",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::LockCanvas),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-091",
        command_id: "Comfy.Canvas.MoveSelectedNodes.Down",
        label: "Move Selected Nodes Down",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::MoveSelectedDown),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-092",
        command_id: "Comfy.Canvas.MoveSelectedNodes.Left",
        label: "Move Selected Nodes Left",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::MoveSelectedLeft),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-093",
        command_id: "Comfy.Canvas.MoveSelectedNodes.Right",
        label: "Move Selected Nodes Right",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::MoveSelectedRight),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-094",
        command_id: "Comfy.Canvas.MoveSelectedNodes.Up",
        label: "Move Selected Nodes Up",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::MoveSelectedUp),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-095",
        command_id: "Comfy.Canvas.PasteFromClipboard",
        label: "Paste",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::GraphPaste),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-096",
        command_id: "Comfy.Canvas.PasteFromClipboardWithConnect",
        label: "Paste with Connect",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::PasteWithConnect),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-097",
        command_id: "Comfy.Canvas.ResetView",
        label: "Reset View",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ResetView),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-098",
        command_id: "Comfy.Canvas.Resize",
        label: "Resize Selected Nodes",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ResizeSelectedNodes),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-099",
        command_id: "Comfy.Canvas.SelectAll",
        label: "Select All",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::GraphSelectAll),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-100",
        command_id: "Comfy.Canvas.ToggleLinkVisibility",
        label: "Canvas Toggle Link Visibility",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ToggleLinkVisibility),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-101",
        command_id: "Comfy.Canvas.ToggleLock",
        label: "Canvas Toggle Lock",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ToggleCanvasLock),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-102",
        command_id: "Comfy.Canvas.ToggleMinimap",
        label: "Canvas Toggle Minimap",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ToggleMinimap),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-104",
        command_id: "Comfy.Canvas.ToggleSelectedNodes.Bypass",
        label: "Bypass/Unbypass Selected Nodes",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ToggleSelectedBypass),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-105",
        command_id: "Comfy.Canvas.ToggleSelectedNodes.Collapse",
        label: "Collapse/Expand Selected Nodes",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ToggleSelectedCollapse),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-106",
        command_id: "Comfy.Canvas.ToggleSelectedNodes.Mute",
        label: "Mute/Unmute Selected Nodes",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ToggleSelectedMute),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-107",
        command_id: "Comfy.Canvas.ToggleSelectedNodes.Pin",
        label: "Pin/Unpin Selected Nodes",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ToggleSelectedNodesPin),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-103",
        command_id: "Comfy.Canvas.ToggleSelected.Pin",
        label: "Pin/Unpin Selected Items",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ToggleSelectedItemsPin),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-108",
        command_id: "Comfy.Canvas.Unlock",
        label: "Unlock Canvas",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::UnlockCanvas),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-109",
        command_id: "Comfy.Canvas.ZoomIn",
        label: "Zoom In",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::GraphZoomIn),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-110",
        command_id: "Comfy.Canvas.ZoomOut",
        label: "Zoom Out",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::GraphZoomOut),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-067",
        command_id: "Comfy.ClearPendingTasks",
        label: "Clear Pending Tasks",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExecutionDock,
        owner: "comfy-parity-execution-ui",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ClearPendingTasks),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-075",
        command_id: "Comfy.ClearWorkflow",
        label: "Clear Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-068",
        command_id: "Comfy.ContactSupport",
        label: "Contact Support",
        availability: CommandAvailability::Active,
        placement: NativePlacement::HelpCenter,
        owner: "comfy-parity-process-diagnostics",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-process-diagnostics",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-069",
        command_id: "Comfy.Dev.ShowModelSelector",
        label: "Show Model Selector (Dev)",
        availability: CommandAvailability::Active,
        placement: NativePlacement::NodeLibrary,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-assets-editors-viewers",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-076",
        command_id: "Comfy.DuplicateWorkflow",
        label: "Duplicate Current Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-077",
        command_id: "Comfy.ExportWorkflow",
        label: "Export Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-078",
        command_id: "Comfy.ExportWorkflowAPI",
        label: "Export Workflow (API Format)",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-111",
        command_id: "Comfy.Graph.ConvertToSubgraph",
        label: "Convert Selection to Subgraph",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-context-menu-surfaces",
        status: CommandNativeStatus::RequiresInput {
            owner: "comfy-parity-graph-context-menu-surfaces",
            input: "subgraph name",
        },
        native_action: Some(NativeAction::ConvertToSubgraph),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-112",
        command_id: "Comfy.Graph.EditSubgraphWidgets",
        label: "Edit Subgraph Widgets",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-context-menu-surfaces",
        status: CommandNativeStatus::RequiresInput {
            owner: "comfy-parity-graph-context-menu-surfaces",
            input: "hovered widget and exposure state",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-113",
        command_id: "Comfy.Graph.ExitSubgraph",
        label: "Exit Subgraph",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ExitSubgraph),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-114",
        command_id: "Comfy.Graph.FitGroupToContents",
        label: "Fit Group To Contents",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::FitGroupToContents),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-115",
        command_id: "Comfy.Graph.GroupSelectedNodes",
        label: "Group Selected Nodes",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::GroupSelectedNodes),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-116",
        command_id: "Comfy.Graph.ToggleWidgetPromotion",
        label: "Toggle promotion of hovered widget",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-context-menu-surfaces",
        status: CommandNativeStatus::RequiresInput {
            owner: "comfy-parity-graph-context-menu-surfaces",
            input: "hovered widget and exposure state",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-117",
        command_id: "Comfy.Graph.UnpackSubgraph",
        label: "Unpack the selected Subgraph",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::UnpackSubgraph),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-070",
        command_id: "Comfy.Help.AboutComfyUI",
        label: "Open About ComfyUI",
        availability: CommandAvailability::Active,
        placement: NativePlacement::HelpCenter,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-071",
        command_id: "Comfy.Help.OpenComfyOrgDiscord",
        label: "Open Comfy-Org Discord",
        availability: CommandAvailability::Active,
        placement: NativePlacement::HelpCenter,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-072",
        command_id: "Comfy.Help.OpenComfyUIDocs",
        label: "Open ComfyUI Docs",
        availability: CommandAvailability::Active,
        placement: NativePlacement::HelpCenter,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-073",
        command_id: "Comfy.Help.OpenComfyUIForum",
        label: "Open ComfyUI Forum",
        availability: CommandAvailability::Active,
        placement: NativePlacement::HelpCenter,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-074",
        command_id: "Comfy.Help.OpenComfyUIIssues",
        label: "Open ComfyUI Issues",
        availability: CommandAvailability::Active,
        placement: NativePlacement::HelpCenter,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-QUEUE-033",
        command_id: "Comfy.Interrupt",
        label: "Interrupt",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExecutionDock,
        owner: "comfy-parity-execution-ui",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::Interrupt),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-079",
        command_id: "Comfy.LoadDefaultWorkflow",
        label: "Load Default Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-FRONTEXT-EXT-087",
        command_id: "Comfy.Manager.CustomNodesManager.ShowCustomNodesMenu",
        label: "Custom Nodes Manager",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExtensionHost,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-assets-editors-viewers",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-FRONTEXT-EXT-088",
        command_id: "Comfy.Manager.CustomNodesManager.ShowLegacyCustomNodesMenu",
        label: "Custom Nodes (Legacy)",
        availability: CommandAvailability::Deprecated,
        placement: NativePlacement::ExtensionHost,
        owner: "comfy-parity-backward-compatibility",
        status: CommandNativeStatus::Legacy {
            owner: "comfy-parity-backward-compatibility",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-FRONTEXT-EXT-089",
        command_id: "Comfy.Manager.ShowLegacyManagerMenu",
        label: "Manager Menu (Legacy)",
        availability: CommandAvailability::Deprecated,
        placement: NativePlacement::ExtensionHost,
        owner: "comfy-parity-backward-compatibility",
        status: CommandNativeStatus::Legacy {
            owner: "comfy-parity-backward-compatibility",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-FRONTEXT-EXT-090",
        command_id: "Comfy.Manager.ShowMissingPacks",
        label: "Install Missing Custom Nodes",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExtensionHost,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-assets-editors-viewers",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-FRONTEXT-EXT-091",
        command_id: "Comfy.Manager.ShowUpdateAvailablePacks",
        label: "Check for Custom Node Updates",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExtensionHost,
        owner: "comfy-parity-updates-snapshots",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-updates-snapshots",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-055",
        command_id: "Comfy.MaskEditor.BrushSize.Decrease",
        label: "Decrease Brush Size in MaskEditor",
        availability: CommandAvailability::Active,
        placement: NativePlacement::MediaEditor,
        owner: "comfy-parity-image-mask-content",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-image-mask-content",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-056",
        command_id: "Comfy.MaskEditor.BrushSize.Increase",
        label: "Increase Brush Size in MaskEditor",
        availability: CommandAvailability::Active,
        placement: NativePlacement::MediaEditor,
        owner: "comfy-parity-image-mask-content",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-image-mask-content",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-057",
        command_id: "Comfy.MaskEditor.ColorPicker",
        label: "Open Color Picker in MaskEditor",
        availability: CommandAvailability::Active,
        placement: NativePlacement::MediaEditor,
        owner: "comfy-parity-image-mask-content",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-image-mask-content",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-058",
        command_id: "Comfy.MaskEditor.Mirror.Horizontal",
        label: "Mirror Horizontal in MaskEditor",
        availability: CommandAvailability::Active,
        placement: NativePlacement::MediaEditor,
        owner: "comfy-parity-image-mask-content",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-image-mask-content",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-059",
        command_id: "Comfy.MaskEditor.Mirror.Vertical",
        label: "Mirror Vertical in MaskEditor",
        availability: CommandAvailability::Active,
        placement: NativePlacement::MediaEditor,
        owner: "comfy-parity-image-mask-content",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-image-mask-content",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-060",
        command_id: "Comfy.MaskEditor.OpenMaskEditor",
        label: "Open Mask Editor for Selected Node",
        availability: CommandAvailability::Active,
        placement: NativePlacement::MediaEditor,
        owner: "comfy-parity-image-mask-content",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-image-mask-content",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-061",
        command_id: "Comfy.MaskEditor.Rotate.Left",
        label: "Rotate Left in MaskEditor",
        availability: CommandAvailability::Active,
        placement: NativePlacement::MediaEditor,
        owner: "comfy-parity-image-mask-content",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-image-mask-content",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-062",
        command_id: "Comfy.MaskEditor.Rotate.Right",
        label: "Rotate Right in MaskEditor",
        availability: CommandAvailability::Active,
        placement: NativePlacement::MediaEditor,
        owner: "comfy-parity-image-mask-content",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-image-mask-content",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-075",
        command_id: "Comfy.Memory.UnloadModels",
        label: "Unload Models",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExecutionDock,
        owner: "comfy-parity-native-memory-planner",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-native-memory-planner",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-QUEUE-034",
        command_id: "Comfy.Memory.UnloadModelsAndExecutionCache",
        label: "Unload Models and Execution Cache",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExecutionDock,
        owner: "comfy-parity-native-memory-planner",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-native-memory-planner",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-080",
        command_id: "Comfy.NewBlankWorkflow",
        label: "New Blank Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-076",
        command_id: "Comfy.OpenClipspace",
        label: "Clipspace",
        availability: CommandAvailability::Active,
        placement: NativePlacement::MediaEditor,
        owner: "comfy-parity-image-mask-content",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-image-mask-content",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-FRONTEXT-EXT-092",
        command_id: "Comfy.OpenManagerDialog",
        label: "Manager",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExtensionHost,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-assets-editors-viewers",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-081",
        command_id: "Comfy.OpenWorkflow",
        label: "Open Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: Some(NativeAction::OpenWorkflow),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-118",
        command_id: "Comfy.PublishSubgraph",
        label: "Publish Subgraph",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::PublishSubgraph),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-QUEUE-036",
        command_id: "Comfy.QueuePrompt",
        label: "Queue Prompt",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExecutionDock,
        owner: "comfy-parity-execution-ui",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::QueuePrompt),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-QUEUE-037",
        command_id: "Comfy.QueuePromptFront",
        label: "Queue Prompt (Front)",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExecutionDock,
        owner: "comfy-parity-execution-ui",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::QueuePromptFront),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-QUEUE-038",
        command_id: "Comfy.QueueSelectedOutputNodes",
        label: "Queue Selected Output Nodes",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExecutionDock,
        owner: "comfy-parity-execution-ui",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::QueueSelectedOutputNodes),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-QUEUE-035",
        command_id: "Comfy.Queue.ToggleOverlay",
        label: "Toggle Job History",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExecutionDock,
        owner: "comfy-parity-execution-ui",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ToggleQueueOverlay),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-077",
        command_id: "Comfy.Redo",
        label: "Redo",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::GraphRedo),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-119",
        command_id: "Comfy.RefreshNodeDefinitions",
        label: "Refresh Node Definitions",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-native-registry-integration",
        status: CommandNativeStatus::RequiresInput {
            owner: "comfy-parity-native-registry-integration",
            input: "resolved node definition",
        },
        native_action: Some(NativeAction::RefreshNodeDefinitions),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-082",
        command_id: "Comfy.RenameWorkflow",
        label: "Rename Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-083",
        command_id: "Comfy.SaveWorkflow",
        label: "Save Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: Some(NativeAction::SaveWorkflow),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-084",
        command_id: "Comfy.SaveWorkflowAs",
        label: "Save Workflow As",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-SETTING-067",
        command_id: "Comfy.ShowSettingsDialog",
        label: "Show Settings Dialog",
        availability: CommandAvailability::Active,
        placement: NativePlacement::Settings,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: Some(NativeAction::ShowSettings),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-120",
        command_id: "Comfy.Subgraph.SetDescription",
        label: "Set Subgraph Description",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-context-menu-surfaces",
        status: CommandNativeStatus::RequiresInput {
            owner: "comfy-parity-graph-context-menu-surfaces",
            input: "subgraph definition and description",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-121",
        command_id: "Comfy.Subgraph.SetSearchAliases",
        label: "Set Subgraph Search Aliases",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-context-menu-surfaces",
        status: CommandNativeStatus::RequiresInput {
            owner: "comfy-parity-graph-context-menu-surfaces",
            input: "subgraph definition and search aliases",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-ASSET-063",
        command_id: "Comfy.ToggleAssetAPI",
        label: "Experimental: Enable AssetAPI",
        availability: CommandAvailability::Experimental,
        placement: NativePlacement::AssetBrowser,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-assets-editors-viewers",
            gate: "experimental",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-122",
        command_id: "Comfy.ToggleCanvasInfo",
        label: "Canvas Performance",
        availability: CommandAvailability::DeveloperOnly,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-graph-shell-accessibility",
            gate: "developer-only",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-078",
        command_id: "Comfy.ToggleHelpCenter",
        label: "Help Center",
        availability: CommandAvailability::Active,
        placement: NativePlacement::HelpCenter,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-WORKFLOW-085",
        command_id: "Comfy.ToggleLinear",
        label: "Toggle App Mode",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: Some(NativeAction::ToggleLinear),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-QUEUE-039",
        command_id: "Comfy.ToggleQPOV2",
        label: "Toggle Queue Panel V2",
        availability: CommandAvailability::Active,
        placement: NativePlacement::ExecutionDock,
        owner: "comfy-parity-execution-ui",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::ToggleQpov2),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-SETTING-068",
        command_id: "Comfy.ToggleTheme",
        label: "Toggle Theme (Dark/Light)",
        availability: CommandAvailability::Active,
        placement: NativePlacement::Settings,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-079",
        command_id: "Comfy.Undo",
        label: "Undo",
        availability: CommandAvailability::Active,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Executable,
        native_action: Some(NativeAction::GraphUndo),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-218",
        command_id: "Comfy.User.OpenSignInDialog",
        label: "Open Sign In Dialog",
        availability: CommandAvailability::CloudPaid,
        placement: NativePlacement::Account,
        owner: "comfy-parity-auth-cloud-telemetry",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-auth-cloud-telemetry",
            gate: "cloud-or-paid-service",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-UI-080",
        command_id: "Comfy.User.SignOut",
        label: "Sign Out",
        availability: CommandAvailability::Active,
        placement: NativePlacement::Account,
        owner: "comfy-parity-auth-cloud-telemetry",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-auth-cloud-telemetry",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-GRAPH-123",
        command_id: "Experimental.ToggleVueNodes",
        label: "Experimental: Enable Nodes 2.0",
        availability: CommandAvailability::Experimental,
        placement: NativePlacement::GraphWorkspace,
        owner: "comfy-parity-graph-shell-accessibility",
        status: CommandNativeStatus::Gated {
            owner: "comfy-parity-graph-shell-accessibility",
            gate: "experimental",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-219",
        command_id: "Workspace.CloseWorkflow",
        label: "Close Current Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-220",
        command_id: "Workspace.NextOpenedWorkflow",
        label: "Next Opened Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-221",
        command_id: "Workspace.PreviousOpenedWorkflow",
        label: "Previous Opened Workflow",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-222",
        command_id: "Workspace.SearchBox.Toggle",
        label: "Toggle Search Box",
        availability: CommandAvailability::Active,
        placement: NativePlacement::AssetBrowser,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-assets-editors-viewers",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-223",
        command_id: "Workspace.ToggleBottomPanel",
        label: "Toggle Bottom Panel",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-process-diagnostics",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-process-diagnostics",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-225",
        command_id: "Workspace.ToggleBottomPanelTab.command-terminal",
        label: "Toggle Terminal Bottom Panel",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-process-diagnostics",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-process-diagnostics",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-226",
        command_id: "Workspace.ToggleBottomPanelTab.logs-terminal",
        label: "Toggle Logs Bottom Panel",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-process-diagnostics",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-process-diagnostics",
        },
        native_action: Some(NativeAction::ToggleLogsPanel),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-227",
        command_id: "Workspace.ToggleBottomPanelTab.shortcuts-essentials",
        label: "Toggle Essential Bottom Panel",
        availability: CommandAvailability::Active,
        placement: NativePlacement::Settings,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-228",
        command_id: "Workspace.ToggleBottomPanelTab.shortcuts-view-controls",
        label: "Toggle View Controls Bottom Panel",
        availability: CommandAvailability::Active,
        placement: NativePlacement::Settings,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-224",
        command_id: "Workspace.ToggleBottomPanel.Shortcuts",
        label: "Show Keybindings Dialog",
        availability: CommandAvailability::Active,
        placement: NativePlacement::Settings,
        owner: "comfy-parity-settings-localization-ui",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-settings-localization-ui",
        },
        native_action: Some(NativeAction::ShowKeybindings),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-229",
        command_id: "Workspace.ToggleFocusMode",
        label: "Toggle Focus Mode",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-230",
        command_id: "Workspace.ToggleSidebarTab.apps",
        label: "Toggle Apps Sidebar",
        availability: CommandAvailability::Active,
        placement: NativePlacement::AssetBrowser,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-assets-editors-viewers",
        },
        native_action: None,
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-231",
        command_id: "Workspace.ToggleSidebarTab.assets",
        label: "Toggle Assets Sidebar",
        availability: CommandAvailability::Active,
        placement: NativePlacement::AssetBrowser,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-assets-editors-viewers",
        },
        native_action: Some(NativeAction::ToggleAssetsSidebar),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-232",
        command_id: "Workspace.ToggleSidebarTab.model-library",
        label: "Toggle Model Library Sidebar",
        availability: CommandAvailability::Active,
        placement: NativePlacement::AssetBrowser,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-assets-editors-viewers",
        },
        native_action: Some(NativeAction::ToggleModelLibrarySidebar),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-233",
        command_id: "Workspace.ToggleSidebarTab.node-library",
        label: "Toggle Node Library Sidebar",
        availability: CommandAvailability::Active,
        placement: NativePlacement::AssetBrowser,
        owner: "comfy-parity-assets-editors-viewers",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-assets-editors-viewers",
        },
        native_action: Some(NativeAction::ToggleNodeLibrarySidebar),
    },
    GeneratedCommandCatalogRow {
        feature_id: "COMFY-CLOUD-234",
        command_id: "Workspace.ToggleSidebarTab.workflows",
        label: "Toggle Workflows Sidebar",
        availability: CommandAvailability::Active,
        placement: NativePlacement::WorkspaceShell,
        owner: "comfy-parity-workflow-experience",
        status: CommandNativeStatus::LaterOwned {
            owner: "comfy-parity-workflow-experience",
        },
        native_action: Some(NativeAction::ToggleWorkflowsSidebar),
    },
];
