#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum GeneratedFrontendExtensionDispositionKind {
    DeclarativeRustWasm,
    LegacyIdentifierMapping,
    LosslessPlaceholder,
    DocumentedOnly,
    DeliberateDefer,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct GeneratedFrontendExtensionDisposition {
    pub feature_id: &'static str,
    pub entry_kind: &'static str,
    pub name: &'static str,
    pub behavior: &'static str,
    pub availability: &'static str,
    pub source_file: &'static str,
    pub evidence_level: &'static str,
    pub classification: GeneratedFrontendExtensionDispositionKind,
    pub native_surface: Option<&'static str>,
    pub replacement_owner: &'static str,
    pub reason: &'static str,
}

pub const GENERATED_FRONTEND_EXTENSION_DISPOSITIONS: &[GeneratedFrontendExtensionDisposition] = &[
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-037",
        entry_kind: "interface member",
        name: "name",
        behavior: "Unique extension name; duplicate or empty registration throws",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("plugin-manifest-identifier"),
        replacement_owner: "comfy-parity-extension-host-plugin-adapter",
        reason: "The signed plugin manifest identifier replaces the mutable JavaScript registration name.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-038",
        entry_kind: "interface member",
        name: "commands",
        behavior: "Register extension commands with source attribution",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("command"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed declarative command metadata maps to the canonical native command registry without executable script callbacks.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-039",
        entry_kind: "interface member",
        name: "keybindings",
        behavior: "Register extension default keybindings",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("keybinding"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed keybinding metadata references an authorized native command and retains canonical key-context ownership.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-040",
        entry_kind: "interface member",
        name: "menuCommands",
        behavior: "Add command groups to menu paths",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("menu"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed menu metadata references plugin-owned native commands and cannot install an arbitrary callback.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-041",
        entry_kind: "interface member",
        name: "settings",
        behavior: "Register extension settings after server values load",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("setting"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed setting schemas project into the existing SettingsStore-backed UI without owning persistence.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-042",
        entry_kind: "interface member",
        name: "bottomPanelTabs",
        behavior: "Register extension bottom panel tabs and commands",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("bottom-panel"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed panel declarations project into the existing workspace panel registry without executable web content.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-043",
        entry_kind: "interface member",
        name: "aboutPageBadges",
        behavior: "Contribute About page badges",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("about-badge"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed badge state is bounded declarative GPUI data.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-044",
        entry_kind: "interface member",
        name: "topbarBadges",
        behavior: "Contribute topbar badges",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("topbar-badge"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed badge state is bounded declarative GPUI data.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-045",
        entry_kind: "interface member",
        name: "actionBarButtons",
        behavior: "Contribute actionbar buttons",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("action-bar-button"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed button metadata may reference only an authorized native command.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-046",
        entry_kind: "interface member",
        name: "init",
        behavior: "Initialize after canvas creation and before node registration",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LosslessPlaceholder,
        native_surface: None,
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Imperative initialization callbacks cannot execute; their identity and payload remain available for replacement.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-047",
        entry_kind: "interface member",
        name: "setup",
        behavior: "Run after standard nodes and drop handlers are installed",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LosslessPlaceholder,
        native_surface: None,
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Imperative setup callbacks cannot execute; their identity and payload remain available for replacement.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-048",
        entry_kind: "interface member",
        name: "addCustomNodeDefs",
        behavior: "Mutate/add backend node definitions before registration",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("plugin-node-descriptor"),
        replacement_owner: "comfy-parity-extension-host-plugin-adapter",
        reason: "Signed PluginNode descriptors replace mutation of backend node definitions.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-049",
        entry_kind: "interface member",
        name: "getCustomWidgets",
        behavior: "Provide sync or async custom widget constructors",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("node-widget"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Typed declarative widget state replaces JavaScript widget constructors.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-050",
        entry_kind: "interface member",
        name: "getSelectionToolboxCommands",
        behavior: "Contribute selection toolbox commands",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("selection-toolbox"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed entries map to canonical graph actions through the existing graph dispatch owner.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-051",
        entry_kind: "interface member",
        name: "getCanvasMenuItems",
        behavior: "Contribute canvas context menu items and separators",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("canvas-menu"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed entries map to canonical graph actions through the existing graph dispatch owner.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-052",
        entry_kind: "interface member",
        name: "getNodeMenuItems",
        behavior: "Contribute node context menu items and separators",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeclarativeRustWasm,
        native_surface: Some("node-menu"),
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Signed entries map to canonical graph actions through the existing graph dispatch owner.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-053",
        entry_kind: "interface member",
        name: "beforeRegisterNodeDef",
        behavior: "Modify generated node class before LiteGraph registration",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("plugin-node-descriptor"),
        replacement_owner: "comfy-parity-extension-host-plugin-adapter",
        reason: "Signed immutable PluginNode descriptors replace generated class mutation.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-054",
        entry_kind: "interface member",
        name: "beforeRegisterVueAppNodeDefs",
        behavior: "Mutate node definitions before Vue store indexing",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("plugin-node-descriptor"),
        replacement_owner: "comfy-parity-extension-host-plugin-adapter",
        reason: "Signed immutable PluginNode descriptors replace Vue-store definition mutation.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-055",
        entry_kind: "interface member",
        name: "registerCustomNodes",
        behavior: "Register frontend-only LiteGraph nodes after backend nodes",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("plugin-node-descriptor"),
        replacement_owner: "comfy-parity-extension-host-plugin-adapter",
        reason: "Verified native Rust/WASM node registrations replace frontend-only LiteGraph classes.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-056",
        entry_kind: "interface member",
        name: "loadedGraphNode",
        behavior: "Patch each node after workflow configuration",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LosslessPlaceholder,
        native_surface: None,
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Per-instance post-load JavaScript patching is not executable in native GPUI.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-057",
        entry_kind: "interface member",
        name: "nodeCreated",
        behavior: "Run after a node instance is created",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LosslessPlaceholder,
        native_surface: None,
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Per-instance creation callbacks are not executable in native GPUI.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-058",
        entry_kind: "interface member",
        name: "beforeConfigureGraph",
        behavior: "Mutate workflow JSON and append missing-node data before configure",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LosslessPlaceholder,
        native_surface: None,
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Arbitrary pre-configuration workflow mutation is rejected; original workflow bytes remain authoritative.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-059",
        entry_kind: "interface member",
        name: "afterConfigureGraph",
        behavior: "Run after graph configure with missing-node data",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LosslessPlaceholder,
        native_surface: None,
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Arbitrary post-configuration callbacks are not executable in native GPUI.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-060",
        entry_kind: "interface member",
        name: "onAuthUserResolved",
        behavior: "Receive latest anonymized auth user and future changes",
        availability: "experimental",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeliberateDefer,
        native_surface: None,
        replacement_owner: "comfy-parity-auth-cloud-telemetry",
        reason: "Profile-scoped anonymized account events remain disabled until the native provider UI task exposes a typed event contract.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-061",
        entry_kind: "interface member",
        name: "onAuthTokenRefreshed",
        behavior: "Receive auth token refresh notification",
        availability: "experimental",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LosslessPlaceholder,
        native_surface: None,
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Raw authentication tokens are never exposed to plugins or UI contributions.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-062",
        entry_kind: "interface member",
        name: "onAuthUserLogout",
        behavior: "Receive logout notification",
        availability: "experimental",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::DeliberateDefer,
        native_surface: None,
        replacement_owner: "comfy-parity-auth-cloud-telemetry",
        reason: "Profile-scoped logout events remain disabled until the native provider UI task exposes a typed event contract.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-063",
        entry_kind: "interface member",
        name: "onNodeOutputsUpdated",
        behavior: "Receive node output map replacement",
        availability: "active",
        source_file: "src/types/comfy.ts; src/services/extensionService.ts",
        evidence_level: "test-backed",
        classification: GeneratedFrontendExtensionDispositionKind::LosslessPlaceholder,
        native_surface: None,
        replacement_owner: "comfy-parity-frontend-extension-compatibility",
        reason: "Global output-map callbacks are not executable; invocation-scoped declarative UI state remains available through the WIT API.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-005",
        entry_kind: "core extension module",
        name: "clipspace",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/clipspace.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:image-clipboard"),
        replacement_owner: "comfy-parity-image-mask-content",
        reason: "Native image and mask content replaces the web clipspace module.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-006",
        entry_kind: "core extension module",
        name: "contextMenuFilter",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/contextMenuFilter.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:context-menu-filter"),
        replacement_owner: "comfy-parity-graph-context-menu-surfaces",
        reason: "The canonical native graph context registry replaces the LiteGraph filter.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-007",
        entry_kind: "core extension module",
        name: "createBoundingBoxes",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/createBoundingBoxes.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:bounding-boxes"),
        replacement_owner: "comfy-parity-image-mask-content",
        reason: "Native bounding-box content replaces the JavaScript module.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-008",
        entry_kind: "core extension module",
        name: "customWidgets",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/customWidgets.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:typed-widgets"),
        replacement_owner: "comfy-parity-assets-editors-viewers",
        reason: "Typed GPUI node widgets replace JavaScript constructors.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-009",
        entry_kind: "core extension module",
        name: "dynamicPrompts",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/dynamicPrompts.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:dynamic-prompts"),
        replacement_owner: "comfy-parity-workflow-experience",
        reason: "Native workflow editing owns dynamic prompt behavior.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-010",
        entry_kind: "core extension module",
        name: "editAttention",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/editAttention.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:attention-editor"),
        replacement_owner: "comfy-parity-workflow-experience",
        reason: "Native workflow text editing owns attention syntax behavior.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-011",
        entry_kind: "core extension module",
        name: "electronAdapter",
        behavior: "Imported by src/extensions/core/index.ts under gate platform-specific",
        availability: "platform-specific",
        source_file: "src/extensions/core/electronAdapter.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:desktop-platform"),
        replacement_owner: "comfy-parity-desktop-native-ui",
        reason: "The native desktop platform adapter replaces Electron-specific behavior.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-012",
        entry_kind: "core extension module",
        name: "groupNode",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/groupNode.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:group-node"),
        replacement_owner: "comfy-parity-graph-context-menu-surfaces",
        reason: "The canonical graph domain owns grouping without a frontend-only node class.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-013",
        entry_kind: "core extension module",
        name: "groupOptions",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/groupOptions.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:group-options"),
        replacement_owner: "comfy-parity-graph-context-menu-surfaces",
        reason: "The canonical graph context dispatcher owns group actions.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-014",
        entry_kind: "core extension module",
        name: "imageCompare",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/imageCompare.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:image-compare"),
        replacement_owner: "comfy-parity-image-mask-content",
        reason: "Native image content owns comparison rendering.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-015",
        entry_kind: "core extension module",
        name: "imageCrop",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/imageCrop.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:image-crop"),
        replacement_owner: "comfy-parity-image-mask-content",
        reason: "Native image content owns crop operations.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-016",
        entry_kind: "core extension module",
        name: "load3dLazy",
        behavior: "Imported by src/extensions/core/index.ts under gate conditional",
        availability: "conditional",
        source_file: "src/extensions/core/load3dLazy.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:three-d-loader"),
        replacement_owner: "comfy-parity-three-d-latent-content",
        reason: "Native 3D content replaces lazy web loading.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-017",
        entry_kind: "core extension module",
        name: "maskeditor",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/maskeditor.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:mask-editor"),
        replacement_owner: "comfy-parity-image-mask-content",
        reason: "Native mask content replaces the web editor.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-018",
        entry_kind: "core extension module",
        name: "nodeTemplates",
        behavior: "Imported by src/extensions/core/index.ts under gate conditional",
        availability: "conditional",
        source_file: "src/extensions/core/nodeTemplates.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:node-templates"),
        replacement_owner: "comfy-parity-workflow-experience",
        reason: "Native workflow templates replace the web module.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-019",
        entry_kind: "core extension module",
        name: "noteNode",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/noteNode.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:note-content"),
        replacement_owner: "comfy-parity-assets-editors-viewers",
        reason: "Typed native structured content replaces the frontend-only note node.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-020",
        entry_kind: "core extension module",
        name: "painter",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/painter.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:painter"),
        replacement_owner: "comfy-parity-image-mask-content",
        reason: "Native paint and mask surfaces replace canvas scripting.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-021",
        entry_kind: "core extension module",
        name: "previewAny",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/previewAny.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:output-inspector"),
        replacement_owner: "comfy-parity-assets-editors-viewers",
        reason: "The native typed content registry replaces previewAny.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-022",
        entry_kind: "core extension module",
        name: "saveText",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/saveText.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:structured-text"),
        replacement_owner: "comfy-parity-three-d-latent-content",
        reason: "Native structured output content replaces saveText.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-023",
        entry_kind: "core extension module",
        name: "rerouteNode",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/rerouteNode.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:reroute"),
        replacement_owner: "comfy-parity-graph-context-menu-surfaces",
        reason: "The canonical graph domain owns reroutes.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-024",
        entry_kind: "core extension module",
        name: "saveImageExtraOutput",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/saveImageExtraOutput.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:image-output"),
        replacement_owner: "comfy-parity-image-mask-content",
        reason: "Native output publication and image content replace extra web output handling.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-025",
        entry_kind: "core extension module",
        name: "selectionBorder",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/selectionBorder.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:selection-border"),
        replacement_owner: "comfy-parity-graph-context-menu-surfaces",
        reason: "Native GPUI graph selection replaces canvas drawing hooks.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-026",
        entry_kind: "core extension module",
        name: "simpleTouchSupport",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/simpleTouchSupport.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:pointer-input"),
        replacement_owner: "comfy-parity-desktop-native-ui",
        reason: "GPUI pointer handling replaces browser touch shims.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-027",
        entry_kind: "core extension module",
        name: "slotDefaults",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/slotDefaults.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:slot-defaults"),
        replacement_owner: "comfy-parity-assets-editors-viewers",
        reason: "Typed node descriptors and editors own slot defaults.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-028",
        entry_kind: "core extension module",
        name: "uploadAudio",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/uploadAudio.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:audio-import"),
        replacement_owner: "comfy-parity-audio-video-content",
        reason: "Native audio import replaces the web upload module.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-029",
        entry_kind: "core extension module",
        name: "uploadImage",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/uploadImage.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:image-import"),
        replacement_owner: "comfy-parity-image-mask-content",
        reason: "Native asset and image services replace the web upload module.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-030",
        entry_kind: "core extension module",
        name: "webcamCapture",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/webcamCapture.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:camera-import"),
        replacement_owner: "comfy-parity-image-mask-content",
        reason: "A permission-gated native media adapter replaces browser webcam capture.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-031",
        entry_kind: "core extension module",
        name: "widgetInputs",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/widgetInputs.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:widget-inputs"),
        replacement_owner: "comfy-parity-assets-editors-viewers",
        reason: "Typed node ports and GPUI widgets replace widget-input scripting.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-032",
        entry_kind: "core extension module",
        name: "cloudRemoteConfig",
        behavior: "Imported by src/extensions/core/index.ts under gate cloud/paid",
        availability: "cloud/paid",
        source_file: "src/extensions/core/cloudRemoteConfig.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:provider-configuration"),
        replacement_owner: "comfy-parity-auth-cloud-telemetry",
        reason: "Profile-scoped provider configuration replaces remote web config.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-033",
        entry_kind: "core extension module",
        name: "cloudBadges",
        behavior: "Imported by src/extensions/core/index.ts under gate cloud/paid",
        availability: "cloud/paid",
        source_file: "src/extensions/core/cloudBadges.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:provider-badges"),
        replacement_owner: "comfy-parity-auth-cloud-telemetry",
        reason: "Profile-scoped provider state supplies native badges.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-034",
        entry_kind: "core extension module",
        name: "cloudSessionCookie",
        behavior: "Imported by src/extensions/core/index.ts under gate cloud/paid",
        availability: "cloud/paid",
        source_file: "src/extensions/core/cloudSessionCookie.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:provider-session"),
        replacement_owner: "comfy-parity-auth-cloud-telemetry",
        reason: "Opaque native provider sessions replace browser cookies.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-035",
        entry_kind: "core extension module",
        name: "cloudFeedbackTopbarButton",
        behavior: "Imported by src/extensions/core/index.ts under gate cloud/paid",
        availability: "cloud/paid",
        source_file: "src/extensions/core/cloudFeedbackTopbarButton.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:provider-feedback"),
        replacement_owner: "comfy-parity-auth-cloud-telemetry",
        reason: "Permission-gated native feedback surfaces replace the web topbar module.",
    },
    GeneratedFrontendExtensionDisposition {
        feature_id: "COMFY-FRONTEXT-EXT-036",
        entry_kind: "core extension module",
        name: "nightlyBadges",
        behavior: "Imported by src/extensions/core/index.ts under gate active",
        availability: "active",
        source_file: "src/extensions/core/nightlyBadges.ts",
        evidence_level: "code-inferred",
        classification: GeneratedFrontendExtensionDispositionKind::LegacyIdentifierMapping,
        native_surface: Some("native-core:release-badge"),
        replacement_owner: "comfy-parity-settings-localization-ui",
        reason: "Native release-channel settings supply badge state.",
    },
];
