// Generated by .agents/specs/collaborative-workspace/scripts/generate-kind-registry.py.
// Do not edit by hand.

use crate::head::PersistenceClass;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReplacementBehavior {
    RetainAll,
    AuthorAndKind,
    AuthorKindAndDiscriminator,
    DiscardAfterDelivery,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PrivacyGates(u8);

impl PrivacyGates {
    pub const COMMUNITY: Self = Self(0);
    pub const AUTHOR_ONLY: Self = Self(1 << 0);
    pub const RESULT_GATED: Self = Self(1 << 1);
    pub const RECIPIENT_GATED: Self = Self(1 << 2);
    pub const AUTHOR_OR_SHARED: Self = Self(1 << 3);

    pub const fn union(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }

    pub const fn contains(self, gate: Self) -> bool {
        gate.0 != 0 && self.0 & gate.0 == gate.0
    }

    pub const fn is_community_visible(self) -> bool {
        self.0 == 0
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum KindStatus {
    Registered,
    DefinedUnused,
    InternalNotRelayEvent,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct KindMetadata {
    pub name: &'static str,
    pub value: u32,
    pub protocols: &'static [&'static str],
    pub persistence: PersistenceClass,
    pub replacement: ReplacementBehavior,
    pub privacy: PrivacyGates,
    pub status: KindStatus,
}

pub const EPHEMERAL_KIND_MAX: u32 = 29999;
pub const EPHEMERAL_KIND_MIN: u32 = 20000;
pub const PARAM_REPLACEABLE_KIND_MAX: u32 = 39999;
pub const PARAM_REPLACEABLE_KIND_MIN: u32 = 30000;

pub const KIND_AGENT_ENGRAM: u32 = 30174;
pub const KIND_AGENT_OBSERVER_FRAME: u32 = 24200;
pub const KIND_AGENT_PROFILE: u32 = 10100;
pub const KIND_AGENT_TURN_METRIC: u32 = 44200;
pub const KIND_APPROVAL_DENY: u32 = 46031;
pub const KIND_APPROVAL_GRANT: u32 = 46030;
pub const KIND_AUDIT_ENTRY: u32 = 48001;
pub const KIND_AUTH: u32 = 22242;
pub const KIND_BLOSSOM_AUTH: u32 = 24242;
pub const KIND_BOOKMARK_LIST: u32 = 10003;
pub const KIND_BOOKMARK_SET: u32 = 30003;
pub const KIND_CANVAS: u32 = 40100;
pub const KIND_CHANNEL_METADATA: u32 = 41;
pub const KIND_CHANNEL_SUMMARY: u32 = 40901;
pub const KIND_CONTACT_LIST: u32 = 3;
pub const KIND_DELETION: u32 = 5;
pub const KIND_DM_ADD_MEMBER: u32 = 41011;
pub const KIND_DM_CREATED: u32 = 41001;
pub const KIND_DM_HIDE: u32 = 41012;
pub const KIND_DM_OPEN: u32 = 41010;
pub const KIND_DM_VISIBILITY: u32 = 30622;
pub const KIND_EMOJI_LIST: u32 = 10030;
pub const KIND_EMOJI_SET: u32 = 30030;
pub const KIND_EVENT_REMINDER: u32 = 30300;
pub const KIND_FILE_METADATA: u32 = 1063;
pub const KIND_FOLLOW_SET: u32 = 30000;
pub const KIND_FORUM_COMMENT: u32 = 45003;
pub const KIND_FORUM_POST: u32 = 45001;
pub const KIND_FORUM_VOTE: u32 = 45002;
pub const KIND_GIFT_WRAP: u32 = 1059;
pub const KIND_GIT_ISSUE: u32 = 1621;
pub const KIND_GIT_PATCH: u32 = 1617;
pub const KIND_GIT_PR_UPDATE: u32 = 1619;
pub const KIND_GIT_PULL_REQUEST: u32 = 1618;
pub const KIND_GIT_REPO_ANNOUNCEMENT: u32 = 30617;
pub const KIND_GIT_REPO_STATE: u32 = 30618;
pub const KIND_GIT_STATUS_CLOSED: u32 = 1632;
pub const KIND_GIT_STATUS_DRAFT: u32 = 1633;
pub const KIND_GIT_STATUS_MERGED: u32 = 1631;
pub const KIND_GIT_STATUS_OPEN: u32 = 1630;
pub const KIND_HTTP_AUTH: u32 = 27235;
pub const KIND_HUDDLE_ENDED: u32 = 48103;
pub const KIND_HUDDLE_GUIDELINES: u32 = 48106;
pub const KIND_HUDDLE_PARTICIPANT_JOINED: u32 = 48101;
pub const KIND_HUDDLE_PARTICIPANT_LEFT: u32 = 48102;
pub const KIND_HUDDLE_REACTION: u32 = 24810;
pub const KIND_HUDDLE_STARTED: u32 = 48100;
pub const KIND_IA_ARCHIVED: u32 = 8002;
pub const KIND_IA_ARCHIVED_LIST: u32 = 13535;
pub const KIND_IA_ARCHIVE_REQUEST: u32 = 9035;
pub const KIND_IA_UNARCHIVED: u32 = 8003;
pub const KIND_IA_UNARCHIVE_REQUEST: u32 = 9036;
pub const KIND_JOB_ACCEPTED: u32 = 43002;
pub const KIND_JOB_CANCEL: u32 = 43005;
pub const KIND_JOB_ERROR: u32 = 43006;
pub const KIND_JOB_PROGRESS: u32 = 43003;
pub const KIND_JOB_REQUEST: u32 = 43001;
pub const KIND_JOB_RESULT: u32 = 43004;
pub const KIND_LONG_FORM: u32 = 30023;
pub const KIND_MANAGED_AGENT: u32 = 30177;
pub const KIND_MEDIA_UPLOAD: u32 = 49001;
pub const KIND_MEMBER_ADDED_NOTIFICATION: u32 = 44100;
pub const KIND_MEMBER_REMOVED_NOTIFICATION: u32 = 44101;
pub const KIND_MODERATION_BAN: u32 = 9040;
pub const KIND_MODERATION_RESOLVE_REPORT: u32 = 9044;
pub const KIND_MODERATION_TIMEOUT: u32 = 9042;
pub const KIND_MODERATION_UNBAN: u32 = 9041;
pub const KIND_MODERATION_UNTIMEOUT: u32 = 9043;
pub const KIND_MUTE_LIST: u32 = 10000;
pub const KIND_NIP29_CREATE_GROUP: u32 = 9007;
pub const KIND_NIP29_CREATE_INVITE: u32 = 9009;
pub const KIND_NIP29_DELETE_EVENT: u32 = 9005;
pub const KIND_NIP29_DELETE_GROUP: u32 = 9008;
pub const KIND_NIP29_EDIT_METADATA: u32 = 9002;
pub const KIND_NIP29_GROUP_ADMINS: u32 = 39001;
pub const KIND_NIP29_GROUP_MEMBERS: u32 = 39002;
pub const KIND_NIP29_GROUP_METADATA: u32 = 39000;
pub const KIND_NIP29_GROUP_ROLES: u32 = 39003;
pub const KIND_NIP29_JOIN_REQUEST: u32 = 9021;
pub const KIND_NIP29_LEAVE_REQUEST: u32 = 9022;
pub const KIND_NIP29_PUT_USER: u32 = 9000;
pub const KIND_NIP29_REMOVE_USER: u32 = 9001;
pub const KIND_NIP43_LEAVE_REQUEST: u32 = 28936;
pub const KIND_NIP43_MEMBERSHIP_LIST: u32 = 13534;
pub const KIND_NIP43_MEMBER_ADDED: u32 = 8000;
pub const KIND_NIP43_MEMBER_REMOVED: u32 = 8001;
pub const KIND_NIP65_RELAY_LIST_METADATA: u32 = 10002;
pub const KIND_NOSTR_IDENTITY_BINDING: u32 = 24243;
pub const KIND_PAIRING: u32 = 24134;
pub const KIND_PERSONA: u32 = 30175;
pub const KIND_PIN_LIST: u32 = 10001;
pub const KIND_PRESENCE_SNAPSHOT: u32 = 40902;
pub const KIND_PRESENCE_UPDATE: u32 = 20001;
pub const KIND_PRIVATE_MANAGED_AGENT: u32 = 30179;
pub const KIND_PRODUCT_FEEDBACK: u32 = 42000;
pub const KIND_PROFILE: u32 = 0;
pub const KIND_PROJECT: u32 = 30621;
pub const KIND_PUSH_LEASE: u32 = 30350;
pub const KIND_REACTION: u32 = 7;
pub const KIND_READ_STATE: u32 = 30078;
pub const KIND_REPORT: u32 = 1984;
pub const KIND_STREAM_MESSAGE: u32 = 9;
pub const KIND_STREAM_MESSAGE_BOOKMARKED: u32 = 40005;
pub const KIND_STREAM_MESSAGE_DIFF: u32 = 40008;
pub const KIND_STREAM_MESSAGE_EDIT: u32 = 40003;
pub const KIND_STREAM_MESSAGE_PINNED: u32 = 40004;
pub const KIND_STREAM_MESSAGE_SCHEDULED: u32 = 40006;
pub const KIND_STREAM_MESSAGE_V2: u32 = 40002;
pub const KIND_STREAM_REMINDER: u32 = 40007;
pub const KIND_SYSTEM_MESSAGE: u32 = 40099;
pub const KIND_TEAM: u32 = 30176;
pub const KIND_TEAM_CATALOG: u32 = 30178;
pub const KIND_TEXT_NOTE: u32 = 1;
pub const KIND_THREAD_SUMMARY: u32 = 39005;
pub const KIND_TYPING_INDICATOR: u32 = 20002;
pub const KIND_USER_STATUS: u32 = 30315;
pub const KIND_WINDOW_BOUNDS: u32 = 39006;
pub const KIND_WORKFLOW_APPROVAL_DENIED: u32 = 46012;
pub const KIND_WORKFLOW_APPROVAL_GRANTED: u32 = 46011;
pub const KIND_WORKFLOW_APPROVAL_REQUESTED: u32 = 46010;
pub const KIND_WORKFLOW_CANCELLED: u32 = 46007;
pub const KIND_WORKFLOW_COMPLETED: u32 = 46005;
pub const KIND_WORKFLOW_DEF: u32 = 30620;
pub const KIND_WORKFLOW_FAILED: u32 = 46006;
pub const KIND_WORKFLOW_STEP_COMPLETED: u32 = 46003;
pub const KIND_WORKFLOW_STEP_FAILED: u32 = 46004;
pub const KIND_WORKFLOW_STEP_STARTED: u32 = 46002;
pub const KIND_WORKFLOW_TRIGGER: u32 = 46020;
pub const KIND_WORKFLOW_TRIGGERED: u32 = 46001;
pub const RELAY_ADMIN_ADD_MEMBER: u32 = 9030;
pub const RELAY_ADMIN_CHANGE_ROLE: u32 = 9032;
pub const RELAY_ADMIN_REMOVE_MEMBER: u32 = 9031;
pub const RELAY_ADMIN_SET_WORKSPACE_PROFILE: u32 = 9033;

pub const EVENT_KIND_COUNT: usize = 133;

pub static EVENT_KINDS: [KindMetadata; EVENT_KIND_COUNT] = [
    KindMetadata {
        name: "KIND_PROFILE",
        value: 0,
        protocols: &["NIP-01"],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_TEXT_NOTE",
        value: 1,
        protocols: &["NIP-01"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_CONTACT_LIST",
        value: 3,
        protocols: &["NIP-02"],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_DELETION",
        value: 5,
        protocols: &["NIP-09"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_REACTION",
        value: 7,
        protocols: &["NIP-25"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_STREAM_MESSAGE",
        value: 9,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_CHANNEL_METADATA",
        value: 41,
        protocols: &["NIP-01"],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::DefinedUnused,
    },
    KindMetadata {
        name: "KIND_GIFT_WRAP",
        value: 1059,
        protocols: &["NIP-17"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::RECIPIENT_GATED,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_FILE_METADATA",
        value: 1063,
        protocols: &["NIP-94"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_GIT_PATCH",
        value: 1617,
        protocols: &["NIP-34"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_GIT_PULL_REQUEST",
        value: 1618,
        protocols: &["NIP-34"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_GIT_PR_UPDATE",
        value: 1619,
        protocols: &["NIP-34"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_GIT_ISSUE",
        value: 1621,
        protocols: &["NIP-34"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_GIT_STATUS_OPEN",
        value: 1630,
        protocols: &["NIP-34"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_GIT_STATUS_MERGED",
        value: 1631,
        protocols: &["NIP-34"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_GIT_STATUS_CLOSED",
        value: 1632,
        protocols: &["NIP-34"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_GIT_STATUS_DRAFT",
        value: 1633,
        protocols: &["NIP-34"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_REPORT",
        value: 1984,
        protocols: &["NIP-56"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP43_MEMBER_ADDED",
        value: 8000,
        protocols: &["NIP-43"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP43_MEMBER_REMOVED",
        value: 8001,
        protocols: &["NIP-43"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_IA_ARCHIVED",
        value: 8002,
        protocols: &["NIP-IA"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_IA_UNARCHIVED",
        value: 8003,
        protocols: &["NIP-IA"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_PUT_USER",
        value: 9000,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_REMOVE_USER",
        value: 9001,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_EDIT_METADATA",
        value: 9002,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_DELETE_EVENT",
        value: 9005,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_CREATE_GROUP",
        value: 9007,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_DELETE_GROUP",
        value: 9008,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_CREATE_INVITE",
        value: 9009,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_JOIN_REQUEST",
        value: 9021,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_LEAVE_REQUEST",
        value: 9022,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "RELAY_ADMIN_ADD_MEMBER",
        value: 9030,
        protocols: &["NIP-43"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "RELAY_ADMIN_REMOVE_MEMBER",
        value: 9031,
        protocols: &["NIP-43"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "RELAY_ADMIN_CHANGE_ROLE",
        value: 9032,
        protocols: &["NIP-43"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "RELAY_ADMIN_SET_WORKSPACE_PROFILE",
        value: 9033,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_IA_ARCHIVE_REQUEST",
        value: 9035,
        protocols: &["NIP-IA"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_IA_UNARCHIVE_REQUEST",
        value: 9036,
        protocols: &["NIP-IA"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_MODERATION_BAN",
        value: 9040,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_MODERATION_UNBAN",
        value: 9041,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_MODERATION_TIMEOUT",
        value: 9042,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_MODERATION_UNTIMEOUT",
        value: 9043,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_MODERATION_RESOLVE_REPORT",
        value: 9044,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_MUTE_LIST",
        value: 10000,
        protocols: &["NIP-51"],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_PIN_LIST",
        value: 10001,
        protocols: &["NIP-51"],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP65_RELAY_LIST_METADATA",
        value: 10002,
        protocols: &["NIP-65"],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_BOOKMARK_LIST",
        value: 10003,
        protocols: &["NIP-51"],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_EMOJI_LIST",
        value: 10030,
        protocols: &["NIP-51"],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_AGENT_PROFILE",
        value: 10100,
        protocols: &[],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP43_MEMBERSHIP_LIST",
        value: 13534,
        protocols: &["NIP-43"],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_IA_ARCHIVED_LIST",
        value: 13535,
        protocols: &["NIP-IA"],
        persistence: PersistenceClass::Replaceable,
        replacement: ReplacementBehavior::AuthorAndKind,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_PRESENCE_UPDATE",
        value: 20001,
        protocols: &[],
        persistence: PersistenceClass::Ephemeral,
        replacement: ReplacementBehavior::DiscardAfterDelivery,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_TYPING_INDICATOR",
        value: 20002,
        protocols: &[],
        persistence: PersistenceClass::Ephemeral,
        replacement: ReplacementBehavior::DiscardAfterDelivery,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_AUTH",
        value: 22242,
        protocols: &["NIP-42"],
        persistence: PersistenceClass::Ephemeral,
        replacement: ReplacementBehavior::DiscardAfterDelivery,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_PAIRING",
        value: 24134,
        protocols: &["NIP-AB"],
        persistence: PersistenceClass::Ephemeral,
        replacement: ReplacementBehavior::DiscardAfterDelivery,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_AGENT_OBSERVER_FRAME",
        value: 24200,
        protocols: &[],
        persistence: PersistenceClass::Ephemeral,
        replacement: ReplacementBehavior::DiscardAfterDelivery,
        privacy: PrivacyGates::RECIPIENT_GATED,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_BLOSSOM_AUTH",
        value: 24242,
        protocols: &["BUD-01"],
        persistence: PersistenceClass::Ephemeral,
        replacement: ReplacementBehavior::DiscardAfterDelivery,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NOSTR_IDENTITY_BINDING",
        value: 24243,
        protocols: &[],
        persistence: PersistenceClass::Ephemeral,
        replacement: ReplacementBehavior::DiscardAfterDelivery,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_HUDDLE_REACTION",
        value: 24810,
        protocols: &[],
        persistence: PersistenceClass::Ephemeral,
        replacement: ReplacementBehavior::DiscardAfterDelivery,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_HTTP_AUTH",
        value: 27235,
        protocols: &["NIP-98"],
        persistence: PersistenceClass::Ephemeral,
        replacement: ReplacementBehavior::DiscardAfterDelivery,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP43_LEAVE_REQUEST",
        value: 28936,
        protocols: &["NIP-43"],
        persistence: PersistenceClass::Ephemeral,
        replacement: ReplacementBehavior::DiscardAfterDelivery,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_FOLLOW_SET",
        value: 30000,
        protocols: &["NIP-51"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_BOOKMARK_SET",
        value: 30003,
        protocols: &["NIP-51"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_LONG_FORM",
        value: 30023,
        protocols: &["NIP-23", "NIP-33"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_EMOJI_SET",
        value: 30030,
        protocols: &["NIP-30", "NIP-33", "NIP-51"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_READ_STATE",
        value: 30078,
        protocols: &["NIP-33", "NIP-44", "NIP-78", "NIP-RS"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_AGENT_ENGRAM",
        value: 30174,
        protocols: &["NIP-AE"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_PERSONA",
        value: 30175,
        protocols: &["NIP-AP"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::AUTHOR_OR_SHARED,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_TEAM",
        value: 30176,
        protocols: &["NIP-AP"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_MANAGED_AGENT",
        value: 30177,
        protocols: &["NIP-AP", "NIP-OA"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_TEAM_CATALOG",
        value: 30178,
        protocols: &["NIP-33", "NIP-AP"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::AUTHOR_OR_SHARED,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_PRIVATE_MANAGED_AGENT",
        value: 30179,
        protocols: &["NIP-44", "NIP-PMA"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::AUTHOR_ONLY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_EVENT_REMINDER",
        value: 30300,
        protocols: &["NIP-44", "NIP-ER"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::AUTHOR_ONLY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_USER_STATUS",
        value: 30315,
        protocols: &["NIP-33", "NIP-38"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_PUSH_LEASE",
        value: 30350,
        protocols: &["NIP-44", "NIP-PL"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::AUTHOR_ONLY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_GIT_REPO_ANNOUNCEMENT",
        value: 30617,
        protocols: &["NIP-34"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_GIT_REPO_STATE",
        value: 30618,
        protocols: &["NIP-34"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_DEF",
        value: 30620,
        protocols: &[],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_PROJECT",
        value: 30621,
        protocols: &["NIP-MP"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_DM_VISIBILITY",
        value: 30622,
        protocols: &["NIP-DV"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::RESULT_GATED.union(PrivacyGates::RECIPIENT_GATED),
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_GROUP_METADATA",
        value: 39000,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_GROUP_ADMINS",
        value: 39001,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_GROUP_MEMBERS",
        value: 39002,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_NIP29_GROUP_ROLES",
        value: 39003,
        protocols: &["NIP-29"],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_THREAD_SUMMARY",
        value: 39005,
        protocols: &[],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WINDOW_BOUNDS",
        value: 39006,
        protocols: &[],
        persistence: PersistenceClass::ParameterizedReplaceable,
        replacement: ReplacementBehavior::AuthorKindAndDiscriminator,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_STREAM_MESSAGE_V2",
        value: 40002,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_STREAM_MESSAGE_EDIT",
        value: 40003,
        protocols: &["NIP-51"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_STREAM_MESSAGE_PINNED",
        value: 40004,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_STREAM_MESSAGE_BOOKMARKED",
        value: 40005,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_STREAM_MESSAGE_SCHEDULED",
        value: 40006,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_STREAM_REMINDER",
        value: 40007,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_STREAM_MESSAGE_DIFF",
        value: 40008,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_SYSTEM_MESSAGE",
        value: 40099,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_CANVAS",
        value: 40100,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_CHANNEL_SUMMARY",
        value: 40901,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_PRESENCE_SNAPSHOT",
        value: 40902,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_DM_CREATED",
        value: 41001,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_DM_OPEN",
        value: 41010,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_DM_ADD_MEMBER",
        value: 41011,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_DM_HIDE",
        value: 41012,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_PRODUCT_FEEDBACK",
        value: 42000,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_JOB_REQUEST",
        value: 43001,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_JOB_ACCEPTED",
        value: 43002,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_JOB_PROGRESS",
        value: 43003,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_JOB_RESULT",
        value: 43004,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_JOB_CANCEL",
        value: 43005,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_JOB_ERROR",
        value: 43006,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_MEMBER_ADDED_NOTIFICATION",
        value: 44100,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::RECIPIENT_GATED,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_MEMBER_REMOVED_NOTIFICATION",
        value: 44101,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::RECIPIENT_GATED,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_AGENT_TURN_METRIC",
        value: 44200,
        protocols: &["NIP-42", "NIP-44", "NIP-AM"],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::RESULT_GATED.union(PrivacyGates::RECIPIENT_GATED),
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_FORUM_POST",
        value: 45001,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_FORUM_VOTE",
        value: 45002,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_FORUM_COMMENT",
        value: 45003,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_TRIGGERED",
        value: 46001,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_STEP_STARTED",
        value: 46002,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_STEP_COMPLETED",
        value: 46003,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_STEP_FAILED",
        value: 46004,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_COMPLETED",
        value: 46005,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_FAILED",
        value: 46006,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_CANCELLED",
        value: 46007,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_APPROVAL_REQUESTED",
        value: 46010,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_APPROVAL_GRANTED",
        value: 46011,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_APPROVAL_DENIED",
        value: 46012,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_WORKFLOW_TRIGGER",
        value: 46020,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_APPROVAL_GRANT",
        value: 46030,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_APPROVAL_DENY",
        value: 46031,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_AUDIT_ENTRY",
        value: 48001,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_HUDDLE_STARTED",
        value: 48100,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_HUDDLE_PARTICIPANT_JOINED",
        value: 48101,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_HUDDLE_PARTICIPANT_LEFT",
        value: 48102,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_HUDDLE_ENDED",
        value: 48103,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_HUDDLE_GUIDELINES",
        value: 48106,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::Registered,
    },
    KindMetadata {
        name: "KIND_MEDIA_UPLOAD",
        value: 49001,
        protocols: &[],
        persistence: PersistenceClass::Regular,
        replacement: ReplacementBehavior::RetainAll,
        privacy: PrivacyGates::COMMUNITY,
        status: KindStatus::InternalNotRelayEvent,
    },
];

pub fn metadata_for_kind(value: u32) -> Option<&'static KindMetadata> {
    EVENT_KINDS
        .binary_search_by_key(&value, |metadata| metadata.value)
        .ok()
        .and_then(|index| EVENT_KINDS.get(index))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_is_sorted_unique_and_complete() {
        assert_eq!(EVENT_KINDS.len(), 133);
        assert!(
            EVENT_KINDS
                .windows(2)
                .all(|pair| pair[0].value < pair[1].value)
        );
        assert_eq!(
            metadata_for_kind(KIND_PROFILE).map(|kind| kind.name),
            Some("KIND_PROFILE")
        );
        assert!(metadata_for_kind(u32::MAX).is_none());
    }

    #[test]
    fn boundary_kinds_have_expected_storage_and_replacement_rules() {
        assert_eq!(
            crate::head::persistence_class(EPHEMERAL_KIND_MIN as u16),
            PersistenceClass::Ephemeral
        );
        assert_eq!(
            crate::head::persistence_class(EPHEMERAL_KIND_MAX as u16),
            PersistenceClass::Ephemeral
        );
        assert_eq!(
            crate::head::persistence_class(PARAM_REPLACEABLE_KIND_MIN as u16),
            PersistenceClass::ParameterizedReplaceable
        );
        assert_eq!(
            crate::head::persistence_class(PARAM_REPLACEABLE_KIND_MAX as u16),
            PersistenceClass::ParameterizedReplaceable
        );
        assert_eq!(
            metadata_for_kind(KIND_MUTE_LIST).map(|kind| kind.replacement),
            Some(ReplacementBehavior::AuthorAndKind)
        );
    }

    #[test]
    fn privacy_gates_preserve_buzz_overlap() {
        let metric = metadata_for_kind(KIND_AGENT_TURN_METRIC).expect("metric kind");
        assert!(metric.privacy.contains(PrivacyGates::RESULT_GATED));
        assert!(metric.privacy.contains(PrivacyGates::RECIPIENT_GATED));
        let persona = metadata_for_kind(KIND_PERSONA).expect("persona kind");
        assert!(persona.privacy.contains(PrivacyGates::AUTHOR_OR_SHARED));
        assert!(
            metadata_for_kind(KIND_TEXT_NOTE)
                .expect("text kind")
                .privacy
                .is_community_visible()
        );
    }
}
