[package]
name = "comfy_sampler"
version = "0.1.0"
edition.workspace = true
publish = false
license = "GPL-3.0-or-later"
build = "build.rs"
[lints]
workspace = true
[lib]
path = "src/comfy_sampler.rs"
[dependencies]
comfy_model.workspace = true
comfy_tensor.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
[dev-dependencies]
serde_json.workspace = true
