&[
    ResolvedOperationContract {
        resolution_module: "accelerated_attention_kernel_01",
        operation_id: "COMFY-TENSOR-OP-B8796E1BECDE",
        baseline_overload_id: "COMFY-TENSOR-OP-B8796E1BECDE:blocked",
        baseline_fixture_sha256: "66cb0abef098d6a598cb9b0d809c2cabde6430a9f16195139c146e024dd8974b",
        overload_id: "zed.native.flash_attn_func.exact_cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"q\",\"type\":\"f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"k\",\"type\":\"f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"v\",\"type\":\"f32 tensor slice\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"causal\",\"type\":\"bool\"},{\"default\":0.0,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"dropout_p\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn flash_attn_func_with_context_exact_native(backend: &CpuBackend, shape: AttentionShape, q: &[f32], k: &[f32], v: &[f32], dropout_p: f32, causal: bool, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, AttentionKernelError>",
        mutation_rule: "out-of-place; q, k, and v remain immutable",
        alias_rule: "returns fresh owned storage that aliases no input",
        shape_rule: "q is BxNqxHxD, k is BxNkxHxD, v is BxNkxHxDv, and output is BxNqxHxDv; all dimensions are nonzero and checked",
        dtype_rule: "the deterministic exact native fallback accepts f32 inputs and rejects execution outside its typed device contract",
        accumulation_dtype: "f32 scores, softmax, and value accumulation",
        layout_rule: "contiguous logical NHD layout only",
        device_rule: "CPU exact native fallback; non-CPU execution requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "scaled dot product with max-subtracted softmax, zero dropout, and bottom-right aligned causal masking",
        tolerance: "absolute 0.000001 for checked f32 forward fixtures and 0.0003 for finite-difference gradients",
        determinism: "fixed loop order and no RNG when dropout_p is zero",
        cancellation_points: "before allocation and once per batch-head-query row; cancellation publishes no output",
        vjp_rule: "analytical softmax attention VJP for q, k, and v with the same mask and causal semantics",
        jvp_rule: "analytical softmax attention JVP for q, k, and v verified against finite differences and the VJP adjoint",
        owner_task_id: "comfy-parity-tensor-ops-accelerated-attention-kernel-comfy-tensor-op-1354ac34a777",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/accelerated_attention_kernel_01/flash_attn_func.json",
        evidence_fixture_sha256: "cd169741eda34c6761a8dc3ecd8b1aac6f75120b65351ebf60bb57801b9bb34a",
    },
    ResolvedOperationContract {
        resolution_module: "accelerated_attention_kernel_01",
        operation_id: "COMFY-TENSOR-OP-1354AC34A777",
        baseline_overload_id: "COMFY-TENSOR-OP-1354AC34A777:blocked",
        baseline_fixture_sha256: "681174e524fe4854593427c242254a6ce1c07fcafc2640a31e9f429fe77e6d56",
        overload_id: "zed.native.sageattn.exact_cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"q\",\"type\":\"f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"k\",\"type\":\"f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"v\",\"type\":\"f32 tensor slice\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"attn_mask\",\"type\":\"optional boolean or additive attention mask\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"is_causal\",\"type\":\"bool\"},{\"default\":\"HND\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"tensor_layout\",\"type\":\"AttentionLayout\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn sageattn_with_context_exact_native(backend: &CpuBackend, shape: AttentionShape, q: &[f32], k: &[f32], v: &[f32], attn_mask: Option<AttentionMask>, is_causal: bool, tensor_layout: AttentionLayout, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, AttentionKernelError>",
        mutation_rule: "out-of-place; q, k, v, and attn_mask remain immutable",
        alias_rule: "returns fresh owned storage that aliases no input or mask",
        shape_rule: "q is BxNqxHxD or BxHxNqxD, k is BxNkxHxD or BxHxNkxD, v uses Dv, masks use checked key, query-key, batch-query-key, or batch-head-query-key shapes, and output follows q layout with Dv",
        dtype_rule: "the deterministic exact native fallback accepts f32 inputs plus boolean or f32 additive masks",
        accumulation_dtype: "f32 scores, softmax, and value accumulation",
        layout_rule: "typed NHD and HND logical layouts are accepted and preserved",
        device_rule: "CPU exact native fallback; non-CPU execution requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "scaled dot product with max-subtracted softmax, broadcast mask application, and bottom-right aligned causal masking",
        tolerance: "absolute 0.000001 for checked f32 forward fixtures and 0.0003 for finite-difference gradients",
        determinism: "fixed loop order with no stochastic path",
        cancellation_points: "before allocation and once per batch-head-query row; cancellation publishes no output",
        vjp_rule: "analytical softmax attention VJP for q, k, and v with mask values treated as constants",
        jvp_rule: "analytical softmax attention JVP for q, k, and v verified against finite differences and the VJP adjoint",
        owner_task_id: "comfy-parity-tensor-ops-accelerated-attention-kernel-comfy-tensor-op-1354ac34a777",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/accelerated_attention_kernel_01/sageattn.json",
        evidence_fixture_sha256: "016f04a0a4fd26d0baa9e68c6016146a6abd4e4adaa4f7b7a7f6a5baacc38295",
    },
    ResolvedOperationContract {
        resolution_module: "accelerated_attention_kernel_01",
        operation_id: "COMFY-TENSOR-OP-5E24E0493F83",
        baseline_overload_id: "COMFY-TENSOR-OP-5E24E0493F83:blocked",
        baseline_fixture_sha256: "09152dc7b0d91e1b0b6e728742c50c5b30eadd4134f52e15190e43ada3444ef3",
        overload_id: "zed.native.sageattn3_blackwell.exact_cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"q\",\"type\":\"f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"k\",\"type\":\"f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"v\",\"type\":\"f32 tensor slice\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"is_causal\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn sageattn3_blackwell_with_context_exact_native(backend: &CpuBackend, shape: AttentionShape, q: &[f32], k: &[f32], v: &[f32], is_causal: bool, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, AttentionKernelError>",
        mutation_rule: "out-of-place; q, k, and v remain immutable",
        alias_rule: "returns fresh owned storage that aliases no input",
        shape_rule: "q is BxHxNqxD, k is BxHxNkxD, v is BxHxNkxDv, output is BxHxNqxDv, and all dimensions are nonzero and checked",
        dtype_rule: "the deterministic source-wrapper fallback accepts f32; certified Blackwell acceleration remains a separate adapter contract",
        accumulation_dtype: "f32 scores, softmax, and value accumulation",
        layout_rule: "contiguous logical HND layout only",
        device_rule: "CPU exact native source-wrapper fallback; Blackwell execution requires separate certification and other devices return typed unavailable here",
        numeric_rule: "scaled dot product with max-subtracted softmax and bottom-right aligned causal masking; no attention mask is accepted",
        tolerance: "absolute 0.000001 for checked f32 forward fixtures and 0.0003 for finite-difference gradients",
        determinism: "fixed loop order with no stochastic path",
        cancellation_points: "before allocation and once per batch-head-query row; cancellation publishes no output",
        vjp_rule: "analytical softmax attention VJP for q, k, and v with the same causal semantics",
        jvp_rule: "analytical softmax attention JVP for q, k, and v verified against finite differences and the VJP adjoint",
        owner_task_id: "comfy-parity-tensor-ops-accelerated-attention-kernel-comfy-tensor-op-1354ac34a777",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/accelerated_attention_kernel_01/sageattn3_blackwell.json",
        evidence_fixture_sha256: "374118bc08ba354c2cd7a85d2a3175327d3e5fef5a94edc4c7d505a45f9ed43b",
    },
    ResolvedOperationContract {
        resolution_module: "accelerated_attention_kernel_01",
        operation_id: "COMFY-TENSOR-OP-9973AD8D6DCC",
        baseline_overload_id: "COMFY-TENSOR-OP-9973AD8D6DCC:blocked",
        baseline_fixture_sha256: "d69e42afe5357fef4c4c909ee3c587c55ab8048fae85783166c5bd631bb51b26",
        overload_id: "zed.native.xformers_memory_efficient_attention.exact_cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"q\",\"type\":\"f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"k\",\"type\":\"f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"v\",\"type\":\"f32 tensor slice\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"attn_bias\",\"type\":\"optional additive f32 attention bias\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn memory_efficient_attention_with_context_exact_native(backend: &CpuBackend, shape: AttentionShape, q: &[f32], k: &[f32], v: &[f32], attn_bias: Option<&[f32]>, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, AttentionKernelError>",
        mutation_rule: "out-of-place; q, k, v, and attn_bias remain immutable",
        alias_rule: "returns fresh owned storage that aliases no input or bias",
        shape_rule: "q is BxNqxHxD, k is BxNkxHxD, v is BxNkxHxDv, additive bias is BxHxNqxNk, and output is BxNqxHxDv",
        dtype_rule: "the deterministic exact native fallback accepts f32 inputs and an optional f32 additive bias",
        accumulation_dtype: "f32 scores, softmax, and value accumulation",
        layout_rule: "contiguous logical NHD tensors with batch-head-query-key additive bias",
        device_rule: "CPU exact native fallback; non-CPU execution requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "scaled dot product with additive bias followed by max-subtracted softmax and deterministic value accumulation",
        tolerance: "absolute 0.000001 for checked f32 forward fixtures and 0.0003 for finite-difference gradients",
        determinism: "fixed loop order with no stochastic path",
        cancellation_points: "before allocation and once per batch-head-query row; cancellation publishes no output",
        vjp_rule: "analytical softmax attention VJP for q, k, and v with attn_bias treated as a constant",
        jvp_rule: "analytical softmax attention JVP for q, k, and v verified against finite differences and the VJP adjoint",
        owner_task_id: "comfy-parity-tensor-ops-accelerated-attention-kernel-comfy-tensor-op-1354ac34a777",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/accelerated_attention_kernel_01/xformers_memory_efficient_attention.json",
        evidence_fixture_sha256: "99025059f9bc4e26900be746dedf267cd371ba0906ee2377a4768deede88faf8",
    },
]
