&[
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-62E4C5B6AD0A",
        baseline_overload_id: "COMFY-TENSOR-OP-62E4C5B6AD0A:blocked",
        baseline_fixture_sha256: "c4a5ffe3a2927314f7f0d19a51dcd1dc537271726ee2b8322b29f887a885e512",
        overload_id: "sim.native.functional.batch_norm.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"running_mean\",\"type\":\"optional mutable f32 channel slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"running_variance\",\"type\":\"optional mutable f32 channel slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"optional f32 channel slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"optional f32 channel slice\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"training\",\"type\":\"bool\"},{\"default\":0.1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"momentum\",\"type\":\"f32\"},{\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn batch_norm_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], running_mean: Option<&mut [f32]>, running_variance: Option<&mut [f32]>, weight: Option<&[f32]>, bias: Option<&[f32]>, training: bool, momentum: f32, epsilon: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "output is out-of-place; successful training atomically updates paired running statistics after output completion",
        alias_rule: "output is fresh owned storage; running-stat slices retain identity and are unchanged on validation failure or cancellation",
        shape_rule: "input rank is at least two in N,C,... layout; channel parameters have C values and training requires more than one value per channel",
        dtype_rule: "the exact native slice accepts contiguous f32 values and optional f32 affine and running-stat slices",
        accumulation_dtype: "f64 fixed-order mean and variance reductions with f32 output and affine arithmetic",
        layout_rule: "logical contiguous row-major N,C,... layout",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "training uses biased variance for normalization and unbiased variance for the transactional running-variance update; evaluation uses supplied running statistics",
        tolerance: "absolute 0.00001 for forward and 0.003 for finite-difference gradient fixtures",
        determinism: "fixed channel, batch, and spatial reduction order",
        cancellation_points: "before allocation, once per channel, and before running-stat commit; cancellation publishes neither output nor state mutation",
        vjp_rule: "analytical training and evaluation VJP for input and optional affine weight and bias; running statistics are non-differentiable state",
        jvp_rule: "analytical training and evaluation JVP for input and optional affine tangents",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/batch_norm.json",
        evidence_fixture_sha256: "fb58dae8b36684e75dd6316a8f70eda23eec8afddad0ec1a9c79f856a0b21579",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-AED18ABCFD2B",
        baseline_overload_id: "COMFY-TENSOR-OP-AED18ABCFD2B:blocked",
        baseline_fixture_sha256: "3540880610f90239ca04b36fdfe53cad3bdd4316768165ec4e34580903fad5f1",
        overload_id: "sim.native.functional.gelu.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":\"none\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"approximation\",\"type\":\"GeluApproximation\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn gelu_with_context_exact_native(backend: &CpuBackend, input: &[f32], approximation: GeluApproximation, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input remains immutable",
        alias_rule: "returns fresh owned storage that aliases no input",
        shape_rule: "preserves every input element and logical shape",
        dtype_rule: "the exact native slice accepts contiguous f32 values",
        accumulation_dtype: "f32 fixed formula evaluation",
        layout_rule: "layout-independent elementwise contiguous logical order",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "supports the erf-based none profile and the PyTorch tanh approximation with NaN and infinity propagation",
        tolerance: "absolute 0.000001 for forward and 0.0003 for finite-difference gradient fixtures",
        determinism: "fixed scalar formula with no RNG",
        cancellation_points: "before allocation and at bounded element intervals; cancellation publishes no output",
        vjp_rule: "analytical derivative for both exact-profile and tanh-profile GELU",
        jvp_rule: "analytical elementwise JVP for both approximation profiles",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/gelu.json",
        evidence_fixture_sha256: "977b430db40d297b6f8ded063dc8f26901f0fbdbb46acbf210623f48c3c781fa",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-E5601CAF0B90",
        baseline_overload_id: "COMFY-TENSOR-OP-E5601CAF0B90:blocked",
        baseline_fixture_sha256: "2676b63ce60d68e7bc9b32f117d77590f8b896607ef1a2bc40c9adcce42621ec",
        overload_id: "sim.native.functional.group_norm.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"groups\",\"type\":\"usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"optional f32 channel slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"optional f32 channel slice\"},{\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn group_norm_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], groups: usize, weight: Option<&[f32]>, bias: Option<&[f32]>, epsilon: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input and affine parameters remain immutable",
        alias_rule: "returns fresh owned storage that aliases no input or parameter",
        shape_rule: "input rank is at least two in N,C,... layout; nonzero groups divide C and optional affine parameters have C values",
        dtype_rule: "the exact native slice accepts contiguous f32 values and optional f32 affine parameters",
        accumulation_dtype: "f64 fixed-order mean and biased-variance reductions with f32 affine output",
        layout_rule: "logical contiguous row-major N,C,... layout",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "each batch-group uses population variance plus positive epsilon followed by per-channel affine projection",
        tolerance: "absolute 0.00001 for forward and 0.003 for finite-difference gradient fixtures",
        determinism: "fixed batch, group, channel, and spatial reduction order",
        cancellation_points: "before allocation and once per batch-group; cancellation publishes no output",
        vjp_rule: "analytical group-normalization VJP for input and optional affine weight and bias",
        jvp_rule: "analytical group-normalization JVP for input and optional affine tangents",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/group_norm.json",
        evidence_fixture_sha256: "a7a9e939d3cfb4b4b0c6f43642ac1ea0ae2767cf28af997d5be3862fd3fc35d8",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-B8FC03A4DCA1",
        baseline_overload_id: "COMFY-TENSOR-OP-B8FC03A4DCA1:blocked",
        baseline_fixture_sha256: "8ead46af11d8f8429a526fc9ca17debac19052eabc2d4c700b90852f5c2aa729",
        overload_id: "sim.native.functional.layer_norm.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"normalized_shape\",\"type\":\"nonempty trailing usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"optional f32 normalized-shape slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"optional f32 normalized-shape slice\"},{\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn layer_norm_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], normalized_shape: &[usize], weight: Option<&[f32]>, bias: Option<&[f32]>, epsilon: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input and affine parameters remain immutable",
        alias_rule: "returns fresh owned storage that aliases no input or parameter",
        shape_rule: "normalized_shape is nonempty and exactly matches the input trailing dimensions; optional affine parameters match its checked product",
        dtype_rule: "the exact native slice accepts contiguous f32 values and optional f32 affine parameters",
        accumulation_dtype: "f64 fixed-order mean and biased-variance reductions with f32 affine output",
        layout_rule: "logical contiguous row-major layout with trailing normalization groups",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "population variance plus positive epsilon, normalized over the exact trailing shape, followed by optional elementwise affine projection",
        tolerance: "absolute 0.00001 for forward and 0.003 for finite-difference gradient fixtures",
        determinism: "fixed outer-group and trailing-component reduction order",
        cancellation_points: "before allocation and once per normalization group; cancellation publishes no output",
        vjp_rule: "analytical layer-normalization VJP for input and optional affine weight and bias",
        jvp_rule: "analytical layer-normalization JVP for input and optional affine tangents",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/layer_norm.json",
        evidence_fixture_sha256: "89239cb8d2b3f34dd427fbca1e0152573e89b352c72289c5af5322617dc1f344",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-8F7DF3AF61B9",
        baseline_overload_id: "COMFY-TENSOR-OP-8F7DF3AF61B9:blocked",
        baseline_fixture_sha256: "03a8d258b0f4d24854256136193f5f7409e7d15547ba2aca6ff38bab01b55e03",
        overload_id: "sim.native.functional.leaky_relu.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":0.01,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"negative_slope\",\"type\":\"f32\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"in_place\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32> or in-place unit\"]",
        rust_signature: "fn leaky_relu_with_context_exact_native(backend: &CpuBackend, input: &[f32], negative_slope: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>; fn leaky_relu_with_context_exact_native_in_place(backend: &CpuBackend, input: &mut [f32], negative_slope: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<(), FunctionalError>",
        mutation_rule: "out-of-place entry leaves input immutable; explicit in-place entry atomically replaces the same slice only after complete success",
        alias_rule: "out-of-place returns fresh storage; in-place preserves the caller-provided allocation identity",
        shape_rule: "preserves every input element and logical shape",
        dtype_rule: "the exact native slice accepts contiguous f32 values and a finite f32 negative slope",
        accumulation_dtype: "f32 elementwise arithmetic",
        layout_rule: "layout-independent elementwise contiguous logical order",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "nonnegative values are unchanged and negative values are multiplied by negative_slope with NaN propagation",
        tolerance: "exact f32 branch arithmetic and absolute 0.0003 for finite-difference gradient fixtures",
        determinism: "fixed scalar formula with no RNG",
        cancellation_points: "before temporary allocation, at bounded element intervals, and before in-place commit; cancellation leaves input unchanged",
        vjp_rule: "analytical piecewise VJP using slope one for nonnegative inputs and negative_slope for negative inputs",
        jvp_rule: "analytical piecewise elementwise JVP with the same zero convention",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/leaky_relu.json",
        evidence_fixture_sha256: "28f97f95916e6a5f6894ebdf3141033d5f59340ef6abcabd01bd03c9933db93d",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-198CE0C4C23A",
        baseline_overload_id: "COMFY-TENSOR-OP-198CE0C4C23A:blocked",
        baseline_fixture_sha256: "552f122c59c834da27dabf1d14c5f6cf721aba6da81e456be65607f175f188d3",
        overload_id: "sim.native.functional.normalize.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":2.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"norm_order\",\"type\":\"f32\"},{\"default\":[1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimensions\",\"type\":\"nonempty unique isize axes\"},{\"default\":1e-12,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn normalize_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], norm_order: f32, dimensions: &[isize], epsilon: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input remains immutable",
        alias_rule: "returns fresh owned storage that aliases no input",
        shape_rule: "shape exactly covers input; dimensions are nonempty, unique, negative-axis aware, and reduced together while output preserves shape",
        dtype_rule: "the exact native slice accepts contiguous f32 values, finite norm order at least one, and positive finite epsilon",
        accumulation_dtype: "f32 fixed-order absolute-power reductions",
        layout_rule: "logical contiguous row-major layout with arbitrary checked reduction axes",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "divides each reduction group by max(p-norm, epsilon), including zero-vector behavior",
        tolerance: "absolute 0.000001 for forward and 0.0003 for finite-difference gradient fixtures",
        determinism: "fixed flat-index reduction and publication order",
        cancellation_points: "before allocation and at bounded reduction and publication intervals; cancellation publishes no output",
        vjp_rule: "analytical p-norm VJP with explicit epsilon-clamped branch",
        jvp_rule: "analytical p-norm JVP with explicit epsilon-clamped branch",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/normalize.json",
        evidence_fixture_sha256: "be31dd09583dd1a1a1955c819d13572062ffb7945cdffba69e39497be8c98557",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-0538873A73B1",
        baseline_overload_id: "COMFY-TENSOR-OP-0538873A73B1:blocked",
        baseline_fixture_sha256: "bf03730f2c5ab08780538044de0bfca378e66538332325acf9e8cccf0a8df2c5",
        overload_id: "sim.native.functional.relu.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"in_place\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32> or in-place unit\"]",
        rust_signature: "fn relu_with_context_exact_native(backend: &CpuBackend, input: &[f32], device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>; fn relu_with_context_exact_native_in_place(backend: &CpuBackend, input: &mut [f32], device: DeviceId, context: &ExecutionContext<'_>) -> Result<(), FunctionalError>",
        mutation_rule: "out-of-place entry leaves input immutable; explicit in-place entry atomically replaces the same slice only after complete success",
        alias_rule: "out-of-place returns fresh storage; in-place preserves the caller-provided allocation identity",
        shape_rule: "preserves every input element and logical shape",
        dtype_rule: "the functional adapter accepts contiguous f32 and delegates scalar ReLU values to CpuBackend's canonical unary implementation",
        accumulation_dtype: "f32 elementwise scalar dispatch",
        layout_rule: "layout-independent elementwise contiguous logical order",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "delegates canonical scalar maximum behavior including NaN propagation and uses derivative zero at zero",
        tolerance: "exact scalar output and analytical gradient fixtures",
        determinism: "fixed scalar dispatch with no RNG",
        cancellation_points: "before temporary allocation, at bounded element intervals, and before in-place commit; cancellation leaves input unchanged",
        vjp_rule: "analytical piecewise VJP with derivative one for positive values and zero otherwise",
        jvp_rule: "analytical piecewise elementwise JVP with derivative zero at zero",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/relu.json",
        evidence_fixture_sha256: "32c77d2a9a7a07c9f8177a7db2b0cc29cd9f53b913a409e18286356cc4621404",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-56C3DFEB2F05",
        baseline_overload_id: "COMFY-TENSOR-OP-56C3DFEB2F05:blocked",
        baseline_fixture_sha256: "93c2bf0bdcdf6035fb0be926ac8b698d3c3aafb8ba050ce25e04824da6e28360",
        overload_id: "sim.native.functional.rms_norm.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"normalized_shape\",\"type\":\"nonempty trailing usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"optional f32 normalized-shape slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"optional f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn rms_norm_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], normalized_shape: &[usize], weight: Option<&[f32]>, epsilon: Option<f32>, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input and optional weight remain immutable",
        alias_rule: "returns fresh owned storage that aliases no input or parameter",
        shape_rule: "normalized_shape is nonempty and exactly matches input trailing dimensions; optional weight matches its checked product",
        dtype_rule: "the exact native slice accepts contiguous f32 values and uses f32 epsilon when omitted",
        accumulation_dtype: "f64 fixed-order mean-square reduction with f32 projection",
        layout_rule: "logical contiguous row-major layout with trailing normalization groups",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "multiplies input by reciprocal sqrt of mean square plus epsilon, then applies optional elementwise weight",
        tolerance: "absolute 0.00001 for forward and 0.003 for finite-difference gradient fixtures",
        determinism: "fixed outer-group and trailing-component reduction order",
        cancellation_points: "before allocation and once per normalization group; cancellation publishes no output",
        vjp_rule: "analytical RMS-normalization VJP for input and optional weight",
        jvp_rule: "analytical RMS-normalization JVP for input and optional weight tangent",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/rms_norm.json",
        evidence_fixture_sha256: "f23528d81e2f80259bac967016bb234b24ecae2476b9c88bb4b77cb165eb019e",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-8D65C6573263",
        baseline_overload_id: "COMFY-TENSOR-OP-8D65C6573263:blocked",
        baseline_fixture_sha256: "4caaccdc28c949f7846d57c52e5559dc29fd185bdc0049a3728d979b8f2cdd7f",
        overload_id: "sim.native.functional.silu.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"in_place\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32> or in-place unit\"]",
        rust_signature: "fn silu_with_context_exact_native(backend: &CpuBackend, input: &[f32], device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>; fn silu_with_context_exact_native_in_place(backend: &CpuBackend, input: &mut [f32], device: DeviceId, context: &ExecutionContext<'_>) -> Result<(), FunctionalError>",
        mutation_rule: "out-of-place entry leaves input immutable; explicit in-place entry atomically replaces the same slice only after complete success",
        alias_rule: "out-of-place returns fresh storage; in-place preserves the caller-provided allocation identity",
        shape_rule: "preserves every input element and logical shape",
        dtype_rule: "the functional adapter accepts contiguous f32; its analytical derivative reuses CpuBackend's canonical scalar sigmoid",
        accumulation_dtype: "f32 elementwise exponential, addition, and division",
        layout_rule: "layout-independent elementwise contiguous logical order",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "computes input divided by one plus exp of negative input in fixed f32 order with NaN and infinity propagation",
        tolerance: "absolute 0.000001 for forward and 0.0003 for finite-difference gradient fixtures",
        determinism: "fixed scalar formula with no RNG",
        cancellation_points: "before temporary allocation, at bounded element intervals, and before in-place commit; cancellation leaves input unchanged",
        vjp_rule: "analytical SiLU VJP using sigmoid times one plus input times one minus sigmoid",
        jvp_rule: "analytical elementwise SiLU JVP",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/silu.json",
        evidence_fixture_sha256: "a3775780edd5374f89766dae7545520e8254aed01f4ba55de1c5d6555017c464",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-0F14CB65D5B7",
        baseline_overload_id: "COMFY-TENSOR-OP-0F14CB65D5B7:blocked",
        baseline_fixture_sha256: "f662964ff72ef2c0fcbb2e9ef277b7e30b84d24c930bf8b11ce2bdecec9df293",
        overload_id: "sim.native.functional.softmax.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"isize axis\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn softmax_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], dimension: isize, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input remains immutable",
        alias_rule: "returns fresh owned storage that aliases no input",
        shape_rule: "shape exactly covers input, rank is nonzero, dimension accepts checked negative indexing, and output preserves shape",
        dtype_rule: "the exact native slice accepts contiguous f32 values",
        accumulation_dtype: "f32 maximum, exponential, sum, and division",
        layout_rule: "logical contiguous row-major layout with arbitrary checked softmax axis",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "max-subtracted stable softmax with fixed row order and explicit NaN propagation",
        tolerance: "absolute 0.000001 for forward and 0.0003 for finite-difference gradient fixtures",
        determinism: "fixed outer, inner, and axis reduction order",
        cancellation_points: "before allocation and once per softmax row; cancellation publishes no output",
        vjp_rule: "analytical softmax VJP y times upstream minus dot of y and upstream",
        jvp_rule: "analytical softmax JVP y times tangent minus dot of y and tangent",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/softmax.json",
        evidence_fixture_sha256: "277e561533c6bd37f02fef84ccdbb8c827d8341c26c306109af885cc0653f0da",
    },
]
