&[
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-62E4C5B6AD0A",
        baseline_overload_id: "COMFY-TENSOR-OP-62E4C5B6AD0A:blocked",
        baseline_fixture_sha256: "c1d8a45d5fa43621ae728695e772cc187e7323c969d385b969e27a50a0b26105",
        overload_id: "zed.native.functional.batch_norm.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"running_mean\",\"type\":\"optional mutable f32 channel slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"running_variance\",\"type\":\"optional mutable f32 channel slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"optional f32 channel slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"optional f32 channel slice\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"training\",\"type\":\"bool\"},{\"default\":0.1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"momentum\",\"type\":\"f32\"},{\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn batch_norm_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], running_mean: Option<&mut [f32]>, running_variance: Option<&mut [f32]>, weight: Option<&[f32]>, bias: Option<&[f32]>, training: bool, momentum: f32, epsilon: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "output is out-of-place; successful training atomically updates paired running statistics after output completion",
        alias_rule: "output is fresh owned storage; running-stat slices retain identity and are unchanged on validation failure or cancellation",
        shape_rule: "input rank is at least two in N,C,... layout; channel parameters have C values and training requires more than one value per channel",
        dtype_rule: "the exact native slice accepts contiguous f32 values and optional f32 affine and running-stat slices",
        accumulation_dtype: "f64 fixed-order mean and variance reductions with f32 output and affine arithmetic",
        layout_rule: "logical contiguous row-major N,C,... layout",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "training uses biased variance for normalization and unbiased variance for the transactional running-variance update; evaluation uses supplied running statistics",
        tolerance: "absolute 0.00001 for forward and 0.003 for finite-difference gradient fixtures",
        determinism: "fixed channel, batch, and spatial reduction order",
        cancellation_points: "before allocation, once per channel, and before running-stat commit; cancellation publishes neither output nor state mutation",
        vjp_rule: "analytical training and evaluation VJP for input and optional affine weight and bias; running statistics are non-differentiable state",
        jvp_rule: "analytical training and evaluation JVP for input and optional affine tangents",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/batch_norm.json",
        evidence_fixture_sha256: "30e0c7e5dee6a5b322504d9dfb9ebae99b390b76aedb8539b19333d36bd4dc3b",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-AED18ABCFD2B",
        baseline_overload_id: "COMFY-TENSOR-OP-AED18ABCFD2B:blocked",
        baseline_fixture_sha256: "e3a0ca44903e7fe21819c819e5c3c99036b59f088606a6b55995514f3b37589e",
        overload_id: "zed.native.functional.gelu.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":\"none\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"approximation\",\"type\":\"GeluApproximation\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn gelu_with_context_exact_native(backend: &CpuBackend, input: &[f32], approximation: GeluApproximation, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input remains immutable",
        alias_rule: "returns fresh owned storage that aliases no input",
        shape_rule: "preserves every input element and logical shape",
        dtype_rule: "the exact native slice accepts contiguous f32 values",
        accumulation_dtype: "f32 fixed formula evaluation",
        layout_rule: "layout-independent elementwise contiguous logical order",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "supports the erf-based none profile and the PyTorch tanh approximation with NaN and infinity propagation",
        tolerance: "absolute 0.000001 for forward and 0.0003 for finite-difference gradient fixtures",
        determinism: "fixed scalar formula with no RNG",
        cancellation_points: "before allocation and at bounded element intervals; cancellation publishes no output",
        vjp_rule: "analytical derivative for both exact-profile and tanh-profile GELU",
        jvp_rule: "analytical elementwise JVP for both approximation profiles",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/gelu.json",
        evidence_fixture_sha256: "ced7778445c4b94ce2a14ee6a29eb2e3acf307e3b626e23e036148b1cc465de1",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-E5601CAF0B90",
        baseline_overload_id: "COMFY-TENSOR-OP-E5601CAF0B90:blocked",
        baseline_fixture_sha256: "0a0c67a653533666ae34ae4296310cef91ec08095d89705de67bab9f5108d0a3",
        overload_id: "zed.native.functional.group_norm.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"groups\",\"type\":\"usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"optional f32 channel slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"optional f32 channel slice\"},{\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn group_norm_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], groups: usize, weight: Option<&[f32]>, bias: Option<&[f32]>, epsilon: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input and affine parameters remain immutable",
        alias_rule: "returns fresh owned storage that aliases no input or parameter",
        shape_rule: "input rank is at least two in N,C,... layout; nonzero groups divide C and optional affine parameters have C values",
        dtype_rule: "the exact native slice accepts contiguous f32 values and optional f32 affine parameters",
        accumulation_dtype: "f64 fixed-order mean and biased-variance reductions with f32 affine output",
        layout_rule: "logical contiguous row-major N,C,... layout",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "each batch-group uses population variance plus positive epsilon followed by per-channel affine projection",
        tolerance: "absolute 0.00001 for forward and 0.003 for finite-difference gradient fixtures",
        determinism: "fixed batch, group, channel, and spatial reduction order",
        cancellation_points: "before allocation and once per batch-group; cancellation publishes no output",
        vjp_rule: "analytical group-normalization VJP for input and optional affine weight and bias",
        jvp_rule: "analytical group-normalization JVP for input and optional affine tangents",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/group_norm.json",
        evidence_fixture_sha256: "049cfd236f3d952f4f7b3365c4b624bc591b2fd849e42e94435da6dfe9bb9fd4",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-B8FC03A4DCA1",
        baseline_overload_id: "COMFY-TENSOR-OP-B8FC03A4DCA1:blocked",
        baseline_fixture_sha256: "f50741821a5d2339e8d58a8d22d8a64cc1cb2fe458b5cf73f6231d790e9ad097",
        overload_id: "zed.native.functional.layer_norm.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"normalized_shape\",\"type\":\"nonempty trailing usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"optional f32 normalized-shape slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"optional f32 normalized-shape slice\"},{\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn layer_norm_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], normalized_shape: &[usize], weight: Option<&[f32]>, bias: Option<&[f32]>, epsilon: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input and affine parameters remain immutable",
        alias_rule: "returns fresh owned storage that aliases no input or parameter",
        shape_rule: "normalized_shape is nonempty and exactly matches the input trailing dimensions; optional affine parameters match its checked product",
        dtype_rule: "the exact native slice accepts contiguous f32 values and optional f32 affine parameters",
        accumulation_dtype: "f64 fixed-order mean and biased-variance reductions with f32 affine output",
        layout_rule: "logical contiguous row-major layout with trailing normalization groups",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "population variance plus positive epsilon, normalized over the exact trailing shape, followed by optional elementwise affine projection",
        tolerance: "absolute 0.00001 for forward and 0.003 for finite-difference gradient fixtures",
        determinism: "fixed outer-group and trailing-component reduction order",
        cancellation_points: "before allocation and once per normalization group; cancellation publishes no output",
        vjp_rule: "analytical layer-normalization VJP for input and optional affine weight and bias",
        jvp_rule: "analytical layer-normalization JVP for input and optional affine tangents",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/layer_norm.json",
        evidence_fixture_sha256: "1303349c475196d9661e3b4b9bea4a2ec9c4fb369a53f4164b9073c2e776b25e",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-8F7DF3AF61B9",
        baseline_overload_id: "COMFY-TENSOR-OP-8F7DF3AF61B9:blocked",
        baseline_fixture_sha256: "584efeb83d8858245d9031c00519283a888c7cc46ea262c5fe677c831aa8d9f5",
        overload_id: "zed.native.functional.leaky_relu.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":0.01,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"negative_slope\",\"type\":\"f32\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"in_place\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32> or in-place unit\"]",
        rust_signature: "fn leaky_relu_with_context_exact_native(backend: &CpuBackend, input: &[f32], negative_slope: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>; fn leaky_relu_with_context_exact_native_in_place(backend: &CpuBackend, input: &mut [f32], negative_slope: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<(), FunctionalError>",
        mutation_rule: "out-of-place entry leaves input immutable; explicit in-place entry atomically replaces the same slice only after complete success",
        alias_rule: "out-of-place returns fresh storage; in-place preserves the caller-provided allocation identity",
        shape_rule: "preserves every input element and logical shape",
        dtype_rule: "the exact native slice accepts contiguous f32 values and a finite f32 negative slope",
        accumulation_dtype: "f32 elementwise arithmetic",
        layout_rule: "layout-independent elementwise contiguous logical order",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "nonnegative values are unchanged and negative values are multiplied by negative_slope with NaN propagation",
        tolerance: "exact f32 branch arithmetic and absolute 0.0003 for finite-difference gradient fixtures",
        determinism: "fixed scalar formula with no RNG",
        cancellation_points: "before temporary allocation, at bounded element intervals, and before in-place commit; cancellation leaves input unchanged",
        vjp_rule: "analytical piecewise VJP using slope one for nonnegative inputs and negative_slope for negative inputs",
        jvp_rule: "analytical piecewise elementwise JVP with the same zero convention",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/leaky_relu.json",
        evidence_fixture_sha256: "dcc0b1a6cc93ae5c21b11db69fa266c571108ea9279a2285c91b6d4f4ba34bf2",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-198CE0C4C23A",
        baseline_overload_id: "COMFY-TENSOR-OP-198CE0C4C23A:blocked",
        baseline_fixture_sha256: "31654030ebecbb43b4da8c0e0b99e2e74991919463bb5c9e30bcdab59cf0e5f6",
        overload_id: "zed.native.functional.normalize.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":2.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"norm_order\",\"type\":\"f32\"},{\"default\":[1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimensions\",\"type\":\"nonempty unique isize axes\"},{\"default\":1e-12,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn normalize_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], norm_order: f32, dimensions: &[isize], epsilon: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input remains immutable",
        alias_rule: "returns fresh owned storage that aliases no input",
        shape_rule: "shape exactly covers input; dimensions are nonempty, unique, negative-axis aware, and reduced together while output preserves shape",
        dtype_rule: "the exact native slice accepts contiguous f32 values, finite norm order at least one, and positive finite epsilon",
        accumulation_dtype: "f32 fixed-order absolute-power reductions",
        layout_rule: "logical contiguous row-major layout with arbitrary checked reduction axes",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "divides each reduction group by max(p-norm, epsilon), including zero-vector behavior",
        tolerance: "absolute 0.000001 for forward and 0.0003 for finite-difference gradient fixtures",
        determinism: "fixed flat-index reduction and publication order",
        cancellation_points: "before allocation and at bounded reduction and publication intervals; cancellation publishes no output",
        vjp_rule: "analytical p-norm VJP with explicit epsilon-clamped branch",
        jvp_rule: "analytical p-norm JVP with explicit epsilon-clamped branch",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/normalize.json",
        evidence_fixture_sha256: "6d37e1f49eebfc14414dcdc2298a6fd4fb0bb02115a41d5b6987e1ac7eb1a434",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-0538873A73B1",
        baseline_overload_id: "COMFY-TENSOR-OP-0538873A73B1:blocked",
        baseline_fixture_sha256: "d7342758b7bc3b6c46e08b248ffdeaa9debd3ec2a49871f7d492bffa4de50c30",
        overload_id: "zed.native.functional.relu.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"in_place\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32> or in-place unit\"]",
        rust_signature: "fn relu_with_context_exact_native(backend: &CpuBackend, input: &[f32], device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>; fn relu_with_context_exact_native_in_place(backend: &CpuBackend, input: &mut [f32], device: DeviceId, context: &ExecutionContext<'_>) -> Result<(), FunctionalError>",
        mutation_rule: "out-of-place entry leaves input immutable; explicit in-place entry atomically replaces the same slice only after complete success",
        alias_rule: "out-of-place returns fresh storage; in-place preserves the caller-provided allocation identity",
        shape_rule: "preserves every input element and logical shape",
        dtype_rule: "the functional adapter accepts contiguous f32 and delegates scalar ReLU values to CpuBackend's canonical unary implementation",
        accumulation_dtype: "f32 elementwise scalar dispatch",
        layout_rule: "layout-independent elementwise contiguous logical order",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "delegates canonical scalar maximum behavior including NaN propagation and uses derivative zero at zero",
        tolerance: "exact scalar output and analytical gradient fixtures",
        determinism: "fixed scalar dispatch with no RNG",
        cancellation_points: "before temporary allocation, at bounded element intervals, and before in-place commit; cancellation leaves input unchanged",
        vjp_rule: "analytical piecewise VJP with derivative one for positive values and zero otherwise",
        jvp_rule: "analytical piecewise elementwise JVP with derivative zero at zero",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/relu.json",
        evidence_fixture_sha256: "b332c14042d158dceda9498e001765723c0f0f45f3e6a37a5b4b21122127b8c5",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-56C3DFEB2F05",
        baseline_overload_id: "COMFY-TENSOR-OP-56C3DFEB2F05:blocked",
        baseline_fixture_sha256: "ecc2bd2476092f42925310b56dc671960816e40ff2e2de1000acd01f7bd6b748",
        overload_id: "zed.native.functional.rms_norm.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"normalized_shape\",\"type\":\"nonempty trailing usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"optional f32 normalized-shape slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"optional f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn rms_norm_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], normalized_shape: &[usize], weight: Option<&[f32]>, epsilon: Option<f32>, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input and optional weight remain immutable",
        alias_rule: "returns fresh owned storage that aliases no input or parameter",
        shape_rule: "normalized_shape is nonempty and exactly matches input trailing dimensions; optional weight matches its checked product",
        dtype_rule: "the exact native slice accepts contiguous f32 values and uses f32 epsilon when omitted",
        accumulation_dtype: "f64 fixed-order mean-square reduction with f32 projection",
        layout_rule: "logical contiguous row-major layout with trailing normalization groups",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "multiplies input by reciprocal sqrt of mean square plus epsilon, then applies optional elementwise weight",
        tolerance: "absolute 0.00001 for forward and 0.003 for finite-difference gradient fixtures",
        determinism: "fixed outer-group and trailing-component reduction order",
        cancellation_points: "before allocation and once per normalization group; cancellation publishes no output",
        vjp_rule: "analytical RMS-normalization VJP for input and optional weight",
        jvp_rule: "analytical RMS-normalization JVP for input and optional weight tangent",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/rms_norm.json",
        evidence_fixture_sha256: "a2df59b686f3fef866a929a12613d68ae429cbe95104bded7ab2c1482a7b34d6",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-8D65C6573263",
        baseline_overload_id: "COMFY-TENSOR-OP-8D65C6573263:blocked",
        baseline_fixture_sha256: "4447beae0ac5c0041ef94df97e8c99a5ef920b62c6839ab30b19ec92f0bcd900",
        overload_id: "zed.native.functional.silu.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"in_place\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32> or in-place unit\"]",
        rust_signature: "fn silu_with_context_exact_native(backend: &CpuBackend, input: &[f32], device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>; fn silu_with_context_exact_native_in_place(backend: &CpuBackend, input: &mut [f32], device: DeviceId, context: &ExecutionContext<'_>) -> Result<(), FunctionalError>",
        mutation_rule: "out-of-place entry leaves input immutable; explicit in-place entry atomically replaces the same slice only after complete success",
        alias_rule: "out-of-place returns fresh storage; in-place preserves the caller-provided allocation identity",
        shape_rule: "preserves every input element and logical shape",
        dtype_rule: "the functional adapter accepts contiguous f32; its analytical derivative reuses CpuBackend's canonical scalar sigmoid",
        accumulation_dtype: "f32 elementwise exponential, addition, and division",
        layout_rule: "layout-independent elementwise contiguous logical order",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "computes input divided by one plus exp of negative input in fixed f32 order with NaN and infinity propagation",
        tolerance: "absolute 0.000001 for forward and 0.0003 for finite-difference gradient fixtures",
        determinism: "fixed scalar formula with no RNG",
        cancellation_points: "before temporary allocation, at bounded element intervals, and before in-place commit; cancellation leaves input unchanged",
        vjp_rule: "analytical SiLU VJP using sigmoid times one plus input times one minus sigmoid",
        jvp_rule: "analytical elementwise SiLU JVP",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/silu.json",
        evidence_fixture_sha256: "1dd83fa20156434645f9159b5a6d2c72049b4d2305f84bc0658f5286d5208766",
    },
    ResolvedOperationContract {
        resolution_module: "activation_normalization_functional_01",
        operation_id: "COMFY-TENSOR-OP-0F14CB65D5B7",
        baseline_overload_id: "COMFY-TENSOR-OP-0F14CB65D5B7:blocked",
        baseline_fixture_sha256: "0b0a4a8f52be11e2610cc9dde72a3c4260adb4768a13813e7528778aac10618f",
        overload_id: "zed.native.functional.softmax.cpu_f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous f32 tensor slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"shape\",\"type\":\"row-major usize dimensions\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"isize axis\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn softmax_with_context_exact_native(backend: &CpuBackend, input: &[f32], shape: &[usize], dimension: isize, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, FunctionalError>",
        mutation_rule: "out-of-place; input remains immutable",
        alias_rule: "returns fresh owned storage that aliases no input",
        shape_rule: "shape exactly covers input, rank is nonzero, dimension accepts checked negative indexing, and output preserves shape",
        dtype_rule: "the exact native slice accepts contiguous f32 values",
        accumulation_dtype: "f32 maximum, exponential, sum, and division",
        layout_rule: "logical contiguous row-major layout with arbitrary checked softmax axis",
        device_rule: "CPU exact native execution; non-CPU requires a separately certified adapter and returns typed unavailable here",
        numeric_rule: "max-subtracted stable softmax with fixed row order and explicit NaN propagation",
        tolerance: "absolute 0.000001 for forward and 0.0003 for finite-difference gradient fixtures",
        determinism: "fixed outer, inner, and axis reduction order",
        cancellation_points: "before allocation and once per softmax row; cancellation publishes no output",
        vjp_rule: "analytical softmax VJP y times upstream minus dot of y and upstream",
        jvp_rule: "analytical softmax JVP y times tangent minus dot of y and tangent",
        owner_task_id: "comfy-parity-tensor-ops-activation-normalization-functional-comfy-tensor-op-0538873a73b1",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/activation_normalization_functional_01/softmax.json",
        evidence_fixture_sha256: "b97e1a71c31c002b074c6b907e58536b3dff1097d6124062e9547311cf329f96",
    },
]
