&[
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-A0BD98DDA517",
        baseline_overload_id: "COMFY-TENSOR-OP-A0BD98DDA517:blocked",
        baseline_fixture_sha256: "245e168716fd9699479ddc2d7b74d06939148c622bf40483d42d114e7a2a9954",
        overload_id: "zed.native.model.zero_init_parameter.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"module\",\"type\":\"mutable NativeModule\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"name\",\"type\":\"weight or bias parameter name\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"fallback_dtype\",\"type\":\"canonical DType\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"fallback_device\",\"type\":\"canonical DeviceId\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn NativeModule::zero_init_parameter_with_context_exact_native(&mut self, backend: &CpuBackend, name: &str, fallback_dtype: DType, fallback_device: DeviceId, context: &ExecutionContext<'_>) -> Result<(), NativeOpsError>",
        mutation_rule: "the complete zero tensor stages first; cancellation or failure leaves parameter state, prefetch state, and generation unchanged",
        alias_rule: "the committed parameter owns fresh canonical zero storage and shares no mutable model mapping",
        shape_rule: "weight or bias shape is derived exclusively from the checked NativeModuleSpec",
        dtype_rule: "an existing dense parameter preserves its dtype and device; an unloaded parameter uses explicit canonical fallback values",
        accumulation_dtype: "no arithmetic accumulation",
        layout_rule: "the zero parameter is canonical contiguous storage",
        device_rule: "CPU ordinal zero is exact native and uncertified devices fail through the canonical tensor owner",
        numeric_rule: "every logical value is positive zero in the requested canonical dtype",
        tolerance: "bit-exact zero",
        determinism: "shape-derived fixed allocation and zero fill",
        cancellation_points: "before shape resolution, during tensor publication, and before the single module-state commit",
        vjp_rule: "parameter materialization is non-differentiable; consuming kernels own gradients",
        jvp_rule: "parameter materialization is non-differentiable; consuming kernels own tangents",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/zero_init_parameter.json",
        evidence_fixture_sha256: "d702369050efcb668d40097c26ee7fe8cf622e1e0b050f7eb9e11a04418381a5",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-A553C4928CA6",
        baseline_overload_id: "COMFY-TENSOR-OP-A553C4928CA6:blocked",
        baseline_fixture_sha256: "2be7e2f691de9762773e1b10f10658947d40de9c07dc79f81c00a20a80f2eb83",
        overload_id: "zed.native.model.disable_weight_init.conv1d.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"kernel_size\",\"type\":\"nonzero usize\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"stride\",\"type\":\"nonzero usize\"},{\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"padding\",\"type\":\"usize\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dilation\",\"type\":\"nonzero usize\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"groups\",\"type\":\"nonzero usize\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"},{\"default\":\"zeros\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"padding_mode\",\"type\":\"ConvolutionPaddingMode\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_conv1d_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_size: usize, stride: usize, padding: usize, dilation: usize, groups: usize, bias: bool, padding_mode: ConvolutionPaddingMode) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "construction creates unloaded checked module state without random initialization; parameter load is atomic",
        alias_rule: "immutable loaded parameters and fresh forward outputs",
        shape_rule: "NCL grouped cross-correlation uses the canonical checked convolution output formula",
        dtype_rule: "canonical module casts surround the single shared f32 convolution kernel",
        accumulation_dtype: "fixed f32 multiply-add order over input channel and kernel coordinates",
        layout_rule: "contiguous logical NCL input, OIL weight, and NCL output",
        device_rule: "CPU exact native; uncertified devices return typed unavailable",
        numeric_rule: "zero, reflect, replicate, and circular padding map coordinates in the canonical convolution owner",
        tolerance: "absolute 0.00001 forward and 0.003 finite-difference gradient",
        determinism: "fixed batch, output-channel, position, input-channel, and kernel order",
        cancellation_points: "before validation, at bounded output positions, and before publication",
        vjp_rule: "canonical convolution VJP accumulates repeated padded coordinates into the source input",
        jvp_rule: "canonical convolution JVP uses the identical padding-coordinate mapping",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/conv1d.json",
        evidence_fixture_sha256: "3681931fe834bdeda318a08c5deca55c68f1a36d9c9c154eaa6daa78eb79a03f",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-A88C934F4A40",
        baseline_overload_id: "COMFY-TENSOR-OP-A88C934F4A40:blocked",
        baseline_fixture_sha256: "cbc552425748d89003b4a9e805fc675fc86bcefdb571bfbb524df91164fc80e6",
        overload_id: "zed.native.model.disable_weight_init.layer_norm.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"normalized_shape\",\"type\":\"nonempty usize dimensions\"},{\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"positive finite f32\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"elementwise_affine\",\"type\":\"bool\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_layer_norm_exact_native(layer_name: impl Into<String>, normalized_shape: Vec<usize>, epsilon: f32, elementwise_affine: bool, bias: bool) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructor is unloaded and performs no random parameter initialization",
        alias_rule: "immutable parameters and fresh normalized output storage",
        shape_rule: "normalized_shape exactly matches trailing input dimensions",
        dtype_rule: "canonical casts delegate normalization arithmetic to the functional layer-normalization owner",
        accumulation_dtype: "inherits functional owner's f64 reductions and f32 affine arithmetic",
        layout_rule: "contiguous logical groups over trailing dimensions",
        device_rule: "CPU exact native; uncertified devices return typed unavailable",
        numeric_rule: "affine and non-affine execution use one canonical functional equation",
        tolerance: "absolute 0.00001 forward and 0.003 gradient",
        determinism: "inherits functional owner reduction order",
        cancellation_points: "before parameter casting, within normalization groups, and before output publication",
        vjp_rule: "delegates analytical VJP to canonical functional layer normalization",
        jvp_rule: "delegates analytical JVP to canonical functional layer normalization",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/layer_norm.json",
        evidence_fixture_sha256: "cead5cabdac8af917bdae8212ed3d09359a28f7ff8ac37ac8a06f4a76ed80372",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-C9049FCF1A75",
        baseline_overload_id: "COMFY-TENSOR-OP-C9049FCF1A75:blocked",
        baseline_fixture_sha256: "885efaf70997cc7da84cb2d92d00a3a14c36bf7f12466b1b9c83342340ab3d10",
        overload_id: "zed.native.model.disable_weight_init.group_norm.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"groups\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"channels\",\"type\":\"nonzero usize divisible by groups\"},{\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"positive finite f32\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"affine\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_group_norm_exact_native(layer_name: impl Into<String>, groups: usize, channels: usize, epsilon: f32, affine: bool) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructor is unloaded and parameter loading is a separate checked atomic commit",
        alias_rule: "immutable parameters and fresh normalized output storage",
        shape_rule: "input is N,C,* with configured C and channels divisible by groups",
        dtype_rule: "canonical casts delegate normalization arithmetic to the functional group-normalization owner",
        accumulation_dtype: "inherits functional owner's stable group-statistic accumulation",
        layout_rule: "contiguous logical N,C,* groups",
        device_rule: "CPU exact native; uncertified devices return typed unavailable",
        numeric_rule: "affine and non-affine execution use one canonical functional equation",
        tolerance: "absolute 0.00001 forward and 0.003 gradient",
        determinism: "fixed batch, group, channel, and spatial order",
        cancellation_points: "before parameter casting, between groups, and before output publication",
        vjp_rule: "delegates analytical VJP to canonical functional group normalization",
        jvp_rule: "delegates analytical JVP to canonical functional group normalization",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/group_norm.json",
        evidence_fixture_sha256: "36abff36c70232700c20b8bdbc44ae659e6d17f6b07325cd0540436a70a385eb",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-D63C669FCD27",
        baseline_overload_id: "COMFY-TENSOR-OP-D63C669FCD27:blocked",
        baseline_fixture_sha256: "33c62f18115d6dee868184bd9bbf647c7e7ab4bb23508be24142e611f7a234d1",
        overload_id: "zed.native.model.pick_operations.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight_dtype\",\"type\":\"canonical DType\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"compute_dtype\",\"type\":\"optional canonical DType\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"load_device\",\"type\":\"optional canonical DeviceId\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"disable_fast_fp8\",\"type\":\"bool\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"fp8_optimizations\",\"type\":\"bool\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"quant_config\",\"type\":\"optional bounded layer quantization map\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeOperationSet\"]",
        rust_signature: "fn pick_operations_exact_native(weight_dtype: DType, compute_dtype: Option<DType>, load_device: Option<DeviceId>, disable_fast_fp8: bool, fp8_optimizations: bool, quant_config: Option<BTreeMap<String, LayerQuantizationV1>>, cancellation: &CancellationToken) -> Result<NativeOperationSet, NativeOpsError>",
        mutation_rule: "returns immutable validated policy without changing device capabilities, global state, or model parameters",
        alias_rule: "the policy owns bounded metadata and constructed modules use immutable canonical parameter handles",
        shape_rule: "selection is shape-neutral; each constructed NativeModule validates its own shapes",
        dtype_rule: "matching or absent compute dtype selects direct storage, differing dtype selects manual cast, and quant metadata selects mixed precision",
        accumulation_dtype: "the selected compute dtype is explicit and kernel owners define reduction precision",
        layout_rule: "layout selection remains with convolution and quantization owners",
        device_rule: "CPU ordinal zero is certified; other devices return typed unavailable without fallback",
        numeric_rule: "CPU exposes no false fast-FP8 or cuBLAS capability and never selects an unavailable accelerated path",
        tolerance: "selection is exact; selected kernels retain their declared tolerance",
        determinism: "canonical dtype, device, and ordered quantization metadata uniquely determine the result",
        cancellation_points: "before capability and metadata validation and before returning the policy",
        vjp_rule: "selection is non-differentiable; selected kernels own gradients",
        jvp_rule: "selection is non-differentiable; selected kernels own tangents",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/pick_operations.json",
        evidence_fixture_sha256: "281eba41915b50a1d83dd38dfd500fc15e9311f41a0f4e6c0a48f4ed893fb108",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-DAC4074BC3B2",
        baseline_overload_id: "COMFY-TENSOR-OP-DAC4074BC3B2:blocked",
        baseline_fixture_sha256: "4931621b7c785d1f8a1c62e0bda466655b6f9720dc833801381ed45016376c02",
        overload_id: "zed.native.model.manual_cast.linear.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input_features\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_features\",\"type\":\"nonzero usize\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn manual_cast_linear_exact_native(layer_name: impl Into<String>, input_features: usize, output_features: usize, bias: bool) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructor creates unloaded checked module state and forward casts without mutating stored parameters",
        alias_rule: "canonical cast alias rules apply to immutable parameters and output is fresh",
        shape_rule: "input trailing width, [output,input] weight, and optional [output] bias are checked",
        dtype_rule: "weight and bias cast to the input-selected compute dtype through the canonical cast owner",
        accumulation_dtype: "fixed f32 linear multiply-add order",
        layout_rule: "contiguous logical rows with trailing feature width",
        device_rule: "CPU exact native; uncertified devices return typed unavailable",
        numeric_rule: "delegates the complete equation to the canonical linear kernel",
        tolerance: "absolute 0.00001 forward and 0.003 finite-difference gradient",
        determinism: "fixed row, output-feature, and input-feature order",
        cancellation_points: "before casts, at bounded output features, and before output publication",
        vjp_rule: "delegates analytical input, weight, and optional bias VJP to the linear owner",
        jvp_rule: "delegates analytical input, weight, and optional bias JVP to the linear owner",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/manual_cast_linear.json",
        evidence_fixture_sha256: "05cd5d1319ee9be00adcc1a1cdb88e824cecda5893b621787fc68030f2b57097",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-FDDDAF202C6D",
        baseline_overload_id: "COMFY-TENSOR-OP-FDDDAF202C6D:blocked",
        baseline_fixture_sha256: "c4ded4eb9143807299b3b9928e144ea3b8914e1d46c19cf38a51bc365bc8df1a",
        overload_id: "zed.native.tensor.cast_to_input.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"canonical Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"canonical Tensor\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"non_blocking\",\"type\":\"bool\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"copy\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn cast_to_input_with_context_exact_native(backend: &CpuBackend, weight: &Tensor, input: &Tensor, non_blocking: bool, copy: bool, context: &ExecutionContext<'_>) -> Result<Tensor, OperatorIndirectionError>",
        mutation_rule: "both inputs remain immutable and only a complete converted tensor is published",
        alias_rule: "delegates copy and same-dtype/device identity exactly to cast_to_exact_native",
        shape_rule: "preserves weight rank, dimensions, and logical element order",
        dtype_rule: "destination dtype and device are taken exactly from input",
        accumulation_dtype: "no arithmetic accumulation",
        layout_rule: "logical strided weights are accepted and converted output is contiguous",
        device_rule: "CPU ordinal zero is exact native; uncertified input devices return typed unavailable",
        numeric_rule: "all scalar conversion behavior is owned by canonical DType codecs",
        tolerance: "bit-exact when representable and canonical narrowing otherwise",
        determinism: "fixed row-major logical traversal",
        cancellation_points: "before delegation, at bounded cast elements, and before publication",
        vjp_rule: "inherits floating-cast identity semantics from cast_to_exact_native",
        jvp_rule: "inherits floating tangent conversion from cast_to_exact_native",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/cast_to_input.json",
        evidence_fixture_sha256: "862f04d3e00c627c669bb181b6c5e5becda7f40f126c580125f9ccf20bd2ad5d",
    },
]
