&[
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-A0BD98DDA517",
        baseline_overload_id: "COMFY-TENSOR-OP-A0BD98DDA517:blocked",
        baseline_fixture_sha256: "1934820844d7913041de43538ff3bfac132ff081cea42ff567fb147d78d7e800",
        overload_id: "sim.native.model.zero_init_parameter.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"module\",\"type\":\"mutable NativeModule\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"name\",\"type\":\"weight or bias parameter name\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"fallback_dtype\",\"type\":\"canonical DType\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"fallback_device\",\"type\":\"canonical DeviceId\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn NativeModule::zero_init_parameter_with_context_exact_native(&mut self, backend: &CpuBackend, name: &str, fallback_dtype: DType, fallback_device: DeviceId, context: &ExecutionContext<'_>) -> Result<(), NativeOpsError>",
        mutation_rule: "the complete zero tensor stages first; cancellation or failure leaves parameter state, prefetch state, and generation unchanged",
        alias_rule: "the committed parameter owns fresh canonical zero storage and shares no mutable model mapping",
        shape_rule: "weight or bias shape is derived exclusively from the checked NativeModuleSpec",
        dtype_rule: "an existing dense parameter preserves its dtype and device; an unloaded parameter uses explicit canonical fallback values",
        accumulation_dtype: "no arithmetic accumulation",
        layout_rule: "the zero parameter is canonical contiguous storage",
        device_rule: "CPU ordinal zero is exact native and uncertified devices fail through the canonical tensor owner",
        numeric_rule: "every logical value is positive zero in the requested canonical dtype",
        tolerance: "bit-exact zero",
        determinism: "shape-derived fixed allocation and zero fill",
        cancellation_points: "before shape resolution, during tensor publication, and before the single module-state commit",
        vjp_rule: "parameter materialization is non-differentiable; consuming kernels own gradients",
        jvp_rule: "parameter materialization is non-differentiable; consuming kernels own tangents",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/zero_init_parameter.json",
        evidence_fixture_sha256: "c0b3965cf0b20347245f7613e4218ca8f64dc4a929b25e8e06060f9bed76fd02",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-A553C4928CA6",
        baseline_overload_id: "COMFY-TENSOR-OP-A553C4928CA6:blocked",
        baseline_fixture_sha256: "3f4d86b85accc0eb6005cc9a4a0c85e1d2ed5b718594c164d33b94d7a69e2166",
        overload_id: "sim.native.model.disable_weight_init.conv1d.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"kernel_size\",\"type\":\"nonzero usize\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"stride\",\"type\":\"nonzero usize\"},{\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"padding\",\"type\":\"usize\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dilation\",\"type\":\"nonzero usize\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"groups\",\"type\":\"nonzero usize\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"},{\"default\":\"zeros\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"padding_mode\",\"type\":\"ConvolutionPaddingMode\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_conv1d_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_size: usize, stride: usize, padding: usize, dilation: usize, groups: usize, bias: bool, padding_mode: ConvolutionPaddingMode) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "construction creates unloaded checked module state without random initialization; parameter load is atomic",
        alias_rule: "immutable loaded parameters and fresh forward outputs",
        shape_rule: "NCL grouped cross-correlation uses the canonical checked convolution output formula",
        dtype_rule: "canonical module casts surround the single shared f32 convolution kernel",
        accumulation_dtype: "fixed f32 multiply-add order over input channel and kernel coordinates",
        layout_rule: "contiguous logical NCL input, OIL weight, and NCL output",
        device_rule: "CPU exact native; uncertified devices return typed unavailable",
        numeric_rule: "zero, reflect, replicate, and circular padding map coordinates in the canonical convolution owner",
        tolerance: "absolute 0.00001 forward and 0.003 finite-difference gradient",
        determinism: "fixed batch, output-channel, position, input-channel, and kernel order",
        cancellation_points: "before validation, at bounded output positions, and before publication",
        vjp_rule: "canonical convolution VJP accumulates repeated padded coordinates into the source input",
        jvp_rule: "canonical convolution JVP uses the identical padding-coordinate mapping",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/conv1d.json",
        evidence_fixture_sha256: "fe15f1cce76d97b8a0657eba10a9adbb83b397fe2c282d184e48f684379f116a",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-A88C934F4A40",
        baseline_overload_id: "COMFY-TENSOR-OP-A88C934F4A40:blocked",
        baseline_fixture_sha256: "cda22cee2b6be4a37bc7eb7bc900edb9af283179bcbacc480ec5c597d907ef3c",
        overload_id: "sim.native.model.disable_weight_init.layer_norm.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"normalized_shape\",\"type\":\"nonempty usize dimensions\"},{\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"positive finite f32\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"elementwise_affine\",\"type\":\"bool\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_layer_norm_exact_native(layer_name: impl Into<String>, normalized_shape: Vec<usize>, epsilon: f32, elementwise_affine: bool, bias: bool) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructor is unloaded and performs no random parameter initialization",
        alias_rule: "immutable parameters and fresh normalized output storage",
        shape_rule: "normalized_shape exactly matches trailing input dimensions",
        dtype_rule: "canonical casts delegate normalization arithmetic to the functional layer-normalization owner",
        accumulation_dtype: "inherits functional owner's f64 reductions and f32 affine arithmetic",
        layout_rule: "contiguous logical groups over trailing dimensions",
        device_rule: "CPU exact native; uncertified devices return typed unavailable",
        numeric_rule: "affine and non-affine execution use one canonical functional equation",
        tolerance: "absolute 0.00001 forward and 0.003 gradient",
        determinism: "inherits functional owner reduction order",
        cancellation_points: "before parameter casting, within normalization groups, and before output publication",
        vjp_rule: "delegates analytical VJP to canonical functional layer normalization",
        jvp_rule: "delegates analytical JVP to canonical functional layer normalization",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/layer_norm.json",
        evidence_fixture_sha256: "7cc3fb6a0fef42d7fa83c736cdc34c77d99a466b4f559417e49a58210d1d6c40",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-C9049FCF1A75",
        baseline_overload_id: "COMFY-TENSOR-OP-C9049FCF1A75:blocked",
        baseline_fixture_sha256: "d179ae55f07a7e772abf4cefc735806514caf4c8ca19790a2c128fc64788fc13",
        overload_id: "sim.native.model.disable_weight_init.group_norm.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"groups\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"channels\",\"type\":\"nonzero usize divisible by groups\"},{\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"positive finite f32\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"affine\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_group_norm_exact_native(layer_name: impl Into<String>, groups: usize, channels: usize, epsilon: f32, affine: bool) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructor is unloaded and parameter loading is a separate checked atomic commit",
        alias_rule: "immutable parameters and fresh normalized output storage",
        shape_rule: "input is N,C,* with configured C and channels divisible by groups",
        dtype_rule: "canonical casts delegate normalization arithmetic to the functional group-normalization owner",
        accumulation_dtype: "inherits functional owner's stable group-statistic accumulation",
        layout_rule: "contiguous logical N,C,* groups",
        device_rule: "CPU exact native; uncertified devices return typed unavailable",
        numeric_rule: "affine and non-affine execution use one canonical functional equation",
        tolerance: "absolute 0.00001 forward and 0.003 gradient",
        determinism: "fixed batch, group, channel, and spatial order",
        cancellation_points: "before parameter casting, between groups, and before output publication",
        vjp_rule: "delegates analytical VJP to canonical functional group normalization",
        jvp_rule: "delegates analytical JVP to canonical functional group normalization",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/group_norm.json",
        evidence_fixture_sha256: "5e89c0a6a20aed7430f4a6753f224c9edfbfb0ba666f396b38428ecbd353bee0",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-D63C669FCD27",
        baseline_overload_id: "COMFY-TENSOR-OP-D63C669FCD27:blocked",
        baseline_fixture_sha256: "d8075d9e349d983d810a01c292fc8f1efa58b07a18cadcd8e6751d63ea88dec0",
        overload_id: "sim.native.model.pick_operations.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight_dtype\",\"type\":\"canonical DType\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"compute_dtype\",\"type\":\"optional canonical DType\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"load_device\",\"type\":\"optional canonical DeviceId\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"disable_fast_fp8\",\"type\":\"bool\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"fp8_optimizations\",\"type\":\"bool\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"quant_config\",\"type\":\"optional bounded layer quantization map\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeOperationSet\"]",
        rust_signature: "fn pick_operations_exact_native(weight_dtype: DType, compute_dtype: Option<DType>, load_device: Option<DeviceId>, disable_fast_fp8: bool, fp8_optimizations: bool, quant_config: Option<BTreeMap<String, LayerQuantizationV1>>, cancellation: &CancellationToken) -> Result<NativeOperationSet, NativeOpsError>",
        mutation_rule: "returns immutable validated policy without changing device capabilities, global state, or model parameters",
        alias_rule: "the policy owns bounded metadata and constructed modules use immutable canonical parameter handles",
        shape_rule: "selection is shape-neutral; each constructed NativeModule validates its own shapes",
        dtype_rule: "matching or absent compute dtype selects direct storage, differing dtype selects manual cast, and quant metadata selects mixed precision",
        accumulation_dtype: "the selected compute dtype is explicit and kernel owners define reduction precision",
        layout_rule: "layout selection remains with convolution and quantization owners",
        device_rule: "CPU ordinal zero is certified; other devices return typed unavailable without fallback",
        numeric_rule: "CPU exposes no false fast-FP8 or cuBLAS capability and never selects an unavailable accelerated path",
        tolerance: "selection is exact; selected kernels retain their declared tolerance",
        determinism: "canonical dtype, device, and ordered quantization metadata uniquely determine the result",
        cancellation_points: "before capability and metadata validation and before returning the policy",
        vjp_rule: "selection is non-differentiable; selected kernels own gradients",
        jvp_rule: "selection is non-differentiable; selected kernels own tangents",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/pick_operations.json",
        evidence_fixture_sha256: "fba72bb9727c37615df70a16d55a6fd8e03984e80de56dad347527985b90e7f1",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-DAC4074BC3B2",
        baseline_overload_id: "COMFY-TENSOR-OP-DAC4074BC3B2:blocked",
        baseline_fixture_sha256: "94c25f2f0be573081add1b73896ec74a262f43c18c2b2a99000c4d20a85fe0c5",
        overload_id: "sim.native.model.manual_cast.linear.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input_features\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_features\",\"type\":\"nonzero usize\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn manual_cast_linear_exact_native(layer_name: impl Into<String>, input_features: usize, output_features: usize, bias: bool) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructor creates unloaded checked module state and forward casts without mutating stored parameters",
        alias_rule: "canonical cast alias rules apply to immutable parameters and output is fresh",
        shape_rule: "input trailing width, [output,input] weight, and optional [output] bias are checked",
        dtype_rule: "weight and bias cast to the input-selected compute dtype through the canonical cast owner",
        accumulation_dtype: "fixed f32 linear multiply-add order",
        layout_rule: "contiguous logical rows with trailing feature width",
        device_rule: "CPU exact native; uncertified devices return typed unavailable",
        numeric_rule: "delegates the complete equation to the canonical linear kernel",
        tolerance: "absolute 0.00001 forward and 0.003 finite-difference gradient",
        determinism: "fixed row, output-feature, and input-feature order",
        cancellation_points: "before casts, at bounded output features, and before output publication",
        vjp_rule: "delegates analytical input, weight, and optional bias VJP to the linear owner",
        jvp_rule: "delegates analytical input, weight, and optional bias JVP to the linear owner",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/manual_cast_linear.json",
        evidence_fixture_sha256: "8bd2deb3386a1eb6136c25f45f64c55572da9cba88ccd0e88c02687344a7014b",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_02",
        operation_id: "COMFY-TENSOR-OP-FDDDAF202C6D",
        baseline_overload_id: "COMFY-TENSOR-OP-FDDDAF202C6D:blocked",
        baseline_fixture_sha256: "b35993a0bedaba694345a57afb3c14365c0ca1b565cae512d5c5b67537cc0d38",
        overload_id: "sim.native.tensor.cast_to_input.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"canonical Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"canonical Tensor\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"non_blocking\",\"type\":\"bool\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"copy\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn cast_to_input_with_context_exact_native(backend: &CpuBackend, weight: &Tensor, input: &Tensor, non_blocking: bool, copy: bool, context: &ExecutionContext<'_>) -> Result<Tensor, OperatorIndirectionError>",
        mutation_rule: "both inputs remain immutable and only a complete converted tensor is published",
        alias_rule: "delegates copy and same-dtype/device identity exactly to cast_to_exact_native",
        shape_rule: "preserves weight rank, dimensions, and logical element order",
        dtype_rule: "destination dtype and device are taken exactly from input",
        accumulation_dtype: "no arithmetic accumulation",
        layout_rule: "logical strided weights are accepted and converted output is contiguous",
        device_rule: "CPU ordinal zero is exact native; uncertified input devices return typed unavailable",
        numeric_rule: "all scalar conversion behavior is owned by canonical DType codecs",
        tolerance: "bit-exact when representable and canonical narrowing otherwise",
        determinism: "fixed row-major logical traversal",
        cancellation_points: "before delegation, at bounded cast elements, and before publication",
        vjp_rule: "inherits floating-cast identity semantics from cast_to_exact_native",
        jvp_rule: "inherits floating tangent conversion from cast_to_exact_native",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-a0bd98dda517",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_02/cast_to_input.json",
        evidence_fixture_sha256: "ab87fd1b0df299da183d0c09ad178ef6803f1d79d8fd0cd780a4b685205de9f0",
    },
]
