&[
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-97205767AA40",
        baseline_overload_id: "COMFY-TENSOR-OP-97205767AA40:blocked",
        baseline_fixture_sha256: "4d155ed28c8f31ffeec171d247ddaa0797c35363e12cab409f9630898412c7b2",
        overload_id: "zed.native.model.cast_bias_weight.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"module\",\"type\":\"mutable NativeModule\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"optional canonical Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dtype\",\"type\":\"optional canonical DType\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"optional canonical DeviceId\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias_dtype\",\"type\":\"optional canonical DType\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"offloadable\",\"type\":\"bool\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"compute_dtype\",\"type\":\"optional canonical DType\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"want_requant\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"CastedParameters\"]",
        rust_signature: "fn NativeModule::cast_bias_weight_with_context_exact_native(&mut self, backend: &CpuBackend, input: Option<&Tensor>, dtype: Option<DType>, device: Option<DeviceId>, bias_dtype: Option<DType>, offloadable: bool, compute_dtype: Option<DType>, want_requant: bool, context: &ExecutionContext<'_>) -> Result<CastedParameters, NativeOpsError>",
        mutation_rule: "parameter state is immutable; only a monotonic cast generation advances after complete preparation",
        alias_rule: "matching dense parameters may share immutable storage; requested copies, dtype conversion, and quantized materialization return canonical fresh tensors",
        shape_rule: "loaded module weight and optional bias shapes were transactionally checked against the module specification",
        dtype_rule: "canonical DType inference follows input then explicit overrides; quantized weights delegate dequantization to comfy_model::quantization",
        accumulation_dtype: "no arithmetic reduction; conversion uses the canonical DType scalar codec",
        layout_rule: "logical values are emitted as canonical contiguous tensors without changing module shapes",
        device_rule: "CPU is exact native; uncertified devices return typed unavailable through the tensor cast owner",
        numeric_rule: "dense and quantized parameters preserve canonical conversion semantics without a Python or framework fallback",
        tolerance: "exact canonical codec conversion or the quantization owner's declared format tolerance",
        determinism: "fixed logical element order and immutable quantization metadata",
        cancellation_points: "before preparation, at bounded conversion intervals, and before generation publication",
        vjp_rule: "parameter casting is a storage adapter; gradients belong to the consuming linear, convolution, normalization, or attention operation",
        jvp_rule: "parameter casting is a storage adapter; tangents pass through the consuming differentiable operation",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/cast_bias_weight.json",
        evidence_fixture_sha256: "253441ab4f29c4ac08b818a87f6fbbd9163302f7a88af0cf96f576a1d1ae954b",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-23DA7F686728",
        baseline_overload_id: "COMFY-TENSOR-OP-23DA7F686728:blocked",
        baseline_fixture_sha256: "ec4189b6e460b26bb81f0cb412066002e88399a29a1923f85a3edc893a12ead8",
        overload_id: "zed.native.model.prefetch_modules.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"modules\",\"type\":\"mutable NativeModule slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dtype\",\"type\":\"canonical DType\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"canonical DeviceId\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias_dtype\",\"type\":\"canonical DType\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"non_blocking\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"PrefetchReceipt\"]",
        rust_signature: "fn cast_modules_with_vbar_with_context_exact_native(modules: &mut [NativeModule], backend: &CpuBackend, dtype: DType, device: DeviceId, bias_dtype: DType, non_blocking: bool, context: &ExecutionContext<'_>) -> Result<PrefetchReceipt, NativeOpsError>",
        mutation_rule: "all module conversions stage first and every prefetched projection commits together; failure or cancellation publishes none",
        alias_rule: "prefetched canonical tensors may share immutable matching storage and never expose mutable model mappings",
        shape_rule: "every module must already contain parameters matching its checked specification",
        dtype_rule: "weight and bias conversion delegates exclusively to canonical cast and quantization owners",
        accumulation_dtype: "no numeric reduction",
        layout_rule: "prefetched projections are canonical contiguous tensors",
        device_rule: "CPU executes synchronously; uncertified devices are typed unavailable",
        numeric_rule: "native prefetch replaces VBAR-specific transport while preserving parameter values and atomic visibility",
        tolerance: "exact canonical codec conversion or declared quantization tolerance",
        determinism: "input module order fixes staging and receipt order",
        cancellation_points: "before staging, between modules, and before the atomic publication loop",
        vjp_rule: "prefetch is non-differentiable storage preparation",
        jvp_rule: "prefetch is non-differentiable storage preparation",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/cast_modules_with_vbar.json",
        evidence_fixture_sha256: "17602c8d9e353b22e822b60811f411fac73239f63266fee179b9a649c4cebb79",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-56B106D5BEE7",
        baseline_overload_id: "COMFY-TENSOR-OP-56B106D5BEE7:blocked",
        baseline_fixture_sha256: "2cf277561560e5b231de03c4cfec2c7927d464b5a35ebd439394949cc5aab39b",
        overload_id: "zed.native.tensor.cast_to.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"canonical Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dtype\",\"type\":\"canonical DType\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"canonical DeviceId\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"non_blocking\",\"type\":\"bool\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"copy\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn cast_to_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dtype: DType, device: DeviceId, non_blocking: bool, copy: bool, context: &ExecutionContext<'_>) -> Result<Tensor, OperatorIndirectionError>",
        mutation_rule: "input storage is immutable and conversion publishes only a complete output",
        alias_rule: "same dtype and device with copy false preserves storage identity; every other case returns fresh canonical storage",
        shape_rule: "preserves rank, dimensions, and logical element order including checked strided input traversal",
        dtype_rule: "all canonical scalar dtypes use DType decode and encode semantics; complex-to-real uses the real component and complex-to-complex preserves both components",
        accumulation_dtype: "no arithmetic accumulation",
        layout_rule: "logical strided input is accepted and converted output is contiguous",
        device_rule: "CPU ordinal zero is exact native; all uncertified devices return typed unavailable",
        numeric_rule: "conversion uses checked integer bounds, canonical float and float8 codecs, and canonical Boolean conversion",
        tolerance: "bit-exact for exactly representable values and canonical rounding for narrowed formats",
        determinism: "fixed row-major logical traversal",
        cancellation_points: "before allocation, every 256 logical elements, after the backend fence, and before publication",
        vjp_rule: "identity for differentiable floating casts with the inverse storage cast; integer and Boolean casts are non-differentiable",
        jvp_rule: "floating tangents use the same destination cast; integer and Boolean casts have no tangent",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/cast_to.json",
        evidence_fixture_sha256: "16f84f4d94ac0008e4881daded9a0228ebaacd11dc4cbacb723403df1dd9c236",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-4B62764DCD01",
        baseline_overload_id: "COMFY-TENSOR-OP-4B62764DCD01:blocked",
        baseline_fixture_sha256: "550c303b8510b33ddbe04491324da95c6b47f560b59ef11761a562d51c0bdf01",
        overload_id: "zed.native.model.disable_weight_init.conv2d.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"kernel_shape\",\"type\":\"two nonzero usize dimensions\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"stride\",\"type\":\"two nonzero usize dimensions\"},{\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"padding\",\"type\":\"two usize dimensions\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dilation\",\"type\":\"two nonzero usize dimensions\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"groups\",\"type\":\"nonzero usize\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_convolution_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_shape: Vec<usize>, bias: bool, geometry: ConvolutionGeometry) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "construction creates an unloaded checked module; parameter loading is a separate atomic commit and performs no random initialization",
        alias_rule: "loaded parameters are immutable canonical handles and forward returns fresh output storage",
        shape_rule: "NCHW grouped convolution uses the checked PyTorch output formula for stride, padding, dilation, and kernel extent",
        dtype_rule: "module storage uses canonical DType conversion and exact kernel arithmetic uses f32 values before output recasting",
        accumulation_dtype: "fixed f32 multiply-add order over group, input channel, and kernel coordinates",
        layout_rule: "contiguous logical NCHW input, OIHW weight, and NCHW output",
        device_rule: "CPU exact native; uncertified devices return typed unavailable",
        numeric_rule: "zero-padding grouped cross-correlation with optional channel bias",
        tolerance: "absolute 0.00001 for forward and 0.003 for finite-difference gradients",
        determinism: "fixed batch, output-channel, spatial, input-channel, and kernel order",
        cancellation_points: "before validation and at bounded output-coordinate intervals before publication",
        vjp_rule: "analytical input, weight, and optional bias VJP uses the exact forward connection map",
        jvp_rule: "analytical input, weight, and optional bias JVP uses the exact forward connection map",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/conv2d.json",
        evidence_fixture_sha256: "eee683c919d136dd9d554fe204c91c1519c0456430588ec92670fb37b764f09c",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-6CF91D19480B",
        baseline_overload_id: "COMFY-TENSOR-OP-6CF91D19480B:blocked",
        baseline_fixture_sha256: "9144b6b3afff976634d2e7e9b1a43d0a77cbc0ca6e5b2a3f20170cd3c75e7fd2",
        overload_id: "zed.native.model.disable_weight_init.conv3d.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"kernel_shape\",\"type\":\"three nonzero usize dimensions\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"stride\",\"type\":\"three nonzero usize dimensions\"},{\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"padding\",\"type\":\"three usize dimensions\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dilation\",\"type\":\"three nonzero usize dimensions\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"groups\",\"type\":\"nonzero usize\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_convolution_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_shape: Vec<usize>, bias: bool, geometry: ConvolutionGeometry) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "construction creates an unloaded checked module without random initialization; parameter loading commits atomically",
        alias_rule: "loaded parameters remain immutable and output storage is fresh",
        shape_rule: "NCDHW grouped convolution uses checked stride, padding, dilation, and kernel formulas over three spatial dimensions",
        dtype_rule: "canonical storage conversion surrounds an exact f32 reference kernel",
        accumulation_dtype: "fixed f32 multiply-add order",
        layout_rule: "contiguous logical NCDHW input, OIDHW weight, and NCDHW output",
        device_rule: "CPU exact native; uncertified devices are typed unavailable",
        numeric_rule: "zero-padding grouped three-dimensional cross-correlation with optional bias",
        tolerance: "absolute 0.00001 for forward and 0.003 for finite-difference gradients",
        determinism: "fixed coordinate and channel order",
        cancellation_points: "before validation and at bounded output-coordinate intervals",
        vjp_rule: "analytical input, weight, and optional bias VJP shares the forward connection map",
        jvp_rule: "analytical input, weight, and optional bias JVP shares the forward connection map",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/conv3d.json",
        evidence_fixture_sha256: "8634c7094987c4a916ffa0fbdbc2a678e8365e41aabdd4f1870c8941006acc2c",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-227F5D04687A",
        baseline_overload_id: "COMFY-TENSOR-OP-227F5D04687A:blocked",
        baseline_fixture_sha256: "c8dc41fc9fc239e4b916293efb330b55ce660f233f9cfa42a8736ddb131c6250",
        overload_id: "zed.native.model.disable_weight_init.conv_transpose1d.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"kernel_shape\",\"type\":\"one nonzero usize dimension\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"stride\",\"type\":\"one nonzero usize dimension\"},{\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"padding\",\"type\":\"one usize dimension\"},{\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_padding\",\"type\":\"one usize dimension smaller than stride\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"groups\",\"type\":\"nonzero usize\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_convolution_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_shape: Vec<usize>, bias: bool, geometry: ConvolutionGeometry) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructor performs no random initialization and later parameter loading commits atomically",
        alias_rule: "immutable loaded parameters and fresh output storage",
        shape_rule: "NCW transposed convolution uses (input-1)*stride-2*padding+dilation*(kernel-1)+output_padding+1",
        dtype_rule: "canonical storage conversion surrounds the f32 reference kernel",
        accumulation_dtype: "fixed f32 scatter-add order",
        layout_rule: "contiguous logical NCW input, IO-group-W weight, and NCW output",
        device_rule: "CPU exact native; uncertified devices are typed unavailable",
        numeric_rule: "grouped transposed convolution scatter-adds weight connections then channel bias",
        tolerance: "absolute 0.00001 forward and 0.003 gradient",
        determinism: "fixed input, output-channel, and kernel order",
        cancellation_points: "before validation and at bounded input-coordinate intervals",
        vjp_rule: "analytical input, weight, and optional bias VJP shares the transposed connection map",
        jvp_rule: "analytical input, weight, and optional bias JVP shares the transposed connection map",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/conv_transpose1d.json",
        evidence_fixture_sha256: "60b53da1e45be63bef90302c0da989719dea3674acc5e98cd8d8c5a2042ef82d",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-6F126397E86F",
        baseline_overload_id: "COMFY-TENSOR-OP-6F126397E86F:blocked",
        baseline_fixture_sha256: "1fbb7a54ab225107df0c7c00f80b403c0b21f6a34f60ecdbddb3c8a06948fd1b",
        overload_id: "zed.native.model.disable_weight_init.conv_transpose2d.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_channels\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"kernel_shape\",\"type\":\"two nonzero usize dimensions\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"stride\",\"type\":\"two nonzero usize dimensions\"},{\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"padding\",\"type\":\"two usize dimensions\"},{\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_padding\",\"type\":\"two usize dimensions smaller than stride\"},{\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"groups\",\"type\":\"nonzero usize\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_convolution_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_shape: Vec<usize>, bias: bool, geometry: ConvolutionGeometry) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructor performs no random initialization and parameter loading is atomic",
        alias_rule: "immutable loaded parameters and fresh output storage",
        shape_rule: "NCHW transposed convolution applies the checked PyTorch output formula independently per spatial dimension",
        dtype_rule: "canonical storage conversion surrounds the f32 reference kernel",
        accumulation_dtype: "fixed f32 scatter-add order",
        layout_rule: "contiguous logical NCHW input, IO-group-HW weight, and NCHW output",
        device_rule: "CPU exact native; uncertified devices are typed unavailable",
        numeric_rule: "grouped transposed convolution scatter-adds weight connections then channel bias",
        tolerance: "absolute 0.00001 forward and 0.003 gradient",
        determinism: "fixed input, output-channel, and kernel order",
        cancellation_points: "before validation and at bounded input-coordinate intervals",
        vjp_rule: "analytical input, weight, and optional bias VJP shares the transposed connection map",
        jvp_rule: "analytical input, weight, and optional bias JVP shares the transposed connection map",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/conv_transpose2d.json",
        evidence_fixture_sha256: "1fe0c99bc7cca313029c28ec622d474a1fd0d8799636c630cf06d971274d4506",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-5D8E418C8374",
        baseline_overload_id: "COMFY-TENSOR-OP-5D8E418C8374:blocked",
        baseline_fixture_sha256: "11f2f29899ede776104baf099e56d142e47ed7ada7ddbd62ff9130961c296038",
        overload_id: "zed.native.model.disable_weight_init.linear.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input_features\",\"type\":\"nonzero usize\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"output_features\",\"type\":\"nonzero usize\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn disable_weight_init_linear_exact_native(layer_name: impl Into<String>, input_features: usize, output_features: usize, bias: bool) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructor creates unloaded shape metadata without random initialization; dense or quantized parameter load commits atomically",
        alias_rule: "immutable parameter handles and fresh output storage",
        shape_rule: "input trailing dimension equals input_features, weight is [output_features,input_features], and optional bias is [output_features]",
        dtype_rule: "canonical storage casts surround a contiguous f32 reference kernel and quantized storage delegates to comfy_model::quantization",
        accumulation_dtype: "fixed f32 multiply-add order over input features",
        layout_rule: "contiguous logical rows with the trailing feature dimension",
        device_rule: "CPU exact native; uncertified devices return typed unavailable",
        numeric_rule: "output equals input times weight transpose plus optional bias",
        tolerance: "absolute 0.00001 forward and 0.003 finite-difference gradient",
        determinism: "fixed row, output-feature, and input-feature order",
        cancellation_points: "before validation and every bounded output row-feature interval",
        vjp_rule: "analytical input, weight, and optional bias VJP",
        jvp_rule: "analytical input, weight, and optional bias JVP",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/linear.json",
        evidence_fixture_sha256: "5472601beadaadd27743c81295db3fd55f844760f648d88d5dbdc53ddfb7be3e",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-7ADDDB2261D6",
        baseline_overload_id: "COMFY-TENSOR-OP-7ADDDB2261D6:blocked",
        baseline_fixture_sha256: "af298ddfc0131d0bb722701e980bd84741b17d5824a46642390cdcd9b0315715",
        overload_id: "zed.native.model.manual_cast.layer_norm.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"normalized_shape\",\"type\":\"nonempty usize dimensions\"},{\"default\":1e-05,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"epsilon\",\"type\":\"positive finite f32\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"elementwise_affine\",\"type\":\"bool\"},{\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"bias\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn manual_cast_layer_norm_exact_native(layer_name: impl Into<String>, normalized_shape: Vec<usize>, epsilon: f32, elementwise_affine: bool, bias: bool) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructor is unloaded and forward casts immutable parameters without mutating module storage",
        alias_rule: "parameter casts follow canonical cast alias rules and normalized output is fresh",
        shape_rule: "normalized_shape exactly matches trailing input dimensions and affine parameters match its checked product",
        dtype_rule: "module casts through canonical DType then delegates all normalization arithmetic to the functional layer-normalization owner",
        accumulation_dtype: "f64 reductions and f32 affine arithmetic owned by functional layer normalization",
        layout_rule: "contiguous logical input with trailing normalization groups",
        device_rule: "CPU exact native; uncertified devices are typed unavailable",
        numeric_rule: "no local normalization equation exists; the adapter invokes the canonical checked functional owner",
        tolerance: "absolute 0.00001 forward and 0.003 gradient",
        determinism: "inherits canonical layer-normalization reduction order",
        cancellation_points: "before parameter casting, within canonical normalization groups, and before output recast",
        vjp_rule: "delegates the analytical layer-normalization VJP to the canonical functional owner",
        jvp_rule: "delegates the analytical layer-normalization JVP to the canonical functional owner",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/manual_cast_layer_norm.json",
        evidence_fixture_sha256: "0708605a7a58c72262fc193189d9a6a433db24a3fa117df20d80211612065886",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-4C30712EC2F7",
        baseline_overload_id: "COMFY-TENSOR-OP-4C30712EC2F7:blocked",
        baseline_fixture_sha256: "91ccb9302104fea3bf2886932096730205c448caf328ca4fb484ce1c4f978f02",
        overload_id: "zed.native.model.mixed_precision_ops.v1",
        ordered_parameters_json: "[{\"default\":{},\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"quant_config\",\"type\":\"bounded layer quantization map\"},{\"default\":\"bfloat16\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"compute_dtype\",\"type\":\"F16, Bf16, or F32 DType\"},{\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"full_precision_matrix_multiply\",\"type\":\"bool\"},{\"default\":[],\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"disabled\",\"type\":\"QuantizationKind set\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeOperationSet\"]",
        rust_signature: "fn mixed_precision_ops_exact_native(quant_config: BTreeMap<String, LayerQuantizationV1>, compute_dtype: DType, full_precision_matrix_multiply: bool, disabled: BTreeSet<QuantizationKind>) -> Result<NativeOperationSet, NativeOpsError>",
        mutation_rule: "returns immutable validated operation-set configuration and mutates no model or global capability state",
        alias_rule: "operation sets own bounded metadata and modules retain immutable parameter handles",
        shape_rule: "per-layer shapes are validated when modules load their dense or quantized parameters",
        dtype_rule: "compute dtype is one of F16, Bf16, or F32 and quantization metadata delegates to the canonical model quantization owner",
        accumulation_dtype: "selected by explicit compute dtype or full-precision matrix-multiply policy",
        layout_rule: "quantized layout interpretation remains exclusively in comfy_model::quantization",
        device_rule: "configuration is device-neutral; module dispatch requires a certified tensor backend",
        numeric_rule: "INT8, MXFP8, NVFP4, and mixed-per-layer values are interpreted only by the canonical quantization implementation",
        tolerance: "inherits each canonical quantization format's declared error bound",
        determinism: "version-one metadata and ordered layer maps provide stable selection",
        cancellation_points: "configuration validation allocates no tensor work; module materialization checks cancellation through canonical owners",
        vjp_rule: "the operation-set selector is non-differentiable; module kernels own gradients",
        jvp_rule: "the operation-set selector is non-differentiable; module kernels own tangents",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/mixed_precision_ops.json",
        evidence_fixture_sha256: "6ff89b6ad202387fcdb6a51eac9a68ab390236219dcab64d60afbdaa21b8f5b8",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-5EAFEF13DE9D",
        baseline_overload_id: "COMFY-TENSOR-OP-5EAFEF13DE9D:blocked",
        baseline_fixture_sha256: "2f8baba68bc29eff122bd6c047e23c18ef77efb2a54e84b6440aa16f0c875677",
        overload_id: "zed.native.tensor.scaled_dot_product_attention.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"request\",\"type\":\"AttentionKernelRequest\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"query\",\"type\":\"contiguous f32 slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"key\",\"type\":\"contiguous f32 slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"value\",\"type\":\"contiguous f32 slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"mask\",\"type\":\"optional checked attention mask\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn scaled_dot_product_attention_with_context_exact_native(backend: &CpuBackend, request: AttentionKernelRequest, query: &[f32], key: &[f32], value: &[f32], mask: Option<AttentionMask>, context: &ExecutionContext<'_>) -> Result<Vec<f32>, OperatorIndirectionError>",
        mutation_rule: "out-of-place and input slices remain immutable",
        alias_rule: "returns fresh owned values",
        shape_rule: "delegates all batch, token, head, dimension, layout, causal, and mask validation to CheckedAttentionInvocation",
        dtype_rule: "exact checked slice accepts contiguous f32 values",
        accumulation_dtype: "f32 dot products, stable softmax, and value projection in the canonical attention owner",
        layout_rule: "NHD or HND as explicitly selected by the checked request",
        device_rule: "canonical attention owner validates CPU and certified adapter availability",
        numeric_rule: "this is a zero-logic facade over the sole checked attention mechanics owner",
        tolerance: "absolute 0.00001 forward and 0.003 finite-difference gradient",
        determinism: "inherits fixed canonical attention reduction order and requires zero dropout",
        cancellation_points: "inherits per-row canonical attention cancellation boundaries",
        vjp_rule: "delegates analytical query, key, and value VJP to CheckedAttentionInvocation",
        jvp_rule: "delegates analytical query, key, and value JVP to CheckedAttentionInvocation",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/scaled_dot_product_attention.json",
        evidence_fixture_sha256: "82222ab5fca77f5574a313c58a12cd733c30076dc29805e198cc1ef9ba7a4db3",
    },
    ResolvedOperationContract {
        resolution_module: "comfy_operator_indirection_01",
        operation_id: "COMFY-TENSOR-OP-86BEA4A2DC25",
        baseline_overload_id: "COMFY-TENSOR-OP-86BEA4A2DC25:blocked",
        baseline_fixture_sha256: "db89afba5fa3bb2f5406917cc88470fb97f0c0a9ca5b0ffeb686a151864b1b78",
        overload_id: "zed.native.model.finish_weight_cast.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"casted_parameters\",\"type\":\"mutable CastedParameters\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"cancellation\",\"type\":\"canonical CancellationToken\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn CastedParameters::finish(&mut self, cancellation: &CancellationToken) -> Result<(), NativeOpsError>",
        mutation_rule: "marks exactly one cast lease complete after its synchronization boundary; repeated completion is rejected",
        alias_rule: "completion changes no tensor value or storage identity and releases temporary ownership by normal Rust lifetime",
        shape_rule: "not shape-bearing",
        dtype_rule: "not dtype-bearing",
        accumulation_dtype: "none",
        layout_rule: "not layout-bearing",
        device_rule: "CPU completion is synchronous; later certified adapters attach their fence to the same lease abstraction",
        numeric_rule: "performs no numeric operation",
        tolerance: "exact state transition",
        determinism: "one monotonic lease transition",
        cancellation_points: "before lease completion; cancellation leaves the lease incomplete and tensor values untouched",
        vjp_rule: "lease completion is non-differentiable",
        jvp_rule: "lease completion is non-differentiable",
        owner_task_id: "comfy-parity-tensor-ops-comfy-operator-indirection-comfy-tensor-op-227f5d04687a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/comfy_operator_indirection_01/uncast_bias_weight.json",
        evidence_fixture_sha256: "7626b082fe9814f0fc2c27a9fb4d89f9c6f21258f540845436fd17f61071c916",
    },
]
