&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-FB884955DE1E",
        baseline_overload_id: "COMFY-TENSOR-OP-FB884955DE1E:blocked",
        baseline_fixture_sha256: "62b4f7121ca4d9cf87b506b90645308b7779471be74264afeafb587aafb3bbe5",
        overload_id: "zed.native.tensor.argsort.method-canonical.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<real|integer|bool>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":-1,"keyword_only":true},{"name":"descending","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"stable","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn argsort_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, descending: bool, stable: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place",
        alias_rule: "thin adapter over the canonical Task 57 argsort owner and its fresh index storage",
        shape_rule: "preserves input shape with a checked negative dimension",
        dtype_rule: "real, integer, or boolean input; I64 indices",
        accumulation_dtype: "not applicable",
        layout_rule: "logical source traversal and contiguous output",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "canonical total ordering, NaN placement, and stable source-index tie behavior",
        tolerance: "exact indices",
        determinism: "canonical argsort ordering",
        cancellation_points: "before adapter dispatch and at canonical per-lane boundaries",
        vjp_rule: "non-differentiable discrete indices",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/argsort_method.json",
        evidence_fixture_sha256: "2801f6a637cbce8902bac98a2fbc0796addbe3223aae1442edb68e2a6fb9bcad",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F2D7AE6E8F48",
        baseline_overload_id: "COMFY-TENSOR-OP-F2D7AE6E8F48:blocked",
        baseline_fixture_sha256: "0f971c5db11df67a8362305ed0efd241fef085df8764e3f045b155da583ccc33",
        overload_id: "zed.native.tensor.floor.method-canonical.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<real>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<input dtype>"]"#,
        rust_signature: "fn floor_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place",
        alias_rule: "thin method adapter over the canonical Task 45 floor owner",
        shape_rule: "preserves shape including empty tensors",
        dtype_rule: "preserves supported real dtype; certified derivatives use F32",
        accumulation_dtype: "F64 decode for forward rounding and F32 derivative zeros",
        layout_rule: "logical traversal and canonical output",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "rounds each finite value toward negative infinity and preserves canonical NaN/Inf handling",
        tolerance: "bit exact encoded result",
        determinism: "fixed logical element order",
        cancellation_points: "canonical bounded traversal and before publication",
        vjp_rule: "zero tensor after output-gradient geometry validation",
        jvp_rule: "zero tensor after tangent geometry validation",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/floor_method.json",
        evidence_fixture_sha256: "9256ee0c76898c9c87bf24be40b146f73369883434a448d5808d4658cdb8c65d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F1F71360D559",
        baseline_overload_id: "COMFY-TENSOR-OP-F1F71360D559:blocked",
        baseline_fixture_sha256: "d2302800925df99aa76339d9add1236918ab4778e30bbb391972bcacddac1601",
        overload_id: "zed.native.tensor.t.read-only-view.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<rank<=2>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<input dtype>"]"#,
        rust_signature: "fn t_method_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "read only",
        alias_rule: "rank-zero and rank-one tensors return a read-only identity view; matrices reuse canonical swapaxes storage sharing",
        shape_rule: "rank zero and one preserve shape; rank two swaps dimensions; higher ranks are rejected",
        dtype_rule: "preserves input dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "checked read-only strided view",
        device_rule: "preserves native device and stream",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "descriptor-only transformation",
        cancellation_points: "before validation and after view construction",
        vjp_rule: "applies t() to the output gradient",
        jvp_rule: "applies t() to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/t_method.json",
        evidence_fixture_sha256: "be04fcc4e71a53ed5c69ec3f96b0251b36b692782da4c648d20063500f195a41",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F56BA497ED13",
        baseline_overload_id: "COMFY-TENSOR-OP-F56BA497ED13:blocked",
        baseline_fixture_sha256: "1f5dc6aad251d3d7bdb5149dae487c7377316b7ab795791c595a3ed3d8543a3f",
        overload_id: "zed.native.tensor.arccos.canonical-acos.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn arccos_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place",
        alias_rule: "thin function alias over the canonical Task 44 acos owner",
        shape_rule: "preserves shape",
        dtype_rule: "certified CPU F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "logical traversal and contiguous output",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "native acos with canonical NaN outside [-1,1]",
        tolerance: "1e-5 absolute",
        determinism: "fixed element order",
        cancellation_points: "canonical backend bounded kernel points",
        vjp_rule: "-output_gradient/sqrt(1-input^2)",
        jvp_rule: "the same derivative multiplied by input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/arccos.json",
        evidence_fixture_sha256: "82595efcb98748d3cf80d4ba7bf738f99b5621e16d47e894e62f55cf75ed4572",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-FBA06A1411DE",
        baseline_overload_id: "COMFY-TENSOR-OP-FBA06A1411DE:blocked",
        baseline_fixture_sha256: "7ba364b5360de4adfc197603b21391d70351117a0fd4920501ecd98b47d25ec1",
        overload_id: "zed.native.tensor.cuda-amp-autocast.policy-adapter.v1",
        ordered_parameters_json: r#"[{"name":"enabled","kind":"keyword_only","type":"bool","default":true,"keyword_only":true},{"name":"dtype","kind":"keyword_only","type":"Option<DType>","default":null,"keyword_only":true},{"name":"cache_enabled","kind":"keyword_only","type":"Option<bool>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["AutocastPolicy"]"#,
        rust_signature: "fn cuda_amp_autocast_exact_native(enabled: bool, dtype: Option<DType>, cache_enabled: Option<bool>, cancellation: &CancellationToken) -> Result<AutocastPolicy, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "constructs immutable request-scoped policy",
        alias_rule: "thin legacy CUDA namespace adapter over canonical AutocastPolicy",
        shape_rule: "not applicable",
        dtype_rule: "defaults CUDA autocast to F16 and validates canonical supported autocast dtypes",
        accumulation_dtype: "policy only",
        layout_rule: "not applicable",
        device_rule: "CUDA policy namespace without process-global state",
        numeric_rule: "no tensor arithmetic",
        tolerance: "exact policy fields",
        determinism: "pure policy construction",
        cancellation_points: "before construction and before return",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/cuda_amp_autocast.json",
        evidence_fixture_sha256: "8bfb1983523f4ccc9bf6c84f487d4820913a7bd31cef4d2bc118af8220dc2e2e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F9ED42F7BFDF",
        baseline_overload_id: "COMFY-TENSOR-OP-F9ED42F7BFDF:blocked",
        baseline_fixture_sha256: "16ceed9ec7329e6d3556c83f12a4a35c38f034ccb91908258ebcd56256222b4a",
        overload_id: "zed.native.device.cuda-name.capability-adapter.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["String"]"#,
        rust_signature: "fn cuda_get_device_name_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<String, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "read only",
        alias_rule: "returns an owned projection from canonical NativeDeviceProperties",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires an exact CUDA or ROCm capability matrix and matching DeviceId",
        numeric_rule: "exact ordinal and kind validation",
        tolerance: "exact UTF-8 name",
        determinism: "immutable capability projection",
        cancellation_points: "before security validation and before return",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/cuda_get_device_name.json",
        evidence_fixture_sha256: "31371d032ee8c5594432914da1bac52fb6716791e442c34a44de9d5dac538e61",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F18E1AE1B857",
        baseline_overload_id: "COMFY-TENSOR-OP-F18E1AE1B857:blocked",
        baseline_fixture_sha256: "3bcffad249753934338d3447232d9d5705cf552af67205824a9624e9010042ce",
        overload_id: "zed.native.worker.cuda-memory-stats.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["BTreeMap<String, u64>"]"#,
        rust_signature: "fn comfy_worker::cuda_memory_stats_exact_native(capabilities: &BackendCapabilityMatrix, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<BTreeMap<String, u64>, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "device-kind adapter over authoritative MemoryAccountingSnapshot",
        shape_rule: "not applicable",
        dtype_rule: "u64 byte counters",
        accumulation_dtype: "u64",
        layout_rule: "stable named-stat map",
        device_rule: "requires canonical CUDA or ROCm capability ownership",
        numeric_rule: "reports active and reserved bytes from authoritative worker accounting",
        tolerance: "exact integers",
        determinism: "snapshot-derived stable map",
        cancellation_points: "before device validation, before accounting lookup, and before publication",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/cuda_memory_stats.json",
        evidence_fixture_sha256: "a589b4c27ae0cdce27b98ba06c15e70799ee077da4411ca96bf6632e00d99175",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-FA7DD244B7CA",
        baseline_overload_id: "COMFY-TENSOR-OP-FA7DD244B7CA:blocked",
        baseline_fixture_sha256: "79107bbc308c7aecdff95b0765a252b2801637b098d9e9a1bce43f02aaa0ce31",
        overload_id: "zed.native.tensor.exp.function-out-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"out","kind":"keyword_only","type":"Option<&mut Tensor>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn exp_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, out: Option<&mut Tensor>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place when out is absent; atomic whole-handle replacement when out is present",
        alias_rule: "canonical Task 63 exp output; out and return share its completed storage",
        shape_rule: "preserves input shape and resizes the Rust out handle atomically",
        dtype_rule: "certified CPU F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical exp contiguous output",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "canonical CpuBackend exponential unary kernel",
        tolerance: "1e-5 absolute",
        determinism: "fixed element order",
        cancellation_points: "canonical kernel boundaries and immediately before optional out publication",
        vjp_rule: "when out is absent, output_gradient multiplied by exp(input); out form is non-autograd",
        jvp_rule: "when out is absent, input_tangent multiplied by exp(input); out form is non-autograd",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/exp_function.json",
        evidence_fixture_sha256: "252d43cd530e0d5afed142eaf4ac64dc26925958ac2804f53adb48cb3f372eaf",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F27D07B4E10D",
        baseline_overload_id: "COMFY-TENSOR-OP-F27D07B4E10D:blocked",
        baseline_fixture_sha256: "26ac4dfe27c28b4b630bf6e09122388be158add7d4a2b9d7fea2924894f38ac4",
        overload_id: "zed.native.tensor.lerp.function-canonical.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"end","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"weight","kind":"positional_or_keyword","type":"f32","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn lerp_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, end: &Tensor, weight: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place",
        alias_rule: "thin function adapter over canonical Task 55 lerp",
        shape_rule: "canonical binary broadcast of input and end",
        dtype_rule: "certified CPU F32 operands and scalar weight",
        accumulation_dtype: "F32",
        layout_rule: "logical broadcast traversal and contiguous output",
        device_rule: "co-located CPU ordinal zero and one source stream",
        numeric_rule: "input + weight * (end - input)",
        tolerance: "1e-5 absolute",
        determinism: "fixed broadcast element order",
        cancellation_points: "canonical bounded traversal and before publication",
        vjp_rule: "reduces (1-weight)*gradient and weight*gradient across broadcast axes",
        jvp_rule: "lerps input and end tangents with the same scalar weight",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/lerp.json",
        evidence_fixture_sha256: "39459a9e427dcdc37b3c4e48e8640550f63b835b84fa54521b24ed2bb6b32b3f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F15A2D8A6BD4",
        baseline_overload_id: "COMFY-TENSOR-OP-F15A2D8A6BD4:blocked",
        baseline_fixture_sha256: "9452114d5ea4ba540cdfbddaff56d0c0f21ef8704f82b1dbf96da0e5ebc14d87",
        overload_id: "zed.native.worker.npu-mem-get-info.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"topology","kind":"positional_or_keyword","type":"MemoryTopology","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["(u64, u64)"]"#,
        rust_signature: "fn comfy_worker::npu_mem_get_info_exact_native(capabilities: &BackendCapabilityMatrix, topology: &MemoryTopology, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<(u64, u64), NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "thin NPU adapter over canonical topology and memory-accounting owners",
        shape_rule: "not applicable",
        dtype_rule: "u64 byte counts",
        accumulation_dtype: "checked u64 subtraction",
        layout_rule: "not applicable",
        device_rule: "requires an exact NPU capability, unique topology budget, and accounting entry",
        numeric_rule: "returns capacity minus active bytes and total capacity",
        tolerance: "exact integers",
        determinism: "immutable topology and snapshot projection",
        cancellation_points: "before device validation, before lookup, and before return",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/npu_mem_get_info.json",
        evidence_fixture_sha256: "eaf4babb09923083d789ac20c3c7d681f2d2aed086886cdfd23d77097798659e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-FACB7FC5B252",
        baseline_overload_id: "COMFY-TENSOR-OP-FACB7FC5B252:blocked",
        baseline_fixture_sha256: "53b29626bd9c2df00cb0b98789867a8741ad1e20fa2516026d9d680f65db376f",
        overload_id: "zed.native.device.xpu-select-capabilities.v1",
        ordered_parameters_json: r#"[{"name":"available","kind":"positional_or_keyword","type":"&[BackendCapabilityMatrix]","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["&BackendCapabilityMatrix"]"#,
        rust_signature: "fn xpu_set_device_exact_native(available: &[BackendCapabilityMatrix], device: DeviceId, cancellation: &CancellationToken) -> Result<&BackendCapabilityMatrix, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "functional request-scoped selection with no process-global mutable state",
        alias_rule: "borrows the one exact canonical capability matrix",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires a unique configured XPU DeviceId",
        numeric_rule: "exact device identity comparison",
        tolerance: "exact identity",
        determinism: "unique capability selection",
        cancellation_points: "before selection and before return",
        vjp_rule: "device selection is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/xpu_set_device.json",
        evidence_fixture_sha256: "1c6c4f2ec3eaa0bfd161a8dae32cf989da764f45d6d2099104a37a4232a44b22",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F3D0014DD82A",
        baseline_overload_id: "COMFY-TENSOR-OP-F3D0014DD82A:blocked",
        baseline_fixture_sha256: "4bb95e41c783f5c0f41bad2a5262c4e7d7ae29d569b96204e705251ebc52c88a",
        overload_id: "zed.native.tensor.zeros-like.preserve-format.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"Option<DType>","default":null,"keyword_only":true},{"name":"device","kind":"keyword_only","type":"Option<DeviceId>","default":null,"keyword_only":true},{"name":"memory_format","kind":"keyword_only","type":"Option<MemoryFormatReference>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn zeros_like_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dtype: Option<DType>, device: Option<DeviceId>, memory_format: Option<MemoryFormatReference>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh backend-owned zero-filled storage",
        shape_rule: "preserves input shape including empty tensors",
        dtype_rule: "preserves input dtype unless an explicit canonical dtype is requested",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves non-overlapping input format by default; supports contiguous and channels-last named formats",
        device_rule: "preserves input device unless explicit; certified native CPU allocation rejects external fallback",
        numeric_rule: "every logical element is the exact zero encoding for the output dtype",
        tolerance: "bit exact",
        determinism: "descriptor-derived fill",
        cancellation_points: "before descriptor admission, at backend fill boundaries, and before publication",
        vjp_rule: "constant creation has no input gradient",
        jvp_rule: "constant creation has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/zeros_like.json",
        evidence_fixture_sha256: "5a7ddc1a682bbdfbcf731f364736768c59b1e8423e028154e177f6585011b46d",
    },
]
