&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-1599F5E140D0",
        baseline_overload_id: "COMFY-TENSOR-OP-1599F5E140D0:blocked",
        baseline_fixture_sha256: "a6455c4c4e853603b72b3d7bf440a3e96a7e13d2791fe2dab37d6fe66d36aaa7",
        overload_id: "zed.native.tensor.ceil.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"real Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn ceil_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place; the input handle and storage are unchanged",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "output shape exactly equals input shape, including scalar and empty tensors",
        dtype_rule: "preserves canonical real, integer, and boolean dtypes; complex input fails typed",
        accumulation_dtype: "no accumulation; the certified derivative overload uses f32",
        layout_rule: "logical values are projected to canonical contiguous output",
        device_rule: "CPU ordinal zero is certified; other devices fail typed",
        numeric_rule: "floating values use IEEE ceiling while integers and booleans are copied exactly; signed zero is preserved",
        tolerance: "canonical dtype encoding is exact",
        determinism: "fixed row-major scalar-codec traversal",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "the certified f32 VJP is a zero tensor because ceiling is piecewise constant",
        jvp_rule: "the certified f32 JVP is a zero tensor because ceiling is piecewise constant",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/ceil.json",
        evidence_fixture_sha256: "c7d38b9b6021f91628711477959c0b52348a3d804a571f8b3ad48960eade465d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-10FC4A6ED9AA",
        baseline_overload_id: "COMFY-TENSOR-OP-10FC4A6ED9AA:blocked",
        baseline_fixture_sha256: "10a67ce7ade987ce3550d48114e5d6215edcc2136a0fabb7bcc9fc5245fc369d",
        overload_id: "zed.native.tensor.tanh.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<f32>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn tanh_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "output shape exactly equals input shape",
        dtype_rule: "the certified CPU overload accepts and returns f32",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "uses the canonical CPU hyperbolic-tangent primitive with IEEE NaN and signed-zero behavior",
        tolerance: "one micro-unit absolute tolerance against the checked f32 profile",
        determinism: "fixed canonical backend traversal",
        cancellation_points: "before dispatch, inside the backend loop, and before publication",
        vjp_rule: "output gradient is multiplied by one minus tanh(input) squared",
        jvp_rule: "input tangent is multiplied by one minus tanh(input) squared",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/tanh.json",
        evidence_fixture_sha256: "5dfe63adc6c714bcaa9d063f4e4fd96fe5ad342687694ae086691341e68e441a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-0FB8594194A8",
        baseline_overload_id: "COMFY-TENSOR-OP-0FB8594194A8:blocked",
        baseline_fixture_sha256: "1335f2a865820d031a9450881dc628f14293cb8bb10c373adbf45d735acc1392",
        overload_id: "zed.native.tensor.acos.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<f32>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn acos_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "output shape exactly equals input shape",
        dtype_rule: "the certified CPU overload accepts and returns f32",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "uses IEEE f32 arccosine; values outside minus one through one yield NaN",
        tolerance: "one micro-unit absolute tolerance on finite fixture values",
        determinism: "fixed row-major traversal",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "output gradient is negative output_gradient divided by sqrt(one minus input squared)",
        jvp_rule: "input tangent is negative input_tangent divided by sqrt(one minus input squared)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/acos.json",
        evidence_fixture_sha256: "88f95e8145b3b72d934611996b308bef6571a7238da8e081269f74afd97a28c6",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-14815FE141B4",
        baseline_overload_id: "COMFY-TENSOR-OP-14815FE141B4:blocked",
        baseline_fixture_sha256: "4ee55a14299352614293b4f7646d728b324e4f944a41b1a7ae4b2139773da72c",
        overload_id: "zed.native.backend.cudnn-availability.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"bool\"]",
        rust_signature: "fn cudnn_is_available_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwoError>",
        mutation_rule: "read-only capability query",
        alias_rule: "returns a copyable boolean",
        shape_rule: "not applicable to backend metadata",
        dtype_rule: "not applicable to backend metadata",
        accumulation_dtype: "not applicable to backend metadata",
        layout_rule: "not applicable to backend metadata",
        device_rule: "returns false for every current native profile because no certified Zed backend exposes or depends on a cuDNN ABI",
        numeric_rule: "exact boolean with no optimistic library probe or external-process fallback",
        tolerance: "exact",
        determinism: "immutable native capability policy",
        cancellation_points: "before and after the capability query",
        vjp_rule: "backend availability metadata is non-differentiable",
        jvp_rule: "backend availability metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/cudnn_is_available.json",
        evidence_fixture_sha256: "57ec587d85cc52d92c2cf4a06f6dc9d3979dc5f2d887aaedd4244bf88b45a504",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-14218933001D",
        baseline_overload_id: "COMFY-TENSOR-OP-14218933001D:blocked",
        baseline_fixture_sha256: "49884981ce28b2835b437df37bdaaa93fd107f1650bf7a5d7cf759ed1a579476",
        overload_id: "zed.native.tensor.eq-scalar.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn equal_scalar_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: Scalar, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh boolean storage",
        shape_rule: "output shape exactly equals input shape",
        dtype_rule: "the scalar is checked and encoded through the input canonical dtype before comparison",
        accumulation_dtype: "no accumulation",
        layout_rule: "canonical contiguous boolean output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "decoded numeric equality treats either signed zero as equal and every NaN as unequal",
        tolerance: "exact numeric equality",
        determinism: "fixed scalar-codec traversal",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "boolean equality is non-differentiable and all observed uses are forward control paths",
        jvp_rule: "boolean equality has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/eq.json",
        evidence_fixture_sha256: "cf29a122d345d11655b453c2ea6e31fc2a7cfd9507ad998f967e0955063fdbb3",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-160E75523010",
        baseline_overload_id: "COMFY-TENSOR-OP-160E75523010:blocked",
        baseline_fixture_sha256: "465fe1f4a05aee0d72afd86a9bff4b5939125552f179c5b34e0e4eb5d5b5b499",
        overload_id: "zed.native.autograd.inference-mode-enabled.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"bool\"]",
        rust_signature: "fn is_inference_mode_enabled_exact_native(mode: GradientMode, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwoError>",
        mutation_rule: "read-only projection from the canonical GradientMode",
        alias_rule: "returns a copyable boolean",
        shape_rule: "not applicable to execution metadata",
        dtype_rule: "not applicable to execution metadata",
        accumulation_dtype: "not applicable to execution metadata",
        layout_rule: "not applicable to execution metadata",
        device_rule: "device independent",
        numeric_rule: "true exactly for GradientMode::Inference and false for every other canonical mode",
        tolerance: "exact",
        determinism: "immutable enum projection",
        cancellation_points: "before and after the mode projection",
        vjp_rule: "execution mode metadata is non-differentiable",
        jvp_rule: "execution mode metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/is_inference_mode_enabled.json",
        evidence_fixture_sha256: "7854f3716bcf6fcb6c58166f85bfc3d184786792c0574ac02058e29689fd29f6",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-190DE0F94657",
        baseline_overload_id: "COMFY-TENSOR-OP-190DE0F94657:blocked",
        baseline_fixture_sha256: "38ce7740e9039afebe8be040e8d0d58d6d462f0075e2229a0e943daa0fc4b413",
        overload_id: "zed.native.runtime.jit-scripting.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"bool\"]",
        rust_signature: "fn jit_is_scripting_exact_native(cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwoError>",
        mutation_rule: "pure native runtime query",
        alias_rule: "returns a copyable boolean",
        shape_rule: "not applicable to runtime metadata",
        dtype_rule: "not applicable to runtime metadata",
        accumulation_dtype: "not applicable to runtime metadata",
        layout_rule: "not applicable to runtime metadata",
        device_rule: "device independent",
        numeric_rule: "always false because native Rust execution never enters Python TorchScript compilation",
        tolerance: "exact",
        determinism: "compile-time production boundary",
        cancellation_points: "before returning the runtime fact",
        vjp_rule: "runtime metadata is non-differentiable",
        jvp_rule: "runtime metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/jit_is_scripting.json",
        evidence_fixture_sha256: "f9cf9f7152716bfaf0fb172c461aff63e54562035fa51633fac4d0c941c2952d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-1912E4160DE1",
        baseline_overload_id: "COMFY-TENSOR-OP-1912E4160DE1:blocked",
        baseline_fixture_sha256: "7a7da563f61a1c88121dfdc986950a57b5304dd9ec9ac0fda98d79057d09b2e7",
        overload_id: "zed.native.tensor.log.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<f32>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn log_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "output shape exactly equals input shape",
        dtype_rule: "the certified CPU overload accepts and returns f32",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "uses the canonical CPU natural-logarithm primitive with IEEE zero, negative, infinity, and NaN behavior",
        tolerance: "one micro-unit absolute tolerance on finite fixture values",
        determinism: "fixed canonical backend traversal",
        cancellation_points: "before dispatch, inside the backend loop, and before publication",
        vjp_rule: "output gradient is divided by input",
        jvp_rule: "input tangent is divided by input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/log.json",
        evidence_fixture_sha256: "77c66d55d807d4974afa6bb3b62afd96d3a39f585bb1f06dd7f3cee48807fbdf",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-147180FA6AF4",
        baseline_overload_id: "COMFY-TENSOR-OP-147180FA6AF4:blocked",
        baseline_fixture_sha256: "69d8727aec553e7d8f0714ea96cacae88fb90936d92952c6647156f3a4bfde29",
        overload_id: "zed.native.worker.npu-memory-stats.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"DeviceId\"}]",
        output_arity: "1",
        output_types_json: "[\"BTreeMap<String,u64>\"]",
        rust_signature: "fn npu_memory_stats_exact_native(capabilities: &BackendCapabilityMatrix, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<BTreeMap<String,u64>, NativeMemoryStatsError>",
        mutation_rule: "read-only projection from canonical worker memory accounting",
        alias_rule: "returns an owned ordered map",
        shape_rule: "the map contains active_bytes.all.current and reserved_bytes.all.current",
        dtype_rule: "all byte counts are exact u64 values",
        accumulation_dtype: "checked u64 accounting owned by MemoryPlacementInventory",
        layout_rule: "ordered string-keyed map",
        device_rule: "the capability matrix must identify NPU and the accounting snapshot must contain the exact ordinal",
        numeric_rule: "active bytes equal accounted NPU allocations; reserved bytes equal active bytes because Zed has no separate caching allocator",
        tolerance: "exact",
        determinism: "immutable worker-accounting projection with sorted keys",
        cancellation_points: "before validation and after map construction",
        vjp_rule: "memory accounting metadata is non-differentiable",
        jvp_rule: "memory accounting metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/npu_memory_stats.json",
        evidence_fixture_sha256: "fa6e9f202b794a15b257ae97a9080fb3896e82f3ee287830ac62a7cdcb94d730",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-1602683BB161",
        baseline_overload_id: "COMFY-TENSOR-OP-1602683BB161:blocked",
        baseline_fixture_sha256: "40e2ff770b37ad8e13bd15ad00fbdabec8c5447eaa61dd774ee0eda902bd2b49",
        overload_id: "zed.native.optim.functional-adamw.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"parameters\",\"type\":\"mutable list of Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"gradients\",\"type\":\"list of Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"exponential_averages\",\"type\":\"mutable list of Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"exponential_average_squares\",\"type\":\"mutable list of Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"maximum_exponential_average_squares\",\"type\":\"mutable list of Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"steps\",\"type\":\"list of positive u64\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"amsgrad\",\"type\":\"bool\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"beta1\",\"type\":\"f32\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"beta2\",\"type\":\"f32\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"learning_rate\",\"type\":\"f32\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"weight_decay\",\"type\":\"f32\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"epsilon\",\"type\":\"f32\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"maximize\",\"type\":\"bool\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn adamw_with_context_exact_native(backend: &CpuBackend, parameters: &mut [Tensor], gradients: &[Tensor], exponential_averages: &mut [Tensor], exponential_average_squares: &mut [Tensor], maximum_exponential_average_squares: &mut [Tensor], steps: &[u64], amsgrad: bool, beta1: f32, beta2: f32, learning_rate: f32, weight_decay: f32, epsilon: f32, maximize: bool, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartTwoError>",
        mutation_rule: "stages every parameter and moment tensor before one publication phase; any error or cancellation leaves every caller-owned list unchanged",
        alias_rule: "committed handles point to fresh canonical storage and preexisting aliases retain prior values",
        shape_rule: "parallel lists have equal length and each parameter, gradient, and moment group has exactly matching shape and stream",
        dtype_rule: "the certified CPU overload requires f32 tensors and finite checked scalar configuration",
        accumulation_dtype: "f32 with positive step bounded by checked i32 exponentiation",
        layout_rule: "committed tensors use canonical contiguous storage",
        device_rule: "CPU ordinal zero is certified for every list entry",
        numeric_rule: "uses decoupled weight decay, bias-corrected first and second moments, optional AMSGrad maximum, and optional gradient maximization",
        tolerance: "fixed f32 operation ordering with one micro-unit fixture tolerance",
        determinism: "parameter-list order then row-major element order",
        cancellation_points: "before each parameter, at bounded element intervals, during staging uploads, and before the publication phase",
        vjp_rule: "optimizer updates are terminal state transitions and do not record a reverse-mode node",
        jvp_rule: "optimizer updates do not propagate tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/adamw.json",
        evidence_fixture_sha256: "238fa75d17a22509987253717acfbdd0ed5164635c6c0ac25658fa68791ccbc7",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-10A0FC173128",
        baseline_overload_id: "COMFY-TENSOR-OP-10A0FC173128:blocked",
        baseline_fixture_sha256: "ac36cca44e68b2b6bfd7112368f2df113787d73b4bf674a9c3046e8f725cacf4",
        overload_id: "zed.native.tensor.polar.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"magnitude\",\"type\":\"Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"angle\",\"type\":\"Tensor<f32>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<complex64>\"]",
        rust_signature: "fn polar_with_context_exact_native(backend: &CpuBackend, magnitude: &Tensor, angle: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh complex storage",
        shape_rule: "magnitude and angle have equal shape and stream and output preserves that shape",
        dtype_rule: "certified f32 inputs produce canonical complex64 output",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous interleaved real-imaginary output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "real equals magnitude times cosine of angle and imaginary equals magnitude times sine of angle",
        tolerance: "one micro-unit absolute tolerance on each component",
        determinism: "fixed row-major traversal and component order",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "the observed rotary-frequency construction is forward only in the cataloged graph",
        jvp_rule: "the observed rotary-frequency construction does not request tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/polar.json",
        evidence_fixture_sha256: "8a40e171f26a8cf341e9b07354e7a0476a3be802b96d87e9c0a72579a001778d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-11C887BB4214",
        baseline_overload_id: "COMFY-TENSOR-OP-11C887BB4214:blocked",
        baseline_fixture_sha256: "ce62162aaaa372c8c4e62e55949f68fc61530463464e838ef4885b5dda522a3a",
        overload_id: "zed.native.tensor.view-as-complex.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous Tensor<f32> with trailing dimension two\"}]",
        output_arity: "1",
        output_types_json: "[\"read-only Tensor<complex64> view\"]",
        rust_signature: "fn view_as_complex_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "read-only view construction with no storage mutation",
        alias_rule: "shares the exact source storage through Tensor::reinterpret_contiguous_read_only and cannot acquire a writable lease",
        shape_rule: "removes the final dimension, which must equal two; scalar and other trailing sizes fail typed",
        dtype_rule: "certified contiguous f32 input reinterprets as complex64 with exactly equal byte length",
        accumulation_dtype: "no accumulation",
        layout_rule: "source and target must be zero-offset canonical contiguous descriptors",
        device_rule: "CPU ordinal zero is certified and device plus stream identity are preserved",
        numeric_rule: "each adjacent f32 pair is interpreted as real then imaginary without copying or conversion",
        tolerance: "bit exact storage reinterpretation",
        determinism: "immutable descriptor validation and storage aliasing",
        cancellation_points: "before validation and after checked view construction",
        vjp_rule: "a complex gradient maps each element back to its adjacent real and imaginary f32 pair",
        jvp_rule: "an adjacent f32 tangent pair is reinterpreted through the identical checked view geometry",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/view_as_complex.json",
        evidence_fixture_sha256: "1f01825cc58b0a465596f7fbf3778ff4098efa47c2da065ce68b1170811cf14b",
    },
]
