&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4B4746D5885A",
        baseline_overload_id: "COMFY-TENSOR-OP-4B4746D5885A:blocked",
        baseline_fixture_sha256: "fb6dd947983b2e35d154bcbadf83f78e51bad74e098ba20c3ea9ffa0f6128adc",
        overload_id: "zed.native.tensor.acos.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn acos_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical acos owner and returns fresh storage",
        shape_rule: "preserves every input dimension including empty dimensions",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE acos with NaN outside the closed unit interval",
        tolerance: "one ULP against the pinned fixture",
        determinism: "canonical CPU traversal",
        cancellation_points: "before delegation, during canonical traversal, and before publication",
        vjp_rule: "negative upstream gradient divided by square root of one minus input squared",
        jvp_rule: "the same derivative applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/acos_method.json",
        evidence_fixture_sha256: "c8a5b4449bc8d202c5026e27d4c77ef33ffd5e5cdcc767a71695110abd60bd17",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-472F133627A1",
        baseline_overload_id: "COMFY-TENSOR-OP-472F133627A1:blocked",
        baseline_fixture_sha256: "29edb4d4773e1b3869dcd4b4718e1168c08bfd8ccf8881a43da28f753397879b",
        overload_id: "zed.native.tensor.bool.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<numeric>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<Bool>"]"#,
        rust_signature: "fn bool_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "canonical DType cast returns fresh storage when dtype changes",
        shape_rule: "preserves shape",
        dtype_rule: "canonical scalar codecs map zero to false and every nonzero value including NaN to true",
        accumulation_dtype: "Bool",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "exact truth conversion through DType",
        tolerance: "exact bits",
        determinism: "canonical cast traversal",
        cancellation_points: "before cast, at bounded cast intervals, and before publication",
        vjp_rule: "boolean cast is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/bool_method.json",
        evidence_fixture_sha256: "c70cde87342d31df9ab7d8c8e54c203f06384494126431ed7a6f969057b5cbc3",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4B6925D60ACD",
        baseline_overload_id: "COMFY-TENSOR-OP-4B6925D60ACD:blocked",
        baseline_fixture_sha256: "7a3a9ce349763d0654dd41c77e39da7acbad37a074394062c3c3490b324cfc8b",
        overload_id: "zed.native.tensor.round.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":0,"keyword_only":true,"kind":"keyword_only","name":"decimals","type":"i32"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn round_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, decimals: i32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F64 only for decimal scaling then checked F32 publication",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "round half to even with finite decimal scaling",
        tolerance: "exact for fixture values",
        determinism: "fixed index traversal",
        cancellation_points: "before validation, at bounded traversal intervals, and before publication",
        vjp_rule: "zero almost everywhere using a canonical zero fill",
        jvp_rule: "zero tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/round_method.json",
        evidence_fixture_sha256: "0689868f4bccaf941d8b466a1f839cef7aaed71ef933a2afceb87aac82c2b157",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-51695C0FE8D8",
        baseline_overload_id: "COMFY-TENSOR-OP-51695C0FE8D8:blocked",
        baseline_fixture_sha256: "8b39aec854bb1488964beb3f310ef97c37f380c845683923299555261aca7a82",
        overload_id: "zed.native.tensor.sigmoid.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sigmoid_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical sigmoid owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "stable canonical sigmoid primitive",
        tolerance: "one ULP against the pinned fixture",
        determinism: "canonical CPU traversal",
        cancellation_points: "before delegation, during canonical traversal, and before publication",
        vjp_rule: "upstream times sigmoid times one minus sigmoid",
        jvp_rule: "the same derivative applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/sigmoid_method.json",
        evidence_fixture_sha256: "313f3dd4a1cab183d2e29e4607ee9556c7c14a4a9eb3480360f2d3c4becff0aa",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4685F95970C6",
        baseline_overload_id: "COMFY-TENSOR-OP-4685F95970C6:blocked",
        baseline_fixture_sha256: "caf14c0b21079c895b102e4c9fa4871c5cc3d3c1e97366621050dda63a7202c0",
        overload_id: "zed.native.tensor.unique.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<non-complex>"},{"default":true,"keyword_only":true,"kind":"keyword_only","name":"sorted","type":"bool"},{"default":false,"keyword_only":true,"kind":"keyword_only","name":"return_inverse","type":"bool"},{"default":false,"keyword_only":true,"kind":"keyword_only","name":"return_counts","type":"bool"}]"#,
        output_arity: "3",
        output_types_json: r#"["Tensor<input dtype>","Option<Tensor<I64>>","Option<Tensor<I64>>"]"#,
        rust_signature: "fn unique_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, sorted: bool, return_inverse: bool, return_counts: bool, context: &ExecutionContext<'_>) -> Result<UniqueResult, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "all requested outputs use fresh canonical storage",
        shape_rule: "values and counts are one dimensional; inverse indices preserve input shape",
        dtype_rule: "values preserve non-complex input dtype; inverse and counts use I64",
        accumulation_dtype: "I64 counts with checked addition",
        layout_rule: "canonical contiguous outputs",
        device_rule: "CPU ordinal zero",
        numeric_rule: "sorted exact scalar equality; NaN values remain distinct and signed zeros compare equal",
        tolerance: "exact encoded values",
        determinism: "stable value ordering with original index tie break",
        cancellation_points: "before validation, during decode and sort publication intervals, and before each output publication",
        vjp_rule: "unique is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/unique_method.json",
        evidence_fixture_sha256: "3ced5fa0a6ab772f16a3f51ef7ccdd0e3ede0380bc6aba3532f6a96e93232f59",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4D087B722410",
        baseline_overload_id: "COMFY-TENSOR-OP-4D087B722410:blocked",
        baseline_fixture_sha256: "f1e4fdd833e9da1b98ce66bb3431ba2878ad202d3fa5c9dac92ed92202ec9671",
        overload_id: "zed.native.tensor.div.function.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"Tensor<F32> or Scalar"},{"default":null,"keyword_only":true,"kind":"keyword_only","name":"rounding_mode","type":"Option<DivisionRoundingMode>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn div_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, rounding_mode: Option<DivisionRoundingMode>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "delegates true division to the canonical divide owner then applies canonical floor or checked truncation",
        shape_rule: "canonical right-aligned broadcasting",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero with co-located operands",
        numeric_rule: "IEEE division with optional floor or trunc rounding",
        tolerance: "exact for rounded modes and one ULP for true division",
        determinism: "canonical broadcast traversal",
        cancellation_points: "before delegation, at bounded arithmetic intervals, and before publication",
        vjp_rule: "canonical divide gradients for true division and zero gradients for rounded modes",
        jvp_rule: "canonical divide tangent for true division and zero tangent for rounded modes",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/div_function.json",
        evidence_fixture_sha256: "642a214390bed9e1c2e7aa857b9169fb00cd62d3e66ca88ae9181fa51ade0822",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-42AC47EA61EE",
        baseline_overload_id: "COMFY-TENSOR-OP-42AC47EA61EE:blocked",
        baseline_fixture_sha256: "c3ced5b2e27706b92fa09fca51af7fdc5cacc8a41324ddef21804b773a4fa15f",
        overload_id: "zed.native.autograd.inference-mode.explicit.v1",
        ordered_parameters_json: r#"[{"default":true,"keyword_only":false,"kind":"positional_or_keyword","name":"enabled","type":"bool"},{"default":"enabled","keyword_only":false,"kind":"positional_or_keyword","name":"current_mode","type":"GradientMode"}]"#,
        output_arity: "1",
        output_types_json: r#"["GradientMode"]"#,
        rust_signature: "fn inference_mode_exact_native(enabled: bool, current_mode: GradientMode, cancellation: &CancellationToken) -> Result<GradientMode, ElementwiseRuntimePartSixError>",
        mutation_rule: "returns an explicit mode value without process global state",
        alias_rule: "value projection only",
        shape_rule: "not applicable to tensor shape",
        dtype_rule: "not applicable to tensor dtype",
        accumulation_dtype: "no numeric accumulation",
        layout_rule: "not applicable to tensor layout",
        device_rule: "device independent explicit autograd mode",
        numeric_rule: "enabled maps to inference and disabled preserves the caller mode",
        tolerance: "exact enum value",
        determinism: "pure value mapping",
        cancellation_points: "before and after mode projection",
        vjp_rule: "inference mode causes AutogradTape to retain no rules",
        jvp_rule: "inference mode records no tangent graph",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/inference_mode.json",
        evidence_fixture_sha256: "9c3a99547b891c2c66140a85a6b0efc872e0356af541e85396e5a5ec9e3655ec",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-49949B24BFD5",
        baseline_overload_id: "COMFY-TENSOR-OP-49949B24BFD5:blocked",
        baseline_fixture_sha256: "c633e31b69606f2a009d996e397963c9d8e1f808c94d2c5898e40ce6678cf148",
        overload_id: "zed.native.jit.is-tracing.false.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn jit_is_tracing_exact_native(cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartSixError>",
        mutation_rule: "read only",
        alias_rule: "value projection only",
        shape_rule: "not applicable to tensor shape",
        dtype_rule: "not applicable to tensor dtype",
        accumulation_dtype: "no numeric accumulation",
        layout_rule: "not applicable to tensor layout",
        device_rule: "device independent native runtime fact",
        numeric_rule: "native Rust execution has no TorchScript tracing state and returns false",
        tolerance: "exact boolean",
        determinism: "constant native runtime fact",
        cancellation_points: "before projection",
        vjp_rule: "runtime fact is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/jit_is_tracing.json",
        evidence_fixture_sha256: "f58de375b603d5347a8ea3a052016d2dd0bea746d825cbda88c8edad6892fba4",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4BE7FEEFD9EF",
        baseline_overload_id: "COMFY-TENSOR-OP-4BE7FEEFD9EF:blocked",
        baseline_fixture_sha256: "ec18037f55681ae3fad222f610bebdc96a417e6eda257ce9610202bbd6c42066",
        overload_id: "zed.native.tensor.sinc.function.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sinc_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage from the CPU unary owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "normalized sine cardinal sin of pi x divided by pi x with exact value one at zero",
        tolerance: "one ULP against the pinned fixture",
        determinism: "canonical CPU traversal",
        cancellation_points: "before validation, during canonical traversal, and before publication",
        vjp_rule: "upstream times the analytical normalized sinc derivative with zero derivative at zero",
        jvp_rule: "the same derivative applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/sinc_function.json",
        evidence_fixture_sha256: "2d1f563548b72c45f9828f5e2f024cd440fdab923575835682bb97caafb79890",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4130D690D4B2",
        baseline_overload_id: "COMFY-TENSOR-OP-4130D690D4B2:blocked",
        baseline_fixture_sha256: "3846f02eac343fa2efee0ec0a1994cd545ad01fcea95157a174abddf9f99ca9f",
        overload_id: "zed.native.tensor.sqrt.function.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sqrt_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical square root owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE square root with NaN for negative finite values",
        tolerance: "one ULP against the pinned fixture",
        determinism: "canonical CPU traversal",
        cancellation_points: "before delegation, during canonical traversal, and before publication",
        vjp_rule: "upstream divided by twice the square root",
        jvp_rule: "the same derivative applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/sqrt_function.json",
        evidence_fixture_sha256: "8b0bb0a7e842e0e44661039e895c85765f960b9f246dc5a3fd4ce6754c1e31be",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-5278A14360E3",
        baseline_overload_id: "COMFY-TENSOR-OP-5278A14360E3:blocked",
        baseline_fixture_sha256: "54822e8e62677f0ff9ba0c5be1fa9c51465d19b475289de0298dbdb821ac2236",
        overload_id: "zed.native.autograd.checkpoint.explicit-replay.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"inputs","type":"slice of Tensor"},{"default":true,"keyword_only":true,"kind":"keyword_only","name":"use_reentrant","type":"bool"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"function","type":"native checked tensor function"}]"#,
        output_arity: "1",
        output_types_json: r#"["CheckpointExecution"]"#,
        rust_signature: "fn checkpoint_exact_native(inputs: &[Tensor], use_reentrant: bool, cancellation: &CancellationToken, function: F) -> Result<CheckpointExecution, ElementwiseRuntimePartSixError>",
        mutation_rule: "records immutable input handles and versions; recomputation publishes only complete outputs",
        alias_rule: "saved inputs use canonical Tensor copy on write and outputs retain the function alias contract",
        shape_rule: "forward and recomputation output arity must match",
        dtype_rule: "preserves the wrapped function dtype contract",
        accumulation_dtype: "owned by the wrapped function",
        layout_rule: "preserves the wrapped function layout contract",
        device_rule: "preserves explicit input devices without process global state",
        numeric_rule: "reentrant forward executes in no grad mode and replay executes with gradients enabled; nonreentrant forward executes enabled",
        tolerance: "bit exact when the wrapped function is deterministic",
        determinism: "explicit replay over version checked saved inputs",
        cancellation_points: "before forward, after forward, before version checks, during replay, and before replay publication",
        vjp_rule: "caller replays the wrapped function with GradientMode enabled and records its canonical backward rules",
        jvp_rule: "caller replays the wrapped function with GradientMode enabled and records its canonical tangent rules",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/checkpoint.json",
        evidence_fixture_sha256: "2f616b256483930997abe4c8e6137ff232eeafb7f5140a138225a79f05ba16fc",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-48C9CD534224",
        baseline_overload_id: "COMFY-TENSOR-OP-48C9CD534224:blocked",
        baseline_fixture_sha256: "e03397d21444c2cb50b5c54609ec0c401a9011f492492925f8b047317d0407e4",
        overload_id: "zed.native.xpu.device-properties.projection.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"capabilities","type":"BackendCapabilityMatrix"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"device","type":"DeviceId<Xpu>"}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeDeviceProperties"]"#,
        rust_signature: "fn xpu_get_device_properties_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<NativeDeviceProperties, ElementwiseRuntimePartSixError>",
        mutation_rule: "read only projection",
        alias_rule: "returns an owned clone of canonical properties",
        shape_rule: "not applicable to tensor shape",
        dtype_rule: "property record includes the canonical fp16 capability",
        accumulation_dtype: "no numeric accumulation",
        layout_rule: "not applicable to tensor layout",
        device_rule: "requested XPU identity must exactly match the capability matrix and property record",
        numeric_rule: "memory and version fields are exact canonical owner values",
        tolerance: "exact fields",
        determinism: "pure canonical owner projection",
        cancellation_points: "before validation and after cloning",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/xpu_get_device_properties.json",
        evidence_fixture_sha256: "c137373a0092493ebd247d641384166ecd3393327709bb85e8122e4979f38e33",
    },
]
