&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7E962991728B",
        baseline_overload_id: "COMFY-TENSOR-OP-7E962991728B:blocked",
        baseline_fixture_sha256: "5c6ee4f357bc9bbac9796cdedadd5430a7588701192ef4901fcdd97fafe2c620",
        overload_id: "zed.native.tensor.clamp-method.canonical-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"minimum","kind":"keyword_only","type":"Option<Scalar>","default":null,"keyword_only":true},{"name":"maximum","kind":"keyword_only","type":"Option<Scalar>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn clamp_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, minimum: Option<Scalar>, maximum: Option<Scalar>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartElevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 52 canonical clamp adapter",
        shape_rule: "preserves shape",
        dtype_rule: "canonical clamp dtype rules",
        accumulation_dtype: "input dtype",
        layout_rule: "canonical logical layout",
        device_rule: "canonical tensor device",
        numeric_rule: "inclusive checked lower and upper bounds",
        tolerance: "exact dtype arithmetic",
        determinism: "canonical clamp traversal",
        cancellation_points: "canonical clamp checkpoints",
        vjp_rule: "upstream gradient inside inclusive bounds",
        jvp_rule: "input tangent inside inclusive bounds",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/clamp_method.json",
        evidence_fixture_sha256: "7b41bfbff4f5476d72442de6e75652669c3d3bf7f4cabb2adad4809acb2d3381",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7E09C5749B60",
        baseline_overload_id: "COMFY-TENSOR-OP-7E09C5749B60:blocked",
        baseline_fixture_sha256: "635fcfadaa9ea229df135c80a088ea8148e5cbadcfad6602bb14bba5ce47dc0c",
        overload_id: "zed.native.tensor.tolist.logical-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["TensorListValue"]"#,
        rust_signature: "fn tolist_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<TensorListValue, ElementwiseRuntimePartElevenError>",
        mutation_rule: "read only",
        alias_rule: "owned recursive values decoded by DType",
        shape_rule: "preserves every descriptor dimension as nested lists",
        dtype_rule: "projects canonical decoded scalar categories",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical logical indexing including views",
        device_rule: "CPU host storage",
        numeric_rule: "exact scalar decode including complex and non-finite values",
        tolerance: "exact",
        determinism: "row-major recursive traversal",
        cancellation_points: "bounded recursive traversal",
        vjp_rule: "non-differentiable host projection",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/tolist.json",
        evidence_fixture_sha256: "5f910ac18c839bca52bf57801d4aeafd8a36a984b821d557918279b8bf157b96",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7F86521B5D09",
        baseline_overload_id: "COMFY-TENSOR-OP-7F86521B5D09:blocked",
        baseline_fixture_sha256: "f8823a5ac89f840bf9ce3114356bd13c13a91b29318ce8135b7404da2c3eff63",
        overload_id: "zed.native.autograd.enable-grad.explicit-mode.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: r#"["GradientMode"]"#,
        rust_signature: "fn enable_grad_exact_native(cancellation: &CancellationToken) -> Result<GradientMode, ElementwiseRuntimePartElevenError>",
        mutation_rule: "read only",
        alias_rule: "returns canonical explicit GradientMode",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "execution-context scoped",
        numeric_rule: "exact Enabled mode value",
        tolerance: "exact",
        determinism: "constant projection",
        cancellation_points: "before projection",
        vjp_rule: "caller-owned AutogradTape records under returned mode",
        jvp_rule: "caller-owned forward rules use returned mode",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/enable_grad.json",
        evidence_fixture_sha256: "323cafd1406f139425e5aef0835dc499deae25f1dd81c43ee757922f8001c9c4",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7A0F5559B701",
        baseline_overload_id: "COMFY-TENSOR-OP-7A0F5559B701:blocked",
        baseline_fixture_sha256: "8c520d63ba8be9d8d59350339430a183103be4f49ba48fc889fb3b9d4fb92281",
        overload_id: "zed.native.tensor.isclose.f32-broadcast.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"relative_tolerance","kind":"keyword_only","type":"f32","default":0.00001,"keyword_only":true},{"name":"absolute_tolerance","kind":"keyword_only","type":"f32","default":0.00000001,"keyword_only":true},{"name":"equal_nan","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<Bool>"]"#,
        rust_signature: "fn isclose_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, relative_tolerance: f32, absolute_tolerance: f32, equal_nan: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartElevenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical Bool storage",
        shape_rule: "right-aligned broadcast shape",
        dtype_rule: "F32 inputs and Bool output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "exact equality or abs(a-b)<=atol+rtol*abs(b) with explicit NaN policy",
        tolerance: "parameters define comparison",
        determinism: "row-major broadcast traversal",
        cancellation_points: "bounded comparison and upload",
        vjp_rule: "non-differentiable predicate",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/isclose.json",
        evidence_fixture_sha256: "77b4b257e221f121b1ab66471e5fb142a28ad0cec256e21c1006e404acbfe3ae",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7DB0B0EC6483",
        baseline_overload_id: "COMFY-TENSOR-OP-7DB0B0EC6483:blocked",
        baseline_fixture_sha256: "ce1444d07139cced1d0e3c093f45112df013ae4439bc1fa1df7b798571ceb00b",
        overload_id: "zed.native.tensor.maximum.canonical-binary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"ElementwiseOperand<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn maximum_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartElevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical BinaryOperation::Maximum",
        shape_rule: "right-aligned broadcasting",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "NaN-propagating maximum with symmetric tie gradients",
        tolerance: "exact F32",
        determinism: "canonical binary traversal",
        cancellation_points: "canonical backend and derivative checkpoints",
        vjp_rule: "winning input receives gradient; ties split equally and broadcast gradients reduce",
        jvp_rule: "winning tangent; ties average",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/maximum.json",
        evidence_fixture_sha256: "6ec951bdf9497058e68f25c2f8aaef0f2db2d1c2459b894080083244254eddf4",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-82BC07D67AFD",
        baseline_overload_id: "COMFY-TENSOR-OP-82BC07D67AFD:blocked",
        baseline_fixture_sha256: "35243834926416aa8e5be78fa55270c65baca856d8dc2955c3a6743c577ad128",
        overload_id: "zed.native.nn.init.zeros.canonical-fill.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["unit"]"#,
        rust_signature: "fn zeros_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartElevenError>",
        mutation_rule: "transactional in place",
        alias_rule: "delegates canonical zero_ staged fill and Tensor publication",
        shape_rule: "preserves descriptor",
        dtype_rule: "canonical fill dtype support",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical logical fill",
        device_rule: "exact backend device",
        numeric_rule: "exact representable zero",
        tolerance: "exact",
        determinism: "canonical fill traversal",
        cancellation_points: "before publication and backend checkpoints",
        vjp_rule: "initialization boundary is forward only",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/zeros_in_place.json",
        evidence_fixture_sha256: "e170916620dfcb5135d25ec41dde6c0cb41dac71f36b2339d35cbc227c2da41b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-791664AD5273",
        baseline_overload_id: "COMFY-TENSOR-OP-791664AD5273:blocked",
        baseline_fixture_sha256: "9991b436979e893c03d1ac63c94e318c8ab0ed3e2eea55b5ea961baaec0dce2d",
        overload_id: "zed.native.device.npu.empty-cache.memory-owner-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","kind":"positional_or_keyword","type":"dyn CachedAllocationOwner","default":null,"keyword_only":false},{"name":"inventory","kind":"positional_or_keyword","type":"MemoryPlacementInventory","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Npu>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeCacheRelease"]"#,
        rust_signature: "fn npu_empty_cache_exact_native(backend: &dyn CachedAllocationOwner, inventory: &mut MemoryPlacementInventory, device: DeviceId, cancellation: &CancellationToken) -> Result<NativeCacheRelease, NativeMemoryStatsError>",
        mutation_rule: "transactional canonical cache release and accounting commit",
        alias_rule: "delegates shared device_empty_cache authority",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires matching NPU cache owner and inventory device",
        numeric_rule: "exact released-byte and eviction accounting",
        tolerance: "exact",
        determinism: "inventory resource order",
        cancellation_points: "before staging and allocator release",
        vjp_rule: "non-differentiable memory control",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/npu_empty_cache.json",
        evidence_fixture_sha256: "6a7f2e72f52a83cd699e94c5ed1ea7916a76ab0d97817d8a1a86706ee6a78ade",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7EA8F732F7A7",
        baseline_overload_id: "COMFY-TENSOR-OP-7EA8F732F7A7:blocked",
        baseline_fixture_sha256: "f86c375e766c527bfd14aba13b75e0fef815a195f566a58164d372e25d49eed9",
        overload_id: "zed.native.device.npu.name.capability-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Npu>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["String"]"#,
        rust_signature: "fn npu_get_device_name_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<String, ElementwiseRuntimePartElevenError>",
        mutation_rule: "read only",
        alias_rule: "owned projection of canonical NativeDeviceProperties",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "exact matching NPU matrix and device",
        numeric_rule: "exact validated device name",
        tolerance: "exact",
        determinism: "capability projection",
        cancellation_points: "before and after projection",
        vjp_rule: "non-differentiable capability query",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/npu_device_name.json",
        evidence_fixture_sha256: "a8523ed9ce8974f8b814779fb28a179cd7662e80be91bd9d97dec9ea32ba02bd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-790CDE1EBF17",
        baseline_overload_id: "COMFY-TENSOR-OP-790CDE1EBF17:blocked",
        baseline_fixture_sha256: "d8c489aede2da49a5ace73ad5c2298b3e0b294f148022f571047abb6329f8a9e",
        overload_id: "zed.native.optimizer.adam.canonical-adamw-zero-decay.v1",
        ordered_parameters_json: r#"[{"name":"parameters","kind":"positional_or_keyword","type":"Vec<Tensor<F32>>","default":null,"keyword_only":false},{"name":"learning_rate","kind":"keyword_only","type":"f32","default":0.001,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeAdam"]"#,
        rust_signature: "fn NativeAdam::new_with_context_exact_native(backend: &CpuBackend, parameters: &[Tensor], learning_rate: f32, context: &ExecutionContext<'_>) -> Result<NativeAdam, ElementwiseRuntimePartElevenError>",
        mutation_rule: "constructor plus transactional steps",
        alias_rule: "focused wrapper over canonical NativeAdamW with zero decay",
        shape_rule: "state matches parameter list and shapes",
        dtype_rule: "F32 parameters and gradients",
        accumulation_dtype: "F32 canonical moment tensors",
        layout_rule: "canonical tensor storage",
        device_rule: "CPU ordinal zero",
        numeric_rule: "Adam defaults beta1 .9 beta2 .999 epsilon 1e-8 and zero weight decay",
        tolerance: "F32 arithmetic",
        determinism: "parameter order and monotonic steps",
        cancellation_points: "canonical AdamW staging checkpoints",
        vjp_rule: "optimizer consumes caller-provided gradients",
        jvp_rule: "optimizer state transition is not differentiated",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/adam.json",
        evidence_fixture_sha256: "ed5f2c59ffa23827d6afb5b82a9bf83e15565c9bd86da65e70550e2cf0eaf20e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-8162B4C00596",
        baseline_overload_id: "COMFY-TENSOR-OP-8162B4C00596:blocked",
        baseline_fixture_sha256: "6aa9322000cf8000ae5d2ee6194118eac0749957834dc7abd85d427f7158329c",
        overload_id: "zed.native.tensor.round-function.canonical-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn round_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartElevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical round method with zero decimals",
        shape_rule: "preserves shape",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "ties to even",
        tolerance: "exact F32",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical round checkpoints",
        vjp_rule: "zero almost everywhere",
        jvp_rule: "zero almost everywhere",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/round_function.json",
        evidence_fixture_sha256: "c029f1ef559f90137369f16d205f9eb0de1007d21f2fd9f569c6d62eda6ca9d2",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-82310D1230AF",
        baseline_overload_id: "COMFY-TENSOR-OP-82310D1230AF:blocked",
        baseline_fixture_sha256: "293a7a20a54ef9e99ab367670b293c2795082dd94a9bca3c042c9c92cdccfb40",
        overload_id: "zed.native.tensor.sign.canonical-unary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sign_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartElevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical UnaryOperation::Signum",
        shape_rule: "preserves shape",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "negative one zero positive one with NaN propagation and signed-zero preservation",
        tolerance: "exact",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical backend checkpoints",
        vjp_rule: "zero almost everywhere",
        jvp_rule: "zero almost everywhere",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/sign.json",
        evidence_fixture_sha256: "6f748f19bf7febee9a948c16b5a669cf16e9e1dac5fec66ed17ecc715c6549b5",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-80B937845579",
        baseline_overload_id: "COMFY-TENSOR-OP-80B937845579:blocked",
        baseline_fixture_sha256: "55d1cb2a961bf27f91216a1d2baf550aaeddf579b599a5eb34ac60e344465747",
        overload_id: "zed.native.device.xpu.memory-stats.accounting-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["BTreeMap<String,u64>"]"#,
        rust_signature: "fn xpu_memory_stats_exact_native(capabilities: &BackendCapabilityMatrix, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<BTreeMap<String, u64>, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "delegates canonical MemoryAccountingSnapshot projection",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "u64 checked accounting",
        layout_rule: "not applicable",
        device_rule: "exact XPU capability device",
        numeric_rule: "exact active and reserved current bytes",
        tolerance: "exact",
        determinism: "ordered source-key map",
        cancellation_points: "before and after projection",
        vjp_rule: "non-differentiable memory diagnostics",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/xpu_memory_stats.json",
        evidence_fixture_sha256: "1cedb55d27c73562cd8fb6cab41d41582b1bdb1bffe138085a1317168f5fe707",
    },
]
