&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-FB884955DE1E",
        baseline_overload_id: "COMFY-TENSOR-OP-FB884955DE1E:blocked",
        baseline_fixture_sha256: "b352c736f7ffe5d481f9c252383aa1be44877d7e5303ad9983f8e7c7b2bc6cf4",
        overload_id: "zed.native.tensor.argsort.method-canonical.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<real|integer|bool>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":-1,"keyword_only":true},{"name":"descending","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"stable","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn argsort_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, descending: bool, stable: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place",
        alias_rule: "thin adapter over the canonical Task 57 argsort owner and its fresh index storage",
        shape_rule: "preserves input shape with a checked negative dimension",
        dtype_rule: "real, integer, or boolean input; I64 indices",
        accumulation_dtype: "not applicable",
        layout_rule: "logical source traversal and contiguous output",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "canonical total ordering, NaN placement, and stable source-index tie behavior",
        tolerance: "exact indices",
        determinism: "canonical argsort ordering",
        cancellation_points: "before adapter dispatch and at canonical per-lane boundaries",
        vjp_rule: "non-differentiable discrete indices",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/argsort_method.json",
        evidence_fixture_sha256: "75ba092b59b6e618491c81509fe1b4eec3ab22c93654d058425da86d60d06c19",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F2D7AE6E8F48",
        baseline_overload_id: "COMFY-TENSOR-OP-F2D7AE6E8F48:blocked",
        baseline_fixture_sha256: "66d2122b894b7e6d2435bcf28e59a1f53b3e3c455830883d891d1e900023218f",
        overload_id: "zed.native.tensor.floor.method-canonical.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<real>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<input dtype>"]"#,
        rust_signature: "fn floor_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place",
        alias_rule: "thin method adapter over the canonical Task 45 floor owner",
        shape_rule: "preserves shape including empty tensors",
        dtype_rule: "preserves supported real dtype; certified derivatives use F32",
        accumulation_dtype: "F64 decode for forward rounding and F32 derivative zeros",
        layout_rule: "logical traversal and canonical output",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "rounds each finite value toward negative infinity and preserves canonical NaN/Inf handling",
        tolerance: "bit exact encoded result",
        determinism: "fixed logical element order",
        cancellation_points: "canonical bounded traversal and before publication",
        vjp_rule: "zero tensor after output-gradient geometry validation",
        jvp_rule: "zero tensor after tangent geometry validation",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/floor_method.json",
        evidence_fixture_sha256: "fb4508731e3223ffb466c29bfbe580343af53192ec0a2ffa6a9e6f6492c9044d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F1F71360D559",
        baseline_overload_id: "COMFY-TENSOR-OP-F1F71360D559:blocked",
        baseline_fixture_sha256: "eaf40b2e4dfeabb8c6b31ae488bc6412cfb2b1138d21596927cc5a1d2dcc7b42",
        overload_id: "zed.native.tensor.t.read-only-view.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<rank<=2>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<input dtype>"]"#,
        rust_signature: "fn t_method_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "read only",
        alias_rule: "rank-zero and rank-one tensors return a read-only identity view; matrices reuse canonical swapaxes storage sharing",
        shape_rule: "rank zero and one preserve shape; rank two swaps dimensions; higher ranks are rejected",
        dtype_rule: "preserves input dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "checked read-only strided view",
        device_rule: "preserves native device and stream",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "descriptor-only transformation",
        cancellation_points: "before validation and after view construction",
        vjp_rule: "applies t() to the output gradient",
        jvp_rule: "applies t() to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/t_method.json",
        evidence_fixture_sha256: "b1fddefea1d22a9ffe4eea958c6abb0b8b01d2db6fd5a4bed377b0890728855b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F56BA497ED13",
        baseline_overload_id: "COMFY-TENSOR-OP-F56BA497ED13:blocked",
        baseline_fixture_sha256: "b692e08bcbc42068a718aad6fbb003fc8b101454bdee2672afd2f46938e9a1a0",
        overload_id: "zed.native.tensor.arccos.canonical-acos.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn arccos_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place",
        alias_rule: "thin function alias over the canonical Task 44 acos owner",
        shape_rule: "preserves shape",
        dtype_rule: "certified CPU F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "logical traversal and contiguous output",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "native acos with canonical NaN outside [-1,1]",
        tolerance: "1e-5 absolute",
        determinism: "fixed element order",
        cancellation_points: "canonical backend bounded kernel points",
        vjp_rule: "-output_gradient/sqrt(1-input^2)",
        jvp_rule: "the same derivative multiplied by input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/arccos.json",
        evidence_fixture_sha256: "0648c07e073bf5cdc3c59d4159f92844cfd40f7bfbee4381baab629600ffbb95",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-FBA06A1411DE",
        baseline_overload_id: "COMFY-TENSOR-OP-FBA06A1411DE:blocked",
        baseline_fixture_sha256: "d7074f9d67d4b5b6d8cfbce1f47227ece85af74b62146bc8b114486f09822ae1",
        overload_id: "zed.native.tensor.cuda-amp-autocast.policy-adapter.v1",
        ordered_parameters_json: r#"[{"name":"enabled","kind":"keyword_only","type":"bool","default":true,"keyword_only":true},{"name":"dtype","kind":"keyword_only","type":"Option<DType>","default":null,"keyword_only":true},{"name":"cache_enabled","kind":"keyword_only","type":"Option<bool>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["AutocastPolicy"]"#,
        rust_signature: "fn cuda_amp_autocast_exact_native(enabled: bool, dtype: Option<DType>, cache_enabled: Option<bool>, cancellation: &CancellationToken) -> Result<AutocastPolicy, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "constructs immutable request-scoped policy",
        alias_rule: "thin legacy CUDA namespace adapter over canonical AutocastPolicy",
        shape_rule: "not applicable",
        dtype_rule: "defaults CUDA autocast to F16 and validates canonical supported autocast dtypes",
        accumulation_dtype: "policy only",
        layout_rule: "not applicable",
        device_rule: "CUDA policy namespace without process-global state",
        numeric_rule: "no tensor arithmetic",
        tolerance: "exact policy fields",
        determinism: "pure policy construction",
        cancellation_points: "before construction and before return",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/cuda_amp_autocast.json",
        evidence_fixture_sha256: "a5c592fd9bb7e6ee940df5596eacb6d64d05d8ed59366def0c609724da187023",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F9ED42F7BFDF",
        baseline_overload_id: "COMFY-TENSOR-OP-F9ED42F7BFDF:blocked",
        baseline_fixture_sha256: "8e0001e2219566fdff439cee3058baf6839eeaec70b575eb212eee3625dbbc7d",
        overload_id: "zed.native.device.cuda-name.capability-adapter.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["String"]"#,
        rust_signature: "fn cuda_get_device_name_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<String, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "read only",
        alias_rule: "returns an owned projection from canonical NativeDeviceProperties",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires an exact CUDA or ROCm capability matrix and matching DeviceId",
        numeric_rule: "exact ordinal and kind validation",
        tolerance: "exact UTF-8 name",
        determinism: "immutable capability projection",
        cancellation_points: "before security validation and before return",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/cuda_get_device_name.json",
        evidence_fixture_sha256: "6d0a62a823b95539743ced6690840b5cd9432c5f28c54e70e29e7b7cf28c2b2c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F18E1AE1B857",
        baseline_overload_id: "COMFY-TENSOR-OP-F18E1AE1B857:blocked",
        baseline_fixture_sha256: "8e232266de27c4e4f922e5151aa6c89c9b5706ac5bd7e8037905593ad50bfeaa",
        overload_id: "zed.native.worker.cuda-memory-stats.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["BTreeMap<String, u64>"]"#,
        rust_signature: "fn comfy_worker::cuda_memory_stats_exact_native(capabilities: &BackendCapabilityMatrix, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<BTreeMap<String, u64>, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "device-kind adapter over authoritative MemoryAccountingSnapshot",
        shape_rule: "not applicable",
        dtype_rule: "u64 byte counters",
        accumulation_dtype: "u64",
        layout_rule: "stable named-stat map",
        device_rule: "requires canonical CUDA or ROCm capability ownership",
        numeric_rule: "reports active and reserved bytes from authoritative worker accounting",
        tolerance: "exact integers",
        determinism: "snapshot-derived stable map",
        cancellation_points: "before device validation, before accounting lookup, and before publication",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/cuda_memory_stats.json",
        evidence_fixture_sha256: "0d1a1a34cfc849a49f802989971f96f7bf98200f58a0d683c210ce37947a3096",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-FA7DD244B7CA",
        baseline_overload_id: "COMFY-TENSOR-OP-FA7DD244B7CA:blocked",
        baseline_fixture_sha256: "9a299a5784219e5f7552d5981cf940070658032d6bf5ed846af5cdf8e2d333ec",
        overload_id: "zed.native.tensor.exp.function-out-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"out","kind":"keyword_only","type":"Option<&mut Tensor>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn exp_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, out: Option<&mut Tensor>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place when out is absent; atomic whole-handle replacement when out is present",
        alias_rule: "canonical Task 63 exp output; out and return share its completed storage",
        shape_rule: "preserves input shape and resizes the Rust out handle atomically",
        dtype_rule: "certified CPU F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical exp contiguous output",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "canonical CpuBackend exponential unary kernel",
        tolerance: "1e-5 absolute",
        determinism: "fixed element order",
        cancellation_points: "canonical kernel boundaries and immediately before optional out publication",
        vjp_rule: "when out is absent, output_gradient multiplied by exp(input); out form is non-autograd",
        jvp_rule: "when out is absent, input_tangent multiplied by exp(input); out form is non-autograd",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/exp_function.json",
        evidence_fixture_sha256: "e99dcaa6780dc5063e7a2e2f29964bafc5b537cb7e32ce615da61d25163abcef",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F27D07B4E10D",
        baseline_overload_id: "COMFY-TENSOR-OP-F27D07B4E10D:blocked",
        baseline_fixture_sha256: "c6ff8e505eb3f51969941c253a58a356ec27b70ff45e8a7229739efaaaa83d23",
        overload_id: "zed.native.tensor.lerp.function-canonical.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"end","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"weight","kind":"positional_or_keyword","type":"f32","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn lerp_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, end: &Tensor, weight: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place",
        alias_rule: "thin function adapter over canonical Task 55 lerp",
        shape_rule: "canonical binary broadcast of input and end",
        dtype_rule: "certified CPU F32 operands and scalar weight",
        accumulation_dtype: "F32",
        layout_rule: "logical broadcast traversal and contiguous output",
        device_rule: "co-located CPU ordinal zero and one source stream",
        numeric_rule: "input + weight * (end - input)",
        tolerance: "1e-5 absolute",
        determinism: "fixed broadcast element order",
        cancellation_points: "canonical bounded traversal and before publication",
        vjp_rule: "reduces (1-weight)*gradient and weight*gradient across broadcast axes",
        jvp_rule: "lerps input and end tangents with the same scalar weight",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/lerp.json",
        evidence_fixture_sha256: "7c4e6c5db338c1f1bb8cb2b0ba1e14976156ab2abce6aaadab387e26eed3cc48",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F15A2D8A6BD4",
        baseline_overload_id: "COMFY-TENSOR-OP-F15A2D8A6BD4:blocked",
        baseline_fixture_sha256: "56f2069b589ffbe67a9fa2d593b1758aaf00e99f52be6e29e73137f12d8e72a8",
        overload_id: "zed.native.worker.npu-mem-get-info.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"topology","kind":"positional_or_keyword","type":"MemoryTopology","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["(u64, u64)"]"#,
        rust_signature: "fn comfy_worker::npu_mem_get_info_exact_native(capabilities: &BackendCapabilityMatrix, topology: &MemoryTopology, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<(u64, u64), NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "thin NPU adapter over canonical topology and memory-accounting owners",
        shape_rule: "not applicable",
        dtype_rule: "u64 byte counts",
        accumulation_dtype: "checked u64 subtraction",
        layout_rule: "not applicable",
        device_rule: "requires an exact NPU capability, unique topology budget, and accounting entry",
        numeric_rule: "returns capacity minus active bytes and total capacity",
        tolerance: "exact integers",
        determinism: "immutable topology and snapshot projection",
        cancellation_points: "before device validation, before lookup, and before return",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/npu_mem_get_info.json",
        evidence_fixture_sha256: "b336ca6caa282c0b90ab2059d79ed80d598d70aeca6a4b1cc1b8d54d829cc511",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-FACB7FC5B252",
        baseline_overload_id: "COMFY-TENSOR-OP-FACB7FC5B252:blocked",
        baseline_fixture_sha256: "b83708ccdcbdc965810d7ac3a2df88e901f5ffff905a785a783ce39da8d484a7",
        overload_id: "zed.native.device.xpu-select-capabilities.v1",
        ordered_parameters_json: r#"[{"name":"available","kind":"positional_or_keyword","type":"&[BackendCapabilityMatrix]","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["&BackendCapabilityMatrix"]"#,
        rust_signature: "fn xpu_set_device_exact_native(available: &[BackendCapabilityMatrix], device: DeviceId, cancellation: &CancellationToken) -> Result<&BackendCapabilityMatrix, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "functional request-scoped selection with no process-global mutable state",
        alias_rule: "borrows the one exact canonical capability matrix",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires a unique configured XPU DeviceId",
        numeric_rule: "exact device identity comparison",
        tolerance: "exact identity",
        determinism: "unique capability selection",
        cancellation_points: "before selection and before return",
        vjp_rule: "device selection is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/xpu_set_device.json",
        evidence_fixture_sha256: "532bced3c273df5ffc4dd1aff38abff47f447c79ba4202147ce919a16c3114d4",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_22",
        operation_id: "COMFY-TENSOR-OP-F3D0014DD82A",
        baseline_overload_id: "COMFY-TENSOR-OP-F3D0014DD82A:blocked",
        baseline_fixture_sha256: "281e24b3169901865ace1e4b3be9e93e0f427d5b0394269003a661fe0f8f6267",
        overload_id: "zed.native.tensor.zeros-like.preserve-format.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"Option<DType>","default":null,"keyword_only":true},{"name":"device","kind":"keyword_only","type":"Option<DeviceId>","default":null,"keyword_only":true},{"name":"memory_format","kind":"keyword_only","type":"Option<MemoryFormatReference>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn zeros_like_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dtype: Option<DType>, device: Option<DeviceId>, memory_format: Option<MemoryFormatReference>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh backend-owned zero-filled storage",
        shape_rule: "preserves input shape including empty tensors",
        dtype_rule: "preserves input dtype unless an explicit canonical dtype is requested",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves non-overlapping input format by default; supports contiguous and channels-last named formats",
        device_rule: "preserves input device unless explicit; certified native CPU allocation rejects external fallback",
        numeric_rule: "every logical element is the exact zero encoding for the output dtype",
        tolerance: "bit exact",
        determinism: "descriptor-derived fill",
        cancellation_points: "before descriptor admission, at backend fill boundaries, and before publication",
        vjp_rule: "constant creation has no input gradient",
        jvp_rule: "constant creation has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-f15a2d8a6bd4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_22/zeros_like.json",
        evidence_fixture_sha256: "72fb1c7b1e627f78bd794cdcb8ba3dd6999d97e6f936939e9312c427e3f3a32d",
    },
]
