&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0B05AB07BE66",
        baseline_overload_id: "COMFY-TENSOR-OP-0B05AB07BE66:blocked",
        baseline_fixture_sha256: "0f393e1596295fbeb6160bb73e5412b5804b8b713c8be8383b9be7cce724a2c9",
        overload_id: "sim.native.tensor.abs.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<f32>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn abs_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimeError>",
        mutation_rule: "out of place; input storage and descriptor are unchanged",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "output shape exactly equals input shape, including scalar and empty tensors",
        dtype_rule: "the certified CPU overload accepts and returns f32",
        accumulation_dtype: "no accumulation",
        layout_rule: "logical values are projected to canonical contiguous output",
        device_rule: "CPU ordinal zero is certified; other devices fail typed",
        numeric_rule: "IEEE absolute value preserves NaN and clears the sign bit of negative zero",
        tolerance: "bit exact except the preserved NaN payload is not compared",
        determinism: "fixed per-element traversal",
        cancellation_points: "before dispatch, inside the canonical backend loop, and before publication",
        vjp_rule: "gradient is output_gradient times sign(input), with zero derivative at either signed zero",
        jvp_rule: "tangent is input_tangent times sign(input), with zero derivative at either signed zero",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/abs.json",
        evidence_fixture_sha256: "ec386f5b1ff92c2606faa39f9a443b998bff149074807e3a6cf4458a24607b3d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0546BABACDB9",
        baseline_overload_id: "COMFY-TENSOR-OP-0546BABACDB9:blocked",
        baseline_fixture_sha256: "11509aa8fdbf69274103c62a46b35359a3d321f2f88a253902802092daada713",
        overload_id: "sim.native.backend.cuda-device-properties.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"DeviceId\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeDeviceProperties\"]",
        rust_signature: "fn cuda_get_device_properties_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<NativeDeviceProperties, ElementwiseRuntimeError>",
        mutation_rule: "read-only projection from the canonical capability matrix",
        alias_rule: "returns an owned bounded property snapshot",
        shape_rule: "not applicable",
        dtype_rule: "property fields are typed integers, booleans, and bounded strings",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "CUDA or ROCm identity and ordinal must exactly match the matrix; missing certified properties fail typed",
        numeric_rule: "memory bytes and major/minor values are exact certified facts",
        tolerance: "exact",
        determinism: "immutable matrix projection",
        cancellation_points: "before validation and before returning the snapshot",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/cuda_get_device_properties.json",
        evidence_fixture_sha256: "44f3d0c122ad8c0fbbbcdf9337ad8f2a631568edae26b732b31de92233324860",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0B36DDFC0CD6",
        baseline_overload_id: "COMFY-TENSOR-OP-0B36DDFC0CD6:blocked",
        baseline_fixture_sha256: "81503b6d3942d224d7a80193eeea817940596ca28f686a0b859ff1fe8e07b543",
        overload_id: "sim.native.tensor.device-parse.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"source\",\"type\":\"str\"}]",
        output_arity: "1",
        output_types_json: "[\"DeviceId\"]",
        rust_signature: "fn device_exact_native(source: &str, cancellation: &CancellationToken) -> Result<DeviceId, ElementwiseRuntimeError>",
        mutation_rule: "pure checked parse",
        alias_rule: "returns a copyable canonical device identity",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "DeviceId alone maps exact native kind aliases and a checked u32 ordinal; an omitted ordinal resolves to zero",
        numeric_rule: "ordinal parsing rejects negative, overflowing, empty, and repeated separators",
        tolerance: "exact",
        determinism: "fixed closed device vocabulary",
        cancellation_points: "before and after parsing",
        vjp_rule: "device identities are non-differentiable",
        jvp_rule: "device identities have no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/device.json",
        evidence_fixture_sha256: "85afdf3db600673af4d6db865a1f5d8ffb157e423b802ab35b4a3239e1518905",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0DB870AE36B5",
        baseline_overload_id: "COMFY-TENSOR-OP-0DB870AE36B5:blocked",
        baseline_fixture_sha256: "51062772a0da3f6060e7224cbfcb8b503f1e24b2060dafd4382a536679399087",
        overload_id: "sim.native.tensor.dim.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"usize\"]",
        rust_signature: "fn dim_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<usize, ElementwiseRuntimeError>",
        mutation_rule: "read-only descriptor query",
        alias_rule: "no tensor is created",
        shape_rule: "returns TensorDescriptor rank exactly; scalar rank is zero",
        dtype_rule: "dtype neutral",
        accumulation_dtype: "not applicable",
        layout_rule: "layout neutral",
        device_rule: "descriptor query does not dispatch a backend",
        numeric_rule: "exact nonnegative integer",
        tolerance: "exact",
        determinism: "immutable descriptor projection",
        cancellation_points: "before and after descriptor projection",
        vjp_rule: "rank metadata is non-differentiable and observed only in shape-control paths",
        jvp_rule: "rank metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/dim.json",
        evidence_fixture_sha256: "1e9ae24caf2efec2c5df131edd282db6ead9e357f95da1f72d58e080775362b5",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0A5DBFB907FD",
        baseline_overload_id: "COMFY-TENSOR-OP-0A5DBFB907FD:blocked",
        baseline_fixture_sha256: "966b324ea081db9624bb255e866f2ec200b40654e7995960d0148b78a8b87fc6",
        overload_id: "sim.native.tensor.finfo.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dtype\",\"type\":\"DType\"}]",
        output_arity: "1",
        output_types_json: "[\"FloatingPointInfo\"]",
        rust_signature: "fn finfo_exact_native(dtype: DType, cancellation: &CancellationToken) -> Result<FloatingPointInfo, ElementwiseRuntimeError>",
        mutation_rule: "pure canonical dtype metadata query",
        alias_rule: "returns a copyable immutable value",
        shape_rule: "not applicable",
        dtype_rule: "DType owns bits, epsilon, min, max, smallest normal, and decimal resolution; non-floating dtypes fail typed",
        accumulation_dtype: "metadata values use f64 representation",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "values are exact constants for every cataloged floating and float8 format",
        tolerance: "bit exact f64 constants",
        determinism: "closed match over canonical DType",
        cancellation_points: "before and after metadata lookup",
        vjp_rule: "dtype metadata is non-differentiable",
        jvp_rule: "dtype metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/finfo.json",
        evidence_fixture_sha256: "7427302f7c1ffbc02434db92b2fe2654c290b088b6541f4d1a0b61bc0e6d4f17",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-07B99A0B13EF",
        baseline_overload_id: "COMFY-TENSOR-OP-07B99A0B13EF:blocked",
        baseline_fixture_sha256: "3cb503ec9e059f4b048dfbcb9a3fdb675dec63256eabbd5f489383a91e3f3987",
        overload_id: "sim.native.tensor.meshgrid.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"inputs\",\"type\":\"nonempty list of scalar or rank-one Tensor\"},{\"default\":\"ij\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"indexing\",\"type\":\"MeshgridIndexing\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<Tensor>\"]",
        rust_signature: "fn meshgrid_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], indexing: MeshgridIndexing, context: &ExecutionContext<'_>) -> Result<Vec<Tensor>, ElementwiseRuntimeError>",
        mutation_rule: "out of place; all inputs remain unchanged",
        alias_rule: "one fresh canonical output storage is returned per input",
        shape_rule: "ij output axes follow input order; xy swaps the first two output axes; scalars contribute length one and empty vectors produce empty grids",
        dtype_rule: "all inputs and outputs share one canonical dtype",
        accumulation_dtype: "VJP accumulation is f32 for the certified differentiable overload",
        layout_rule: "outputs are canonical contiguous tensors",
        device_rule: "CPU ordinal zero is certified and all inputs must share stream",
        numeric_rule: "each output broadcasts its corresponding input value over every other grid axis",
        tolerance: "bit-exact element copying; f32 VJP uses fixed addition order",
        determinism: "row-major traversal with explicit ij or xy mapping",
        cancellation_points: "before validation, every bounded output traversal, during upload, and before publication",
        vjp_rule: "each input gradient sums its corresponding output gradient over all broadcast axes",
        jvp_rule: "input tangents use the identical meshgrid mapping",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/meshgrid.json",
        evidence_fixture_sha256: "70029f6941bb6266b42c966a6008d3153196a2d14b58be2fc5af4c392f5ddc9e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-015751FC6965",
        baseline_overload_id: "COMFY-TENSOR-OP-015751FC6965:blocked",
        baseline_fixture_sha256: "4c9979616a33f3751a72c9b4388bed0f27901f5fc0babb381bbdecb93212da97",
        overload_id: "sim.native.tensor.signbit.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"real Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn signbit_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimeError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh boolean storage",
        shape_rule: "output shape exactly equals input shape",
        dtype_rule: "canonical scalar codecs handle boolean, signed, unsigned, and floating inputs; complex inputs fail typed",
        accumulation_dtype: "no accumulation",
        layout_rule: "canonical contiguous boolean output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "floating sign uses the encoded IEEE sign including negative zero and signed NaN; signed integers test less than zero; unsigned and bool are false",
        tolerance: "bit exact",
        determinism: "fixed scalar-codec traversal",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "boolean sign classification is non-differentiable and its observed quantization call is forward only",
        jvp_rule: "boolean sign classification has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/signbit.json",
        evidence_fixture_sha256: "b59d49c6a4d964694c8c3d7e6e5ee12dd00c4c639bb2d17bbf24cb74179b9bb0",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0BDEE629B8C6",
        baseline_overload_id: "COMFY-TENSOR-OP-0BDEE629B8C6:blocked",
        baseline_fixture_sha256: "19e7415cbf046d79a9619ecedead983ad9e3f1c1e61654ebecbf76ddb658486a",
        overload_id: "sim.native.tensor.sub-in-place.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Tensor<f32>\"},{\"default\":1.0,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"alpha\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor alias\"]",
        rust_signature: "fn subtract_in_place_with_context_exact_native<'a>(backend: &CpuBackend, input: &'a mut Tensor, other: &Tensor, alpha: f32, context: &ExecutionContext<'_>) -> Result<&'a Tensor, ElementwiseRuntimeError>",
        mutation_rule: "stages input minus alpha times other and commits the input handle once after final cancellation",
        alias_rule: "returns the mutated input handle; canonical copy-on-write keeps preexisting aliases unchanged",
        shape_rule: "observed overload requires equal shapes and streams",
        dtype_rule: "certified CPU overload requires f32 input, other, and result",
        accumulation_dtype: "f32",
        layout_rule: "commit uses canonical contiguous storage",
        device_rule: "CPU ordinal zero is certified; cross-device input fails typed",
        numeric_rule: "computes input - alpha * other with the canonical multiply and subtract primitives",
        tolerance: "exact f32 primitive ordering",
        determinism: "fixed two-stage primitive order",
        cancellation_points: "before either primitive, within backend loops, and before the single handle commit",
        vjp_rule: "input gradient is output_gradient and other gradient is -alpha times output_gradient",
        jvp_rule: "output tangent is input_tangent - alpha times other_tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/sub_in_place.json",
        evidence_fixture_sha256: "d5f2d6c8085de1bfa0695c99c5664ba566d0cc3652c8350232df3aa49f76ee54",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0678D863EEBA",
        baseline_overload_id: "COMFY-TENSOR-OP-0678D863EEBA:blocked",
        baseline_fixture_sha256: "eee990e56e08de5bb25c40732cb173e0d194f3a84618126e4fc2554a9be439c1",
        overload_id: "sim.native.tensor.triu.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"diagonal\",\"type\":\"isize\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn triu_with_context_exact_native(backend: &CpuBackend, input: &Tensor, diagonal: isize, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimeError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "rank must be at least two; the last two axes define rows and columns and leading axes batch independently",
        dtype_rule: "preserves every canonical scalar dtype through exact byte copies and canonical zero encoding",
        accumulation_dtype: "no accumulation",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "keeps element [row,column] exactly when column-row is at least diagonal and writes positive canonical zero otherwise",
        tolerance: "bit exact",
        determinism: "fixed row-major mask geometry",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "output gradient is masked by the identical triangular geometry",
        jvp_rule: "input tangent is masked by the identical triangular geometry",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/triu.json",
        evidence_fixture_sha256: "d70e19cc2aa0f8627dfb02ab99c6d19ea884caa9d4dd4b32fd2c53d5a9bf75bd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-010917B0D872",
        baseline_overload_id: "COMFY-TENSOR-OP-010917B0D872:blocked",
        baseline_fixture_sha256: "80b3abe116d6fbdab36dca48438e96da3ba741e75fa55c25b8c31526d9ecb559",
        overload_id: "sim.native.tensor.vander.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"rank-one floating Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"columns\",\"type\":\"optional usize\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"increasing\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn vander_with_context_exact_native(backend: &CpuBackend, input: &Tensor, columns: Option<usize>, increasing: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimeError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "rank-one length M input returns [M,N], where omitted N equals M and zero N is valid",
        dtype_rule: "preserves canonical floating dtype; unrepresentable float8 powers fail typed",
        accumulation_dtype: "f32 for the certified VJP and JVP",
        layout_rule: "canonical contiguous row-major output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "columns contain powers N-1 through zero by default or zero through N-1 when increasing; x to power zero is one",
        tolerance: "exact powi and canonical scalar-codec conversion; f32 gradients use fixed order",
        determinism: "fixed row then column traversal",
        cancellation_points: "before validation, at bounded output intervals, during upload, and before publication",
        vjp_rule: "input gradient sums output_gradient times exponent times input^(exponent-1) over columns",
        jvp_rule: "each output tangent is exponent times input^(exponent-1) times input_tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/vander.json",
        evidence_fixture_sha256: "af60ffeb1129340c0cb9b787d0fa5b666ca960d64bc71ebd2ddc8d690e67a104",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-01475E433DB3",
        baseline_overload_id: "COMFY-TENSOR-OP-01475E433DB3:blocked",
        baseline_fixture_sha256: "c8043ae409c1c86d49230f71c2fec32c935dbe6a2f70837e5726c67078437cbd",
        overload_id: "sim.native.backend.xpu-current-device.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"u32\"]",
        rust_signature: "fn xpu_current_device_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<u32, ElementwiseRuntimeError>",
        mutation_rule: "read-only capability-context query with no process-global device mutation",
        alias_rule: "returns a copyable ordinal",
        shape_rule: "not applicable",
        dtype_rule: "exact u32 ordinal",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "the canonical matrix must identify XPU; other kinds fail typed",
        numeric_rule: "returns the exact canonical DeviceId ordinal",
        tolerance: "exact",
        determinism: "immutable matrix projection",
        cancellation_points: "before validation and before return",
        vjp_rule: "device selection metadata is non-differentiable",
        jvp_rule: "device selection metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/xpu_current_device.json",
        evidence_fixture_sha256: "cb99e45b838e57159ce205693dbb9142b93397ce37d6bb3cf117c224c841526f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-04A23E8A6156",
        baseline_overload_id: "COMFY-TENSOR-OP-04A23E8A6156:blocked",
        baseline_fixture_sha256: "3d0edc63389a129097bd6c1e8d52c0378f4d9cdc2b9712f29b16fb2b5aa59afc",
        overload_id: "sim.native.backend.xpu-bf16-support.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"bool\"]",
        rust_signature: "fn xpu_is_bf16_supported_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimeError>",
        mutation_rule: "read-only capability query",
        alias_rule: "returns a copyable boolean",
        shape_rule: "not applicable",
        dtype_rule: "queries canonical Bf16 support rather than a parallel hardware flag",
        accumulation_dtype: "not applicable",
        layout_rule: "support is true when at least one exact Bf16 matrix row is certified",
        device_rule: "the canonical matrix must identify XPU; other kinds fail typed",
        numeric_rule: "exact boolean with no optimistic fallback",
        tolerance: "exact",
        determinism: "immutable sorted capability projection",
        cancellation_points: "before validation and before return",
        vjp_rule: "capability metadata is non-differentiable",
        jvp_rule: "capability metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/xpu_is_bf16_supported.json",
        evidence_fixture_sha256: "08d0f1f3da690b16320efd5adff052ae1f81797d829cb3b4f62c5e58a5d5bbb4",
    },
]
