&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-1599F5E140D0",
        baseline_overload_id: "COMFY-TENSOR-OP-1599F5E140D0:blocked",
        baseline_fixture_sha256: "6ebcc68787163e4e05a065ae1a4a99759d6597523f4616343a29d8b0115d99df",
        overload_id: "sim.native.tensor.ceil.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"real Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn ceil_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place; the input handle and storage are unchanged",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "output shape exactly equals input shape, including scalar and empty tensors",
        dtype_rule: "preserves canonical real, integer, and boolean dtypes; complex input fails typed",
        accumulation_dtype: "no accumulation; the certified derivative overload uses f32",
        layout_rule: "logical values are projected to canonical contiguous output",
        device_rule: "CPU ordinal zero is certified; other devices fail typed",
        numeric_rule: "floating values use IEEE ceiling while integers and booleans are copied exactly; signed zero is preserved",
        tolerance: "canonical dtype encoding is exact",
        determinism: "fixed row-major scalar-codec traversal",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "the certified f32 VJP is a zero tensor because ceiling is piecewise constant",
        jvp_rule: "the certified f32 JVP is a zero tensor because ceiling is piecewise constant",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/ceil.json",
        evidence_fixture_sha256: "b177f4f2f71f662dc0f7a5817740741aec6d170e6704c48a1b5a17532abcc278",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-10FC4A6ED9AA",
        baseline_overload_id: "COMFY-TENSOR-OP-10FC4A6ED9AA:blocked",
        baseline_fixture_sha256: "e9dd5e9ecbdd5f66963811f3b5e834077da27b2ce490fa72dce0fdd7d88e97e2",
        overload_id: "sim.native.tensor.tanh.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<f32>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn tanh_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "output shape exactly equals input shape",
        dtype_rule: "the certified CPU overload accepts and returns f32",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "uses the canonical CPU hyperbolic-tangent primitive with IEEE NaN and signed-zero behavior",
        tolerance: "one micro-unit absolute tolerance against the checked f32 profile",
        determinism: "fixed canonical backend traversal",
        cancellation_points: "before dispatch, inside the backend loop, and before publication",
        vjp_rule: "output gradient is multiplied by one minus tanh(input) squared",
        jvp_rule: "input tangent is multiplied by one minus tanh(input) squared",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/tanh.json",
        evidence_fixture_sha256: "cc4b7b52b31dd8b2c022dc533a010766e2fb10e4aeb175e1785fba7de78f3326",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-0FB8594194A8",
        baseline_overload_id: "COMFY-TENSOR-OP-0FB8594194A8:blocked",
        baseline_fixture_sha256: "29a2aef2b956f8723c9a4db486bf29456ab6a38477329623f4aa4bdacf276a32",
        overload_id: "sim.native.tensor.acos.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<f32>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn acos_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "output shape exactly equals input shape",
        dtype_rule: "the certified CPU overload accepts and returns f32",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "uses IEEE f32 arccosine; values outside minus one through one yield NaN",
        tolerance: "one micro-unit absolute tolerance on finite fixture values",
        determinism: "fixed row-major traversal",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "output gradient is negative output_gradient divided by sqrt(one minus input squared)",
        jvp_rule: "input tangent is negative input_tangent divided by sqrt(one minus input squared)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/acos.json",
        evidence_fixture_sha256: "6678232d7615c9853953259c5a114f16837e4b61909df4578506adf882be51f0",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-14815FE141B4",
        baseline_overload_id: "COMFY-TENSOR-OP-14815FE141B4:blocked",
        baseline_fixture_sha256: "1994a71c9d3ca3fe3362d08430dfdd7fdd9fa9cd9042f1fc6a9c3a5c40671841",
        overload_id: "sim.native.backend.cudnn-availability.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"bool\"]",
        rust_signature: "fn cudnn_is_available_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwoError>",
        mutation_rule: "read-only capability query",
        alias_rule: "returns a copyable boolean",
        shape_rule: "not applicable to backend metadata",
        dtype_rule: "not applicable to backend metadata",
        accumulation_dtype: "not applicable to backend metadata",
        layout_rule: "not applicable to backend metadata",
        device_rule: "returns false for every current native profile because no certified Sim backend exposes or depends on a cuDNN ABI",
        numeric_rule: "exact boolean with no optimistic library probe or external-process fallback",
        tolerance: "exact",
        determinism: "immutable native capability policy",
        cancellation_points: "before and after the capability query",
        vjp_rule: "backend availability metadata is non-differentiable",
        jvp_rule: "backend availability metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/cudnn_is_available.json",
        evidence_fixture_sha256: "1417edb9bf3decbebfc4e5ab7b881351db11b214c1bc5b1f017fae523f7058ae",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-14218933001D",
        baseline_overload_id: "COMFY-TENSOR-OP-14218933001D:blocked",
        baseline_fixture_sha256: "4a20cf214bf9eb067e8eb36a21f19e74e3b73bf20d777a173b51fc2016a9f81e",
        overload_id: "sim.native.tensor.eq-scalar.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn equal_scalar_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: Scalar, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh boolean storage",
        shape_rule: "output shape exactly equals input shape",
        dtype_rule: "the scalar is checked and encoded through the input canonical dtype before comparison",
        accumulation_dtype: "no accumulation",
        layout_rule: "canonical contiguous boolean output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "decoded numeric equality treats either signed zero as equal and every NaN as unequal",
        tolerance: "exact numeric equality",
        determinism: "fixed scalar-codec traversal",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "boolean equality is non-differentiable and all observed uses are forward control paths",
        jvp_rule: "boolean equality has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/eq.json",
        evidence_fixture_sha256: "101b135af9e29f59e3f9e9259049bdb09b4e240c06f1119fdd013a21e261d44b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-160E75523010",
        baseline_overload_id: "COMFY-TENSOR-OP-160E75523010:blocked",
        baseline_fixture_sha256: "1abcc42bdc81f18f32f9b43a29a25f9b4b72cbe83fd88316e979df7a08d9bd8a",
        overload_id: "sim.native.autograd.inference-mode-enabled.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"bool\"]",
        rust_signature: "fn is_inference_mode_enabled_exact_native(mode: GradientMode, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwoError>",
        mutation_rule: "read-only projection from the canonical GradientMode",
        alias_rule: "returns a copyable boolean",
        shape_rule: "not applicable to execution metadata",
        dtype_rule: "not applicable to execution metadata",
        accumulation_dtype: "not applicable to execution metadata",
        layout_rule: "not applicable to execution metadata",
        device_rule: "device independent",
        numeric_rule: "true exactly for GradientMode::Inference and false for every other canonical mode",
        tolerance: "exact",
        determinism: "immutable enum projection",
        cancellation_points: "before and after the mode projection",
        vjp_rule: "execution mode metadata is non-differentiable",
        jvp_rule: "execution mode metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/is_inference_mode_enabled.json",
        evidence_fixture_sha256: "5d0e5a6f0d72fe5b1167fca6c5a500fb863338cf87c441f1992da65c6b48737a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-190DE0F94657",
        baseline_overload_id: "COMFY-TENSOR-OP-190DE0F94657:blocked",
        baseline_fixture_sha256: "c4d605a7257fc052af8d1b0484ba2e49f92108bd9b623fd3d8280e0366ba46f0",
        overload_id: "sim.native.runtime.jit-scripting.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"bool\"]",
        rust_signature: "fn jit_is_scripting_exact_native(cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwoError>",
        mutation_rule: "pure native runtime query",
        alias_rule: "returns a copyable boolean",
        shape_rule: "not applicable to runtime metadata",
        dtype_rule: "not applicable to runtime metadata",
        accumulation_dtype: "not applicable to runtime metadata",
        layout_rule: "not applicable to runtime metadata",
        device_rule: "device independent",
        numeric_rule: "always false because native Rust execution never enters Python TorchScript compilation",
        tolerance: "exact",
        determinism: "compile-time production boundary",
        cancellation_points: "before returning the runtime fact",
        vjp_rule: "runtime metadata is non-differentiable",
        jvp_rule: "runtime metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/jit_is_scripting.json",
        evidence_fixture_sha256: "ba4350cac7f8c4a89f420df5df72fab7923b62839255c4af3ab5e5c338164faa",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-1912E4160DE1",
        baseline_overload_id: "COMFY-TENSOR-OP-1912E4160DE1:blocked",
        baseline_fixture_sha256: "27ea1d372a1429071a911fb5b306c8aef0bcf2ab3b9ede986d61762bacf040ce",
        overload_id: "sim.native.tensor.log.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<f32>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn log_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "output shape exactly equals input shape",
        dtype_rule: "the certified CPU overload accepts and returns f32",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "uses the canonical CPU natural-logarithm primitive with IEEE zero, negative, infinity, and NaN behavior",
        tolerance: "one micro-unit absolute tolerance on finite fixture values",
        determinism: "fixed canonical backend traversal",
        cancellation_points: "before dispatch, inside the backend loop, and before publication",
        vjp_rule: "output gradient is divided by input",
        jvp_rule: "input tangent is divided by input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/log.json",
        evidence_fixture_sha256: "2d759cbe35306e8efce5269b28793812acc0f6c2cab38b166aeeeb1cfc41775d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-147180FA6AF4",
        baseline_overload_id: "COMFY-TENSOR-OP-147180FA6AF4:blocked",
        baseline_fixture_sha256: "1ca95b0dc4d3f9c454deee97860a2d57c8ed0672c0352d18ddf455915b7aca3a",
        overload_id: "sim.native.worker.npu-memory-stats.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"DeviceId\"}]",
        output_arity: "1",
        output_types_json: "[\"BTreeMap<String,u64>\"]",
        rust_signature: "fn npu_memory_stats_exact_native(capabilities: &BackendCapabilityMatrix, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<BTreeMap<String,u64>, NativeMemoryStatsError>",
        mutation_rule: "read-only projection from canonical worker memory accounting",
        alias_rule: "returns an owned ordered map",
        shape_rule: "the map contains active_bytes.all.current and reserved_bytes.all.current",
        dtype_rule: "all byte counts are exact u64 values",
        accumulation_dtype: "checked u64 accounting owned by MemoryPlacementInventory",
        layout_rule: "ordered string-keyed map",
        device_rule: "the capability matrix must identify NPU and the accounting snapshot must contain the exact ordinal",
        numeric_rule: "active bytes equal accounted NPU allocations; reserved bytes equal active bytes because Sim has no separate caching allocator",
        tolerance: "exact",
        determinism: "immutable worker-accounting projection with sorted keys",
        cancellation_points: "before validation and after map construction",
        vjp_rule: "memory accounting metadata is non-differentiable",
        jvp_rule: "memory accounting metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/npu_memory_stats.json",
        evidence_fixture_sha256: "5fceb8bfcecb66abd56ffdc13964f0a64a673a2062cd1ff545f176566de024bd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-1602683BB161",
        baseline_overload_id: "COMFY-TENSOR-OP-1602683BB161:blocked",
        baseline_fixture_sha256: "b15ee3fb22863a8ba6d3c65bcc092744290f3c5c0b13f520f7ae603f2595504e",
        overload_id: "sim.native.optim.functional-adamw.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"parameters\",\"type\":\"mutable list of Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"gradients\",\"type\":\"list of Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"exponential_averages\",\"type\":\"mutable list of Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"exponential_average_squares\",\"type\":\"mutable list of Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"maximum_exponential_average_squares\",\"type\":\"mutable list of Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"steps\",\"type\":\"list of positive u64\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"amsgrad\",\"type\":\"bool\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"beta1\",\"type\":\"f32\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"beta2\",\"type\":\"f32\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"learning_rate\",\"type\":\"f32\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"weight_decay\",\"type\":\"f32\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"epsilon\",\"type\":\"f32\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"maximize\",\"type\":\"bool\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn adamw_with_context_exact_native(backend: &CpuBackend, parameters: &mut [Tensor], gradients: &[Tensor], exponential_averages: &mut [Tensor], exponential_average_squares: &mut [Tensor], maximum_exponential_average_squares: &mut [Tensor], steps: &[u64], amsgrad: bool, beta1: f32, beta2: f32, learning_rate: f32, weight_decay: f32, epsilon: f32, maximize: bool, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartTwoError>",
        mutation_rule: "stages every parameter and moment tensor before one publication phase; any error or cancellation leaves every caller-owned list unchanged",
        alias_rule: "committed handles point to fresh canonical storage and preexisting aliases retain prior values",
        shape_rule: "parallel lists have equal length and each parameter, gradient, and moment group has exactly matching shape and stream",
        dtype_rule: "the certified CPU overload requires f32 tensors and finite checked scalar configuration",
        accumulation_dtype: "f32 with positive step bounded by checked i32 exponentiation",
        layout_rule: "committed tensors use canonical contiguous storage",
        device_rule: "CPU ordinal zero is certified for every list entry",
        numeric_rule: "uses decoupled weight decay, bias-corrected first and second moments, optional AMSGrad maximum, and optional gradient maximization",
        tolerance: "fixed f32 operation ordering with one micro-unit fixture tolerance",
        determinism: "parameter-list order then row-major element order",
        cancellation_points: "before each parameter, at bounded element intervals, during staging uploads, and before the publication phase",
        vjp_rule: "optimizer updates are terminal state transitions and do not record a reverse-mode node",
        jvp_rule: "optimizer updates do not propagate tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/adamw.json",
        evidence_fixture_sha256: "2e870e41513fa1a1f88255c7863492fd2d112a5a4510a52ef43667d66f1ad0f6",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-10A0FC173128",
        baseline_overload_id: "COMFY-TENSOR-OP-10A0FC173128:blocked",
        baseline_fixture_sha256: "ddeccc27c4a6b4668de00450e0a2479097be3c1e5b23c97e88963a8a2ee32b5c",
        overload_id: "sim.native.tensor.polar.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"magnitude\",\"type\":\"Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"angle\",\"type\":\"Tensor<f32>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<complex64>\"]",
        rust_signature: "fn polar_with_context_exact_native(backend: &CpuBackend, magnitude: &Tensor, angle: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh complex storage",
        shape_rule: "magnitude and angle have equal shape and stream and output preserves that shape",
        dtype_rule: "certified f32 inputs produce canonical complex64 output",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous interleaved real-imaginary output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "real equals magnitude times cosine of angle and imaginary equals magnitude times sine of angle",
        tolerance: "one micro-unit absolute tolerance on each component",
        determinism: "fixed row-major traversal and component order",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "the observed rotary-frequency construction is forward only in the cataloged graph",
        jvp_rule: "the observed rotary-frequency construction does not request tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/polar.json",
        evidence_fixture_sha256: "98d65690a36bce8eb7d73c6bfd8945fc4b53026d6f5bd0f3faf9056092d7d894",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_02",
        operation_id: "COMFY-TENSOR-OP-11C887BB4214",
        baseline_overload_id: "COMFY-TENSOR-OP-11C887BB4214:blocked",
        baseline_fixture_sha256: "0afc52edc4d7d93dda981b99b51d353f04a4b88d5f176706dff5b2b1abfb242f",
        overload_id: "sim.native.tensor.view-as-complex.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"contiguous Tensor<f32> with trailing dimension two\"}]",
        output_arity: "1",
        output_types_json: "[\"read-only Tensor<complex64> view\"]",
        rust_signature: "fn view_as_complex_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartTwoError>",
        mutation_rule: "read-only view construction with no storage mutation",
        alias_rule: "shares the exact source storage through Tensor::reinterpret_contiguous_read_only and cannot acquire a writable lease",
        shape_rule: "removes the final dimension, which must equal two; scalar and other trailing sizes fail typed",
        dtype_rule: "certified contiguous f32 input reinterprets as complex64 with exactly equal byte length",
        accumulation_dtype: "no accumulation",
        layout_rule: "source and target must be zero-offset canonical contiguous descriptors",
        device_rule: "CPU ordinal zero is certified and device plus stream identity are preserved",
        numeric_rule: "each adjacent f32 pair is interpreted as real then imaginary without copying or conversion",
        tolerance: "bit exact storage reinterpretation",
        determinism: "immutable descriptor validation and storage aliasing",
        cancellation_points: "before validation and after checked view construction",
        vjp_rule: "a complex gradient maps each element back to its adjacent real and imaginary f32 pair",
        jvp_rule: "an adjacent f32 tangent pair is reinterpreted through the identical checked view geometry",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-0fb8594194a8",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_02/view_as_complex.json",
        evidence_fixture_sha256: "976c1b5cdf860b56ec38521aa957a663857cbd6adda0e68ba6b5f8bc4c7f1e37",
    },
]
