&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B74E6E64A97F",
        baseline_overload_id: "COMFY-TENSOR-OP-B74E6E64A97F:blocked",
        baseline_fixture_sha256: "480a7010ca5b9a414a4fe1208375f8439bf91978938c387711b431911822c55a",
        overload_id: "zed.native.tensor.add-method.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"Tensor<F32>|Scalar"},{"default":1.0,"keyword_only":true,"kind":"keyword_only","name":"alpha","type":"f32"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn add_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, alpha: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "standard tensor broadcasting; scalar preserves input shape",
        dtype_rule: "F32 leaf profile",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "input + alpha*other through canonical binary owners",
        tolerance: "1e-6 absolute",
        determinism: "canonical row-major binary traversal",
        cancellation_points: "before and during canonical backend stages",
        vjp_rule: "input gradient is reduced output gradient; tensor-other gradient is alpha-scaled and broadcast-reduced",
        jvp_rule: "dinput + alpha*dother",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/add_method.json",
        evidence_fixture_sha256: "b6ea30b9a2db99f7dd7f6b70bdd19380ec500d07e290fdf7995f2a6ded8bc52f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B82E0C11E45D",
        baseline_overload_id: "COMFY-TENSOR-OP-B82E0C11E45D:blocked",
        baseline_fixture_sha256: "fb4f454ea3aecddcdd97c59c6eeca15a06737e35f0be9637340b4488f3e345bf",
        overload_id: "zed.native.tensor.mul-method.canonical.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn mul_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 51 canonical multiply owner",
        shape_rule: "standard broadcasting",
        dtype_rule: "canonical multiply F32 profile",
        accumulation_dtype: "F32",
        layout_rule: "canonical multiply layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical IEEE multiplication",
        tolerance: "1e-6 absolute",
        determinism: "canonical multiply traversal",
        cancellation_points: "canonical multiply checkpoints",
        vjp_rule: "canonical product rule with broadcast reduction",
        jvp_rule: "dinput*other + input*dother",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/mul_method.json",
        evidence_fixture_sha256: "e7fe80d23d653d08c585af67032bae98ae874c99fe6c895d22dd6874717e9693",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B40398C137FF",
        baseline_overload_id: "COMFY-TENSOR-OP-B40398C137FF:blocked",
        baseline_fixture_sha256: "aa0e00ffb308f14a77fbccecaae7dcdd56a325b008dc3d20fc35780f6460852e",
        overload_id: "zed.native.tensor.square-method.canonical.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn square_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 50 canonical square owner",
        shape_rule: "preserves shape",
        dtype_rule: "canonical square F32 profile",
        accumulation_dtype: "F32",
        layout_rule: "canonical square layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "value multiplied by itself",
        tolerance: "1e-6 absolute",
        determinism: "canonical square traversal",
        cancellation_points: "canonical square checkpoints",
        vjp_rule: "2*input*output_gradient",
        jvp_rule: "2*input*input_tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/square_method.json",
        evidence_fixture_sha256: "9a0e9d3c7f3d1bcc527de1ef937e23b33cd6658377353049374324177f7faaad",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B4F8F3B2B2E6",
        baseline_overload_id: "COMFY-TENSOR-OP-B4F8F3B2B2E6:blocked",
        baseline_fixture_sha256: "f8faab94c62c86ed3b299359048af3c275f3d5f1274841b0c8b6bcad09141029",
        overload_id: "zed.native.tensor.atan.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn atan_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "Rust f32 atan with IEEE NaN and infinity behavior",
        tolerance: "1e-6 absolute",
        determinism: "canonical unary traversal",
        cancellation_points: "backend unary checkpoints",
        vjp_rule: "output_gradient/(1+input^2)",
        jvp_rule: "input_tangent/(1+input^2)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/atan.json",
        evidence_fixture_sha256: "a99d2af93e7a77d608ea79e039387a8890e93cab1e6d8e2e37d6005d9bae808a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B4B7266D14A9",
        baseline_overload_id: "COMFY-TENSOR-OP-B4B7266D14A9:blocked",
        baseline_fixture_sha256: "c0fac1a756ab9fd8f40b997cc89bc96abba78dacfdf58aaf249ba37bea20901a",
        overload_id: "zed.native.tensor.bitwise-and.cpu-integral.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"left","type":"integral Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"right","type":"integral Tensor"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn bitwise_and_with_context_exact_native(backend: &CpuBackend, left: &Tensor, right: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "standard broadcasting",
        dtype_rule: "canonical integral and bool promotion; floating and complex reject",
        accumulation_dtype: "promoted integral dtype",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "bit-exact boolean, signed, or unsigned AND",
        tolerance: "exact",
        determinism: "fixed row-major traversal",
        cancellation_points: "bounded element intervals and atomic upload",
        vjp_rule: "non-differentiable",
        jvp_rule: "non-differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/bitwise_and.json",
        evidence_fixture_sha256: "db6104b57f48c753b30a4a6f98405cc60dc87adaded069c5aed6167430f76dc7",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B153098D5C48",
        baseline_overload_id: "COMFY-TENSOR-OP-B153098D5C48:blocked",
        baseline_fixture_sha256: "5de306385200c5b1bb79558dd632928477cefbfa3da7e96032d244ff746aa793",
        overload_id: "zed.native.runtime.cudart.certified-ffi.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"certification","type":"CertifiedNativeFfi"}]"#,
        output_arity: "1",
        output_types_json: r#"["CertifiedNativeFfi"]"#,
        rust_signature: "fn comfy_runtime::cudart_exact_native(certification: &CertifiedNativeFfi, context: &ExecutionContext<'_>) -> Result<&CertifiedNativeFfi, TrustError>",
        mutation_rule: "read-only certification projection",
        alias_rule: "borrows the registry-issued sealed certification",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "does not claim CUDA availability or expose an unchecked raw handle",
        numeric_rule: "exact library, ABI digest, and required-symbol certificate",
        tolerance: "exact",
        determinism: "registry-issued immutable certificate",
        cancellation_points: "before and after certificate inspection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/cudart.json",
        evidence_fixture_sha256: "4fecc53877ead99394c75dff76a5c796a1096dddacedd98d31acdbba04d7ec43",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B1A79A94DDE6",
        baseline_overload_id: "COMFY-TENSOR-OP-B1A79A94DDE6:blocked",
        baseline_fixture_sha256: "23399370fe01fa0b2235b8e45e28ae5103efd2b3deaef80d5a39c8388cd23414",
        overload_id: "zed.native.tensor.is-tensor.typed-projection.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Option<&Tensor>"}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn is_tensor_exact_native(input: Option<&Tensor>, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "read only",
        alias_rule: "copyable bool",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent typed boundary projection",
        numeric_rule: "true exactly when boundary decoding produced a canonical Tensor reference",
        tolerance: "exact",
        determinism: "pure typed projection",
        cancellation_points: "before projection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/is_tensor.json",
        evidence_fixture_sha256: "c77e94044b275344f7f2409b1cdbc90dc61086ec6090d8e4ab31d79141c3affc",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B296530D4BB3",
        baseline_overload_id: "COMFY-TENSOR-OP-B296530D4BB3:blocked",
        baseline_fixture_sha256: "652cb129817af21d89c756bdc3b48f06765b560dc45d84bed083770497bb984c",
        overload_id: "zed.native.tensor.kaiser-window.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"length","type":"u64"},{"default":true,"keyword_only":false,"kind":"positional_or_keyword","name":"periodic","type":"bool"},{"default":12.0,"keyword_only":false,"kind":"positional_or_keyword","name":"beta","type":"f64"},{"default":"F32","keyword_only":true,"kind":"keyword_only","name":"dtype","type":"F32|F64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn kaiser_window_with_context_exact_native(backend: &CpuBackend, length: u64, periodic: bool, beta: f64, dtype: DType, stream: StreamId, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "rank-one [length]; periodic denominator length, symmetric denominator length-1",
        dtype_rule: "F32 or F64",
        accumulation_dtype: "F64",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "Cephes-compatible modified Bessel I0 approximation; length zero empty and length one equals one",
        tolerance: "2e-6 absolute",
        determinism: "fixed index traversal",
        cancellation_points: "bounded sample intervals and atomic upload",
        vjp_rule: "window construction parameters are non-Tensor inputs",
        jvp_rule: "window construction parameters are non-Tensor inputs",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/kaiser_window.json",
        evidence_fixture_sha256: "17edc338617667139b8f523694e7bd3012719558c7d1ba3d03489ee5f4e9b3ad",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B7955A0A7AC9",
        baseline_overload_id: "COMFY-TENSOR-OP-B7955A0A7AC9:blocked",
        baseline_fixture_sha256: "610e64cbb65a3a8534c6bb818770808a74075ed595518c50e2bbbda9d23072f5",
        overload_id: "zed.native.tensor.logaddexp.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"left","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"right","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn logaddexp_with_context_exact_native(backend: &CpuBackend, left: &Tensor, right: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "standard broadcasting",
        dtype_rule: "F32 leaf profile",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "max(left,right)+log1p(exp(-abs(left-right))) with equal-infinity and NaN handling",
        tolerance: "2e-6 absolute",
        determinism: "canonical row-major binary traversal",
        cancellation_points: "backend binary and derivative traversal checkpoints",
        vjp_rule: "stable softmax weights times output gradient with broadcast reduction",
        jvp_rule: "stable softmax weights times input tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/logaddexp.json",
        evidence_fixture_sha256: "6e18c01599f939bc567ad45124fff8726add49a66e5f3c738f6ea73833ddcf47",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B2699A727A6C",
        baseline_overload_id: "COMFY-TENSOR-OP-B2699A727A6C:blocked",
        baseline_fixture_sha256: "038c3ed4ef492af03ac61ff345ee0e6c23b6d33c5671ff62cf3bd24c1f846144",
        overload_id: "zed.native.worker.mlu-empty-cache.canonical-accounting.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"backend","type":"CachedAllocationOwner"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"inventory","type":"MemoryPlacementInventory"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"device","type":"MLU DeviceId"}]"#,
        output_arity: "1",
        output_types_json: r#"["CacheReleaseSummary"]"#,
        rust_signature: "fn comfy_worker::mlu_empty_cache_exact_native(backend: &dyn CachedAllocationOwner, inventory: &mut MemoryPlacementInventory, device: DeviceId, context: &ExecutionContext<'_>) -> Result<CacheReleaseSummary, NativeMemoryStatsError>",
        mutation_rule: "canonical inventory removes only accounted evictable cache records after backend release succeeds",
        alias_rule: "no parallel cache state",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 bytes",
        layout_rule: "not applicable",
        device_rule: "exact MLU device-kind validation",
        numeric_rule: "exact released allocator bytes and accounting action summary",
        tolerance: "exact",
        determinism: "canonical resource-id eviction order",
        cancellation_points: "before release, before each accounting action, and before publication",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/mlu_empty_cache.json",
        evidence_fixture_sha256: "4b7074b5185817891cf956043d03dfa8d9c973d180a896f017411382a58d7046",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B30CBD7D8727",
        baseline_overload_id: "COMFY-TENSOR-OP-B30CBD7D8727:blocked",
        baseline_fixture_sha256: "47de87b9ac102dbca4b48e7f5f50575661fef3c7ca565feab0beb49595bc74fe",
        overload_id: "zed.native.model.add-safe-globals.immutable-admission.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"requested_targets","type":"slice<&str>"}]"#,
        output_arity: "1",
        output_types_json: r#"["SafeGlobalsAdmission"]"#,
        rust_signature: "fn comfy_model::add_safe_globals_exact_native(requested_targets: &[&str], context: &ExecutionContext<'_>) -> Result<SafeGlobalsAdmission, RestrictedPickleError>",
        mutation_rule: "returns immutable request-scoped admission; never mutates the process allowlist",
        alias_rule: "admitted targets borrow static canonical allowlist identifiers",
        shape_rule: "bounded by canonical allowlist length",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "exact sorted and deduplicated allowlist membership",
        tolerance: "exact",
        determinism: "canonical lexical target order",
        cancellation_points: "before and during bounded target validation",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/add_safe_globals.json",
        evidence_fixture_sha256: "a1f58b5fd51b4e4d76ea6391db2610a12b70a515dcea91cf252c67e1d03478c6",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B088976A05AB",
        baseline_overload_id: "COMFY-TENSOR-OP-B088976A05AB:blocked",
        baseline_fixture_sha256: "5a783e1fc7da40737c95d00594441abf36c156aa1c718e1c2282ff2d269133a1",
        overload_id: "zed.native.tensor.tile.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"repeats","type":"slice<i64>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tile_with_context_exact_native(backend: &CpuBackend, input: &Tensor, repeats: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place with publication after full checked copy",
        alias_rule: "fresh canonical storage",
        shape_rule: "left-pad input shape or repeats with ones, reject negative repeats, checked dimension multiplication",
        dtype_rule: "preserves all canonical dtype bytes",
        accumulation_dtype: "none; F32 for VJP",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "byte-exact repeated logical indexing",
        tolerance: "exact forward; 1e-6 derivative",
        determinism: "fixed row-major output traversal",
        cancellation_points: "bounded output intervals and atomic upload",
        vjp_rule: "sum each repeated output-gradient position into its original input index",
        jvp_rule: "tile the input tangent with identical repeats",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/tile.json",
        evidence_fixture_sha256: "8ff299c6bd31d60865b85f4fbc8527ddc0dffc02a435e5d215fe9f9ad97212ee",
    },
]
