&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A2B7298E8EB4",
        baseline_overload_id: "COMFY-TENSOR-OP-A2B7298E8EB4:blocked",
        baseline_fixture_sha256: "bc514d97ac94241fe90830c3b659a45429afa0c28c9cbb08d30f60f4e33ace59",
        overload_id: "zed.native.tensor.detach.cow-alias.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn detach_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "read only",
        alias_rule: "shares canonical Tensor storage until copy-on-write mutation",
        shape_rule: "preserves shape",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves descriptor",
        device_rule: "preserves device and stream",
        numeric_rule: "identity",
        tolerance: "exact",
        determinism: "immutable alias construction",
        cancellation_points: "before and after clone",
        vjp_rule: "stops reverse-mode gradients",
        jvp_rule: "stops forward-mode tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/detach.json",
        evidence_fixture_sha256: "22d9ff082ab3eb27c0336338ef55327a615fb6724d345a59cd01c5b654c713fd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A496777C1987",
        baseline_overload_id: "COMFY-TENSOR-OP-A496777C1987:blocked",
        baseline_fixture_sha256: "f5c6fe66177a6cad5c2e5f41ad742679551e7d1060bd3d4833f4f95ae706afcb",
        overload_id: "zed.native.tensor.mul-in-place.atomic-cow.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor|Scalar","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["unit"]"#,
        rust_signature: "fn mul_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartFourteenError>",
        mutation_rule: "atomically replaces the receiver after successful canonical multiplication",
        alias_rule: "canonical Tensor copy-on-write isolates shared aliases at mutation",
        shape_rule: "broadcast output must equal receiver shape",
        dtype_rule: "canonical multiply promotion constrained to receiver dtype for scalar form",
        accumulation_dtype: "operation dtype",
        layout_rule: "contiguous staged result",
        device_rule: "CPU ordinal zero with matching streams",
        numeric_rule: "receiver times other",
        tolerance: "operation dtype",
        determinism: "canonical binary traversal",
        cancellation_points: "during staging and before receiver publication",
        vjp_rule: "mutation is recorded by higher-level autograd ownership",
        jvp_rule: "mutation is recorded by higher-level autograd ownership",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/mul_in_place.json",
        evidence_fixture_sha256: "e6b7273a3f060923f296d8149d0c62ee6502c77a403ce1c225f5290eb22eb0e3",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A3A6638578F7",
        baseline_overload_id: "COMFY-TENSOR-OP-A3A6638578F7:blocked",
        baseline_fixture_sha256: "50682fa957e2f9cff78ce6d89828b161854e77397d009a869b7ff6aee937f2a5",
        overload_id: "zed.native.tensor.abs-function.canonical-unary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn abs_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 43 canonical absolute unary operation",
        shape_rule: "preserves shape",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "absolute value preserving NaN",
        tolerance: "exact",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical unary checkpoints",
        vjp_rule: "output gradient times sign of input",
        jvp_rule: "input tangent times sign of input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/abs_function.json",
        evidence_fixture_sha256: "6e381a48777087fc51d0b542d55984fb12a417c62b86dfcdd6d70b80302d681c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A46ED7068064",
        baseline_overload_id: "COMFY-TENSOR-OP-A46ED7068064:blocked",
        baseline_fixture_sha256: "d7d6d4d029a9150c104a72a8f22269f6440af950994cb9efa0df0a5ea14b7abc",
        overload_id: "zed.native.tensor.argsort.stable-i64.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<real|integer|bool>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":-1,"keyword_only":true},{"name":"descending","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"stable","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn argsort_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, descending: bool, stable: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh index storage",
        shape_rule: "preserves shape with checked negative axis",
        dtype_rule: "real integer or boolean input and I64 output",
        accumulation_dtype: "not applicable",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "total order with NaNs after finite values when ascending and stable source-order ties",
        tolerance: "exact indices",
        determinism: "stable mode preserves source index ties",
        cancellation_points: "per sort lane and output allocation",
        vjp_rule: "non-differentiable indices",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/argsort.json",
        evidence_fixture_sha256: "5159450fbf9237fe1a208559be82bfca5bdc2199f4b2a4861ab7077d99c64c9d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A59D885AD4F9",
        baseline_overload_id: "COMFY-TENSOR-OP-A59D885AD4F9:blocked",
        baseline_fixture_sha256: "d863a3bbd92e4b06f83838e2f68a5d958fc6ed9014b166deae2f3bdde5ba76a8",
        overload_id: "zed.native.tensor.autocast.explicit-policy.v1",
        ordered_parameters_json: r#"[{"name":"device_type","kind":"positional_or_keyword","type":"DeviceKind","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"optional<DType>","default":null,"keyword_only":true},{"name":"enabled","kind":"keyword_only","type":"bool","default":true,"keyword_only":true},{"name":"cache_enabled","kind":"keyword_only","type":"optional<bool>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["AutocastPolicy"]"#,
        rust_signature: "fn autocast_exact_native(device_type: DeviceKind, dtype: Option<DType>, enabled: bool, cache_enabled: Option<bool>, cancellation: &CancellationToken) -> Result<AutocastPolicy, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "returns immutable execution-scoped policy",
        alias_rule: "reuses canonical AutocastPolicy",
        shape_rule: "not applicable",
        dtype_rule: "floating dtype; CPU defaults BF16 and accelerators default F16",
        accumulation_dtype: "policy dependent",
        layout_rule: "not applicable",
        device_rule: "explicit device kind without process-global state",
        numeric_rule: "typed policy construction",
        tolerance: "exact",
        determinism: "immutable value",
        cancellation_points: "before and after construction",
        vjp_rule: "policy is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/autocast.json",
        evidence_fixture_sha256: "d125d0298ae203bd703ae94d0fa6f32e7e473c991d6b16db1ed022b49e2570e1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-9F0E29E01970",
        baseline_overload_id: "COMFY-TENSOR-OP-9F0E29E01970:blocked",
        baseline_fixture_sha256: "ed2f2bf420621bd7a02096e18a0364a7c2f7d35be925e28091771074b9636e60",
        overload_id: "zed.native.model.math-sdp-reduction.attention-policy.v1",
        ordered_parameters_json: r#"[{"name":"enabled","kind":"positional_or_keyword","type":"bool","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["MathSdpReductionPolicy"]"#,
        rust_signature: "fn allow_fp16_bf16_reduction_math_sdp_exact_native(enabled: bool, context: &ExecutionContext<'_>) -> Result<MathSdpReductionPolicy, AttentionError>",
        mutation_rule: "returns immutable policy",
        alias_rule: "comfy_model attention remains the sole policy owner",
        shape_rule: "not applicable",
        dtype_rule: "controls F16 and BF16 math-SDP reduction",
        accumulation_dtype: "policy selected",
        layout_rule: "not applicable",
        device_rule: "applies at native attention dispatch",
        numeric_rule: "exact boolean policy projection",
        tolerance: "exact",
        determinism: "immutable value",
        cancellation_points: "before construction",
        vjp_rule: "policy is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/math_sdp_reduction.json",
        evidence_fixture_sha256: "abe700988e032005fa7a51a86939a90265482e9767e2c4d1d5e571a444f5cece",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-9E2C8B750099",
        baseline_overload_id: "COMFY-TENSOR-OP-9E2C8B750099:blocked",
        baseline_fixture_sha256: "0f0def5665e3bfdddb9bf75d61413f975e9bfc02e14cac82fbe38db0cf8bc4af",
        overload_id: "zed.native.device.cudnn-version.capability-unavailable.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["optional<u64>"]"#,
        rust_signature: "fn cudnn_version_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<Option<u64>, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical backend capability ownership without inventing an ABI version",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "returns none until a certified native cuDNN ABI records a version",
        numeric_rule: "optional version integer",
        tolerance: "exact",
        determinism: "immutable projection",
        cancellation_points: "before projection",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/cudnn_version.json",
        evidence_fixture_sha256: "b795c78813ccea9e5132d90cea435ff06ef238fec926dda3f1a03e9a8e10d303",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-9CD229514F61",
        baseline_overload_id: "COMFY-TENSOR-OP-9CD229514F61:blocked",
        baseline_fixture_sha256: "d1d3c8b3b18c7cfc2e968f225c0cb3060355e95f54511c779a819fd51b9660de",
        overload_id: "zed.native.tensor.concat.canonical-concatenate.v1",
        ordered_parameters_json: r#"[{"name":"inputs","kind":"positional_or_keyword","type":"list<Tensor<F32>>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn concat_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 51 canonical concatenate implementation",
        shape_rule: "non-concatenated dimensions match and selected dimensions sum with checked arithmetic",
        dtype_rule: "matching F32 inputs",
        accumulation_dtype: "F32",
        layout_rule: "logical reads and contiguous output",
        device_rule: "CPU ordinal zero with matching streams",
        numeric_rule: "ordered concatenation",
        tolerance: "exact",
        determinism: "fixed input and logical traversal order",
        cancellation_points: "canonical concatenate checkpoints",
        vjp_rule: "split output gradient by original extents",
        jvp_rule: "concatenate input tangents along the same axis",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/concat.json",
        evidence_fixture_sha256: "1f7edf97002a581d2220829a1c5675dc8c1b8e5599b71f80a94b8e538d3f2076",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-9D504472EFE5",
        baseline_overload_id: "COMFY-TENSOR-OP-9D504472EFE5:blocked",
        baseline_fixture_sha256: "e68353da812ced4a4fbd2381e76f431f42a4fb338761e73ad5575b8581dfe712",
        overload_id: "zed.native.tensor.isposinf.typed-predicate.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<real|integer|bool>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<Bool>"]"#,
        rust_signature: "fn isposinf_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh boolean storage",
        shape_rule: "preserves shape",
        dtype_rule: "real integer or boolean input and Bool output",
        accumulation_dtype: "not applicable",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "true only for positive infinity; false for negative infinity NaN and finite values",
        tolerance: "exact boolean",
        determinism: "fixed traversal",
        cancellation_points: "bounded logical traversal and allocation",
        vjp_rule: "predicate is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/isposinf.json",
        evidence_fixture_sha256: "3fd518d3a26ed50b4fdfa7099559c19ca7eaf9d42f7231af6c7b48bc62ad9dcc",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A680A8A7456F",
        baseline_overload_id: "COMFY-TENSOR-OP-A680A8A7456F:blocked",
        baseline_fixture_sha256: "54eb0c390f391ebfe8750b87742b2a94aad5857f2f6fbf5c93ce9f3907bb20b8",
        overload_id: "zed.native.device.npu-count.topology-projection.v1",
        ordered_parameters_json: r#"[{"name":"topology","kind":"positional_or_keyword","type":"MemoryTopology","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u32"]"#,
        rust_signature: "fn npu_device_count_exact_native(topology: &MemoryTopology, context: &ExecutionContext<'_>) -> Result<u32, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "delegates worker-owned MemoryTopology inventory",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u32 count",
        layout_rule: "not applicable",
        device_rule: "counts NPU topology entries",
        numeric_rule: "exact inventory count",
        tolerance: "exact",
        determinism: "canonical topology traversal",
        cancellation_points: "before and after count",
        vjp_rule: "device query is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/npu_device_count.json",
        evidence_fixture_sha256: "4537177a623027b0311dec0ee4c2124d32335a865b565c858a3e528c57338a53",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A67546895304",
        baseline_overload_id: "COMFY-TENSOR-OP-A67546895304:blocked",
        baseline_fixture_sha256: "528404728df5301680b6ed730502e042f2590493045c08c293d383d29840c6a6",
        overload_id: "zed.native.tensor.view-as-real.checked-reinterpretation.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<Complex64|Complex128>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32|F64> view"]"#,
        rust_signature: "fn view_as_real_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "read only",
        alias_rule: "checked read-only reinterpretation through canonical Tensor storage",
        shape_rule: "appends trailing dimension two",
        dtype_rule: "Complex64 to F32 and Complex128 to F64",
        accumulation_dtype: "matching real component dtype",
        layout_rule: "doubles source strides and appends unit component stride",
        device_rule: "CPU ordinal zero preserving stream",
        numeric_rule: "real and imaginary components without copying",
        tolerance: "exact byte reinterpretation",
        determinism: "descriptor-only view construction",
        cancellation_points: "before and after checked reinterpretation",
        vjp_rule: "inverse checked reinterpretation to complex gradient",
        jvp_rule: "identical view mapping over complex tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/view_as_real.json",
        evidence_fixture_sha256: "536596900ed35340181656e512e4e6480d238a475ce88839d4af7f6359eae8ce",
    },
]
