&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4B4746D5885A",
        baseline_overload_id: "COMFY-TENSOR-OP-4B4746D5885A:blocked",
        baseline_fixture_sha256: "2b80a54706c15920ab7d94f74c43e464cc3fb5db4b1f9d4f9a31d18ace5cd42f",
        overload_id: "zed.native.tensor.acos.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn acos_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical acos owner and returns fresh storage",
        shape_rule: "preserves every input dimension including empty dimensions",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE acos with NaN outside the closed unit interval",
        tolerance: "one ULP against the pinned fixture",
        determinism: "canonical CPU traversal",
        cancellation_points: "before delegation, during canonical traversal, and before publication",
        vjp_rule: "negative upstream gradient divided by square root of one minus input squared",
        jvp_rule: "the same derivative applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/acos_method.json",
        evidence_fixture_sha256: "841c479e435bad5e2341d74b4369c3827884ad245f8f96d8a0612fdee6b45b05",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-472F133627A1",
        baseline_overload_id: "COMFY-TENSOR-OP-472F133627A1:blocked",
        baseline_fixture_sha256: "2a1bbc8779e84c7fe98df0b61381eacad034e7d48c59163bd954dfacd8d793dc",
        overload_id: "zed.native.tensor.bool.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<numeric>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<Bool>"]"#,
        rust_signature: "fn bool_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "canonical DType cast returns fresh storage when dtype changes",
        shape_rule: "preserves shape",
        dtype_rule: "canonical scalar codecs map zero to false and every nonzero value including NaN to true",
        accumulation_dtype: "Bool",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "exact truth conversion through DType",
        tolerance: "exact bits",
        determinism: "canonical cast traversal",
        cancellation_points: "before cast, at bounded cast intervals, and before publication",
        vjp_rule: "boolean cast is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/bool_method.json",
        evidence_fixture_sha256: "a52f0d0766d3887a58fa1898ac2b5cfbd9699e75d8913d81d42496162ffb6f8d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4B6925D60ACD",
        baseline_overload_id: "COMFY-TENSOR-OP-4B6925D60ACD:blocked",
        baseline_fixture_sha256: "996a22a5e69077633a7fdb7785f33c00688309377a881a05432db95f6d31c0e0",
        overload_id: "zed.native.tensor.round.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":0,"keyword_only":true,"kind":"keyword_only","name":"decimals","type":"i32"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn round_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, decimals: i32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F64 only for decimal scaling then checked F32 publication",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "round half to even with finite decimal scaling",
        tolerance: "exact for fixture values",
        determinism: "fixed index traversal",
        cancellation_points: "before validation, at bounded traversal intervals, and before publication",
        vjp_rule: "zero almost everywhere using a canonical zero fill",
        jvp_rule: "zero tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/round_method.json",
        evidence_fixture_sha256: "5c6412c24e3bcc048c8e05ff295a0437bcb8e639ddfc68b0fb852e0ee18acafd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-51695C0FE8D8",
        baseline_overload_id: "COMFY-TENSOR-OP-51695C0FE8D8:blocked",
        baseline_fixture_sha256: "51bc1810bfae25c106f9b16e404dd4032db71c4fbca0fede64be8c14d6e200e3",
        overload_id: "zed.native.tensor.sigmoid.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sigmoid_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical sigmoid owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "stable canonical sigmoid primitive",
        tolerance: "one ULP against the pinned fixture",
        determinism: "canonical CPU traversal",
        cancellation_points: "before delegation, during canonical traversal, and before publication",
        vjp_rule: "upstream times sigmoid times one minus sigmoid",
        jvp_rule: "the same derivative applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/sigmoid_method.json",
        evidence_fixture_sha256: "78504087670387e35a3f31260baf6a37a284f7549d4fb2afd172e5db6a782e7d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4685F95970C6",
        baseline_overload_id: "COMFY-TENSOR-OP-4685F95970C6:blocked",
        baseline_fixture_sha256: "ce57b4bf6d1bef506e259c4ad1258a709281f1df4d74e692f76307aa698ccdf1",
        overload_id: "zed.native.tensor.unique.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<non-complex>"},{"default":true,"keyword_only":true,"kind":"keyword_only","name":"sorted","type":"bool"},{"default":false,"keyword_only":true,"kind":"keyword_only","name":"return_inverse","type":"bool"},{"default":false,"keyword_only":true,"kind":"keyword_only","name":"return_counts","type":"bool"}]"#,
        output_arity: "3",
        output_types_json: r#"["Tensor<input dtype>","Option<Tensor<I64>>","Option<Tensor<I64>>"]"#,
        rust_signature: "fn unique_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, sorted: bool, return_inverse: bool, return_counts: bool, context: &ExecutionContext<'_>) -> Result<UniqueResult, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "all requested outputs use fresh canonical storage",
        shape_rule: "values and counts are one dimensional; inverse indices preserve input shape",
        dtype_rule: "values preserve non-complex input dtype; inverse and counts use I64",
        accumulation_dtype: "I64 counts with checked addition",
        layout_rule: "canonical contiguous outputs",
        device_rule: "CPU ordinal zero",
        numeric_rule: "sorted exact scalar equality; NaN values remain distinct and signed zeros compare equal",
        tolerance: "exact encoded values",
        determinism: "stable value ordering with original index tie break",
        cancellation_points: "before validation, during decode and sort publication intervals, and before each output publication",
        vjp_rule: "unique is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/unique_method.json",
        evidence_fixture_sha256: "872081c403ffd2f0021caf3a2f514a2f31fcacb3d7d39349bbf7a1edb7a0afcb",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4D087B722410",
        baseline_overload_id: "COMFY-TENSOR-OP-4D087B722410:blocked",
        baseline_fixture_sha256: "6c08e9c22c6577c044857c48b9acf6fca5a04676aead18a130266e6405412cf4",
        overload_id: "zed.native.tensor.div.function.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"Tensor<F32> or Scalar"},{"default":null,"keyword_only":true,"kind":"keyword_only","name":"rounding_mode","type":"Option<DivisionRoundingMode>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn div_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, rounding_mode: Option<DivisionRoundingMode>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "delegates true division to the canonical divide owner then applies canonical floor or checked truncation",
        shape_rule: "canonical right-aligned broadcasting",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero with co-located operands",
        numeric_rule: "IEEE division with optional floor or trunc rounding",
        tolerance: "exact for rounded modes and one ULP for true division",
        determinism: "canonical broadcast traversal",
        cancellation_points: "before delegation, at bounded arithmetic intervals, and before publication",
        vjp_rule: "canonical divide gradients for true division and zero gradients for rounded modes",
        jvp_rule: "canonical divide tangent for true division and zero tangent for rounded modes",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/div_function.json",
        evidence_fixture_sha256: "3923d2641115a2fc53bbda893b424171601b3d3686d6d9edb15b6fc659cba3db",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-42AC47EA61EE",
        baseline_overload_id: "COMFY-TENSOR-OP-42AC47EA61EE:blocked",
        baseline_fixture_sha256: "d240bb12d87f1343bfecf04eb96966450667157ba7521046f508fbc3dce66430",
        overload_id: "zed.native.autograd.inference-mode.explicit.v1",
        ordered_parameters_json: r#"[{"default":true,"keyword_only":false,"kind":"positional_or_keyword","name":"enabled","type":"bool"},{"default":"enabled","keyword_only":false,"kind":"positional_or_keyword","name":"current_mode","type":"GradientMode"}]"#,
        output_arity: "1",
        output_types_json: r#"["GradientMode"]"#,
        rust_signature: "fn inference_mode_exact_native(enabled: bool, current_mode: GradientMode, cancellation: &CancellationToken) -> Result<GradientMode, ElementwiseRuntimePartSixError>",
        mutation_rule: "returns an explicit mode value without process global state",
        alias_rule: "value projection only",
        shape_rule: "not applicable to tensor shape",
        dtype_rule: "not applicable to tensor dtype",
        accumulation_dtype: "no numeric accumulation",
        layout_rule: "not applicable to tensor layout",
        device_rule: "device independent explicit autograd mode",
        numeric_rule: "enabled maps to inference and disabled preserves the caller mode",
        tolerance: "exact enum value",
        determinism: "pure value mapping",
        cancellation_points: "before and after mode projection",
        vjp_rule: "inference mode causes AutogradTape to retain no rules",
        jvp_rule: "inference mode records no tangent graph",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/inference_mode.json",
        evidence_fixture_sha256: "b641e3d2f0bb6ffa4384bc769c3ce4ae70a7cb7154ac6b8c71b5e1a0455af7fd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-49949B24BFD5",
        baseline_overload_id: "COMFY-TENSOR-OP-49949B24BFD5:blocked",
        baseline_fixture_sha256: "905f5c4179244d258269379794b2218580c3404a1de5878223a78158c938f27e",
        overload_id: "zed.native.jit.is-tracing.false.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn jit_is_tracing_exact_native(cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartSixError>",
        mutation_rule: "read only",
        alias_rule: "value projection only",
        shape_rule: "not applicable to tensor shape",
        dtype_rule: "not applicable to tensor dtype",
        accumulation_dtype: "no numeric accumulation",
        layout_rule: "not applicable to tensor layout",
        device_rule: "device independent native runtime fact",
        numeric_rule: "native Rust execution has no TorchScript tracing state and returns false",
        tolerance: "exact boolean",
        determinism: "constant native runtime fact",
        cancellation_points: "before projection",
        vjp_rule: "runtime fact is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/jit_is_tracing.json",
        evidence_fixture_sha256: "ce9e65871dec62b6edb876bf9dd9bec69ebe3259acdf12c7b2069ec142b139ae",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4BE7FEEFD9EF",
        baseline_overload_id: "COMFY-TENSOR-OP-4BE7FEEFD9EF:blocked",
        baseline_fixture_sha256: "06b480c6372a4bc753f4dad34bc2993ea7354fb82f484922f8a52fd06a664fd9",
        overload_id: "zed.native.tensor.sinc.function.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sinc_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage from the CPU unary owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "normalized sine cardinal sin of pi x divided by pi x with exact value one at zero",
        tolerance: "one ULP against the pinned fixture",
        determinism: "canonical CPU traversal",
        cancellation_points: "before validation, during canonical traversal, and before publication",
        vjp_rule: "upstream times the analytical normalized sinc derivative with zero derivative at zero",
        jvp_rule: "the same derivative applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/sinc_function.json",
        evidence_fixture_sha256: "0559c0ebc88b0af4e28799552e7ab786889bcc2497e23ce1603ecc2a001219f1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-4130D690D4B2",
        baseline_overload_id: "COMFY-TENSOR-OP-4130D690D4B2:blocked",
        baseline_fixture_sha256: "b7802f09250f115110025354079e5bee1876cf3311a6d6e93fabbe97ff155ba4",
        overload_id: "zed.native.tensor.sqrt.function.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sqrt_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical square root owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE square root with NaN for negative finite values",
        tolerance: "one ULP against the pinned fixture",
        determinism: "canonical CPU traversal",
        cancellation_points: "before delegation, during canonical traversal, and before publication",
        vjp_rule: "upstream divided by twice the square root",
        jvp_rule: "the same derivative applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/sqrt_function.json",
        evidence_fixture_sha256: "5fbf95235f88bff99dc17ddb3e61829483a23e2a5379270bb8d290ea3102faca",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-5278A14360E3",
        baseline_overload_id: "COMFY-TENSOR-OP-5278A14360E3:blocked",
        baseline_fixture_sha256: "79a7d12d6a9e70b84c973e9a5bf454cab29da5f5141bf8a341fe08eaec1fabe9",
        overload_id: "zed.native.autograd.checkpoint.explicit-replay.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"inputs","type":"slice of Tensor"},{"default":true,"keyword_only":true,"kind":"keyword_only","name":"use_reentrant","type":"bool"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"function","type":"native checked tensor function"}]"#,
        output_arity: "1",
        output_types_json: r#"["CheckpointExecution"]"#,
        rust_signature: "fn checkpoint_exact_native(inputs: &[Tensor], use_reentrant: bool, cancellation: &CancellationToken, function: F) -> Result<CheckpointExecution, ElementwiseRuntimePartSixError>",
        mutation_rule: "records immutable input handles and versions; recomputation publishes only complete outputs",
        alias_rule: "saved inputs use canonical Tensor copy on write and outputs retain the function alias contract",
        shape_rule: "forward and recomputation output arity must match",
        dtype_rule: "preserves the wrapped function dtype contract",
        accumulation_dtype: "owned by the wrapped function",
        layout_rule: "preserves the wrapped function layout contract",
        device_rule: "preserves explicit input devices without process global state",
        numeric_rule: "reentrant forward executes in no grad mode and replay executes with gradients enabled; nonreentrant forward executes enabled",
        tolerance: "bit exact when the wrapped function is deterministic",
        determinism: "explicit replay over version checked saved inputs",
        cancellation_points: "before forward, after forward, before version checks, during replay, and before replay publication",
        vjp_rule: "caller replays the wrapped function with GradientMode enabled and records its canonical backward rules",
        jvp_rule: "caller replays the wrapped function with GradientMode enabled and records its canonical tangent rules",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/checkpoint.json",
        evidence_fixture_sha256: "519e1f5952d6cd8e7f976d4ba81023def0a762101f6a30e757fbce162d8e264f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_06",
        operation_id: "COMFY-TENSOR-OP-48C9CD534224",
        baseline_overload_id: "COMFY-TENSOR-OP-48C9CD534224:blocked",
        baseline_fixture_sha256: "1ed49736b4765f234a6931421096d669d8575c938bf9e07dd722c443b42d7255",
        overload_id: "zed.native.xpu.device-properties.projection.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"capabilities","type":"BackendCapabilityMatrix"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"device","type":"DeviceId<Xpu>"}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeDeviceProperties"]"#,
        rust_signature: "fn xpu_get_device_properties_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<NativeDeviceProperties, ElementwiseRuntimePartSixError>",
        mutation_rule: "read only projection",
        alias_rule: "returns an owned clone of canonical properties",
        shape_rule: "not applicable to tensor shape",
        dtype_rule: "property record includes the canonical fp16 capability",
        accumulation_dtype: "no numeric accumulation",
        layout_rule: "not applicable to tensor layout",
        device_rule: "requested XPU identity must exactly match the capability matrix and property record",
        numeric_rule: "memory and version fields are exact canonical owner values",
        tolerance: "exact fields",
        determinism: "pure canonical owner projection",
        cancellation_points: "before validation and after cloning",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-4130d690d4b2",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_06/xpu_get_device_properties.json",
        evidence_fixture_sha256: "81bfb7e24f03c3c5d3b18c925b3196541e29b800e5a2a8a6008183e5030ff10a",
    },
]
