&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AB3C563E635F",
        baseline_overload_id: "COMFY-TENSOR-OP-AB3C563E635F:blocked",
        baseline_fixture_sha256: "a96d4edf5649ec63f9f7434ae3bf2ade21caad3f94fe6a33177380cfe244017f",
        overload_id: "zed.native.tensor.float-tensor.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"values","type":"slice<f32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"shape","type":"slice<u64>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn float_tensor_with_context_exact_native(backend: &CpuBackend, values: &[f32], shape: &[u64], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "checked shape equals value count",
        dtype_rule: "F32 through canonical cast/upload owner",
        accumulation_dtype: "none",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "exact f32 payload",
        tolerance: "exact",
        determinism: "fixed upload order",
        cancellation_points: "canonical upload checkpoints",
        vjp_rule: "constructor values are forward inputs outside Tensor autograd",
        jvp_rule: "constructor values are forward inputs outside Tensor autograd",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/float_tensor.json",
        evidence_fixture_sha256: "e16f74c6267e2cdcdf802ee9e1663af16c34a47b5740334e004d0d66a5d8440d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AA014D6FD446",
        baseline_overload_id: "COMFY-TENSOR-OP-AA014D6FD446:blocked",
        baseline_fixture_sha256: "b50d4ea42f06705b6b029d4c3c051bda306fcfe5092f81cf01914d9e3e2021e9",
        overload_id: "zed.native.tensor.long.canonical-cast.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn long_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical cast owner",
        shape_rule: "preserves shape",
        dtype_rule: "I64",
        accumulation_dtype: "none",
        layout_rule: "canonical cast layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical DType scalar conversion",
        tolerance: "exact",
        determinism: "canonical cast traversal",
        cancellation_points: "canonical cast checkpoints",
        vjp_rule: "integer cast is non-differentiable",
        jvp_rule: "integer cast has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/long.json",
        evidence_fixture_sha256: "dd0be54ca04bd29e414333920f492b73f0cc483decfd06eae326ced839d9aade",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AC4C80016C2B",
        baseline_overload_id: "COMFY-TENSOR-OP-AC4C80016C2B:blocked",
        baseline_fixture_sha256: "e290e4d761b4e850d8ba703e4cd6e0f9044c5a10ca5babb7861d8a8d4d4decfe",
        overload_id: "zed.native.tensor.atan2.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn atan2_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "standard broadcasting",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical f32 atan2 with IEEE NaN and signed-zero quadrants",
        tolerance: "1e-6 absolute",
        determinism: "canonical binary traversal",
        cancellation_points: "backend binary checkpoints",
        vjp_rule: "g_input=g*other/(input^2+other^2), g_other=-g*input/(input^2+other^2) with broadcast reduction",
        jvp_rule: "(other*dinput-input*dother)/(input^2+other^2)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/atan2.json",
        evidence_fixture_sha256: "affd665b03d05bf3da068c0da72022ecc28a46a9ffb76d89f5cc1dc7dd7561d0",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AB6C1D5013D1",
        baseline_overload_id: "COMFY-TENSOR-OP-AB6C1D5013D1:blocked",
        baseline_fixture_sha256: "b6fb535f16eb16229a86d6b598966b09e10d98e6a0eb45571e02ce107e848f99",
        overload_id: "zed.native.model.attention.flash-sdp-selection.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"enabled","type":"bool"}]"#,
        output_arity: "1",
        output_types_json: r#"["MathSdpSelection"]"#,
        rust_signature: "fn comfy_model::enable_flash_sdp_exact_native(enabled: bool, context: &ExecutionContext<'_>) -> Result<MathSdpSelection, AttentionError>",
        mutation_rule: "returns immutable explicit policy",
        alias_rule: "copyable value",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "selection does not certify a device kernel",
        numeric_rule: "exact enabled or disabled mapping",
        tolerance: "exact",
        determinism: "explicit caller-scoped value",
        cancellation_points: "before selection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/enable_flash_sdp.json",
        evidence_fixture_sha256: "f33ce84705608da10875e69614fd43564a0e74c90ea34a4545bdf46d5143f68c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AA097B951CB6",
        baseline_overload_id: "COMFY-TENSOR-OP-AA097B951CB6:blocked",
        baseline_fixture_sha256: "2e02e1c7ab6e6a100782a956d5e38e7e0d0c2d5a86993e56e7b334a3b0bcfc3a",
        overload_id: "zed.native.tensor.baddbmm.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"broadcastable Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"batch1","type":"Tensor<F32>[B,N,M]"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"batch2","type":"Tensor<F32>[B,M,P]"},{"default":1.0,"keyword_only":true,"kind":"keyword_only","name":"beta","type":"f32"},{"default":1.0,"keyword_only":true,"kind":"keyword_only","name":"alpha","type":"f32"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>[B,N,P]"]"#,
        rust_signature: "fn baddbmm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, batch1: &Tensor, batch2: &Tensor, beta: f32, alpha: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place with publication after all stages",
        alias_rule: "fresh canonical storage",
        shape_rule: "beta*input broadcast to [B,N,P] plus alpha*(batch1@batch2)",
        dtype_rule: "F32",
        accumulation_dtype: "F32 fixed inner order",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "beta zero does not read input; fixed multiply-add order",
        tolerance: "1e-5 absolute",
        determinism: "row-major batch,row,column,inner order",
        cancellation_points: "before dispatch, each bounded inner loop, each backend stage, before publication",
        vjp_rule: "analytical gradients for input and both batch matrices with broadcast reduction",
        jvp_rule: "beta*dinput+alpha*(dbatch1@batch2+batch1@dbatch2)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/baddbmm.json",
        evidence_fixture_sha256: "f2098450a624a46f8afbba3d4d6f11110a78e826cc723699a9b5ce79f68c17e4",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-A91E1CFDC489",
        baseline_overload_id: "COMFY-TENSOR-OP-A91E1CFDC489:blocked",
        baseline_fixture_sha256: "4e1f0413fae5e45457445a2bb3491b6b75fef3c062e1833a95bbae70fb3ca63f",
        overload_id: "zed.native.tensor.ceil-function.canonical.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"real Tensor"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn ceil_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 44 canonical ceil owner",
        shape_rule: "preserves shape",
        dtype_rule: "canonical ceil dtype rules",
        accumulation_dtype: "none",
        layout_rule: "canonical ceil layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical IEEE ceiling",
        tolerance: "canonical ceil tolerance",
        determinism: "canonical ceil traversal",
        cancellation_points: "canonical ceil checkpoints",
        vjp_rule: "inherits zero VJP from canonical ceil",
        jvp_rule: "inherits zero JVP from canonical ceil",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/ceil_function.json",
        evidence_fixture_sha256: "64955b7112f069ade98e13589f1ba13f246a5517370a983a9d2b0625b29a1d70",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-A8B4A9E79500",
        baseline_overload_id: "COMFY-TENSOR-OP-A8B4A9E79500:blocked",
        baseline_fixture_sha256: "f67cf09704d12698a2cd9a553adb076580431b724d48d7167acdf0729bf2f46c",
        overload_id: "zed.native.tensor.diag.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"rank-one or rank-two Tensor"},{"default":0,"keyword_only":false,"kind":"positional_or_keyword","name":"diagonal","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn diag_with_context_exact_native(backend: &CpuBackend, input: &Tensor, diagonal: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "rank one constructs a square offset-diagonal matrix; rank two extracts the checked offset diagonal",
        dtype_rule: "preserves canonical dtype bytes",
        accumulation_dtype: "none",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "byte-exact copy with canonical zero encoding",
        tolerance: "exact",
        determinism: "fixed diagonal order",
        cancellation_points: "bounded diagonal intervals and upload",
        vjp_rule: "inverse diagonal extraction or scatter into the original shape",
        jvp_rule: "same linear diagonal transform",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/diag.json",
        evidence_fixture_sha256: "a2a90c456b4b1882ae870a332ca866ff8a0a2e92ba1495b73fef674568496fed",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AC979D604DAA",
        baseline_overload_id: "COMFY-TENSOR-OP-AC979D604DAA:blocked",
        baseline_fixture_sha256: "eaa00db5eddae1edacf37606beb9a2bdc830d9efa6def4298e4e4d37319a7d4e",
        overload_id: "zed.native.tensor.fliplr.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor rank>=2"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn fliplr_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh non-aliasing storage",
        shape_rule: "preserves shape and reverses dimension one",
        dtype_rule: "preserves canonical dtype bytes",
        accumulation_dtype: "none",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "byte-exact logical reversal",
        tolerance: "exact",
        determinism: "fixed row-major traversal",
        cancellation_points: "bounded element intervals and upload",
        vjp_rule: "fliplr of output gradient",
        jvp_rule: "fliplr of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/fliplr.json",
        evidence_fixture_sha256: "23f0e8b90d4035c0bc8fdfea76575cd59f4d0ab6684dfc60aced79429eba516f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-A69CEE614EB5",
        baseline_overload_id: "COMFY-TENSOR-OP-A69CEE614EB5:blocked",
        baseline_fixture_sha256: "97cd2288b72fdaa509797cdca04a2df4030dad8d334a0507d7778be236b66eaa",
        overload_id: "zed.native.worker.npu-availability.topology-projection.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn comfy_worker::npu_is_available_exact_native(topology: &MemoryTopology, context: &ExecutionContext<'_>) -> Result<bool, NativeMemoryStatsError>",
        mutation_rule: "read-only projection",
        alias_rule: "copyable bool",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "true exactly when canonical topology contains an NPU device",
        numeric_rule: "exact count greater than zero",
        tolerance: "exact",
        determinism: "canonical topology order independent",
        cancellation_points: "canonical device-count checkpoints",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/npu_is_available.json",
        evidence_fixture_sha256: "be51c87f2aa70b447284842c3214bfabcfaf2314d92e302993bbdb5b33ce1f7a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AA36FFD0433B",
        baseline_overload_id: "COMFY-TENSOR-OP-AA36FFD0433B:blocked",
        baseline_fixture_sha256: "62195050ea3b8126100b14259d0fe2014b409eafd31f938f59fecbd06a219c6a",
        overload_id: "zed.native.tensor.ones-like.canonical-full-like.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor"},{"default":null,"keyword_only":true,"kind":"keyword_only","name":"dtype","type":"Option<DType>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn ones_like_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical full_like allocation",
        shape_rule: "preserves shape",
        dtype_rule: "explicit dtype or input dtype",
        accumulation_dtype: "none",
        layout_rule: "canonical full_like layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical DType encoding of one",
        tolerance: "exact",
        determinism: "canonical full_like traversal",
        cancellation_points: "canonical full_like checkpoints",
        vjp_rule: "output is constant with respect to input values",
        jvp_rule: "zero tangent with respect to input values",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/ones_like.json",
        evidence_fixture_sha256: "7e2fb8e9c1046cf2ea349469fa35ffec12950a21fb0ed687bf584c0a9a808f4a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AAB5F10B20F5",
        baseline_overload_id: "COMFY-TENSOR-OP-AAB5F10B20F5:blocked",
        baseline_fixture_sha256: "b3aa3ccaae178cf9c120d85bff6cd1818b34ab94ced7094720192ac1ca7dc1a8",
        overload_id: "zed.native.tensor.searchsorted.cpu-f32-i64.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"sorted_sequence","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"values","type":"Tensor<F32>"},{"default":false,"keyword_only":true,"kind":"keyword_only","name":"right","type":"bool"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn searchsorted_with_context_exact_native(backend: &CpuBackend, sorted_sequence: &Tensor, values: &Tensor, right: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "output shape equals values; one-dimensional boundaries broadcast across value rows, otherwise leading dimensions match",
        dtype_rule: "F32 boundaries and values, I64 indices",
        accumulation_dtype: "none",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "lower or upper bound binary search; NaN values insert at row end; unsorted or NaN boundaries fail typed",
        tolerance: "exact indices",
        determinism: "fixed row-major binary search",
        cancellation_points: "bounded values and validation intervals plus upload",
        vjp_rule: "indices are non-differentiable",
        jvp_rule: "indices have no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/searchsorted.json",
        evidence_fixture_sha256: "34cad7b812cfb40a8f70d1f68be35320103fd6826ed933f54e7bf8553368916f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-A68AE691163C",
        baseline_overload_id: "COMFY-TENSOR-OP-A68AE691163C:blocked",
        baseline_fixture_sha256: "ae86ed69dca1f4303b5d33c34b30bdfa78c94d3c784915d84eef2ed729fddd1b",
        overload_id: "zed.native.tensor.tan.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn tan_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical f32 tangent with IEEE NaN, infinity, and signed zero",
        tolerance: "1e-6 absolute on finite fixtures",
        determinism: "canonical unary traversal",
        cancellation_points: "backend unary checkpoints",
        vjp_rule: "output gradient divided by cos(input)^2",
        jvp_rule: "input tangent divided by cos(input)^2",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/tan.json",
        evidence_fixture_sha256: "d2f59c1a27af4196d823323b8e8bd9883d05cf57d8bdda0a74f7d82704286fdd",
    },
]
