&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BDAC082E9091",
        baseline_overload_id: "COMFY-TENSOR-OP-BDAC082E9091:blocked",
        baseline_fixture_sha256: "8daaeee444049c638687c3a6a5fd508a0f5ce12205d13588cf059c091cb5fede",
        overload_id: "zed.native.tensor.requires-grad-method.autograd-tape.v1",
        ordered_parameters_json: r#"[{"name":"tape","kind":"positional_or_keyword","type":"&mut AutogradTape","default":null,"keyword_only":false},{"name":"input","kind":"positional_or_keyword","type":"&Tensor","default":null,"keyword_only":false},{"name":"leaf","kind":"positional_or_keyword","type":"Option<LeafId>","default":null,"keyword_only":false},{"name":"requires_grad","kind":"positional_or_keyword","type":"bool","default":true,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn requires_grad_method_exact_native(tape: &mut AutogradTape, input: &Tensor, leaf: Option<LeafId>, requires_grad: bool, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "mutates only caller-owned AutogradTape leaf participation",
        alias_rule: "returned Tensor shares canonical input storage",
        shape_rule: "preserves shape",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves descriptor",
        device_rule: "preserves device",
        numeric_rule: "checked storage-to-leaf registration or removal",
        tolerance: "exact",
        determinism: "storage identity keyed tape mutation",
        cancellation_points: "before and after staged tape validation",
        vjp_rule: "enables canonical tape accumulation for the checked leaf",
        jvp_rule: "leaf participation metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/requires_grad_method.json",
        evidence_fixture_sha256: "6ac5f437eba2ed0cb39192880a4a99efe04f9d83b8f2e52f7dafba03c97c8ed5",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BA7930023140",
        baseline_overload_id: "COMFY-TENSOR-OP-BA7930023140:blocked",
        baseline_fixture_sha256: "07535252c82c1463f96af2281c788cce8c89315022219dc537d1446b8529304e",
        overload_id: "zed.native.tensor.atanh.cpu-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn atanh_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "Rust f32 atanh with IEEE domain behavior",
        tolerance: "1e-6 absolute",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical backend unary checkpoints",
        vjp_rule: "output_gradient/(1-input^2)",
        jvp_rule: "input_tangent/(1-input^2)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/atanh.json",
        evidence_fixture_sha256: "69ed08a096c70110972beb87016dd1381d645021e16b8a7e3dc077bdf4799261",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BB442559BFF4",
        baseline_overload_id: "COMFY-TENSOR-OP-BB442559BFF4:blocked",
        baseline_fixture_sha256: "e3501b821e66c83696ca1c0edc5ed0c02d8bfdcac520d75034790b6990372c54",
        overload_id: "zed.native.tensor.clip.canonical-clamp-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"minimum","kind":"positional_or_keyword","type":"Option<f32>","default":null,"keyword_only":false},{"name":"maximum","kind":"positional_or_keyword","type":"Option<f32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn clip_with_context_exact_native(backend: &CpuBackend, input: &Tensor, minimum: Option<f32>, maximum: Option<f32>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical clamp owner",
        shape_rule: "preserves shape",
        dtype_rule: "Task 60 F32 source profile",
        accumulation_dtype: "F32",
        layout_rule: "canonical clamp layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "inclusive optional lower and upper clamp bounds",
        tolerance: "exact for finite F32 inputs",
        determinism: "canonical clamp traversal",
        cancellation_points: "canonical clamp checkpoints",
        vjp_rule: "output gradient inside bounds and zero outside",
        jvp_rule: "input tangent inside bounds and zero outside",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/clip.json",
        evidence_fixture_sha256: "99ae9994479f9bc30b8aedff20e3ffe87b80ed6057b6bfd0b5ff4978dbceacfa",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BBE4FD70D20E",
        baseline_overload_id: "COMFY-TENSOR-OP-BBE4FD70D20E:blocked",
        baseline_fixture_sha256: "bf620bb73fe78e94cdb7977e0996e8aabf91b2080617f6d76a85bd9002790fae",
        overload_id: "zed.native.worker.cuda-ipc-collect.inventory-transaction.v1",
        ordered_parameters_json: r#"[{"name":"inventory","kind":"positional_or_keyword","type":"&mut MemoryPlacementInventory","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Cuda|Rocm>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeIpcCollection"]"#,
        rust_signature: "fn comfy_worker::cuda_ipc_collect_exact_native(inventory: &mut MemoryPlacementInventory, device: DeviceId, cancellation: &CancellationToken) -> Result<NativeIpcCollection, NativeMemoryStatsError>",
        mutation_rule: "atomically commits staged removal of reclaimable IPC exports",
        alias_rule: "returns owned accounting actions",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 bytes",
        layout_rule: "not applicable",
        device_rule: "exact configured CUDA or ROCm device",
        numeric_rule: "checked sum of dropped unprotected IpcExport resources",
        tolerance: "exact",
        determinism: "inventory order",
        cancellation_points: "before and during staging and before commit",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/cuda_ipc_collect.json",
        evidence_fixture_sha256: "bd0008e6553e4854fb833ed87b6d022469b555893427845a4a401587e9948982",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BF7BF3AA74D7",
        baseline_overload_id: "COMFY-TENSOR-OP-BF7BF3AA74D7:blocked",
        baseline_fixture_sha256: "be705b98d1773307b9fee02bc9cfb1fbc68603f1d471fa50054757023d582176",
        overload_id: "zed.native.worker.cuda-mem-get-info.topology-accounting.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"topology","kind":"positional_or_keyword","type":"&MemoryTopology","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"&MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["(u64,u64)"]"#,
        rust_signature: "fn comfy_worker::cuda_mem_get_info_exact_native(capabilities: &BackendCapabilityMatrix, topology: &MemoryTopology, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<(u64, u64), NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "copyable byte counts",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 bytes",
        layout_rule: "not applicable",
        device_rule: "exact CUDA or ROCm capability device in topology",
        numeric_rule: "free equals capacity minus canonical active bytes; total equals capacity",
        tolerance: "exact",
        determinism: "immutable topology and accounting snapshot",
        cancellation_points: "before and after projection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/cuda_mem_get_info.json",
        evidence_fixture_sha256: "f09d2a7704627d832819a7021bce98e8c985d9a7cf0c65c3cecd80cef57684e9",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BB1114038F65",
        baseline_overload_id: "COMFY-TENSOR-OP-BB1114038F65:blocked",
        baseline_fixture_sha256: "a3dedfff75f7a7fa070b7bbed5110834d8fc509c754eee18e770ab545eced8eb",
        overload_id: "zed.native.model.sdpa-kernel.immutable-policy.v1",
        ordered_parameters_json: r#"[{"name":"backends","kind":"positional_or_keyword","type":"&[SdpaBackend]","default":null,"keyword_only":false},{"name":"set_priority","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["SdpaKernelSelection"]"#,
        rust_signature: "fn comfy_model::sdpa_kernel_exact_native(backends: &[SdpaBackend], set_priority: bool, cancellation: &CancellationToken) -> Result<SdpaKernelSelection, AttentionError>",
        mutation_rule: "read only",
        alias_rule: "owned immutable ordered selection",
        shape_rule: "one through four unique backends",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "selection only; execution remains capability checked",
        numeric_rule: "preserves unique caller order and priority flag",
        tolerance: "exact",
        determinism: "input order",
        cancellation_points: "before and during validation",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/sdpa_kernel.json",
        evidence_fixture_sha256: "63cb425782924842ec0fd4d98281ceb545ee3a864a7716b41e0f810471123d13",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-B96B1B025618",
        baseline_overload_id: "COMFY-TENSOR-OP-B96B1B025618:blocked",
        baseline_fixture_sha256: "e2ebf35b4312813dbab427878d717dd194ab36a000b924d1837ea0a539e888b9",
        overload_id: "zed.native.model.spectral-norm.module-lifecycle.v1",
        ordered_parameters_json: r#"[{"name":"module","kind":"positional_or_keyword","type":"&mut NativeModule","default":null,"keyword_only":false},{"name":"name","kind":"positional_or_keyword","type":"&str","default":"weight","keyword_only":false},{"name":"power_iterations","kind":"positional_or_keyword","type":"usize","default":1,"keyword_only":false},{"name":"epsilon","kind":"positional_or_keyword","type":"f32","default":1e-12,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"Option<usize>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["&mut NativeModule"]"#,
        rust_signature: "fn comfy_model::spectral_norm_exact_native(module: &mut NativeModule, name: &str, power_iterations: usize, epsilon: f32, dimension: Option<usize>, cancellation: &CancellationToken) -> Result<&mut NativeModule, NativeOpsError>",
        mutation_rule: "atomically registers canonical NativeModule parametrization",
        alias_rule: "returns the same module borrow",
        shape_rule: "dimension must address the canonical weight shape",
        dtype_rule: "materialization preserves original parameter dtype",
        accumulation_dtype: "F64 sigma with F32 power vectors",
        layout_rule: "materialized canonical parameter layout",
        device_rule: "canonical module parameter device",
        numeric_rule: "deterministic power iteration and division by dominant singular value",
        tolerance: "1e-5 absolute for F32",
        determinism: "fixed row and column traversal",
        cancellation_points: "registration, materialization iterations, and publication boundaries",
        vjp_rule: "module construction boundary; downstream tensor autograd owns gradients",
        jvp_rule: "module construction boundary; downstream tensor autograd owns tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/spectral_norm.json",
        evidence_fixture_sha256: "0f86f496c3218371730be6ef3f298e3964af0d1667391db14d9651b75fe38677",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BD0C27F1B551",
        baseline_overload_id: "COMFY-TENSOR-OP-BD0C27F1B551:blocked",
        baseline_fixture_sha256: "cadb9e5d4d8bb8ef9756d772fab2617ff8844845d5fc5701828b0caac562aa6c",
        overload_id: "zed.native.tensor.roll.cpu-byte-preserving.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"shifts","kind":"positional_or_keyword","type":"&[i64]","default":null,"keyword_only":false},{"name":"dimensions","kind":"positional_or_keyword","type":"Option<&[i64]>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn roll_with_context_exact_native(backend: &CpuBackend, input: &Tensor, shifts: &[i64], dimensions: Option<&[i64]>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape; absent dimensions flatten logically",
        dtype_rule: "byte preserving for every canonical dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "contiguous output from logical input traversal",
        device_rule: "CPU ordinal zero",
        numeric_rule: "modular permutation with repeated dimensions accumulated",
        tolerance: "bit exact",
        determinism: "row-major output traversal",
        cancellation_points: "bounded element intervals and atomic upload",
        vjp_rule: "inverse roll of output gradient",
        jvp_rule: "forward roll of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/roll.json",
        evidence_fixture_sha256: "ff4d9d4b36238c17fcc7d30f58832a23c2aecd7a0a0277f4f2df8e80f1144a88",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BE1F415B5A74",
        baseline_overload_id: "COMFY-TENSOR-OP-BE1F415B5A74:blocked",
        baseline_fixture_sha256: "ee1a02d59746203acf237e351394ad438a58c4015e68cd7d654c3049dea98d35",
        overload_id: "zed.native.tensor.tensor-split.readonly-views.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"specification","kind":"positional_or_keyword","type":"Sections(u64)|Indices(Vec<i64>)","default":null,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"i64","default":0,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn tensor_split_exact_native(input: &Tensor, specification: &TensorSplitSpec, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "read only",
        alias_rule: "read-only views share canonical input storage",
        shape_rule: "balanced sections or clamped index slices along normalized dimension",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "F32 for cataloged VJP",
        layout_rule: "preserves input strides with adjusted shape and offset",
        device_rule: "CPU ordinal zero",
        numeric_rule: "no value transformation",
        tolerance: "bit exact",
        determinism: "declared split order",
        cancellation_points: "bounded output and gradient scatter intervals",
        vjp_rule: "scatter-add output gradients into input shape",
        jvp_rule: "identical read-only split of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/tensor_split.json",
        evidence_fixture_sha256: "c1667f19d71b0716f3c3f85a8a9921790686f83fccb5a9a4fe87d2beffeaa830",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BF0B50BCC3B4",
        baseline_overload_id: "COMFY-TENSOR-OP-BF0B50BCC3B4:blocked",
        baseline_fixture_sha256: "8b722ed5e7101bc02ba5ea71c71bd014258fcd2153faeb54a318d1122002b07e",
        overload_id: "zed.native.worker.xpu-is-available.topology.v1",
        ordered_parameters_json: r#"[{"name":"topology","kind":"positional_or_keyword","type":"&MemoryTopology","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn comfy_worker::xpu_is_available_exact_native(topology: &MemoryTopology, cancellation: &CancellationToken) -> Result<bool, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "copyable bool",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u32 device count",
        layout_rule: "not applicable",
        device_rule: "counts exact XPU device-kind entries",
        numeric_rule: "true exactly when canonical topology has at least one XPU",
        tolerance: "exact",
        determinism: "immutable topology traversal",
        cancellation_points: "before and after canonical count",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/xpu_is_available.json",
        evidence_fixture_sha256: "5f6aceccd57481713964f4138833a875bb65e874e7f21f1efa2dd6cb538912f1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-B91A910A5AF9",
        baseline_overload_id: "COMFY-TENSOR-OP-B91A910A5AF9:blocked",
        baseline_fixture_sha256: "28fbf04e8dc963d2a8bc0f8f0e8981a9f79df632d9a3ed682abca62b4799a2ba",
        overload_id: "zed.native.tensor.xpu-synchronize.event-fence.v1",
        ordered_parameters_json: r#"[{"name":"backend","kind":"positional_or_keyword","type":"&dyn TensorBackend","default":null,"keyword_only":false},{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"execution","kind":"positional_or_keyword","type":"&ExecutionContext","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["()"]"#,
        rust_signature: "fn xpu_synchronize_exact_native(backend: &dyn TensorBackend, capabilities: &BackendCapabilityMatrix, execution: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "records and waits through the canonical backend event owner",
        alias_rule: "not applicable",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "backend and capability matrix must name the same XPU device",
        numeric_rule: "completion follows one canonical stream event fence",
        tolerance: "exact",
        determinism: "stream-ordered event sequence",
        cancellation_points: "before record and after wait through ExecutionContext",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/xpu_synchronize.json",
        evidence_fixture_sha256: "35178b497015313abb8525e36bc5927613d125d2f66f79238eca8ff58a0c57b0",
    },
]
