&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-365E27719CFD",
        baseline_overload_id: "COMFY-TENSOR-OP-365E27719CFD:blocked",
        baseline_fixture_sha256: "0f096106f5bafda847a47370f78bb2d3b04b3199b107f52c8d33a19e8e6d2164",
        overload_id: "zed.native.tensor.div-method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"f32 Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"f32 Tensor or Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn div_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "canonical right-aligned broadcasting",
        dtype_rule: "certified CPU profile accepts f32 and checked f32 scalars",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero with exact stream agreement",
        numeric_rule: "IEEE division including signed zero, infinity, and NaN",
        tolerance: "exact f32 primitive result",
        determinism: "canonical broadcast traversal",
        cancellation_points: "before validation, during primitive traversal, and before publication",
        vjp_rule: "input gradient is grad divided by other; tensor-other gradient is negative grad times input divided by other squared with broadcast reduction",
        jvp_rule: "the same checked quotient differential",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/div.json",
        evidence_fixture_sha256: "eeb978d176d19ef7429ee8c412c24cf513d2270a0435b831a9e9e4d243f1647f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-3D0519DB53BD",
        baseline_overload_id: "COMFY-TENSOR-OP-3D0519DB53BD:blocked",
        baseline_fixture_sha256: "b4e540f27a5e4dc453c70fd366bc4b3d7256f9c141993b1373be296e731051e5",
        overload_id: "zed.native.tensor.item.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"single-element Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"DecodedScalar\"]",
        rust_signature: "fn item_with_context_exact_native(input: &Tensor, context: &ExecutionContext<'_>) -> Result<DecodedScalar, ElementwiseRuntimePartFiveError>",
        mutation_rule: "read only",
        alias_rule: "returns a copyable decoded scalar",
        shape_rule: "requires exactly one logical element at any rank",
        dtype_rule: "canonical DType codec owns scalar decoding",
        accumulation_dtype: "none",
        layout_rule: "logical element access supports canonical views",
        device_rule: "host-readable CPU ordinal zero",
        numeric_rule: "preserves boolean, signed, unsigned, real, and complex scalar classes",
        tolerance: "exact codec result",
        determinism: "single logical read",
        cancellation_points: "before validation and after decoding",
        vjp_rule: "scalar extraction is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/item.json",
        evidence_fixture_sha256: "6e7bacf35ec5fc2c72def2db5466b037809b8308fd4a6e1aafe27210cc71f0b0",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-332E7E59DC10",
        baseline_overload_id: "COMFY-TENSOR-OP-332E7E59DC10:blocked",
        baseline_fixture_sha256: "51dcf894bddd430d103d38ad89e68a02ab6effbac0df0d465035a29e68afe7e7",
        overload_id: "zed.native.tensor.sin-method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"f32 Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn sin_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "certified CPU profile accepts f32",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical native sine primitive",
        tolerance: "platform f32 transcendental tolerance",
        determinism: "fixed logical traversal",
        cancellation_points: "canonical unary primitive checkpoints",
        vjp_rule: "output gradient multiplied by cosine of input",
        jvp_rule: "input tangent multiplied by cosine of input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/sin.json",
        evidence_fixture_sha256: "9b7d5abf480556e8c652708f207100db5650e391879412646655695d880dbf4b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-3D09997B7D21",
        baseline_overload_id: "COMFY-TENSOR-OP-3D09997B7D21:blocked",
        baseline_fixture_sha256: "94e647f7a31d6f3ddd0d6597ee92f4999d7b021dbf0e6a9c6ecb611f9b86a72d",
        overload_id: "zed.native.tensor.sqrt-method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"f32 Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn sqrt_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "certified CPU profile accepts f32",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE square root with negative inputs producing NaN",
        tolerance: "platform f32 transcendental tolerance",
        determinism: "fixed logical traversal",
        cancellation_points: "canonical unary primitive checkpoints",
        vjp_rule: "output gradient divided by two times square root of input",
        jvp_rule: "input tangent divided by two times square root of input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/sqrt.json",
        evidence_fixture_sha256: "1d62dafc520deee4e7313eda2a67c2de2bf92783cc07c947891fcb0dd27ec16d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-33CCFBAAA7B3",
        baseline_overload_id: "COMFY-TENSOR-OP-33CCFBAAA7B3:blocked",
        baseline_fixture_sha256: "bb4eff9580a1337a4307ef34187365cc5cf2b8c913c22e72626e3160a6bc2d56",
        overload_id: "zed.native.tensor.zero-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"unit\"]",
        rust_signature: "fn zero_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartFiveError>",
        mutation_rule: "stages a complete canonical fill before one receiver publication",
        alias_rule: "preserves the receiver through canonical copy-on-write mutation",
        shape_rule: "shape unchanged including zero-sized tensors",
        dtype_rule: "zero is checked by the canonical DType codec",
        accumulation_dtype: "none",
        layout_rule: "descriptor and logical layout preserved",
        device_rule: "CPU ordinal zero",
        numeric_rule: "every logical value becomes exact encoded zero",
        tolerance: "exact bytes",
        determinism: "canonical fill traversal",
        cancellation_points: "before validation, during staged fill, and before publication",
        vjp_rule: "terminal mutation has no VJP",
        jvp_rule: "terminal mutation does not propagate tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/zero_in_place.json",
        evidence_fixture_sha256: "389a440ed89fc740f98ec053ea26abb96616d8c8ffa0bb4ab19f70bb0330366c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-384A8C6954B8",
        baseline_overload_id: "COMFY-TENSOR-OP-384A8C6954B8:blocked",
        baseline_fixture_sha256: "c2e9470d5999d7bb65c65cea888c8584a6630d6404fde73ecc2edbcdc4905f7a",
        overload_id: "zed.native.tensor.bitwise-left-shift.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"integer Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"integer Tensor or u32 Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<integer>\"]",
        rust_signature: "fn bitwise_left_shift_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: BitwiseShiftOperand<'_>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "canonical right-aligned broadcasting",
        dtype_rule: "input integer dtype is preserved; shift operands must be integers",
        accumulation_dtype: "u128 bit pattern bounded to the input width",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "two's-complement fixed-width shift; negative or out-of-width shifts fail typed",
        tolerance: "exact bits",
        determinism: "fixed broadcast traversal",
        cancellation_points: "before validation, at bounded traversal intervals, and before upload publication",
        vjp_rule: "integer operation is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/bitwise_left_shift.json",
        evidence_fixture_sha256: "aabbb82bfc3fbdbaeaa71f26b815b50e64a0ec0393579ce7c573038aa539ca1d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-3ADC7A3998E4",
        baseline_overload_id: "COMFY-TENSOR-OP-3ADC7A3998E4:blocked",
        baseline_fixture_sha256: "a4a9fcf50daa2b09b51f7c2afef77f8483d52406e6c2b697778a0193ea088866",
        overload_id: "zed.native.tensor.count-nonzero.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<i64>\"]",
        rust_signature: "fn count_nonzero_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "read only with a fresh scalar output",
        alias_rule: "output owns canonical scalar storage",
        shape_rule: "returns a rank-zero tensor",
        dtype_rule: "all canonical decoded scalar classes are accepted; output is i64",
        accumulation_dtype: "checked u64 converted to i64",
        layout_rule: "logical input traversal and contiguous scalar output",
        device_rule: "host-readable CPU ordinal zero",
        numeric_rule: "NaN is nonzero; complex is nonzero when either component differs from zero",
        tolerance: "exact count",
        determinism: "fixed logical traversal",
        cancellation_points: "before validation, at bounded traversal intervals, and during scalar publication",
        vjp_rule: "counting predicate is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/count_nonzero.json",
        evidence_fixture_sha256: "fd4e34cab4fb14107685cb8d52f26943704b233501f4e90a41e630ee390aa9a3",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-40FEFA2DEAC6",
        baseline_overload_id: "COMFY-TENSOR-OP-40FEFA2DEAC6:blocked",
        baseline_fixture_sha256: "26febf3e81e781375f30848b8226ee227f5e16d0f1c8468e6f910b9c29de9b0c",
        overload_id: "zed.native.allocator.cuda-backend-name.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"owner\",\"type\":\"CachedAllocationOwner\"}]",
        output_arity: "1",
        output_types_json: "[\"static string\"]",
        rust_signature: "fn cuda_get_allocator_backend_exact_native(owner: &dyn CachedAllocationOwner, cancellation: &CancellationToken) -> Result<&'static str, ElementwiseRuntimePartFiveError>",
        mutation_rule: "read-only owner projection",
        alias_rule: "returns the authoritative static backend identifier",
        shape_rule: "not applicable",
        dtype_rule: "UTF-8 identifier bounded to 128 non-NUL bytes",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "CUDA or ROCm allocator owners only",
        numeric_rule: "not applicable",
        tolerance: "exact string",
        determinism: "fixed owner projection",
        cancellation_points: "before owner validation and after projection",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/cuda_get_allocator_backend.json",
        evidence_fixture_sha256: "cbadb060b32504020c47d4239092ec03cc5cc1ac089615e60913029a1e8be448",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-3A3C79159CBC",
        baseline_overload_id: "COMFY-TENSOR-OP-3A3C79159CBC:blocked",
        baseline_fixture_sha256: "bac3356539749253b91293090f5638061655258026180fd29b8b20b5ba95e50b",
        overload_id: "zed.native.device.cuda-select-capabilities.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"available\",\"type\":\"BackendCapabilityMatrix slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"DeviceId\"}]",
        output_arity: "1",
        output_types_json: "[\"borrowed BackendCapabilityMatrix\"]",
        rust_signature: "fn cuda_set_device_exact_native<'a>(available: &'a [BackendCapabilityMatrix], device: DeviceId, cancellation: &CancellationToken) -> Result<&'a BackendCapabilityMatrix, ElementwiseRuntimePartFiveError>",
        mutation_rule: "functional selection with no process-global mutable state",
        alias_rule: "borrows the exact canonical capability matrix",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "exact configured CUDA or ROCm DeviceId must exist",
        numeric_rule: "ordinal comparison is exact",
        tolerance: "exact identity",
        determinism: "first and only canonical matrix match",
        cancellation_points: "before lookup and after selection",
        vjp_rule: "device selection is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/cuda_set_device.json",
        evidence_fixture_sha256: "afa8f5f7123f3a2b118b66e2deb3fb53d8cd10facb9d634ae47d67f1cbae93c1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-388D285AB0F7",
        baseline_overload_id: "COMFY-TENSOR-OP-388D285AB0F7:blocked",
        baseline_fixture_sha256: "b9aebcbe7f236dc918296562ee01e7aa3d1c0859a800c92695504f60693d5287",
        overload_id: "zed.native.tensor.minimum.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"f32 Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"f32 Tensor or Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn minimum_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "canonical right-aligned broadcasting",
        dtype_rule: "certified CPU profile accepts f32 and checked f32 scalars",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero with exact stream agreement",
        numeric_rule: "smaller value wins and either NaN propagates",
        tolerance: "exact f32 comparisons",
        determinism: "fixed broadcast traversal",
        cancellation_points: "before validation, during primitive traversal, and before publication",
        vjp_rule: "gradient routes to the smaller operand and splits equally at ties with broadcast reduction",
        jvp_rule: "tangent routes by the same smaller-or-tie mask",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/minimum.json",
        evidence_fixture_sha256: "405dcc65bcc1f3f7beeb3ea5e372368b1fbd358417f1e7c63fe8600088be7efb",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-37266D0A196F",
        baseline_overload_id: "COMFY-TENSOR-OP-37266D0A196F:blocked",
        baseline_fixture_sha256: "5bd26bec6dfd861b39f898635319e2206672bc35cceeb6f8a19dd40ac130a122",
        overload_id: "zed.native.tensor.constant-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"value\",\"type\":\"Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"unit\"]",
        rust_signature: "fn constant_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, value: Scalar, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartFiveError>",
        mutation_rule: "stages a complete canonical fill before one receiver publication",
        alias_rule: "preserves the receiver through canonical copy-on-write mutation",
        shape_rule: "shape unchanged including zero-sized tensors",
        dtype_rule: "value is checked by the canonical DType codec",
        accumulation_dtype: "none",
        layout_rule: "descriptor and logical layout preserved",
        device_rule: "CPU ordinal zero",
        numeric_rule: "every logical value becomes the exact encoded constant",
        tolerance: "exact canonical encoding",
        determinism: "canonical fill traversal",
        cancellation_points: "before validation, during staged fill, and before publication",
        vjp_rule: "initializer mutation has no VJP",
        jvp_rule: "initializer does not propagate tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/constant_in_place.json",
        evidence_fixture_sha256: "91fdec77a04c58dd620613b0903968101a136ef36970b7b22333415f2a4a6135",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-3A641CA3FC0F",
        baseline_overload_id: "COMFY-TENSOR-OP-3A641CA3FC0F:blocked",
        baseline_fixture_sha256: "8b96e03edc68913df675c98bbee31ffc6200d635181d102a6d25d99da8488e4d",
        overload_id: "zed.native.device.xpu-name.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"capabilities\",\"type\":\"BackendCapabilityMatrix\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"DeviceId\"}]",
        output_arity: "1",
        output_types_json: "[\"String\"]",
        rust_signature: "fn xpu_get_device_name_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<String, ElementwiseRuntimePartFiveError>",
        mutation_rule: "read-only canonical property projection",
        alias_rule: "returns an owned boundary string",
        shape_rule: "not applicable",
        dtype_rule: "validated UTF-8 device property",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "exact XPU DeviceId and capability matrix agreement",
        numeric_rule: "not applicable",
        tolerance: "exact string",
        determinism: "fixed property projection",
        cancellation_points: "before validation and after copying the name",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/xpu_get_device_name.json",
        evidence_fixture_sha256: "81558d055e927b749ffe8639c16d4ce2676e2278c6ad1e697f9f27e02913a1ef",
    },
]
