&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-28BA5C917CFB",
        baseline_overload_id: "COMFY-TENSOR-OP-28BA5C917CFB:blocked",
        baseline_fixture_sha256: "b2216195c020707aa7e1946f3103bdf3a449d9b62dcf514e24e9c0ecc80040f1",
        overload_id: "zed.native.worker.cuda-device-count.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"topology\",\"type\":\"MemoryTopology\"}]",
        output_arity: "1",
        output_types_json: "[\"u32\"]",
        rust_signature: "fn cuda_device_count_exact_native(topology: &MemoryTopology, cancellation: &CancellationToken) -> Result<u32, NativeMemoryStatsError>",
        mutation_rule: "read-only projection",
        alias_rule: "returns a copyable count",
        shape_rule: "not applicable",
        dtype_rule: "checked u32 count",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "counts canonical CUDA and ROCm topology entries exposed through the source CUDA namespace",
        numeric_rule: "exact configured-device count without probing",
        tolerance: "exact",
        determinism: "fixed topology traversal",
        cancellation_points: "before and after canonical inventory traversal",
        vjp_rule: "non-differentiable device metadata",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/cuda_device_count.json",
        evidence_fixture_sha256: "b318e702a42768c813fbebedd4d5e9e11fb73778c0f02d6c33145560f7fe1eec",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-310F887878BC",
        baseline_overload_id: "COMFY-TENSOR-OP-310F887878BC:blocked",
        baseline_fixture_sha256: "c71df51c35977e3b1be8fb4ef4b1d8819ce676f355a25537797e0e38997e72af",
        overload_id: "zed.native.worker.cuda-is-available.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"topology\",\"type\":\"MemoryTopology\"}]",
        output_arity: "1",
        output_types_json: "[\"bool\"]",
        rust_signature: "fn cuda_is_available_exact_native(topology: &MemoryTopology, cancellation: &CancellationToken) -> Result<bool, NativeMemoryStatsError>",
        mutation_rule: "read-only projection",
        alias_rule: "returns a copyable boolean",
        shape_rule: "not applicable",
        dtype_rule: "boolean",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "true only when canonical topology contains CUDA or ROCm",
        numeric_rule: "device count greater than zero",
        tolerance: "exact",
        determinism: "canonical device-count projection",
        cancellation_points: "canonical device-count cancellation points",
        vjp_rule: "non-differentiable device metadata",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/cuda_is_available.json",
        evidence_fixture_sha256: "029f7bc341387432c1b9f6cae158ff432b836cfce89c005ffcfcf2eac8500432",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-2ED7F479B4BD",
        baseline_overload_id: "COMFY-TENSOR-OP-2ED7F479B4BD:blocked",
        baseline_fixture_sha256: "284dcab2e452af70f1e8295aa252b5d9ca797fecf3152e5a442354490686bb07",
        overload_id: "zed.native.tensor.deg2rad.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"floating or complex Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn deg2rad_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "floating or complex dtype preserved",
        accumulation_dtype: "f64 scalar transform before canonical encoding",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "each component multiplied by pi divided by 180",
        tolerance: "dtype-specific transcendental encoding tolerance",
        determinism: "fixed logical traversal",
        cancellation_points: "before validation, bounded intervals, upload, and publication",
        vjp_rule: "output gradient multiplied by pi divided by 180",
        jvp_rule: "input tangent multiplied by pi divided by 180",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/deg2rad.json",
        evidence_fixture_sha256: "85193b07aca4cd35ad16b3af5e4c706647e4e3d72b002bc0f0d8405794f97e1b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-2C340B4A7331",
        baseline_overload_id: "COMFY-TENSOR-OP-2C340B4A7331:blocked",
        baseline_fixture_sha256: "228f29bb9c6c140eee37d4f207e7676811cd785fb15d07a88711abf34d037646",
        overload_id: "zed.native.autograd.grad-scaler.v1",
        ordered_parameters_json: "[{\"default\":\"GradScalerConfig::default()\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"config\",\"type\":\"GradScalerConfig\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeGradScaler\"]",
        rust_signature: "fn grad_scaler_exact_native(config: GradScalerConfig, cancellation: &CancellationToken) -> Result<NativeGradScaler, ElementwiseRuntimePartFourError>",
        mutation_rule: "constructor returns canonical scaler state; scale and unscale stage tensors before publication",
        alias_rule: "disabled scaling preserves canonical tensor storage; enabled scaling returns copy-on-write values",
        shape_rule: "gradient shapes are unchanged",
        dtype_rule: "floating tensors only",
        accumulation_dtype: "f64 scale state with canonical tensor codecs",
        layout_rule: "canonical Tensor logical indexing",
        device_rule: "CPU ordinal zero until certified device adapters consume this owner",
        numeric_rule: "source defaults, reciprocal unscale, non-finite step skip, growth and backoff state machine",
        tolerance: "exact state transitions and dtype encoding tolerance",
        determinism: "fixed optimizer-stage and tensor traversal order",
        cancellation_points: "before every transition, bounded tensor intervals, and before publication",
        vjp_rule: "scaled loss enters the canonical autograd tape; unscale is an optimizer-boundary state transition",
        jvp_rule: "scale multiplies tangents by the same scale",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/grad_scaler.json",
        evidence_fixture_sha256: "fe911f5d4c5528f86e8bcc960b828afeae4be9427d0f65d58881355f8a2d789e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-2C5A78E85B7F",
        baseline_overload_id: "COMFY-TENSOR-OP-2C5A78E85B7F:blocked",
        baseline_fixture_sha256: "e507119cb96e24456923fb5c1b1a90342e78b730b69103114e2a1173d4d5a264",
        overload_id: "zed.native.tensor.isfinite.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn isfinite_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourError>",
        mutation_rule: "out of place",
        alias_rule: "fresh bool storage",
        shape_rule: "shape unchanged",
        dtype_rule: "all canonical dtypes accepted; output bool",
        accumulation_dtype: "none",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "real finite; complex requires both finite; integer and boolean always true",
        tolerance: "exact",
        determinism: "fixed logical traversal",
        cancellation_points: "before validation, bounded intervals, upload, and publication",
        vjp_rule: "predicate is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/isfinite.json",
        evidence_fixture_sha256: "7d27520964d4a5e8f8466fa1f1cbd8223d6bf68667477802efb38bcc9dae3f06",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-3118FDEB2829",
        baseline_overload_id: "COMFY-TENSOR-OP-3118FDEB2829:blocked",
        baseline_fixture_sha256: "759f72fa7da75b1dfc2bef6d55845601c60af7506d06304e6bd54b7647744f6d",
        overload_id: "zed.native.tensor.kaiming-uniform-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"floating Tensor\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"rng\",\"type\":\"RngTransaction\"},{\"default\":\"0\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"a\",\"type\":\"f64\"},{\"default\":\"fan_in\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"mode\",\"type\":\"KaimingMode\"},{\"default\":\"leaky_relu\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"nonlinearity\",\"type\":\"KaimingNonlinearity\"}]",
        output_arity: "1",
        output_types_json: "[\"RngCheckpoint\"]",
        rust_signature: "fn kaiming_uniform_in_place_exact_native(input: &mut Tensor, rng: RngTransaction, negative_slope: f64, mode: KaimingMode, nonlinearity: KaimingNonlinearity, cancellation: &CancellationToken) -> Result<RngCheckpoint, ElementwiseRuntimePartFourError>",
        mutation_rule: "tensor and RNG state stage completely before one tensor publication and checkpoint return",
        alias_rule: "preserves receiver handle through canonical copy-on-write",
        shape_rule: "rank at least two; zero-element tensors are no-ops; otherwise fan derives from checked shape product",
        dtype_rule: "floating dtype preserved",
        accumulation_dtype: "f64 fan, gain, bound, and uniform mapping",
        layout_rule: "logical values publish through TensorWrite",
        device_rule: "CPU ordinal zero and canonical RNG stream device identity",
        numeric_rule: "zero-element tensors consume no RNG words; otherwise uniform values lie in plus-or-minus sqrt(3) times gain over sqrt(fan) with source gain rules",
        tolerance: "exact RNG words and dtype encoding tolerance",
        determinism: "canonical MT19937 or Philox transaction order",
        cancellation_points: "before validation, per RNG sample interval, before checkpoint, and before tensor publication",
        vjp_rule: "initializer is a terminal parameter mutation with no VJP",
        jvp_rule: "initializer does not propagate tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/kaiming_uniform.json",
        evidence_fixture_sha256: "b3248566913576975a58d5fb64f76865d4912e73846c9563c704eea507a9444e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-2E9C9B320055",
        baseline_overload_id: "COMFY-TENSOR-OP-2E9C9B320055:blocked",
        baseline_fixture_sha256: "ecd322295c45f248e652eafc1d4ef721e75aeefc22124c98ec0266261b3e0880",
        overload_id: "zed.native.worker.mps-empty-cache.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"backend\",\"type\":\"CachedAllocationOwner\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"inventory\",\"type\":\"MemoryPlacementInventory\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"DeviceId\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeCacheRelease\"]",
        rust_signature: "fn mps_empty_cache_exact_native(backend: &dyn CachedAllocationOwner, inventory: &mut MemoryPlacementInventory, device: DeviceId, cancellation: &CancellationToken) -> Result<NativeCacheRelease, NativeMemoryStatsError>",
        mutation_rule: "stages unfenced cache metadata, releases the canonical backend cache, then publishes accounting exactly once",
        alias_rule: "backend owns real allocator release; authoritative inventory publishes only after backend success",
        shape_rule: "not applicable",
        dtype_rule: "byte accounting uses checked u64 values",
        accumulation_dtype: "u64 accounting",
        layout_rule: "not applicable",
        device_rule: "checked Metal device only",
        numeric_rule: "reports real backend bytes plus exact dropped accounting resources and bytes",
        tolerance: "exact",
        determinism: "canonical inventory order",
        cancellation_points: "before selection, per resource, and before irreversible backend release; allocator success fences cancellation so accounting must publish",
        vjp_rule: "non-differentiable memory transition",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/mps_empty_cache.json",
        evidence_fixture_sha256: "7174b8c0c3aa690d5cd9a381050dea78e2cc61fc1983a2a6442be5953fabb719",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-290B200830F8",
        baseline_overload_id: "COMFY-TENSOR-OP-290B200830F8:blocked",
        baseline_fixture_sha256: "ef75983f53158aa603f04a5f19fa9b036af49dd1bba43dd848af315885d3d94f",
        overload_id: "zed.native.tensor.nan-to-num.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":\"0.0\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"nan\",\"type\":\"Option<f64>\"},{\"default\":\"None\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"posinf\",\"type\":\"Option<f64>\"},{\"default\":\"None\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"neginf\",\"type\":\"Option<f64>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn nan_to_num_with_context_exact_native(backend: &CpuBackend, input: &Tensor, nan: Option<f64>, positive_infinity: Option<f64>, negative_infinity: Option<f64>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "dtype preserved; integer and boolean values copied",
        accumulation_dtype: "f64 replacement selection before canonical encoding",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "NaN defaults to zero and infinities default to finite dtype extrema; explicit replacements override each real or complex component independently",
        tolerance: "exact canonical encoding",
        determinism: "fixed logical traversal",
        cancellation_points: "before validation, bounded intervals, upload, and publication",
        vjp_rule: "gradient passes at finite scalar components and is zero independently for each replaced real or complex component",
        jvp_rule: "tangent passes at finite scalar components and is zero independently for each replaced real or complex component",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/nan_to_num.json",
        evidence_fixture_sha256: "9e4e11f795d6b48a0af6e08a4f173e9b5572195fa67a07f7d763bc6a6af7e6f9",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-2881ABE3D797",
        baseline_overload_id: "COMFY-TENSOR-OP-2881ABE3D797:blocked",
        baseline_fixture_sha256: "449d07486f67c3eb81a6c93340122dc2a82d1bccb5f8d4c61212b6b4452cd3b5",
        overload_id: "zed.native.runtime.compile-policy.v2",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"model\",\"type\":\"Model\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"policy\",\"type\":\"NativeCompilePolicy\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"capabilities\",\"type\":\"Option<&BackendCapabilityMatrix>\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeCompiledModel<Model>\"]",
        rust_signature: "fn compile_exact_native<Model>(model: Model, policy: NativeCompilePolicy, capabilities: Option<&BackendCapabilityMatrix>, cancellation: &CancellationToken) -> Result<NativeCompiledModel<Model>, NativeCompileError>",
        mutation_rule: "wraps the native model without mutating it",
        alias_rule: "owns the supplied model and exposes invocation only through the checked wrapper",
        shape_rule: "not applicable",
        dtype_rule: "execution dtype remains owned by the native runtime backend",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "native graph policy needs no device claim; CUDA-graphs requires a certified CUDA or ROCm capability matrix with native device properties; unsupported or uncertified backends fail typed",
        numeric_rule: "does not alter model arithmetic; the observed skip_torch_compile_dict source guard maps to a typed native guard policy and options outside that observed mapping fail typed",
        tolerance: "exact policy and cache identity",
        determinism: "canonical serialized version-two policy SHA-256 cache token",
        cancellation_points: "before policy sealing, capability certification, invocation, and invocation return",
        vjp_rule: "model autograd semantics are unchanged",
        jvp_rule: "model tangent semantics are unchanged",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/native_compile.json",
        evidence_fixture_sha256: "5004b367351b4e48bf5ec525c0503f85d5463900f4d1cf023502bdc82b8e271f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-289B94EF73DE",
        baseline_overload_id: "COMFY-TENSOR-OP-289B94EF73DE:blocked",
        baseline_fixture_sha256: "f05bb4a9f1bccfe19820b8c78e4191cfb76803aa4ff8be0c0816ea73eb417265",
        overload_id: "zed.native.tensor.relu.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"floating Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn relu_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "floating dtype preserved",
        accumulation_dtype: "canonical f32 activation profile",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "delegates forward scalar mechanics and gradient mask to the canonical functional ReLU owner",
        tolerance: "canonical activation tolerance",
        determinism: "canonical functional traversal",
        cancellation_points: "canonical functional cancellation points plus tensor projection",
        vjp_rule: "output gradient where input is greater than zero, else zero",
        jvp_rule: "input tangent where input is greater than zero, else zero",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/relu.json",
        evidence_fixture_sha256: "2d60f1917ecd4d73caa1cc5de8785a9673c922a93e8c58f2c9dfc697cee6d608",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-2D7E75B69A4E",
        baseline_overload_id: "COMFY-TENSOR-OP-2D7E75B69A4E:blocked",
        baseline_fixture_sha256: "060a5ee91dab520163fe11e6f63cd2ef33922f882d55d83160c393dac0c5e7cf",
        overload_id: "zed.native.model.remove-parametrizations.weight.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"module\",\"type\":\"NativeModule\"},{\"default\":\"weight\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"name\",\"type\":\"str\"},{\"default\":\"true\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"leave_parametrized\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"()\"]",
        rust_signature: "fn remove_parametrizations_with_context_exact_native(backend: &CpuBackend, module: &mut NativeModule, name: &str, leave_parametrized: bool, context: &ExecutionContext<'_>) -> Result<(), NativeOpsError>",
        mutation_rule: "materializes weight norm completely before one NativeModule generation transition",
        alias_rule: "module retains the current materialized weight and drops parametrization state",
        shape_rule: "materialized weight shape equals direction shape",
        dtype_rule: "weight dtype and device preserved",
        accumulation_dtype: "f64 norm reduction over canonical f32 tensor projection",
        layout_rule: "canonical module weight tensor",
        device_rule: "CPU ordinal zero until certified module adapters consume the owner",
        numeric_rule: "weight equals magnitude times direction divided by norm over every axis except dim",
        tolerance: "canonical normalization tolerance",
        determinism: "fixed reduction and module transition order",
        cancellation_points: "before materialization, bounded reduction intervals, and before module publication",
        vjp_rule: "removal is a terminal module-structure transition; the materialized parameter remains autograd-reachable",
        jvp_rule: "same materialized forward value",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/remove_parametrizations.json",
        evidence_fixture_sha256: "90a2784f7e9cc38e544a04a1b29397aa7afc0f5b74a89447d87396445027840a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_04",
        operation_id: "COMFY-TENSOR-OP-30F43E74E34C",
        baseline_overload_id: "COMFY-TENSOR-OP-30F43E74E34C:blocked",
        baseline_fixture_sha256: "219b0bcc5ba0fd12d32f155e10acc8755e0bedbf487c3c117890ac4a6614e9b6",
        overload_id: "zed.native.tensor.eq-method-scalar.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn tensor_eq_scalar_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: Scalar, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical scalar-equality owner and returns fresh bool storage",
        shape_rule: "shape unchanged",
        dtype_rule: "scalar is checked through the receiver DType codec; output is bool",
        accumulation_dtype: "none",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "exact equality including IEEE NaN inequality",
        tolerance: "exact",
        determinism: "canonical equality traversal",
        cancellation_points: "canonical equality cancellation points",
        vjp_rule: "comparison is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-2881abe3d797",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_04/tensor_eq_scalar.json",
        evidence_fixture_sha256: "72e5c0bd4ae15294af2de4f1c4b8c493afb312deb729c184cc1bd0bd7b8bcd9c",
    },
]
