&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5DFBC70338A1",
        baseline_overload_id: "COMFY-TENSOR-OP-5DFBC70338A1:blocked",
        baseline_fixture_sha256: "d93d2a7c56ab33eb927e58bfb523f6fe05a96a53bb2abcb242723e7a46840b91",
        overload_id: "sim.native.tensor.byte.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<real or integer>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<U8>"]"#,
        rust_signature: "fn byte_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical U8 storage",
        shape_rule: "preserves shape",
        dtype_rule: "real, integer, and boolean inputs convert to U8; complex inputs fail",
        accumulation_dtype: "U8",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "integers and truncated real values wrap modulo 256",
        tolerance: "exact bytes",
        determinism: "row-major scalar decoding",
        cancellation_points: "before dispatch, bounded conversion intervals, and before publication",
        vjp_rule: "non-differentiable cast",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/byte_method.json",
        evidence_fixture_sha256: "da6b27709a2d6354e8b0a0de650318b87f0e8f9d833320cacc5ae1c8aa581768",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5ED49DCA2F78",
        baseline_overload_id: "COMFY-TENSOR-OP-5ED49DCA2F78:blocked",
        baseline_fixture_sha256: "a7462e7c7d6d49bbc5aab7fc70155471ada36370f8896a0605f90e7a638fb86f",
        overload_id: "sim.native.tensor.log.method.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn log_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to canonical natural-logarithm owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE natural logarithm including zero, infinity, and domain NaN",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical unary checkpoints",
        vjp_rule: "upstream divided by input",
        jvp_rule: "input tangent divided by input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/log_method.json",
        evidence_fixture_sha256: "de3775d18b112d6ce79cbb13ba8727637c9a75fbb271602bd5c5918b8a8ce934",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5CEC7CF2D62D",
        baseline_overload_id: "COMFY-TENSOR-OP-5CEC7CF2D62D:blocked",
        baseline_fixture_sha256: "5102da88723dd12318b305efc8dfece18be313c19ff76cac554fedd71661bbc6",
        overload_id: "sim.native.autograd.grad.reverse-tape.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"tape","type":"mutable AutogradTape"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"seeds","type":"Vec<(OutputSlot, Tensor)>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"inputs","type":"slice<LeafId>"},{"default":false,"keyword_only":true,"kind":"keyword_only","name":"allow_unused","type":"bool"}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Option<Tensor>>"]"#,
        rust_signature: "fn autograd_grad_exact_native(tape: &mut AutogradTape, seeds: Vec<(OutputSlot, Tensor)>, inputs: &[LeafId], reducer: &dyn GradientReducer, allow_unused: bool, cancellation: &CancellationToken) -> Result<Vec<Option<Tensor>>, ElementwiseRuntimePartEightError>",
        mutation_rule: "consumes the canonical tape through its terminal backward transition",
        alias_rule: "gradient tensors are owned by AutogradTape and returned in requested leaf order",
        shape_rule: "seed and VJP shapes are validated by the canonical tape",
        dtype_rule: "canonical tape and reducer descriptor rules",
        accumulation_dtype: "canonical GradientReducer",
        layout_rule: "preserves canonical gradient descriptors",
        device_rule: "delegates device validation to tape VJPs and reducer",
        numeric_rule: "reverse traversal and accumulation are owned by AutogradTape",
        tolerance: "exact canonical tape result",
        determinism: "reverse node order and requested leaf order",
        cancellation_points: "canonical tape checkpoints and ordered result projection",
        vjp_rule: "this is the reverse-mode execution boundary",
        jvp_rule: "not applicable to the reverse-mode boundary",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/autograd_grad.json",
        evidence_fixture_sha256: "7a1eb2bd024aa1922b8e78f7fe541894791d3a4b943c0f1e7aa10406c1b28ee8",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5BF1DE9DA499",
        baseline_overload_id: "COMFY-TENSOR-OP-5BF1DE9DA499:blocked",
        baseline_fixture_sha256: "57ecf452e80aeddadbef8326f202eb453b3bf35d9eeba01d7983ffaf2cf9036a",
        overload_id: "sim.native.device.mps.is-available.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"capabilities","type":"slice<BackendCapabilityMatrix>"}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn mps_is_available_exact_native(capabilities: &[BackendCapabilityMatrix], cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartEightError>",
        mutation_rule: "read only",
        alias_rule: "projects caller-owned canonical capability matrices",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "true iff a certified Metal capability matrix is present",
        numeric_rule: "boolean capability projection",
        tolerance: "exact boolean",
        determinism: "caller-provided canonical matrix order does not affect the result",
        cancellation_points: "before and during bounded matrix inspection",
        vjp_rule: "non-differentiable capability query",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/mps_is_available.json",
        evidence_fixture_sha256: "c1732bb4d740c1d3b37a0ba4b579b5791cbf7e53064b62d0489f75f55ea4a343",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5C52F193416C",
        baseline_overload_id: "COMFY-TENSOR-OP-5C52F193416C:blocked",
        baseline_fixture_sha256: "f10e5556ab785a44eb90bba136bdad8bab20259a31eeb4f7b03f370af6c3bd29",
        overload_id: "sim.native.tensor.concatenate.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"inputs","type":"slice<Tensor>"},{"default":0,"keyword_only":true,"kind":"keyword_only","name":"dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn concatenate_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "matching ranks and non-axis dimensions; signed axis lengths are summed with overflow checks",
        dtype_rule: "all inputs have one exact canonical dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "exact element-byte concatenation in input order",
        tolerance: "bit exact",
        determinism: "input order then row-major order",
        cancellation_points: "before validation, bounded element copies, and before publication",
        vjp_rule: "splits the upstream gradient into exact axis ranges",
        jvp_rule: "concatenates input tangents with identical geometry",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/concatenate.json",
        evidence_fixture_sha256: "921fd53af27141d0a5beef953c47a80494576d4c86b6b14951385d156d949b4c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5C00AB949613",
        baseline_overload_id: "COMFY-TENSOR-OP-5C00AB949613:blocked",
        baseline_fixture_sha256: "0dc763d379e5c22fe1b53cf5dd193cca768e992e02cd4c92dcf3fbfa40c27e78",
        overload_id: "sim.native.tensor.cos.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn cos_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "canonical unary owner allocates fresh storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE cosine",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical unary checkpoints",
        vjp_rule: "negative sine times upstream",
        jvp_rule: "negative sine times input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/cos.json",
        evidence_fixture_sha256: "1d80af4d13c3b852cdf310be24a13e6c681125005ec4723e825092bec20a8819",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5D7C103AB024",
        baseline_overload_id: "COMFY-TENSOR-OP-5D7C103AB024:blocked",
        baseline_fixture_sha256: "6af1b41e4a3b665c5cf1b92a1e0ded5b77e6ba2e4cb334aa70e938648f79c7ca",
        overload_id: "sim.native.tensor.expm1.function.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn expm1_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical expm1 owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output on observed paths",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE expm1 with small-value precision",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical owner checkpoints",
        vjp_rule: "upstream multiplied by exp(input)",
        jvp_rule: "input tangent multiplied by exp(input)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/expm1_function.json",
        evidence_fixture_sha256: "874eaed8c93e9e4bc6828a4b43d3f6dba42589bebd52e94352ddf68c63f2ba3a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5AB4376A79B5",
        baseline_overload_id: "COMFY-TENSOR-OP-5AB4376A79B5:blocked",
        baseline_fixture_sha256: "e8e4736e52b3f2a567e801bdac0c07947caefc2015201e621969819378f10bd3",
        overload_id: "sim.native.tensor.index-select.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"i64"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"indices","type":"Tensor<I64, rank 1>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn index_select_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, indices: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "replaces the selected signed-axis length with the one-dimensional index count",
        dtype_rule: "preserves the canonical input dtype and requires I64 indices",
        accumulation_dtype: "F32 for the cataloged VJP",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "ordered exact gathers with checked nonnegative in-range indices",
        tolerance: "bit exact forward",
        determinism: "row-major output and index order",
        cancellation_points: "bounded index decoding, gather, scatter-add, and publication",
        vjp_rule: "scatter-adds upstream values into the F32 input shape",
        jvp_rule: "gathers the input tangent with the same indices",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/index_select.json",
        evidence_fixture_sha256: "b96da5ca2e17bdbe3c4d5149dde16a6dacee40092c23868b9bb9fec635c9918a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5BA79209BB02",
        baseline_overload_id: "COMFY-TENSOR-OP-5BA79209BB02:blocked",
        baseline_fixture_sha256: "3e0000122f150084ca4a7f18578b2426de9bb29d70e2e598ef694b2fe3229596",
        overload_id: "sim.native.tensor.median.dimension.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":true,"kind":"keyword_only","name":"dimension","type":"i64"},{"default":false,"keyword_only":true,"kind":"keyword_only","name":"keep_dimension","type":"bool"}]"#,
        output_arity: "2",
        output_types_json: r#"["Tensor<F32>","Tensor<I64>"]"#,
        rust_signature: "fn median_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, keep_dimension: bool, context: &ExecutionContext<'_>) -> Result<MedianDimensionResult, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh value and index storage",
        shape_rule: "reduces a signed nonempty axis and optionally retains length one",
        dtype_rule: "F32 values and I64 selected indices",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous outputs",
        device_rule: "CPU ordinal zero",
        numeric_rule: "lower median for even lengths, stable lowest index for ties, and first NaN propagation",
        tolerance: "exact selected values and indices",
        determinism: "outer-slice order then stable value/index ordering",
        cancellation_points: "bounded slice scans, sorting boundaries, gradient projection, and publication",
        vjp_rule: "routes upstream values to the selected source positions",
        jvp_rule: "selects tangents at the same source positions",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/median.json",
        evidence_fixture_sha256: "98529605236bf5a9ec951e91a629fd25485eb510988bd710f5a957b3e7951880",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5EECCD4F0130",
        baseline_overload_id: "COMFY-TENSOR-OP-5EECCD4F0130:blocked",
        baseline_fixture_sha256: "5b6188a8144cb11bfc0a5c5ce85c946f57dce21ce41d7a9a24442be3680c1f00",
        overload_id: "sim.native.device.mlu.current-device.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"capabilities","type":"BackendCapabilityMatrix"}]"#,
        output_arity: "1",
        output_types_json: r#"["u32"]"#,
        rust_signature: "fn mlu_current_device_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<u32, ElementwiseRuntimePartEightError>",
        mutation_rule: "read only",
        alias_rule: "projects the canonical capability matrix device",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires MLU and returns its exact ordinal",
        numeric_rule: "checked ordinal projection",
        tolerance: "exact integer",
        determinism: "canonical DeviceId value",
        cancellation_points: "before validation and before return",
        vjp_rule: "non-differentiable device query",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/mlu_current_device.json",
        evidence_fixture_sha256: "c364dd1ffc10c58ac2953c19ef58a2e191bfc0cbb04caa6148ca165c299e61fd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5CDFF9F97B6F",
        baseline_overload_id: "COMFY-TENSOR-OP-5CDFF9F97B6F:blocked",
        baseline_fixture_sha256: "377dc4fff39de1f7449505e319827bbdf7445523c19a64ae8afe9648789ae904",
        overload_id: "sim.native.tensor.rot90.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor"},{"default":1,"keyword_only":true,"kind":"keyword_only","name":"quarter_turns","type":"i64"},{"default":[0,1],"keyword_only":true,"kind":"keyword_only","name":"dimensions","type":"[i64; 2]"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn rot90_with_context_exact_native(backend: &CpuBackend, input: &Tensor, quarter_turns: i64, dimensions: [i64; 2], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "distinct signed axes swap lengths for odd normalized turns",
        dtype_rule: "preserves the canonical input dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "exact counter-clockwise quarter-turn index mapping",
        tolerance: "bit exact",
        determinism: "normalized turns and row-major copy order",
        cancellation_points: "bounded copy intervals and before publication",
        vjp_rule: "inverse quarter-turn of the upstream tensor",
        jvp_rule: "the same quarter-turn of the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/rot90.json",
        evidence_fixture_sha256: "0c3097377fc46e422804b6f41a3535cd31a2030d8bf675e746262018873f09e4",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-60A72EC2F5DD",
        baseline_overload_id: "COMFY-TENSOR-OP-60A72EC2F5DD:blocked",
        baseline_fixture_sha256: "3730cc6c468f9bc22473430f237b46e166189057e90c7d6d4e19e582d3236c2e",
        overload_id: "sim.native.tensor.square.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn square_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output on observed paths",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "input multiplied by itself with IEEE overflow and NaN behavior",
        tolerance: "one ULP",
        determinism: "row-major unary traversal",
        cancellation_points: "before dispatch, bounded elements, and before publication",
        vjp_rule: "two times input times upstream",
        jvp_rule: "two times input times input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/square.json",
        evidence_fixture_sha256: "216f1d24c0348e809d9f0d55d77753278d6b7963340e0a04a4ba38bc3a23407f",
    },
]
