&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5DFBC70338A1",
        baseline_overload_id: "COMFY-TENSOR-OP-5DFBC70338A1:blocked",
        baseline_fixture_sha256: "784550654e53a716633d1ef75a99c7a234456d61111e655f0f6eb419f337f8c6",
        overload_id: "zed.native.tensor.byte.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<real or integer>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<U8>"]"#,
        rust_signature: "fn byte_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical U8 storage",
        shape_rule: "preserves shape",
        dtype_rule: "real, integer, and boolean inputs convert to U8; complex inputs fail",
        accumulation_dtype: "U8",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "integers and truncated real values wrap modulo 256",
        tolerance: "exact bytes",
        determinism: "row-major scalar decoding",
        cancellation_points: "before dispatch, bounded conversion intervals, and before publication",
        vjp_rule: "non-differentiable cast",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/byte_method.json",
        evidence_fixture_sha256: "d8de65e069dc65efda386c165079cc5afd7005d21ee0862297696b91211ec778",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5ED49DCA2F78",
        baseline_overload_id: "COMFY-TENSOR-OP-5ED49DCA2F78:blocked",
        baseline_fixture_sha256: "38df4c4db6441f0b3d3b9abddc1eca20de30a2d6d0bc70188bd40f12b8ea6614",
        overload_id: "zed.native.tensor.log.method.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn log_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to canonical natural-logarithm owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE natural logarithm including zero, infinity, and domain NaN",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical unary checkpoints",
        vjp_rule: "upstream divided by input",
        jvp_rule: "input tangent divided by input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/log_method.json",
        evidence_fixture_sha256: "51b1c8836edefe5dcb40327ad63308d6ff31cb019c1c87ca25fd3b6b545c48f1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5CEC7CF2D62D",
        baseline_overload_id: "COMFY-TENSOR-OP-5CEC7CF2D62D:blocked",
        baseline_fixture_sha256: "974bd7716c51af798e6bd53898e1d0ca3e1d60069a68be95e9dbd7bef864ccc9",
        overload_id: "zed.native.autograd.grad.reverse-tape.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"tape","type":"mutable AutogradTape"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"seeds","type":"Vec<(OutputSlot, Tensor)>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"inputs","type":"slice<LeafId>"},{"default":false,"keyword_only":true,"kind":"keyword_only","name":"allow_unused","type":"bool"}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Option<Tensor>>"]"#,
        rust_signature: "fn autograd_grad_exact_native(tape: &mut AutogradTape, seeds: Vec<(OutputSlot, Tensor)>, inputs: &[LeafId], reducer: &dyn GradientReducer, allow_unused: bool, cancellation: &CancellationToken) -> Result<Vec<Option<Tensor>>, ElementwiseRuntimePartEightError>",
        mutation_rule: "consumes the canonical tape through its terminal backward transition",
        alias_rule: "gradient tensors are owned by AutogradTape and returned in requested leaf order",
        shape_rule: "seed and VJP shapes are validated by the canonical tape",
        dtype_rule: "canonical tape and reducer descriptor rules",
        accumulation_dtype: "canonical GradientReducer",
        layout_rule: "preserves canonical gradient descriptors",
        device_rule: "delegates device validation to tape VJPs and reducer",
        numeric_rule: "reverse traversal and accumulation are owned by AutogradTape",
        tolerance: "exact canonical tape result",
        determinism: "reverse node order and requested leaf order",
        cancellation_points: "canonical tape checkpoints and ordered result projection",
        vjp_rule: "this is the reverse-mode execution boundary",
        jvp_rule: "not applicable to the reverse-mode boundary",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/autograd_grad.json",
        evidence_fixture_sha256: "a59e13e55646f98e9f78077482f8c0c474b69ae25b53f70ce2c108027b276b48",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5BF1DE9DA499",
        baseline_overload_id: "COMFY-TENSOR-OP-5BF1DE9DA499:blocked",
        baseline_fixture_sha256: "e8a45e4f7eea72a7af736a3978bf2f9b53e61cbdcaed139a2d9cfc3d73ce9886",
        overload_id: "zed.native.device.mps.is-available.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"capabilities","type":"slice<BackendCapabilityMatrix>"}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn mps_is_available_exact_native(capabilities: &[BackendCapabilityMatrix], cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartEightError>",
        mutation_rule: "read only",
        alias_rule: "projects caller-owned canonical capability matrices",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "true iff a certified Metal capability matrix is present",
        numeric_rule: "boolean capability projection",
        tolerance: "exact boolean",
        determinism: "caller-provided canonical matrix order does not affect the result",
        cancellation_points: "before and during bounded matrix inspection",
        vjp_rule: "non-differentiable capability query",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/mps_is_available.json",
        evidence_fixture_sha256: "f690f1247a9b08d7e5a147db29a79d906e56ea3d1a82ad37c17bd4fda4e58798",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5C52F193416C",
        baseline_overload_id: "COMFY-TENSOR-OP-5C52F193416C:blocked",
        baseline_fixture_sha256: "1166a02fecba1ed1344cdd3ae2203c38e026e0bfdc012d7ce6f3100fd657bd5b",
        overload_id: "zed.native.tensor.concatenate.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"inputs","type":"slice<Tensor>"},{"default":0,"keyword_only":true,"kind":"keyword_only","name":"dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn concatenate_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "matching ranks and non-axis dimensions; signed axis lengths are summed with overflow checks",
        dtype_rule: "all inputs have one exact canonical dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "exact element-byte concatenation in input order",
        tolerance: "bit exact",
        determinism: "input order then row-major order",
        cancellation_points: "before validation, bounded element copies, and before publication",
        vjp_rule: "splits the upstream gradient into exact axis ranges",
        jvp_rule: "concatenates input tangents with identical geometry",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/concatenate.json",
        evidence_fixture_sha256: "e3e31329bda8ed6ac88a2aacb886fbb4a2b197ecf65e3d3c538b60b9c09211ab",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5C00AB949613",
        baseline_overload_id: "COMFY-TENSOR-OP-5C00AB949613:blocked",
        baseline_fixture_sha256: "fe2beb5309a9014e1d6a35fc7c1973349a5f2ba96ab5e569f40b04ed07a7d442",
        overload_id: "zed.native.tensor.cos.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn cos_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "canonical unary owner allocates fresh storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE cosine",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical unary checkpoints",
        vjp_rule: "negative sine times upstream",
        jvp_rule: "negative sine times input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/cos.json",
        evidence_fixture_sha256: "937bc2f484cf25929124005bb886b0a0d4c02a7adef972cd8f2b2b9a04c12982",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5D7C103AB024",
        baseline_overload_id: "COMFY-TENSOR-OP-5D7C103AB024:blocked",
        baseline_fixture_sha256: "10bf4a62d2729e9231a5ae60d5dd64805b9708b94ae6abcfbb8e5edee39b3ac6",
        overload_id: "zed.native.tensor.expm1.function.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn expm1_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical expm1 owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output on observed paths",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE expm1 with small-value precision",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical owner checkpoints",
        vjp_rule: "upstream multiplied by exp(input)",
        jvp_rule: "input tangent multiplied by exp(input)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/expm1_function.json",
        evidence_fixture_sha256: "f1d579895a292ec05c5dc4d27d5c5ea42fa36f5f735bc198ff06ce01f4501cdc",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5AB4376A79B5",
        baseline_overload_id: "COMFY-TENSOR-OP-5AB4376A79B5:blocked",
        baseline_fixture_sha256: "66eaf33517716ea6b483200a5241a3d7a0b5f4ae72a00393fa1e06e9763b5b82",
        overload_id: "zed.native.tensor.index-select.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"i64"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"indices","type":"Tensor<I64, rank 1>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn index_select_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, indices: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "replaces the selected signed-axis length with the one-dimensional index count",
        dtype_rule: "preserves the canonical input dtype and requires I64 indices",
        accumulation_dtype: "F32 for the cataloged VJP",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "ordered exact gathers with checked nonnegative in-range indices",
        tolerance: "bit exact forward",
        determinism: "row-major output and index order",
        cancellation_points: "bounded index decoding, gather, scatter-add, and publication",
        vjp_rule: "scatter-adds upstream values into the F32 input shape",
        jvp_rule: "gathers the input tangent with the same indices",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/index_select.json",
        evidence_fixture_sha256: "996fa6bddcbafb1631fbe14105249069d4c33d579af475746255d2c936273327",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5BA79209BB02",
        baseline_overload_id: "COMFY-TENSOR-OP-5BA79209BB02:blocked",
        baseline_fixture_sha256: "90f36c53acfaf932f0c85175ee48f6fa94e12e99d869a1064d3087ba5613a666",
        overload_id: "zed.native.tensor.median.dimension.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":true,"kind":"keyword_only","name":"dimension","type":"i64"},{"default":false,"keyword_only":true,"kind":"keyword_only","name":"keep_dimension","type":"bool"}]"#,
        output_arity: "2",
        output_types_json: r#"["Tensor<F32>","Tensor<I64>"]"#,
        rust_signature: "fn median_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, keep_dimension: bool, context: &ExecutionContext<'_>) -> Result<MedianDimensionResult, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh value and index storage",
        shape_rule: "reduces a signed nonempty axis and optionally retains length one",
        dtype_rule: "F32 values and I64 selected indices",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous outputs",
        device_rule: "CPU ordinal zero",
        numeric_rule: "lower median for even lengths, stable lowest index for ties, and first NaN propagation",
        tolerance: "exact selected values and indices",
        determinism: "outer-slice order then stable value/index ordering",
        cancellation_points: "bounded slice scans, sorting boundaries, gradient projection, and publication",
        vjp_rule: "routes upstream values to the selected source positions",
        jvp_rule: "selects tangents at the same source positions",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/median.json",
        evidence_fixture_sha256: "a01a796114431c75ee30cf9e3fdf303b7d89ceb0b3f9699eec20a382aeb2875b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5EECCD4F0130",
        baseline_overload_id: "COMFY-TENSOR-OP-5EECCD4F0130:blocked",
        baseline_fixture_sha256: "94d3ac5aa4924d748b9b9a9d435a6244887922bc7eebb583f69b781d99f890f3",
        overload_id: "zed.native.device.mlu.current-device.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"capabilities","type":"BackendCapabilityMatrix"}]"#,
        output_arity: "1",
        output_types_json: r#"["u32"]"#,
        rust_signature: "fn mlu_current_device_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<u32, ElementwiseRuntimePartEightError>",
        mutation_rule: "read only",
        alias_rule: "projects the canonical capability matrix device",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires MLU and returns its exact ordinal",
        numeric_rule: "checked ordinal projection",
        tolerance: "exact integer",
        determinism: "canonical DeviceId value",
        cancellation_points: "before validation and before return",
        vjp_rule: "non-differentiable device query",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/mlu_current_device.json",
        evidence_fixture_sha256: "23e7b73bca15ddd0435e4bc39713f0f51bfd2225ce68d9b456c57af3d59ca429",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-5CDFF9F97B6F",
        baseline_overload_id: "COMFY-TENSOR-OP-5CDFF9F97B6F:blocked",
        baseline_fixture_sha256: "ca76e601c6c3a9af506389435e4cd10b04dc32d65883ad1f2681d80f9a99c02a",
        overload_id: "zed.native.tensor.rot90.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor"},{"default":1,"keyword_only":true,"kind":"keyword_only","name":"quarter_turns","type":"i64"},{"default":[0,1],"keyword_only":true,"kind":"keyword_only","name":"dimensions","type":"[i64; 2]"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn rot90_with_context_exact_native(backend: &CpuBackend, input: &Tensor, quarter_turns: i64, dimensions: [i64; 2], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "distinct signed axes swap lengths for odd normalized turns",
        dtype_rule: "preserves the canonical input dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "exact counter-clockwise quarter-turn index mapping",
        tolerance: "bit exact",
        determinism: "normalized turns and row-major copy order",
        cancellation_points: "bounded copy intervals and before publication",
        vjp_rule: "inverse quarter-turn of the upstream tensor",
        jvp_rule: "the same quarter-turn of the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/rot90.json",
        evidence_fixture_sha256: "8a1c98c9dc815f10a890339e7f8b22ca6c9a26da58b17f91e7ff4064d87c1e23",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_08",
        operation_id: "COMFY-TENSOR-OP-60A72EC2F5DD",
        baseline_overload_id: "COMFY-TENSOR-OP-60A72EC2F5DD:blocked",
        baseline_fixture_sha256: "755180823af0291865cf63afda373acca057a9b9afdd1612a9b3b4be34657c4f",
        overload_id: "zed.native.tensor.square.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn square_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEightError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output on observed paths",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "input multiplied by itself with IEEE overflow and NaN behavior",
        tolerance: "one ULP",
        determinism: "row-major unary traversal",
        cancellation_points: "before dispatch, bounded elements, and before publication",
        vjp_rule: "two times input times upstream",
        jvp_rule: "two times input times input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-5ab4376a79b5",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_08/square.json",
        evidence_fixture_sha256: "e05f92c4697ffa5b973568c5ffab01f51952007c23e761c3b267e17d9877201e",
    },
]
