&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B74E6E64A97F",
        baseline_overload_id: "COMFY-TENSOR-OP-B74E6E64A97F:blocked",
        baseline_fixture_sha256: "c3857bb513dabbd4345b40f031ed4b0d6d9f6ad6f996341ad3afc5a9dc5995a5",
        overload_id: "zed.native.tensor.add-method.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"Tensor<F32>|Scalar"},{"default":1.0,"keyword_only":true,"kind":"keyword_only","name":"alpha","type":"f32"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn add_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, alpha: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "standard tensor broadcasting; scalar preserves input shape",
        dtype_rule: "F32 leaf profile",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "input + alpha*other through canonical binary owners",
        tolerance: "1e-6 absolute",
        determinism: "canonical row-major binary traversal",
        cancellation_points: "before and during canonical backend stages",
        vjp_rule: "input gradient is reduced output gradient; tensor-other gradient is alpha-scaled and broadcast-reduced",
        jvp_rule: "dinput + alpha*dother",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/add_method.json",
        evidence_fixture_sha256: "d89db899bcaf69681b16933e6cdc8aaed5d949437775aab3f941e39fabf8ab25",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B82E0C11E45D",
        baseline_overload_id: "COMFY-TENSOR-OP-B82E0C11E45D:blocked",
        baseline_fixture_sha256: "007d3d7bc07a1f7953ce47b62f7d09770716395cc08f1ebf4f10dfa593a0ba5b",
        overload_id: "zed.native.tensor.mul-method.canonical.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn mul_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 51 canonical multiply owner",
        shape_rule: "standard broadcasting",
        dtype_rule: "canonical multiply F32 profile",
        accumulation_dtype: "F32",
        layout_rule: "canonical multiply layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical IEEE multiplication",
        tolerance: "1e-6 absolute",
        determinism: "canonical multiply traversal",
        cancellation_points: "canonical multiply checkpoints",
        vjp_rule: "canonical product rule with broadcast reduction",
        jvp_rule: "dinput*other + input*dother",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/mul_method.json",
        evidence_fixture_sha256: "ff146ca201d73f494660a746f60c7d5530be5cd98cff7efd5df40a9ba6eba4cc",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B40398C137FF",
        baseline_overload_id: "COMFY-TENSOR-OP-B40398C137FF:blocked",
        baseline_fixture_sha256: "23be7cf9d67f8e19cc3bdde17e847c67dd2c06b0575555b916c9ad48ba0826de",
        overload_id: "zed.native.tensor.square-method.canonical.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn square_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 50 canonical square owner",
        shape_rule: "preserves shape",
        dtype_rule: "canonical square F32 profile",
        accumulation_dtype: "F32",
        layout_rule: "canonical square layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "value multiplied by itself",
        tolerance: "1e-6 absolute",
        determinism: "canonical square traversal",
        cancellation_points: "canonical square checkpoints",
        vjp_rule: "2*input*output_gradient",
        jvp_rule: "2*input*input_tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/square_method.json",
        evidence_fixture_sha256: "695b7423a32c97dd6ae53355bbf51fee52d4f5ff0d32b728ebeebd0619453843",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B4F8F3B2B2E6",
        baseline_overload_id: "COMFY-TENSOR-OP-B4F8F3B2B2E6:blocked",
        baseline_fixture_sha256: "27542cc37e4a203fff7e2a3da41f765bfb9cb563920bc43b7d6c37e032187428",
        overload_id: "zed.native.tensor.atan.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn atan_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "Rust f32 atan with IEEE NaN and infinity behavior",
        tolerance: "1e-6 absolute",
        determinism: "canonical unary traversal",
        cancellation_points: "backend unary checkpoints",
        vjp_rule: "output_gradient/(1+input^2)",
        jvp_rule: "input_tangent/(1+input^2)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/atan.json",
        evidence_fixture_sha256: "2f8826e1194da88e4569e9f0b7a6e2ca0efe52a70197e32fdaa24b0e6f9d0154",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B4B7266D14A9",
        baseline_overload_id: "COMFY-TENSOR-OP-B4B7266D14A9:blocked",
        baseline_fixture_sha256: "14c71e0d65f6cc6984a45f114989a48130eb5a8fe58992598bbe6c745f9e7aa0",
        overload_id: "zed.native.tensor.bitwise-and.cpu-integral.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"left","type":"integral Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"right","type":"integral Tensor"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn bitwise_and_with_context_exact_native(backend: &CpuBackend, left: &Tensor, right: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "standard broadcasting",
        dtype_rule: "canonical integral and bool promotion; floating and complex reject",
        accumulation_dtype: "promoted integral dtype",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "bit-exact boolean, signed, or unsigned AND",
        tolerance: "exact",
        determinism: "fixed row-major traversal",
        cancellation_points: "bounded element intervals and atomic upload",
        vjp_rule: "non-differentiable",
        jvp_rule: "non-differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/bitwise_and.json",
        evidence_fixture_sha256: "f7296a21251bdd8348bc35f64df7170d63eb5c76d6bf6a6eda209887e33b71bd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B153098D5C48",
        baseline_overload_id: "COMFY-TENSOR-OP-B153098D5C48:blocked",
        baseline_fixture_sha256: "2ae2094f9965356732c0e988aa61fa195cc9c5896b41cc273dc5937d4b3142c1",
        overload_id: "zed.native.runtime.cudart.certified-ffi.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"certification","type":"CertifiedNativeFfi"}]"#,
        output_arity: "1",
        output_types_json: r#"["CertifiedNativeFfi"]"#,
        rust_signature: "fn comfy_runtime::cudart_exact_native(certification: &CertifiedNativeFfi, context: &ExecutionContext<'_>) -> Result<&CertifiedNativeFfi, TrustError>",
        mutation_rule: "read-only certification projection",
        alias_rule: "borrows the registry-issued sealed certification",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "does not claim CUDA availability or expose an unchecked raw handle",
        numeric_rule: "exact library, ABI digest, and required-symbol certificate",
        tolerance: "exact",
        determinism: "registry-issued immutable certificate",
        cancellation_points: "before and after certificate inspection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/cudart.json",
        evidence_fixture_sha256: "fa115ed433a20fda1d9636d6aa6f87c7859d948c2045bb554c9ee77b1571a909",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B1A79A94DDE6",
        baseline_overload_id: "COMFY-TENSOR-OP-B1A79A94DDE6:blocked",
        baseline_fixture_sha256: "e7680822dde60d88d1f8c04b6eac041e20a5e46b7ccb24f806d9952ce2b42250",
        overload_id: "zed.native.tensor.is-tensor.typed-projection.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Option<&Tensor>"}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn is_tensor_exact_native(input: Option<&Tensor>, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "read only",
        alias_rule: "copyable bool",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent typed boundary projection",
        numeric_rule: "true exactly when boundary decoding produced a canonical Tensor reference",
        tolerance: "exact",
        determinism: "pure typed projection",
        cancellation_points: "before projection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/is_tensor.json",
        evidence_fixture_sha256: "8ec85e5a89f074a36604250473bc4aca654885655cb0110a45d205b1479401cb",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B296530D4BB3",
        baseline_overload_id: "COMFY-TENSOR-OP-B296530D4BB3:blocked",
        baseline_fixture_sha256: "4a0f5dfba4cfe5f8557e92229ea88a8baeacb068e36b78f9c1a99f437368c5df",
        overload_id: "zed.native.tensor.kaiser-window.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"length","type":"u64"},{"default":true,"keyword_only":false,"kind":"positional_or_keyword","name":"periodic","type":"bool"},{"default":12.0,"keyword_only":false,"kind":"positional_or_keyword","name":"beta","type":"f64"},{"default":"F32","keyword_only":true,"kind":"keyword_only","name":"dtype","type":"F32|F64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn kaiser_window_with_context_exact_native(backend: &CpuBackend, length: u64, periodic: bool, beta: f64, dtype: DType, stream: StreamId, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "rank-one [length]; periodic denominator length, symmetric denominator length-1",
        dtype_rule: "F32 or F64",
        accumulation_dtype: "F64",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "Cephes-compatible modified Bessel I0 approximation; length zero empty and length one equals one",
        tolerance: "2e-6 absolute",
        determinism: "fixed index traversal",
        cancellation_points: "bounded sample intervals and atomic upload",
        vjp_rule: "window construction parameters are non-Tensor inputs",
        jvp_rule: "window construction parameters are non-Tensor inputs",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/kaiser_window.json",
        evidence_fixture_sha256: "924ab7985e154a31a841341ae86a8da54a3cdb28bb07dc630c1387ce7dcfefb3",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B7955A0A7AC9",
        baseline_overload_id: "COMFY-TENSOR-OP-B7955A0A7AC9:blocked",
        baseline_fixture_sha256: "9adb855a948058ff22550316ed7200afa5102be0d6c278818e6a9c97219b3ad3",
        overload_id: "zed.native.tensor.logaddexp.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"left","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"right","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn logaddexp_with_context_exact_native(backend: &CpuBackend, left: &Tensor, right: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "standard broadcasting",
        dtype_rule: "F32 leaf profile",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "max(left,right)+log1p(exp(-abs(left-right))) with equal-infinity and NaN handling",
        tolerance: "2e-6 absolute",
        determinism: "canonical row-major binary traversal",
        cancellation_points: "backend binary and derivative traversal checkpoints",
        vjp_rule: "stable softmax weights times output gradient with broadcast reduction",
        jvp_rule: "stable softmax weights times input tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/logaddexp.json",
        evidence_fixture_sha256: "caf86f7e9d9e5f4a845acd59515b0546a07dd014f09a9ab7d16ec818dbb4579f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B2699A727A6C",
        baseline_overload_id: "COMFY-TENSOR-OP-B2699A727A6C:blocked",
        baseline_fixture_sha256: "3310fb89814d58869a7b8b0f4d44ac495cfee9cd4c7a1aab3f265de5cb6050fc",
        overload_id: "zed.native.worker.mlu-empty-cache.canonical-accounting.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"backend","type":"CachedAllocationOwner"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"inventory","type":"MemoryPlacementInventory"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"device","type":"MLU DeviceId"}]"#,
        output_arity: "1",
        output_types_json: r#"["CacheReleaseSummary"]"#,
        rust_signature: "fn comfy_worker::mlu_empty_cache_exact_native(backend: &dyn CachedAllocationOwner, inventory: &mut MemoryPlacementInventory, device: DeviceId, context: &ExecutionContext<'_>) -> Result<CacheReleaseSummary, NativeMemoryStatsError>",
        mutation_rule: "canonical inventory removes only accounted evictable cache records after backend release succeeds",
        alias_rule: "no parallel cache state",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 bytes",
        layout_rule: "not applicable",
        device_rule: "exact MLU device-kind validation",
        numeric_rule: "exact released allocator bytes and accounting action summary",
        tolerance: "exact",
        determinism: "canonical resource-id eviction order",
        cancellation_points: "before release, before each accounting action, and before publication",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/mlu_empty_cache.json",
        evidence_fixture_sha256: "1cdae371a347a1197f19c4b5a9a479d861e3b02a44bf4c183efb3cc5cc4203f7",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B30CBD7D8727",
        baseline_overload_id: "COMFY-TENSOR-OP-B30CBD7D8727:blocked",
        baseline_fixture_sha256: "f39d2ddd6f04bb98db21278b22b13d0e782cc723d857a065596caab33c75565d",
        overload_id: "zed.native.model.add-safe-globals.immutable-admission.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"requested_targets","type":"slice<&str>"}]"#,
        output_arity: "1",
        output_types_json: r#"["SafeGlobalsAdmission"]"#,
        rust_signature: "fn comfy_model::add_safe_globals_exact_native(requested_targets: &[&str], context: &ExecutionContext<'_>) -> Result<SafeGlobalsAdmission, RestrictedPickleError>",
        mutation_rule: "returns immutable request-scoped admission; never mutates the process allowlist",
        alias_rule: "admitted targets borrow static canonical allowlist identifiers",
        shape_rule: "bounded by canonical allowlist length",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "exact sorted and deduplicated allowlist membership",
        tolerance: "exact",
        determinism: "canonical lexical target order",
        cancellation_points: "before and during bounded target validation",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/add_safe_globals.json",
        evidence_fixture_sha256: "16b5ec6158381e55906f87d93168529d95554b0531c2f4b6058e5af82bafde70",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_16",
        operation_id: "COMFY-TENSOR-OP-B088976A05AB",
        baseline_overload_id: "COMFY-TENSOR-OP-B088976A05AB:blocked",
        baseline_fixture_sha256: "752f87a0ed672a943897ccfd6525651dbae3e8459de590774d6a4e482ade5f84",
        overload_id: "zed.native.tensor.tile.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"repeats","type":"slice<i64>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tile_with_context_exact_native(backend: &CpuBackend, input: &Tensor, repeats: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSixteenError>",
        mutation_rule: "out of place with publication after full checked copy",
        alias_rule: "fresh canonical storage",
        shape_rule: "left-pad input shape or repeats with ones, reject negative repeats, checked dimension multiplication",
        dtype_rule: "preserves all canonical dtype bytes",
        accumulation_dtype: "none; F32 for VJP",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "byte-exact repeated logical indexing",
        tolerance: "exact forward; 1e-6 derivative",
        determinism: "fixed row-major output traversal",
        cancellation_points: "bounded output intervals and atomic upload",
        vjp_rule: "sum each repeated output-gradient position into its original input index",
        jvp_rule: "tile the input tangent with identical repeats",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b088976a05ab",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_16/tile.json",
        evidence_fixture_sha256: "9afc1e6b6ad3284a5fc5b99cf0a31f6b87beb09e62f3fa818263bcc3176d8301",
    },
]
