&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0B05AB07BE66",
        baseline_overload_id: "COMFY-TENSOR-OP-0B05AB07BE66:blocked",
        baseline_fixture_sha256: "755833e4c723bcf8e8e49e5bad63c544d07f11d973496bedecd7c1ab60f7e6c6",
        overload_id: "zed.native.tensor.abs.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<f32>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn abs_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimeError>",
        mutation_rule: "out of place; input storage and descriptor are unchanged",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "output shape exactly equals input shape, including scalar and empty tensors",
        dtype_rule: "the certified CPU overload accepts and returns f32",
        accumulation_dtype: "no accumulation",
        layout_rule: "logical values are projected to canonical contiguous output",
        device_rule: "CPU ordinal zero is certified; other devices fail typed",
        numeric_rule: "IEEE absolute value preserves NaN and clears the sign bit of negative zero",
        tolerance: "bit exact except the preserved NaN payload is not compared",
        determinism: "fixed per-element traversal",
        cancellation_points: "before dispatch, inside the canonical backend loop, and before publication",
        vjp_rule: "gradient is output_gradient times sign(input), with zero derivative at either signed zero",
        jvp_rule: "tangent is input_tangent times sign(input), with zero derivative at either signed zero",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/abs.json",
        evidence_fixture_sha256: "88c61be52a70a469f877cee981bd5257d877873aa07c1cf36ce1deb8a0a05b47",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0546BABACDB9",
        baseline_overload_id: "COMFY-TENSOR-OP-0546BABACDB9:blocked",
        baseline_fixture_sha256: "6448091e56b4b01d33eb3a3b457da6c1cc662598386a5da6254bc5fcececddde",
        overload_id: "zed.native.backend.cuda-device-properties.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"DeviceId\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeDeviceProperties\"]",
        rust_signature: "fn cuda_get_device_properties_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<NativeDeviceProperties, ElementwiseRuntimeError>",
        mutation_rule: "read-only projection from the canonical capability matrix",
        alias_rule: "returns an owned bounded property snapshot",
        shape_rule: "not applicable",
        dtype_rule: "property fields are typed integers, booleans, and bounded strings",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "CUDA or ROCm identity and ordinal must exactly match the matrix; missing certified properties fail typed",
        numeric_rule: "memory bytes and major/minor values are exact certified facts",
        tolerance: "exact",
        determinism: "immutable matrix projection",
        cancellation_points: "before validation and before returning the snapshot",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/cuda_get_device_properties.json",
        evidence_fixture_sha256: "2d64ea6fe64c4a313eed9c54417ce14bc9f042cdc9fc6ba4c1e78d7dbd8b651f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0B36DDFC0CD6",
        baseline_overload_id: "COMFY-TENSOR-OP-0B36DDFC0CD6:blocked",
        baseline_fixture_sha256: "f111971a040581c900d809a22b8ac6c5f56103573910b7650ecd815f6ee368d8",
        overload_id: "zed.native.tensor.device-parse.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"source\",\"type\":\"str\"}]",
        output_arity: "1",
        output_types_json: "[\"DeviceId\"]",
        rust_signature: "fn device_exact_native(source: &str, cancellation: &CancellationToken) -> Result<DeviceId, ElementwiseRuntimeError>",
        mutation_rule: "pure checked parse",
        alias_rule: "returns a copyable canonical device identity",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "DeviceId alone maps exact native kind aliases and a checked u32 ordinal; an omitted ordinal resolves to zero",
        numeric_rule: "ordinal parsing rejects negative, overflowing, empty, and repeated separators",
        tolerance: "exact",
        determinism: "fixed closed device vocabulary",
        cancellation_points: "before and after parsing",
        vjp_rule: "device identities are non-differentiable",
        jvp_rule: "device identities have no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/device.json",
        evidence_fixture_sha256: "1d7b371f83c7a9b0e77dc5498725ee2238f715e457a9e73de87d6582dce63322",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0DB870AE36B5",
        baseline_overload_id: "COMFY-TENSOR-OP-0DB870AE36B5:blocked",
        baseline_fixture_sha256: "1ec42c2bf2feac1966a509789edf7813f0d0cae61aac57f268d5688e950c616e",
        overload_id: "zed.native.tensor.dim.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"usize\"]",
        rust_signature: "fn dim_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<usize, ElementwiseRuntimeError>",
        mutation_rule: "read-only descriptor query",
        alias_rule: "no tensor is created",
        shape_rule: "returns TensorDescriptor rank exactly; scalar rank is zero",
        dtype_rule: "dtype neutral",
        accumulation_dtype: "not applicable",
        layout_rule: "layout neutral",
        device_rule: "descriptor query does not dispatch a backend",
        numeric_rule: "exact nonnegative integer",
        tolerance: "exact",
        determinism: "immutable descriptor projection",
        cancellation_points: "before and after descriptor projection",
        vjp_rule: "rank metadata is non-differentiable and observed only in shape-control paths",
        jvp_rule: "rank metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/dim.json",
        evidence_fixture_sha256: "ec6ea03d16323c68dba2f6e7f015e85bc5113b72880e9257e24c1ce935261710",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0A5DBFB907FD",
        baseline_overload_id: "COMFY-TENSOR-OP-0A5DBFB907FD:blocked",
        baseline_fixture_sha256: "c405aecfc3a262982f51f3e98c0491413056ea73d8da1519e231dd96b1a86605",
        overload_id: "zed.native.tensor.finfo.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dtype\",\"type\":\"DType\"}]",
        output_arity: "1",
        output_types_json: "[\"FloatingPointInfo\"]",
        rust_signature: "fn finfo_exact_native(dtype: DType, cancellation: &CancellationToken) -> Result<FloatingPointInfo, ElementwiseRuntimeError>",
        mutation_rule: "pure canonical dtype metadata query",
        alias_rule: "returns a copyable immutable value",
        shape_rule: "not applicable",
        dtype_rule: "DType owns bits, epsilon, min, max, smallest normal, and decimal resolution; non-floating dtypes fail typed",
        accumulation_dtype: "metadata values use f64 representation",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "values are exact constants for every cataloged floating and float8 format",
        tolerance: "bit exact f64 constants",
        determinism: "closed match over canonical DType",
        cancellation_points: "before and after metadata lookup",
        vjp_rule: "dtype metadata is non-differentiable",
        jvp_rule: "dtype metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/finfo.json",
        evidence_fixture_sha256: "4f77e4f516395daea85cb997a43a4faf315820e3f5497a6b0640365bc1b66d5f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-07B99A0B13EF",
        baseline_overload_id: "COMFY-TENSOR-OP-07B99A0B13EF:blocked",
        baseline_fixture_sha256: "85376ed522bedbe69e56cd21725f693cf16fada9bbbb8150ca39c821822473d2",
        overload_id: "zed.native.tensor.meshgrid.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"inputs\",\"type\":\"nonempty list of scalar or rank-one Tensor\"},{\"default\":\"ij\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"indexing\",\"type\":\"MeshgridIndexing\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<Tensor>\"]",
        rust_signature: "fn meshgrid_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], indexing: MeshgridIndexing, context: &ExecutionContext<'_>) -> Result<Vec<Tensor>, ElementwiseRuntimeError>",
        mutation_rule: "out of place; all inputs remain unchanged",
        alias_rule: "one fresh canonical output storage is returned per input",
        shape_rule: "ij output axes follow input order; xy swaps the first two output axes; scalars contribute length one and empty vectors produce empty grids",
        dtype_rule: "all inputs and outputs share one canonical dtype",
        accumulation_dtype: "VJP accumulation is f32 for the certified differentiable overload",
        layout_rule: "outputs are canonical contiguous tensors",
        device_rule: "CPU ordinal zero is certified and all inputs must share stream",
        numeric_rule: "each output broadcasts its corresponding input value over every other grid axis",
        tolerance: "bit-exact element copying; f32 VJP uses fixed addition order",
        determinism: "row-major traversal with explicit ij or xy mapping",
        cancellation_points: "before validation, every bounded output traversal, during upload, and before publication",
        vjp_rule: "each input gradient sums its corresponding output gradient over all broadcast axes",
        jvp_rule: "input tangents use the identical meshgrid mapping",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/meshgrid.json",
        evidence_fixture_sha256: "6dce009fcb89dbe49f140097f0f387c2cc41af1bbeeab34b5d7320b80c47657c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-015751FC6965",
        baseline_overload_id: "COMFY-TENSOR-OP-015751FC6965:blocked",
        baseline_fixture_sha256: "c8b6b048af1e11c9fcca3d6a49854243291291d26d502316c7ad49ac80df35e4",
        overload_id: "zed.native.tensor.signbit.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"real Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn signbit_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimeError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh boolean storage",
        shape_rule: "output shape exactly equals input shape",
        dtype_rule: "canonical scalar codecs handle boolean, signed, unsigned, and floating inputs; complex inputs fail typed",
        accumulation_dtype: "no accumulation",
        layout_rule: "canonical contiguous boolean output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "floating sign uses the encoded IEEE sign including negative zero and signed NaN; signed integers test less than zero; unsigned and bool are false",
        tolerance: "bit exact",
        determinism: "fixed scalar-codec traversal",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "boolean sign classification is non-differentiable and its observed quantization call is forward only",
        jvp_rule: "boolean sign classification has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/signbit.json",
        evidence_fixture_sha256: "b997216d9952c110d5b1198e562dbde8086d1866e5bb35f923688abe24be3546",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0BDEE629B8C6",
        baseline_overload_id: "COMFY-TENSOR-OP-0BDEE629B8C6:blocked",
        baseline_fixture_sha256: "a0d4dc41f4a045eb2308618bb0b21a60b274d9d490a0f697709cf341047e13e1",
        overload_id: "zed.native.tensor.sub-in-place.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Tensor<f32>\"},{\"default\":1.0,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"alpha\",\"type\":\"f32\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor alias\"]",
        rust_signature: "fn subtract_in_place_with_context_exact_native<'a>(backend: &CpuBackend, input: &'a mut Tensor, other: &Tensor, alpha: f32, context: &ExecutionContext<'_>) -> Result<&'a Tensor, ElementwiseRuntimeError>",
        mutation_rule: "stages input minus alpha times other and commits the input handle once after final cancellation",
        alias_rule: "returns the mutated input handle; canonical copy-on-write keeps preexisting aliases unchanged",
        shape_rule: "observed overload requires equal shapes and streams",
        dtype_rule: "certified CPU overload requires f32 input, other, and result",
        accumulation_dtype: "f32",
        layout_rule: "commit uses canonical contiguous storage",
        device_rule: "CPU ordinal zero is certified; cross-device input fails typed",
        numeric_rule: "computes input - alpha * other with the canonical multiply and subtract primitives",
        tolerance: "exact f32 primitive ordering",
        determinism: "fixed two-stage primitive order",
        cancellation_points: "before either primitive, within backend loops, and before the single handle commit",
        vjp_rule: "input gradient is output_gradient and other gradient is -alpha times output_gradient",
        jvp_rule: "output tangent is input_tangent - alpha times other_tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/sub_in_place.json",
        evidence_fixture_sha256: "6cda587f135e15b48918313d032369af655e3686236267f2abbae1d60f12dc42",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-0678D863EEBA",
        baseline_overload_id: "COMFY-TENSOR-OP-0678D863EEBA:blocked",
        baseline_fixture_sha256: "6bc1f13919125b4ff5ecd42ca07d3b9785baafb6140eb2cfde5b0734d2f12bb7",
        overload_id: "zed.native.tensor.triu.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"diagonal\",\"type\":\"isize\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn triu_with_context_exact_native(backend: &CpuBackend, input: &Tensor, diagonal: isize, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimeError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "rank must be at least two; the last two axes define rows and columns and leading axes batch independently",
        dtype_rule: "preserves every canonical scalar dtype through exact byte copies and canonical zero encoding",
        accumulation_dtype: "no accumulation",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "keeps element [row,column] exactly when column-row is at least diagonal and writes positive canonical zero otherwise",
        tolerance: "bit exact",
        determinism: "fixed row-major mask geometry",
        cancellation_points: "before validation, at bounded element intervals, during upload, and before publication",
        vjp_rule: "output gradient is masked by the identical triangular geometry",
        jvp_rule: "input tangent is masked by the identical triangular geometry",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/triu.json",
        evidence_fixture_sha256: "6ba0a35f64336f0d3b0db9739a11129a01645700151e2fb1a80235dfa5aa1a66",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-010917B0D872",
        baseline_overload_id: "COMFY-TENSOR-OP-010917B0D872:blocked",
        baseline_fixture_sha256: "c91b53c0c668f1c65642d03874de7690c78f559dd430f0c2290d367e286db912",
        overload_id: "zed.native.tensor.vander.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"rank-one floating Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"columns\",\"type\":\"optional usize\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"increasing\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn vander_with_context_exact_native(backend: &CpuBackend, input: &Tensor, columns: Option<usize>, increasing: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimeError>",
        mutation_rule: "out of place",
        alias_rule: "returns fresh canonical storage",
        shape_rule: "rank-one length M input returns [M,N], where omitted N equals M and zero N is valid",
        dtype_rule: "preserves canonical floating dtype; unrepresentable float8 powers fail typed",
        accumulation_dtype: "f32 for the certified VJP and JVP",
        layout_rule: "canonical contiguous row-major output",
        device_rule: "CPU ordinal zero is certified",
        numeric_rule: "columns contain powers N-1 through zero by default or zero through N-1 when increasing; x to power zero is one",
        tolerance: "exact powi and canonical scalar-codec conversion; f32 gradients use fixed order",
        determinism: "fixed row then column traversal",
        cancellation_points: "before validation, at bounded output intervals, during upload, and before publication",
        vjp_rule: "input gradient sums output_gradient times exponent times input^(exponent-1) over columns",
        jvp_rule: "each output tangent is exponent times input^(exponent-1) times input_tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/vander.json",
        evidence_fixture_sha256: "e4b3d0c3fb2bd702f42e45b7a63ccea89119dc96da12ecdf8f3695954aabf505",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-01475E433DB3",
        baseline_overload_id: "COMFY-TENSOR-OP-01475E433DB3:blocked",
        baseline_fixture_sha256: "8d61f7c25921df25144f004624f972372ebc8f2ff163d70ebcc5420765f52f83",
        overload_id: "zed.native.backend.xpu-current-device.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"u32\"]",
        rust_signature: "fn xpu_current_device_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<u32, ElementwiseRuntimeError>",
        mutation_rule: "read-only capability-context query with no process-global device mutation",
        alias_rule: "returns a copyable ordinal",
        shape_rule: "not applicable",
        dtype_rule: "exact u32 ordinal",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "the canonical matrix must identify XPU; other kinds fail typed",
        numeric_rule: "returns the exact canonical DeviceId ordinal",
        tolerance: "exact",
        determinism: "immutable matrix projection",
        cancellation_points: "before validation and before return",
        vjp_rule: "device selection metadata is non-differentiable",
        jvp_rule: "device selection metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/xpu_current_device.json",
        evidence_fixture_sha256: "da54db5513bb929259fee7c0a3b38f754137c72c40fa8ecd87457fefa8f0dcb2",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_01",
        operation_id: "COMFY-TENSOR-OP-04A23E8A6156",
        baseline_overload_id: "COMFY-TENSOR-OP-04A23E8A6156:blocked",
        baseline_fixture_sha256: "2e66a9f0acd5e38054bb9d9454c31cf2cce44345b5f531ee78c6ff94bc215404",
        overload_id: "zed.native.backend.xpu-bf16-support.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"bool\"]",
        rust_signature: "fn xpu_is_bf16_supported_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimeError>",
        mutation_rule: "read-only capability query",
        alias_rule: "returns a copyable boolean",
        shape_rule: "not applicable",
        dtype_rule: "queries canonical Bf16 support rather than a parallel hardware flag",
        accumulation_dtype: "not applicable",
        layout_rule: "support is true when at least one exact Bf16 matrix row is certified",
        device_rule: "the canonical matrix must identify XPU; other kinds fail typed",
        numeric_rule: "exact boolean with no optimistic fallback",
        tolerance: "exact",
        determinism: "immutable sorted capability projection",
        cancellation_points: "before validation and before return",
        vjp_rule: "capability metadata is non-differentiable",
        jvp_rule: "capability metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-010917b0d872",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_01/xpu_is_bf16_supported.json",
        evidence_fixture_sha256: "85fcf835dfbdab08f1900955b81c1da48d946b1e783231bed5fb9ebfc0b6e58e",
    },
]
