&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8A892AD7A3C2",
        baseline_overload_id: "COMFY-TENSOR-OP-8A892AD7A3C2:blocked",
        baseline_fixture_sha256: "1f28e7d9fb59edec88102a9b649e3022105c4bf45f28a12a4a85c00b1912d3e6",
        overload_id: "zed.native.tensor.is-contiguous.descriptor-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn is_contiguous_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical TensorDescriptor",
        shape_rule: "all ranks including empty and singleton dimensions",
        dtype_rule: "all canonical dtypes",
        accumulation_dtype: "not applicable",
        layout_rule: "delegates TensorDescriptor::is_contiguous",
        device_rule: "descriptor-only projection",
        numeric_rule: "exact stride comparison",
        tolerance: "exact",
        determinism: "descriptor order",
        cancellation_points: "before projection",
        vjp_rule: "metadata predicate is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/is_contiguous.json",
        evidence_fixture_sha256: "1222d0f5ecc0952c25219be70b0ecccc273a59a81c739197e43558f95964f206",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8AE4F174E7A1",
        baseline_overload_id: "COMFY-TENSOR-OP-8AE4F174E7A1:blocked",
        baseline_fixture_sha256: "d4842ab544e9497c3ff8a21c806ee909a533e454b6e804a6862082c953cc73fd",
        overload_id: "zed.native.tensor.numel.descriptor-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u64"]"#,
        rust_signature: "fn numel_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<u64, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical TensorDescriptor",
        shape_rule: "checked product with scalar product one and empty dimension product zero",
        dtype_rule: "all canonical dtypes",
        accumulation_dtype: "u64 checked arithmetic",
        layout_rule: "independent of strides",
        device_rule: "descriptor-only projection",
        numeric_rule: "exact checked integer product",
        tolerance: "exact",
        determinism: "shape order",
        cancellation_points: "before projection",
        vjp_rule: "metadata value is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/numel.json",
        evidence_fixture_sha256: "2da7ba69d25c357bdad4a129454632b0113bdddf974ccffdbdef175dfcb93fcf",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8E0C873ABBAD",
        baseline_overload_id: "COMFY-TENSOR-OP-8E0C873ABBAD:blocked",
        baseline_fixture_sha256: "2740a2ee5e95585c37be9112149104fd0da475c4a5edd22abdc952ed62ded498",
        overload_id: "zed.native.tensor.pow-method.canonical-power.v1",
        ordered_parameters_json: r#"[{"name":"base","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"exponent","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn tensor_pow_with_context_exact_native(backend: &CpuBackend, base: &Tensor, exponent: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical BinaryOperation::Power",
        shape_rule: "canonical right-aligned broadcasting",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE powf including NaN infinity and signed zero",
        tolerance: "F32 power tolerance",
        determinism: "canonical binary traversal",
        cancellation_points: "canonical backend checkpoints",
        vjp_rule: "canonical analytical power VJP with broadcast reduction",
        jvp_rule: "canonical analytical power JVP",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/pow_method.json",
        evidence_fixture_sha256: "84b597ef3c1b01cb8ef5218295e03a0ae47eec44ef98f28e79cb0b811c7f80a9",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8C351B65C789",
        baseline_overload_id: "COMFY-TENSOR-OP-8C351B65C789:blocked",
        baseline_fixture_sha256: "34beb4770ba448f6b9957c414ee2b238aa7ce1b2c2611d9c818e6bd6bfba5ca6",
        overload_id: "zed.native.attention.math-sdp.explicit-selection.v1",
        ordered_parameters_json: r#"[{"name":"enabled","kind":"positional_or_keyword","type":"bool","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["MathSdpSelection"]"#,
        rust_signature: "fn comfy_model::enable_math_sdp_exact_native(enabled: bool, context: &ExecutionContext<'_>) -> Result<MathSdpSelection, AttentionError>",
        mutation_rule: "read only explicit policy construction",
        alias_rule: "canonical comfy_model attention policy projects AttentionKernelKind without process-global state",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "explicit native attention selection",
        numeric_rule: "boolean selection",
        tolerance: "exact",
        determinism: "constant mapping",
        cancellation_points: "before selection",
        vjp_rule: "configuration is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/enable_math_sdp.json",
        evidence_fixture_sha256: "53873ec40ff221b444df8bf3824c34b2da11060be844ce75284db59eeeacaeeb",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-861EE6173859",
        baseline_overload_id: "COMFY-TENSOR-OP-861EE6173859:blocked",
        baseline_fixture_sha256: "232256762d6099e976e92a7268928da63335defdb24c07db0814f1fc83ec104b",
        overload_id: "zed.native.device.cuda.current-stream.execution-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Cuda>","default":null,"keyword_only":false},{"name":"execution","kind":"positional_or_keyword","type":"ExecutionContext","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["StreamId"]"#,
        rust_signature: "fn cuda_current_stream_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, execution: &ExecutionContext<'_>) -> Result<StreamId, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical ExecutionContext stream",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "matching CUDA capability matrix and device",
        numeric_rule: "exact stream identifier",
        tolerance: "exact",
        determinism: "execution-scoped projection",
        cancellation_points: "before projection",
        vjp_rule: "runtime query is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/cuda_current_stream.json",
        evidence_fixture_sha256: "2a0e41ba92bc3ab1050c0fd99b556deab4397d1f3ad86b91867758bc3603c3a0",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-88FE050115A9",
        baseline_overload_id: "COMFY-TENSOR-OP-88FE050115A9:blocked",
        baseline_fixture_sha256: "92478239db9e588816fb9b5ac075b4d717567d98f8022ccaf27ffcf1206b34fc",
        overload_id: "zed.native.tensor.cumsum-function.canonical-scan.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"Option<DType>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn cumsum_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 53 canonical cumsum scan",
        shape_rule: "preserves shape and normalizes negative axis",
        dtype_rule: "canonical integer promotion or explicit dtype",
        accumulation_dtype: "output dtype",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "ordered prefix addition",
        tolerance: "exact dtype arithmetic",
        determinism: "row-major scan state",
        cancellation_points: "canonical scan and upload checkpoints",
        vjp_rule: "reverse cumulative sum",
        jvp_rule: "forward cumulative sum of tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/cumsum_function.json",
        evidence_fixture_sha256: "78721d854ee90a4e71736b37430ba0ae5f535c321b9b14b26e19f5a1324fe4e5",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-868F72C2BE67",
        baseline_overload_id: "COMFY-TENSOR-OP-868F72C2BE67:blocked",
        baseline_fixture_sha256: "b9aaad2c4dfe28c51d7602dc0f3962bc05e2b8a334dc0ba14b394ba971e631ce",
        overload_id: "zed.native.autocast.gpu-dtype.policy-projection.v1",
        ordered_parameters_json: r#"[{"name":"policy","kind":"positional_or_keyword","type":"AutocastPolicy","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["DType"]"#,
        rust_signature: "fn get_autocast_gpu_dtype_exact_native(policy: &AutocastPolicy, cancellation: &CancellationToken) -> Result<DType, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical AutocastPolicy",
        shape_rule: "not applicable",
        dtype_rule: "validated floating dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "execution-scoped GPU policy",
        numeric_rule: "exact enum projection",
        tolerance: "exact",
        determinism: "policy projection",
        cancellation_points: "before projection",
        vjp_rule: "configuration is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/autocast_gpu_dtype.json",
        evidence_fixture_sha256: "77a5d62d18565335a377e9d6bd1e49e8bc7b3c269849c9a245b438c0c5ba3a77",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8B5439D32B8F",
        baseline_overload_id: "COMFY-TENSOR-OP-8B5439D32B8F:blocked",
        baseline_fixture_sha256: "bd2e5c8af0214bea8e536102ee335a6e3c1de7c606d006df8704623afe53a9c7",
        overload_id: "zed.native.tensor.is-floating-point.dtype-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn is_floating_point_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical DType numeric class",
        shape_rule: "independent of shape",
        dtype_rule: "true only for canonical floating-point class",
        accumulation_dtype: "not applicable",
        layout_rule: "independent of layout",
        device_rule: "descriptor-only projection",
        numeric_rule: "exact enum classification",
        tolerance: "exact",
        determinism: "dtype projection",
        cancellation_points: "before projection",
        vjp_rule: "metadata predicate is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/is_floating_point.json",
        evidence_fixture_sha256: "6adb52853bf82673c1ebd9a7e676fc7e602d627a733148c39072280637a78791",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8E5582D70F18",
        baseline_overload_id: "COMFY-TENSOR-OP-8E5582D70F18:blocked",
        baseline_fixture_sha256: "13100740f176c20977c1f5f717d92b8e48fc8b8a0f50c4ddf2e45ea9c7ab727a",
        overload_id: "zed.native.nn.init.fan-in-out.descriptor-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["FanInAndFanOut"]"#,
        rust_signature: "fn calculate_fan_in_and_fan_out_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<FanInAndFanOut, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical TensorDescriptor shape",
        shape_rule: "rank at least two; receptive field is product of trailing dimensions",
        dtype_rule: "independent of dtype",
        accumulation_dtype: "u64 checked arithmetic",
        layout_rule: "independent of strides",
        device_rule: "descriptor-only projection",
        numeric_rule: "fan_in=shape[1]*receptive and fan_out=shape[0]*receptive",
        tolerance: "exact",
        determinism: "shape order",
        cancellation_points: "before projection",
        vjp_rule: "initialization metadata is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/fan_in_out.json",
        evidence_fixture_sha256: "9557dd993114b2906817cf16edde1f2222b50a7a03dd8bf7335aaf7359d16b1d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8C29B75AEA2A",
        baseline_overload_id: "COMFY-TENSOR-OP-8C29B75AEA2A:blocked",
        baseline_fixture_sha256: "7226344fedacbaf0a00cca0724e6d6449acd3db19446353b0ac25848b0754801",
        overload_id: "zed.native.tensor.stft.f32-complex64.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"n_fft","kind":"positional_or_keyword","type":"usize","default":null,"keyword_only":false},{"name":"hop_length","kind":"keyword_only","type":"Option<usize>","default":null,"keyword_only":true},{"name":"win_length","kind":"keyword_only","type":"Option<usize>","default":null,"keyword_only":true},{"name":"window","kind":"keyword_only","type":"Option<Tensor<F32>>","default":null,"keyword_only":true},{"name":"center","kind":"keyword_only","type":"bool","default":true,"keyword_only":true},{"name":"normalized","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"onesided","kind":"keyword_only","type":"bool","default":true,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<Complex64>"]"#,
        rust_signature: "fn stft_with_context_exact_native(backend: &CpuBackend, input: &Tensor, n_fft: usize, hop_length: Option<usize>, win_length: Option<usize>, window: Option<&Tensor>, center: bool, normalized: bool, onesided: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh complex storage using canonical Tensor upload",
        shape_rule: "one- or two-dimensional waveform to frequency by frame output",
        dtype_rule: "F32 input and window to Complex64 output",
        accumulation_dtype: "F32 complex",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "reflect-centered windowed FFT with exact onesided and normalization rules",
        tolerance: "relative 1e-5 absolute 1e-5",
        determinism: "radix-two FFT or ordered DFT fallback",
        cancellation_points: "bounded frame sample FFT and upload checkpoints",
        vjp_rule: "analytical overlap-add adjoint including reflected padding",
        jvp_rule: "STFT of the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/stft.json",
        evidence_fixture_sha256: "1858ac9c547743da225a43eac68598131ded91102aff3f8c3d7a36e561033e30",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8DF974B2A77C",
        baseline_overload_id: "COMFY-TENSOR-OP-8DF974B2A77C:blocked",
        baseline_fixture_sha256: "29e0a8f18e5aa0d46c856cb3b30ceef2ec71cae150bb1bc7201d89fbb3516ee5",
        overload_id: "zed.native.tensor.topk.f32-deterministic.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"k","kind":"positional_or_keyword","type":"usize","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":-1,"keyword_only":true},{"name":"largest","kind":"keyword_only","type":"bool","default":true,"keyword_only":true},{"name":"sorted","kind":"keyword_only","type":"bool","default":true,"keyword_only":true}]"#,
        output_arity: "2",
        output_types_json: r#"["Tensor<F32>","Tensor<I64>"]"#,
        rust_signature: "fn topk_with_context_exact_native(backend: &CpuBackend, input: &Tensor, k: usize, dimension: i64, largest: bool, sorted: bool, context: &ExecutionContext<'_>) -> Result<TopKResult, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh values and indices storage",
        shape_rule: "selected dimension becomes k with checked negative axis",
        dtype_rule: "F32 values and I64 indices",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous outputs",
        device_rule: "CPU ordinal zero",
        numeric_rule: "NaN-first largest ordering and stable lower-index ties",
        tolerance: "exact selected values",
        determinism: "total ordering and stable tie index",
        cancellation_points: "bounded slice selection and upload checkpoints",
        vjp_rule: "scatter output gradients to selected input coordinates",
        jvp_rule: "gather input tangents at selected coordinates",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/topk.json",
        evidence_fixture_sha256: "8b258b01f7f366407032762f9052fffe762f43b3cb86a3c68fe8e3de3f357638",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-874C83BCB8C5",
        baseline_overload_id: "COMFY-TENSOR-OP-874C83BCB8C5:blocked",
        baseline_fixture_sha256: "a44ef736e9b4fd98d49697a975aac5b0c3b801c7c410b6667e303497f9bdbfc7",
        overload_id: "zed.native.tensor.tril.canonical-triangular-mask.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"diagonal","kind":"positional_or_keyword","type":"isize","default":0,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tril_with_context_exact_native(backend: &CpuBackend, input: &Tensor, diagonal: isize, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical triangular-mask traversal shared with triu",
        shape_rule: "rank at least two and preserves shape",
        dtype_rule: "canonical zero encoding for input dtype",
        accumulation_dtype: "input dtype",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "retain column-row less than or equal to diagonal",
        tolerance: "exact",
        determinism: "row-major logical traversal",
        cancellation_points: "canonical triangular mask and upload checkpoints",
        vjp_rule: "apply identical lower-triangular mask to output gradient",
        jvp_rule: "apply identical lower-triangular mask to input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/tril.json",
        evidence_fixture_sha256: "a84a6a9c7ee242e47705ddcf05173112e1f03540846767b94289ef84c3d3b52f",
    },
]
