&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C579143F7B56",
        baseline_overload_id: "COMFY-TENSOR-OP-C579143F7B56:blocked",
        baseline_fixture_sha256: "b9bbb7497f0581dae09ce737a5f7adec2d6d9f04adf4cbf9cda2dde5585bd0df",
        overload_id: "zed.native.tensor.byte-tensor.canonical-u8-constructor.v1",
        ordered_parameters_json: r#"[{"name":"values","kind":"positional_or_keyword","type":"&[u8]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<U8>"]"#,
        rust_signature: "fn byte_tensor_with_context_exact_native(backend: &CpuBackend, values: &[u8], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates the canonical tensor constructor",
        shape_rule: "one-dimensional length equal to values",
        dtype_rule: "U8",
        accumulation_dtype: "not applicable",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero on the caller-owned context stream",
        numeric_rule: "each byte is preserved exactly",
        tolerance: "bit exact",
        determinism: "input order",
        cancellation_points: "before allocation, during bounded value conversion, and during canonical upload",
        vjp_rule: "integer constructor is not differentiable",
        jvp_rule: "integer constructor is not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/byte_tensor.json",
        evidence_fixture_sha256: "3abe2bec9c8bb13f535c3411a0731d5313eda45dfbb85118c1b8f6cdafcf6b77",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C83ECA429710",
        baseline_overload_id: "COMFY-TENSOR-OP-C83ECA429710:blocked",
        baseline_fixture_sha256: "43d84f57220abbe62d819717215dea3b160ddf12e24e15567e6c48bd609d6b6a",
        overload_id: "zed.native.tensor.element-size.dtype-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"&Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u64"]"#,
        rust_signature: "fn element_size_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<u64, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "read only",
        alias_rule: "scalar projection",
        shape_rule: "independent of shape",
        dtype_rule: "canonical DType byte width",
        accumulation_dtype: "u64",
        layout_rule: "independent of layout",
        device_rule: "independent of device",
        numeric_rule: "exact byte width",
        tolerance: "exact",
        determinism: "immutable descriptor projection",
        cancellation_points: "before projection",
        vjp_rule: "metadata query is not differentiable",
        jvp_rule: "metadata query is not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/element_size.json",
        evidence_fixture_sha256: "c6860a08da2e4bffca9027b48e0643762bbc406ad237d9fbe7f2ada835a222d0",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C1FAC5999B98",
        baseline_overload_id: "COMFY-TENSOR-OP-C1FAC5999B98:blocked",
        baseline_fixture_sha256: "0c4ec39c7742191e24ad8c1cb5179439c934664ae01641951ccb8337e42aac47",
        overload_id: "zed.native.tensor.sub-method.canonical-add-adapter-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>|Scalar","default":null,"keyword_only":false},{"name":"alpha","kind":"keyword_only","type":"f32","default":1.0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sub_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, alpha: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical add and binary primitive owners with negated alpha",
        shape_rule: "canonical broadcast shape",
        dtype_rule: "source F32 profile",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "input minus alpha times other",
        tolerance: "1e-6 absolute",
        determinism: "canonical binary traversal",
        cancellation_points: "before validation and at canonical primitive checkpoints",
        vjp_rule: "input gradient one and other gradient negative alpha with broadcast reduction",
        jvp_rule: "input tangent minus alpha times other tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/sub_method.json",
        evidence_fixture_sha256: "a84ce01acfb801bf09cf12521a5a298acf4ba063d9fac9e501c011cfad89eb6e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C575200CD790",
        baseline_overload_id: "COMFY-TENSOR-OP-C575200CD790:blocked",
        baseline_fixture_sha256: "4a97837b55045c54006433377c08d5ff2bc1861703a90e1215bafe50bdc69b60",
        overload_id: "zed.native.tensor.add.scalar-tensor-source-overload-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"f32","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"alpha","kind":"keyword_only","type":"f32","default":1.0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn add_scalar_tensor_with_context_exact_native(backend: &CpuBackend, input: f32, other: &Tensor, alpha: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical primitive output",
        shape_rule: "preserves tensor shape",
        dtype_rule: "source F32 profile",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero and tensor stream",
        numeric_rule: "input plus alpha times other",
        tolerance: "1e-6 absolute",
        determinism: "canonical multiply then add primitives",
        cancellation_points: "before validation and at canonical primitive checkpoints",
        vjp_rule: "tensor gradient is alpha times output gradient",
        jvp_rule: "alpha times tensor tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/add.json",
        evidence_fixture_sha256: "d31cb5012dc1a30169e25daeb71a1b97d69ac3cd8426af793d813b32c8d21119",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C7A255E21877",
        baseline_overload_id: "COMFY-TENSOR-OP-C7A255E21877:blocked",
        baseline_fixture_sha256: "25111b76932da29f374c2e7f69e58d640b952d5edb51d757b6da422c0556c2ac",
        overload_id: "zed.native.tensor.bincount.unweighted-integer-source-overload.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<Integer>","default":null,"keyword_only":false},{"name":"minlength","kind":"keyword_only","type":"u64","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn bincount_with_context_exact_native(backend: &CpuBackend, input: &Tensor, minlength: u64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh count storage",
        shape_rule: "one-dimensional max(max(input)+1,minlength)",
        dtype_rule: "integer input and I64 output",
        accumulation_dtype: "checked I64 counts",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "nonnegative exact histogram",
        tolerance: "exact",
        determinism: "input order with checked counters",
        cancellation_points: "before validation and at bounded input, initialization, accumulation, and upload intervals",
        vjp_rule: "integer histogram is not differentiable",
        jvp_rule: "integer histogram is not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/bincount.json",
        evidence_fixture_sha256: "6fec6a34484202c2a7d6daaf099c56df3a1f06e6d68c06ce54d5faf0388366b6",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C7B72CD0ABE7",
        baseline_overload_id: "COMFY-TENSOR-OP-C7B72CD0ABE7:blocked",
        baseline_fixture_sha256: "2ef50c3c87d68e2ac6d731357728005faf78aad213a15df4d30d1f352bd39e5f",
        overload_id: "zed.native.tensor.bucketize.sorted-boundaries-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"boundaries","kind":"positional_or_keyword","type":"Tensor<F32,rank=1>","default":null,"keyword_only":false},{"name":"right","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"out_int32","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64|I32>"]"#,
        rust_signature: "fn bucketize_with_context_exact_native(backend: &CpuBackend, input: &Tensor, boundaries: &Tensor, right: bool, out_int32: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh index storage",
        shape_rule: "preserves input shape",
        dtype_rule: "F32 input and boundaries; I64 default or I32 requested output",
        accumulation_dtype: "usize search index checked into output dtype",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "lower-bound when right is false and upper-bound when true; NaN maps after all boundaries",
        tolerance: "exact",
        determinism: "sorted binary partition",
        cancellation_points: "before validation and at bounded boundary, input, and upload intervals",
        vjp_rule: "discrete search is not differentiable",
        jvp_rule: "discrete search is not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/bucketize.json",
        evidence_fixture_sha256: "19fea32714ce58d54499e96dc290aba64e78f0bb530f5dfebfc7d22401cc3f9a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C0D4EF19ED71",
        baseline_overload_id: "COMFY-TENSOR-OP-C0D4EF19ED71:blocked",
        baseline_fixture_sha256: "34a4bf821e59971c73ad058a419b7f9f897c729bbe7adb412c8429b7ee02ab82",
        overload_id: "zed.native.runtime.compiler-is-compiling.compile-phase-projection.v1",
        ordered_parameters_json: r#"[{"name":"phase","kind":"positional_or_keyword","type":"NativeCompilePhase","default":"eager","keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn comfy_runtime::compiler_is_compiling_exact_native(phase: NativeCompilePhase, cancellation: &CancellationToken) -> Result<bool, NativeCompileError>",
        mutation_rule: "read only",
        alias_rule: "copyable boolean projection",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "native compile owner independent of device",
        numeric_rule: "true only during native graph capture",
        tolerance: "exact",
        determinism: "explicit compile phase",
        cancellation_points: "before projection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/compiler_is_compiling.json",
        evidence_fixture_sha256: "501dcd2dab7997d27f03c508d00c46249827d6c8a936929dce7c81dd3b86d442",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C64E630A756E",
        baseline_overload_id: "COMFY-TENSOR-OP-C64E630A756E:blocked",
        baseline_fixture_sha256: "eb5f4914af0f987e1cb38a1f944dca0cef36e502ea05f24eae0a16139de40278",
        overload_id: "zed.native.tensor.is-autocast-enabled.policy-projection.v1",
        ordered_parameters_json: r#"[{"name":"policy","kind":"positional_or_keyword","type":"&AutocastPolicy","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn is_autocast_enabled_exact_native(policy: &AutocastPolicy, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "read only",
        alias_rule: "copyable boolean projection",
        shape_rule: "not applicable",
        dtype_rule: "canonical policy validates floating dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "explicit policy scope",
        numeric_rule: "exact enabled flag",
        tolerance: "exact",
        determinism: "immutable policy",
        cancellation_points: "before projection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/is_autocast_enabled.json",
        evidence_fixture_sha256: "6e8fe940d8ca95f46a288a2320640b7a34051c26e8e0819c4d72c16c625f21c6",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C63B343CD3EF",
        baseline_overload_id: "COMFY-TENSOR-OP-C63B343CD3EF:blocked",
        baseline_fixture_sha256: "90778fec24232cb4e883fbd81d77a56975628a18ea2a4666df1615dcf9d62bc4",
        overload_id: "zed.native.tensor.library-custom-op.kernel-declaration-adapter.v1",
        ordered_parameters_json: r#"[{"name":"qualified_name","kind":"positional_or_keyword","type":"&str","default":null,"keyword_only":false},{"name":"mutates_arguments","kind":"keyword_only","type":"&[usize]","default":"[]","keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeCustomOperatorDeclaration"]"#,
        rust_signature: "fn library_custom_op_exact_native(qualified_name: &str, mutates_arguments: &[usize], cancellation: &CancellationToken) -> Result<NativeCustomOperatorDeclaration, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "constructs an immutable declaration only",
        alias_rule: "maps explicitly to canonical CustomKernelId execution identity",
        shape_rule: "not applicable until declared kernel invocation",
        dtype_rule: "not applicable until declared kernel invocation",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable until declared kernel invocation",
        device_rule: "backend dispatch remains owned by TensorBackend",
        numeric_rule: "valid namespace::identifier and unique mutation indices",
        tolerance: "exact",
        determinism: "canonical name mapping and caller order",
        cancellation_points: "before validation and publication",
        vjp_rule: "kernel declaration carries no gradient; the bound kernel owns maps",
        jvp_rule: "kernel declaration carries no tangent; the bound kernel owns maps",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/library_custom_op.json",
        evidence_fixture_sha256: "4f7ded619664bcb732d0d8bdafbe79b016fefb3e50e919b3f0532d9b69c1913a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C46EB25624FB",
        baseline_overload_id: "COMFY-TENSOR-OP-C46EB25624FB:blocked",
        baseline_fixture_sha256: "db4344cca7b87d51d8ab4dd8eab1a1e9b4ec8ed16ecdec1023bd6ccc4e4a5440",
        overload_id: "zed.native.tensor.log-softmax.stable-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn log_softmax_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage after canonical functional delegation",
        shape_rule: "preserves shape along normalized dimension",
        dtype_rule: "source F32 profile",
        accumulation_dtype: "F64 exponential sum projected to F32",
        layout_rule: "contiguous output from logical input traversal",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "stable max-shift log-sum-exp",
        tolerance: "1e-6 absolute",
        determinism: "canonical activation owner fixed outer-axis-inner traversal",
        cancellation_points: "before validation, during logical storage projection and canonical axis traversal, and before atomic upload",
        vjp_rule: "gradient minus softmax(output) times axis gradient sum",
        jvp_rule: "tangent minus the axis sum of softmax(output) times tangent, broadcast across the axis",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/log_softmax.json",
        evidence_fixture_sha256: "ec1f98ef1fdc0d1e15f307bd03dfa1eb2989d25c45908e3608768be4ecc0368c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C1BBE55AA3A0",
        baseline_overload_id: "COMFY-TENSOR-OP-C1BBE55AA3A0:blocked",
        baseline_fixture_sha256: "3b3216bb76646bd91a644beef8fa560174c4bcff4065fa3bb6586c9b630cdcd5",
        overload_id: "zed.native.tensor.numel-function.canonical-descriptor-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"&Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u64"]"#,
        rust_signature: "fn numel_function_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<u64, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "read only",
        alias_rule: "delegates Task 12 canonical descriptor projection",
        shape_rule: "checked product with scalar rank equal to one element and any zero dimension equal to zero",
        dtype_rule: "independent of dtype",
        accumulation_dtype: "checked u64",
        layout_rule: "logical shape independent of storage layout",
        device_rule: "independent of device",
        numeric_rule: "exact checked product",
        tolerance: "exact",
        determinism: "immutable descriptor",
        cancellation_points: "before delegation and at the canonical numel checkpoint",
        vjp_rule: "metadata query is not differentiable",
        jvp_rule: "metadata query is not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/numel.json",
        evidence_fixture_sha256: "bd33f25e9c9d8d80e57d02f04f36e1a50a53f48c93e73ac93947bd6c7a8f4121",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C05FE0730305",
        baseline_overload_id: "COMFY-TENSOR-OP-C05FE0730305:blocked",
        baseline_fixture_sha256: "7598d7c3566e956dba126907371c8a194b22c3c2dc5a436aa6b45f8f24cfe722",
        overload_id: "zed.native.tensor.xpu-stream.canonical-stream-registry.v1",
        ordered_parameters_json: r#"[{"name":"registry","kind":"positional_or_keyword","type":"&NativeStreamRegistry","default":null,"keyword_only":false},{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"keyword_only","type":"DeviceId<Xpu>","default":null,"keyword_only":true},{"name":"priority","kind":"keyword_only","type":"i32","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeStream"]"#,
        rust_signature: "fn xpu_stream_exact_native(registry: &NativeStreamRegistry, capabilities: &BackendCapabilityMatrix, device: DeviceId, priority: i32, cancellation: &CancellationToken) -> Result<NativeStream, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "atomically allocates one non-default stream identity",
        alias_rule: "owned immutable stream descriptor",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 identity sequence",
        layout_rule: "not applicable",
        device_rule: "exact XPU device matching canonical capability matrix",
        numeric_rule: "preserves signed priority and unique monotonically allocated identity",
        tolerance: "exact",
        determinism: "registry allocation order",
        cancellation_points: "before device validation and atomic allocation",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/xpu_stream.json",
        evidence_fixture_sha256: "ad03daa358ef67e5bd21481a1cec6252fb1a9b23b8a0f752bcb001354bee155b",
    },
]
