&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-365E27719CFD",
        baseline_overload_id: "COMFY-TENSOR-OP-365E27719CFD:blocked",
        baseline_fixture_sha256: "5b74f3c6ba39012c1be5633bf1a69c276fed3c3fe8484043a2f52712c8d24952",
        overload_id: "zed.native.tensor.div-method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"f32 Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"f32 Tensor or Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn div_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "canonical right-aligned broadcasting",
        dtype_rule: "certified CPU profile accepts f32 and checked f32 scalars",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero with exact stream agreement",
        numeric_rule: "IEEE division including signed zero, infinity, and NaN",
        tolerance: "exact f32 primitive result",
        determinism: "canonical broadcast traversal",
        cancellation_points: "before validation, during primitive traversal, and before publication",
        vjp_rule: "input gradient is grad divided by other; tensor-other gradient is negative grad times input divided by other squared with broadcast reduction",
        jvp_rule: "the same checked quotient differential",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/div.json",
        evidence_fixture_sha256: "c21f66080f88b0f26ed228aeb47fb71df6ddbfe464abcfd858a0601d7dee84fb",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-3D0519DB53BD",
        baseline_overload_id: "COMFY-TENSOR-OP-3D0519DB53BD:blocked",
        baseline_fixture_sha256: "1683a370d7c062c75b5bef14a07b566934ed3c08e482bf06c7ff82d0a719177c",
        overload_id: "zed.native.tensor.item.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"single-element Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"DecodedScalar\"]",
        rust_signature: "fn item_with_context_exact_native(input: &Tensor, context: &ExecutionContext<'_>) -> Result<DecodedScalar, ElementwiseRuntimePartFiveError>",
        mutation_rule: "read only",
        alias_rule: "returns a copyable decoded scalar",
        shape_rule: "requires exactly one logical element at any rank",
        dtype_rule: "canonical DType codec owns scalar decoding",
        accumulation_dtype: "none",
        layout_rule: "logical element access supports canonical views",
        device_rule: "host-readable CPU ordinal zero",
        numeric_rule: "preserves boolean, signed, unsigned, real, and complex scalar classes",
        tolerance: "exact codec result",
        determinism: "single logical read",
        cancellation_points: "before validation and after decoding",
        vjp_rule: "scalar extraction is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/item.json",
        evidence_fixture_sha256: "24c807e5f7e7d9ede82f0c1aab70b776c3fe125fdcdc55f6773e6f5b63482345",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-332E7E59DC10",
        baseline_overload_id: "COMFY-TENSOR-OP-332E7E59DC10:blocked",
        baseline_fixture_sha256: "38ebfa18154897801ae929957560dae8f657d43c02239b4f7d380f193d31a4d3",
        overload_id: "zed.native.tensor.sin-method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"f32 Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn sin_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "certified CPU profile accepts f32",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical native sine primitive",
        tolerance: "platform f32 transcendental tolerance",
        determinism: "fixed logical traversal",
        cancellation_points: "canonical unary primitive checkpoints",
        vjp_rule: "output gradient multiplied by cosine of input",
        jvp_rule: "input tangent multiplied by cosine of input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/sin.json",
        evidence_fixture_sha256: "ac6d643f70dbfeb35f0b460398be13fdbdd291918d16a52cf6b32fa8a94b24df",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-3D09997B7D21",
        baseline_overload_id: "COMFY-TENSOR-OP-3D09997B7D21:blocked",
        baseline_fixture_sha256: "b1019255b6f54176ce58c1f189184f2e65d7c4a114e862a65d69a1b951e77ea9",
        overload_id: "zed.native.tensor.sqrt-method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"f32 Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn sqrt_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "certified CPU profile accepts f32",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE square root with negative inputs producing NaN",
        tolerance: "platform f32 transcendental tolerance",
        determinism: "fixed logical traversal",
        cancellation_points: "canonical unary primitive checkpoints",
        vjp_rule: "output gradient divided by two times square root of input",
        jvp_rule: "input tangent divided by two times square root of input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/sqrt.json",
        evidence_fixture_sha256: "b3ab80e44f907d70b0e06be7a925e37f4d9df8a34028f32d098b683758fe04cf",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-33CCFBAAA7B3",
        baseline_overload_id: "COMFY-TENSOR-OP-33CCFBAAA7B3:blocked",
        baseline_fixture_sha256: "4e4e09b218ba70bc302e97f1e96e36a4ebad7a0a3b64ed6ff535893e64b85f60",
        overload_id: "zed.native.tensor.zero-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"unit\"]",
        rust_signature: "fn zero_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartFiveError>",
        mutation_rule: "stages a complete canonical fill before one receiver publication",
        alias_rule: "preserves the receiver through canonical copy-on-write mutation",
        shape_rule: "shape unchanged including zero-sized tensors",
        dtype_rule: "zero is checked by the canonical DType codec",
        accumulation_dtype: "none",
        layout_rule: "descriptor and logical layout preserved",
        device_rule: "CPU ordinal zero",
        numeric_rule: "every logical value becomes exact encoded zero",
        tolerance: "exact bytes",
        determinism: "canonical fill traversal",
        cancellation_points: "before validation, during staged fill, and before publication",
        vjp_rule: "terminal mutation has no VJP",
        jvp_rule: "terminal mutation does not propagate tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/zero_in_place.json",
        evidence_fixture_sha256: "1731b25385f692e5ffcbfaad5405c832cc8cffb27a883e96c2c3eb6f3a47bdee",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-384A8C6954B8",
        baseline_overload_id: "COMFY-TENSOR-OP-384A8C6954B8:blocked",
        baseline_fixture_sha256: "64d7ada81191d4537b95a5486b8ebfa3471f7cbba0c2cec3711f690ebd412b6a",
        overload_id: "zed.native.tensor.bitwise-left-shift.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"integer Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"integer Tensor or u32 Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<integer>\"]",
        rust_signature: "fn bitwise_left_shift_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: BitwiseShiftOperand<'_>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "canonical right-aligned broadcasting",
        dtype_rule: "input integer dtype is preserved; shift operands must be integers",
        accumulation_dtype: "u128 bit pattern bounded to the input width",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "two's-complement fixed-width shift; negative or out-of-width shifts fail typed",
        tolerance: "exact bits",
        determinism: "fixed broadcast traversal",
        cancellation_points: "before validation, at bounded traversal intervals, and before upload publication",
        vjp_rule: "integer operation is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/bitwise_left_shift.json",
        evidence_fixture_sha256: "a8c8fd0c3d48f2e2e9badd2db8a37737ba6376d19d3ee1bdb4345ae4836fc8ba",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-3ADC7A3998E4",
        baseline_overload_id: "COMFY-TENSOR-OP-3ADC7A3998E4:blocked",
        baseline_fixture_sha256: "0eb827217d79803bb76cfbec8ae38c56062f58f1c974fe7910c6da78641891a9",
        overload_id: "zed.native.tensor.count-nonzero.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<i64>\"]",
        rust_signature: "fn count_nonzero_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "read only with a fresh scalar output",
        alias_rule: "output owns canonical scalar storage",
        shape_rule: "returns a rank-zero tensor",
        dtype_rule: "all canonical decoded scalar classes are accepted; output is i64",
        accumulation_dtype: "checked u64 converted to i64",
        layout_rule: "logical input traversal and contiguous scalar output",
        device_rule: "host-readable CPU ordinal zero",
        numeric_rule: "NaN is nonzero; complex is nonzero when either component differs from zero",
        tolerance: "exact count",
        determinism: "fixed logical traversal",
        cancellation_points: "before validation, at bounded traversal intervals, and during scalar publication",
        vjp_rule: "counting predicate is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/count_nonzero.json",
        evidence_fixture_sha256: "fb0717d0552604a3470fea6f6354b0fa8ba0592071889fb55bf7055decbcf379",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-40FEFA2DEAC6",
        baseline_overload_id: "COMFY-TENSOR-OP-40FEFA2DEAC6:blocked",
        baseline_fixture_sha256: "8fdfd999603dfe185bfbecddb3057753548f4ece141f9e0ad4adad4b48092dd8",
        overload_id: "zed.native.allocator.cuda-backend-name.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"owner\",\"type\":\"CachedAllocationOwner\"}]",
        output_arity: "1",
        output_types_json: "[\"static string\"]",
        rust_signature: "fn cuda_get_allocator_backend_exact_native(owner: &dyn CachedAllocationOwner, cancellation: &CancellationToken) -> Result<&'static str, ElementwiseRuntimePartFiveError>",
        mutation_rule: "read-only owner projection",
        alias_rule: "returns the authoritative static backend identifier",
        shape_rule: "not applicable",
        dtype_rule: "UTF-8 identifier bounded to 128 non-NUL bytes",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "CUDA or ROCm allocator owners only",
        numeric_rule: "not applicable",
        tolerance: "exact string",
        determinism: "fixed owner projection",
        cancellation_points: "before owner validation and after projection",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/cuda_get_allocator_backend.json",
        evidence_fixture_sha256: "2ede7e9896e07e85c7ef07cc33ca535ba2cd4a8fba1dab6881abe200aa888282",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-3A3C79159CBC",
        baseline_overload_id: "COMFY-TENSOR-OP-3A3C79159CBC:blocked",
        baseline_fixture_sha256: "afd5f6b68ade1e6c52dd0e44a82cb4f396dac9eb409b933571e8aa91783b109d",
        overload_id: "zed.native.device.cuda-select-capabilities.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"available\",\"type\":\"BackendCapabilityMatrix slice\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"DeviceId\"}]",
        output_arity: "1",
        output_types_json: "[\"borrowed BackendCapabilityMatrix\"]",
        rust_signature: "fn cuda_set_device_exact_native<'a>(available: &'a [BackendCapabilityMatrix], device: DeviceId, cancellation: &CancellationToken) -> Result<&'a BackendCapabilityMatrix, ElementwiseRuntimePartFiveError>",
        mutation_rule: "functional selection with no process-global mutable state",
        alias_rule: "borrows the exact canonical capability matrix",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "exact configured CUDA or ROCm DeviceId must exist",
        numeric_rule: "ordinal comparison is exact",
        tolerance: "exact identity",
        determinism: "first and only canonical matrix match",
        cancellation_points: "before lookup and after selection",
        vjp_rule: "device selection is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/cuda_set_device.json",
        evidence_fixture_sha256: "622581fd91db39729565bf986d8d1abeef2dcf1696324cbe2e52243ed0476dac",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-388D285AB0F7",
        baseline_overload_id: "COMFY-TENSOR-OP-388D285AB0F7:blocked",
        baseline_fixture_sha256: "1320a544f5f94b8b988ef405a20d8817f5b073cbe6a65441be7e34482549e213",
        overload_id: "zed.native.tensor.minimum.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"f32 Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"f32 Tensor or Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<f32>\"]",
        rust_signature: "fn minimum_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFiveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "canonical right-aligned broadcasting",
        dtype_rule: "certified CPU profile accepts f32 and checked f32 scalars",
        accumulation_dtype: "f32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero with exact stream agreement",
        numeric_rule: "smaller value wins and either NaN propagates",
        tolerance: "exact f32 comparisons",
        determinism: "fixed broadcast traversal",
        cancellation_points: "before validation, during primitive traversal, and before publication",
        vjp_rule: "gradient routes to the smaller operand and splits equally at ties with broadcast reduction",
        jvp_rule: "tangent routes by the same smaller-or-tie mask",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/minimum.json",
        evidence_fixture_sha256: "89e80b6e3d5a3d5f275f4bc2e5eaa02bedef1c0c03344b205c0ad29efeeebda8",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-37266D0A196F",
        baseline_overload_id: "COMFY-TENSOR-OP-37266D0A196F:blocked",
        baseline_fixture_sha256: "b0fabcda26daf2d5eb981fd00fc22fc6f9b4918e605a0d957f0dd77ab278784f",
        overload_id: "zed.native.tensor.constant-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"value\",\"type\":\"Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"unit\"]",
        rust_signature: "fn constant_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, value: Scalar, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartFiveError>",
        mutation_rule: "stages a complete canonical fill before one receiver publication",
        alias_rule: "preserves the receiver through canonical copy-on-write mutation",
        shape_rule: "shape unchanged including zero-sized tensors",
        dtype_rule: "value is checked by the canonical DType codec",
        accumulation_dtype: "none",
        layout_rule: "descriptor and logical layout preserved",
        device_rule: "CPU ordinal zero",
        numeric_rule: "every logical value becomes the exact encoded constant",
        tolerance: "exact canonical encoding",
        determinism: "canonical fill traversal",
        cancellation_points: "before validation, during staged fill, and before publication",
        vjp_rule: "initializer mutation has no VJP",
        jvp_rule: "initializer does not propagate tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/constant_in_place.json",
        evidence_fixture_sha256: "72e9f25291d91c7de5933dbef4486e8657ec2a08a05bb509a5aba70d91e77b18",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_05",
        operation_id: "COMFY-TENSOR-OP-3A641CA3FC0F",
        baseline_overload_id: "COMFY-TENSOR-OP-3A641CA3FC0F:blocked",
        baseline_fixture_sha256: "f3d05f3584554047967f0da77fbf93fd5012e2ec1138ef519846c3c64fe24969",
        overload_id: "zed.native.device.xpu-name.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"capabilities\",\"type\":\"BackendCapabilityMatrix\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"device\",\"type\":\"DeviceId\"}]",
        output_arity: "1",
        output_types_json: "[\"String\"]",
        rust_signature: "fn xpu_get_device_name_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<String, ElementwiseRuntimePartFiveError>",
        mutation_rule: "read-only canonical property projection",
        alias_rule: "returns an owned boundary string",
        shape_rule: "not applicable",
        dtype_rule: "validated UTF-8 device property",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "exact XPU DeviceId and capability matrix agreement",
        numeric_rule: "not applicable",
        tolerance: "exact string",
        determinism: "fixed property projection",
        cancellation_points: "before validation and after copying the name",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-332e7e59dc10",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_05/xpu_get_device_name.json",
        evidence_fixture_sha256: "196d55e292faa41ba6805377d94b50e044d15d24e7b60fbdffe37375cdb12fd2",
    },
]
