&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6A39A98E4F68",
        baseline_overload_id: "COMFY-TENSOR-OP-6A39A98E4F68:blocked",
        baseline_fixture_sha256: "c9197e1a28bbfb3af90e2fbfc88ce5faf9b49f917ed6ede8428d157976815f66",
        overload_id: "sim.native.tensor.constructor.cpu.v1",
        ordered_parameters_json: r#"[{"name":"values","kind":"positional_or_keyword","type":"slice<Scalar>","default":null,"keyword_only":false},{"name":"shape","kind":"positional_or_keyword","type":"slice<u64>","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"DType","default":"F32","keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_constructor_with_context_exact_native(backend: &CpuBackend, values: &[Scalar], shape: &[u64], dtype: DType, stream: StreamId, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical backend storage",
        shape_rule: "value count exactly equals checked shape product",
        dtype_rule: "canonical checked scalar codec",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "checked dtype conversion",
        tolerance: "bit exact",
        determinism: "input order",
        cancellation_points: "before and during scalar encoding and upload",
        vjp_rule: "leaf constructor boundary",
        jvp_rule: "leaf constructor boundary",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/tensor_constructor.json",
        evidence_fixture_sha256: "301d140c4aaf12bcd5ca4f5c8520432e9828799f5df045896828857f643dd0cc",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-616CB031A549",
        baseline_overload_id: "COMFY-TENSOR-OP-616CB031A549:blocked",
        baseline_fixture_sha256: "ca85ba4ee079724bbe898ca11e991a47f1b1fecb09be056b0c3cdfaa50da5385",
        overload_id: "sim.native.tensor.bitwise-xor.cpu.v1",
        ordered_parameters_json: r#"[{"name":"left","kind":"positional_or_keyword","type":"Tensor<integer or bool>","default":null,"keyword_only":false},{"name":"right","kind":"positional_or_keyword","type":"Tensor<same dtype>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn bitwise_xor_with_context_exact_native(backend: &CpuBackend, left: &Tensor, right: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "NumPy trailing-dimension broadcast",
        dtype_rule: "matching bool or integer dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous",
        device_rule: "co-located CPU stream",
        numeric_rule: "width-preserving XOR",
        tolerance: "bit exact",
        determinism: "row-major broadcast traversal",
        cancellation_points: "bounded element intervals and upload",
        vjp_rule: "non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/bitwise_xor.json",
        evidence_fixture_sha256: "092f4f0edae07f760549e65834c74ed3e2668311b7c7599262515368b2aec583",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-67B5EDD39C41",
        baseline_overload_id: "COMFY-TENSOR-OP-67B5EDD39C41:blocked",
        baseline_fixture_sha256: "44bc8656b6785c64d15143d3c0a4f7c742980c2d7fbd0e64bd461da7aaf99bff",
        overload_id: "sim.native.tensor.clamp.adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"minimum","kind":"keyword_only","type":"Option<Scalar>","default":null,"keyword_only":true},{"name":"maximum","kind":"keyword_only","type":"Option<Scalar>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn clamp_with_context_exact_native(backend: &CpuBackend, input: &Tensor, minimum: Option<Scalar>, maximum: Option<Scalar>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place through canonical copy-on-write clamp",
        alias_rule: "canonical storage clone detaches before write",
        shape_rule: "preserves shape",
        dtype_rule: "preserves supported dtype",
        accumulation_dtype: "input dtype",
        layout_rule: "preserves descriptor",
        device_rule: "canonical clamp owner",
        numeric_rule: "inclusive finite bounds with canonical NaN behavior",
        tolerance: "canonical scalar codec",
        determinism: "canonical staged traversal",
        cancellation_points: "canonical clamp checkpoints",
        vjp_rule: "upstream within unclipped interval",
        jvp_rule: "input tangent within unclipped interval",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/clamp.json",
        evidence_fixture_sha256: "d3f9ae011cdb7100b3fec3d52ab2b16b7ec4dc2683c3bfb1d93076da2525bcd5",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6A4C6EDFC695",
        baseline_overload_id: "COMFY-TENSOR-OP-6A4C6EDFC695:blocked",
        baseline_fixture_sha256: "9201bc9140a7406867c9d8a5d1ca501670ca687ca33f9c4e0bcaa654ffa58068",
        overload_id: "sim.native.tensor.frombuffer.owned-cpu.v1",
        ordered_parameters_json: r#"[{"name":"source","kind":"positional_or_keyword","type":"slice<u8>","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"DType","default":null,"keyword_only":true},{"name":"count","kind":"keyword_only","type":"Option<usize>","default":null,"keyword_only":true},{"name":"offset","kind":"keyword_only","type":"usize","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn frombuffer_with_context_exact_native(backend: &CpuBackend, source: &[u8], dtype: DType, count: Option<usize>, offset: usize, stream: StreamId, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "owned canonical snapshot because borrowed Rust slices cannot outlive the call",
        shape_rule: "one-dimensional checked element count",
        dtype_rule: "caller-selected canonical dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "native-endian exact byte interpretation",
        tolerance: "bit exact",
        determinism: "source byte order",
        cancellation_points: "before validation and canonical upload",
        vjp_rule: "non-differentiable byte boundary",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/frombuffer.json",
        evidence_fixture_sha256: "5762ce1828d444b44a4613782cfdcef4e5ad9895d0d1b43258c86d39e2915c93",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6664BEC3F5BD",
        baseline_overload_id: "COMFY-TENSOR-OP-6664BEC3F5BD:blocked",
        baseline_fixture_sha256: "d1467a1650b1a671554da1bd9cbd55edcaf9b18def6bbc7c0fc9a409154c387e",
        overload_id: "sim.native.tensor.full-like.cpu.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"fill_value","kind":"positional_or_keyword","type":"Scalar","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"Option<DType>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn full_like_with_context_exact_native(backend: &CpuBackend, input: &Tensor, fill_value: Scalar, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves input shape",
        dtype_rule: "override or input dtype via canonical scalar codec",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous",
        device_rule: "input CPU stream",
        numeric_rule: "checked scalar conversion then exact repetition",
        tolerance: "bit exact",
        determinism: "row-major fill",
        cancellation_points: "bounded fill intervals and upload",
        vjp_rule: "non-differentiable fill",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/full_like.json",
        evidence_fixture_sha256: "aa835e0b7fecf5038280a770b79df4ceed88c814d8eab64d5085404d2f11a084",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-65EF512E0143",
        baseline_overload_id: "COMFY-TENSOR-OP-65EF512E0143:blocked",
        baseline_fixture_sha256: "4406d74ecd2c58129b057d41468aae52e480c41faa98337aaab7233ee7cb5303",
        overload_id: "sim.native.torch.load.model-loader-adapter.v1",
        ordered_parameters_json: r#"[{"name":"loader","kind":"positional_or_keyword","type":"dyn TorchArchiveLoader","default":null,"keyword_only":false},{"name":"map_location","kind":"keyword_only","type":"DeviceId","default":"CPU","keyword_only":true},{"name":"weights_only","kind":"keyword_only","type":"bool","default":true,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["TorchArchiveValue"]"#,
        rust_signature: "fn torch_load_with_context_exact_native(loader: &dyn TorchArchiveLoader, backend: &CpuBackend, map_location: DeviceId, weights_only: bool, context: &ExecutionContext<'_>) -> Result<TorchArchiveValue, ElementwiseRuntimePartNineError>",
        mutation_rule: "read-only delegation and new canonical tensors",
        alias_rule: "comfy_model loader copies validated archive storages into canonical backend storage",
        shape_rule: "canonical model parser validates pickle tensor geometry and storage bounds",
        dtype_rule: "canonical model parser allowlist mapped to canonical DType",
        accumulation_dtype: "not applicable",
        layout_rule: "validated canonical contiguous tensors",
        device_rule: "CPU map location only",
        numeric_rule: "delegates all ZIP CRC restricted-pickle and tensor-rebuild validation to comfy_model formats",
        tolerance: "bit exact",
        determinism: "canonical model parser traversal",
        cancellation_points: "before delegation and throughout canonical model parsing and storage uploads",
        vjp_rule: "serialization boundary",
        jvp_rule: "serialization boundary",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/torch_load.json",
        evidence_fixture_sha256: "4c5bb4c5ca91b03eb5c00421592867f4bf8ab20627a0cb24ebd2104b8c94cbd6",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-615251B481B7",
        baseline_overload_id: "COMFY-TENSOR-OP-615251B481B7:blocked",
        baseline_fixture_sha256: "219ee7530b5a95996fda2bbe572198cce656bdbdec75c54918b5ec8c0a984f40",
        overload_id: "sim.native.tensor.mul.canonical-binary.v1",
        ordered_parameters_json: r#"[{"name":"left","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"right","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn mul_with_context_exact_native(backend: &CpuBackend, left: &Tensor, right: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical BinaryOperation::Multiply",
        shape_rule: "NumPy broadcast",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous",
        device_rule: "co-located CPU stream",
        numeric_rule: "IEEE multiplication",
        tolerance: "one ULP",
        determinism: "canonical binary traversal",
        cancellation_points: "canonical backend and derivative loops",
        vjp_rule: "broadcast-reduced upstream times opposite operand",
        jvp_rule: "left tangent times right plus left times right tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/mul.json",
        evidence_fixture_sha256: "58bd87f319676dd66b719e50626174fd766f729b6ddb5a311eee7a1fd40f56b8",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6311D94BE18A",
        baseline_overload_id: "COMFY-TENSOR-OP-6311D94BE18A:blocked",
        baseline_fixture_sha256: "d7ae0a6e0265ac99fb4c24fa727e9c504181b4229b9776c0c462bf67b41c593d",
        overload_id: "sim.native.device.npu.current-device.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u32"]"#,
        rust_signature: "fn npu_current_device_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<u32, ElementwiseRuntimePartNineError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical capability owner",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires NPU and returns its ordinal",
        numeric_rule: "exact ordinal",
        tolerance: "exact",
        determinism: "capability projection",
        cancellation_points: "before projection",
        vjp_rule: "non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/npu_current_device.json",
        evidence_fixture_sha256: "63cb65c3fa4d4aa64105313c0eb177277d0b6500d64eba9b21bd5dd13f56b820",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6238000D28B1",
        baseline_overload_id: "COMFY-TENSOR-OP-6238000D28B1:blocked",
        baseline_fixture_sha256: "1f2a90c792584ab3782c74fca9d86269c7b89358abc7972d6b2c7b81cb64ca03",
        overload_id: "sim.native.optim.adamw.state-adapter.v1",
        ordered_parameters_json: r#"[{"name":"parameters","kind":"positional_or_keyword","type":"slice<Tensor<F32>>","default":null,"keyword_only":false},{"name":"learning_rate","kind":"keyword_only","type":"f32","default":0.001,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeAdamW"]"#,
        rust_signature: "fn NativeAdamW::new_with_context_exact_native(backend: &CpuBackend, parameters: &[Tensor], learning_rate: f32, beta1: f32, beta2: f32, epsilon: f32, weight_decay: f32, amsgrad: bool, maximize: bool, context: &ExecutionContext<'_>) -> Result<NativeAdamW, ElementwiseRuntimePartNineError>",
        mutation_rule: "stateful optimizer with transactional canonical steps",
        alias_rule: "owns canonical moment tensors and delegates updates",
        shape_rule: "one state tensor per parameter",
        dtype_rule: "F32 catalog overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical state layouts",
        device_rule: "CPU parameters on their streams",
        numeric_rule: "delegates canonical AdamW functional kernel",
        tolerance: "canonical AdamW tolerance",
        determinism: "parameter order and monotonic checked steps",
        cancellation_points: "state allocation and canonical AdamW checkpoints",
        vjp_rule: "optimizer boundary",
        jvp_rule: "optimizer boundary",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/adamw.json",
        evidence_fixture_sha256: "5cc2c7feed0f6b50b3072dfba25392984a1917e323028ebb84c8bcffc4f5ff37",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-67F181B603A1",
        baseline_overload_id: "COMFY-TENSOR-OP-67F181B603A1:blocked",
        baseline_fixture_sha256: "95a8427747fe877b2bd6a54da686cc9cd56bc2916e020bd598ebc1c3e9ba1dd5",
        overload_id: "sim.native.tensor.pow.canonical-binary.v1",
        ordered_parameters_json: r#"[{"name":"base","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"exponent","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn pow_with_context_exact_native(backend: &CpuBackend, base: &Tensor, exponent: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical BinaryOperation::Power",
        shape_rule: "NumPy broadcast",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous",
        device_rule: "co-located CPU stream",
        numeric_rule: "IEEE powf domain behavior",
        tolerance: "platform libm tolerance",
        determinism: "canonical binary traversal",
        cancellation_points: "canonical backend and derivative loops",
        vjp_rule: "base: upstream*exponent*base^(exponent-1); exponent: upstream*output*ln(base), broadcast-reduced",
        jvp_rule: "sum of directional derivatives",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/pow.json",
        evidence_fixture_sha256: "056a7691b51aadaf671d40a0d62f4842888fac3b4bb99965731d8e9166680913",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-69E05601EAEA",
        baseline_overload_id: "COMFY-TENSOR-OP-69E05601EAEA:blocked",
        baseline_fixture_sha256: "aa3349108da44e6283f7479609bb0fb25d6c6b7969ebee37be8552bf032f3306",
        overload_id: "sim.native.tensor.special-expit.sigmoid-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn expit_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical sigmoid owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical unary output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "stable canonical sigmoid",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical sigmoid checkpoints",
        vjp_rule: "upstream*sigmoid*(1-sigmoid)",
        jvp_rule: "input tangent*sigmoid*(1-sigmoid)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/expit.json",
        evidence_fixture_sha256: "bca586750f72a1a73189521a41b0b081772269a563e48ac9ba88f3f6c0ff4005",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6520A75955CD",
        baseline_overload_id: "COMFY-TENSOR-OP-6520A75955CD:blocked",
        baseline_fixture_sha256: "202c5471dc705d497189101a5e17ab708e293eb0e63edce3c03e17f2be089ef7",
        overload_id: "sim.native.tensor.special-ndtri.cpu-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn ndtri_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F64 rational evaluation then F32",
        layout_rule: "canonical contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "piecewise rational inverse standard-normal CDF; endpoints map to infinities and invalid probabilities to NaN",
        tolerance: "1e-6 on central fixture range",
        determinism: "row-major fixed coefficients",
        cancellation_points: "bounded element intervals and upload",
        vjp_rule: "upstream divided by standard-normal density at output",
        jvp_rule: "input tangent divided by standard-normal density at output",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/ndtri.json",
        evidence_fixture_sha256: "327cc5b0433e1ca6be33bb2da82d6b905ef48309d7bae569c214d918c7524ce7",
    },
]
