&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A2B7298E8EB4",
        baseline_overload_id: "COMFY-TENSOR-OP-A2B7298E8EB4:blocked",
        baseline_fixture_sha256: "270974f6151cc92196b63668b36be2d688e9506125423921c99bbc0897f2c1f8",
        overload_id: "zed.native.tensor.detach.cow-alias.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn detach_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "read only",
        alias_rule: "shares canonical Tensor storage until copy-on-write mutation",
        shape_rule: "preserves shape",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves descriptor",
        device_rule: "preserves device and stream",
        numeric_rule: "identity",
        tolerance: "exact",
        determinism: "immutable alias construction",
        cancellation_points: "before and after clone",
        vjp_rule: "stops reverse-mode gradients",
        jvp_rule: "stops forward-mode tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/detach.json",
        evidence_fixture_sha256: "280f4ac31b359ca372c49adef61f33492ab45370552dcbdfb8d23a7a359a7e1d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A496777C1987",
        baseline_overload_id: "COMFY-TENSOR-OP-A496777C1987:blocked",
        baseline_fixture_sha256: "291c661233c253cc1607b28fc774148f1f23416786ea32e06a29be171d4b6c76",
        overload_id: "zed.native.tensor.mul-in-place.atomic-cow.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor|Scalar","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["unit"]"#,
        rust_signature: "fn mul_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartFourteenError>",
        mutation_rule: "atomically replaces the receiver after successful canonical multiplication",
        alias_rule: "canonical Tensor copy-on-write isolates shared aliases at mutation",
        shape_rule: "broadcast output must equal receiver shape",
        dtype_rule: "canonical multiply promotion constrained to receiver dtype for scalar form",
        accumulation_dtype: "operation dtype",
        layout_rule: "contiguous staged result",
        device_rule: "CPU ordinal zero with matching streams",
        numeric_rule: "receiver times other",
        tolerance: "operation dtype",
        determinism: "canonical binary traversal",
        cancellation_points: "during staging and before receiver publication",
        vjp_rule: "mutation is recorded by higher-level autograd ownership",
        jvp_rule: "mutation is recorded by higher-level autograd ownership",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/mul_in_place.json",
        evidence_fixture_sha256: "d7f7f9f9ffc0f8b0cb7c086878c86ed9b6740202f9db6f57b7704913bb65d2a9",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A3A6638578F7",
        baseline_overload_id: "COMFY-TENSOR-OP-A3A6638578F7:blocked",
        baseline_fixture_sha256: "665e4f585798565ab836cd1509c21b74497df516cedff35ae8190aa73088b190",
        overload_id: "zed.native.tensor.abs-function.canonical-unary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn abs_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 43 canonical absolute unary operation",
        shape_rule: "preserves shape",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "absolute value preserving NaN",
        tolerance: "exact",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical unary checkpoints",
        vjp_rule: "output gradient times sign of input",
        jvp_rule: "input tangent times sign of input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/abs_function.json",
        evidence_fixture_sha256: "4a571e0f039d001df8935ceb130d79218f9d2605c3e2f5b74cf7fbf666aa8d79",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A46ED7068064",
        baseline_overload_id: "COMFY-TENSOR-OP-A46ED7068064:blocked",
        baseline_fixture_sha256: "95b4ffe7371f2cc21a2f1c564d2e0983de3877e89c7e23bf26f123e0fdfcfde2",
        overload_id: "zed.native.tensor.argsort.stable-i64.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<real|integer|bool>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":-1,"keyword_only":true},{"name":"descending","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"stable","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn argsort_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, descending: bool, stable: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh index storage",
        shape_rule: "preserves shape with checked negative axis",
        dtype_rule: "real integer or boolean input and I64 output",
        accumulation_dtype: "not applicable",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "total order with NaNs after finite values when ascending and stable source-order ties",
        tolerance: "exact indices",
        determinism: "stable mode preserves source index ties",
        cancellation_points: "per sort lane and output allocation",
        vjp_rule: "non-differentiable indices",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/argsort.json",
        evidence_fixture_sha256: "02c9cf9c9c600e55ab661c1e2289918913d95b9497c171775a3ada40021f728e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A59D885AD4F9",
        baseline_overload_id: "COMFY-TENSOR-OP-A59D885AD4F9:blocked",
        baseline_fixture_sha256: "eaa5a4f529899ef0f862f5c491d9035b17bcef5618d8487e7bbd2443749a3d86",
        overload_id: "zed.native.tensor.autocast.explicit-policy.v1",
        ordered_parameters_json: r#"[{"name":"device_type","kind":"positional_or_keyword","type":"DeviceKind","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"optional<DType>","default":null,"keyword_only":true},{"name":"enabled","kind":"keyword_only","type":"bool","default":true,"keyword_only":true},{"name":"cache_enabled","kind":"keyword_only","type":"optional<bool>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["AutocastPolicy"]"#,
        rust_signature: "fn autocast_exact_native(device_type: DeviceKind, dtype: Option<DType>, enabled: bool, cache_enabled: Option<bool>, cancellation: &CancellationToken) -> Result<AutocastPolicy, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "returns immutable execution-scoped policy",
        alias_rule: "reuses canonical AutocastPolicy",
        shape_rule: "not applicable",
        dtype_rule: "floating dtype; CPU defaults BF16 and accelerators default F16",
        accumulation_dtype: "policy dependent",
        layout_rule: "not applicable",
        device_rule: "explicit device kind without process-global state",
        numeric_rule: "typed policy construction",
        tolerance: "exact",
        determinism: "immutable value",
        cancellation_points: "before and after construction",
        vjp_rule: "policy is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/autocast.json",
        evidence_fixture_sha256: "26cebdcca23f02fb7ea8b35a5c239ad7703792ef75010c76861b50c79e9364da",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-9F0E29E01970",
        baseline_overload_id: "COMFY-TENSOR-OP-9F0E29E01970:blocked",
        baseline_fixture_sha256: "4703c6e42b78ebadd0dcbae7675c0d663621e76d53451e85e54f5901e585127c",
        overload_id: "zed.native.model.math-sdp-reduction.attention-policy.v1",
        ordered_parameters_json: r#"[{"name":"enabled","kind":"positional_or_keyword","type":"bool","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["MathSdpReductionPolicy"]"#,
        rust_signature: "fn allow_fp16_bf16_reduction_math_sdp_exact_native(enabled: bool, context: &ExecutionContext<'_>) -> Result<MathSdpReductionPolicy, AttentionError>",
        mutation_rule: "returns immutable policy",
        alias_rule: "comfy_model attention remains the sole policy owner",
        shape_rule: "not applicable",
        dtype_rule: "controls F16 and BF16 math-SDP reduction",
        accumulation_dtype: "policy selected",
        layout_rule: "not applicable",
        device_rule: "applies at native attention dispatch",
        numeric_rule: "exact boolean policy projection",
        tolerance: "exact",
        determinism: "immutable value",
        cancellation_points: "before construction",
        vjp_rule: "policy is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/math_sdp_reduction.json",
        evidence_fixture_sha256: "d7719efc2cb00bcfbae681bebcab4d0559ffbeb1bf1a9dbb0e05696e91ef98f1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-9E2C8B750099",
        baseline_overload_id: "COMFY-TENSOR-OP-9E2C8B750099:blocked",
        baseline_fixture_sha256: "be6eadce27d6f06d49f444d376d1fd08ea485dfe35a9800ad28cf5514d9c84c7",
        overload_id: "zed.native.device.cudnn-version.capability-unavailable.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["optional<u64>"]"#,
        rust_signature: "fn cudnn_version_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<Option<u64>, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical backend capability ownership without inventing an ABI version",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "returns none until a certified native cuDNN ABI records a version",
        numeric_rule: "optional version integer",
        tolerance: "exact",
        determinism: "immutable projection",
        cancellation_points: "before projection",
        vjp_rule: "device metadata is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/cudnn_version.json",
        evidence_fixture_sha256: "6aec8c970547283017770eedb1e9d7085d4e98c779da5da73c521c31dde8e0aa",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-9CD229514F61",
        baseline_overload_id: "COMFY-TENSOR-OP-9CD229514F61:blocked",
        baseline_fixture_sha256: "0323a41deaec79e0baf5be6342e0d2ce47f02473b57284da1a43ccc0a17855cd",
        overload_id: "zed.native.tensor.concat.canonical-concatenate.v1",
        ordered_parameters_json: r#"[{"name":"inputs","kind":"positional_or_keyword","type":"list<Tensor<F32>>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn concat_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 51 canonical concatenate implementation",
        shape_rule: "non-concatenated dimensions match and selected dimensions sum with checked arithmetic",
        dtype_rule: "matching F32 inputs",
        accumulation_dtype: "F32",
        layout_rule: "logical reads and contiguous output",
        device_rule: "CPU ordinal zero with matching streams",
        numeric_rule: "ordered concatenation",
        tolerance: "exact",
        determinism: "fixed input and logical traversal order",
        cancellation_points: "canonical concatenate checkpoints",
        vjp_rule: "split output gradient by original extents",
        jvp_rule: "concatenate input tangents along the same axis",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/concat.json",
        evidence_fixture_sha256: "19c44cfc1d128ce4a7f5a70dd48e48e5918edb47cfdfd941ff8b78e0c866517f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-9D504472EFE5",
        baseline_overload_id: "COMFY-TENSOR-OP-9D504472EFE5:blocked",
        baseline_fixture_sha256: "1986c4c49de6b712812ecab9c87bc844a512c2e925fa8a7263299aed154779e5",
        overload_id: "zed.native.tensor.isposinf.typed-predicate.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<real|integer|bool>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<Bool>"]"#,
        rust_signature: "fn isposinf_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh boolean storage",
        shape_rule: "preserves shape",
        dtype_rule: "real integer or boolean input and Bool output",
        accumulation_dtype: "not applicable",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "true only for positive infinity; false for negative infinity NaN and finite values",
        tolerance: "exact boolean",
        determinism: "fixed traversal",
        cancellation_points: "bounded logical traversal and allocation",
        vjp_rule: "predicate is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/isposinf.json",
        evidence_fixture_sha256: "b7a5ead6e59d32267d6cde9765a485478b012266ed7fb6c1e6f6b80ab2b6db8b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A680A8A7456F",
        baseline_overload_id: "COMFY-TENSOR-OP-A680A8A7456F:blocked",
        baseline_fixture_sha256: "0f30b2a8d7f0ccad6ce39f983998a1934c26a747cae8b4fb01565d40b7d45830",
        overload_id: "zed.native.device.npu-count.topology-projection.v1",
        ordered_parameters_json: r#"[{"name":"topology","kind":"positional_or_keyword","type":"MemoryTopology","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u32"]"#,
        rust_signature: "fn npu_device_count_exact_native(topology: &MemoryTopology, context: &ExecutionContext<'_>) -> Result<u32, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "delegates worker-owned MemoryTopology inventory",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u32 count",
        layout_rule: "not applicable",
        device_rule: "counts NPU topology entries",
        numeric_rule: "exact inventory count",
        tolerance: "exact",
        determinism: "canonical topology traversal",
        cancellation_points: "before and after count",
        vjp_rule: "device query is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/npu_device_count.json",
        evidence_fixture_sha256: "c278666790db26e9e5c2e3fc62358641b0ca820b8d0cab9fab6058e338f36d5a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_14",
        operation_id: "COMFY-TENSOR-OP-A67546895304",
        baseline_overload_id: "COMFY-TENSOR-OP-A67546895304:blocked",
        baseline_fixture_sha256: "a3f6cdbe2f8819937f9507c63c6086200c7a306df90453c4d91d4d6837c01f36",
        overload_id: "zed.native.tensor.view-as-real.checked-reinterpretation.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<Complex64|Complex128>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32|F64> view"]"#,
        rust_signature: "fn view_as_real_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartFourteenError>",
        mutation_rule: "read only",
        alias_rule: "checked read-only reinterpretation through canonical Tensor storage",
        shape_rule: "appends trailing dimension two",
        dtype_rule: "Complex64 to F32 and Complex128 to F64",
        accumulation_dtype: "matching real component dtype",
        layout_rule: "doubles source strides and appends unit component stride",
        device_rule: "CPU ordinal zero preserving stream",
        numeric_rule: "real and imaginary components without copying",
        tolerance: "exact byte reinterpretation",
        determinism: "descriptor-only view construction",
        cancellation_points: "before and after checked reinterpretation",
        vjp_rule: "inverse checked reinterpretation to complex gradient",
        jvp_rule: "identical view mapping over complex tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-9cd229514f61",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_14/view_as_real.json",
        evidence_fixture_sha256: "9168a2be0b887251e95c1f1c7d60a64325100cedefb040122c190c12df11cefa",
    },
]
