&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-75127DF334F2",
        baseline_overload_id: "COMFY-TENSOR-OP-75127DF334F2:blocked",
        baseline_fixture_sha256: "5cb32351df61f09ea7f76714681cab47dc1874eaa50afcabd5d6522c94988e5f",
        overload_id: "zed.native.tensor.cumsum.scan.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"Option<DType>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn cumsum_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical backend storage",
        shape_rule: "preserves shape and normalizes a checked axis",
        dtype_rule: "explicit dtype or int64 integer promotion",
        accumulation_dtype: "output dtype",
        layout_rule: "canonical contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "single-pass cumulative sum with wrapping integer accumulation",
        tolerance: "dtype arithmetic",
        determinism: "row-major scan state order",
        cancellation_points: "bounded scan intervals and upload",
        vjp_rule: "reverse cumulative sum of output gradient",
        jvp_rule: "cumulative sum of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/cumsum.json",
        evidence_fixture_sha256: "4918df622abfdc865e2a66ced5193ce10b9a5ac5033adc5b14859440db3fc755",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-77C67CAAC4AD",
        baseline_overload_id: "COMFY-TENSOR-OP-77C67CAAC4AD:blocked",
        baseline_fixture_sha256: "cc7e70e56de5bc2ee341cde4cc433d03056c910f1ae0550c1902d2967ab4b843",
        overload_id: "zed.native.tensor.size.descriptor-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"Option<i64>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["TensorSize"]"#,
        rust_signature: "fn size_exact_native(input: &Tensor, dimension: Option<i64>, cancellation: &CancellationToken) -> Result<TensorSize, ElementwiseRuntimePartTenError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical TensorDescriptor shape",
        shape_rule: "whole checked shape or one normalized dimension",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent descriptor query",
        numeric_rule: "exact u64 dimensions",
        tolerance: "exact",
        determinism: "descriptor order",
        cancellation_points: "before projection",
        vjp_rule: "non-differentiable metadata",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/size.json",
        evidence_fixture_sha256: "69c9072f8cab0af787b7c028ac1104544edee3e75bcc335e17f9cf6498a23469",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-78FD9BB26FAF",
        baseline_overload_id: "COMFY-TENSOR-OP-78FD9BB26FAF:blocked",
        baseline_fixture_sha256: "2c4f70ce219343053a37f07cb90f5fbcea0f8bced2d52831af735a9b9bc0c3f4",
        overload_id: "zed.native.tensor.fmod.canonical-binary-scalar.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"divisor","kind":"positional_or_keyword","type":"f32","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn fmod_with_context_exact_native(backend: &CpuBackend, input: &Tensor, divisor: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical BinaryOperation::FloatingRemainder",
        shape_rule: "preserves input shape",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "truncation-sign IEEE floating remainder",
        tolerance: "one ULP",
        determinism: "canonical binary-scalar traversal",
        cancellation_points: "canonical backend checkpoints",
        vjp_rule: "upstream gradient with respect to input away from discontinuities",
        jvp_rule: "input tangent away from discontinuities",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/fmod.json",
        evidence_fixture_sha256: "7515813c40b7dda3e3f33adb8ac82a89a29c445f4f2f9b08c96ce8bcc6a04aa9",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-73EF9076727A",
        baseline_overload_id: "COMFY-TENSOR-OP-73EF9076727A:blocked",
        baseline_fixture_sha256: "089e11b1a8d74bb86c134f13bfd4fdc874f3a56a32ee5be6c5cd09a2f8075db5",
        overload_id: "zed.native.tensor.hann-window.cpu.v1",
        ordered_parameters_json: r#"[{"name":"window_length","kind":"positional_or_keyword","type":"usize","default":null,"keyword_only":false},{"name":"periodic","kind":"keyword_only","type":"bool","default":true,"keyword_only":true},{"name":"dtype","kind":"keyword_only","type":"DType","default":"F32","keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn hann_window_with_context_exact_native(backend: &CpuBackend, window_length: usize, periodic: bool, dtype: DType, stream: StreamId, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical backend storage",
        shape_rule: "one-dimensional window_length",
        dtype_rule: "F32 or F64",
        accumulation_dtype: "F64 formula evaluation",
        layout_rule: "canonical contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "0.5*(1-cos(2*pi*n/denominator)) with exact singleton behavior",
        tolerance: "one ULP after dtype conversion",
        determinism: "ascending window index",
        cancellation_points: "bounded generation intervals and upload",
        vjp_rule: "non-differentiable constructor",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/hann_window.json",
        evidence_fixture_sha256: "f18472d17a08ee3eed913e2e4ddf88539e28793f17a8f4581e2b920d5506ffcd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-75F89A81FD21",
        baseline_overload_id: "COMFY-TENSOR-OP-75F89A81FD21:blocked",
        baseline_fixture_sha256: "452d701353e2a29ba934f2b896c3b5613d8aa288435b0c3f3c62c41767886f46",
        overload_id: "zed.native.dtype.iinfo.canonical-catalog.v1",
        ordered_parameters_json: r#"[{"name":"dtype","kind":"positional_or_keyword","type":"DType","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["IntegerInfo"]"#,
        rust_signature: "fn iinfo_exact_native(dtype: DType, cancellation: &CancellationToken) -> Result<IntegerInfo, ElementwiseRuntimePartTenError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical DType catalog",
        shape_rule: "not applicable",
        dtype_rule: "integer dtypes only",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "exact bit width and mathematical integer bounds",
        tolerance: "exact",
        determinism: "dtype table lookup",
        cancellation_points: "before lookup",
        vjp_rule: "non-differentiable metadata",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/iinfo.json",
        evidence_fixture_sha256: "9ef54175829f799626db5812d2e8d62544bb806607e71225abb308acf7266d3a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-6F8F8AE14084",
        baseline_overload_id: "COMFY-TENSOR-OP-6F8F8AE14084:blocked",
        baseline_fixture_sha256: "149572d98388102805424d34673e5badc741cdcc2d397c18da600bcf5dca1235",
        overload_id: "zed.native.autocast.cache-policy-query.v1",
        ordered_parameters_json: r#"[{"name":"policy","kind":"positional_or_keyword","type":"AutocastPolicy","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn is_autocast_cache_enabled_exact_native(policy: &AutocastPolicy, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTenError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical explicit autocast execution policy",
        shape_rule: "not applicable",
        dtype_rule: "policy validates floating autocast dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "execution-policy scoped",
        numeric_rule: "exact boolean",
        tolerance: "exact",
        determinism: "policy projection",
        cancellation_points: "before projection",
        vjp_rule: "non-differentiable runtime state",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/autocast_cache.json",
        evidence_fixture_sha256: "317f82c4d6ce09a4d0d53b46d742c52109e15ebc353da064110d477eec4635a9",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-6D6C617423EA",
        baseline_overload_id: "COMFY-TENSOR-OP-6D6C617423EA:blocked",
        baseline_fixture_sha256: "2b0b93be48cabcab6cfa7ba62aeeca94b68bfdc1ab1d20e8ed239732c48f8e13",
        overload_id: "zed.native.tensor.log2.canonical-unary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn log2_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical UnaryOperation::LogarithmBaseTwo",
        shape_rule: "preserves shape",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE base-two logarithm",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical backend and derivative checkpoints",
        vjp_rule: "upstream/(input*ln(2))",
        jvp_rule: "input_tangent/(input*ln(2))",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/log2.json",
        evidence_fixture_sha256: "c5af3940999ae985bbc5923ec632c91905ed0ff12d806af8199ba77a8f2767c1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-73E8932FDF3A",
        baseline_overload_id: "COMFY-TENSOR-OP-73E8932FDF3A:blocked",
        baseline_fixture_sha256: "44c5f11506ed3d4afef809df80473e0ec9f3fa6482c6f9a3754ab2e6907891c3",
        overload_id: "zed.native.device.mlu.count.memory-topology-adapter.v1",
        ordered_parameters_json: r#"[{"name":"topology","kind":"positional_or_keyword","type":"MemoryTopology","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u32"]"#,
        rust_signature: "fn mlu_device_count_exact_native(topology: &MemoryTopology, cancellation: &CancellationToken) -> Result<u32, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "delegates canonical MemoryTopology device inventory",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "counts MLU device identities only",
        numeric_rule: "checked u32 count",
        tolerance: "exact",
        determinism: "topology inventory projection",
        cancellation_points: "before and after traversal",
        vjp_rule: "non-differentiable capability query",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/mlu_device_count.json",
        evidence_fixture_sha256: "e2c9ff9dce23cc7e8ab8b1096df39412a6b5482734ebffcba4c75f96c15cc582",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-6E17F49E5F14",
        baseline_overload_id: "COMFY-TENSOR-OP-6E17F49E5F14:blocked",
        baseline_fixture_sha256: "2e444bdb16385bf5545986a03d6233f35b5168174f8f0d8c5860b571da6d90c6",
        overload_id: "zed.native.nn.pair.typed-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"PairInput","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["[u64;2]"]"#,
        rust_signature: "fn pair_exact_native(input: PairInput, cancellation: &CancellationToken) -> Result<[u64; 2], ElementwiseRuntimePartTenError>",
        mutation_rule: "read only",
        alias_rule: "owned fixed-size output",
        shape_rule: "scalar duplicates or pair preserves order",
        dtype_rule: "u64 dimensions",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "exact dimension values",
        tolerance: "exact",
        determinism: "input order",
        cancellation_points: "before conversion",
        vjp_rule: "non-differentiable configuration",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/pair.json",
        evidence_fixture_sha256: "156e26c84ea224d5e8c81d3e28262c6e9e53a8d2489c99a5865e751c3d399c55",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-706EE92A3AD0",
        baseline_overload_id: "COMFY-TENSOR-OP-706EE92A3AD0:blocked",
        baseline_fixture_sha256: "4315f1edd2002d030a3a701e3d4f322adb80f126c56eb04f51e4259614ee7651",
        overload_id: "zed.native.tensor.unique.cpu.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"sorted","kind":"keyword_only","type":"bool","default":true,"keyword_only":true},{"name":"return_inverse","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"return_counts","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"dimension","kind":"keyword_only","type":"Option<i64>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["UniqueResult"]"#,
        rust_signature: "fn unique_with_context_exact_native(backend: &CpuBackend, input: &Tensor, sorted: bool, return_inverse: bool, return_counts: bool, dimension: Option<i64>, context: &ExecutionContext<'_>) -> Result<UniqueResult, ElementwiseRuntimePartTenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical values inverse and count storage",
        shape_rule: "flattened values or unique slices along a checked dimension",
        dtype_rule: "preserves non-complex input dtype; indices and counts are I64",
        accumulation_dtype: "I64 counts",
        layout_rule: "canonical contiguous outputs",
        device_rule: "CPU ordinal zero",
        numeric_rule: "ascending scalar or lexicographic slice order with NaNs distinct",
        tolerance: "bit-preserving values and exact indices",
        determinism: "total scalar ordering plus source-index tie break",
        cancellation_points: "bounded item extraction grouping copy and upload",
        vjp_rule: "non-differentiable discrete selection",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/unique.json",
        evidence_fixture_sha256: "a9554a73366b21b0ce15d0dafff0f054f42d0005db3b7e80caeaa0cb35d40838",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-78CD1B8EFCEC",
        baseline_overload_id: "COMFY-TENSOR-OP-78CD1B8EFCEC:blocked",
        baseline_fixture_sha256: "e5b52b021f3acdf97f2c2912e0087d535ddc5b2e70ba380b93b49f7149f51ff8",
        overload_id: "zed.native.tensor.unique-consecutive.cpu.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"return_inverse","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"return_counts","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"dimension","kind":"keyword_only","type":"Option<i64>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["UniqueResult"]"#,
        rust_signature: "fn unique_consecutive_with_context_exact_native(backend: &CpuBackend, input: &Tensor, return_inverse: bool, return_counts: bool, dimension: Option<i64>, context: &ExecutionContext<'_>) -> Result<UniqueResult, ElementwiseRuntimePartTenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical values inverse and count storage",
        shape_rule: "flattened runs or adjacent unique slices along a checked dimension",
        dtype_rule: "preserves non-complex input dtype; indices and counts are I64",
        accumulation_dtype: "I64 counts",
        layout_rule: "canonical contiguous outputs",
        device_rule: "CPU ordinal zero",
        numeric_rule: "adjacent equality only with NaNs distinct",
        tolerance: "bit-preserving values and exact indices",
        determinism: "source traversal order",
        cancellation_points: "bounded item extraction grouping copy and upload",
        vjp_rule: "non-differentiable discrete selection",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/unique_consecutive.json",
        evidence_fixture_sha256: "80bed8d128df1c51e74f7615bcc55283dc234c8c9f2add70eb770ea0cc09104c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_10",
        operation_id: "COMFY-TENSOR-OP-6DEA145A655F",
        baseline_overload_id: "COMFY-TENSOR-OP-6DEA145A655F:blocked",
        baseline_fixture_sha256: "c5c7f599c33a4ca9b84219c4efc708d32893df88abc86801f2e4e0fdc917c6f3",
        overload_id: "zed.native.device.xpu.empty-cache.memory-owner-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","kind":"positional_or_keyword","type":"dyn CachedAllocationOwner","default":null,"keyword_only":false},{"name":"inventory","kind":"positional_or_keyword","type":"MemoryPlacementInventory","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Xpu>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeCacheRelease"]"#,
        rust_signature: "fn xpu_empty_cache_exact_native(backend: &dyn CachedAllocationOwner, inventory: &mut MemoryPlacementInventory, device: DeviceId, cancellation: &CancellationToken) -> Result<NativeCacheRelease, NativeMemoryStatsError>",
        mutation_rule: "transactional canonical cache release and accounting commit",
        alias_rule: "delegates shared device_empty_cache authority",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires matching XPU cache owner and inventory device",
        numeric_rule: "exact released-byte and eviction accounting",
        tolerance: "exact",
        determinism: "inventory resource order",
        cancellation_points: "before staging and canonical allocator release",
        vjp_rule: "non-differentiable memory control",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-6d6c617423ea",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_10/xpu_empty_cache.json",
        evidence_fixture_sha256: "debb67ad4ecb1478b443242553030f4f101f87da84aae855a8c13900da996754",
    },
]
