&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6A39A98E4F68",
        baseline_overload_id: "COMFY-TENSOR-OP-6A39A98E4F68:blocked",
        baseline_fixture_sha256: "100e859769726a6700547667c3a2f0710112a4fe2655fdd8c065f4de08d577ab",
        overload_id: "zed.native.tensor.constructor.cpu.v1",
        ordered_parameters_json: r#"[{"name":"values","kind":"positional_or_keyword","type":"slice<Scalar>","default":null,"keyword_only":false},{"name":"shape","kind":"positional_or_keyword","type":"slice<u64>","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"DType","default":"F32","keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_constructor_with_context_exact_native(backend: &CpuBackend, values: &[Scalar], shape: &[u64], dtype: DType, stream: StreamId, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical backend storage",
        shape_rule: "value count exactly equals checked shape product",
        dtype_rule: "canonical checked scalar codec",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "checked dtype conversion",
        tolerance: "bit exact",
        determinism: "input order",
        cancellation_points: "before and during scalar encoding and upload",
        vjp_rule: "leaf constructor boundary",
        jvp_rule: "leaf constructor boundary",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/tensor_constructor.json",
        evidence_fixture_sha256: "3f45f7f7d5c2e3f5ab367f88e24992675a7746e3489f0016470a187668ee3898",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-616CB031A549",
        baseline_overload_id: "COMFY-TENSOR-OP-616CB031A549:blocked",
        baseline_fixture_sha256: "df6a89c0afd8cb03ff982b4b92d288285a7a49fc21a44bf0298947c291ced0bc",
        overload_id: "zed.native.tensor.bitwise-xor.cpu.v1",
        ordered_parameters_json: r#"[{"name":"left","kind":"positional_or_keyword","type":"Tensor<integer or bool>","default":null,"keyword_only":false},{"name":"right","kind":"positional_or_keyword","type":"Tensor<same dtype>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn bitwise_xor_with_context_exact_native(backend: &CpuBackend, left: &Tensor, right: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "NumPy trailing-dimension broadcast",
        dtype_rule: "matching bool or integer dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous",
        device_rule: "co-located CPU stream",
        numeric_rule: "width-preserving XOR",
        tolerance: "bit exact",
        determinism: "row-major broadcast traversal",
        cancellation_points: "bounded element intervals and upload",
        vjp_rule: "non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/bitwise_xor.json",
        evidence_fixture_sha256: "ceccaf9193759dcc9facc75f1554832d46371738b72d320efb5acdce90d127fb",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-67B5EDD39C41",
        baseline_overload_id: "COMFY-TENSOR-OP-67B5EDD39C41:blocked",
        baseline_fixture_sha256: "4916143dfb9eb6665adef3bf6dc028748f69922012dfad46d6859428a2e261ce",
        overload_id: "zed.native.tensor.clamp.adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"minimum","kind":"keyword_only","type":"Option<Scalar>","default":null,"keyword_only":true},{"name":"maximum","kind":"keyword_only","type":"Option<Scalar>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn clamp_with_context_exact_native(backend: &CpuBackend, input: &Tensor, minimum: Option<Scalar>, maximum: Option<Scalar>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place through canonical copy-on-write clamp",
        alias_rule: "canonical storage clone detaches before write",
        shape_rule: "preserves shape",
        dtype_rule: "preserves supported dtype",
        accumulation_dtype: "input dtype",
        layout_rule: "preserves descriptor",
        device_rule: "canonical clamp owner",
        numeric_rule: "inclusive finite bounds with canonical NaN behavior",
        tolerance: "canonical scalar codec",
        determinism: "canonical staged traversal",
        cancellation_points: "canonical clamp checkpoints",
        vjp_rule: "upstream within unclipped interval",
        jvp_rule: "input tangent within unclipped interval",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/clamp.json",
        evidence_fixture_sha256: "371d778db5f05816231cc83bb5addcc6494c0d4ca7af1478a80926f28d0d921a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6A4C6EDFC695",
        baseline_overload_id: "COMFY-TENSOR-OP-6A4C6EDFC695:blocked",
        baseline_fixture_sha256: "c66f49c84be618fa4bdeba783ff2a55d10ccb08326283193437dc9c4a2a807cb",
        overload_id: "zed.native.tensor.frombuffer.owned-cpu.v1",
        ordered_parameters_json: r#"[{"name":"source","kind":"positional_or_keyword","type":"slice<u8>","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"DType","default":null,"keyword_only":true},{"name":"count","kind":"keyword_only","type":"Option<usize>","default":null,"keyword_only":true},{"name":"offset","kind":"keyword_only","type":"usize","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn frombuffer_with_context_exact_native(backend: &CpuBackend, source: &[u8], dtype: DType, count: Option<usize>, offset: usize, stream: StreamId, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "owned canonical snapshot because borrowed Rust slices cannot outlive the call",
        shape_rule: "one-dimensional checked element count",
        dtype_rule: "caller-selected canonical dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "native-endian exact byte interpretation",
        tolerance: "bit exact",
        determinism: "source byte order",
        cancellation_points: "before validation and canonical upload",
        vjp_rule: "non-differentiable byte boundary",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/frombuffer.json",
        evidence_fixture_sha256: "e25a8a781d544ca90a752200381226cbb651a574945a92a59d3af4925c6c171c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6664BEC3F5BD",
        baseline_overload_id: "COMFY-TENSOR-OP-6664BEC3F5BD:blocked",
        baseline_fixture_sha256: "0934ad801ad1266ec34b3d45eb14638ae0e0c55fa80469df17992c27afca8d69",
        overload_id: "zed.native.tensor.full-like.cpu.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"fill_value","kind":"positional_or_keyword","type":"Scalar","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"Option<DType>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn full_like_with_context_exact_native(backend: &CpuBackend, input: &Tensor, fill_value: Scalar, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves input shape",
        dtype_rule: "override or input dtype via canonical scalar codec",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous",
        device_rule: "input CPU stream",
        numeric_rule: "checked scalar conversion then exact repetition",
        tolerance: "bit exact",
        determinism: "row-major fill",
        cancellation_points: "bounded fill intervals and upload",
        vjp_rule: "non-differentiable fill",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/full_like.json",
        evidence_fixture_sha256: "0b660549462b067c89ff0342f1d618df1df29adb05fb48e60bb550413cd75c85",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-65EF512E0143",
        baseline_overload_id: "COMFY-TENSOR-OP-65EF512E0143:blocked",
        baseline_fixture_sha256: "d6859d7953069e4e9496907eb84715827b87d95a654a2cbfff930d3b73a39cbd",
        overload_id: "zed.native.torch.load.model-loader-adapter.v1",
        ordered_parameters_json: r#"[{"name":"loader","kind":"positional_or_keyword","type":"dyn TorchArchiveLoader","default":null,"keyword_only":false},{"name":"map_location","kind":"keyword_only","type":"DeviceId","default":"CPU","keyword_only":true},{"name":"weights_only","kind":"keyword_only","type":"bool","default":true,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["TorchArchiveValue"]"#,
        rust_signature: "fn torch_load_with_context_exact_native(loader: &dyn TorchArchiveLoader, backend: &CpuBackend, map_location: DeviceId, weights_only: bool, context: &ExecutionContext<'_>) -> Result<TorchArchiveValue, ElementwiseRuntimePartNineError>",
        mutation_rule: "read-only delegation and new canonical tensors",
        alias_rule: "comfy_model loader copies validated archive storages into canonical backend storage",
        shape_rule: "canonical model parser validates pickle tensor geometry and storage bounds",
        dtype_rule: "canonical model parser allowlist mapped to canonical DType",
        accumulation_dtype: "not applicable",
        layout_rule: "validated canonical contiguous tensors",
        device_rule: "CPU map location only",
        numeric_rule: "delegates all ZIP CRC restricted-pickle and tensor-rebuild validation to comfy_model formats",
        tolerance: "bit exact",
        determinism: "canonical model parser traversal",
        cancellation_points: "before delegation and throughout canonical model parsing and storage uploads",
        vjp_rule: "serialization boundary",
        jvp_rule: "serialization boundary",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/torch_load.json",
        evidence_fixture_sha256: "4bbbaf78298c1c20c2c22d83018386dd89d3fdb9c74a518f4f336635c5a0ef74",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-615251B481B7",
        baseline_overload_id: "COMFY-TENSOR-OP-615251B481B7:blocked",
        baseline_fixture_sha256: "41b05d0f46918191852dddff8c766782dfd49b961544d1425654a81360e1ca2d",
        overload_id: "zed.native.tensor.mul.canonical-binary.v1",
        ordered_parameters_json: r#"[{"name":"left","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"right","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn mul_with_context_exact_native(backend: &CpuBackend, left: &Tensor, right: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical BinaryOperation::Multiply",
        shape_rule: "NumPy broadcast",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous",
        device_rule: "co-located CPU stream",
        numeric_rule: "IEEE multiplication",
        tolerance: "one ULP",
        determinism: "canonical binary traversal",
        cancellation_points: "canonical backend and derivative loops",
        vjp_rule: "broadcast-reduced upstream times opposite operand",
        jvp_rule: "left tangent times right plus left times right tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/mul.json",
        evidence_fixture_sha256: "c032d3ef432965547667af892b62690c8d37d9f2283e58a55c46c1586e493631",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6311D94BE18A",
        baseline_overload_id: "COMFY-TENSOR-OP-6311D94BE18A:blocked",
        baseline_fixture_sha256: "ebfbd239166eaac6180704a40e84f0374aef9b7b0ec634d2b194e5a678392ef2",
        overload_id: "zed.native.device.npu.current-device.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u32"]"#,
        rust_signature: "fn npu_current_device_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<u32, ElementwiseRuntimePartNineError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical capability owner",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires NPU and returns its ordinal",
        numeric_rule: "exact ordinal",
        tolerance: "exact",
        determinism: "capability projection",
        cancellation_points: "before projection",
        vjp_rule: "non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/npu_current_device.json",
        evidence_fixture_sha256: "c8f09edfad8e89f22e1afd97cce747dc125ad826e3c20f37f24e2c68e0d5fe46",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6238000D28B1",
        baseline_overload_id: "COMFY-TENSOR-OP-6238000D28B1:blocked",
        baseline_fixture_sha256: "5b19b5125b3f34fb5ba698296af3e99495b2dfa2ab9571f1880fcd451ef6ebdc",
        overload_id: "zed.native.optim.adamw.state-adapter.v1",
        ordered_parameters_json: r#"[{"name":"parameters","kind":"positional_or_keyword","type":"slice<Tensor<F32>>","default":null,"keyword_only":false},{"name":"learning_rate","kind":"keyword_only","type":"f32","default":0.001,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeAdamW"]"#,
        rust_signature: "fn NativeAdamW::new_with_context_exact_native(backend: &CpuBackend, parameters: &[Tensor], learning_rate: f32, beta1: f32, beta2: f32, epsilon: f32, weight_decay: f32, amsgrad: bool, maximize: bool, context: &ExecutionContext<'_>) -> Result<NativeAdamW, ElementwiseRuntimePartNineError>",
        mutation_rule: "stateful optimizer with transactional canonical steps",
        alias_rule: "owns canonical moment tensors and delegates updates",
        shape_rule: "one state tensor per parameter",
        dtype_rule: "F32 catalog overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical state layouts",
        device_rule: "CPU parameters on their streams",
        numeric_rule: "delegates canonical AdamW functional kernel",
        tolerance: "canonical AdamW tolerance",
        determinism: "parameter order and monotonic checked steps",
        cancellation_points: "state allocation and canonical AdamW checkpoints",
        vjp_rule: "optimizer boundary",
        jvp_rule: "optimizer boundary",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/adamw.json",
        evidence_fixture_sha256: "eccd1340b7be54026247962ebc211b9b7f6f94aa12779a509882455f67622898",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-67F181B603A1",
        baseline_overload_id: "COMFY-TENSOR-OP-67F181B603A1:blocked",
        baseline_fixture_sha256: "e6ea77edd80d861759fa233f5a9a0cc558489acbaacf8569b55a7da16067370d",
        overload_id: "zed.native.tensor.pow.canonical-binary.v1",
        ordered_parameters_json: r#"[{"name":"base","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"exponent","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn pow_with_context_exact_native(backend: &CpuBackend, base: &Tensor, exponent: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical BinaryOperation::Power",
        shape_rule: "NumPy broadcast",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous",
        device_rule: "co-located CPU stream",
        numeric_rule: "IEEE powf domain behavior",
        tolerance: "platform libm tolerance",
        determinism: "canonical binary traversal",
        cancellation_points: "canonical backend and derivative loops",
        vjp_rule: "base: upstream*exponent*base^(exponent-1); exponent: upstream*output*ln(base), broadcast-reduced",
        jvp_rule: "sum of directional derivatives",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/pow.json",
        evidence_fixture_sha256: "632f68f050594dc8067e7947a3f135b1fb098c62dc181e551452118afe2c5ae1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-69E05601EAEA",
        baseline_overload_id: "COMFY-TENSOR-OP-69E05601EAEA:blocked",
        baseline_fixture_sha256: "9b6df3a3b7f1d23b0c763812b247b6e6e995d1647e29511df392e76621cdbc24",
        overload_id: "zed.native.tensor.special-expit.sigmoid-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn expit_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical sigmoid owner",
        shape_rule: "preserves shape",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical unary output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "stable canonical sigmoid",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical sigmoid checkpoints",
        vjp_rule: "upstream*sigmoid*(1-sigmoid)",
        jvp_rule: "input tangent*sigmoid*(1-sigmoid)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/expit.json",
        evidence_fixture_sha256: "9c5f51199084a8ab9693276813d63d5c45bc266a631d8c6d33852c80226de17e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_09",
        operation_id: "COMFY-TENSOR-OP-6520A75955CD",
        baseline_overload_id: "COMFY-TENSOR-OP-6520A75955CD:blocked",
        baseline_fixture_sha256: "2f5c6f12962b407439fe327853a3c40e9de323f40a7ad14f8dcf9bb8a9ed3187",
        overload_id: "zed.native.tensor.special-ndtri.cpu-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn ndtri_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F64 rational evaluation then F32",
        layout_rule: "canonical contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "piecewise rational inverse standard-normal CDF; endpoints map to infinities and invalid probabilities to NaN",
        tolerance: "1e-6 on central fixture range",
        determinism: "row-major fixed coefficients",
        cancellation_points: "bounded element intervals and upload",
        vjp_rule: "upstream divided by standard-normal density at output",
        jvp_rule: "input tangent divided by standard-normal density at output",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-615251b481b7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_09/ndtri.json",
        evidence_fixture_sha256: "38e6d1c7cffabbaa3b208e10ef7f79f19425679beb3a56f0bc8abe5a39649797",
    },
]
