&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BDAC082E9091",
        baseline_overload_id: "COMFY-TENSOR-OP-BDAC082E9091:blocked",
        baseline_fixture_sha256: "c5c58e2e77a29749ae632a1ec05025ab70e631316670b6566d33270baf925f27",
        overload_id: "sim.native.tensor.requires-grad-method.autograd-tape.v1",
        ordered_parameters_json: r#"[{"name":"tape","kind":"positional_or_keyword","type":"&mut AutogradTape","default":null,"keyword_only":false},{"name":"input","kind":"positional_or_keyword","type":"&Tensor","default":null,"keyword_only":false},{"name":"leaf","kind":"positional_or_keyword","type":"Option<LeafId>","default":null,"keyword_only":false},{"name":"requires_grad","kind":"positional_or_keyword","type":"bool","default":true,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn requires_grad_method_exact_native(tape: &mut AutogradTape, input: &Tensor, leaf: Option<LeafId>, requires_grad: bool, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "mutates only caller-owned AutogradTape leaf participation",
        alias_rule: "returned Tensor shares canonical input storage",
        shape_rule: "preserves shape",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves descriptor",
        device_rule: "preserves device",
        numeric_rule: "checked storage-to-leaf registration or removal",
        tolerance: "exact",
        determinism: "storage identity keyed tape mutation",
        cancellation_points: "before and after staged tape validation",
        vjp_rule: "enables canonical tape accumulation for the checked leaf",
        jvp_rule: "leaf participation metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/requires_grad_method.json",
        evidence_fixture_sha256: "04d7c62b1bf6bf1c8b7c9085943511176404ee378a9f0e1cd61415d8b482d59e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BA7930023140",
        baseline_overload_id: "COMFY-TENSOR-OP-BA7930023140:blocked",
        baseline_fixture_sha256: "010a9e9ed6b1385d0326e704abe08c1aa394e9ccd85e3d574a5ed658a9eaddf6",
        overload_id: "sim.native.tensor.atanh.cpu-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn atanh_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "Rust f32 atanh with IEEE domain behavior",
        tolerance: "1e-6 absolute",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical backend unary checkpoints",
        vjp_rule: "output_gradient/(1-input^2)",
        jvp_rule: "input_tangent/(1-input^2)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/atanh.json",
        evidence_fixture_sha256: "e18abe5bdaa203c866d92d2e3c08f0f3304aec42890f449869cb743d5127bd5b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BB442559BFF4",
        baseline_overload_id: "COMFY-TENSOR-OP-BB442559BFF4:blocked",
        baseline_fixture_sha256: "65b4e93d168fb9fdd6a4f4ff569b49f2ad06185d3ea8ae8f122a878cf2fd688b",
        overload_id: "sim.native.tensor.clip.canonical-clamp-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"minimum","kind":"positional_or_keyword","type":"Option<f32>","default":null,"keyword_only":false},{"name":"maximum","kind":"positional_or_keyword","type":"Option<f32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn clip_with_context_exact_native(backend: &CpuBackend, input: &Tensor, minimum: Option<f32>, maximum: Option<f32>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical clamp owner",
        shape_rule: "preserves shape",
        dtype_rule: "Task 60 F32 source profile",
        accumulation_dtype: "F32",
        layout_rule: "canonical clamp layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "inclusive optional lower and upper clamp bounds",
        tolerance: "exact for finite F32 inputs",
        determinism: "canonical clamp traversal",
        cancellation_points: "canonical clamp checkpoints",
        vjp_rule: "output gradient inside bounds and zero outside",
        jvp_rule: "input tangent inside bounds and zero outside",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/clip.json",
        evidence_fixture_sha256: "7f6bf7317cff5c5d240d64dd450a0e0d9b8361e5905f853e32e1199fa6495a56",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BBE4FD70D20E",
        baseline_overload_id: "COMFY-TENSOR-OP-BBE4FD70D20E:blocked",
        baseline_fixture_sha256: "bc53f480091770800573fd3e854620b701f8e59c7ce470eba139b81e09b06a09",
        overload_id: "sim.native.worker.cuda-ipc-collect.inventory-transaction.v1",
        ordered_parameters_json: r#"[{"name":"inventory","kind":"positional_or_keyword","type":"&mut MemoryPlacementInventory","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Cuda|Rocm>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeIpcCollection"]"#,
        rust_signature: "fn comfy_worker::cuda_ipc_collect_exact_native(inventory: &mut MemoryPlacementInventory, device: DeviceId, cancellation: &CancellationToken) -> Result<NativeIpcCollection, NativeMemoryStatsError>",
        mutation_rule: "atomically commits staged removal of reclaimable IPC exports",
        alias_rule: "returns owned accounting actions",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 bytes",
        layout_rule: "not applicable",
        device_rule: "exact configured CUDA or ROCm device",
        numeric_rule: "checked sum of dropped unprotected IpcExport resources",
        tolerance: "exact",
        determinism: "inventory order",
        cancellation_points: "before and during staging and before commit",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/cuda_ipc_collect.json",
        evidence_fixture_sha256: "3ad4cf56145fcd05451f2d286ab07e74157c0cae486239f79e536d2abf06be94",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BF7BF3AA74D7",
        baseline_overload_id: "COMFY-TENSOR-OP-BF7BF3AA74D7:blocked",
        baseline_fixture_sha256: "de1100d3456396de1e624519e84eced568299b96f16a97cbf13e57381f50d5af",
        overload_id: "sim.native.worker.cuda-mem-get-info.topology-accounting.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"topology","kind":"positional_or_keyword","type":"&MemoryTopology","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"&MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["(u64,u64)"]"#,
        rust_signature: "fn comfy_worker::cuda_mem_get_info_exact_native(capabilities: &BackendCapabilityMatrix, topology: &MemoryTopology, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<(u64, u64), NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "copyable byte counts",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 bytes",
        layout_rule: "not applicable",
        device_rule: "exact CUDA or ROCm capability device in topology",
        numeric_rule: "free equals capacity minus canonical active bytes; total equals capacity",
        tolerance: "exact",
        determinism: "immutable topology and accounting snapshot",
        cancellation_points: "before and after projection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/cuda_mem_get_info.json",
        evidence_fixture_sha256: "1a4b7798196c1dfa9da682f904d4e83a92a657110efc0711766765a4dc7ebfbe",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BB1114038F65",
        baseline_overload_id: "COMFY-TENSOR-OP-BB1114038F65:blocked",
        baseline_fixture_sha256: "99dddcb61d85039603e2b741f49a033d3ed0cb56828507af274d7ee9b87135cb",
        overload_id: "sim.native.model.sdpa-kernel.immutable-policy.v1",
        ordered_parameters_json: r#"[{"name":"backends","kind":"positional_or_keyword","type":"&[SdpaBackend]","default":null,"keyword_only":false},{"name":"set_priority","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["SdpaKernelSelection"]"#,
        rust_signature: "fn comfy_model::sdpa_kernel_exact_native(backends: &[SdpaBackend], set_priority: bool, cancellation: &CancellationToken) -> Result<SdpaKernelSelection, AttentionError>",
        mutation_rule: "read only",
        alias_rule: "owned immutable ordered selection",
        shape_rule: "one through four unique backends",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "selection only; execution remains capability checked",
        numeric_rule: "preserves unique caller order and priority flag",
        tolerance: "exact",
        determinism: "input order",
        cancellation_points: "before and during validation",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/sdpa_kernel.json",
        evidence_fixture_sha256: "f8e1e6a0aa319f188026d5ecafdf3fe8b6579b606f5ad614790761177d1002c9",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-B96B1B025618",
        baseline_overload_id: "COMFY-TENSOR-OP-B96B1B025618:blocked",
        baseline_fixture_sha256: "0ba367511b5b78f8fa087adfa8457c5ed2b8d1830e7162cc9634c2da8baa0ee2",
        overload_id: "sim.native.model.spectral-norm.module-lifecycle.v1",
        ordered_parameters_json: r#"[{"name":"module","kind":"positional_or_keyword","type":"&mut NativeModule","default":null,"keyword_only":false},{"name":"name","kind":"positional_or_keyword","type":"&str","default":"weight","keyword_only":false},{"name":"power_iterations","kind":"positional_or_keyword","type":"usize","default":1,"keyword_only":false},{"name":"epsilon","kind":"positional_or_keyword","type":"f32","default":1e-12,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"Option<usize>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["&mut NativeModule"]"#,
        rust_signature: "fn comfy_model::spectral_norm_exact_native(module: &mut NativeModule, name: &str, power_iterations: usize, epsilon: f32, dimension: Option<usize>, cancellation: &CancellationToken) -> Result<&mut NativeModule, NativeOpsError>",
        mutation_rule: "atomically registers canonical NativeModule parametrization",
        alias_rule: "returns the same module borrow",
        shape_rule: "dimension must address the canonical weight shape",
        dtype_rule: "materialization preserves original parameter dtype",
        accumulation_dtype: "F64 sigma with F32 power vectors",
        layout_rule: "materialized canonical parameter layout",
        device_rule: "canonical module parameter device",
        numeric_rule: "deterministic power iteration and division by dominant singular value",
        tolerance: "1e-5 absolute for F32",
        determinism: "fixed row and column traversal",
        cancellation_points: "registration, materialization iterations, and publication boundaries",
        vjp_rule: "module construction boundary; downstream tensor autograd owns gradients",
        jvp_rule: "module construction boundary; downstream tensor autograd owns tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/spectral_norm.json",
        evidence_fixture_sha256: "424546407799037a0273a18b548932dfba8340a28eb09597d2b72b90823f23ec",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BD0C27F1B551",
        baseline_overload_id: "COMFY-TENSOR-OP-BD0C27F1B551:blocked",
        baseline_fixture_sha256: "aea5e8286e1cae3f88d707eea768cafabb7377632f70656e959aad4f3dd5983e",
        overload_id: "sim.native.tensor.roll.cpu-byte-preserving.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"shifts","kind":"positional_or_keyword","type":"&[i64]","default":null,"keyword_only":false},{"name":"dimensions","kind":"positional_or_keyword","type":"Option<&[i64]>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn roll_with_context_exact_native(backend: &CpuBackend, input: &Tensor, shifts: &[i64], dimensions: Option<&[i64]>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape; absent dimensions flatten logically",
        dtype_rule: "byte preserving for every canonical dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "contiguous output from logical input traversal",
        device_rule: "CPU ordinal zero",
        numeric_rule: "modular permutation with repeated dimensions accumulated",
        tolerance: "bit exact",
        determinism: "row-major output traversal",
        cancellation_points: "bounded element intervals and atomic upload",
        vjp_rule: "inverse roll of output gradient",
        jvp_rule: "forward roll of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/roll.json",
        evidence_fixture_sha256: "db55cc9660c826bb1b11f680f417ae628f312e9ee7c77790917c8ae8063fd4f8",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BE1F415B5A74",
        baseline_overload_id: "COMFY-TENSOR-OP-BE1F415B5A74:blocked",
        baseline_fixture_sha256: "1f1d8aa754f6a87f805ca56ce7e2929d02431fbdec87a781826c0dd858c492da",
        overload_id: "sim.native.tensor.tensor-split.readonly-views.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"specification","kind":"positional_or_keyword","type":"Sections(u64)|Indices(Vec<i64>)","default":null,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"i64","default":0,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn tensor_split_exact_native(input: &Tensor, specification: &TensorSplitSpec, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "read only",
        alias_rule: "read-only views share canonical input storage",
        shape_rule: "balanced sections or clamped index slices along normalized dimension",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "F32 for cataloged VJP",
        layout_rule: "preserves input strides with adjusted shape and offset",
        device_rule: "CPU ordinal zero",
        numeric_rule: "no value transformation",
        tolerance: "bit exact",
        determinism: "declared split order",
        cancellation_points: "bounded output and gradient scatter intervals",
        vjp_rule: "scatter-add output gradients into input shape",
        jvp_rule: "identical read-only split of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/tensor_split.json",
        evidence_fixture_sha256: "7897a41368336d280696698b2ba61a6e4cdfa84ac273b16c3def9499410fed88",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-BF0B50BCC3B4",
        baseline_overload_id: "COMFY-TENSOR-OP-BF0B50BCC3B4:blocked",
        baseline_fixture_sha256: "e7f5af7a1c6f3be875295a670ee21d9e539ba76e0da34383c0e36856b895e94c",
        overload_id: "sim.native.worker.xpu-is-available.topology.v1",
        ordered_parameters_json: r#"[{"name":"topology","kind":"positional_or_keyword","type":"&MemoryTopology","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn comfy_worker::xpu_is_available_exact_native(topology: &MemoryTopology, cancellation: &CancellationToken) -> Result<bool, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "copyable bool",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u32 device count",
        layout_rule: "not applicable",
        device_rule: "counts exact XPU device-kind entries",
        numeric_rule: "true exactly when canonical topology has at least one XPU",
        tolerance: "exact",
        determinism: "immutable topology traversal",
        cancellation_points: "before and after canonical count",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/xpu_is_available.json",
        evidence_fixture_sha256: "5665b3dc382e373912306ce7376b3fc80d7b0999bcb19fb57bbb6002f945b2af",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_17",
        operation_id: "COMFY-TENSOR-OP-B91A910A5AF9",
        baseline_overload_id: "COMFY-TENSOR-OP-B91A910A5AF9:blocked",
        baseline_fixture_sha256: "42058f33642a787324b400bc94437bd94d0b9486999509f81e67d4cce4cece3d",
        overload_id: "sim.native.tensor.xpu-synchronize.event-fence.v1",
        ordered_parameters_json: r#"[{"name":"backend","kind":"positional_or_keyword","type":"&dyn TensorBackend","default":null,"keyword_only":false},{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"execution","kind":"positional_or_keyword","type":"&ExecutionContext","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["()"]"#,
        rust_signature: "fn xpu_synchronize_exact_native(backend: &dyn TensorBackend, capabilities: &BackendCapabilityMatrix, execution: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartSeventeenError>",
        mutation_rule: "records and waits through the canonical backend event owner",
        alias_rule: "not applicable",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "backend and capability matrix must name the same XPU device",
        numeric_rule: "completion follows one canonical stream event fence",
        tolerance: "exact",
        determinism: "stream-ordered event sequence",
        cancellation_points: "before record and after wait through ExecutionContext",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-b91a910a5af9",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_17/xpu_synchronize.json",
        evidence_fixture_sha256: "dcb6ef374c5263085ace2df40b6f93bda909ab8a81a929885c138b8071d56d4b",
    },
]
