&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-DDAAD49116D0",
        baseline_overload_id: "COMFY-TENSOR-OP-DDAAD49116D0:blocked",
        baseline_fixture_sha256: "7a4da6d4da56b6f6b5d0c5982b6a4148855abb27f54c04d366635b4be1d7b670",
        overload_id: "zed.native.model.alias-free-activation1d.v1",
        ordered_parameters_json: r#"[{"name":"activation","kind":"positional_or_keyword","type":"PeriodicActivation","default":null,"keyword_only":false},{"name":"up_ratio","kind":"keyword_only","type":"usize","default":2,"keyword_only":true},{"name":"down_ratio","kind":"keyword_only","type":"usize","default":2,"keyword_only":true},{"name":"up_kernel_size","kind":"keyword_only","type":"usize","default":12,"keyword_only":true},{"name":"down_kernel_size","kind":"keyword_only","type":"usize","default":12,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeAliasFreeActivation1d"]"#,
        rust_signature: "fn comfy_model::alias_free_activation_1d_exact_native(activation: PeriodicActivation, up_ratio: usize, down_ratio: usize, up_kernel_size: usize, down_kernel_size: usize, cancellation: &CancellationToken) -> Result<NativeAliasFreeActivation1d, AliasFreeActivationError>",
        mutation_rule: "constructs immutable native module state; forward stages a fresh tensor",
        alias_rule: "extends NativeModule base lifecycle and owns only focused periodic parameters and fixed Kaiser-sinc buffers",
        shape_rule: "forward accepts BCT and applies exact upsample-activation-downsample geometry",
        dtype_rule: "certified CPU F32 forward",
        accumulation_dtype: "F32 with f64 filter construction",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU reference; certified backends may add native kernels without fallback",
        numeric_rule: "normalized Kaiser-sinc depthwise resampling and Snake or SnakeBeta equation",
        tolerance: "1e-5 absolute",
        determinism: "fixed filter and traversal order",
        cancellation_points: "before construction, bounded filter/traversal points, and before publication",
        vjp_rule: "constructor is not differentiable; model forward autograd is owned by the later model-family graph",
        jvp_rule: "constructor has no tangent; model forward tangent is owned by the later model-family graph",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/activation_1d.json",
        evidence_fixture_sha256: "57069a0e1c4e101f40448a0610de6006aa41a045d46e6b500f604e4a4cc4960c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E644686B4E0F",
        baseline_overload_id: "COMFY-TENSOR-OP-E644686B4E0F:blocked",
        baseline_fixture_sha256: "acee81433e64383f797d194a89da5ae90458f650ba93966ac24e4083e95ac47d",
        overload_id: "zed.native.tensor.broadcast-tensors.read-only-views.v1",
        ordered_parameters_json: r#"[{"name":"inputs","kind":"variadic_positional","type":"&[Tensor]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn broadcast_tensors_exact_native(inputs: &[Tensor], cancellation: &CancellationToken) -> Result<Vec<Tensor>, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "read only",
        alias_rule: "returns canonical read-only zero-stride Tensor views sharing source storage",
        shape_rule: "folds canonical binary broadcast shape across one or more inputs",
        dtype_rule: "preserves each input dtype independently",
        accumulation_dtype: "not applicable",
        layout_rule: "checked strided views with zero strides only on expanded singleton or missing dimensions",
        device_rule: "all inputs share one canonical device and stream",
        numeric_rule: "logical values repeat exactly without copy",
        tolerance: "bit exact",
        determinism: "input order and canonical trailing-axis broadcast",
        cancellation_points: "at every public forward or derivative boundary, per input or reduction interval, and before publication",
        vjp_rule: "reduces output gradient across inserted and expanded axes",
        jvp_rule: "broadcasts input tangent through the same read-only view geometry",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/broadcast_tensors.json",
        evidence_fixture_sha256: "c5be835f088781148a92db4e87a48b482096760c6c44cfb093f73f600b6f7144",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-D6F57272FC58",
        baseline_overload_id: "COMFY-TENSOR-OP-D6F57272FC58:blocked",
        baseline_fixture_sha256: "5cc4e7e46d745676a005dbd1514a67fc8542c28d4560a30377efc610603d9d26",
        overload_id: "zed.native.tensor.cross.f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"Option<i64>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn cross_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, dimension: Option<i64>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical output",
        shape_rule: "equal shapes with a selected length-three axis; omitted dimension chooses the first length-three axis",
        dtype_rule: "certified F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "logical view traversal and contiguous output",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "right-handed three-component cross product",
        tolerance: "1e-6 absolute",
        determinism: "row-major logical traversal",
        cancellation_points: "at every public forward or derivative boundary before validation, bounded element intervals, and upload",
        vjp_rule: "input gradient is other cross output-gradient; other gradient is output-gradient cross input",
        jvp_rule: "input-tangent cross other plus input cross other-tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/cross.json",
        evidence_fixture_sha256: "8cbedfb32c94544388efc445de2310517db58bd45defc79b6836b31ce48c6ed3",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E237E236E06A",
        baseline_overload_id: "COMFY-TENSOR-OP-E237E236E06A:blocked",
        baseline_fixture_sha256: "c1d68937ab9dd40eea7bf2ac0528db257aae693d1be233ecf11de9cd7e227740",
        overload_id: "zed.native.tensor.cuda-stream.task61-adapter.v1",
        ordered_parameters_json: r#"[{"name":"registry","kind":"positional_or_keyword","type":"&NativeStreamRegistry","default":null,"keyword_only":false},{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"keyword_only","type":"DeviceId","default":null,"keyword_only":true},{"name":"priority","kind":"keyword_only","type":"i32","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeStream"]"#,
        rust_signature: "fn cuda_stream_exact_native(registry: &NativeStreamRegistry, capabilities: &BackendCapabilityMatrix, device: DeviceId, priority: i32, cancellation: &CancellationToken) -> Result<NativeStream, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "allocates one canonical stream identity through Task 61",
        alias_rule: "thin source-call adapter over NativeStreamRegistry",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 identity",
        layout_rule: "not applicable",
        device_rule: "exact CUDA or ROCm capability device",
        numeric_rule: "preserves priority and canonical allocation order",
        tolerance: "exact",
        determinism: "registry allocation order",
        cancellation_points: "at the public adapter boundary before device validation and canonical identifier allocation",
        vjp_rule: "stream metadata is not differentiable",
        jvp_rule: "stream metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/cuda_stream.json",
        evidence_fixture_sha256: "deb215b8c566c42ca33586d17b6236c62d94a73a223984f96c9185554626d2a1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-D718FC279D3E",
        baseline_overload_id: "COMFY-TENSOR-OP-D718FC279D3E:blocked",
        baseline_fixture_sha256: "9d67f36167fe623557b35c61ac181f2148d178f80188d530925a61d7d350dce8",
        overload_id: "zed.native.tensor.cuda-synchronize.canonical-event-fence.v1",
        ordered_parameters_json: r#"[{"name":"backend","kind":"positional_or_keyword","type":"&dyn TensorBackend","default":null,"keyword_only":false},{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"execution","kind":"positional_or_keyword","type":"&ExecutionContext","default":null,"keyword_only":false}]"#,
        output_arity: "0",
        output_types_json: r#"[]"#,
        rust_signature: "fn cuda_synchronize_exact_native(backend: &dyn TensorBackend, capabilities: &BackendCapabilityMatrix, execution: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartTwentyError>",
        mutation_rule: "records and waits for one canonical event fence",
        alias_rule: "delegates all fence state and validation to TensorBackend and the canonical synchronization owner",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked fence sequence",
        layout_rule: "not applicable",
        device_rule: "exact CUDA or ROCm backend and capability device",
        numeric_rule: "waits through a backend event rather than process-global busy polling",
        tolerance: "exact",
        determinism: "backend event sequence",
        cancellation_points: "at the public adapter boundary before validation or record, within backend operations, and after wait",
        vjp_rule: "synchronization is not differentiable",
        jvp_rule: "synchronization has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/cuda_synchronize.json",
        evidence_fixture_sha256: "ac21104e3a6005f4e7ae35b40d6b03fee69a43851122650a8b33038cca197ea7",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E01C0CE81BB1",
        baseline_overload_id: "COMFY-TENSOR-OP-E01C0CE81BB1:blocked",
        baseline_fixture_sha256: "29301a17c32efc68b41f41e662a94ad6a09cf2eab0146754f732f306566ba423",
        overload_id: "zed.native.tensor.directml-device-name.canonical-properties.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["String"]"#,
        rust_signature: "fn directml_device_name_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<String, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "read only",
        alias_rule: "projects an owned name through the canonical device-property validation owner",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "exact DirectML capability device with certified native properties",
        numeric_rule: "preserves canonical UTF-8 property name",
        tolerance: "exact UTF-8",
        determinism: "immutable capability matrix",
        cancellation_points: "at the public adapter boundary before validation and before publication",
        vjp_rule: "device metadata is not differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/directml_device_name.json",
        evidence_fixture_sha256: "0e6d19cbf1bd7728cc14de0063e160c7c6fbf157e6ab15f67a796cb4b0b838b3",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E07BBEBA226B",
        baseline_overload_id: "COMFY-TENSOR-OP-E07BBEBA226B:blocked",
        baseline_fixture_sha256: "4630744f67c01a9b567d3c631d82171e63eb4e113cf4e90ff1f998f833d8513d",
        overload_id: "zed.native.tensor.flip.task57-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimensions","kind":"positional_or_keyword","type":"&[i64]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn flip_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 57 generic byte-preserving axis reversal",
        shape_rule: "preserves shape and requires unique normalized dimensions",
        dtype_rule: "preserves canonical dtype bytes",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "reverses selected axes exactly once",
        tolerance: "bit exact",
        determinism: "canonical logical traversal",
        cancellation_points: "at every public forward or derivative adapter boundary and canonical flip checkpoints",
        vjp_rule: "self-inverse flip of output gradient",
        jvp_rule: "flip of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/flip.json",
        evidence_fixture_sha256: "6df47bddfb78098ff3c219cdddb7f68ba148c5ed900306ae7a0a97f92c394d7f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-D5D333C89A34",
        baseline_overload_id: "COMFY-TENSOR-OP-D5D333C89A34:blocked",
        baseline_fixture_sha256: "4bee41c0bd7363e3ac68aeffd2c45c501cb143ee961871a520f716ae32a26097",
        overload_id: "zed.native.tensor.int-method.canonical-cast-i32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I32>"]"#,
        rust_signature: "fn int_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "out of place unless canonical cast returns an exact identity, which cannot occur for non-I32 input",
        alias_rule: "delegates canonical cast_to storage and publication semantics",
        shape_rule: "preserves shape",
        dtype_rule: "casts to canonical I32 with source conversion rules",
        accumulation_dtype: "I32",
        layout_rule: "canonical cast output layout",
        device_rule: "preserves canonical input device through the certified cast owner",
        numeric_rule: "canonical dtype conversion including truncation and range behavior",
        tolerance: "exact",
        determinism: "canonical cast traversal",
        cancellation_points: "at the public adapter boundary and canonical cast checkpoints",
        vjp_rule: "integral cast is non-differentiable",
        jvp_rule: "integral cast has no floating tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/int_method.json",
        evidence_fixture_sha256: "637203b3180422e5fdcc9a30058deebc31ba8cf4db0c004ede6cfc5f5bb4dab8",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-D54F52B18FB1",
        baseline_overload_id: "COMFY-TENSOR-OP-D54F52B18FB1:blocked",
        baseline_fixture_sha256: "fd54e91264a8fe626d3d3646d95a8b58864c6123fc5e8695165223c6ecd398ef",
        overload_id: "zed.native.model.mem-efficient-sdp.immutable-selection.v1",
        ordered_parameters_json: r#"[{"name":"enabled","kind":"positional_or_keyword","type":"bool","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["MathSdpSelection"]"#,
        rust_signature: "fn comfy_model::enable_mem_efficient_sdp_exact_native(enabled: bool, cancellation: &CancellationToken) -> Result<MathSdpSelection, AttentionError>",
        mutation_rule: "returns immutable execution-scoped selection without global mutation",
        alias_rule: "comfy_model::attention remains the sole attention policy owner",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "selection is consumed only by a certified native attention backend",
        numeric_rule: "enabled selects exact native memory-efficient reference SDP and disabled rejects that selection",
        tolerance: "exact",
        determinism: "input boolean",
        cancellation_points: "before selection publication",
        vjp_rule: "policy metadata is not differentiable",
        jvp_rule: "policy metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/mem_efficient_sdp.json",
        evidence_fixture_sha256: "9aa5a66e0298d5d8d70862cf050cfbce2430f2a6d0d71f0f8e5e447434de1d6a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-D54AF27B4D70",
        baseline_overload_id: "COMFY-TENSOR-OP-D54AF27B4D70:blocked",
        baseline_fixture_sha256: "3e482c5f1241183c95d92c789b898692af7dc25328dbbc99f201cc84786db684",
        overload_id: "zed.native.model.module-init.container.v1",
        ordered_parameters_json: r#"[]"#,
        output_arity: "1",
        output_types_json: r#"["NativeModule"]"#,
        rust_signature: "fn comfy_model::module_init_exact_native(cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs an empty canonical NativeModule container",
        alias_rule: "NativeModule remains the sole module generation and parameter lifecycle owner",
        shape_rule: "contains no parameters or forward geometry",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent until parameters are loaded by a concrete module",
        numeric_rule: "generation begins at zero with no prefetched or parametrized state",
        tolerance: "exact",
        determinism: "fixed canonical base-module identity",
        cancellation_points: "before construction and publication",
        vjp_rule: "module initialization is not differentiable",
        jvp_rule: "module initialization has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/module_init.json",
        evidence_fixture_sha256: "07b91d5bab204f3a4a683224be8d714ea936e2c4d098beaa2b271bd3a6aaee8b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E430CCED2202",
        baseline_overload_id: "COMFY-TENSOR-OP-E430CCED2202:blocked",
        baseline_fixture_sha256: "35a516e70c15d79d22e77c717539ffc7833d39074a09ffff5ec252e64587050a",
        overload_id: "zed.native.tensor.softmax-method.canonical-functional.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn softmax_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "out of place",
        alias_rule: "delegates the canonical activation-normalization softmax owner",
        shape_rule: "preserves shape over one normalized dimension",
        dtype_rule: "certified F32 overload",
        accumulation_dtype: "F32 stable reduction",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU reference and input stream",
        numeric_rule: "max-subtracted exponentiation with canonical reduction order",
        tolerance: "1e-6 absolute",
        determinism: "canonical softmax reduction order",
        cancellation_points: "at every public forward or derivative adapter boundary and canonical reduction checkpoints",
        vjp_rule: "canonical y times gradient-minus-dot map",
        jvp_rule: "canonical y times tangent-minus-dot map",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/softmax_method.json",
        evidence_fixture_sha256: "1b6b07e589cca411c86f31c97b1054808f811ac67ddeb1e46ce7c80a4d9bbb4e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E0C529F06769",
        baseline_overload_id: "COMFY-TENSOR-OP-E0C529F06769:blocked",
        baseline_fixture_sha256: "60ca7fb40e34b4877a3c495e9f0b0837fc21a1d0edf3f2739609d874c931ca6c",
        overload_id: "zed.native.tensor.swapaxes.read-only-view.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"axis_zero","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false},{"name":"axis_one","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn swapaxes_exact_native(input: &Tensor, axis_zero: i64, axis_one: i64, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "read only",
        alias_rule: "returns a canonical read-only Tensor view sharing storage",
        shape_rule: "swaps two normalized shape dimensions",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "swaps descriptor strides and marks the checked view strided",
        device_rule: "preserves device and stream",
        numeric_rule: "logical values are transposed without copy",
        tolerance: "bit exact",
        determinism: "descriptor permutation",
        cancellation_points: "at every public forward or derivative boundary before descriptor construction and publication",
        vjp_rule: "self-inverse swap of output gradient",
        jvp_rule: "same swap of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/swapaxes.json",
        evidence_fixture_sha256: "bcbe561d9a0427e2d723f96fb4651f061c89fb9ebe75913cc91998526ad825e9",
    },
]
