&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9C679FFC6CCF",
        baseline_overload_id: "COMFY-TENSOR-OP-9C679FFC6CCF:blocked",
        baseline_fixture_sha256: "84ae7de37f1b5e86cff23df0b784c0b0480029e819a804d1d5fd35bbd3a54c78",
        overload_id: "zed.native.tensor.lerp.canonical-binary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"end","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"weight","kind":"positional_or_keyword","type":"f32","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn lerp_with_context_exact_native(backend: &CpuBackend, input: &Tensor, end: &Tensor, weight: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical binary primitives and returns fresh storage",
        shape_rule: "NumPy-style input/end broadcasting",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero with matching streams",
        numeric_rule: "input + weight * (end - input)",
        tolerance: "absolute 0.00001",
        determinism: "canonical binary traversal",
        cancellation_points: "primitive boundaries and derivative traversal",
        vjp_rule: "broadcast-reduced (1-weight) and weight gradients",
        jvp_rule: "the same affine interpolation over tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/lerp.json",
        evidence_fixture_sha256: "0a8ecef7afc65f0955bd5bc4e4fdd6e1c88b5a169effcdcaf684ccb88eb073b5",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9547009E77B6",
        baseline_overload_id: "COMFY-TENSOR-OP-9547009E77B6:blocked",
        baseline_fixture_sha256: "41990d0230ce66bf19e5bda5166c8c2fbafbdbd1a590e068e4151b74e145a0fa",
        overload_id: "zed.native.tensor.sign-method.canonical-unary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn tensor_sign_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 54 canonical Signum unary primitive",
        shape_rule: "preserves shape",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "negative, signed-zero, positive and NaN sign semantics from canonical Signum",
        tolerance: "exact",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical unary checkpoints",
        vjp_rule: "zero almost everywhere via Task 54",
        jvp_rule: "zero almost everywhere via Task 54",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/sign_method.json",
        evidence_fixture_sha256: "fbb52fea9ab667b396216734cda1c5c3b85b1c0d23e7580e2567b81250aea86a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9443F2A50F6D",
        baseline_overload_id: "COMFY-TENSOR-OP-9443F2A50F6D:blocked",
        baseline_fixture_sha256: "13e821023da3b9456a3e7b46bc464b87b9d19510221310f5668de87e19ce8189",
        overload_id: "zed.native.tensor.addmm.linear-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"matrix1","kind":"positional_or_keyword","type":"Tensor<F32,rank=2>","default":null,"keyword_only":false},{"name":"matrix2","kind":"positional_or_keyword","type":"Tensor<F32,rank=2>","default":null,"keyword_only":false},{"name":"beta","kind":"keyword_only","type":"f32","default":1.0,"keyword_only":true},{"name":"alpha","kind":"keyword_only","type":"f32","default":1.0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn addmm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, matrix1: &Tensor, matrix2: &Tensor, beta: f32, alpha: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates the canonical native linear equation and returns fresh storage",
        shape_rule: "rank-two compatible matrices plus broadcast-compatible input",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU ordinal zero with matching streams",
        numeric_rule: "beta * input + alpha * matrix1 @ matrix2",
        tolerance: "absolute 0.00001",
        determinism: "fixed matrix traversal inherited from native linear",
        cancellation_points: "linear and broadcast traversal checkpoints",
        vjp_rule: "linear VJP plus broadcast-reduced input gradient",
        jvp_rule: "linear JVP plus scaled input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/addmm.json",
        evidence_fixture_sha256: "c8c744390de65fb9d4fb4d1069292836ffe8ccc0fdbdd1d02e7955d913d6a688",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9285B877ECB7",
        baseline_overload_id: "COMFY-TENSOR-OP-9285B877ECB7:blocked",
        baseline_fixture_sha256: "effa434eb30fa3a8df030c31b015e0f389f65b25456ead59bb966d852e9f043e",
        overload_id: "zed.native.tensor.allclose.isclose-reduction.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"relative_tolerance","kind":"keyword_only","type":"f32","default":0.00001,"keyword_only":true},{"name":"absolute_tolerance","kind":"keyword_only","type":"f32","default":0.00000001,"keyword_only":true},{"name":"equal_nan","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn allclose_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, relative_tolerance: f32, absolute_tolerance: f32, equal_nan: bool, context: &ExecutionContext<'_>) -> Result<bool, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "read only",
        alias_rule: "reduces Task 54 canonical isclose output",
        shape_rule: "broadcast-compatible inputs",
        dtype_rule: "F32 inputs and boolean intermediate",
        accumulation_dtype: "not applicable",
        layout_rule: "logical traversal",
        device_rule: "CPU ordinal zero",
        numeric_rule: "all(abs(input-other) <= atol + rtol*abs(other)) with equal_nan option",
        tolerance: "exact boolean",
        determinism: "fixed reduction order",
        cancellation_points: "isclose and reduction traversal",
        vjp_rule: "non-differentiable boolean result",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/allclose.json",
        evidence_fixture_sha256: "9b3427a288bc50bfff7a05d0acaed8ca26171f2ea9af4268c6b0a32a2d0919d4",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9CC2489AFA14",
        baseline_overload_id: "COMFY-TENSOR-OP-9CC2489AFA14:blocked",
        baseline_fixture_sha256: "7a527bcd1d69ca3f3219b8e16466f5234fa2bac934fef40b1a8e78197c144d0e",
        overload_id: "zed.native.device.cuda.bf16.capability-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix<Cuda>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn cuda_is_bf16_supported_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "read only",
        alias_rule: "projects the canonical backend capability matrix",
        shape_rule: "not applicable",
        dtype_rule: "queries Bf16 support",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "CUDA capability matrix only",
        numeric_rule: "exact capability membership",
        tolerance: "exact",
        determinism: "immutable projection",
        cancellation_points: "before and after projection",
        vjp_rule: "device query is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/cuda_bf16.json",
        evidence_fixture_sha256: "1b0585df44d44341937bd57dd8c17f8e689d107aed8f4a5d9a68e94db5fca567",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9B68023167CF",
        baseline_overload_id: "COMFY-TENSOR-OP-9B68023167CF:blocked",
        baseline_fixture_sha256: "e6d45be281418a6703fc918f1ee90194a6371ccfa5de14784cb64c44018dc660",
        overload_id: "zed.native.tensor.empty-like.canonical-allocation.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"optional<DType>","default":null,"keyword_only":true},{"name":"device","kind":"keyword_only","type":"optional<DeviceId>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn empty_like_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dtype: Option<DType>, device: Option<DeviceId>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "allocates fresh writable storage",
        alias_rule: "delegates TensorDescriptor preserving-format derivation and TensorBackend allocation",
        shape_rule: "preserves input shape",
        dtype_rule: "preserves input dtype unless explicitly overridden",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves non-overlapping format and canonicalizes overlapping format",
        device_rule: "exact CPU native allocation in this implementation",
        numeric_rule: "element values are intentionally unspecified",
        tolerance: "not applicable",
        determinism: "descriptor and allocation identity are deterministic; values are not observable by contract",
        cancellation_points: "backend allocation checkpoints",
        vjp_rule: "allocation is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/empty_like.json",
        evidence_fixture_sha256: "50635bcf9d45e9b44b7a610d34553f6870dffaa928c56057e117e47f8610dc07",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-97058675DD67",
        baseline_overload_id: "COMFY-TENSOR-OP-97058675DD67:blocked",
        baseline_fixture_sha256: "df58de111ac370b69bb9239088a72e0597536fbbd570c0623eb4c54ec59cd76a",
        overload_id: "zed.native.device.mlu.available.topology-projection.v1",
        ordered_parameters_json: r#"[{"name":"topology","kind":"positional_or_keyword","type":"MemoryTopology","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn mlu_is_available_exact_native(topology: &MemoryTopology, context: &ExecutionContext<'_>) -> Result<bool, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "delegates canonical worker MemoryTopology device count",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "u32 checked count",
        layout_rule: "not applicable",
        device_rule: "MLU topology entries",
        numeric_rule: "true exactly when at least one MLU device is present",
        tolerance: "exact",
        determinism: "topology projection",
        cancellation_points: "before and after count",
        vjp_rule: "device query is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/mlu_available.json",
        evidence_fixture_sha256: "c66bc64b3e05eb26b09c53b890703ead362a2f01d7f978988b74b9417b1df0bc",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-8F0ACDA02879",
        baseline_overload_id: "COMFY-TENSOR-OP-8F0ACDA02879:blocked",
        baseline_fixture_sha256: "6cecfcbea73979d35b9496927ae84ed2da83ca7b873baf518ac5ae29f79646af",
        overload_id: "zed.native.device.mlu.memory-info.accounting-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix<Mlu>","default":null,"keyword_only":false},{"name":"topology","kind":"positional_or_keyword","type":"MemoryTopology","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["tuple<u64,u64>"]"#,
        rust_signature: "fn mlu_mem_get_info_exact_native(capabilities: &BackendCapabilityMatrix, topology: &MemoryTopology, snapshot: &MemoryAccountingSnapshot, context: &ExecutionContext<'_>) -> Result<(u64, u64), NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "projects worker-owned topology and accounting snapshot",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "u64 checked accounting",
        layout_rule: "not applicable",
        device_rule: "matching MLU capability, topology and snapshot device",
        numeric_rule: "free equals capacity minus active bytes; total equals topology capacity",
        tolerance: "exact bytes",
        determinism: "canonical accounting projection",
        cancellation_points: "before and after projection",
        vjp_rule: "memory diagnostics are non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/mlu_mem_get_info.json",
        evidence_fixture_sha256: "409f3dc8cdf0817ac19b39ce339655007f69050db501be6038d08a0690564a44",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-8F6CC1A0A7AC",
        baseline_overload_id: "COMFY-TENSOR-OP-8F6CC1A0A7AC:blocked",
        baseline_fixture_sha256: "138621b2667b3473f4ae568ebb30370598714a9910e2243011fea95baf7096b6",
        overload_id: "zed.native.tensor.quantile.linear-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"quantile","kind":"positional_or_keyword","type":"f32[0,1]","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"optional<i64>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn quantile_with_context_exact_native(backend: &CpuBackend, input: &Tensor, quantile: f32, dimension: Option<i64>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output storage",
        shape_rule: "flattened scalar or selected-axis reduction with checked negative axes",
        dtype_rule: "F32",
        accumulation_dtype: "F32 linear interpolation",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "stable ascending selection with linear interpolation and NaN propagation",
        tolerance: "absolute 0.00001",
        determinism: "stable original-index tie ordering",
        cancellation_points: "group collection, selection and upload",
        vjp_rule: "scatter interpolation weights to selected ranks",
        jvp_rule: "interpolate selected input tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/quantile.json",
        evidence_fixture_sha256: "a797623aff1878c0293e25d7e48e440af8daa41d0d8bc1ac80f8ec0c262503c7",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9BE377B59853",
        baseline_overload_id: "COMFY-TENSOR-OP-9BE377B59853:blocked",
        baseline_fixture_sha256: "0fbd771a0c947ed984a1c96b3fdf9166bcda05246a2644edf4e2f0e75e58638f",
        overload_id: "zed.native.tensor.softmax.functional-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn softmax_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical activation functional softmax and returns fresh storage",
        shape_rule: "preserves shape with checked signed axis",
        dtype_rule: "F32",
        accumulation_dtype: "F32 max-subtracted exponential sum",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "max-subtracted normalized exponential",
        tolerance: "absolute 0.00001",
        determinism: "canonical functional traversal",
        cancellation_points: "functional row and upload checkpoints",
        vjp_rule: "canonical softmax Jacobian-vector product",
        jvp_rule: "canonical softmax Jacobian-vector product",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/softmax.json",
        evidence_fixture_sha256: "aaacfebc88192a6740d71f0101dcdbf18d13b817ee8b0faf88d9ada20f2177e0",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-999B3107D90B",
        baseline_overload_id: "COMFY-TENSOR-OP-999B3107D90B:blocked",
        baseline_fixture_sha256: "c6392b51eb7f067e71eef8c09a49096610bdb3aba44dd6f2ebc32e8f55a30709",
        overload_id: "zed.native.runtime.deterministic-algorithms.explicit-policy.v1",
        ordered_parameters_json: r#"[{"name":"enabled","kind":"positional_or_keyword","type":"bool","default":null,"keyword_only":false},{"name":"warn_only","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["DeterministicAlgorithmsPolicy"]"#,
        rust_signature: "fn use_deterministic_algorithms_exact_native(enabled: bool, warn_only: bool, cancellation: &CancellationToken) -> Result<DeterministicAlgorithmsPolicy, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "constructs an immutable execution policy; no global mutable state",
        alias_rule: "policy evaluates canonical BackendCapabilityMatrix determinism",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "backend-independent policy with matrix evaluation",
        numeric_rule: "allowed, warn or reject according to enabled/warn-only and deterministic capability membership",
        tolerance: "exact",
        determinism: "explicit immutable policy",
        cancellation_points: "before policy construction",
        vjp_rule: "runtime policy is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/deterministic_algorithms.json",
        evidence_fixture_sha256: "8ad970c124f4b25e93581ee400c0cbcfa06945243768b702aa68b3b0496bc317",
    },
]
