&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-DDAAD49116D0",
        baseline_overload_id: "COMFY-TENSOR-OP-DDAAD49116D0:blocked",
        baseline_fixture_sha256: "4c3a75e3321f68c5ff3d5b6539bb9fa699ca89b8ea9c6a4a6e2bb53a3efb74ff",
        overload_id: "sim.native.model.alias-free-activation1d.v1",
        ordered_parameters_json: r#"[{"name":"activation","kind":"positional_or_keyword","type":"PeriodicActivation","default":null,"keyword_only":false},{"name":"up_ratio","kind":"keyword_only","type":"usize","default":2,"keyword_only":true},{"name":"down_ratio","kind":"keyword_only","type":"usize","default":2,"keyword_only":true},{"name":"up_kernel_size","kind":"keyword_only","type":"usize","default":12,"keyword_only":true},{"name":"down_kernel_size","kind":"keyword_only","type":"usize","default":12,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeAliasFreeActivation1d"]"#,
        rust_signature: "fn comfy_model::alias_free_activation_1d_exact_native(activation: PeriodicActivation, up_ratio: usize, down_ratio: usize, up_kernel_size: usize, down_kernel_size: usize, cancellation: &CancellationToken) -> Result<NativeAliasFreeActivation1d, AliasFreeActivationError>",
        mutation_rule: "constructs immutable native module state; forward stages a fresh tensor",
        alias_rule: "extends NativeModule base lifecycle and owns only focused periodic parameters and fixed Kaiser-sinc buffers",
        shape_rule: "forward accepts BCT and applies exact upsample-activation-downsample geometry",
        dtype_rule: "certified CPU F32 forward",
        accumulation_dtype: "F32 with f64 filter construction",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU reference; certified backends may add native kernels without fallback",
        numeric_rule: "normalized Kaiser-sinc depthwise resampling and Snake or SnakeBeta equation",
        tolerance: "1e-5 absolute",
        determinism: "fixed filter and traversal order",
        cancellation_points: "before construction, bounded filter/traversal points, and before publication",
        vjp_rule: "constructor is not differentiable; model forward autograd is owned by the later model-family graph",
        jvp_rule: "constructor has no tangent; model forward tangent is owned by the later model-family graph",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/activation_1d.json",
        evidence_fixture_sha256: "d0a949f4d488a45570201131521b49ceb022839ef84058b875e130ee4d723400",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E644686B4E0F",
        baseline_overload_id: "COMFY-TENSOR-OP-E644686B4E0F:blocked",
        baseline_fixture_sha256: "73393e5d7135bdb696f6585ac7583e5039b46ccdfdc0e5158bb3d2bf96c0b719",
        overload_id: "sim.native.tensor.broadcast-tensors.read-only-views.v1",
        ordered_parameters_json: r#"[{"name":"inputs","kind":"variadic_positional","type":"&[Tensor]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn broadcast_tensors_exact_native(inputs: &[Tensor], cancellation: &CancellationToken) -> Result<Vec<Tensor>, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "read only",
        alias_rule: "returns canonical read-only zero-stride Tensor views sharing source storage",
        shape_rule: "folds canonical binary broadcast shape across one or more inputs",
        dtype_rule: "preserves each input dtype independently",
        accumulation_dtype: "not applicable",
        layout_rule: "checked strided views with zero strides only on expanded singleton or missing dimensions",
        device_rule: "all inputs share one canonical device and stream",
        numeric_rule: "logical values repeat exactly without copy",
        tolerance: "bit exact",
        determinism: "input order and canonical trailing-axis broadcast",
        cancellation_points: "at every public forward or derivative boundary, per input or reduction interval, and before publication",
        vjp_rule: "reduces output gradient across inserted and expanded axes",
        jvp_rule: "broadcasts input tangent through the same read-only view geometry",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/broadcast_tensors.json",
        evidence_fixture_sha256: "7dc7e01a23d6ae001d7bd7934f5d5143c717169e9e21013df71e4626f656c31b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-D6F57272FC58",
        baseline_overload_id: "COMFY-TENSOR-OP-D6F57272FC58:blocked",
        baseline_fixture_sha256: "f341d1f00fb3a2bb038b319dfb39655206b3158ee96f58d50d078af94533276c",
        overload_id: "sim.native.tensor.cross.f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"Option<i64>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn cross_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, dimension: Option<i64>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical output",
        shape_rule: "equal shapes with a selected length-three axis; omitted dimension chooses the first length-three axis",
        dtype_rule: "certified F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "logical view traversal and contiguous output",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "right-handed three-component cross product",
        tolerance: "1e-6 absolute",
        determinism: "row-major logical traversal",
        cancellation_points: "at every public forward or derivative boundary before validation, bounded element intervals, and upload",
        vjp_rule: "input gradient is other cross output-gradient; other gradient is output-gradient cross input",
        jvp_rule: "input-tangent cross other plus input cross other-tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/cross.json",
        evidence_fixture_sha256: "170bd797f6b03088ba5db441657ad89ca9b4fe4db3faebe1f6eb2d9f7b7bc475",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E237E236E06A",
        baseline_overload_id: "COMFY-TENSOR-OP-E237E236E06A:blocked",
        baseline_fixture_sha256: "4585926f101214d2638898e5a0b45f7a1b1bba67df59ae8978e3572b3707f0e7",
        overload_id: "sim.native.tensor.cuda-stream.task61-adapter.v1",
        ordered_parameters_json: r#"[{"name":"registry","kind":"positional_or_keyword","type":"&NativeStreamRegistry","default":null,"keyword_only":false},{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"keyword_only","type":"DeviceId","default":null,"keyword_only":true},{"name":"priority","kind":"keyword_only","type":"i32","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeStream"]"#,
        rust_signature: "fn cuda_stream_exact_native(registry: &NativeStreamRegistry, capabilities: &BackendCapabilityMatrix, device: DeviceId, priority: i32, cancellation: &CancellationToken) -> Result<NativeStream, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "allocates one canonical stream identity through Task 61",
        alias_rule: "thin source-call adapter over NativeStreamRegistry",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 identity",
        layout_rule: "not applicable",
        device_rule: "exact CUDA or ROCm capability device",
        numeric_rule: "preserves priority and canonical allocation order",
        tolerance: "exact",
        determinism: "registry allocation order",
        cancellation_points: "at the public adapter boundary before device validation and canonical identifier allocation",
        vjp_rule: "stream metadata is not differentiable",
        jvp_rule: "stream metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/cuda_stream.json",
        evidence_fixture_sha256: "9b7c98d6391d3f99c45ffcec99fd3e3f18a2dfec7bb2c12e728110e2232550e2",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-D718FC279D3E",
        baseline_overload_id: "COMFY-TENSOR-OP-D718FC279D3E:blocked",
        baseline_fixture_sha256: "36052dd5cf12dab38311dc323ded35b2be763bf7175c8dc7d0c870ba4258d1ab",
        overload_id: "sim.native.tensor.cuda-synchronize.canonical-event-fence.v1",
        ordered_parameters_json: r#"[{"name":"backend","kind":"positional_or_keyword","type":"&dyn TensorBackend","default":null,"keyword_only":false},{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"execution","kind":"positional_or_keyword","type":"&ExecutionContext","default":null,"keyword_only":false}]"#,
        output_arity: "0",
        output_types_json: r#"[]"#,
        rust_signature: "fn cuda_synchronize_exact_native(backend: &dyn TensorBackend, capabilities: &BackendCapabilityMatrix, execution: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartTwentyError>",
        mutation_rule: "records and waits for one canonical event fence",
        alias_rule: "delegates all fence state and validation to TensorBackend and the canonical synchronization owner",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked fence sequence",
        layout_rule: "not applicable",
        device_rule: "exact CUDA or ROCm backend and capability device",
        numeric_rule: "waits through a backend event rather than process-global busy polling",
        tolerance: "exact",
        determinism: "backend event sequence",
        cancellation_points: "at the public adapter boundary before validation or record, within backend operations, and after wait",
        vjp_rule: "synchronization is not differentiable",
        jvp_rule: "synchronization has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/cuda_synchronize.json",
        evidence_fixture_sha256: "7cf25ac404424b23391cf43f745da463e3aeefef598917afc70dcedca4bbd8c2",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E01C0CE81BB1",
        baseline_overload_id: "COMFY-TENSOR-OP-E01C0CE81BB1:blocked",
        baseline_fixture_sha256: "41acd91558343124580c7a705793b8b7d173ee68e7dfa9b7d89a4144bb4e8736",
        overload_id: "sim.native.tensor.directml-device-name.canonical-properties.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["String"]"#,
        rust_signature: "fn directml_device_name_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<String, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "read only",
        alias_rule: "projects an owned name through the canonical device-property validation owner",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "exact DirectML capability device with certified native properties",
        numeric_rule: "preserves canonical UTF-8 property name",
        tolerance: "exact UTF-8",
        determinism: "immutable capability matrix",
        cancellation_points: "at the public adapter boundary before validation and before publication",
        vjp_rule: "device metadata is not differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/directml_device_name.json",
        evidence_fixture_sha256: "ab41cd0df09ad62fec6496c44d06c73e4e9974a806d2e0c4171501c43982f8ea",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E07BBEBA226B",
        baseline_overload_id: "COMFY-TENSOR-OP-E07BBEBA226B:blocked",
        baseline_fixture_sha256: "384bbe3448aa2e15c75a4ee1566aba61753c2d2a5bf899cda2f965ced70dd2c8",
        overload_id: "sim.native.tensor.flip.task57-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimensions","kind":"positional_or_keyword","type":"&[i64]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn flip_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 57 generic byte-preserving axis reversal",
        shape_rule: "preserves shape and requires unique normalized dimensions",
        dtype_rule: "preserves canonical dtype bytes",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "reverses selected axes exactly once",
        tolerance: "bit exact",
        determinism: "canonical logical traversal",
        cancellation_points: "at every public forward or derivative adapter boundary and canonical flip checkpoints",
        vjp_rule: "self-inverse flip of output gradient",
        jvp_rule: "flip of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/flip.json",
        evidence_fixture_sha256: "69aae4b074779061a279e92506ba73dde816dbddc7413f9a253c2f5aab7b7b16",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-D5D333C89A34",
        baseline_overload_id: "COMFY-TENSOR-OP-D5D333C89A34:blocked",
        baseline_fixture_sha256: "d809dd30ea6dc6d78090d782cbc37c02a8cd0d445cdf60c478a89445d29dd937",
        overload_id: "sim.native.tensor.int-method.canonical-cast-i32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I32>"]"#,
        rust_signature: "fn int_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "out of place unless canonical cast returns an exact identity, which cannot occur for non-I32 input",
        alias_rule: "delegates canonical cast_to storage and publication semantics",
        shape_rule: "preserves shape",
        dtype_rule: "casts to canonical I32 with source conversion rules",
        accumulation_dtype: "I32",
        layout_rule: "canonical cast output layout",
        device_rule: "preserves canonical input device through the certified cast owner",
        numeric_rule: "canonical dtype conversion including truncation and range behavior",
        tolerance: "exact",
        determinism: "canonical cast traversal",
        cancellation_points: "at the public adapter boundary and canonical cast checkpoints",
        vjp_rule: "integral cast is non-differentiable",
        jvp_rule: "integral cast has no floating tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/int_method.json",
        evidence_fixture_sha256: "228c662e44e59a585082d493c7bc3352af903335bad48aab6221d03b1486e1f6",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-D54F52B18FB1",
        baseline_overload_id: "COMFY-TENSOR-OP-D54F52B18FB1:blocked",
        baseline_fixture_sha256: "ea3340c8c662ec8f68a1674a25b881b92d79edb683bbfc21da0b34015bbe8598",
        overload_id: "sim.native.model.mem-efficient-sdp.immutable-selection.v1",
        ordered_parameters_json: r#"[{"name":"enabled","kind":"positional_or_keyword","type":"bool","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["MathSdpSelection"]"#,
        rust_signature: "fn comfy_model::enable_mem_efficient_sdp_exact_native(enabled: bool, cancellation: &CancellationToken) -> Result<MathSdpSelection, AttentionError>",
        mutation_rule: "returns immutable execution-scoped selection without global mutation",
        alias_rule: "comfy_model::attention remains the sole attention policy owner",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "selection is consumed only by a certified native attention backend",
        numeric_rule: "enabled selects exact native memory-efficient reference SDP and disabled rejects that selection",
        tolerance: "exact",
        determinism: "input boolean",
        cancellation_points: "before selection publication",
        vjp_rule: "policy metadata is not differentiable",
        jvp_rule: "policy metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/mem_efficient_sdp.json",
        evidence_fixture_sha256: "422b47634498a1e59dc6b5b09d2d6aa107b27a7be16c842f45cfdc3f9c423aa9",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-D54AF27B4D70",
        baseline_overload_id: "COMFY-TENSOR-OP-D54AF27B4D70:blocked",
        baseline_fixture_sha256: "9552f74c27091bd12364029fb816e02df7c93ef352fb954753fac8a476666b53",
        overload_id: "sim.native.model.module-init.container.v1",
        ordered_parameters_json: r#"[]"#,
        output_arity: "1",
        output_types_json: r#"["NativeModule"]"#,
        rust_signature: "fn comfy_model::module_init_exact_native(cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs an empty canonical NativeModule container",
        alias_rule: "NativeModule remains the sole module generation and parameter lifecycle owner",
        shape_rule: "contains no parameters or forward geometry",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent until parameters are loaded by a concrete module",
        numeric_rule: "generation begins at zero with no prefetched or parametrized state",
        tolerance: "exact",
        determinism: "fixed canonical base-module identity",
        cancellation_points: "before construction and publication",
        vjp_rule: "module initialization is not differentiable",
        jvp_rule: "module initialization has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/module_init.json",
        evidence_fixture_sha256: "9e5adce30a8e7715ab1baa7811abbe2ad9338585564a24d67d189a64dc7cdb29",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E430CCED2202",
        baseline_overload_id: "COMFY-TENSOR-OP-E430CCED2202:blocked",
        baseline_fixture_sha256: "afc8189986e2628f060bc23cc82a5ce65c5266b916ac0aef40833745deac47cd",
        overload_id: "sim.native.tensor.softmax-method.canonical-functional.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn softmax_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "out of place",
        alias_rule: "delegates the canonical activation-normalization softmax owner",
        shape_rule: "preserves shape over one normalized dimension",
        dtype_rule: "certified F32 overload",
        accumulation_dtype: "F32 stable reduction",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU reference and input stream",
        numeric_rule: "max-subtracted exponentiation with canonical reduction order",
        tolerance: "1e-6 absolute",
        determinism: "canonical softmax reduction order",
        cancellation_points: "at every public forward or derivative adapter boundary and canonical reduction checkpoints",
        vjp_rule: "canonical y times gradient-minus-dot map",
        jvp_rule: "canonical y times tangent-minus-dot map",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/softmax_method.json",
        evidence_fixture_sha256: "9df7cb8f470a63bda45bd95c68a25edd7912ff5da9c3b413259f3742216515e5",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_20",
        operation_id: "COMFY-TENSOR-OP-E0C529F06769",
        baseline_overload_id: "COMFY-TENSOR-OP-E0C529F06769:blocked",
        baseline_fixture_sha256: "9f69f0a0dc5e81ca1cd1c734dc82a9b359c17cfee77f15ffd281cc8bf9cacbf3",
        overload_id: "sim.native.tensor.swapaxes.read-only-view.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"axis_zero","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false},{"name":"axis_one","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn swapaxes_exact_native(input: &Tensor, axis_zero: i64, axis_one: i64, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartTwentyError>",
        mutation_rule: "read only",
        alias_rule: "returns a canonical read-only Tensor view sharing storage",
        shape_rule: "swaps two normalized shape dimensions",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "swaps descriptor strides and marks the checked view strided",
        device_rule: "preserves device and stream",
        numeric_rule: "logical values are transposed without copy",
        tolerance: "bit exact",
        determinism: "descriptor permutation",
        cancellation_points: "at every public forward or derivative boundary before descriptor construction and publication",
        vjp_rule: "self-inverse swap of output gradient",
        jvp_rule: "same swap of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-d54af27b4d70",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_20/swapaxes.json",
        evidence_fixture_sha256: "ca9ec70c78de782ce7035ec526700752666c4ecbae32d3d668d95e7385487be4",
    },
]
