&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-1ED3CF790B68",
        baseline_overload_id: "COMFY-TENSOR-OP-1ED3CF790B68:blocked",
        baseline_fixture_sha256: "cdb05fd3fc6297ac83de9421964a907ca1cd3a76e3bcf4f625cc159c8ee8c8a6",
        overload_id: "zed.native.tensor.add-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Tensor or Scalar\"},{\"default\":\"1\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"alpha\",\"type\":\"Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"()\"]",
        rust_signature: "fn add_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, other: ElementwiseOperand<'_>, alpha: Scalar, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartThreeError>",
        mutation_rule: "transactional in place; all values are staged before one copy-on-write publication",
        alias_rule: "preserves the receiver handle while detaching shared storage on publication",
        shape_rule: "other may right-align broadcast only to the receiver shape; expansion beyond it fails typed",
        dtype_rule: "receiver dtype is preserved and tensor operands must match it",
        accumulation_dtype: "receiver dtype",
        layout_rule: "logical values are written through canonical TensorWrite",
        device_rule: "CPU ordinal zero only",
        numeric_rule: "left plus alpha times other with canonical dtype overflow/wrapping semantics",
        tolerance: "exact canonical scalar encoding",
        determinism: "fixed row-major staging",
        cancellation_points: "before validation, at bounded staging intervals, before write, and before publication",
        vjp_rule: "autograd records this mutation through the existing canonical mutable-operation journal; no standalone VJP entry point",
        jvp_rule: "same as VJP reachability",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/add_in_place.json",
        evidence_fixture_sha256: "666d193a6090a5235502472dd50540112bab63328a1145d3bc245a5386fe9a28",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-26EF6B18C684",
        baseline_overload_id: "COMFY-TENSOR-OP-26EF6B18C684:blocked",
        baseline_fixture_sha256: "51b8ce08ff60eeae7bef89addc091e7e13582c3abe85a622e963c07cac06cfd3",
        overload_id: "zed.native.tensor.clamp-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"ordered Tensor\"},{\"default\":\"None\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"min\",\"type\":\"optional Scalar\"},{\"default\":\"None\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"max\",\"type\":\"optional Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"()\"]",
        rust_signature: "fn clamp_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, minimum: Option<Scalar>, maximum: Option<Scalar>, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartThreeError>",
        mutation_rule: "transactional in place; all values are staged before one copy-on-write publication",
        alias_rule: "preserves the receiver handle and uses canonical copy-on-write",
        shape_rule: "shape is unchanged including scalar and empty tensors",
        dtype_rule: "real and integer receiver dtype is preserved; complex and boolean fail typed",
        accumulation_dtype: "none",
        layout_rule: "logical values use canonical strides and TensorWrite",
        device_rule: "CPU ordinal zero only",
        numeric_rule: "inclusive clamp with IEEE NaN propagation; when minimum exceeds maximum every finite value becomes maximum",
        tolerance: "exact canonical encoding",
        determinism: "fixed row-major staging",
        cancellation_points: "before validation, at bounded staging intervals, before write, and before publication",
        vjp_rule: "mutation is journaled by the canonical autograd owner; no standalone VJP entry point",
        jvp_rule: "same as VJP reachability",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/clamp_in_place.json",
        evidence_fixture_sha256: "8a677f27001cb7e25a8ccba381cd00426c92d1ee650be7550df883f8b4bad7fe",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-1B60D420F7C7",
        baseline_overload_id: "COMFY-TENSOR-OP-1B60D420F7C7:blocked",
        baseline_fixture_sha256: "74e0014b9038fa040a77dd61b0cad577bd7ba6b87bef0c2d55e5a1e0c5d096af",
        overload_id: "zed.native.worker.cuda-memory-summary.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"capabilities\",\"type\":\"BackendCapabilityMatrix\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"snapshot\",\"type\":\"MemoryAccountingSnapshot\"}]",
        output_arity: "1",
        output_types_json: "[\"String\"]",
        rust_signature: "fn cuda_memory_summary_exact_native(capabilities: &BackendCapabilityMatrix, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<String, NativeMemoryStatsError>",
        mutation_rule: "read-only projection",
        alias_rule: "returns an owned diagnostic string",
        shape_rule: "not applicable",
        dtype_rule: "integer byte counters",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "certified CUDA and ROCm worker profiles",
        numeric_rule: "exact deterministic projection of canonical memory accounting counters",
        tolerance: "exact",
        determinism: "fixed field order",
        cancellation_points: "before source-stat projection and after formatting",
        vjp_rule: "non-differentiable diagnostics",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/cuda_memory_summary.json",
        evidence_fixture_sha256: "c791e05750b2c7d570a6ccf93e21f0781b3714589f43375becd513ebb7e8d7b4",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-231238FDA88D",
        baseline_overload_id: "COMFY-TENSOR-OP-231238FDA88D:blocked",
        baseline_fixture_sha256: "3ad58eb2fde4298181a1f90a19e2d6b892161dd4b48d0b8599ad8e700316482c",
        overload_id: "zed.native.tensor.cudnn-convolution-facade.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"TensorValues<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"TensorValues<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"geometry\",\"type\":\"3D convolution geometry\"}]",
        output_arity: "1",
        output_types_json: "[\"TensorValues\"]",
        rust_signature: "fn cudnn_convolution_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], padding: Vec<usize>, stride: Vec<usize>, dilation: Vec<usize>, groups: usize, benchmark: bool, deterministic: bool, allow_tf32: bool, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, ElementwiseRuntimePartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical convolution owner and returns fresh values",
        shape_rule: "canonical 3D convolution geometry and checked output shape",
        dtype_rule: "certified f32 overload",
        accumulation_dtype: "f32",
        layout_rule: "canonical convolution layout",
        device_rule: "CPU ordinal zero certified; no cuDNN ABI or fallback",
        numeric_rule: "exact canonical convolution with the observed false,false,true source flags",
        tolerance: "canonical convolution tolerance",
        determinism: "canonical convolution traversal",
        cancellation_points: "before facade validation and throughout canonical convolution",
        vjp_rule: "delegates to canonical convolution VJP",
        jvp_rule: "delegates to canonical convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/cudnn_convolution.json",
        evidence_fixture_sha256: "22cbdd894a81e277bde469d05ebd5ac4e6725cedc48a73f342438b78d99279da",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-1F39246F0FAD",
        baseline_overload_id: "COMFY-TENSOR-OP-1F39246F0FAD:blocked",
        baseline_fixture_sha256: "a7b7f42e880f6930f1b85adc4b4c7098248077bb77c4ab1f0ee6f71474c6f307",
        overload_id: "zed.native.tensor.data-ptr.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"usize\"]",
        rust_signature: "fn data_ptr_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<usize, ElementwiseRuntimePartThreeError>",
        mutation_rule: "read only",
        alias_rule: "returns a borrowed-storage address value without transferring ownership",
        shape_rule: "not applicable; checked storage offset contributes to the address",
        dtype_rule: "all canonical CPU storage dtypes",
        accumulation_dtype: "none",
        layout_rule: "address is base host storage plus checked byte offset",
        device_rule: "CPU ordinal zero only; device handles are never exposed",
        numeric_rule: "exact checked host address",
        tolerance: "exact",
        determinism: "stable while canonical storage remains alive and unmodified",
        cancellation_points: "before and after address projection",
        vjp_rule: "non-differentiable storage metadata",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/data_ptr.json",
        evidence_fixture_sha256: "16116a80c51e307df162ffb15e68ec5a283becb0d57cb1274ebaf4414e3266f0",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-263D166C9D1F",
        baseline_overload_id: "COMFY-TENSOR-OP-263D166C9D1F:blocked",
        baseline_fixture_sha256: "3e632388a7f221b313456bd3b52372db56fe043c2b3137db6a3e5612d65ce534",
        overload_id: "zed.native.tensor.expm1.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"real Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn expm1_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "floating dtype preserved; other dtypes fail typed",
        accumulation_dtype: "same floating dtype; f32 derivative profile",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE expm1 preserving signed zero and small-value precision",
        tolerance: "canonical dtype tolerance",
        determinism: "fixed row-major traversal",
        cancellation_points: "before validation, bounded intervals, upload, publication",
        vjp_rule: "output_gradient times exp(input)",
        jvp_rule: "input_tangent times exp(input)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/expm1.json",
        evidence_fixture_sha256: "359cf6e40e49d03321e5dcfa70c84f5173bbf58db87806b34530b66559adc7a4",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-1C55B11AD08B",
        baseline_overload_id: "COMFY-TENSOR-OP-1C55B11AD08B:blocked",
        baseline_fixture_sha256: "de781d3ba8e3ceece0d901b09377308632942d2635412276a38f5f44042bdf73",
        overload_id: "zed.native.tensor.floor.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"real Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn floor_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "real dtypes preserved and integers copied",
        accumulation_dtype: "none; f32 derivative profile",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE floor with signed zero; integers exact",
        tolerance: "exact canonical encoding",
        determinism: "fixed row-major traversal",
        cancellation_points: "before validation, bounded intervals, upload, publication",
        vjp_rule: "zero f32 tensor",
        jvp_rule: "zero f32 tensor",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/floor.json",
        evidence_fixture_sha256: "eca5ab9407b2b2373fe86b6433de343f3f0b2dc3472318d9951baa665cc11446",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-22DF6A4C26CC",
        baseline_overload_id: "COMFY-TENSOR-OP-22DF6A4C26CC:blocked",
        baseline_fixture_sha256: "4320198ac7460ed86093617d19fe8d1530fa793dc28b029fb0319d5cfbbafff3",
        overload_id: "zed.native.tensor.greater.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"ordered Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Tensor or Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn greater_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical boolean storage",
        shape_rule: "right-aligned broadcasting including scalar and empty dimensions",
        dtype_rule: "matching ordered tensor dtype or scalar coercible to input dtype",
        accumulation_dtype: "none",
        layout_rule: "canonical contiguous boolean output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "ordered greater-than; IEEE NaN compares false",
        tolerance: "exact",
        determinism: "fixed row-major broadcast traversal",
        cancellation_points: "before validation, bounded intervals, upload, publication",
        vjp_rule: "comparison is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/greater.json",
        evidence_fixture_sha256: "12c1d3b2dd491098dfafb2690b851879b80322ccb3de09fe8a8ff95ec0cbbf2e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-2673CE820FAC",
        baseline_overload_id: "COMFY-TENSOR-OP-2673CE820FAC:blocked",
        baseline_fixture_sha256: "9a7e1856bb36a604373dcd0a9268f836560a5c0dfdcd1dc4942a23a917737a85",
        overload_id: "zed.native.autograd.no-grad-mode.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"GradientMode\"]",
        rust_signature: "fn no_grad_exact_native(cancellation: &CancellationToken) -> Result<GradientMode, ElementwiseRuntimePartThreeError>",
        mutation_rule: "read-only mode construction",
        alias_rule: "returns the canonical GradientMode value",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "exact NoGrad enum value",
        tolerance: "exact",
        determinism: "immutable domain value",
        cancellation_points: "before construction",
        vjp_rule: "suppresses tape recording through the canonical autograd owner",
        jvp_rule: "tangents are not recorded",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/no_grad.json",
        evidence_fixture_sha256: "a4f5473199469bbe9f25dacb12d8ee34263a6bc42d03ae7f1a4ad94ecebe8a56",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-1917B7227A5C",
        baseline_overload_id: "COMFY-TENSOR-OP-1917B7227A5C:blocked",
        baseline_fixture_sha256: "599dcb00390f86460048e0f6234a8d190a8519c5a5de895c5ec6ee70de5f2c9e",
        overload_id: "zed.native.tensor.sigmoid.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"real Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn sigmoid_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "floating dtype preserved; other dtypes fail typed",
        accumulation_dtype: "same floating dtype; f32 derivative profile",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "delegates scalar mechanics to CpuBackend sigmoid",
        tolerance: "canonical activation tolerance",
        determinism: "fixed row-major traversal",
        cancellation_points: "before validation, bounded intervals, upload, publication",
        vjp_rule: "output_gradient times sigmoid(input) times one minus sigmoid(input)",
        jvp_rule: "input_tangent times sigmoid(input) times one minus sigmoid(input)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/sigmoid.json",
        evidence_fixture_sha256: "a6f4b862f29d7b9abc223038a65ab8608dd0c2e3b336b246d46a4078cfb8f33f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-2464198E16CB",
        baseline_overload_id: "COMFY-TENSOR-OP-2464198E16CB:blocked",
        baseline_fixture_sha256: "33a79f1bd899bb66591a57cec7149979719aca6b003450938901053edd24bc1c",
        overload_id: "zed.native.tensor.torch-archive-bytes.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"value\",\"type\":\"TorchArchiveValue\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<u8>\"]",
        rust_signature: "fn torch_save_exact_native(value: &TorchArchiveValue, cancellation: &CancellationToken) -> Result<Vec<u8>, ElementwiseRuntimePartThreeError>",
        mutation_rule: "read-only content generation; performs no filesystem write or output commit",
        alias_rule: "shared canonical tensor storages are emitted once and tensor views retain offsets/strides",
        shape_rule: "nested values are bounded to depth 64 and one million nodes",
        dtype_rule: "certified PyTorch storage dtypes only",
        accumulation_dtype: "none",
        layout_rule: "deterministic stored ZIP with protocol-2 pickle metadata",
        device_rule: "CPU tensor storage only",
        numeric_rule: "PyTorch-compatible archive content; final publication remains owned by OutputCommitter",
        tolerance: "byte exact for identical input",
        determinism: "BTreeMap ordering, stable storage discovery, zero timestamps",
        cancellation_points: "before and during value encoding and ZIP construction",
        vjp_rule: "serialization is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/torch_save.json",
        evidence_fixture_sha256: "bd03b1cd473e87cf61f070347d8b9b591354b3f7aea07dbc807635ebe9dabc60",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-2255F11A43BA",
        baseline_overload_id: "COMFY-TENSOR-OP-2255F11A43BA:blocked",
        baseline_fixture_sha256: "9e0ff580732f7d30d384f9348bce36791fdb2b26976a8d7768400be520ba2e4e",
        overload_id: "zed.native.worker.xpu-device-count.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"topology\",\"type\":\"MemoryTopology\"}]",
        output_arity: "1",
        output_types_json: "[\"u32\"]",
        rust_signature: "fn xpu_device_count_exact_native(topology: &MemoryTopology, cancellation: &CancellationToken) -> Result<u32, NativeMemoryStatsError>",
        mutation_rule: "read-only projection",
        alias_rule: "returns a copyable count",
        shape_rule: "not applicable",
        dtype_rule: "checked u32 count",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "counts canonical Intel XPU topology entries",
        numeric_rule: "exact count without runtime probing or external fallback",
        tolerance: "exact",
        determinism: "fixed topology traversal",
        cancellation_points: "before traversal, at bounded intervals, and after count",
        vjp_rule: "non-differentiable device metadata",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/xpu_device_count.json",
        evidence_fixture_sha256: "22ad88c164863c5beba3dc5ba7589f5b21313c2afa9c4013454b63c2dc80f15a",
    },
]
