&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7E962991728B",
        baseline_overload_id: "COMFY-TENSOR-OP-7E962991728B:blocked",
        baseline_fixture_sha256: "4cc3ac97fee38ada91459d4994fd9d32e2d11cef6ec85bbc1451ee4c00c201a0",
        overload_id: "sim.native.tensor.clamp-method.canonical-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"minimum","kind":"keyword_only","type":"Option<Scalar>","default":null,"keyword_only":true},{"name":"maximum","kind":"keyword_only","type":"Option<Scalar>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn clamp_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, minimum: Option<Scalar>, maximum: Option<Scalar>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartElevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 52 canonical clamp adapter",
        shape_rule: "preserves shape",
        dtype_rule: "canonical clamp dtype rules",
        accumulation_dtype: "input dtype",
        layout_rule: "canonical logical layout",
        device_rule: "canonical tensor device",
        numeric_rule: "inclusive checked lower and upper bounds",
        tolerance: "exact dtype arithmetic",
        determinism: "canonical clamp traversal",
        cancellation_points: "canonical clamp checkpoints",
        vjp_rule: "upstream gradient inside inclusive bounds",
        jvp_rule: "input tangent inside inclusive bounds",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/clamp_method.json",
        evidence_fixture_sha256: "e9ce61c88a73be9df9e73bea72e660a50a7ffdbb00a178d982d0ee385ff73227",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7E09C5749B60",
        baseline_overload_id: "COMFY-TENSOR-OP-7E09C5749B60:blocked",
        baseline_fixture_sha256: "f90b757fb02f1c600a52a0e88143510241a821bf7f4f27f551c921eaabbbd1ea",
        overload_id: "sim.native.tensor.tolist.logical-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["TensorListValue"]"#,
        rust_signature: "fn tolist_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<TensorListValue, ElementwiseRuntimePartElevenError>",
        mutation_rule: "read only",
        alias_rule: "owned recursive values decoded by DType",
        shape_rule: "preserves every descriptor dimension as nested lists",
        dtype_rule: "projects canonical decoded scalar categories",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical logical indexing including views",
        device_rule: "CPU host storage",
        numeric_rule: "exact scalar decode including complex and non-finite values",
        tolerance: "exact",
        determinism: "row-major recursive traversal",
        cancellation_points: "bounded recursive traversal",
        vjp_rule: "non-differentiable host projection",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/tolist.json",
        evidence_fixture_sha256: "5e6e39e8fa898bfa47e8bb5ed0dd11877b0b01003ee484cc4e3567d405039efb",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7F86521B5D09",
        baseline_overload_id: "COMFY-TENSOR-OP-7F86521B5D09:blocked",
        baseline_fixture_sha256: "4cc68d8b61118c6293a812acf0b9384e4ef54d95626a69e635968cde8a663bed",
        overload_id: "sim.native.autograd.enable-grad.explicit-mode.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: r#"["GradientMode"]"#,
        rust_signature: "fn enable_grad_exact_native(cancellation: &CancellationToken) -> Result<GradientMode, ElementwiseRuntimePartElevenError>",
        mutation_rule: "read only",
        alias_rule: "returns canonical explicit GradientMode",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "execution-context scoped",
        numeric_rule: "exact Enabled mode value",
        tolerance: "exact",
        determinism: "constant projection",
        cancellation_points: "before projection",
        vjp_rule: "caller-owned AutogradTape records under returned mode",
        jvp_rule: "caller-owned forward rules use returned mode",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/enable_grad.json",
        evidence_fixture_sha256: "d0805339f50fb2ece9ca1338bd8f4dc6dcb0ecd997bcc2728b8016061dd2e48f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7A0F5559B701",
        baseline_overload_id: "COMFY-TENSOR-OP-7A0F5559B701:blocked",
        baseline_fixture_sha256: "2e0530b2174efa8a5ae59ca85a06201f826b3ddd67b48d35292700b1df57cad8",
        overload_id: "sim.native.tensor.isclose.f32-broadcast.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"relative_tolerance","kind":"keyword_only","type":"f32","default":0.00001,"keyword_only":true},{"name":"absolute_tolerance","kind":"keyword_only","type":"f32","default":0.00000001,"keyword_only":true},{"name":"equal_nan","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<Bool>"]"#,
        rust_signature: "fn isclose_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, relative_tolerance: f32, absolute_tolerance: f32, equal_nan: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartElevenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical Bool storage",
        shape_rule: "right-aligned broadcast shape",
        dtype_rule: "F32 inputs and Bool output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "exact equality or abs(a-b)<=atol+rtol*abs(b) with explicit NaN policy",
        tolerance: "parameters define comparison",
        determinism: "row-major broadcast traversal",
        cancellation_points: "bounded comparison and upload",
        vjp_rule: "non-differentiable predicate",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/isclose.json",
        evidence_fixture_sha256: "0e6e577c5748b63e50b9a84558abaf64af34ba4fb82ea364f6271655d11083d5",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7DB0B0EC6483",
        baseline_overload_id: "COMFY-TENSOR-OP-7DB0B0EC6483:blocked",
        baseline_fixture_sha256: "bd2ed30e6dcdd4aee591859f698f137ed39e70959fcbd5ebdc546a5a03174ee2",
        overload_id: "sim.native.tensor.maximum.canonical-binary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"ElementwiseOperand<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn maximum_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartElevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical BinaryOperation::Maximum",
        shape_rule: "right-aligned broadcasting",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "NaN-propagating maximum with symmetric tie gradients",
        tolerance: "exact F32",
        determinism: "canonical binary traversal",
        cancellation_points: "canonical backend and derivative checkpoints",
        vjp_rule: "winning input receives gradient; ties split equally and broadcast gradients reduce",
        jvp_rule: "winning tangent; ties average",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/maximum.json",
        evidence_fixture_sha256: "b958ccf4074d5faf67edff04056c0f784cd2c6996d415f0748b3c69a326ed2c9",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-82BC07D67AFD",
        baseline_overload_id: "COMFY-TENSOR-OP-82BC07D67AFD:blocked",
        baseline_fixture_sha256: "6bd571346f4947840be373148b9f8bc158fc25f0877f91b2fe34fe192128d31d",
        overload_id: "sim.native.nn.init.zeros.canonical-fill.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["unit"]"#,
        rust_signature: "fn zeros_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartElevenError>",
        mutation_rule: "transactional in place",
        alias_rule: "delegates canonical zero_ staged fill and Tensor publication",
        shape_rule: "preserves descriptor",
        dtype_rule: "canonical fill dtype support",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical logical fill",
        device_rule: "exact backend device",
        numeric_rule: "exact representable zero",
        tolerance: "exact",
        determinism: "canonical fill traversal",
        cancellation_points: "before publication and backend checkpoints",
        vjp_rule: "initialization boundary is forward only",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/zeros_in_place.json",
        evidence_fixture_sha256: "12c8fe776a7fcc9c66b035e832dde640da07a87546d4b58e9abc8149ff54805f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-791664AD5273",
        baseline_overload_id: "COMFY-TENSOR-OP-791664AD5273:blocked",
        baseline_fixture_sha256: "4acbe63df0d751511239a6331639efbfd6348a015750e861c16f7f51a682bd58",
        overload_id: "sim.native.device.npu.empty-cache.memory-owner-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","kind":"positional_or_keyword","type":"dyn CachedAllocationOwner","default":null,"keyword_only":false},{"name":"inventory","kind":"positional_or_keyword","type":"MemoryPlacementInventory","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Npu>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeCacheRelease"]"#,
        rust_signature: "fn npu_empty_cache_exact_native(backend: &dyn CachedAllocationOwner, inventory: &mut MemoryPlacementInventory, device: DeviceId, cancellation: &CancellationToken) -> Result<NativeCacheRelease, NativeMemoryStatsError>",
        mutation_rule: "transactional canonical cache release and accounting commit",
        alias_rule: "delegates shared device_empty_cache authority",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "requires matching NPU cache owner and inventory device",
        numeric_rule: "exact released-byte and eviction accounting",
        tolerance: "exact",
        determinism: "inventory resource order",
        cancellation_points: "before staging and allocator release",
        vjp_rule: "non-differentiable memory control",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/npu_empty_cache.json",
        evidence_fixture_sha256: "849a66dfbd1549c22deaf9d70843b006ca4c0bc37ac6ba6847b673cff98638ce",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-7EA8F732F7A7",
        baseline_overload_id: "COMFY-TENSOR-OP-7EA8F732F7A7:blocked",
        baseline_fixture_sha256: "ee17bd2713d5dc97874c46317b7812ac049ee011b250a8a09e4f5f64d163d8d4",
        overload_id: "sim.native.device.npu.name.capability-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Npu>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["String"]"#,
        rust_signature: "fn npu_get_device_name_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<String, ElementwiseRuntimePartElevenError>",
        mutation_rule: "read only",
        alias_rule: "owned projection of canonical NativeDeviceProperties",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "exact matching NPU matrix and device",
        numeric_rule: "exact validated device name",
        tolerance: "exact",
        determinism: "capability projection",
        cancellation_points: "before and after projection",
        vjp_rule: "non-differentiable capability query",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/npu_device_name.json",
        evidence_fixture_sha256: "c1bcab837a3523494123e29fbabe4e054067bdf2ef97a575d345131b53246699",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-790CDE1EBF17",
        baseline_overload_id: "COMFY-TENSOR-OP-790CDE1EBF17:blocked",
        baseline_fixture_sha256: "47c368b57408f4f567ada76bea9357c2325ed99862b7abec565e05baf2b210b8",
        overload_id: "sim.native.optimizer.adam.canonical-adamw-zero-decay.v1",
        ordered_parameters_json: r#"[{"name":"parameters","kind":"positional_or_keyword","type":"Vec<Tensor<F32>>","default":null,"keyword_only":false},{"name":"learning_rate","kind":"keyword_only","type":"f32","default":0.001,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeAdam"]"#,
        rust_signature: "fn NativeAdam::new_with_context_exact_native(backend: &CpuBackend, parameters: &[Tensor], learning_rate: f32, context: &ExecutionContext<'_>) -> Result<NativeAdam, ElementwiseRuntimePartElevenError>",
        mutation_rule: "constructor plus transactional steps",
        alias_rule: "focused wrapper over canonical NativeAdamW with zero decay",
        shape_rule: "state matches parameter list and shapes",
        dtype_rule: "F32 parameters and gradients",
        accumulation_dtype: "F32 canonical moment tensors",
        layout_rule: "canonical tensor storage",
        device_rule: "CPU ordinal zero",
        numeric_rule: "Adam defaults beta1 .9 beta2 .999 epsilon 1e-8 and zero weight decay",
        tolerance: "F32 arithmetic",
        determinism: "parameter order and monotonic steps",
        cancellation_points: "canonical AdamW staging checkpoints",
        vjp_rule: "optimizer consumes caller-provided gradients",
        jvp_rule: "optimizer state transition is not differentiated",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/adam.json",
        evidence_fixture_sha256: "017e3e442cc0bdfe8e7216237d1707b2d3f02b3be81871dbf4da2bd5daa73479",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-8162B4C00596",
        baseline_overload_id: "COMFY-TENSOR-OP-8162B4C00596:blocked",
        baseline_fixture_sha256: "0575f5e8e4512e4f2e9ce6479b307f3121a54e5cc84b14616226e0d559a5cc8c",
        overload_id: "sim.native.tensor.round-function.canonical-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn round_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartElevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical round method with zero decimals",
        shape_rule: "preserves shape",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "ties to even",
        tolerance: "exact F32",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical round checkpoints",
        vjp_rule: "zero almost everywhere",
        jvp_rule: "zero almost everywhere",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/round_function.json",
        evidence_fixture_sha256: "ae70dbd523e663972c25937de2459d9a29fbd8a006040acdf36162b82dfa3e4c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-82310D1230AF",
        baseline_overload_id: "COMFY-TENSOR-OP-82310D1230AF:blocked",
        baseline_fixture_sha256: "d110c1a84f95704420bb4d7be86c34b3056b8f3f0a6b379ffad6fd6b79e9656b",
        overload_id: "sim.native.tensor.sign.canonical-unary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sign_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartElevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical UnaryOperation::Signum",
        shape_rule: "preserves shape",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "negative one zero positive one with NaN propagation and signed-zero preservation",
        tolerance: "exact",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical backend checkpoints",
        vjp_rule: "zero almost everywhere",
        jvp_rule: "zero almost everywhere",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/sign.json",
        evidence_fixture_sha256: "79cdea46f454473f325d337e58cecab7af6cf9e4889d8da695d022304fbcb0aa",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_11",
        operation_id: "COMFY-TENSOR-OP-80B937845579",
        baseline_overload_id: "COMFY-TENSOR-OP-80B937845579:blocked",
        baseline_fixture_sha256: "29f8dd31d36714919efd695e1cfd4f4905104d56c7faa397cb81dd421ae59687",
        overload_id: "sim.native.device.xpu.memory-stats.accounting-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["BTreeMap<String,u64>"]"#,
        rust_signature: "fn xpu_memory_stats_exact_native(capabilities: &BackendCapabilityMatrix, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<BTreeMap<String, u64>, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "delegates canonical MemoryAccountingSnapshot projection",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "u64 checked accounting",
        layout_rule: "not applicable",
        device_rule: "exact XPU capability device",
        numeric_rule: "exact active and reserved current bytes",
        tolerance: "exact",
        determinism: "ordered source-key map",
        cancellation_points: "before and after projection",
        vjp_rule: "non-differentiable memory diagnostics",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-790cde1ebf17",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_11/xpu_memory_stats.json",
        evidence_fixture_sha256: "88f54b6338f02e981309e0106708872bdbac6cc36c8a934d65b640cc789d863f",
    },
]
