&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-CC875F3A9DF9",
        baseline_overload_id: "COMFY-TENSOR-OP-CC875F3A9DF9:blocked",
        baseline_fixture_sha256: "d02690b9e28b7c641ec2793564c5e10c9999b71a1f321882ba28c1d63a95a03d",
        overload_id: "zed.native.tensor.size.immutable-shape-facade.v1",
        ordered_parameters_json: r#"[{"name":"dimensions","kind":"positional_or_keyword","type":"&[u64]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Arc<[u64]>"]"#,
        rust_signature: "fn tensor_size_exact_native(dimensions: &[u64], cancellation: &CancellationToken) -> Result<Arc<[u64]>, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "pure immutable shape construction",
        alias_rule: "returns an owned immutable arc slice and owns no TensorDescriptor geometry",
        shape_rule: "preserves the ordered dimensions exactly, including zero dimensions and scalar empty shape",
        dtype_rule: "checked u64 dimensions",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable to metadata",
        device_rule: "device independent",
        numeric_rule: "exact nonnegative dimension values",
        tolerance: "exact",
        determinism: "input order",
        cancellation_points: "before allocation and before publication",
        vjp_rule: "shape metadata is not differentiable",
        jvp_rule: "shape metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/tensor_size.json",
        evidence_fixture_sha256: "1c6b5d1947493b1ade3deed60d12d18957c8e417eaf929c85127642424add93d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-CD54624C2360",
        baseline_overload_id: "COMFY-TENSOR-OP-CD54624C2360:blocked",
        baseline_fixture_sha256: "698bdc780c815ffa8d7624e6db1e4ee905eeb43c30fd82b044824324dd86ef10",
        overload_id: "zed.native.tensor.cos-method.canonical-unary-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn cos_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates the canonical Task 50 cosine primitive and returns fresh storage",
        shape_rule: "preserves shape",
        dtype_rule: "certified F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "canonical Rust f32 cosine with IEEE NaN and infinity behavior",
        tolerance: "1e-6 absolute for finite fixture values",
        determinism: "canonical unary traversal",
        cancellation_points: "at the public adapter boundary, canonical backend checkpoints, and before publication",
        vjp_rule: "negative sine of input times output gradient through the canonical Task 50 map",
        jvp_rule: "negative sine of input times input tangent through the canonical Task 50 map",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/cos_method.json",
        evidence_fixture_sha256: "f37e86f3e7bab33d6517c3957afa9da6d6064e5ad7e178fcaa0fa1144ed75e54",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C9CC06A648EC",
        baseline_overload_id: "COMFY-TENSOR-OP-C9CC06A648EC:blocked",
        baseline_fixture_sha256: "451b1fed6338f4a07728b5273442735a7a3f118f053b78c931888d12a2bc2011",
        overload_id: "zed.native.tensor.div-in-place.canonical-div-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"&mut Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>|Scalar","default":null,"keyword_only":false}]"#,
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn div_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartNineteenError>",
        mutation_rule: "stages canonical division and commits the receiver handle only after validation and cancellation",
        alias_rule: "uses the established in-place facade ownership and never partially publishes staged storage",
        shape_rule: "broadcast output must equal the receiver shape",
        dtype_rule: "certified F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical division output replaces the receiver facade",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "canonical Task 47 division including IEEE zero and NaN behavior",
        tolerance: "1e-6 absolute for finite fixture values",
        determinism: "canonical binary traversal",
        cancellation_points: "at the public adapter boundary, canonical division checkpoints, and immediately before commit",
        vjp_rule: "the canonical Task 47 division contract owns analytical maps before mutation",
        jvp_rule: "the canonical Task 47 division contract owns analytical maps before mutation",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/div_in_place.json",
        evidence_fixture_sha256: "c15bde237ad330e1ce44598e56146161cfba595a1f1302b0ec2a3ae2aa86642e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C9C8310F80B5",
        baseline_overload_id: "COMFY-TENSOR-OP-C9C8310F80B5:blocked",
        baseline_fixture_sha256: "84437c3269309a001356e6e6624c74d252de30ee039dafae2d21b7a3a79892b6",
        overload_id: "zed.native.tensor.flip.canonical-axis-reversal.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimensions","kind":"positional_or_keyword","type":"&[i64]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn flip_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 57 canonical byte-preserving axis reversal and returns fresh storage",
        shape_rule: "preserves shape and requires unique normalized dimensions",
        dtype_rule: "preserves every canonical dtype byte for byte",
        accumulation_dtype: "not applicable",
        layout_rule: "contiguous output from logical input traversal",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "reverses each selected axis exactly once",
        tolerance: "bit exact",
        determinism: "row-major logical traversal",
        cancellation_points: "at every public forward or derivative adapter boundary, canonical bounded reversal checkpoints, and upload",
        vjp_rule: "flip is self-inverse and flips the output gradient over the same dimensions",
        jvp_rule: "flips the input tangent over the same dimensions",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/flip.json",
        evidence_fixture_sha256: "05228df6acd483be68e53a46a1ee0e67653353404743fe64357f68ebc913dca3",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C93863D94FF9",
        baseline_overload_id: "COMFY-TENSOR-OP-C93863D94FF9:blocked",
        baseline_fixture_sha256: "1e3e1aad53a7c4ed904002154beef5acf4694eddee75edf3d7055256e0c6a575",
        overload_id: "zed.native.tensor.cuda-current-device.capability-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix<Cuda|Rocm>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u32"]"#,
        rust_signature: "fn cuda_current_device_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<u32, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "read only",
        alias_rule: "copyable ordinal projection",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "u32",
        layout_rule: "not applicable",
        device_rule: "exact caller-owned CUDA or ROCm capability device",
        numeric_rule: "returns the canonical DeviceId ordinal without process-global current-device state",
        tolerance: "exact",
        determinism: "immutable capability matrix",
        cancellation_points: "before and after projection",
        vjp_rule: "device metadata is not differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/cuda_current_device.json",
        evidence_fixture_sha256: "699c577ad10e630012a7e1b927c68893beae3e803fc7a79ae93b9b0cfa9b1707",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-CA8F43C066B1",
        baseline_overload_id: "COMFY-TENSOR-OP-CA8F43C066B1:blocked",
        baseline_fixture_sha256: "7f0cf547ce5e072074f73a151a7ddb3ef4869b72caf699b7d91fe220759c9e27",
        overload_id: "zed.native.worker.cuda-empty-cache.canonical-cache-transaction.v1",
        ordered_parameters_json: r#"[{"name":"backend","kind":"positional_or_keyword","type":"&dyn CachedAllocationOwner","default":null,"keyword_only":false},{"name":"inventory","kind":"positional_or_keyword","type":"&mut MemoryPlacementInventory","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Cuda|Rocm>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeCacheRelease"]"#,
        rust_signature: "fn comfy_worker::cuda_empty_cache_exact_native(backend: &dyn CachedAllocationOwner, inventory: &mut MemoryPlacementInventory, device: DeviceId, context: &ExecutionContext<'_>) -> Result<NativeCacheRelease, NativeMemoryStatsError>",
        mutation_rule: "atomically commits the canonical staged reclaimable-cache accounting transaction",
        alias_rule: "returns owned release accounting and owns no allocator or inventory state",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 byte accounting",
        layout_rule: "not applicable",
        device_rule: "exact configured CUDA or ROCm cache owner and inventory device",
        numeric_rule: "canonical allocator release plus accounting actions",
        tolerance: "exact",
        determinism: "inventory order and allocator result",
        cancellation_points: "before and during staging, allocator release, and before accounting commit",
        vjp_rule: "memory management is not differentiable",
        jvp_rule: "memory management has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/cuda_empty_cache.json",
        evidence_fixture_sha256: "6e72a285bdb3fd39146aacca5ef16e0d6fc11c836e3429c5f4ddb40f699f666d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C9765FFEEB7F",
        baseline_overload_id: "COMFY-TENSOR-OP-C9765FFEEB7F:blocked",
        baseline_fixture_sha256: "17bd1a7f4daac40a30a370362b1289eb12a38b69f06347aceb0fd3fd06898ad5",
        overload_id: "zed.native.tensor.cuda-stream.canonical-stream-registry.v1",
        ordered_parameters_json: r#"[{"name":"registry","kind":"positional_or_keyword","type":"&NativeStreamRegistry","default":null,"keyword_only":false},{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix<Cuda|Rocm>","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Cuda|Rocm>","default":null,"keyword_only":false},{"name":"priority","kind":"keyword_only","type":"i32","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeStream"]"#,
        rust_signature: "fn cuda_stream_exact_native(registry: &NativeStreamRegistry, capabilities: &BackendCapabilityMatrix, device: DeviceId, priority: i32, cancellation: &CancellationToken) -> Result<NativeStream, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "atomically allocates one non-default canonical stream identity",
        alias_rule: "returns an owned immutable NativeStream",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 stream identity",
        layout_rule: "not applicable",
        device_rule: "exact CUDA or ROCm device matching the canonical capability matrix",
        numeric_rule: "preserves signed priority and registry allocation order",
        tolerance: "exact",
        determinism: "canonical registry allocation order",
        cancellation_points: "before device validation and before atomic identifier allocation",
        vjp_rule: "stream metadata is not differentiable",
        jvp_rule: "stream metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/cuda_stream.json",
        evidence_fixture_sha256: "7884913c661ee6cad49ee2f7f5c4208575f755216570aa9377f9e370409223e0",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C905902EB028",
        baseline_overload_id: "COMFY-TENSOR-OP-C905902EB028:blocked",
        baseline_fixture_sha256: "e41a7b34f0a38d0c1ef849d90ebd1a116a25be5749a6eb8c01c3cce5b0caaa78",
        overload_id: "zed.native.tensor.equal.whole-tensor-numeric.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"&Tensor","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"&Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn equal_exact_native(input: &Tensor, other: &Tensor, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "read only",
        alias_rule: "returns a copyable boolean",
        shape_rule: "false for unequal shapes and elementwise comparison for equal shapes",
        dtype_rule: "supports canonical numeric cross-dtype equality without promotion storage",
        accumulation_dtype: "exact signed, unsigned, or f64 decoded comparison",
        layout_rule: "logical traversal supports views and noncontiguous inputs",
        device_rule: "requires a common canonical device",
        numeric_rule: "all corresponding numeric values must compare equal; NaN is unequal and signed zero is equal",
        tolerance: "exact",
        determinism: "logical index order with early false return",
        cancellation_points: "before traversal, bounded intervals, and before true publication",
        vjp_rule: "whole-tensor equality is not differentiable",
        jvp_rule: "whole-tensor equality has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/equal.json",
        evidence_fixture_sha256: "6b635e5aa2bf85fbb1752bbaca8b0771daa03a0fefbaa4fdc3be7d7ff61d6159",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-CC4DC3D17ADD",
        baseline_overload_id: "COMFY-TENSOR-OP-CC4DC3D17ADD:blocked",
        baseline_fixture_sha256: "f3fdc7f34830c5d3a5ff446c0a58a8fe06c08b1f36857cf4abeebec6b28cac5f",
        overload_id: "zed.native.tensor.mlu-device-name.capability-properties.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix<Mlu>","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Mlu>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["String"]"#,
        rust_signature: "fn mlu_get_device_name_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<String, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "read only",
        alias_rule: "returns an owned projection of canonical device properties",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "exact MLU capability device with certified native properties",
        numeric_rule: "preserves the canonical property name exactly",
        tolerance: "exact UTF-8",
        determinism: "immutable capability matrix",
        cancellation_points: "before validation and before publication",
        vjp_rule: "device metadata is not differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/mlu_device_name.json",
        evidence_fixture_sha256: "c7c797b1d18d7995b5a52c71c36a68da59f6a8f1d7290a22e57d598619cce2b3",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C8BA6CE3159C",
        baseline_overload_id: "COMFY-TENSOR-OP-C8BA6CE3159C:blocked",
        baseline_fixture_sha256: "09c2541b8859293ef361b1ab69b92071e76ffe727ca916212c2ef70c05b1b6a9",
        overload_id: "zed.native.tensor.sort.canonical-argsort-gather.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":-1,"keyword_only":true},{"name":"descending","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"stable","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "2",
        output_types_json: r#"["Tensor","Tensor<I64>"]"#,
        rust_signature: "fn sort_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, descending: bool, stable: bool, context: &ExecutionContext<'_>) -> Result<NativeSortResult, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "out of place",
        alias_rule: "canonical Task 57 argsort owns ordering; this adapter gathers fresh values and returns its fresh indices",
        shape_rule: "both outputs preserve input shape along a normalized dimension",
        dtype_rule: "values preserve any Task 57 sortable dtype and indices are I64",
        accumulation_dtype: "decoded scalar comparison and checked I64 indices",
        layout_rule: "contiguous logical outputs",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "canonical stable or deterministic unstable argsort ordering followed by exact byte gather",
        tolerance: "bit exact values and exact indices",
        determinism: "canonical argsort order and row-major gather",
        cancellation_points: "at every public forward or derivative adapter boundary, canonical ordering, bounded gather or scatter intervals, and before publication",
        vjp_rule: "inverse permutation scatters output gradient to original positions",
        jvp_rule: "the primal permutation gathers the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/sort.json",
        evidence_fixture_sha256: "733f2c96dfb8fdf9e9e404feced4cf44eb3027eab92cb9bb8d2b63c5b7ede280",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-CE66E20937C0",
        baseline_overload_id: "COMFY-TENSOR-OP-CE66E20937C0:blocked",
        baseline_fixture_sha256: "4f9c45968b92d65b00564a6c1be012b8a826f2e359fe1d1143fae6efa4ee7af7",
        overload_id: "zed.native.tensor.directml-device.capability-validated.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix<DirectMl>","default":null,"keyword_only":false},{"name":"ordinal","kind":"positional_or_keyword","type":"u32","default":0,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["DeviceId<DirectMl>"]"#,
        rust_signature: "fn directml_device_exact_native(capabilities: &BackendCapabilityMatrix, ordinal: u32, cancellation: &CancellationToken) -> Result<DeviceId, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "read only",
        alias_rule: "returns the canonical copyable DeviceId",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "u32 ordinal",
        layout_rule: "not applicable",
        device_rule: "requires an exact caller-owned DirectML capability device and never binds an unavailable ABI",
        numeric_rule: "maps the source ordinal to canonical DeviceId exactly",
        tolerance: "exact",
        determinism: "immutable capability matrix",
        cancellation_points: "before validation and before publication",
        vjp_rule: "device metadata is not differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/directml_device.json",
        evidence_fixture_sha256: "3ba2d58354204823e167c62aeb8c17a9a82a0a4c95f282a17972bb1186e27682",
    },
]
