&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-CC875F3A9DF9",
        baseline_overload_id: "COMFY-TENSOR-OP-CC875F3A9DF9:blocked",
        baseline_fixture_sha256: "28b485365ea1e5aa2c2720fed5a94926e35097cf5ecaaae9e0e18f90d3b0ccf2",
        overload_id: "sim.native.tensor.size.immutable-shape-facade.v1",
        ordered_parameters_json: r#"[{"name":"dimensions","kind":"positional_or_keyword","type":"&[u64]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Arc<[u64]>"]"#,
        rust_signature: "fn tensor_size_exact_native(dimensions: &[u64], cancellation: &CancellationToken) -> Result<Arc<[u64]>, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "pure immutable shape construction",
        alias_rule: "returns an owned immutable arc slice and owns no TensorDescriptor geometry",
        shape_rule: "preserves the ordered dimensions exactly, including zero dimensions and scalar empty shape",
        dtype_rule: "checked u64 dimensions",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable to metadata",
        device_rule: "device independent",
        numeric_rule: "exact nonnegative dimension values",
        tolerance: "exact",
        determinism: "input order",
        cancellation_points: "before allocation and before publication",
        vjp_rule: "shape metadata is not differentiable",
        jvp_rule: "shape metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/tensor_size.json",
        evidence_fixture_sha256: "18e284f3167ee029489ead2c45e80750b7bc730e246986a0c8cef9a0a23df01c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-CD54624C2360",
        baseline_overload_id: "COMFY-TENSOR-OP-CD54624C2360:blocked",
        baseline_fixture_sha256: "624399edf05e2ac655eba5c91b2c864c70aa2910686d36a6857fe034235a2965",
        overload_id: "sim.native.tensor.cos-method.canonical-unary-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn cos_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates the canonical Task 50 cosine primitive and returns fresh storage",
        shape_rule: "preserves shape",
        dtype_rule: "certified F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "canonical Rust f32 cosine with IEEE NaN and infinity behavior",
        tolerance: "1e-6 absolute for finite fixture values",
        determinism: "canonical unary traversal",
        cancellation_points: "at the public adapter boundary, canonical backend checkpoints, and before publication",
        vjp_rule: "negative sine of input times output gradient through the canonical Task 50 map",
        jvp_rule: "negative sine of input times input tangent through the canonical Task 50 map",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/cos_method.json",
        evidence_fixture_sha256: "020131508133b15effb3028322927a3db6f19549c8a46a3ad77f0d712548a211",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C9CC06A648EC",
        baseline_overload_id: "COMFY-TENSOR-OP-C9CC06A648EC:blocked",
        baseline_fixture_sha256: "845f17e268986224eb43fea13c65fc13bcf57f07ae0d39a1d1933600dfe6b0f1",
        overload_id: "sim.native.tensor.div-in-place.canonical-div-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"&mut Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>|Scalar","default":null,"keyword_only":false}]"#,
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn div_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartNineteenError>",
        mutation_rule: "stages canonical division and commits the receiver handle only after validation and cancellation",
        alias_rule: "uses the established in-place facade ownership and never partially publishes staged storage",
        shape_rule: "broadcast output must equal the receiver shape",
        dtype_rule: "certified F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical division output replaces the receiver facade",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "canonical Task 47 division including IEEE zero and NaN behavior",
        tolerance: "1e-6 absolute for finite fixture values",
        determinism: "canonical binary traversal",
        cancellation_points: "at the public adapter boundary, canonical division checkpoints, and immediately before commit",
        vjp_rule: "the canonical Task 47 division contract owns analytical maps before mutation",
        jvp_rule: "the canonical Task 47 division contract owns analytical maps before mutation",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/div_in_place.json",
        evidence_fixture_sha256: "5062f8a6e4e2cf6821f4da0ff2a94f17426e2238cdc43ed1ebc14924ac8b96fd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C9C8310F80B5",
        baseline_overload_id: "COMFY-TENSOR-OP-C9C8310F80B5:blocked",
        baseline_fixture_sha256: "593b4b360c70bdfad975587de9617fc0966006b577ff3c8f12f79098414bd4e2",
        overload_id: "sim.native.tensor.flip.canonical-axis-reversal.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimensions","kind":"positional_or_keyword","type":"&[i64]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn flip_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 57 canonical byte-preserving axis reversal and returns fresh storage",
        shape_rule: "preserves shape and requires unique normalized dimensions",
        dtype_rule: "preserves every canonical dtype byte for byte",
        accumulation_dtype: "not applicable",
        layout_rule: "contiguous output from logical input traversal",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "reverses each selected axis exactly once",
        tolerance: "bit exact",
        determinism: "row-major logical traversal",
        cancellation_points: "at every public forward or derivative adapter boundary, canonical bounded reversal checkpoints, and upload",
        vjp_rule: "flip is self-inverse and flips the output gradient over the same dimensions",
        jvp_rule: "flips the input tangent over the same dimensions",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/flip.json",
        evidence_fixture_sha256: "2172c2dd0a0b4e90a8f4d97158372b0df1920095f35c75c86448e6c1fe792651",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C93863D94FF9",
        baseline_overload_id: "COMFY-TENSOR-OP-C93863D94FF9:blocked",
        baseline_fixture_sha256: "1eb98bc37bce8036283787e0ec76a162702e08b922a703f0c36644f564e3ef8f",
        overload_id: "sim.native.tensor.cuda-current-device.capability-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix<Cuda|Rocm>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u32"]"#,
        rust_signature: "fn cuda_current_device_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<u32, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "read only",
        alias_rule: "copyable ordinal projection",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "u32",
        layout_rule: "not applicable",
        device_rule: "exact caller-owned CUDA or ROCm capability device",
        numeric_rule: "returns the canonical DeviceId ordinal without process-global current-device state",
        tolerance: "exact",
        determinism: "immutable capability matrix",
        cancellation_points: "before and after projection",
        vjp_rule: "device metadata is not differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/cuda_current_device.json",
        evidence_fixture_sha256: "0c6df0c32a090713643943f8850798da3f9a161f6f44d34c7b5eb4f80f62bbe2",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-CA8F43C066B1",
        baseline_overload_id: "COMFY-TENSOR-OP-CA8F43C066B1:blocked",
        baseline_fixture_sha256: "a61ed4ee9efd005c420179290ba4239f7a2b9b2957d69862c530e332e3d83955",
        overload_id: "sim.native.worker.cuda-empty-cache.canonical-cache-transaction.v1",
        ordered_parameters_json: r#"[{"name":"backend","kind":"positional_or_keyword","type":"&dyn CachedAllocationOwner","default":null,"keyword_only":false},{"name":"inventory","kind":"positional_or_keyword","type":"&mut MemoryPlacementInventory","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Cuda|Rocm>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeCacheRelease"]"#,
        rust_signature: "fn comfy_worker::cuda_empty_cache_exact_native(backend: &dyn CachedAllocationOwner, inventory: &mut MemoryPlacementInventory, device: DeviceId, context: &ExecutionContext<'_>) -> Result<NativeCacheRelease, NativeMemoryStatsError>",
        mutation_rule: "atomically commits the canonical staged reclaimable-cache accounting transaction",
        alias_rule: "returns owned release accounting and owns no allocator or inventory state",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 byte accounting",
        layout_rule: "not applicable",
        device_rule: "exact configured CUDA or ROCm cache owner and inventory device",
        numeric_rule: "canonical allocator release plus accounting actions",
        tolerance: "exact",
        determinism: "inventory order and allocator result",
        cancellation_points: "before and during staging, allocator release, and before accounting commit",
        vjp_rule: "memory management is not differentiable",
        jvp_rule: "memory management has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/cuda_empty_cache.json",
        evidence_fixture_sha256: "ec066fcced69c8fe90209d2379db62936cfe0fbd9d03569789eb8a3b818393af",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C9765FFEEB7F",
        baseline_overload_id: "COMFY-TENSOR-OP-C9765FFEEB7F:blocked",
        baseline_fixture_sha256: "7f3c1ecefb5c6bd85404556bbee3013c9d6098be27df4a62bd244644fc68b2df",
        overload_id: "sim.native.tensor.cuda-stream.canonical-stream-registry.v1",
        ordered_parameters_json: r#"[{"name":"registry","kind":"positional_or_keyword","type":"&NativeStreamRegistry","default":null,"keyword_only":false},{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix<Cuda|Rocm>","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Cuda|Rocm>","default":null,"keyword_only":false},{"name":"priority","kind":"keyword_only","type":"i32","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeStream"]"#,
        rust_signature: "fn cuda_stream_exact_native(registry: &NativeStreamRegistry, capabilities: &BackendCapabilityMatrix, device: DeviceId, priority: i32, cancellation: &CancellationToken) -> Result<NativeStream, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "atomically allocates one non-default canonical stream identity",
        alias_rule: "returns an owned immutable NativeStream",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 stream identity",
        layout_rule: "not applicable",
        device_rule: "exact CUDA or ROCm device matching the canonical capability matrix",
        numeric_rule: "preserves signed priority and registry allocation order",
        tolerance: "exact",
        determinism: "canonical registry allocation order",
        cancellation_points: "before device validation and before atomic identifier allocation",
        vjp_rule: "stream metadata is not differentiable",
        jvp_rule: "stream metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/cuda_stream.json",
        evidence_fixture_sha256: "879cf2290cf859fa380a457abca4e6ae3ccc01f5db3814f7383cc96c8c807039",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C905902EB028",
        baseline_overload_id: "COMFY-TENSOR-OP-C905902EB028:blocked",
        baseline_fixture_sha256: "1cad02d5c230bb23ae612603333ac0363be5629fecc257a88cd845686698b350",
        overload_id: "sim.native.tensor.equal.whole-tensor-numeric.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"&Tensor","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"&Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn equal_exact_native(input: &Tensor, other: &Tensor, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "read only",
        alias_rule: "returns a copyable boolean",
        shape_rule: "false for unequal shapes and elementwise comparison for equal shapes",
        dtype_rule: "supports canonical numeric cross-dtype equality without promotion storage",
        accumulation_dtype: "exact signed, unsigned, or f64 decoded comparison",
        layout_rule: "logical traversal supports views and noncontiguous inputs",
        device_rule: "requires a common canonical device",
        numeric_rule: "all corresponding numeric values must compare equal; NaN is unequal and signed zero is equal",
        tolerance: "exact",
        determinism: "logical index order with early false return",
        cancellation_points: "before traversal, bounded intervals, and before true publication",
        vjp_rule: "whole-tensor equality is not differentiable",
        jvp_rule: "whole-tensor equality has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/equal.json",
        evidence_fixture_sha256: "70e92e1774c004212433186cf4d840ae92b86f193a99e524f53b41e7ef9ee26a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-CC4DC3D17ADD",
        baseline_overload_id: "COMFY-TENSOR-OP-CC4DC3D17ADD:blocked",
        baseline_fixture_sha256: "fe6f3fdd76a411a34ad26a5519563cff25613643f0a23ce89e455b7f13689fbf",
        overload_id: "sim.native.tensor.mlu-device-name.capability-properties.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix<Mlu>","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Mlu>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["String"]"#,
        rust_signature: "fn mlu_get_device_name_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, cancellation: &CancellationToken) -> Result<String, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "read only",
        alias_rule: "returns an owned projection of canonical device properties",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "exact MLU capability device with certified native properties",
        numeric_rule: "preserves the canonical property name exactly",
        tolerance: "exact UTF-8",
        determinism: "immutable capability matrix",
        cancellation_points: "before validation and before publication",
        vjp_rule: "device metadata is not differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/mlu_device_name.json",
        evidence_fixture_sha256: "f37239c6958e3c7576d1aa500c66f98d61c2b2fdbceb596ea4a22d6b7328a46f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-C8BA6CE3159C",
        baseline_overload_id: "COMFY-TENSOR-OP-C8BA6CE3159C:blocked",
        baseline_fixture_sha256: "a85ea1ecf34c02dfd2186aae951fdcc4873099b70663d03f5dc47555fb1a0f35",
        overload_id: "sim.native.tensor.sort.canonical-argsort-gather.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":-1,"keyword_only":true},{"name":"descending","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"stable","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "2",
        output_types_json: r#"["Tensor","Tensor<I64>"]"#,
        rust_signature: "fn sort_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, descending: bool, stable: bool, context: &ExecutionContext<'_>) -> Result<NativeSortResult, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "out of place",
        alias_rule: "canonical Task 57 argsort owns ordering; this adapter gathers fresh values and returns its fresh indices",
        shape_rule: "both outputs preserve input shape along a normalized dimension",
        dtype_rule: "values preserve any Task 57 sortable dtype and indices are I64",
        accumulation_dtype: "decoded scalar comparison and checked I64 indices",
        layout_rule: "contiguous logical outputs",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "canonical stable or deterministic unstable argsort ordering followed by exact byte gather",
        tolerance: "bit exact values and exact indices",
        determinism: "canonical argsort order and row-major gather",
        cancellation_points: "at every public forward or derivative adapter boundary, canonical ordering, bounded gather or scatter intervals, and before publication",
        vjp_rule: "inverse permutation scatters output gradient to original positions",
        jvp_rule: "the primal permutation gathers the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/sort.json",
        evidence_fixture_sha256: "30c1df025445eea25b316eef39058bc62c6a8cbaf683640bef9a85bcdb345459",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_19",
        operation_id: "COMFY-TENSOR-OP-CE66E20937C0",
        baseline_overload_id: "COMFY-TENSOR-OP-CE66E20937C0:blocked",
        baseline_fixture_sha256: "0545c0a9ca78f392f4b8d845a7b676689316595e971df05214d452f43b21d9f1",
        overload_id: "sim.native.tensor.directml-device.capability-validated.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix<DirectMl>","default":null,"keyword_only":false},{"name":"ordinal","kind":"positional_or_keyword","type":"u32","default":0,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["DeviceId<DirectMl>"]"#,
        rust_signature: "fn directml_device_exact_native(capabilities: &BackendCapabilityMatrix, ordinal: u32, cancellation: &CancellationToken) -> Result<DeviceId, ElementwiseRuntimePartNineteenError>",
        mutation_rule: "read only",
        alias_rule: "returns the canonical copyable DeviceId",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "u32 ordinal",
        layout_rule: "not applicable",
        device_rule: "requires an exact caller-owned DirectML capability device and never binds an unavailable ABI",
        numeric_rule: "maps the source ordinal to canonical DeviceId exactly",
        tolerance: "exact",
        determinism: "immutable capability matrix",
        cancellation_points: "before validation and before publication",
        vjp_rule: "device metadata is not differentiable",
        jvp_rule: "device metadata has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c8ba6ce3159c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_19/directml_device.json",
        evidence_fixture_sha256: "c4179bfe3e5c7286bcb6eb8f8818bd7857bee5da26af6198955f02b4123c29a7",
    },
]
