&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-ED2FCEFE4ECE",
        baseline_overload_id: "COMFY-TENSOR-OP-ED2FCEFE4ECE:blocked",
        baseline_fixture_sha256: "acf7f5178f959ebc99035ef29a29cf0287e88e84e741bb54b7a745df4a31632c",
        overload_id: "zed.native.tensor.backward.canonical-store.v2",
        ordered_parameters_json: r#"[{"name":"output_slot","kind":"positional_or_keyword","type":"OutputSlot","default":null,"keyword_only":false},{"name":"gradient","kind":"positional_or_keyword","type":"Option<Tensor>","default":null,"keyword_only":false},{"name":"inputs","kind":"keyword_only","type":"Option<&[LeafId]>","default":null,"keyword_only":true},{"name":"retain_graph","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"create_graph","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["()"]"#,
        rust_signature: "fn backward_method_with_context_exact_native(backend: &CpuBackend, tape: &mut AutogradTape, output_slot: OutputSlot, output: &Tensor, gradient: Option<Tensor>, inputs: Option<&[LeafId]>, reducer: &dyn GradientReducer, gradient_store: &mut GradientStore, retain_graph: bool, create_graph: bool, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "AutogradTape performs the canonical reverse traversal and transactionally publishes filtered leaf gradients through GradientStore; terminal traversal releases nodes and retained traversal preserves them",
        alias_rule: "seed and saved tensors are read only; GradientStore alone owns published gradient handles",
        shape_rule: "implicit seed is accepted only for one-element outputs; explicit seed matches output geometry",
        dtype_rule: "seed dtype and device match the output; tape rules own downstream dtype checks",
        accumulation_dtype: "owned by canonical GradientReducer and GradientStore",
        layout_rule: "logical tensor geometry; tape rules preserve their certified layouts",
        device_rule: "canonical native tape, reducer, and gradient store; no external autograd runtime",
        numeric_rule: "reverse topological VJP accumulation through AutogradTape",
        tolerance: "owned by registered backward rules",
        determinism: "stable reverse tape order, reducer order, and leaf publication order",
        cancellation_points: "before seed creation, within tape traversal, and before atomic GradientStore publication",
        vjp_rule: "this operation invokes the canonical VJP tape",
        jvp_rule: "not applicable to the backward control operation",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/backward.json",
        evidence_fixture_sha256: "916b5ed2fa0f7d8d85555695ad84e380a0694aa92837ab21b12fd1b8fe8916ac",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-E9EE26A3960C",
        baseline_overload_id: "COMFY-TENSOR-OP-E9EE26A3960C:blocked",
        baseline_fixture_sha256: "8764edf7a20f7fdb028d5cafdfc8bb857d070d89d395ea69d4e3df332c7a641d",
        overload_id: "zed.native.tensor.exp.f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn exp_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "certified CPU F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "logical traversal and contiguous output",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "native CpuBackend exponential unary kernel",
        tolerance: "1e-5 absolute",
        determinism: "fixed element order",
        cancellation_points: "backend bounded kernel points",
        vjp_rule: "output_gradient multiplied by exp(input)",
        jvp_rule: "input_tangent multiplied by exp(input)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/exp.json",
        evidence_fixture_sha256: "89865067ac3797af497999ac18540acfbe3ffe6f885cacee4568f8fc10f6dd02",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-ECF812A5CF81",
        baseline_overload_id: "COMFY-TENSOR-OP-ECF812A5CF81:blocked",
        baseline_fixture_sha256: "9e03e7a4a66ae73bf5376914993d8997b98e7de0c27f88272008e1bc01d8964e",
        overload_id: "zed.native.tensor.neg.f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn neg_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "certified CPU F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "logical traversal and contiguous output",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "native CpuBackend negate unary kernel including signed zero",
        tolerance: "bit exact except signed-zero semantics",
        determinism: "fixed element order",
        cancellation_points: "backend bounded kernel points",
        vjp_rule: "negates output gradient",
        jvp_rule: "negates input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/neg.json",
        evidence_fixture_sha256: "90981431f3cf80f126b22d16b544acf327dd53e4283d612b3fc74a74a557aedd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-E78AD841C264",
        baseline_overload_id: "COMFY-TENSOR-OP-E78AD841C264:blocked",
        baseline_fixture_sha256: "e6478272d1db7ee845b21389801f339ad1e087821fda6ae8b94b778c215a6a27",
        overload_id: "zed.native.tensor.unfold.read-only-view.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false},{"name":"size","kind":"positional_or_keyword","type":"u64","default":null,"keyword_only":false},{"name":"step","kind":"positional_or_keyword","type":"u64","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn unfold_exact_native(input: &Tensor, dimension: i64, size: u64, step: u64, cancellation: &CancellationToken) -> Result<Tensor, ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "read only",
        alias_rule: "canonical read-only strided view sharing source storage",
        shape_rule: "selected dimension becomes floor((length-size)/step)+1 and window size is appended",
        dtype_rule: "preserves input dtype",
        accumulation_dtype: "F32 for certified VJP",
        layout_rule: "checked Layout::Strided view",
        device_rule: "preserves native device and stream",
        numeric_rule: "no forward arithmetic",
        tolerance: "bit exact",
        determinism: "fixed stride geometry",
        cancellation_points: "before and after descriptor construction; bounded VJP traversal",
        vjp_rule: "scatter-adds overlapping window gradients into input geometry",
        jvp_rule: "applies identical unfold view to input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/unfold.json",
        evidence_fixture_sha256: "69ff129c149af5134bdae71fa19fa22c0e3df12e20e57ac25d7692c5904cf578",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-EBFD0D7FDA6D",
        baseline_overload_id: "COMFY-TENSOR-OP-EBFD0D7FDA6D:blocked",
        baseline_fixture_sha256: "ce6d4f1c5261d0471691db56b6b95ae4dd911329118b5d87312684a06b127b4d",
        overload_id: "zed.native.tensor.addcmul.f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"tensor_one","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"tensor_two","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"value","kind":"keyword_only","type":"f32","default":1.0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn addcmul_with_context_exact_native(backend: &CpuBackend, input: &Tensor, tensor_one: &Tensor, tensor_two: &Tensor, value: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output through canonical mul and add owners",
        shape_rule: "canonical broadcasting for product and addition",
        dtype_rule: "certified CPU F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "logical traversal and contiguous output",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "input + value * tensor_one * tensor_two",
        tolerance: "1e-5 absolute",
        determinism: "canonical binary kernel order",
        cancellation_points: "canonical mul/add bounded points",
        vjp_rule: "composes canonical add and mul VJPs with broadcast reduction",
        jvp_rule: "composes canonical mul and add JVPs",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/addcmul.json",
        evidence_fixture_sha256: "3e3b38c7cebc9ad92a1932d6e76eef6e98bcc1e167b542accd7da00b9e7cee3d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-E8EA8CB65E2C",
        baseline_overload_id: "COMFY-TENSOR-OP-E8EA8CB65E2C:blocked",
        baseline_fixture_sha256: "bae6c8a3a9468cb45d7b969f600302297e4521d5f6ea5b3fbf54aafb7bc4d82f",
        overload_id: "zed.native.tensor.bitwise-or.promoted.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<IntegerOrBool>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<IntegerOrBool>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<IntegerOrBool>"]"#,
        rust_signature: "fn bitwise_or_with_context_exact_native(backend: &CpuBackend, left: &Tensor, right: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output owned by canonical bitwise traversal",
        shape_rule: "canonical binary broadcasting",
        dtype_rule: "canonical integer/bool promotion shared with bitwise AND and XOR",
        accumulation_dtype: "promoted output dtype",
        layout_rule: "logical traversal and contiguous output",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "elementwise bitwise OR",
        tolerance: "bit exact",
        determinism: "fixed broadcast traversal",
        cancellation_points: "before casts and at bounded traversal points",
        vjp_rule: "non-differentiable integer operation",
        jvp_rule: "non-differentiable integer operation",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/bitwise_or.json",
        evidence_fixture_sha256: "f70bf9fab9c2112fca10a8ac6256933608126ec381b13cf26e14646b478da2b5",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-ECAAC1BA206A",
        baseline_overload_id: "COMFY-TENSOR-OP-ECAAC1BA206A:blocked",
        baseline_fixture_sha256: "6b3c9d1e37f2278c72fce946a3c9b69a5f27aaf092eef34ad8a53976a0e85969",
        overload_id: "zed.native.tensor.cumprod.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"Option<DType>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn cumprod_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output from canonical cumulative-scan owner",
        shape_rule: "preserves shape and scans the normalized dimension",
        dtype_rule: "explicit dtype or canonical integer-to-I64 cumulative default",
        accumulation_dtype: "output dtype",
        layout_rule: "logical traversal and contiguous output",
        device_rule: "CPU reference and source stream",
        numeric_rule: "prefix product with dtype-normalized wrapping integer semantics",
        tolerance: "bit exact for integers; 1e-5 absolute for F32",
        determinism: "fixed prefix traversal",
        cancellation_points: "bounded canonical scan and derivative traversals",
        vjp_rule: "zero-aware sum of prefix products excluding each input",
        jvp_rule: "zero-aware directional prefix product derivative",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/cumprod.json",
        evidence_fixture_sha256: "b956e25b83650a5fb54ef10ac937b399d81e3273124709c14f3a694783e3c61b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-EC849F37A5FD",
        baseline_overload_id: "COMFY-TENSOR-OP-EC849F37A5FD:blocked",
        baseline_fixture_sha256: "4ec863fc5e623ab6a571419ebe7d01955bf4cae9332a9607a9078318aae1413c",
        overload_id: "zed.native.tensor.default-dtype.f32.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: r#"["DType"]"#,
        rust_signature: "fn get_default_dtype_exact_native(cancellation: &CancellationToken) -> Result<DType, ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "read only",
        alias_rule: "request-scoped value with no global mutable state",
        shape_rule: "not applicable",
        dtype_rule: "returns DType::F32",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "canonical Zed default floating dtype",
        tolerance: "exact enum equality",
        determinism: "constant result",
        cancellation_points: "before returning",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/get_default_dtype.json",
        evidence_fixture_sha256: "9c58751ea9e3a7cb3ddc0ef081800f122d4dbb64435b788a98538e0441b2418f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-E8537C6996DA",
        baseline_overload_id: "COMFY-TENSOR-OP-E8537C6996DA:blocked",
        baseline_fixture_sha256: "f5acf180e91e223f6cfeb43fed88bab4a2ee0dc46a3a7abab61f09d41f4ebf08",
        overload_id: "zed.native.tensor.grad-mode-query.v1",
        ordered_parameters_json: r#"[{"name":"mode","kind":"positional_or_keyword","type":"GradientMode","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn is_grad_enabled_exact_native(mode: GradientMode, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "read only",
        alias_rule: "queries canonical request-scoped GradientMode",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "true only for GradientMode::Enabled",
        tolerance: "exact boolean equality",
        determinism: "pure mode query",
        cancellation_points: "before returning",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/is_grad_enabled.json",
        evidence_fixture_sha256: "9087fe23839d1aeac9c9f1bcd46ad482941e2cc641734d114b7dfc31a797e29a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-F122D7D4E807",
        baseline_overload_id: "COMFY-TENSOR-OP-F122D7D4E807:blocked",
        baseline_fixture_sha256: "08960719c07e6f2bf7a6b95765a3596cac0463a265e0d29860d6b7c506f55e8c",
        overload_id: "zed.native.tensor.kron.f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn kron_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "left-pads lower rank with ones and multiplies aligned dimensions",
        dtype_rule: "certified CPU F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "logical traversal and contiguous output",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "Kronecker product with canonical aligned index mapping",
        tolerance: "1e-5 absolute",
        determinism: "fixed output traversal",
        cancellation_points: "bounded forward and derivative traversals",
        vjp_rule: "contracts output gradient against the opposite operand",
        jvp_rule: "kron(input_tangent, other) + kron(input, other_tangent)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/kron.json",
        evidence_fixture_sha256: "0c31302e7403ddbb165c300803986dfd8e8d96d1c8e9f74ea2b505d4467e4910",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-EA16F5C2EAC6",
        baseline_overload_id: "COMFY-TENSOR-OP-EA16F5C2EAC6:blocked",
        baseline_fixture_sha256: "ea4758daf8f44c89aa6d521499437d8f2524e0628353d1d61812b553610dcc0c",
        overload_id: "zed.native.worker.mlu-memory-stats.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["BTreeMap<String, u64>"]"#,
        rust_signature: "fn comfy_worker::mlu_memory_stats_exact_native(capabilities: &BackendCapabilityMatrix, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<BTreeMap<String, u64>, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "thin device-kind adapter over MemoryAccountingSnapshot",
        shape_rule: "not applicable",
        dtype_rule: "u64 byte counters",
        accumulation_dtype: "u64",
        layout_rule: "stable named-stat map",
        device_rule: "requires canonical DeviceKind::Mlu capability",
        numeric_rule: "reports active and reserved bytes from authoritative worker accounting",
        tolerance: "exact integer equality",
        determinism: "snapshot-derived stable map",
        cancellation_points: "before device validation, before accounting lookup, and before publication",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/mlu_memory_stats.json",
        evidence_fixture_sha256: "9dda707f16456a28d689edb43112e3c2adb989c2e76bfe0ecd5e7151ea5b9946",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_21",
        operation_id: "COMFY-TENSOR-OP-E851105B589B",
        baseline_overload_id: "COMFY-TENSOR-OP-E851105B589B:blocked",
        baseline_fixture_sha256: "5bd29d52dd1f850244c65fe5e02466cf875cb908373b8050958c7fd6729bbfb1",
        overload_id: "zed.native.tensor.sin.canonical-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sin_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyOneError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical Task 47 sin owner and returns fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "certified CPU F32 overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical sin logical traversal",
        device_rule: "CPU ordinal zero and source stream",
        numeric_rule: "native sine unary kernel",
        tolerance: "1e-5 absolute",
        determinism: "canonical sin owner",
        cancellation_points: "canonical sin bounded points",
        vjp_rule: "delegates canonical cos(input) times output_gradient VJP",
        jvp_rule: "delegates canonical cos(input) times input_tangent JVP",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-e78ad841c264",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_21/sin.json",
        evidence_fixture_sha256: "e00294398cefa8240075b1611cd0d732211043f6b970ec195d8f75c639f37b18",
    },
]
