&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8A892AD7A3C2",
        baseline_overload_id: "COMFY-TENSOR-OP-8A892AD7A3C2:blocked",
        baseline_fixture_sha256: "889dd18da1cac0ca6b07b645c08b0748bba4c7129e64b7403ce6de4158d545f3",
        overload_id: "sim.native.tensor.is-contiguous.descriptor-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn is_contiguous_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical TensorDescriptor",
        shape_rule: "all ranks including empty and singleton dimensions",
        dtype_rule: "all canonical dtypes",
        accumulation_dtype: "not applicable",
        layout_rule: "delegates TensorDescriptor::is_contiguous",
        device_rule: "descriptor-only projection",
        numeric_rule: "exact stride comparison",
        tolerance: "exact",
        determinism: "descriptor order",
        cancellation_points: "before projection",
        vjp_rule: "metadata predicate is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/is_contiguous.json",
        evidence_fixture_sha256: "6a7c2ccec8b9869475bebb8cb2b278fa781440e121834662f468e52e2a304aa1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8AE4F174E7A1",
        baseline_overload_id: "COMFY-TENSOR-OP-8AE4F174E7A1:blocked",
        baseline_fixture_sha256: "b7ac1cc91ededbcc9aa16542311a654e51fa0d2e500bf0ed1b82a766d5c1b925",
        overload_id: "sim.native.tensor.numel.descriptor-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u64"]"#,
        rust_signature: "fn numel_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<u64, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical TensorDescriptor",
        shape_rule: "checked product with scalar product one and empty dimension product zero",
        dtype_rule: "all canonical dtypes",
        accumulation_dtype: "u64 checked arithmetic",
        layout_rule: "independent of strides",
        device_rule: "descriptor-only projection",
        numeric_rule: "exact checked integer product",
        tolerance: "exact",
        determinism: "shape order",
        cancellation_points: "before projection",
        vjp_rule: "metadata value is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/numel.json",
        evidence_fixture_sha256: "7f0187604afe8850236ff4f9386bdb861cb6b4ccc7f6a15f54a2da0177484744",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8E0C873ABBAD",
        baseline_overload_id: "COMFY-TENSOR-OP-8E0C873ABBAD:blocked",
        baseline_fixture_sha256: "c2ce100cf4ba3f46dce441655b8b5e3a9bea45f43127ccb0fa8a8958221a81cf",
        overload_id: "sim.native.tensor.pow-method.canonical-power.v1",
        ordered_parameters_json: r#"[{"name":"base","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"exponent","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn tensor_pow_with_context_exact_native(backend: &CpuBackend, base: &Tensor, exponent: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical BinaryOperation::Power",
        shape_rule: "canonical right-aligned broadcasting",
        dtype_rule: "F32 observed overload",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE powf including NaN infinity and signed zero",
        tolerance: "F32 power tolerance",
        determinism: "canonical binary traversal",
        cancellation_points: "canonical backend checkpoints",
        vjp_rule: "canonical analytical power VJP with broadcast reduction",
        jvp_rule: "canonical analytical power JVP",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/pow_method.json",
        evidence_fixture_sha256: "08a0c2d3fdb898815b77095525bee9522ee6d1e7ed250db00af5387250f9b81d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8C351B65C789",
        baseline_overload_id: "COMFY-TENSOR-OP-8C351B65C789:blocked",
        baseline_fixture_sha256: "1e302656435c56815bebf13a33e3a807c14c9400312a461f0a2181064dd10189",
        overload_id: "sim.native.attention.math-sdp.explicit-selection.v1",
        ordered_parameters_json: r#"[{"name":"enabled","kind":"positional_or_keyword","type":"bool","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["MathSdpSelection"]"#,
        rust_signature: "fn comfy_model::enable_math_sdp_exact_native(enabled: bool, context: &ExecutionContext<'_>) -> Result<MathSdpSelection, AttentionError>",
        mutation_rule: "read only explicit policy construction",
        alias_rule: "canonical comfy_model attention policy projects AttentionKernelKind without process-global state",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "explicit native attention selection",
        numeric_rule: "boolean selection",
        tolerance: "exact",
        determinism: "constant mapping",
        cancellation_points: "before selection",
        vjp_rule: "configuration is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/enable_math_sdp.json",
        evidence_fixture_sha256: "bb2cacc2d3cf973558eb8a7242488fb15777ae8b887784ab1fc992647f557bc4",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-861EE6173859",
        baseline_overload_id: "COMFY-TENSOR-OP-861EE6173859:blocked",
        baseline_fixture_sha256: "5f52efc9bf5d72a019d8280d1edd16d8766f924efd592bc4a3160e1ab661f219",
        overload_id: "sim.native.device.cuda.current-stream.execution-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"positional_or_keyword","type":"DeviceId<Cuda>","default":null,"keyword_only":false},{"name":"execution","kind":"positional_or_keyword","type":"ExecutionContext","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["StreamId"]"#,
        rust_signature: "fn cuda_current_stream_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, execution: &ExecutionContext<'_>) -> Result<StreamId, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical ExecutionContext stream",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "matching CUDA capability matrix and device",
        numeric_rule: "exact stream identifier",
        tolerance: "exact",
        determinism: "execution-scoped projection",
        cancellation_points: "before projection",
        vjp_rule: "runtime query is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/cuda_current_stream.json",
        evidence_fixture_sha256: "ce06d56fff4d7fbe011ca8ff89e9d05fd4f825375c88869c900666c7f6dbcf1e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-88FE050115A9",
        baseline_overload_id: "COMFY-TENSOR-OP-88FE050115A9:blocked",
        baseline_fixture_sha256: "38e246cf7653d030855024418c134b1143a538db28567a18e1ad8481a78ad4d1",
        overload_id: "sim.native.tensor.cumsum-function.canonical-scan.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dimension","kind":"positional_or_keyword","type":"i64","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"Option<DType>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn cumsum_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 53 canonical cumsum scan",
        shape_rule: "preserves shape and normalizes negative axis",
        dtype_rule: "canonical integer promotion or explicit dtype",
        accumulation_dtype: "output dtype",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "ordered prefix addition",
        tolerance: "exact dtype arithmetic",
        determinism: "row-major scan state",
        cancellation_points: "canonical scan and upload checkpoints",
        vjp_rule: "reverse cumulative sum",
        jvp_rule: "forward cumulative sum of tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/cumsum_function.json",
        evidence_fixture_sha256: "95b680f13e5765c614d69e65b84446db31cc2faf10d3e9c70330e9e77462e861",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-868F72C2BE67",
        baseline_overload_id: "COMFY-TENSOR-OP-868F72C2BE67:blocked",
        baseline_fixture_sha256: "13c7364f96fb78686a0ffee51ad2f4d411ce50922df045f2f3d9ebc929834489",
        overload_id: "sim.native.autocast.gpu-dtype.policy-projection.v1",
        ordered_parameters_json: r#"[{"name":"policy","kind":"positional_or_keyword","type":"AutocastPolicy","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["DType"]"#,
        rust_signature: "fn get_autocast_gpu_dtype_exact_native(policy: &AutocastPolicy, cancellation: &CancellationToken) -> Result<DType, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical AutocastPolicy",
        shape_rule: "not applicable",
        dtype_rule: "validated floating dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "execution-scoped GPU policy",
        numeric_rule: "exact enum projection",
        tolerance: "exact",
        determinism: "policy projection",
        cancellation_points: "before projection",
        vjp_rule: "configuration is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/autocast_gpu_dtype.json",
        evidence_fixture_sha256: "2a44bae05bc3e4b4e33da10d702f6d8fd081e8092ea9e07b3a6ad25c1f38b035",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8B5439D32B8F",
        baseline_overload_id: "COMFY-TENSOR-OP-8B5439D32B8F:blocked",
        baseline_fixture_sha256: "0fe64b96b8257b89761b329eccc6390fe02179a02f81680450049c6aa1dddbd0",
        overload_id: "sim.native.tensor.is-floating-point.dtype-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn is_floating_point_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical DType numeric class",
        shape_rule: "independent of shape",
        dtype_rule: "true only for canonical floating-point class",
        accumulation_dtype: "not applicable",
        layout_rule: "independent of layout",
        device_rule: "descriptor-only projection",
        numeric_rule: "exact enum classification",
        tolerance: "exact",
        determinism: "dtype projection",
        cancellation_points: "before projection",
        vjp_rule: "metadata predicate is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/is_floating_point.json",
        evidence_fixture_sha256: "3cdac6bdfee511f945b814a6b0696171ef2cc5d83d9b352a2f0cbf976b1b6944",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8E5582D70F18",
        baseline_overload_id: "COMFY-TENSOR-OP-8E5582D70F18:blocked",
        baseline_fixture_sha256: "a2881944ee47a54b98af432f5987bc8bb579eb22c5c3494bb5752b811dce184c",
        overload_id: "sim.native.nn.init.fan-in-out.descriptor-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["FanInAndFanOut"]"#,
        rust_signature: "fn calculate_fan_in_and_fan_out_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<FanInAndFanOut, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "read only",
        alias_rule: "projects canonical TensorDescriptor shape",
        shape_rule: "rank at least two; receptive field is product of trailing dimensions",
        dtype_rule: "independent of dtype",
        accumulation_dtype: "u64 checked arithmetic",
        layout_rule: "independent of strides",
        device_rule: "descriptor-only projection",
        numeric_rule: "fan_in=shape[1]*receptive and fan_out=shape[0]*receptive",
        tolerance: "exact",
        determinism: "shape order",
        cancellation_points: "before projection",
        vjp_rule: "initialization metadata is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/fan_in_out.json",
        evidence_fixture_sha256: "87dca37bd1def8c20ea08eb8c368b5e125f26b8cf5c5a69bf8d6b0939d6f70b7",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8C29B75AEA2A",
        baseline_overload_id: "COMFY-TENSOR-OP-8C29B75AEA2A:blocked",
        baseline_fixture_sha256: "cd4f2fcd958306b40a01b3fbb404f82909a1477d88f95cd0bb3082c7fe18faf2",
        overload_id: "sim.native.tensor.stft.f32-complex64.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"n_fft","kind":"positional_or_keyword","type":"usize","default":null,"keyword_only":false},{"name":"hop_length","kind":"keyword_only","type":"Option<usize>","default":null,"keyword_only":true},{"name":"win_length","kind":"keyword_only","type":"Option<usize>","default":null,"keyword_only":true},{"name":"window","kind":"keyword_only","type":"Option<Tensor<F32>>","default":null,"keyword_only":true},{"name":"center","kind":"keyword_only","type":"bool","default":true,"keyword_only":true},{"name":"normalized","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"onesided","kind":"keyword_only","type":"bool","default":true,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<Complex64>"]"#,
        rust_signature: "fn stft_with_context_exact_native(backend: &CpuBackend, input: &Tensor, n_fft: usize, hop_length: Option<usize>, win_length: Option<usize>, window: Option<&Tensor>, center: bool, normalized: bool, onesided: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh complex storage using canonical Tensor upload",
        shape_rule: "one- or two-dimensional waveform to frequency by frame output",
        dtype_rule: "F32 input and window to Complex64 output",
        accumulation_dtype: "F32 complex",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "reflect-centered windowed FFT with exact onesided and normalization rules",
        tolerance: "relative 1e-5 absolute 1e-5",
        determinism: "radix-two FFT or ordered DFT fallback",
        cancellation_points: "bounded frame sample FFT and upload checkpoints",
        vjp_rule: "analytical overlap-add adjoint including reflected padding",
        jvp_rule: "STFT of the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/stft.json",
        evidence_fixture_sha256: "aed97695a6fb231f684f51f2ba535ac23339f084c8cec0361d39e72aaa19588c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-8DF974B2A77C",
        baseline_overload_id: "COMFY-TENSOR-OP-8DF974B2A77C:blocked",
        baseline_fixture_sha256: "6384861bc65c8d94b3c66c0d589a1273a86852064b77887a892df4d51d29f8b2",
        overload_id: "sim.native.tensor.topk.f32-deterministic.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"k","kind":"positional_or_keyword","type":"usize","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":-1,"keyword_only":true},{"name":"largest","kind":"keyword_only","type":"bool","default":true,"keyword_only":true},{"name":"sorted","kind":"keyword_only","type":"bool","default":true,"keyword_only":true}]"#,
        output_arity: "2",
        output_types_json: r#"["Tensor<F32>","Tensor<I64>"]"#,
        rust_signature: "fn topk_with_context_exact_native(backend: &CpuBackend, input: &Tensor, k: usize, dimension: i64, largest: bool, sorted: bool, context: &ExecutionContext<'_>) -> Result<TopKResult, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "out of place",
        alias_rule: "fresh values and indices storage",
        shape_rule: "selected dimension becomes k with checked negative axis",
        dtype_rule: "F32 values and I64 indices",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous outputs",
        device_rule: "CPU ordinal zero",
        numeric_rule: "NaN-first largest ordering and stable lower-index ties",
        tolerance: "exact selected values",
        determinism: "total ordering and stable tie index",
        cancellation_points: "bounded slice selection and upload checkpoints",
        vjp_rule: "scatter output gradients to selected input coordinates",
        jvp_rule: "gather input tangents at selected coordinates",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/topk.json",
        evidence_fixture_sha256: "6d41cf73ca7089da7788677ad5bb2c9cb4a9cbc11911116010d7555b7070119f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_12",
        operation_id: "COMFY-TENSOR-OP-874C83BCB8C5",
        baseline_overload_id: "COMFY-TENSOR-OP-874C83BCB8C5:blocked",
        baseline_fixture_sha256: "41804d88aab914fb51713f121380a2090c68a427e34f32ac48c49790216f6a1a",
        overload_id: "sim.native.tensor.tril.canonical-triangular-mask.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"diagonal","kind":"positional_or_keyword","type":"isize","default":0,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tril_with_context_exact_native(backend: &CpuBackend, input: &Tensor, diagonal: isize, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwelveError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical triangular-mask traversal shared with triu",
        shape_rule: "rank at least two and preserves shape",
        dtype_rule: "canonical zero encoding for input dtype",
        accumulation_dtype: "input dtype",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "retain column-row less than or equal to diagonal",
        tolerance: "exact",
        determinism: "row-major logical traversal",
        cancellation_points: "canonical triangular mask and upload checkpoints",
        vjp_rule: "apply identical lower-triangular mask to output gradient",
        jvp_rule: "apply identical lower-triangular mask to input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-861ee6173859",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_12/tril.json",
        evidence_fixture_sha256: "61c113155e47e82ed6e0e907da21255860ef01d5ab7c04b4f41ff9c1c8281934",
    },
]
