&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-1ED3CF790B68",
        baseline_overload_id: "COMFY-TENSOR-OP-1ED3CF790B68:blocked",
        baseline_fixture_sha256: "e649a974dd9a02c9ca2723cc72e89dc0f1dcd9ce4a7bf68ac53b207da7d2b26f",
        overload_id: "zed.native.tensor.add-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Tensor or Scalar\"},{\"default\":\"1\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"alpha\",\"type\":\"Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"()\"]",
        rust_signature: "fn add_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, other: ElementwiseOperand<'_>, alpha: Scalar, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartThreeError>",
        mutation_rule: "transactional in place; all values are staged before one copy-on-write publication",
        alias_rule: "preserves the receiver handle while detaching shared storage on publication",
        shape_rule: "other may right-align broadcast only to the receiver shape; expansion beyond it fails typed",
        dtype_rule: "receiver dtype is preserved and tensor operands must match it",
        accumulation_dtype: "receiver dtype",
        layout_rule: "logical values are written through canonical TensorWrite",
        device_rule: "CPU ordinal zero only",
        numeric_rule: "left plus alpha times other with canonical dtype overflow/wrapping semantics",
        tolerance: "exact canonical scalar encoding",
        determinism: "fixed row-major staging",
        cancellation_points: "before validation, at bounded staging intervals, before write, and before publication",
        vjp_rule: "autograd records this mutation through the existing canonical mutable-operation journal; no standalone VJP entry point",
        jvp_rule: "same as VJP reachability",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/add_in_place.json",
        evidence_fixture_sha256: "f916a9788e428c1fbb83d4ef44795d42f0f958c9f9c768c649026cfce126d3a9",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-26EF6B18C684",
        baseline_overload_id: "COMFY-TENSOR-OP-26EF6B18C684:blocked",
        baseline_fixture_sha256: "c3c8230dba45ed0e82188feb52a13cbd2fadfaec72708630b2876ef1df033b6e",
        overload_id: "zed.native.tensor.clamp-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"ordered Tensor\"},{\"default\":\"None\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"min\",\"type\":\"optional Scalar\"},{\"default\":\"None\",\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"max\",\"type\":\"optional Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"()\"]",
        rust_signature: "fn clamp_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, minimum: Option<Scalar>, maximum: Option<Scalar>, context: &ExecutionContext<'_>) -> Result<(), ElementwiseRuntimePartThreeError>",
        mutation_rule: "transactional in place; all values are staged before one copy-on-write publication",
        alias_rule: "preserves the receiver handle and uses canonical copy-on-write",
        shape_rule: "shape is unchanged including scalar and empty tensors",
        dtype_rule: "real and integer receiver dtype is preserved; complex and boolean fail typed",
        accumulation_dtype: "none",
        layout_rule: "logical values use canonical strides and TensorWrite",
        device_rule: "CPU ordinal zero only",
        numeric_rule: "inclusive clamp with IEEE NaN propagation; when minimum exceeds maximum every finite value becomes maximum",
        tolerance: "exact canonical encoding",
        determinism: "fixed row-major staging",
        cancellation_points: "before validation, at bounded staging intervals, before write, and before publication",
        vjp_rule: "mutation is journaled by the canonical autograd owner; no standalone VJP entry point",
        jvp_rule: "same as VJP reachability",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/clamp_in_place.json",
        evidence_fixture_sha256: "4c7a588482d78d7d64e82d80ce53ee93fb87be53118f739e4aac4249820372bc",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-1B60D420F7C7",
        baseline_overload_id: "COMFY-TENSOR-OP-1B60D420F7C7:blocked",
        baseline_fixture_sha256: "086008a10f0cf51aad00e8c8309ec35c033696ba41c022a4bad204e33996ec96",
        overload_id: "zed.native.worker.cuda-memory-summary.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"capabilities\",\"type\":\"BackendCapabilityMatrix\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"snapshot\",\"type\":\"MemoryAccountingSnapshot\"}]",
        output_arity: "1",
        output_types_json: "[\"String\"]",
        rust_signature: "fn cuda_memory_summary_exact_native(capabilities: &BackendCapabilityMatrix, snapshot: &MemoryAccountingSnapshot, cancellation: &CancellationToken) -> Result<String, NativeMemoryStatsError>",
        mutation_rule: "read-only projection",
        alias_rule: "returns an owned diagnostic string",
        shape_rule: "not applicable",
        dtype_rule: "integer byte counters",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "certified CUDA and ROCm worker profiles",
        numeric_rule: "exact deterministic projection of canonical memory accounting counters",
        tolerance: "exact",
        determinism: "fixed field order",
        cancellation_points: "before source-stat projection and after formatting",
        vjp_rule: "non-differentiable diagnostics",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/cuda_memory_summary.json",
        evidence_fixture_sha256: "f0142e59d93b1c90be230ae5219157b6f153a4c0b08fc4c940ee1a705dd96d50",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-231238FDA88D",
        baseline_overload_id: "COMFY-TENSOR-OP-231238FDA88D:blocked",
        baseline_fixture_sha256: "371ca96625dc410ad5eb99dfc405b4a9becee27fb30f640ec86ad82b79c20380",
        overload_id: "zed.native.tensor.cudnn-convolution-facade.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"TensorValues<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"weight\",\"type\":\"TensorValues<f32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"geometry\",\"type\":\"3D convolution geometry\"}]",
        output_arity: "1",
        output_types_json: "[\"TensorValues\"]",
        rust_signature: "fn cudnn_convolution_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], padding: Vec<usize>, stride: Vec<usize>, dilation: Vec<usize>, groups: usize, benchmark: bool, deterministic: bool, allow_tf32: bool, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, ElementwiseRuntimePartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical convolution owner and returns fresh values",
        shape_rule: "canonical 3D convolution geometry and checked output shape",
        dtype_rule: "certified f32 overload",
        accumulation_dtype: "f32",
        layout_rule: "canonical convolution layout",
        device_rule: "CPU ordinal zero certified; no cuDNN ABI or fallback",
        numeric_rule: "exact canonical convolution with the observed false,false,true source flags",
        tolerance: "canonical convolution tolerance",
        determinism: "canonical convolution traversal",
        cancellation_points: "before facade validation and throughout canonical convolution",
        vjp_rule: "delegates to canonical convolution VJP",
        jvp_rule: "delegates to canonical convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/cudnn_convolution.json",
        evidence_fixture_sha256: "988f276e8d98c3ae9b0a93a26b489b4f9087d87c9bb615f7e51ead1268ec411e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-1F39246F0FAD",
        baseline_overload_id: "COMFY-TENSOR-OP-1F39246F0FAD:blocked",
        baseline_fixture_sha256: "8a6756184d744e06aaaa855ee46800fd50f513aedde5d88768bf6123269c48fb",
        overload_id: "zed.native.tensor.data-ptr.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"usize\"]",
        rust_signature: "fn data_ptr_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<usize, ElementwiseRuntimePartThreeError>",
        mutation_rule: "read only",
        alias_rule: "returns a borrowed-storage address value without transferring ownership",
        shape_rule: "not applicable; checked storage offset contributes to the address",
        dtype_rule: "all canonical CPU storage dtypes",
        accumulation_dtype: "none",
        layout_rule: "address is base host storage plus checked byte offset",
        device_rule: "CPU ordinal zero only; device handles are never exposed",
        numeric_rule: "exact checked host address",
        tolerance: "exact",
        determinism: "stable while canonical storage remains alive and unmodified",
        cancellation_points: "before and after address projection",
        vjp_rule: "non-differentiable storage metadata",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/data_ptr.json",
        evidence_fixture_sha256: "56a24efd381f1f95ca191c9ae11e81c4f448589bbc2656ca21be97eb0305723e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-263D166C9D1F",
        baseline_overload_id: "COMFY-TENSOR-OP-263D166C9D1F:blocked",
        baseline_fixture_sha256: "8ecd822de22eb24b473dde4ca5e45af4b0cf72bca2ba2e47105e923e31fbba0a",
        overload_id: "zed.native.tensor.expm1.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"real Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn expm1_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "floating dtype preserved; other dtypes fail typed",
        accumulation_dtype: "same floating dtype; f32 derivative profile",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE expm1 preserving signed zero and small-value precision",
        tolerance: "canonical dtype tolerance",
        determinism: "fixed row-major traversal",
        cancellation_points: "before validation, bounded intervals, upload, publication",
        vjp_rule: "output_gradient times exp(input)",
        jvp_rule: "input_tangent times exp(input)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/expm1.json",
        evidence_fixture_sha256: "e516cfe66b7ec1fd5191092c89ba3d59bb2efc9c613eb33d034ed81d19b28769",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-1C55B11AD08B",
        baseline_overload_id: "COMFY-TENSOR-OP-1C55B11AD08B:blocked",
        baseline_fixture_sha256: "70ef6cc634481a7ee8c54fee39b2d5c5888dde55aad1070dce1973fbe73a04de",
        overload_id: "zed.native.tensor.floor.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"real Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn floor_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "real dtypes preserved and integers copied",
        accumulation_dtype: "none; f32 derivative profile",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE floor with signed zero; integers exact",
        tolerance: "exact canonical encoding",
        determinism: "fixed row-major traversal",
        cancellation_points: "before validation, bounded intervals, upload, publication",
        vjp_rule: "zero f32 tensor",
        jvp_rule: "zero f32 tensor",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/floor.json",
        evidence_fixture_sha256: "35399df1db1af134d130b0f6b0536be7618daeab5403cf09842f3205e4d5fdb6",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-22DF6A4C26CC",
        baseline_overload_id: "COMFY-TENSOR-OP-22DF6A4C26CC:blocked",
        baseline_fixture_sha256: "0e914078395dfd1c65d7cf51698938c15d1fdf0b96ecfbe497329796c8f82294",
        overload_id: "zed.native.tensor.greater.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"ordered Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Tensor or Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn greater_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical boolean storage",
        shape_rule: "right-aligned broadcasting including scalar and empty dimensions",
        dtype_rule: "matching ordered tensor dtype or scalar coercible to input dtype",
        accumulation_dtype: "none",
        layout_rule: "canonical contiguous boolean output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "ordered greater-than; IEEE NaN compares false",
        tolerance: "exact",
        determinism: "fixed row-major broadcast traversal",
        cancellation_points: "before validation, bounded intervals, upload, publication",
        vjp_rule: "comparison is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/greater.json",
        evidence_fixture_sha256: "0c065a3266d8adf38a0462866ad01b4dd966370569eea75fe7f14bb9e03bee61",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-2673CE820FAC",
        baseline_overload_id: "COMFY-TENSOR-OP-2673CE820FAC:blocked",
        baseline_fixture_sha256: "4134e7ca59af83719e0058c4ff1c2aa6b0cd4dac8cc17f6cf4b4c815a2419f4e",
        overload_id: "zed.native.autograd.no-grad-mode.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: "[\"GradientMode\"]",
        rust_signature: "fn no_grad_exact_native(cancellation: &CancellationToken) -> Result<GradientMode, ElementwiseRuntimePartThreeError>",
        mutation_rule: "read-only mode construction",
        alias_rule: "returns the canonical GradientMode value",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "exact NoGrad enum value",
        tolerance: "exact",
        determinism: "immutable domain value",
        cancellation_points: "before construction",
        vjp_rule: "suppresses tape recording through the canonical autograd owner",
        jvp_rule: "tangents are not recorded",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/no_grad.json",
        evidence_fixture_sha256: "2e37671ca5c66d4f03ed73949713919d8bcef5f6fac9541245f898ebff36125d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-1917B7227A5C",
        baseline_overload_id: "COMFY-TENSOR-OP-1917B7227A5C:blocked",
        baseline_fixture_sha256: "92b7782b2dc82ce53f82443d47b7d1756b56d0a01584fa71019b9b6301809bac",
        overload_id: "zed.native.tensor.sigmoid.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"real Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn sigmoid_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "shape unchanged",
        dtype_rule: "floating dtype preserved; other dtypes fail typed",
        accumulation_dtype: "same floating dtype; f32 derivative profile",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "delegates scalar mechanics to CpuBackend sigmoid",
        tolerance: "canonical activation tolerance",
        determinism: "fixed row-major traversal",
        cancellation_points: "before validation, bounded intervals, upload, publication",
        vjp_rule: "output_gradient times sigmoid(input) times one minus sigmoid(input)",
        jvp_rule: "input_tangent times sigmoid(input) times one minus sigmoid(input)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/sigmoid.json",
        evidence_fixture_sha256: "d7b5d7bc48cfd17618b5c7c6191b5e9317aa29893878c4ff208d753458679e2f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-2464198E16CB",
        baseline_overload_id: "COMFY-TENSOR-OP-2464198E16CB:blocked",
        baseline_fixture_sha256: "9aaaaa36ad6cd28de1c1f913d4c15e9971770b2f0cb7e61a9a16017a52b7df03",
        overload_id: "zed.native.tensor.torch-archive-bytes.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"value\",\"type\":\"TorchArchiveValue\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<u8>\"]",
        rust_signature: "fn torch_save_exact_native(value: &TorchArchiveValue, cancellation: &CancellationToken) -> Result<Vec<u8>, ElementwiseRuntimePartThreeError>",
        mutation_rule: "read-only content generation; performs no filesystem write or output commit",
        alias_rule: "shared canonical tensor storages are emitted once and tensor views retain offsets/strides",
        shape_rule: "nested values are bounded to depth 64 and one million nodes",
        dtype_rule: "certified PyTorch storage dtypes only",
        accumulation_dtype: "none",
        layout_rule: "deterministic stored ZIP with protocol-2 pickle metadata",
        device_rule: "CPU tensor storage only",
        numeric_rule: "PyTorch-compatible archive content; final publication remains owned by OutputCommitter",
        tolerance: "byte exact for identical input",
        determinism: "BTreeMap ordering, stable storage discovery, zero timestamps",
        cancellation_points: "before and during value encoding and ZIP construction",
        vjp_rule: "serialization is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/torch_save.json",
        evidence_fixture_sha256: "ee9057a7632fb0a13baba3746e4d6012ea5b204d2aa7d1f87b151116ee99e26e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_03",
        operation_id: "COMFY-TENSOR-OP-2255F11A43BA",
        baseline_overload_id: "COMFY-TENSOR-OP-2255F11A43BA:blocked",
        baseline_fixture_sha256: "dff8ab6a55d662d3043618129024bd9fbea5773a4248d4815429eb1c2cff52f9",
        overload_id: "zed.native.worker.xpu-device-count.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"topology\",\"type\":\"MemoryTopology\"}]",
        output_arity: "1",
        output_types_json: "[\"u32\"]",
        rust_signature: "fn xpu_device_count_exact_native(topology: &MemoryTopology, cancellation: &CancellationToken) -> Result<u32, NativeMemoryStatsError>",
        mutation_rule: "read-only projection",
        alias_rule: "returns a copyable count",
        shape_rule: "not applicable",
        dtype_rule: "checked u32 count",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "counts canonical Intel XPU topology entries",
        numeric_rule: "exact count without runtime probing or external fallback",
        tolerance: "exact",
        determinism: "fixed topology traversal",
        cancellation_points: "before traversal, at bounded intervals, and after count",
        vjp_rule: "non-differentiable device metadata",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-1917b7227a5c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_03/xpu_device_count.json",
        evidence_fixture_sha256: "82b770c48f786d2dbeba66117c734856df532bd9e5c68d9a299701d67692722a",
    },
]
