&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-5A1598AB1BFB",
        baseline_overload_id: "COMFY-TENSOR-OP-5A1598AB1BFB:blocked",
        baseline_fixture_sha256: "43eaee6737b3e4a53ec0de01eb4e2e201f4ea52343e939d5b8395b4debbcc969",
        overload_id: "sim.native.tensor.expm1.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn expm1_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to canonical expm1",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output on observed paths",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE expm1 with small-value precision",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical owner checkpoints",
        vjp_rule: "upstream multiplied by exp(input)",
        jvp_rule: "input tangent multiplied by exp(input)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/expm1_method.json",
        evidence_fixture_sha256: "afad384c6efcabfc0a4117c09ff2cf163ef3134a572b099a27d8a1dca905fd03",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-5668EBF27561",
        baseline_overload_id: "COMFY-TENSOR-OP-5668EBF27561:blocked",
        baseline_fixture_sha256: "573c5e1f1c54e54e2b36b50e1c150190ba83d1603013e2143bd36a5d98558969",
        overload_id: "sim.native.tensor.addcdiv.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"tensor1","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"tensor2","type":"Tensor<F32>"},{"default":1.0,"keyword_only":false,"kind":"positional_or_keyword","name":"value","type":"f32"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn addcdiv_with_context_exact_native(backend: &CpuBackend, input: &Tensor, tensor1: &Tensor, tensor2: &Tensor, value: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "right-aligned three-input broadcasting",
        dtype_rule: "co-located F32 tensors",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "input plus value times tensor1 divided by tensor2",
        tolerance: "one ULP",
        determinism: "fixed broadcast traversal",
        cancellation_points: "before validation and at bounded broadcast intervals",
        vjp_rule: "analytical gradients reduced across broadcast dimensions",
        jvp_rule: "analytical product and quotient tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/addcdiv.json",
        evidence_fixture_sha256: "ec0c2c197430d251d003b01f67022fc2251db726d0029a5751e2b86f923252d1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-59C70700F28E",
        baseline_overload_id: "COMFY-TENSOR-OP-59C70700F28E:blocked",
        baseline_fixture_sha256: "3992f94e3b38ac9850b40cd9727d05f88ee8b83271fa3ade19c9b6c80024b3f7",
        overload_id: "sim.native.tensor.argwhere.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<canonical dtype>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn argwhere_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh coordinate storage",
        shape_rule: "nonzero count by input rank",
        dtype_rule: "all canonical input dtypes and I64 coordinates",
        accumulation_dtype: "I64 checked coordinates",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "zero is false and every nonzero component is true",
        tolerance: "exact coordinates",
        determinism: "row-major source order",
        cancellation_points: "bounded scan and publication intervals",
        vjp_rule: "non-differentiable index result",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/argwhere.json",
        evidence_fixture_sha256: "a7f894ae80c81cd55bc5914e88fd49ffe1ab60023e53fb3499979e586124e4d8",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-56E8CFEB8E84",
        baseline_overload_id: "COMFY-TENSOR-OP-56E8CFEB8E84:blocked",
        baseline_fixture_sha256: "61a197faf3c387f64652e35a7ef9e0a80bb46729900d82d13cc7608fa2754baf",
        overload_id: "sim.native.tensor.log1p.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn log1p_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "canonical unary owner allocates fresh storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE log1p including signed zero and domain NaN",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical owner checkpoints",
        vjp_rule: "upstream divided by one plus input",
        jvp_rule: "input tangent divided by one plus input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/log1p.json",
        evidence_fixture_sha256: "03339a7c37a0d759aff013885233d21030c1a51ae6193a9125d3cf62ebd8e30f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-58AE3CA27BFE",
        baseline_overload_id: "COMFY-TENSOR-OP-58AE3CA27BFE:blocked",
        baseline_fixture_sha256: "f82190adf6ea22807a1556befde54f364a7a1c57ac267d03d03e31e9e727cfa3",
        overload_id: "sim.native.model.weight-norm.register.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"module","type":"mutable NativeModule"},{"default":"weight","keyword_only":false,"kind":"positional_or_keyword","name":"name","type":"str"},{"default":0,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"Option<usize>"}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeModule reference"]"#,
        rust_signature: "fn weight_norm_exact_native<'a>(module: &'a mut NativeModule, name: &str, dimension: Option<usize>, cancellation: &CancellationToken) -> Result<&'a mut NativeModule, NativeOpsError>",
        mutation_rule: "NativeModule atomically registers parameter lifecycle metadata",
        alias_rule: "returns the same module reference",
        shape_rule: "dimension must be inside canonical weight rank",
        dtype_rule: "parameter dtype is established by later native loading",
        accumulation_dtype: "canonical weight materialization owner",
        layout_rule: "module parameter layout",
        device_rule: "module parameter device",
        numeric_rule: "later magnitude and direction loading uses canonical NativeModule materialization",
        tolerance: "exact lifecycle state",
        determinism: "generation-monotonic registration",
        cancellation_points: "before validation and before generation publication",
        vjp_rule: "module parametrization delegates tensor gradients to native weight materialization",
        jvp_rule: "module parametrization delegates tangents to native weight materialization",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/weight_norm.json",
        evidence_fixture_sha256: "a4d1304b2e9ed2e215a77c38800af3ddd8295361f52c9281495191c043ca5f08",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-594BD684E5EF",
        baseline_overload_id: "COMFY-TENSOR-OP-594BD684E5EF:blocked",
        baseline_fixture_sha256: "43d34f14f070a1c9d86fb40df6b8f7842af2b4fda60d28587b7a127865740eeb",
        overload_id: "sim.native.optim.sgd.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"parameter_count","type":"usize"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"learning_rate","type":"f32"},{"default":0.0,"keyword_only":false,"kind":"positional_or_keyword","name":"momentum","type":"f32"},{"default":0.0,"keyword_only":false,"kind":"positional_or_keyword","name":"dampening","type":"f32"},{"default":0.0,"keyword_only":false,"kind":"positional_or_keyword","name":"weight_decay","type":"f32"},{"default":false,"keyword_only":false,"kind":"positional_or_keyword","name":"nesterov","type":"bool"},{"default":false,"keyword_only":false,"kind":"positional_or_keyword","name":"maximize","type":"bool"}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeSgd"]"#,
        rust_signature: "fn NativeSgd::new_exact_native(parameter_count: usize, learning_rate: f32, momentum: f32, dampening: f32, weight_decay: f32, nesterov: bool, maximize: bool, cancellation: &CancellationToken) -> Result<NativeSgd, ElementwiseRuntimePartSevenError>",
        mutation_rule: "step stages every parameter and momentum buffer before one publication",
        alias_rule: "Tensor copy-on-write retains canonical storage ownership",
        shape_rule: "parallel parameter, gradient, and state lists match",
        dtype_rule: "observed training path uses F32",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous staged tensors",
        device_rule: "CPU ordinal zero",
        numeric_rule: "PyTorch SGD momentum, dampening, decay, nesterov, and maximize rules",
        tolerance: "one ULP",
        determinism: "parameter and element order",
        cancellation_points: "before each parameter, bounded elements, and before atomic publication",
        vjp_rule: "optimizer update is a terminal state transition",
        jvp_rule: "optimizer update does not propagate tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/sgd.json",
        evidence_fixture_sha256: "74dfd31be903e57dc6b3aa19d0f9d36cacd120df9371fe546f68f7207334c659",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-59EBFDE56C4F",
        baseline_overload_id: "COMFY-TENSOR-OP-59EBFDE56C4F:blocked",
        baseline_fixture_sha256: "f00165aa1e92db28bd4a609328ef26d0a654059ea6c10f11958f2e1811aee257",
        overload_id: "sim.native.tensor.outer.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32, rank 1>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"Tensor<F32, rank 1>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32, rank 2>"]"#,
        rust_signature: "fn outer_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "left length by right length",
        dtype_rule: "co-located F32 vectors",
        accumulation_dtype: "F32",
        layout_rule: "canonical row-major output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "pairwise vector products",
        tolerance: "exact fixture values",
        determinism: "left-major traversal",
        cancellation_points: "bounded pair intervals",
        vjp_rule: "matrix-vector reductions for both inputs",
        jvp_rule: "outer(input tangent, other) plus outer(input, other tangent)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/outer.json",
        evidence_fixture_sha256: "980d93373ca13099261939110d35e63749a17f42849d991af9fc02a88f63100e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-54E28780B32B",
        baseline_overload_id: "COMFY-TENSOR-OP-54E28780B32B:blocked",
        baseline_fixture_sha256: "1b0028b986efa643344a6a2f9d4b83486234d64a761fe5e75905212cb81ed32f",
        overload_id: "sim.native.tensor.rsqrt.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn rsqrt_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "canonical unary owner allocates fresh storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "reciprocal of IEEE square root",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical owner checkpoints",
        vjp_rule: "negative one half upstream divided by input to the three halves",
        jvp_rule: "same derivative applied to tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/rsqrt.json",
        evidence_fixture_sha256: "e6f80ba2878bfec2bd05148eebcc528b8daf0374de2fbb7508ee6dc451c209b8",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-5547BE508AEE",
        baseline_overload_id: "COMFY-TENSOR-OP-5547BE508AEE:blocked",
        baseline_fixture_sha256: "ea29269ab90718c93763ad0b1096e3394b4d3bdd75341121a1dcbc6d812d324c",
        overload_id: "sim.native.tensor.print-options.explicit.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"current","type":"TensorPrintOptions"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"update","type":"Option<TensorPrintOptionsUpdate>"}]"#,
        output_arity: "1",
        output_types_json: r#"["TensorPrintOptions"]"#,
        rust_signature: "fn set_printoptions_exact_native(current: &TensorPrintOptions, update: Option<TensorPrintOptionsUpdate>, cancellation: &CancellationToken) -> Result<TensorPrintOptions, ElementwiseRuntimePartSevenError>",
        mutation_rule: "returns explicit validated options without global state",
        alias_rule: "value object",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "bounded precision, threshold, edge items, line width, and scientific mode",
        tolerance: "exact fields",
        determinism: "pure value mapping",
        cancellation_points: "before and after validation",
        vjp_rule: "presentation state is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/set_printoptions.json",
        evidence_fixture_sha256: "66bfb930a1e883bffb1f51aa1a3ec937cb250da18a26ece58ad27f9c4293b4cb",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-59AD8FFF431A",
        baseline_overload_id: "COMFY-TENSOR-OP-59AD8FFF431A:blocked",
        baseline_fixture_sha256: "af53ca22401037c6d2728be394dcf7097698abef01c89cc84fb81ad347c60297",
        overload_id: "sim.native.tensor.tanh.function.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn tanh_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to canonical tanh",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE hyperbolic tangent",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical owner checkpoints",
        vjp_rule: "upstream times one minus output squared",
        jvp_rule: "input tangent times one minus output squared",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/tanh.json",
        evidence_fixture_sha256: "ef7569e76a34219c73c060a1160273f1eccb9cb5226bc7bd30549d5a4032890f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-576587FE2EAF",
        baseline_overload_id: "COMFY-TENSOR-OP-576587FE2EAF:blocked",
        baseline_fixture_sha256: "194695e014970220d7ee72b3f78da7bcabeaa14f6e950b06387b008e20bbefa5",
        overload_id: "sim.native.xpu.current-stream.explicit.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"capabilities","type":"BackendCapabilityMatrix"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"device","type":"DeviceId<Xpu>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"execution","type":"ExecutionContext"}]"#,
        output_arity: "1",
        output_types_json: r#"["StreamId"]"#,
        rust_signature: "fn xpu_current_stream_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, execution: &ExecutionContext<'_>) -> Result<StreamId, ElementwiseRuntimePartSevenError>",
        mutation_rule: "read-only explicit projection",
        alias_rule: "copy value",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "exact XPU device must match canonical capability matrix",
        numeric_rule: "returns the canonical operation execution context stream",
        tolerance: "exact identity",
        determinism: "pure projection",
        cancellation_points: "the canonical execution context token is checked before and after validation",
        vjp_rule: "runtime stream identity is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/xpu_current_stream.json",
        evidence_fixture_sha256: "80c01db124c240e37d6bc952f71e62e038ed197a41facfc37e4613ed64f7db83",
    },
]
