&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AB3C563E635F",
        baseline_overload_id: "COMFY-TENSOR-OP-AB3C563E635F:blocked",
        baseline_fixture_sha256: "50ac22225c6757e39a829a8bf8139059b92ae33ed8a3c65315c29fcbc2e3fb00",
        overload_id: "zed.native.tensor.float-tensor.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"values","type":"slice<f32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"shape","type":"slice<u64>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn float_tensor_with_context_exact_native(backend: &CpuBackend, values: &[f32], shape: &[u64], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "checked shape equals value count",
        dtype_rule: "F32 through canonical cast/upload owner",
        accumulation_dtype: "none",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "exact f32 payload",
        tolerance: "exact",
        determinism: "fixed upload order",
        cancellation_points: "canonical upload checkpoints",
        vjp_rule: "constructor values are forward inputs outside Tensor autograd",
        jvp_rule: "constructor values are forward inputs outside Tensor autograd",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/float_tensor.json",
        evidence_fixture_sha256: "6e7e840aded898c38fe584ebe227114f2cdf15c9a03fe80bb18b569df09cf7ed",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AA014D6FD446",
        baseline_overload_id: "COMFY-TENSOR-OP-AA014D6FD446:blocked",
        baseline_fixture_sha256: "16e8fc42125c5ee4597671f15e7dbd7cd77c1dc2e3dd4a29e6685860a2ff8115",
        overload_id: "zed.native.tensor.long.canonical-cast.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn long_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical cast owner",
        shape_rule: "preserves shape",
        dtype_rule: "I64",
        accumulation_dtype: "none",
        layout_rule: "canonical cast layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical DType scalar conversion",
        tolerance: "exact",
        determinism: "canonical cast traversal",
        cancellation_points: "canonical cast checkpoints",
        vjp_rule: "integer cast is non-differentiable",
        jvp_rule: "integer cast has no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/long.json",
        evidence_fixture_sha256: "a68519a0e321dc39d2eff842ed67271126b4f71288256a451b83709a692c91e1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AC4C80016C2B",
        baseline_overload_id: "COMFY-TENSOR-OP-AC4C80016C2B:blocked",
        baseline_fixture_sha256: "c8b31ba8b056f4340850471b7c930947589d8c62d8b2f10bd9a114a62c5238f1",
        overload_id: "zed.native.tensor.atan2.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn atan2_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "standard broadcasting",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical f32 atan2 with IEEE NaN and signed-zero quadrants",
        tolerance: "1e-6 absolute",
        determinism: "canonical binary traversal",
        cancellation_points: "backend binary checkpoints",
        vjp_rule: "g_input=g*other/(input^2+other^2), g_other=-g*input/(input^2+other^2) with broadcast reduction",
        jvp_rule: "(other*dinput-input*dother)/(input^2+other^2)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/atan2.json",
        evidence_fixture_sha256: "64440aa2990c882568d08ca05ccb9640d39559144ee2a46fbbe005c0cfbd9ee1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AB6C1D5013D1",
        baseline_overload_id: "COMFY-TENSOR-OP-AB6C1D5013D1:blocked",
        baseline_fixture_sha256: "017aa6fb459f43ef8cb8d86017093016f646cba8c830bfda3e70d81f84efcfdc",
        overload_id: "zed.native.model.attention.flash-sdp-selection.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"enabled","type":"bool"}]"#,
        output_arity: "1",
        output_types_json: r#"["MathSdpSelection"]"#,
        rust_signature: "fn comfy_model::enable_flash_sdp_exact_native(enabled: bool, context: &ExecutionContext<'_>) -> Result<MathSdpSelection, AttentionError>",
        mutation_rule: "returns immutable explicit policy",
        alias_rule: "copyable value",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "selection does not certify a device kernel",
        numeric_rule: "exact enabled or disabled mapping",
        tolerance: "exact",
        determinism: "explicit caller-scoped value",
        cancellation_points: "before selection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/enable_flash_sdp.json",
        evidence_fixture_sha256: "37af31d09cb20a6f082e987fb75a48196bd91ea36aa431777226e92c72d13d36",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AA097B951CB6",
        baseline_overload_id: "COMFY-TENSOR-OP-AA097B951CB6:blocked",
        baseline_fixture_sha256: "07c0dd87451f382a4e697fae76a7104bbfeb67a2ae047b2f2ff540f8d25b065f",
        overload_id: "zed.native.tensor.baddbmm.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"broadcastable Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"batch1","type":"Tensor<F32>[B,N,M]"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"batch2","type":"Tensor<F32>[B,M,P]"},{"default":1.0,"keyword_only":true,"kind":"keyword_only","name":"beta","type":"f32"},{"default":1.0,"keyword_only":true,"kind":"keyword_only","name":"alpha","type":"f32"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>[B,N,P]"]"#,
        rust_signature: "fn baddbmm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, batch1: &Tensor, batch2: &Tensor, beta: f32, alpha: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place with publication after all stages",
        alias_rule: "fresh canonical storage",
        shape_rule: "beta*input broadcast to [B,N,P] plus alpha*(batch1@batch2)",
        dtype_rule: "F32",
        accumulation_dtype: "F32 fixed inner order",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "beta zero does not read input; fixed multiply-add order",
        tolerance: "1e-5 absolute",
        determinism: "row-major batch,row,column,inner order",
        cancellation_points: "before dispatch, each bounded inner loop, each backend stage, before publication",
        vjp_rule: "analytical gradients for input and both batch matrices with broadcast reduction",
        jvp_rule: "beta*dinput+alpha*(dbatch1@batch2+batch1@dbatch2)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/baddbmm.json",
        evidence_fixture_sha256: "f678527c61458601b757fcb751cd98e04f11e66550b8636698628ac37be6cb0e",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-A91E1CFDC489",
        baseline_overload_id: "COMFY-TENSOR-OP-A91E1CFDC489:blocked",
        baseline_fixture_sha256: "84a33f8b7deda6abc47a5f1604c7cc6f3cce497b8f2a207e8b427523e43cf58b",
        overload_id: "zed.native.tensor.ceil-function.canonical.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"real Tensor"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn ceil_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 44 canonical ceil owner",
        shape_rule: "preserves shape",
        dtype_rule: "canonical ceil dtype rules",
        accumulation_dtype: "none",
        layout_rule: "canonical ceil layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical IEEE ceiling",
        tolerance: "canonical ceil tolerance",
        determinism: "canonical ceil traversal",
        cancellation_points: "canonical ceil checkpoints",
        vjp_rule: "inherits zero VJP from canonical ceil",
        jvp_rule: "inherits zero JVP from canonical ceil",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/ceil_function.json",
        evidence_fixture_sha256: "fb302f32910e22a99e20c6572502ab6a92d88f9e051d039aea3b74d7f41a2085",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-A8B4A9E79500",
        baseline_overload_id: "COMFY-TENSOR-OP-A8B4A9E79500:blocked",
        baseline_fixture_sha256: "99ecffe9726f15cd5493dc9e29417915752edbe4cc40645ded7f422f18f80cff",
        overload_id: "zed.native.tensor.diag.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"rank-one or rank-two Tensor"},{"default":0,"keyword_only":false,"kind":"positional_or_keyword","name":"diagonal","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn diag_with_context_exact_native(backend: &CpuBackend, input: &Tensor, diagonal: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "rank one constructs a square offset-diagonal matrix; rank two extracts the checked offset diagonal",
        dtype_rule: "preserves canonical dtype bytes",
        accumulation_dtype: "none",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "byte-exact copy with canonical zero encoding",
        tolerance: "exact",
        determinism: "fixed diagonal order",
        cancellation_points: "bounded diagonal intervals and upload",
        vjp_rule: "inverse diagonal extraction or scatter into the original shape",
        jvp_rule: "same linear diagonal transform",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/diag.json",
        evidence_fixture_sha256: "5e1abd482d1ce32d05b12237bb6bb129285fae1b94bcae54652e7bc655173d6a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AC979D604DAA",
        baseline_overload_id: "COMFY-TENSOR-OP-AC979D604DAA:blocked",
        baseline_fixture_sha256: "9292fbc02872498e81e6e4af1634129987fe38a38fe9d1d09ba16cf29edb39d7",
        overload_id: "zed.native.tensor.fliplr.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor rank>=2"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn fliplr_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh non-aliasing storage",
        shape_rule: "preserves shape and reverses dimension one",
        dtype_rule: "preserves canonical dtype bytes",
        accumulation_dtype: "none",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "byte-exact logical reversal",
        tolerance: "exact",
        determinism: "fixed row-major traversal",
        cancellation_points: "bounded element intervals and upload",
        vjp_rule: "fliplr of output gradient",
        jvp_rule: "fliplr of input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/fliplr.json",
        evidence_fixture_sha256: "7a9a0365721ac651b0a92912970f8dbbb916ab81d7ba412ef7aa7ea9c494a7a8",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-A69CEE614EB5",
        baseline_overload_id: "COMFY-TENSOR-OP-A69CEE614EB5:blocked",
        baseline_fixture_sha256: "47ee9e35a85adf204a64d51a24c873fd6308e77a2e3851faf6128ec280f8f30a",
        overload_id: "zed.native.worker.npu-availability.topology-projection.v1",
        ordered_parameters_json: "[]",
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn comfy_worker::npu_is_available_exact_native(topology: &MemoryTopology, context: &ExecutionContext<'_>) -> Result<bool, NativeMemoryStatsError>",
        mutation_rule: "read-only projection",
        alias_rule: "copyable bool",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "true exactly when canonical topology contains an NPU device",
        numeric_rule: "exact count greater than zero",
        tolerance: "exact",
        determinism: "canonical topology order independent",
        cancellation_points: "canonical device-count checkpoints",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/npu_is_available.json",
        evidence_fixture_sha256: "8ea4384986d6a94e9a3ab8aa14b61e99a1c1998bebf7075cfa8f3f806dafd01c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AA36FFD0433B",
        baseline_overload_id: "COMFY-TENSOR-OP-AA36FFD0433B:blocked",
        baseline_fixture_sha256: "d64d688a35a01603c542e87d8d58bb36ced2a303be96f7522409cfc5607983f1",
        overload_id: "zed.native.tensor.ones-like.canonical-full-like.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor"},{"default":null,"keyword_only":true,"kind":"keyword_only","name":"dtype","type":"Option<DType>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn ones_like_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical full_like allocation",
        shape_rule: "preserves shape",
        dtype_rule: "explicit dtype or input dtype",
        accumulation_dtype: "none",
        layout_rule: "canonical full_like layout",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical DType encoding of one",
        tolerance: "exact",
        determinism: "canonical full_like traversal",
        cancellation_points: "canonical full_like checkpoints",
        vjp_rule: "output is constant with respect to input values",
        jvp_rule: "zero tangent with respect to input values",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/ones_like.json",
        evidence_fixture_sha256: "da6d2175f919b02d6d543c3b487d3443abeb02178c116012ab85c1e305a67005",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-AAB5F10B20F5",
        baseline_overload_id: "COMFY-TENSOR-OP-AAB5F10B20F5:blocked",
        baseline_fixture_sha256: "4c19317c88f93c1ce04b5c9e8cfabd0e3cd4808cfdb90c2b49a9547cfcb881ff",
        overload_id: "zed.native.tensor.searchsorted.cpu-f32-i64.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"sorted_sequence","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"values","type":"Tensor<F32>"},{"default":false,"keyword_only":true,"kind":"keyword_only","name":"right","type":"bool"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn searchsorted_with_context_exact_native(backend: &CpuBackend, sorted_sequence: &Tensor, values: &Tensor, right: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "output shape equals values; one-dimensional boundaries broadcast across value rows, otherwise leading dimensions match",
        dtype_rule: "F32 boundaries and values, I64 indices",
        accumulation_dtype: "none",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "lower or upper bound binary search; NaN values insert at row end; unsorted or NaN boundaries fail typed",
        tolerance: "exact indices",
        determinism: "fixed row-major binary search",
        cancellation_points: "bounded values and validation intervals plus upload",
        vjp_rule: "indices are non-differentiable",
        jvp_rule: "indices have no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/searchsorted.json",
        evidence_fixture_sha256: "451028219c6a9f57c427013b6509c9c0592a6a2d4b29aaa056f71f3506b27043",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_15",
        operation_id: "COMFY-TENSOR-OP-A68AE691163C",
        baseline_overload_id: "COMFY-TENSOR-OP-A68AE691163C:blocked",
        baseline_fixture_sha256: "894f33002d101e4637a0fe529438d11dce9addd3623b22518c9604afad285f3b",
        overload_id: "zed.native.tensor.tan.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn tan_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartFifteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero",
        numeric_rule: "canonical f32 tangent with IEEE NaN, infinity, and signed zero",
        tolerance: "1e-6 absolute on finite fixtures",
        determinism: "canonical unary traversal",
        cancellation_points: "backend unary checkpoints",
        vjp_rule: "output gradient divided by cos(input)^2",
        jvp_rule: "input tangent divided by cos(input)^2",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-a68ae691163c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_15/tan.json",
        evidence_fixture_sha256: "fb1da2ab82c1db91bc0859e235bc75e5c383be8d34d90331a5e4f15f463fa986",
    },
]
