&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C579143F7B56",
        baseline_overload_id: "COMFY-TENSOR-OP-C579143F7B56:blocked",
        baseline_fixture_sha256: "1d01fb90e7f36afff1c05c80459e67234cf07d63f4c63fc5e4d1cc1a773d10e2",
        overload_id: "zed.native.tensor.byte-tensor.canonical-u8-constructor.v1",
        ordered_parameters_json: r#"[{"name":"values","kind":"positional_or_keyword","type":"&[u8]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<U8>"]"#,
        rust_signature: "fn byte_tensor_with_context_exact_native(backend: &CpuBackend, values: &[u8], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates the canonical tensor constructor",
        shape_rule: "one-dimensional length equal to values",
        dtype_rule: "U8",
        accumulation_dtype: "not applicable",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero on the caller-owned context stream",
        numeric_rule: "each byte is preserved exactly",
        tolerance: "bit exact",
        determinism: "input order",
        cancellation_points: "before allocation, during bounded value conversion, and during canonical upload",
        vjp_rule: "integer constructor is not differentiable",
        jvp_rule: "integer constructor is not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/byte_tensor.json",
        evidence_fixture_sha256: "54244c1b3a4bc0ee5f773147bcafdcda22373823c950fecef93eb1f6dfdd0668",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C83ECA429710",
        baseline_overload_id: "COMFY-TENSOR-OP-C83ECA429710:blocked",
        baseline_fixture_sha256: "ff57f8dfce330441d4a5635c03395f64f205db56572c08634fbed20d4dcbf415",
        overload_id: "zed.native.tensor.element-size.dtype-projection.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"&Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u64"]"#,
        rust_signature: "fn element_size_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<u64, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "read only",
        alias_rule: "scalar projection",
        shape_rule: "independent of shape",
        dtype_rule: "canonical DType byte width",
        accumulation_dtype: "u64",
        layout_rule: "independent of layout",
        device_rule: "independent of device",
        numeric_rule: "exact byte width",
        tolerance: "exact",
        determinism: "immutable descriptor projection",
        cancellation_points: "before projection",
        vjp_rule: "metadata query is not differentiable",
        jvp_rule: "metadata query is not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/element_size.json",
        evidence_fixture_sha256: "cb683097693cd8beb61d6b22fd2ad78e2ba4a3c90c5fe8e2a71e04855f9a5630",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C1FAC5999B98",
        baseline_overload_id: "COMFY-TENSOR-OP-C1FAC5999B98:blocked",
        baseline_fixture_sha256: "1da3e536b8750b776322a56b92148ae383167ffd3cbbb382bd1aecf8514ec4d3",
        overload_id: "zed.native.tensor.sub-method.canonical-add-adapter-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>|Scalar","default":null,"keyword_only":false},{"name":"alpha","kind":"keyword_only","type":"f32","default":1.0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn sub_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: ElementwiseOperand<'_>, alpha: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical add and binary primitive owners with negated alpha",
        shape_rule: "canonical broadcast shape",
        dtype_rule: "source F32 profile",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "input minus alpha times other",
        tolerance: "1e-6 absolute",
        determinism: "canonical binary traversal",
        cancellation_points: "before validation and at canonical primitive checkpoints",
        vjp_rule: "input gradient one and other gradient negative alpha with broadcast reduction",
        jvp_rule: "input tangent minus alpha times other tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/sub_method.json",
        evidence_fixture_sha256: "573f81188515a2a9dfcfde5694718238b89757ecda4e744f45406003bb39faee",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C575200CD790",
        baseline_overload_id: "COMFY-TENSOR-OP-C575200CD790:blocked",
        baseline_fixture_sha256: "dbf3825e1273c27bd4808e79f08af23f069e328a59a247f83fda9c3dd8d516ea",
        overload_id: "zed.native.tensor.add.scalar-tensor-source-overload-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"f32","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"alpha","kind":"keyword_only","type":"f32","default":1.0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn add_scalar_tensor_with_context_exact_native(backend: &CpuBackend, input: f32, other: &Tensor, alpha: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical primitive output",
        shape_rule: "preserves tensor shape",
        dtype_rule: "source F32 profile",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero and tensor stream",
        numeric_rule: "input plus alpha times other",
        tolerance: "1e-6 absolute",
        determinism: "canonical multiply then add primitives",
        cancellation_points: "before validation and at canonical primitive checkpoints",
        vjp_rule: "tensor gradient is alpha times output gradient",
        jvp_rule: "alpha times tensor tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/add.json",
        evidence_fixture_sha256: "799f33f8d62e12c9a4146ba96d15e4484f3f6825aae431d19e35a79bcb00555d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C7A255E21877",
        baseline_overload_id: "COMFY-TENSOR-OP-C7A255E21877:blocked",
        baseline_fixture_sha256: "0676365779425333bd64f8045f9032c1600c009c05c9b80ad2963b8cc45c7131",
        overload_id: "zed.native.tensor.bincount.unweighted-integer-source-overload.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<Integer>","default":null,"keyword_only":false},{"name":"minlength","kind":"keyword_only","type":"u64","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn bincount_with_context_exact_native(backend: &CpuBackend, input: &Tensor, minlength: u64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh count storage",
        shape_rule: "one-dimensional max(max(input)+1,minlength)",
        dtype_rule: "integer input and I64 output",
        accumulation_dtype: "checked I64 counts",
        layout_rule: "contiguous",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "nonnegative exact histogram",
        tolerance: "exact",
        determinism: "input order with checked counters",
        cancellation_points: "before validation and at bounded input, initialization, accumulation, and upload intervals",
        vjp_rule: "integer histogram is not differentiable",
        jvp_rule: "integer histogram is not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/bincount.json",
        evidence_fixture_sha256: "af4b3d6151ffabd3d00561e4d8e2e44a4438a7f4a874be040b38fc09ca786c10",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C7B72CD0ABE7",
        baseline_overload_id: "COMFY-TENSOR-OP-C7B72CD0ABE7:blocked",
        baseline_fixture_sha256: "4bcd316b4de994b1f9ecfae81f10389f500d6d1b495fade4717ba114c11a3a85",
        overload_id: "zed.native.tensor.bucketize.sorted-boundaries-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"boundaries","kind":"positional_or_keyword","type":"Tensor<F32,rank=1>","default":null,"keyword_only":false},{"name":"right","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"out_int32","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64|I32>"]"#,
        rust_signature: "fn bucketize_with_context_exact_native(backend: &CpuBackend, input: &Tensor, boundaries: &Tensor, right: bool, out_int32: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh index storage",
        shape_rule: "preserves input shape",
        dtype_rule: "F32 input and boundaries; I64 default or I32 requested output",
        accumulation_dtype: "usize search index checked into output dtype",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero and common stream",
        numeric_rule: "lower-bound when right is false and upper-bound when true; NaN maps after all boundaries",
        tolerance: "exact",
        determinism: "sorted binary partition",
        cancellation_points: "before validation and at bounded boundary, input, and upload intervals",
        vjp_rule: "discrete search is not differentiable",
        jvp_rule: "discrete search is not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/bucketize.json",
        evidence_fixture_sha256: "8930e0542fff8edbac46689a6c7af6ddf21b8107675739668536ef0e827c8f09",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C0D4EF19ED71",
        baseline_overload_id: "COMFY-TENSOR-OP-C0D4EF19ED71:blocked",
        baseline_fixture_sha256: "1533d08f3f0276779ea3cd0ea546ba8038bfbd088155a71aaa78ecf296440d05",
        overload_id: "zed.native.runtime.compiler-is-compiling.compile-phase-projection.v1",
        ordered_parameters_json: r#"[{"name":"phase","kind":"positional_or_keyword","type":"NativeCompilePhase","default":"eager","keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn comfy_runtime::compiler_is_compiling_exact_native(phase: NativeCompilePhase, cancellation: &CancellationToken) -> Result<bool, NativeCompileError>",
        mutation_rule: "read only",
        alias_rule: "copyable boolean projection",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "native compile owner independent of device",
        numeric_rule: "true only during native graph capture",
        tolerance: "exact",
        determinism: "explicit compile phase",
        cancellation_points: "before projection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/compiler_is_compiling.json",
        evidence_fixture_sha256: "79efa0d621791002df83c68dbec8f0dc3b5d672cf54a5ef8acaaf15e8518bd0c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C64E630A756E",
        baseline_overload_id: "COMFY-TENSOR-OP-C64E630A756E:blocked",
        baseline_fixture_sha256: "948e52ad84f07cd8d1c31c767dec434d3fb534352cc991b488b9c7c3326d257c",
        overload_id: "zed.native.tensor.is-autocast-enabled.policy-projection.v1",
        ordered_parameters_json: r#"[{"name":"policy","kind":"positional_or_keyword","type":"&AutocastPolicy","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn is_autocast_enabled_exact_native(policy: &AutocastPolicy, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "read only",
        alias_rule: "copyable boolean projection",
        shape_rule: "not applicable",
        dtype_rule: "canonical policy validates floating dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "explicit policy scope",
        numeric_rule: "exact enabled flag",
        tolerance: "exact",
        determinism: "immutable policy",
        cancellation_points: "before projection",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/is_autocast_enabled.json",
        evidence_fixture_sha256: "655c38ae401c6a4ca7912e37c7affbae4386987aae2eb651e8d8d5e5c27bc63f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C63B343CD3EF",
        baseline_overload_id: "COMFY-TENSOR-OP-C63B343CD3EF:blocked",
        baseline_fixture_sha256: "7cae8259f0e4a8e5ba8c1e3ce1540019577578524f01a4c7888ed30e1c22bdcb",
        overload_id: "zed.native.tensor.library-custom-op.kernel-declaration-adapter.v1",
        ordered_parameters_json: r#"[{"name":"qualified_name","kind":"positional_or_keyword","type":"&str","default":null,"keyword_only":false},{"name":"mutates_arguments","kind":"keyword_only","type":"&[usize]","default":"[]","keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeCustomOperatorDeclaration"]"#,
        rust_signature: "fn library_custom_op_exact_native(qualified_name: &str, mutates_arguments: &[usize], cancellation: &CancellationToken) -> Result<NativeCustomOperatorDeclaration, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "constructs an immutable declaration only",
        alias_rule: "maps explicitly to canonical CustomKernelId execution identity",
        shape_rule: "not applicable until declared kernel invocation",
        dtype_rule: "not applicable until declared kernel invocation",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable until declared kernel invocation",
        device_rule: "backend dispatch remains owned by TensorBackend",
        numeric_rule: "valid namespace::identifier and unique mutation indices",
        tolerance: "exact",
        determinism: "canonical name mapping and caller order",
        cancellation_points: "before validation and publication",
        vjp_rule: "kernel declaration carries no gradient; the bound kernel owns maps",
        jvp_rule: "kernel declaration carries no tangent; the bound kernel owns maps",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/library_custom_op.json",
        evidence_fixture_sha256: "6280ca0638a3b664fa4e3343d55571e99008abc4367b32f8e77477ef9c1a8962",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C46EB25624FB",
        baseline_overload_id: "COMFY-TENSOR-OP-C46EB25624FB:blocked",
        baseline_fixture_sha256: "266382e34e50df79c829578f38b74fae7d019d5de25db037edbce21f80dbea61",
        overload_id: "zed.native.tensor.log-softmax.stable-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn log_softmax_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage after canonical functional delegation",
        shape_rule: "preserves shape along normalized dimension",
        dtype_rule: "source F32 profile",
        accumulation_dtype: "F64 exponential sum projected to F32",
        layout_rule: "contiguous output from logical input traversal",
        device_rule: "CPU ordinal zero and input stream",
        numeric_rule: "stable max-shift log-sum-exp",
        tolerance: "1e-6 absolute",
        determinism: "canonical activation owner fixed outer-axis-inner traversal",
        cancellation_points: "before validation, during logical storage projection and canonical axis traversal, and before atomic upload",
        vjp_rule: "gradient minus softmax(output) times axis gradient sum",
        jvp_rule: "tangent minus the axis sum of softmax(output) times tangent, broadcast across the axis",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/log_softmax.json",
        evidence_fixture_sha256: "350e2468dcabde60b351f111a3361e8ef715c2d1f9eb902f9122640c97b0baf8",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C1BBE55AA3A0",
        baseline_overload_id: "COMFY-TENSOR-OP-C1BBE55AA3A0:blocked",
        baseline_fixture_sha256: "40cc075a9a631aac7efc39f1f90269c7b2d797a4c3770cfafcc1200f642c6f52",
        overload_id: "zed.native.tensor.numel-function.canonical-descriptor-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"&Tensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["u64"]"#,
        rust_signature: "fn numel_function_exact_native(input: &Tensor, cancellation: &CancellationToken) -> Result<u64, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "read only",
        alias_rule: "delegates Task 12 canonical descriptor projection",
        shape_rule: "checked product with scalar rank equal to one element and any zero dimension equal to zero",
        dtype_rule: "independent of dtype",
        accumulation_dtype: "checked u64",
        layout_rule: "logical shape independent of storage layout",
        device_rule: "independent of device",
        numeric_rule: "exact checked product",
        tolerance: "exact",
        determinism: "immutable descriptor",
        cancellation_points: "before delegation and at the canonical numel checkpoint",
        vjp_rule: "metadata query is not differentiable",
        jvp_rule: "metadata query is not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/numel.json",
        evidence_fixture_sha256: "adbb7878dbeab9a529b96f3fa7e2555cf2db6b67cf27589b6fa7af068cc744c1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_18",
        operation_id: "COMFY-TENSOR-OP-C05FE0730305",
        baseline_overload_id: "COMFY-TENSOR-OP-C05FE0730305:blocked",
        baseline_fixture_sha256: "18cfdfd09cb03d182dcdfd6d194e052ff3c6a8fcc155c0f7f54eef891c758ab8",
        overload_id: "zed.native.tensor.xpu-stream.canonical-stream-registry.v1",
        ordered_parameters_json: r#"[{"name":"registry","kind":"positional_or_keyword","type":"&NativeStreamRegistry","default":null,"keyword_only":false},{"name":"capabilities","kind":"positional_or_keyword","type":"&BackendCapabilityMatrix","default":null,"keyword_only":false},{"name":"device","kind":"keyword_only","type":"DeviceId<Xpu>","default":null,"keyword_only":true},{"name":"priority","kind":"keyword_only","type":"i32","default":0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeStream"]"#,
        rust_signature: "fn xpu_stream_exact_native(registry: &NativeStreamRegistry, capabilities: &BackendCapabilityMatrix, device: DeviceId, priority: i32, cancellation: &CancellationToken) -> Result<NativeStream, ElementwiseRuntimePartEighteenError>",
        mutation_rule: "atomically allocates one non-default stream identity",
        alias_rule: "owned immutable stream descriptor",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "checked u64 identity sequence",
        layout_rule: "not applicable",
        device_rule: "exact XPU device matching canonical capability matrix",
        numeric_rule: "preserves signed priority and unique monotonically allocated identity",
        tolerance: "exact",
        determinism: "registry allocation order",
        cancellation_points: "before device validation and atomic allocation",
        vjp_rule: "not differentiable",
        jvp_rule: "not differentiable",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-c05fe0730305",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_18/xpu_stream.json",
        evidence_fixture_sha256: "2ee8793fd7261a296f4f139b262513bb87a065c7a4bd843ccbe29a7fd23e0086",
    },
]
