&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9C679FFC6CCF",
        baseline_overload_id: "COMFY-TENSOR-OP-9C679FFC6CCF:blocked",
        baseline_fixture_sha256: "e9bb1204f649c6f65fa7d0fd9e34161b5fd989ff623684913d4f365a60420dc7",
        overload_id: "zed.native.tensor.lerp.canonical-binary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"end","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"weight","kind":"positional_or_keyword","type":"f32","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn lerp_with_context_exact_native(backend: &CpuBackend, input: &Tensor, end: &Tensor, weight: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical binary primitives and returns fresh storage",
        shape_rule: "NumPy-style input/end broadcasting",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero with matching streams",
        numeric_rule: "input + weight * (end - input)",
        tolerance: "absolute 0.00001",
        determinism: "canonical binary traversal",
        cancellation_points: "primitive boundaries and derivative traversal",
        vjp_rule: "broadcast-reduced (1-weight) and weight gradients",
        jvp_rule: "the same affine interpolation over tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/lerp.json",
        evidence_fixture_sha256: "eba1c744569aca399fdfd3772685a1e9c3dffaf8d7211787706d178e7903098d",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9547009E77B6",
        baseline_overload_id: "COMFY-TENSOR-OP-9547009E77B6:blocked",
        baseline_fixture_sha256: "c792bfc15186ca6a3f7c2ec68ef5b450afc708d39e92e9977525fdaaf4a1c71f",
        overload_id: "zed.native.tensor.sign-method.canonical-unary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn tensor_sign_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates Task 54 canonical Signum unary primitive",
        shape_rule: "preserves shape",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "negative, signed-zero, positive and NaN sign semantics from canonical Signum",
        tolerance: "exact",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical unary checkpoints",
        vjp_rule: "zero almost everywhere via Task 54",
        jvp_rule: "zero almost everywhere via Task 54",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/sign_method.json",
        evidence_fixture_sha256: "8f27e945780e8783526bc1fef107f21165c419d30a0fec54b200d76d1a065543",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9443F2A50F6D",
        baseline_overload_id: "COMFY-TENSOR-OP-9443F2A50F6D:blocked",
        baseline_fixture_sha256: "6f3eade1d35ef43d5d5b812aa3102afe3482b9a37055d444253d22e6a01ca1d8",
        overload_id: "zed.native.tensor.addmm.linear-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"matrix1","kind":"positional_or_keyword","type":"Tensor<F32,rank=2>","default":null,"keyword_only":false},{"name":"matrix2","kind":"positional_or_keyword","type":"Tensor<F32,rank=2>","default":null,"keyword_only":false},{"name":"beta","kind":"keyword_only","type":"f32","default":1.0,"keyword_only":true},{"name":"alpha","kind":"keyword_only","type":"f32","default":1.0,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn addmm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, matrix1: &Tensor, matrix2: &Tensor, beta: f32, alpha: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates the canonical native linear equation and returns fresh storage",
        shape_rule: "rank-two compatible matrices plus broadcast-compatible input",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU ordinal zero with matching streams",
        numeric_rule: "beta * input + alpha * matrix1 @ matrix2",
        tolerance: "absolute 0.00001",
        determinism: "fixed matrix traversal inherited from native linear",
        cancellation_points: "linear and broadcast traversal checkpoints",
        vjp_rule: "linear VJP plus broadcast-reduced input gradient",
        jvp_rule: "linear JVP plus scaled input tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/addmm.json",
        evidence_fixture_sha256: "13ecc148f536920dc17ed42e334fac5811e06627fbe2eb68cab6a5ff7ad9991f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9285B877ECB7",
        baseline_overload_id: "COMFY-TENSOR-OP-9285B877ECB7:blocked",
        baseline_fixture_sha256: "78e3cd202f934c401ab0874f152a58ed36c9b6cc9d87e68267398fd449d28ab8",
        overload_id: "zed.native.tensor.allclose.isclose-reduction.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"other","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"relative_tolerance","kind":"keyword_only","type":"f32","default":0.00001,"keyword_only":true},{"name":"absolute_tolerance","kind":"keyword_only","type":"f32","default":0.00000001,"keyword_only":true},{"name":"equal_nan","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn allclose_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, relative_tolerance: f32, absolute_tolerance: f32, equal_nan: bool, context: &ExecutionContext<'_>) -> Result<bool, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "read only",
        alias_rule: "reduces Task 54 canonical isclose output",
        shape_rule: "broadcast-compatible inputs",
        dtype_rule: "F32 inputs and boolean intermediate",
        accumulation_dtype: "not applicable",
        layout_rule: "logical traversal",
        device_rule: "CPU ordinal zero",
        numeric_rule: "all(abs(input-other) <= atol + rtol*abs(other)) with equal_nan option",
        tolerance: "exact boolean",
        determinism: "fixed reduction order",
        cancellation_points: "isclose and reduction traversal",
        vjp_rule: "non-differentiable boolean result",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/allclose.json",
        evidence_fixture_sha256: "0263d6a8e24d9609bd9e5555cdfada032a642b25d1c31d196b0cf7944ee4e485",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9CC2489AFA14",
        baseline_overload_id: "COMFY-TENSOR-OP-9CC2489AFA14:blocked",
        baseline_fixture_sha256: "e1529c3999ce5590db8ff4defb0d96578cc72919b5abe8cae709bd087c6b3325",
        overload_id: "zed.native.device.cuda.bf16.capability-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix<Cuda>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn cuda_is_bf16_supported_exact_native(capabilities: &BackendCapabilityMatrix, cancellation: &CancellationToken) -> Result<bool, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "read only",
        alias_rule: "projects the canonical backend capability matrix",
        shape_rule: "not applicable",
        dtype_rule: "queries Bf16 support",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "CUDA capability matrix only",
        numeric_rule: "exact capability membership",
        tolerance: "exact",
        determinism: "immutable projection",
        cancellation_points: "before and after projection",
        vjp_rule: "device query is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/cuda_bf16.json",
        evidence_fixture_sha256: "6175466b15bb045d2fe44570b8ae72dc800c3f85f71aaccfb36deb21d534528a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9B68023167CF",
        baseline_overload_id: "COMFY-TENSOR-OP-9B68023167CF:blocked",
        baseline_fixture_sha256: "f4f426e3a561a06c1e389efb8baa57f12f31e85f1fec1cf2a803f43c316d600b",
        overload_id: "zed.native.tensor.empty-like.canonical-allocation.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"dtype","kind":"keyword_only","type":"optional<DType>","default":null,"keyword_only":true},{"name":"device","kind":"keyword_only","type":"optional<DeviceId>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn empty_like_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dtype: Option<DType>, device: Option<DeviceId>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "allocates fresh writable storage",
        alias_rule: "delegates TensorDescriptor preserving-format derivation and TensorBackend allocation",
        shape_rule: "preserves input shape",
        dtype_rule: "preserves input dtype unless explicitly overridden",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves non-overlapping format and canonicalizes overlapping format",
        device_rule: "exact CPU native allocation in this implementation",
        numeric_rule: "element values are intentionally unspecified",
        tolerance: "not applicable",
        determinism: "descriptor and allocation identity are deterministic; values are not observable by contract",
        cancellation_points: "backend allocation checkpoints",
        vjp_rule: "allocation is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/empty_like.json",
        evidence_fixture_sha256: "65deefc73f7a6c4c347ec18be6aa503798cb8fec19f0f5878e48d9792e52b5a8",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-97058675DD67",
        baseline_overload_id: "COMFY-TENSOR-OP-97058675DD67:blocked",
        baseline_fixture_sha256: "b1b873d1c79d33ded431c0be6872917530a54313c77c1005d00a89d5a430c588",
        overload_id: "zed.native.device.mlu.available.topology-projection.v1",
        ordered_parameters_json: r#"[{"name":"topology","kind":"positional_or_keyword","type":"MemoryTopology","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["bool"]"#,
        rust_signature: "fn mlu_is_available_exact_native(topology: &MemoryTopology, context: &ExecutionContext<'_>) -> Result<bool, NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "delegates canonical worker MemoryTopology device count",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "u32 checked count",
        layout_rule: "not applicable",
        device_rule: "MLU topology entries",
        numeric_rule: "true exactly when at least one MLU device is present",
        tolerance: "exact",
        determinism: "topology projection",
        cancellation_points: "before and after count",
        vjp_rule: "device query is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/mlu_available.json",
        evidence_fixture_sha256: "df49431b6cb552370f728a273ae6ba749b947a0a7092b9feed41ad06f20e3775",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-8F0ACDA02879",
        baseline_overload_id: "COMFY-TENSOR-OP-8F0ACDA02879:blocked",
        baseline_fixture_sha256: "3e33788fd628bdafa6f6d8ef03d23af48123c797ee02707dee41f341f6ecf9eb",
        overload_id: "zed.native.device.mlu.memory-info.accounting-projection.v1",
        ordered_parameters_json: r#"[{"name":"capabilities","kind":"positional_or_keyword","type":"BackendCapabilityMatrix<Mlu>","default":null,"keyword_only":false},{"name":"topology","kind":"positional_or_keyword","type":"MemoryTopology","default":null,"keyword_only":false},{"name":"snapshot","kind":"positional_or_keyword","type":"MemoryAccountingSnapshot","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["tuple<u64,u64>"]"#,
        rust_signature: "fn mlu_mem_get_info_exact_native(capabilities: &BackendCapabilityMatrix, topology: &MemoryTopology, snapshot: &MemoryAccountingSnapshot, context: &ExecutionContext<'_>) -> Result<(u64, u64), NativeMemoryStatsError>",
        mutation_rule: "read only",
        alias_rule: "projects worker-owned topology and accounting snapshot",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "u64 checked accounting",
        layout_rule: "not applicable",
        device_rule: "matching MLU capability, topology and snapshot device",
        numeric_rule: "free equals capacity minus active bytes; total equals topology capacity",
        tolerance: "exact bytes",
        determinism: "canonical accounting projection",
        cancellation_points: "before and after projection",
        vjp_rule: "memory diagnostics are non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/mlu_mem_get_info.json",
        evidence_fixture_sha256: "845a77b0331462ddce573e8aa825d599d891b719b9b5de9364c94ad1e74beb9c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-8F6CC1A0A7AC",
        baseline_overload_id: "COMFY-TENSOR-OP-8F6CC1A0A7AC:blocked",
        baseline_fixture_sha256: "67c9b4910694090615ba2ec12ec8ab2e7d65ec8c4684c4dc7a0476e1788ee34d",
        overload_id: "zed.native.tensor.quantile.linear-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"quantile","kind":"positional_or_keyword","type":"f32[0,1]","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"optional<i64>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn quantile_with_context_exact_native(backend: &CpuBackend, input: &Tensor, quantile: f32, dimension: Option<i64>, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output storage",
        shape_rule: "flattened scalar or selected-axis reduction with checked negative axes",
        dtype_rule: "F32",
        accumulation_dtype: "F32 linear interpolation",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "stable ascending selection with linear interpolation and NaN propagation",
        tolerance: "absolute 0.00001",
        determinism: "stable original-index tie ordering",
        cancellation_points: "group collection, selection and upload",
        vjp_rule: "scatter interpolation weights to selected ranks",
        jvp_rule: "interpolate selected input tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/quantile.json",
        evidence_fixture_sha256: "f882f9599cdba757a0f2c230636e9c1d6f922cbf99ad0d8570e25efea9fad05b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-9BE377B59853",
        baseline_overload_id: "COMFY-TENSOR-OP-9BE377B59853:blocked",
        baseline_fixture_sha256: "67ac615b8f62f459612a289288df6b53e94e6e931f71d1120d1800df38238859",
        overload_id: "zed.native.tensor.softmax.functional-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32>","default":null,"keyword_only":false},{"name":"dimension","kind":"keyword_only","type":"i64","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn softmax_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical activation functional softmax and returns fresh storage",
        shape_rule: "preserves shape with checked signed axis",
        dtype_rule: "F32",
        accumulation_dtype: "F32 max-subtracted exponential sum",
        layout_rule: "logical input traversal and contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "max-subtracted normalized exponential",
        tolerance: "absolute 0.00001",
        determinism: "canonical functional traversal",
        cancellation_points: "functional row and upload checkpoints",
        vjp_rule: "canonical softmax Jacobian-vector product",
        jvp_rule: "canonical softmax Jacobian-vector product",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/softmax.json",
        evidence_fixture_sha256: "335991d81c08d3c6c68a39385213daa597888d06eeca122a4958b94a4d9757bb",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_13",
        operation_id: "COMFY-TENSOR-OP-999B3107D90B",
        baseline_overload_id: "COMFY-TENSOR-OP-999B3107D90B:blocked",
        baseline_fixture_sha256: "5a613f2c07ea7ed6606066dd35555bb96e68052a97df7841c8a39673b903b6e9",
        overload_id: "zed.native.runtime.deterministic-algorithms.explicit-policy.v1",
        ordered_parameters_json: r#"[{"name":"enabled","kind":"positional_or_keyword","type":"bool","default":null,"keyword_only":false},{"name":"warn_only","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["DeterministicAlgorithmsPolicy"]"#,
        rust_signature: "fn use_deterministic_algorithms_exact_native(enabled: bool, warn_only: bool, cancellation: &CancellationToken) -> Result<DeterministicAlgorithmsPolicy, ElementwiseRuntimePartThirteenError>",
        mutation_rule: "constructs an immutable execution policy; no global mutable state",
        alias_rule: "policy evaluates canonical BackendCapabilityMatrix determinism",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "backend-independent policy with matrix evaluation",
        numeric_rule: "allowed, warn or reject according to enabled/warn-only and deterministic capability membership",
        tolerance: "exact",
        determinism: "explicit immutable policy",
        cancellation_points: "before policy construction",
        vjp_rule: "runtime policy is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-8f0acda02879",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_13/deterministic_algorithms.json",
        evidence_fixture_sha256: "93a45d71d0a1221f51ebcab50f55e91103591c5965d80d13a06eff68bd1a40c8",
    },
]
