&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-5A1598AB1BFB",
        baseline_overload_id: "COMFY-TENSOR-OP-5A1598AB1BFB:blocked",
        baseline_fixture_sha256: "ab197ba4e910b2afb413c331bb8998fed5cf47e36d1557ab0f7d6ddf5233dacd",
        overload_id: "zed.native.tensor.expm1.method.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn expm1_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to canonical expm1",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output on observed paths",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE expm1 with small-value precision",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical owner checkpoints",
        vjp_rule: "upstream multiplied by exp(input)",
        jvp_rule: "input tangent multiplied by exp(input)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/expm1_method.json",
        evidence_fixture_sha256: "6c19c82ede2bd80c3b6e0e67e6d6079f8e46d208385af9b4f5b9b15b5977bd1a",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-5668EBF27561",
        baseline_overload_id: "COMFY-TENSOR-OP-5668EBF27561:blocked",
        baseline_fixture_sha256: "17d59dd7746b80f2233511a1f2af827b3490e4690d3af0223f1459800a214533",
        overload_id: "zed.native.tensor.addcdiv.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"tensor1","type":"Tensor<F32>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"tensor2","type":"Tensor<F32>"},{"default":1.0,"keyword_only":false,"kind":"positional_or_keyword","name":"value","type":"f32"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn addcdiv_with_context_exact_native(backend: &CpuBackend, input: &Tensor, tensor1: &Tensor, tensor2: &Tensor, value: f32, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "right-aligned three-input broadcasting",
        dtype_rule: "co-located F32 tensors",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "input plus value times tensor1 divided by tensor2",
        tolerance: "one ULP",
        determinism: "fixed broadcast traversal",
        cancellation_points: "before validation and at bounded broadcast intervals",
        vjp_rule: "analytical gradients reduced across broadcast dimensions",
        jvp_rule: "analytical product and quotient tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/addcdiv.json",
        evidence_fixture_sha256: "ff7a888ef72f0b03be3bbddf36d2b992f7451c512bd627090fdaa79a0f905466",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-59C70700F28E",
        baseline_overload_id: "COMFY-TENSOR-OP-59C70700F28E:blocked",
        baseline_fixture_sha256: "c6b7cb97318d0a6ee1cb851095461ad0a609b51068306dc3fa3005898033dde9",
        overload_id: "zed.native.tensor.argwhere.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<canonical dtype>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<I64>"]"#,
        rust_signature: "fn argwhere_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh coordinate storage",
        shape_rule: "nonzero count by input rank",
        dtype_rule: "all canonical input dtypes and I64 coordinates",
        accumulation_dtype: "I64 checked coordinates",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "zero is false and every nonzero component is true",
        tolerance: "exact coordinates",
        determinism: "row-major source order",
        cancellation_points: "bounded scan and publication intervals",
        vjp_rule: "non-differentiable index result",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/argwhere.json",
        evidence_fixture_sha256: "3702eda5b89d69ebffa686cef9cb70cb18881d968f0e898a256eede9affd5e5f",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-56E8CFEB8E84",
        baseline_overload_id: "COMFY-TENSOR-OP-56E8CFEB8E84:blocked",
        baseline_fixture_sha256: "af2f8301471d190470bd64786df1a2224130db3b95453943fb57058dc7f5975a",
        overload_id: "zed.native.tensor.log1p.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn log1p_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "canonical unary owner allocates fresh storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE log1p including signed zero and domain NaN",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical owner checkpoints",
        vjp_rule: "upstream divided by one plus input",
        jvp_rule: "input tangent divided by one plus input",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/log1p.json",
        evidence_fixture_sha256: "8fe0cf19e727de4d95b304c63d34576589c1998e1dccbacfa6beadad9f7e8812",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-58AE3CA27BFE",
        baseline_overload_id: "COMFY-TENSOR-OP-58AE3CA27BFE:blocked",
        baseline_fixture_sha256: "c1733330830f6de0cd6c383ce6567700ed0102d375d4de3dce1a21fec18fd6aa",
        overload_id: "zed.native.model.weight-norm.register.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"module","type":"mutable NativeModule"},{"default":"weight","keyword_only":false,"kind":"positional_or_keyword","name":"name","type":"str"},{"default":0,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"Option<usize>"}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeModule reference"]"#,
        rust_signature: "fn weight_norm_exact_native<'a>(module: &'a mut NativeModule, name: &str, dimension: Option<usize>, cancellation: &CancellationToken) -> Result<&'a mut NativeModule, NativeOpsError>",
        mutation_rule: "NativeModule atomically registers parameter lifecycle metadata",
        alias_rule: "returns the same module reference",
        shape_rule: "dimension must be inside canonical weight rank",
        dtype_rule: "parameter dtype is established by later native loading",
        accumulation_dtype: "canonical weight materialization owner",
        layout_rule: "module parameter layout",
        device_rule: "module parameter device",
        numeric_rule: "later magnitude and direction loading uses canonical NativeModule materialization",
        tolerance: "exact lifecycle state",
        determinism: "generation-monotonic registration",
        cancellation_points: "before validation and before generation publication",
        vjp_rule: "module parametrization delegates tensor gradients to native weight materialization",
        jvp_rule: "module parametrization delegates tangents to native weight materialization",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/weight_norm.json",
        evidence_fixture_sha256: "96f347f1301755463acb15d95ebf4042c1fa464bde4dec3fe63b35ebb55c9936",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-594BD684E5EF",
        baseline_overload_id: "COMFY-TENSOR-OP-594BD684E5EF:blocked",
        baseline_fixture_sha256: "c8cddc1ecb8961770bba8e865cc78d508c4cae379e3a7db2fa54a677e66ca3b8",
        overload_id: "zed.native.optim.sgd.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"parameter_count","type":"usize"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"learning_rate","type":"f32"},{"default":0.0,"keyword_only":false,"kind":"positional_or_keyword","name":"momentum","type":"f32"},{"default":0.0,"keyword_only":false,"kind":"positional_or_keyword","name":"dampening","type":"f32"},{"default":0.0,"keyword_only":false,"kind":"positional_or_keyword","name":"weight_decay","type":"f32"},{"default":false,"keyword_only":false,"kind":"positional_or_keyword","name":"nesterov","type":"bool"},{"default":false,"keyword_only":false,"kind":"positional_or_keyword","name":"maximize","type":"bool"}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeSgd"]"#,
        rust_signature: "fn NativeSgd::new_exact_native(parameter_count: usize, learning_rate: f32, momentum: f32, dampening: f32, weight_decay: f32, nesterov: bool, maximize: bool, cancellation: &CancellationToken) -> Result<NativeSgd, ElementwiseRuntimePartSevenError>",
        mutation_rule: "step stages every parameter and momentum buffer before one publication",
        alias_rule: "Tensor copy-on-write retains canonical storage ownership",
        shape_rule: "parallel parameter, gradient, and state lists match",
        dtype_rule: "observed training path uses F32",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous staged tensors",
        device_rule: "CPU ordinal zero",
        numeric_rule: "PyTorch SGD momentum, dampening, decay, nesterov, and maximize rules",
        tolerance: "one ULP",
        determinism: "parameter and element order",
        cancellation_points: "before each parameter, bounded elements, and before atomic publication",
        vjp_rule: "optimizer update is a terminal state transition",
        jvp_rule: "optimizer update does not propagate tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/sgd.json",
        evidence_fixture_sha256: "23b830e4a083b3c0a207d250a582911410fb4dc6277e6c2db31ea5801aef2329",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-59EBFDE56C4F",
        baseline_overload_id: "COMFY-TENSOR-OP-59EBFDE56C4F:blocked",
        baseline_fixture_sha256: "98ad77a7c3b8aa8dd759cb4f316a48907df0969b0b99c1b78b20506b330a63d3",
        overload_id: "zed.native.tensor.outer.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32, rank 1>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"Tensor<F32, rank 1>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32, rank 2>"]"#,
        rust_signature: "fn outer_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "left length by right length",
        dtype_rule: "co-located F32 vectors",
        accumulation_dtype: "F32",
        layout_rule: "canonical row-major output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "pairwise vector products",
        tolerance: "exact fixture values",
        determinism: "left-major traversal",
        cancellation_points: "bounded pair intervals",
        vjp_rule: "matrix-vector reductions for both inputs",
        jvp_rule: "outer(input tangent, other) plus outer(input, other tangent)",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/outer.json",
        evidence_fixture_sha256: "d03a147999f932cf14555180bbff758f65b54de27c61382d3c8b9a4f61e0f96c",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-54E28780B32B",
        baseline_overload_id: "COMFY-TENSOR-OP-54E28780B32B:blocked",
        baseline_fixture_sha256: "25500ba4c1f19099c05129159ec2837319aad0c1112564569e8594aa42b307d8",
        overload_id: "zed.native.tensor.rsqrt.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn rsqrt_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "canonical unary owner allocates fresh storage",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "reciprocal of IEEE square root",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical owner checkpoints",
        vjp_rule: "negative one half upstream divided by input to the three halves",
        jvp_rule: "same derivative applied to tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/rsqrt.json",
        evidence_fixture_sha256: "be7e7784dfdabd9917729feaa0b621a2cc1eaddb6717438d4ea7e504e8df0960",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-5547BE508AEE",
        baseline_overload_id: "COMFY-TENSOR-OP-5547BE508AEE:blocked",
        baseline_fixture_sha256: "0458f0a4b90c5d6b248972e3a0f421fc8222d36802c7a99f80b944aea2c9cbac",
        overload_id: "zed.native.tensor.print-options.explicit.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"current","type":"TensorPrintOptions"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"update","type":"Option<TensorPrintOptionsUpdate>"}]"#,
        output_arity: "1",
        output_types_json: r#"["TensorPrintOptions"]"#,
        rust_signature: "fn set_printoptions_exact_native(current: &TensorPrintOptions, update: Option<TensorPrintOptionsUpdate>, cancellation: &CancellationToken) -> Result<TensorPrintOptions, ElementwiseRuntimePartSevenError>",
        mutation_rule: "returns explicit validated options without global state",
        alias_rule: "value object",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "device independent",
        numeric_rule: "bounded precision, threshold, edge items, line width, and scientific mode",
        tolerance: "exact fields",
        determinism: "pure value mapping",
        cancellation_points: "before and after validation",
        vjp_rule: "presentation state is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/set_printoptions.json",
        evidence_fixture_sha256: "75650ad45f2d407ff6fca74472c7aeb00463582312566a1ea18a99c48838c35b",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-59AD8FFF431A",
        baseline_overload_id: "COMFY-TENSOR-OP-59AD8FFF431A:blocked",
        baseline_fixture_sha256: "b3a9300315c35b18b8df0a30b615940a7b51ca02a6790ee78e073d9c5cdeeca6",
        overload_id: "zed.native.tensor.tanh.function.cpu-f32.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"Tensor<F32>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32>"]"#,
        rust_signature: "fn tanh_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartSevenError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to canonical tanh",
        shape_rule: "preserves shape",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU ordinal zero",
        numeric_rule: "IEEE hyperbolic tangent",
        tolerance: "one ULP",
        determinism: "canonical unary traversal",
        cancellation_points: "canonical owner checkpoints",
        vjp_rule: "upstream times one minus output squared",
        jvp_rule: "input tangent times one minus output squared",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/tanh.json",
        evidence_fixture_sha256: "a0cbeb8c0113151bc53c5092777befae57bcfd38b8c89ac9bd1095d680ec15dd",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_07",
        operation_id: "COMFY-TENSOR-OP-576587FE2EAF",
        baseline_overload_id: "COMFY-TENSOR-OP-576587FE2EAF:blocked",
        baseline_fixture_sha256: "46f05e253257f9f47d96923394da36e84280d529535e6b200b02eaad0e35833d",
        overload_id: "zed.native.xpu.current-stream.explicit.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"capabilities","type":"BackendCapabilityMatrix"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"device","type":"DeviceId<Xpu>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"execution","type":"ExecutionContext"}]"#,
        output_arity: "1",
        output_types_json: r#"["StreamId"]"#,
        rust_signature: "fn xpu_current_stream_exact_native(capabilities: &BackendCapabilityMatrix, device: DeviceId, execution: &ExecutionContext<'_>) -> Result<StreamId, ElementwiseRuntimePartSevenError>",
        mutation_rule: "read-only explicit projection",
        alias_rule: "copy value",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "none",
        layout_rule: "not applicable",
        device_rule: "exact XPU device must match canonical capability matrix",
        numeric_rule: "returns the canonical operation execution context stream",
        tolerance: "exact identity",
        determinism: "pure projection",
        cancellation_points: "the canonical execution context token is checked before and after validation",
        vjp_rule: "runtime stream identity is non-differentiable",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-54e28780b32b",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_07/xpu_current_stream.json",
        evidence_fixture_sha256: "00bbd74ff842b15771476a64977a24516a192f439db8b2e2e540be3389a849cf",
    },
]
