&[
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_23",
        operation_id: "COMFY-TENSOR-OP-FEFD7C671451",
        baseline_overload_id: "COMFY-TENSOR-OP-FEFD7C671451:blocked",
        baseline_fixture_sha256: "93cab85e9136722291e7bb9217751bd3eba6d35e39e6cabdf75271dcdb56c3cc",
        overload_id: "sim.native.tensor.cartesian-prod.generic-bytes.v1",
        ordered_parameters_json: r#"[{"name":"inputs","kind":"variadic_positional","type":"&[Tensor<same dtype>]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<input dtype>"]"#,
        rust_signature: "fn cartesian_prod_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], context: &ExecutionContext<'_>) -> Result<Tensor, ElementwiseRuntimePartTwentyThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh backend-owned storage; no input aliases",
        shape_rule: "one input preserves its vector shape; two or more inputs produce [product(lengths), input_count]; zero-length inputs produce zero rows",
        dtype_rule: "all inputs have one identical canonical dtype, preserved exactly",
        accumulation_dtype: "not applicable",
        layout_rule: "logical rank-one input traversal and contiguous output",
        device_rule: "co-located CPU ordinal zero and one source stream",
        numeric_rule: "itertools.product order with the last input varying fastest and byte-exact scalar copying",
        tolerance: "bit exact",
        determinism: "checked fixed mixed-radix row order",
        cancellation_points: "before validation, at bounded input and row boundaries, and before publication",
        vjp_rule: "forward-only for the cataloged I64 position-grid call; integral inputs have no gradient",
        jvp_rule: "forward-only for the cataloged I64 position-grid call; integral inputs have no tangent",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-fcda841034ed",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_23/cartesian_prod.json",
        evidence_fixture_sha256: "489c3f4b16c26bdec57a731d92548162e47a9ef609d6e66df78ba2973d13d9a1",
    },
    ResolvedOperationContract {
        resolution_module: "elementwise_or_runtime_operation_23",
        operation_id: "COMFY-TENSOR-OP-FCDA841034ED",
        baseline_overload_id: "COMFY-TENSOR-OP-FCDA841034ED:blocked",
        baseline_fixture_sha256: "0d9f25bcfb5927e85e6666cfb5c9accf3c6a79fc3b85d5f11988a59ba60b999c",
        overload_id: "sim.native.optimizer.rmsprop.transactional-f32.v1",
        ordered_parameters_json: r#"[{"name":"backend","kind":"positional_or_keyword","type":"&CpuBackend","default":null,"keyword_only":false},{"name":"parameters","kind":"positional_or_keyword","type":"&[Tensor<F32>]","default":null,"keyword_only":false},{"name":"learning_rate","kind":"keyword_only","type":"f32","default":0.01,"keyword_only":true},{"name":"alpha","kind":"keyword_only","type":"f32","default":0.99,"keyword_only":true},{"name":"epsilon","kind":"keyword_only","type":"f32","default":1e-8,"keyword_only":true},{"name":"weight_decay","kind":"keyword_only","type":"f32","default":0.0,"keyword_only":true},{"name":"momentum","kind":"keyword_only","type":"f32","default":0.0,"keyword_only":true},{"name":"centered","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"maximize","kind":"keyword_only","type":"bool","default":false,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeRmsprop"]"#,
        rust_signature: "fn NativeRmsprop::new_with_context_exact_native(backend: &CpuBackend, parameters: &[Tensor], learning_rate: f32, alpha: f32, epsilon: f32, weight_decay: f32, momentum: f32, centered: bool, maximize: bool, context: &ExecutionContext<'_>) -> Result<NativeRmsprop, ElementwiseRuntimePartTwentyThreeError>",
        mutation_rule: "stateful optimizer with all-parameter transactional step publication",
        alias_rule: "owns checked step counters and dedicated square-average, optional momentum, and optional gradient-average tensors; parameter handles are caller-owned",
        shape_rule: "one state tensor per parameter with identical logical shape",
        dtype_rule: "certified native CPU F32 parameters, gradients, and state",
        accumulation_dtype: "F32 in fixed element order",
        layout_rule: "logical parameter reads and contiguous state/update publication",
        device_rule: "CPU ordinal zero with exact per-parameter stream preservation",
        numeric_rule: "PyTorch RMSprop order: weight decay on gradient, exponential square average, optional centered variance, square root before epsilon, optional momentum, then learning-rate update",
        tolerance: "1e-5 absolute for finite F32 fixtures; IEEE NaN/Inf propagation",
        determinism: "fixed parameter and logical-element traversal",
        cancellation_points: "before construction, at parameter and element staging boundaries, before every backend upload, and once before the single publication phase",
        vjp_rule: "optimizer consumes caller-provided gradients and does not record a reverse-mode node",
        jvp_rule: "optimizer state transitions do not propagate tangents",
        owner_task_id: "comfy-parity-tensor-ops-elementwise-or-runtime-operation-comfy-tensor-op-fcda841034ed",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/elementwise_or_runtime_operation_23/rmsprop.json",
        evidence_fixture_sha256: "4c13b26a0051e0a9e4faee5510d97e33f2b54a92844c174b875fcaea395ed9a4",
    },
]
