&[
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_03",
        operation_id: "COMFY-TENSOR-OP-F37B4E403ACF",
        baseline_overload_id: "COMFY-TENSOR-OP-F37B4E403ACF:blocked",
        baseline_fixture_sha256: "72f5f1d568debdd98e4321bc1cb3e321e1a5cf3d344e408770c1a5d26313a3df",
        overload_id: "zed.native.kornia.lab-to-rgb-0.8.2-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,...C...>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...C...>"]"#,
        rust_signature: "fn lab_to_rgb_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output delegated to the sole canonical color traversal",
        shape_rule: "preserves rank and shape and requires exactly three channels at the third-from-final axis",
        dtype_rule: "CPU F32 input and output",
        accumulation_dtype: "F32 CIE Lab inverse, XYZ matrix, and piecewise sRGB transfer",
        layout_rule: "logical strided color reads and contiguous output in the input logical shape",
        device_rule: "CPU ordinal zero on the input stream; other native devices fail typed",
        numeric_rule: "Kornia 0.8.2 D65 CIE-Lab-to-sRGB inverse with clip=true",
        tolerance: "3e-5 absolute for finite F32 values",
        determinism: "fixed canonical pixel and channel traversal with fixed matrix order",
        cancellation_points: "before validation, at bounded pixel intervals, and before publication",
        vjp_rule: "analytical transpose of the clipped piecewise Lab-to-RGB Jacobian",
        jvp_rule: "analytical clipped piecewise Lab-to-RGB Jacobian applied to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-c5a306eb73fd",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_03/lab_to_rgb.json",
        evidence_fixture_sha256: "f4636614130b469159116c643375b5f89a9c4ba6c97b086ea5af490aac7e713d",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_03",
        operation_id: "COMFY-TENSOR-OP-C5A306EB73FD",
        baseline_overload_id: "COMFY-TENSOR-OP-C5A306EB73FD:blocked",
        baseline_fixture_sha256: "f737dd317d89a9a8130e3cb53091894a25ab2c0277b6ef64afb232d4065082e0",
        overload_id: "zed.native.kornia.morphology-bottom-hat-0.8.2-flat-geodesic.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,BCHW>","default":null,"keyword_only":false},{"name":"kernel","kind":"positional_or_keyword","type":"Tensor<F32,HW>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,BCHW>"]"#,
        rust_signature: "fn bottom_hat_with_context_exact_native(backend: &CpuBackend, input: &Tensor, kernel: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output delegated to the sole canonical morphology engine",
        shape_rule: "preserves BCHW shape for every nonempty rank-two flat kernel",
        dtype_rule: "CPU F32 input, kernel, and output",
        accumulation_dtype: "F32 comparisons and subtraction",
        layout_rule: "logical BCHW reads and contiguous BCHW output",
        device_rule: "CPU ordinal zero on one stream; other native devices fail typed",
        numeric_rule: "Kornia 0.8.2 closing minus input with flipped dilation mask and finite geodesic sentinels",
        tolerance: "bit exact for finite fixtures",
        determinism: "fixed canonical morphology traversal",
        cancellation_points: "before validation, within delegated stages, and before publication",
        vjp_rule: "forward-only at the cataloged morphology UI node",
        jvp_rule: "forward-only at the cataloged morphology UI node",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-c5a306eb73fd",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_03/bottom_hat.json",
        evidence_fixture_sha256: "e5e32ac0a1b21a8161aed4d71b2ba86b06e8019d0572c7e6fec0abe14ba82fd7",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_03",
        operation_id: "COMFY-TENSOR-OP-F73C7107B450",
        baseline_overload_id: "COMFY-TENSOR-OP-F73C7107B450:blocked",
        baseline_fixture_sha256: "76e3a952bdafc96470881939b63e0999eae9e21da8b19b8dfc5ac078cc3be8d2",
        overload_id: "zed.native.torchaudio.bass-biquad-2.10.0-f32.v1",
        ordered_parameters_json: r#"[{"name":"waveform","kind":"positional_or_keyword","type":"Tensor<F32,...T>","default":null,"keyword_only":false},{"name":"sample_rate","kind":"positional_or_keyword","type":"u32","default":null,"keyword_only":false},{"name":"gain","kind":"positional_or_keyword","type":"f64","default":null,"keyword_only":false},{"name":"central_frequency","kind":"positional_or_keyword","type":"f64","default":100.0,"keyword_only":false},{"name":"quality","kind":"positional_or_keyword","type":"f64","default":0.707,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...T>"]"#,
        rust_signature: "fn bass_biquad_with_context_exact_native(backend: &CpuBackend, waveform: &Tensor, sample_rate: u32, gain: f64, central_frequency: f64, quality: f64, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output; adapter owns coefficients only and delegates recurrence",
        shape_rule: "preserves every nonempty waveform shape with time on the final axis",
        dtype_rule: "CPU F32 waveform and output",
        accumulation_dtype: "F64 coefficient construction and canonical F64 recurrence with F32 publication",
        layout_rule: "logical channel-major traversal over the final time axis",
        device_rule: "CPU ordinal zero on the input stream; other native devices fail typed",
        numeric_rule: "TorchAudio 2.10.0 RBJ low-shelf coefficients with clamped canonical biquad output",
        tolerance: "1e-6 absolute for finite F32 fixtures",
        determinism: "fixed coefficient and recurrence ordering",
        cancellation_points: "before parameter validation, within delegated samples, and before publication",
        vjp_rule: "forward-only at the cataloged audio equalizer UI node",
        jvp_rule: "forward-only at the cataloged audio equalizer UI node",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-c5a306eb73fd",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_03/bass_biquad.json",
        evidence_fixture_sha256: "198cdd3047088ec65eafb6b6aa684708ec81fc84ddc1e15cf616027ef2596695",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_03",
        operation_id: "COMFY-TENSOR-OP-EBA0D3470A35",
        baseline_overload_id: "COMFY-TENSOR-OP-EBA0D3470A35:blocked",
        baseline_fixture_sha256: "5ce20b4da9e3302dba8ce59465164d41aff4300c9aaa98a14236335cf51d01cb",
        overload_id: "zed.native.torchaudio.mel-scale-2.10.0-slaney-f32.v1",
        ordered_parameters_json: r#"[{"name":"spectrogram","kind":"positional_or_keyword","type":"Tensor<F32,...FT>","default":null,"keyword_only":false},{"name":"configuration","kind":"positional_or_keyword","type":"NativeMelScaleConfiguration","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...MT>"]"#,
        rust_signature: "fn mel_scale_with_context_exact_native(backend: &CpuBackend, spectrogram: &Tensor, configuration: NativeMelScaleConfiguration, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output delegated to the sole canonical mel filter-bank projection",
        shape_rule: "preserves leading and frame axes and replaces the penultimate n_stft axis with n_mels",
        dtype_rule: "CPU F32 input and output",
        accumulation_dtype: "F32 fixed-order triangular-filter accumulation",
        layout_rule: "logical strided input and contiguous output in leading, mel, frame order",
        device_rule: "CPU ordinal zero on the input stream; other native devices fail typed",
        numeric_rule: "TorchAudio 2.10.0 Slaney or HTK triangular banks with optional Slaney area normalization",
        tolerance: "1e-6 absolute for the finite source fixture",
        determinism: "fixed leading, mel, frame, and frequency traversal",
        cancellation_points: "before configuration validation, at bounded frame intervals, and before publication",
        vjp_rule: "transpose of the same immutable mel filter bank",
        jvp_rule: "the same mel projection applied to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-c5a306eb73fd",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_03/mel_scale.json",
        evidence_fixture_sha256: "fda3dba755393b4ca3bce2adc3c0366e0a984f1dd9146130f0d491c87832f321",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_03",
        operation_id: "COMFY-TENSOR-OP-E937CE70AC37",
        baseline_overload_id: "COMFY-TENSOR-OP-E937CE70AC37:blocked",
        baseline_fixture_sha256: "7995490f3a56d4009f3292cde44bb623d6381f3ee7f45445dda395394746dae8",
        overload_id: "zed.native.torchvision.box-convert-0.27-cxcywh-xyxy-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,...4>","default":null,"keyword_only":false},{"name":"input_format","kind":"positional_or_keyword","type":"NativeBoxFormat","default":null,"keyword_only":false},{"name":"output_format","kind":"positional_or_keyword","type":"NativeBoxFormat","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...4>"]"#,
        rust_signature: "fn box_convert_with_context_exact_native(backend: &CpuBackend, input: &Tensor, input_format: NativeBoxFormat, output_format: NativeBoxFormat, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output including identity and empty conversions",
        shape_rule: "preserves any rank-one-or-greater shape ending in four coordinates",
        dtype_rule: "CPU F32 input and output at the observed RT-DETR call site",
        accumulation_dtype: "F32 coordinate arithmetic",
        layout_rule: "logical strided box reads and contiguous output",
        device_rule: "CPU ordinal zero on the input stream; other native devices fail typed",
        numeric_rule: "Torchvision 0.27 cxcywh and xyxy equations with explicit half-width and half-height ordering",
        tolerance: "bit exact for the finite source fixture",
        determinism: "fixed logical box and coordinate traversal",
        cancellation_points: "before validation, at bounded box intervals, and before publication",
        vjp_rule: "analytical transpose of the selected linear coordinate map",
        jvp_rule: "the selected linear coordinate map applied to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-c5a306eb73fd",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_03/box_convert.json",
        evidence_fixture_sha256: "b543ac0a35000ab8dc588371734d30515981fd6f9976ec7557f7386032a1e7e3",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_03",
        operation_id: "COMFY-TENSOR-OP-FBC26239461B",
        baseline_overload_id: "COMFY-TENSOR-OP-FBC26239461B:blocked",
        baseline_fixture_sha256: "1d70af2e6ef03c67681c16940ab0c6292628389a71881b72b3ba1f2bdf9a1d8f",
        overload_id: "zed.native.torchvision.compose-normalize-0.27-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,...CHW>","default":null,"keyword_only":false},{"name":"transforms","kind":"positional_or_keyword","type":"&[NativeTensorTransform]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...CHW>"]"#,
        rust_signature: "fn compose_with_context_exact_native(backend: &CpuBackend, input: &Tensor, transforms: &[NativeTensorTransform], context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartThreeError>",
        mutation_rule: "out of place unless the transform list is empty",
        alias_rule: "empty composition returns the input alias; observed normalization produces canonical fresh output",
        shape_rule: "each typed transform must preserve the canonical tensor shape",
        dtype_rule: "observed Normalize path requires CPU F32 input and output",
        accumulation_dtype: "delegated to the canonical normalization owner",
        layout_rule: "ordered immutable transform recipe with no adapter-owned storage",
        device_rule: "delegated transform device rules; no external runtime fallback",
        numeric_rule: "Torchvision 0.27 ordered Compose containing the observed Normalize mean 0.5 and standard deviation 0.5",
        tolerance: "bit exact for the finite source fixture",
        determinism: "declared transform order with canonical per-transform traversal",
        cancellation_points: "before recipe traversal, between transforms, and before return",
        vjp_rule: "reverse ordered canonical transform VJPs; observed source call is no-grad",
        jvp_rule: "forward ordered canonical transform JVPs; observed source call is no-grad",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-c5a306eb73fd",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_03/compose.json",
        evidence_fixture_sha256: "a2cd72cbc7d3447bff8fa6a9cc07065106d08206b8d9706155ca93a349b82b1b",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_03",
        operation_id: "COMFY-TENSOR-OP-D2AF4145E6CE",
        baseline_overload_id: "COMFY-TENSOR-OP-D2AF4145E6CE:blocked",
        baseline_fixture_sha256: "971e5252fd53ca5c301a4b94e14a64268794a57b00b54e8b9154f39f55fe65f3",
        overload_id: "zed.native.torchvision.to-tensor-0.27-rgb8-boundary.v1",
        ordered_parameters_json: r#"[{"name":"image","kind":"positional_or_keyword","type":"Rgb8ImageTensor","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,CHW>"]"#,
        rust_signature: "fn to_tensor_with_context_exact_native(backend: &CpuBackend, image: &Rgb8ImageTensor, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartThreeError>",
        mutation_rule: "out of place",
        alias_rule: "fresh F32 output; canonical RGB8 tensor remains immutable",
        shape_rule: "checked HWC RGB8 image becomes CHW with identical height and width",
        dtype_rule: "U8 channels become F32 values divided by 255",
        accumulation_dtype: "F32 channel scaling",
        layout_rule: "delegates the sole canonical HWC-to-CHW traversal and publishes contiguous CHW",
        device_rule: "CPU ordinal zero on the RGB8 tensor stream; other devices are rejected by the image boundary",
        numeric_rule: "Torchvision 0.27 ToTensor RGB byte scaling and channel permutation",
        tolerance: "bit exact F32 division for the source fixture",
        determinism: "fixed canonical channel, row, and column traversal",
        cancellation_points: "before image validation, within delegated rows, and before publication",
        vjp_rule: "non-differentiable U8 image boundary at the cataloged drawing call site",
        jvp_rule: "non-differentiable U8 image boundary at the cataloged drawing call site",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-c5a306eb73fd",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_03/to_tensor.json",
        evidence_fixture_sha256: "1f4ee0f4f656a33e658fb1cadef5310b990d805563085d7d26ce8a438e18696f",
    },
]
