&[
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-41E0A53BDA36",
        baseline_overload_id: "COMFY-TENSOR-OP-41E0A53BDA36:blocked",
        baseline_fixture_sha256: "dfc643525c7b601240459386f27a607400212dca4c2dac91edbec73aa71bd328",
        overload_id: "zed.native.rearrange.checked-plan.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"plan","kind":"positional_or_keyword","type":"NativeRearrangePlan","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<input dtype>"]"#,
        rust_signature: "fn rearrange_with_context_exact_native(backend: &CpuBackend, input: &Tensor, plan: &NativeRearrangePlan, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh contiguous storage; the immutable plan is a one-to-one source permutation",
        shape_rule: "the checked plan preserves element count; the cataloged adapter maps BCTHW patches to BTHW-feature",
        dtype_rule: "preserves every canonical input dtype byte-exactly",
        accumulation_dtype: "not applicable",
        layout_rule: "logical input reads and contiguous output; inverse scatter restores contiguous input layout",
        device_rule: "CPU ordinal zero and the input stream; unsupported native backends fail typed",
        numeric_rule: "C-order einops enumeration using one checked source index per output element",
        tolerance: "bit exact",
        determinism: "immutable plan and fixed output-linear traversal",
        cancellation_points: "before validation, at bounded output-element intervals, and before publication",
        vjp_rule: "inverse one-to-one scatter into the declared input shape",
        jvp_rule: "the same checked gather plan applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/rearrange.json",
        evidence_fixture_sha256: "e9bdf196ffb4dc68db9c0b6c3d693988834be78d0f02e347ccdd62a7dc73ef92",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-338E50E9975A",
        baseline_overload_id: "COMFY-TENSOR-OP-338E50E9975A:blocked",
        baseline_fixture_sha256: "57d35fd0ccb567bd162fae1642edf5e4f162544e728e7ea29f82fe1861a79121",
        overload_id: "zed.native.morphology.closing-flat-geodesic.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,BCHW>","default":null,"keyword_only":false},{"name":"kernel","kind":"positional_or_keyword","type":"Tensor<F32,HW>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,BCHW>"]"#,
        rust_signature: "fn native_morphology_with_context_exact(backend: &CpuBackend, input: &Tensor, kernel: &Tensor, operation: NativeMorphologyOperation::Closing, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output; canonical native_morphology_exact owns validation, both primitive traversals, composition, and atomic publication",
        shape_rule: "preserves BCHW input shape for every non-empty rank-two flat kernel",
        dtype_rule: "CPU F32 input and kernel",
        accumulation_dtype: "F32 comparisons",
        layout_rule: "logical BCHW reads and contiguous BCHW publication",
        device_rule: "CPU ordinal zero; unsupported native backends fail typed",
        numeric_rule: "Kornia 0.8.2 flat closing: dilation flips the full kernel mask and uses -10000 for inactive entries and geodesic padding, then erosion uses the unflipped mask and +10000 finite sentinels; sparse and all-zero masks remain executable",
        tolerance: "bit exact for finite fixtures",
        determinism: "fixed batch-channel-pixel-kernel traversal",
        cancellation_points: "before validation and kernel inspection, at bounded pixel and kernel intervals, between delegated primitives, and before publication; cancellation takes precedence over malformed input",
        vjp_rule: "forward-only at cataloged morphology-node inference call sites",
        jvp_rule: "forward-only at cataloged morphology-node inference call sites",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/closing.json",
        evidence_fixture_sha256: "1b97b0f275ae3c6ac79b9e30bb425f292441b4fb10f621a1a24ebfc465e46d8b",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-165C20AC8DD8",
        baseline_overload_id: "COMFY-TENSOR-OP-165C20AC8DD8:blocked",
        baseline_fixture_sha256: "400b4c07b42ace1d172d889812f6fddeef2a0560191eff8f0e149628134f260f",
        overload_id: "zed.native.morphology.gradient-flat-geodesic.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,BCHW>","default":null,"keyword_only":false},{"name":"kernel","kind":"positional_or_keyword","type":"Tensor<F32,HW>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,BCHW>"]"#,
        rust_signature: "fn native_morphology_with_context_exact(backend: &CpuBackend, input: &Tensor, kernel: &Tensor, operation: NativeMorphologyOperation::Gradient, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output; canonical native_morphology_exact owns validation, both primitive traversals, subtraction, and atomic publication",
        shape_rule: "preserves BCHW input shape for every non-empty rank-two flat kernel",
        dtype_rule: "CPU F32 input and kernel",
        accumulation_dtype: "F32 subtraction after F32 comparisons",
        layout_rule: "logical BCHW reads and contiguous BCHW publication",
        device_rule: "CPU ordinal zero; unsupported native backends fail typed",
        numeric_rule: "Kornia 0.8.2 flat gradient: flipped-mask dilation with -10000 finite sentinels minus unflipped-mask erosion with +10000 finite sentinels; sparse and all-zero masks remain executable",
        tolerance: "bit exact for finite fixtures",
        determinism: "fixed batch-channel-pixel-kernel traversal",
        cancellation_points: "before validation and kernel inspection, at bounded pixel and kernel intervals, between delegated primitives, and before publication; cancellation takes precedence over malformed input",
        vjp_rule: "forward-only at cataloged morphology-node inference call sites",
        jvp_rule: "forward-only at cataloged morphology-node inference call sites",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/gradient.json",
        evidence_fixture_sha256: "4d793c37fd8a46a938ab788e6d161666e19a86a5d7c78bee3f26189ad04fb098",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-363BE404A764",
        baseline_overload_id: "COMFY-TENSOR-OP-363BE404A764:blocked",
        baseline_fixture_sha256: "acda7933997708843c76196406d9a25de8f67ad20c2eee0dc4a4f28c166b163d",
        overload_id: "zed.native.morphology.opening-flat-geodesic.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,BCHW>","default":null,"keyword_only":false},{"name":"kernel","kind":"positional_or_keyword","type":"Tensor<F32,HW>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,BCHW>"]"#,
        rust_signature: "fn native_morphology_with_context_exact(backend: &CpuBackend, input: &Tensor, kernel: &Tensor, operation: NativeMorphologyOperation::Opening, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output; canonical native_morphology_exact owns validation, both primitive traversals, composition, and atomic publication",
        shape_rule: "preserves BCHW input shape for every non-empty rank-two flat kernel",
        dtype_rule: "CPU F32 input and kernel",
        accumulation_dtype: "F32 comparisons",
        layout_rule: "logical BCHW reads and contiguous BCHW publication",
        device_rule: "CPU ordinal zero; unsupported native backends fail typed",
        numeric_rule: "Kornia 0.8.2 flat opening: erosion uses the unflipped full kernel mask and +10000 for inactive entries and geodesic padding, then dilation flips the mask and uses -10000 finite sentinels; sparse and all-zero masks remain executable",
        tolerance: "bit exact for finite fixtures",
        determinism: "fixed batch-channel-pixel-kernel traversal",
        cancellation_points: "before validation and kernel inspection, at bounded pixel and kernel intervals, between delegated primitives, and before publication; cancellation takes precedence over malformed input",
        vjp_rule: "forward-only at cataloged morphology-node inference call sites",
        jvp_rule: "forward-only at cataloged morphology-node inference call sites",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/opening.json",
        evidence_fixture_sha256: "7c185fd9ea6c1205b14546a97001c623fe47cea8066846f8b46215e7db9ca74b",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-0607DAA06439",
        baseline_overload_id: "COMFY-TENSOR-OP-0607DAA06439:blocked",
        baseline_fixture_sha256: "5b3412fc91f88349e0a07413c9487925b7f4201423d27873d54a6372aca0c5a7",
        overload_id: "zed.native.audio.equalizer-biquad-f32.v1",
        ordered_parameters_json: r#"[{"name":"waveform","kind":"positional_or_keyword","type":"Tensor<F32,...T>","default":null,"keyword_only":false},{"name":"sample_rate","kind":"positional_or_keyword","type":"u32","default":null,"keyword_only":false},{"name":"center_frequency","kind":"positional_or_keyword","type":"f64","default":null,"keyword_only":false},{"name":"gain","kind":"positional_or_keyword","type":"f64","default":null,"keyword_only":false},{"name":"quality","kind":"positional_or_keyword","type":"f64","default":0.707,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...T>"]"#,
        rust_signature: "fn equalizer_biquad_with_context_exact_native(backend: &CpuBackend, waveform: &Tensor, sample_rate: u32, center_frequency: f64, gain: f64, quality: f64, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output with no filter-state persistence",
        shape_rule: "preserves every leading waveform dimension and the final time length",
        dtype_rule: "CPU F32 waveform; coefficients are computed in F64 and samples publish F32",
        accumulation_dtype: "F64 recurrence",
        layout_rule: "logical final-axis channel traversal and contiguous output",
        device_rule: "CPU ordinal zero; unsupported native backends fail typed",
        numeric_rule: "torchaudio equalizer coefficient equations and zero-state direct-form recurrence with output clamp",
        tolerance: "1e-5 absolute for finite F32 fixtures",
        determinism: "fixed channel then time recurrence order",
        cancellation_points: "before validation, at bounded sample intervals, and before publication",
        vjp_rule: "forward-only at the cataloged audio-effect inference call site",
        jvp_rule: "forward-only at the cataloged audio-effect inference call site",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/equalizer_biquad.json",
        evidence_fixture_sha256: "bac60fbd1e2cc80cf3997517f94d69f7429732a37d078ded350c7b3480e7c98a",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-0A14AB1C4005",
        baseline_overload_id: "COMFY-TENSOR-OP-0A14AB1C4005:blocked",
        baseline_fixture_sha256: "f917778240793b7cdc49beb0acb9eeae5ea51975092d2582f18341c764150bf5",
        overload_id: "zed.native.audio.resample-sinc-hann-f32.v1",
        ordered_parameters_json: r#"[{"name":"waveform","kind":"positional_or_keyword","type":"Tensor<F32,...T>","default":null,"keyword_only":false},{"name":"original_frequency","kind":"positional_or_keyword","type":"u32","default":null,"keyword_only":false},{"name":"new_frequency","kind":"positional_or_keyword","type":"u32","default":null,"keyword_only":false},{"name":"lowpass_filter_width","kind":"keyword_only","type":"u32","default":6,"keyword_only":true},{"name":"rolloff","kind":"keyword_only","type":"f64","default":0.99,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...T2>"]"#,
        rust_signature: "fn resample_with_context_exact_native(backend: &CpuBackend, waveform: &Tensor, configuration: NativeResampleConfiguration, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output; immutable phase kernels are local to the invocation",
        shape_rule: "preserves leading dimensions and sets final length to ceil(new_frequency * input_length / original_frequency)",
        dtype_rule: "CPU F32 waveform",
        accumulation_dtype: "F64 weighted sum with F32 publication",
        layout_rule: "logical final-axis reads and contiguous output",
        device_rule: "CPU ordinal zero; unsupported native backends fail typed",
        numeric_rule: "torchaudio sinc_interp_hann phase kernels after frequency GCD reduction with zero padding",
        tolerance: "2e-5 absolute for finite F32 fixtures",
        determinism: "fixed channel, output, and phase-kernel traversal",
        cancellation_points: "before validation, at bounded output-sample intervals, and before publication",
        vjp_rule: "transpose accumulation through the exact forward phase weights",
        jvp_rule: "the exact forward resample applied to the waveform tangent",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/resample.json",
        evidence_fixture_sha256: "876095878c5dd94c3797e21f33e28719711ba67b94f6edbe932099b87a5630fd",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-49A168D86220",
        baseline_overload_id: "COMFY-TENSOR-OP-49A168D86220:blocked",
        baseline_fixture_sha256: "2eedb938b507ba29a16a3a1fd4790f6d3558c021a4e4981da0e30e5139d02255",
        overload_id: "zed.native.audio.treble-biquad-f32.v1",
        ordered_parameters_json: r#"[{"name":"waveform","kind":"positional_or_keyword","type":"Tensor<F32,...T>","default":null,"keyword_only":false},{"name":"sample_rate","kind":"positional_or_keyword","type":"u32","default":null,"keyword_only":false},{"name":"gain","kind":"positional_or_keyword","type":"f64","default":null,"keyword_only":false},{"name":"central_frequency","kind":"positional_or_keyword","type":"f64","default":3000.0,"keyword_only":false},{"name":"quality","kind":"positional_or_keyword","type":"f64","default":0.707,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...T>"]"#,
        rust_signature: "fn treble_biquad_with_context_exact_native(backend: &CpuBackend, waveform: &Tensor, sample_rate: u32, gain: f64, central_frequency: f64, quality: f64, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output with no filter-state persistence",
        shape_rule: "preserves every leading waveform dimension and the final time length",
        dtype_rule: "CPU F32 waveform; coefficients are computed in F64 and samples publish F32",
        accumulation_dtype: "F64 recurrence",
        layout_rule: "logical final-axis channel traversal and contiguous output",
        device_rule: "CPU ordinal zero; unsupported native backends fail typed",
        numeric_rule: "torchaudio treble shelving coefficient equations and zero-state direct-form recurrence with output clamp",
        tolerance: "1e-5 absolute for finite F32 fixtures",
        determinism: "fixed channel then time recurrence order",
        cancellation_points: "before validation, at bounded sample intervals, and before publication",
        vjp_rule: "forward-only at the cataloged audio-effect inference call site",
        jvp_rule: "forward-only at the cataloged audio-effect inference call site",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/treble_biquad.json",
        evidence_fixture_sha256: "a2317d3ccec00bd382458a25ddc402fa6b080897c4a7b49588db77072d122c09",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-367BF5D133D8",
        baseline_overload_id: "COMFY-TENSOR-OP-367BF5D133D8:blocked",
        baseline_fixture_sha256: "bf091cca5b820643978cade78744277a1242562518fcb47c1f0e3ab6b0a134e8",
        overload_id: "zed.native.audio.mel-spectrogram-f32.v1",
        ordered_parameters_json: r#"[{"name":"waveform","kind":"positional_or_keyword","type":"Tensor<F32,...T>","default":null,"keyword_only":false},{"name":"configuration","kind":"positional_or_keyword","type":"NativeMelSpectrogramConfiguration","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...MF>"]"#,
        rust_signature: "fn mel_spectrogram_with_context_exact_native(backend: &CpuBackend, waveform: &Tensor, configuration: NativeMelSpectrogramConfiguration, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output; native Hann window, STFT, and mel bank intermediates remain invocation-local",
        shape_rule: "preserves waveform leading dimensions and appends [n_mels, frame_count]",
        dtype_rule: "CPU F32 waveform and output with Complex64 native STFT intermediate",
        accumulation_dtype: "F32 magnitude power and fixed-order mel accumulation",
        layout_rule: "leading dimensions flatten only through a checked contiguous view and are restored in output",
        device_rule: "CPU ordinal zero; unsupported native backends fail typed",
        numeric_rule: "composition of canonical periodic Hann and reflect-centered native STFT with HTK or Slaney triangular mel filters and optional Slaney area normalization",
        tolerance: "3e-4 absolute and relative for finite F32 fixtures",
        determinism: "fixed leading-batch, mel, frame, and frequency traversal",
        cancellation_points: "at every delegated window/STFT boundary, bounded mel-frame intervals, and before publication",
        vjp_rule: "forward-only at cataloged Whisper and audio-model feature-extraction call sites",
        jvp_rule: "forward-only at cataloged Whisper and audio-model feature-extraction call sites",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/mel_spectrogram.json",
        evidence_fixture_sha256: "969a5a5123a0ec3e0aa63ec05b7f74f1f3dfbc2e6ef0d53202939f308b8f0ab9",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-0ABA532316FA",
        baseline_overload_id: "COMFY-TENSOR-OP-0ABA532316FA:blocked",
        baseline_fixture_sha256: "d1ae08641d7119468a882269033d549acab01afc82dfa5b4987217210043e8c9",
        overload_id: "zed.native.vision.roi-align-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,NCHW>","default":null,"keyword_only":false},{"name":"boxes_by_batch","kind":"positional_or_keyword","type":"&[Tensor<F32,K4>]","default":null,"keyword_only":false},{"name":"configuration","kind":"positional_or_keyword","type":"RoiAlignConfiguration","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,KCHW>"]"#,
        rust_signature: "fn roi_align_with_context_exact_native(backend: &CpuBackend, input: &Tensor, boxes_by_batch: &[Tensor], configuration: RoiAlignConfiguration, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output; boxes remain immutable boundary tensors",
        shape_rule: "[N,C,H,W] plus per-batch [K,4] boxes produces [sum(K),C,output_height,output_width]",
        dtype_rule: "CPU F32 input, boxes, and output",
        accumulation_dtype: "F32 bilinear weighted sums",
        layout_rule: "logical NCHW reads and contiguous KCHW output",
        device_rule: "CPU ordinal zero and one input stream; unsupported native backends fail typed",
        numeric_rule: "torchvision aligned offset, adaptive or fixed sampling grid, and boundary-clamped bilinear weights",
        tolerance: "1e-5 absolute for finite F32 fixtures",
        determinism: "fixed ROI, channel, bin, grid, and neighbor traversal",
        cancellation_points: "before validation, at box and output-bin boundaries, and before publication",
        vjp_rule: "scatter-add through every averaged bilinear sample into the input feature map; boxes are non-differentiable in this overload",
        jvp_rule: "the exact forward sampling plan applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/roi_align.json",
        evidence_fixture_sha256: "dfe939939a03218afd73cef9d73f1a4425ac657166d8685bef5529f612b77bb8",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-0AB66ED3B4C2",
        baseline_overload_id: "COMFY-TENSOR-OP-0AB66ED3B4C2:blocked",
        baseline_fixture_sha256: "ba8150aee9eb9adc144580bfc92dba3842c341d2a59d15fc49ce8bfb9f13113d",
        overload_id: "zed.native.vision.normalize-channel-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,...CHW>","default":null,"keyword_only":false},{"name":"mean","kind":"positional_or_keyword","type":"&[f32]","default":null,"keyword_only":false},{"name":"standard_deviation","kind":"positional_or_keyword","type":"&[f32]","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...CHW>"]"#,
        rust_signature: "fn normalize_with_context_exact_native(backend: &CpuBackend, input: &Tensor, mean: &[f32], standard_deviation: &[f32], context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output and immutable affine parameters",
        shape_rule: "preserves [...,C,H,W] input shape and broadcasts scalar or per-channel parameters",
        dtype_rule: "CPU F32 input and output",
        accumulation_dtype: "F32 subtraction and division",
        layout_rule: "logical input reads and contiguous output",
        device_rule: "CPU ordinal zero; unsupported native backends fail typed",
        numeric_rule: "torchvision channel affine equation (input - mean) / standard_deviation",
        tolerance: "1e-6 absolute for finite F32 fixtures",
        determinism: "fixed output-linear traversal",
        cancellation_points: "before validation, at bounded element intervals, and before publication",
        vjp_rule: "output gradient divided by the matching channel standard deviation",
        jvp_rule: "input tangent divided by the matching channel standard deviation",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/normalize.json",
        evidence_fixture_sha256: "3fd874f8ab4700c06f108f0637950185babbf543f3f1b14482d87b64bb486b30",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-0882F83B464A",
        baseline_overload_id: "COMFY-TENSOR-OP-0882F83B464A:blocked",
        baseline_fixture_sha256: "368414dfe364e5a55fe2948fd61b31d9070cad0f4dcac95c4c984172560e7e3d",
        overload_id: "zed.native.vision.resize-backend-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32|U8,...CHW>","default":null,"keyword_only":false},{"name":"output_height","kind":"positional_or_keyword","type":"u64","default":null,"keyword_only":false},{"name":"output_width","kind":"positional_or_keyword","type":"u64","default":null,"keyword_only":false},{"name":"mode","kind":"positional_or_keyword","type":"ResizeMode","default":null,"keyword_only":false},{"name":"antialias","kind":"keyword_only","type":"bool","default":true,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<input dtype,...CHW>"]"#,
        rust_signature: "fn resize_with_context_exact_native(backend: &CpuBackend, input: &Tensor, output_height: u64, output_width: u64, mode: ResizeMode, antialias: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output delegated to the canonical TensorBackend resize publication",
        shape_rule: "preserves every leading and channel dimension and replaces the final H,W dimensions",
        dtype_rule: "CPU F32 or U8; U8 is deterministically converted for sampling then rounded and saturated back to U8",
        accumulation_dtype: "F32 canonical resize sampling",
        layout_rule: "checked contiguous leading-batch flattening into NCHW and restored [...,C,H,W] output",
        device_rule: "CPU ordinal zero through TensorBackend::resize; unsupported native backends fail typed",
        numeric_rule: "canonical nearest, bilinear, area, bicubic, or Lanczos sampling with widened separable bilinear/bicubic filters for antialiased downsampling",
        tolerance: "1e-5 for F32 and one U8 code value where source quantization requires",
        determinism: "canonical backend output-linear traversal and fixed antialias weight order",
        cancellation_points: "before conversion, through canonical backend sampling tiles, and before dtype publication",
        vjp_rule: "forward-only at cataloged mask and uint8 preprocessing call sites",
        jvp_rule: "forward-only at cataloged mask and uint8 preprocessing call sites",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/resize.json",
        evidence_fixture_sha256: "0d847c78e339176fc0dec3412ba121eab6cd4ff16796f33bd92df89cd11846e7",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_01",
        operation_id: "COMFY-TENSOR-OP-2799F344E971",
        baseline_overload_id: "COMFY-TENSOR-OP-2799F344E971:blocked",
        baseline_fixture_sha256: "a0e64964ebf52fbefac542e5e9caaba218f619399e6c23ad17fad31d1363f071",
        overload_id: "zed.native.vision.hwc-u8-to-chw-f32.v1",
        ordered_parameters_json: r#"[{"name":"image_hwc_u8","kind":"positional_or_keyword","type":"&[u8]","default":null,"keyword_only":false},{"name":"height","kind":"positional_or_keyword","type":"u64","default":null,"keyword_only":false},{"name":"width","kind":"positional_or_keyword","type":"u64","default":null,"keyword_only":false},{"name":"channels","kind":"positional_or_keyword","type":"u64","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,CHW>"]"#,
        rust_signature: "fn to_tensor_with_context_exact_native(backend: &CpuBackend, image_hwc_u8: &[u8], height: u64, width: u64, channels: u64, stream: StreamId, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh tensor storage; borrowed native image bytes are never retained",
        shape_rule: "exact HWC byte length maps to CHW with 1, 3, or 4 channels",
        dtype_rule: "U8 input bytes map to F32 values divided by 255",
        accumulation_dtype: "not applicable",
        layout_rule: "deterministic HWC-to-CHW transpose into contiguous output",
        device_rule: "CPU ordinal zero on the explicit stream",
        numeric_rule: "torchvision U8 to_tensor scaling with no PIL, Python, gamma, or color-space conversion",
        tolerance: "bit exact F32 division results",
        determinism: "fixed channel, row, and column traversal",
        cancellation_points: "before validation, at bounded pixel intervals, and before publication",
        vjp_rule: "forward-only boundary conversion from non-differentiable image bytes",
        jvp_rule: "forward-only boundary conversion from non-differentiable image bytes",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-0607daa06439",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_01/to_tensor.json",
        evidence_fixture_sha256: "e022fc790e089aaf36f38c0650cfe26921fb55cc028e130458be20c12527ec5b",
    },
]
