&[
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-A56F89536902",
        baseline_overload_id: "COMFY-TENSOR-OP-A56F89536902:blocked",
        baseline_fixture_sha256: "ce98c40a00e63da3e992d23ac696d00320714a485d15d37bb66320cb9f609529",
        overload_id: "zed.native.einops.rearrange-0.8.1.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor","default":null,"keyword_only":false},{"name":"pattern","kind":"positional_or_keyword","type":"&str","default":null,"keyword_only":false},{"name":"axis_lengths","kind":"keyword_only","type":"&BTreeMap<String,u64>","default":{},"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<input dtype>"]"#,
        rust_signature: "fn einops_rearrange_with_context_exact_native(backend: &CpuBackend, input: &Tensor, pattern: &str, axis_lengths: &BTreeMap<String, u64>, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "delegates to the canonical checked rearrangement plan; stride-only and empty rearrangements share immutable storage while materializing permutations publish fresh storage",
        shape_rule: "einops 0.8.1 named axes, singleton groups, composition, decomposition, one ellipsis, and zero-length dimensions compile to a checked element-count-preserving shape",
        dtype_rule: "preserves every canonical tensor dtype byte-exactly",
        accumulation_dtype: "not applicable",
        layout_rule: "C-order logical axes; checked view strides are retained when representable and otherwise output is contiguous",
        device_rule: "CPU ordinal zero on the input stream; other native devices fail typed",
        numeric_rule: "einops 0.8.1 rearrange axis grammar compiles into the Task 66 canonical NativeRearrangePlan owner",
        tolerance: "bit exact",
        determinism: "immutable recipe and fixed C-order output traversal",
        cancellation_points: "before parsing, during bounded plan compilation, before an empty result returns, during delegated traversal, and before publication",
        vjp_rule: "inverse checked one-to-one rearrangement scatter into the declared input shape",
        jvp_rule: "the same checked rearrangement plan applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/einops_rearrange.json",
        evidence_fixture_sha256: "9fbbde89b35613cd94421fb8a6464542d946ec40a517663e7183473ea801959d",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-4F9C05E204D4",
        baseline_overload_id: "COMFY-TENSOR-OP-4F9C05E204D4:blocked",
        baseline_fixture_sha256: "b9744f8d16e04859e98a3abad2b5d5ca1ca96819cc41f9bc791010e0553e1640",
        overload_id: "zed.native.kornia.rgb-to-lab-0.8.2-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,...C...>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...C...>"]"#,
        rust_signature: "fn rgb_to_lab_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output with no storage alias to the RGB input",
        shape_rule: "preserves rank and shape and requires exactly three channels at the canonical third-from-final channel axis",
        dtype_rule: "CPU F32 input and output",
        accumulation_dtype: "F32 piecewise sRGB linearization, XYZ matrix, and CIE Lab transform",
        layout_rule: "logical strided color reads and contiguous output in the input logical shape",
        device_rule: "CPU ordinal zero on the input stream; other native devices fail typed",
        numeric_rule: "Kornia 0.8.2 D65 sRGB-to-CIE-Lab equations with epsilon 0.008856 and kappa 7.787",
        tolerance: "2e-4 absolute for finite F32 values",
        determinism: "fixed pixel and channel traversal with fixed matrix order",
        cancellation_points: "before validation, at bounded pixel intervals, and before publication",
        vjp_rule: "analytical transpose of the piecewise RGB-to-Lab Jacobian at the primal input",
        jvp_rule: "analytical RGB-to-Lab Jacobian applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/rgb_to_lab.json",
        evidence_fixture_sha256: "62601ee4f38d75c9494e10c16e32e0a666aa76a6f750ef47a6c1aa166e7a9da0",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-A555F803F554",
        baseline_overload_id: "COMFY-TENSOR-OP-A555F803F554:blocked",
        baseline_fixture_sha256: "7b58e404ad03425cab75499692d29b31f0d384f3f5117d12a1c5e7763ee0422e",
        overload_id: "zed.native.kornia.rgb-to-ycbcr-0.8.2-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,...C...>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...C...>"]"#,
        rust_signature: "fn rgb_to_ycbcr_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output with no storage alias to the RGB input",
        shape_rule: "preserves rank and shape and requires exactly three channels at the canonical third-from-final channel axis",
        dtype_rule: "CPU F32 input and output",
        accumulation_dtype: "F32 affine channel transform",
        layout_rule: "logical strided color reads and contiguous output in the input logical shape",
        device_rule: "CPU ordinal zero on the input stream; other native devices fail typed",
        numeric_rule: "Kornia 0.8.2 JPEG YCbCr equations using 0.299, 0.587, 0.114, 0.564, 0.713, and chroma offset 0.5",
        tolerance: "1e-6 absolute for finite F32 values",
        determinism: "fixed pixel and channel traversal with fixed affine order",
        cancellation_points: "before validation, at bounded pixel intervals, and before publication",
        vjp_rule: "exact transpose of the constant RGB-to-YCbCr affine Jacobian",
        jvp_rule: "constant RGB-to-YCbCr affine Jacobian applied to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/rgb_to_ycbcr.json",
        evidence_fixture_sha256: "7261afd10d510b782e77235480a2e603be8b97bd72ec14f17cd705ac75f52dd7",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-9EF1D9EB674A",
        baseline_overload_id: "COMFY-TENSOR-OP-9EF1D9EB674A:blocked",
        baseline_fixture_sha256: "9160d1233d251a0c81cd180158903bcafcea43ae08ff8c8cbe35ab2ab748e7fa",
        overload_id: "zed.native.kornia.ycbcr-to-rgb-0.8.2-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,...C...>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,...C...>"]"#,
        rust_signature: "fn ycbcr_to_rgb_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output with no storage alias to the YCbCr input",
        shape_rule: "preserves rank and shape and requires exactly three channels at the canonical third-from-final channel axis",
        dtype_rule: "CPU F32 input and output",
        accumulation_dtype: "F32 affine channel transform followed by F32 clamp",
        layout_rule: "logical strided color reads and contiguous output in the input logical shape",
        device_rule: "CPU ordinal zero on the input stream; other native devices fail typed",
        numeric_rule: "Kornia 0.8.2 JPEG YCbCr inverse using 1.403, 0.714, 0.344, and 1.773 followed by channel clamp to [0,1]",
        tolerance: "1e-6 absolute for finite F32 values",
        determinism: "fixed pixel and channel traversal with fixed affine order",
        cancellation_points: "before validation, at bounded pixel intervals, and before publication",
        vjp_rule: "transpose affine Jacobian with zero derivative for channels outside the clamp interval",
        jvp_rule: "affine Jacobian applied to the input tangent with zero derivative for channels outside the clamp interval",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/ycbcr_to_rgb.json",
        evidence_fixture_sha256: "6ff4fa8ff87c096af3bd75afd8681f8d5a3b8d51e0ed240b8b10e9ab152dbd0f",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-A551C36699B7",
        baseline_overload_id: "COMFY-TENSOR-OP-A551C36699B7:blocked",
        baseline_fixture_sha256: "819a5d460270afd8cd2dfc9c61a2e1157b5335c332c40a2b011d3daa682c34d7",
        overload_id: "zed.native.kornia.canny-0.8.2-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,BCHW>","default":null,"keyword_only":false},{"name":"low_threshold","kind":"positional_or_keyword","type":"f32","default":0.1,"keyword_only":false},{"name":"high_threshold","kind":"positional_or_keyword","type":"f32","default":0.2,"keyword_only":false}]"#,
        output_arity: "2",
        output_types_json: r#"["Tensor<F32,B1HW> magnitude","Tensor<F32,B1HW> edges"]"#,
        rust_signature: "fn canny_with_context_exact_native(backend: &CpuBackend, input: &Tensor, low_threshold: f32, high_threshold: f32, context: &ExecutionContext<'_>) -> Result<NativeCannyOutput, ExternalTensorKernelPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh magnitude and edge tensors; grayscale, blur, gradient, suppression, and hysteresis buffers remain private",
        shape_rule: "BCHW with C equal to one or three and H,W at least three produces two B1HW tensors",
        dtype_rule: "CPU F32 input, magnitude, and binary edge output",
        accumulation_dtype: "F32 convolution, magnitude, threshold, and hysteresis state",
        layout_rule: "logical BCHW input reads and contiguous B1HW outputs",
        device_rule: "CPU ordinal zero on the input stream; other native devices fail typed",
        numeric_rule: "Kornia 0.8.2 profile: RGB grayscale, separable 5x5 sigma-one Gaussian, Sobel gradient, quantized nonmaximum suppression, double threshold, and eight-neighbor hysteresis",
        tolerance: "2e-5 absolute for magnitude and bit exact for edges",
        determinism: "fixed convolution, pixel, direction, and hysteresis iteration order",
        cancellation_points: "before validation, within bounded convolution and pixel loops, between hysteresis passes, and before publication",
        vjp_rule: "forward-only at the cataloged Canny node inference call site",
        jvp_rule: "forward-only at the cataloged Canny node inference call site",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/canny.json",
        evidence_fixture_sha256: "e71b92be3beddf73aa314b238da7656ae1e89517a86e01a55033ed6e91b49156",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-AF5C2820E4C3",
        baseline_overload_id: "COMFY-TENSOR-OP-AF5C2820E4C3:blocked",
        baseline_fixture_sha256: "e82c1a462fb4db4bdd9e1a64ba2ea105a12a51368634961256ccf0df1b3a3849",
        overload_id: "zed.native.kornia.morphology-dilation-0.8.2-flat-geodesic.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,BCHW>","default":null,"keyword_only":false},{"name":"kernel","kind":"positional_or_keyword","type":"Tensor<F32,HW>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,BCHW>"]"#,
        rust_signature: "fn dilation_with_context_exact_native(backend: &CpuBackend, input: &Tensor, kernel: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output delegated to the sole canonical native morphology traversal owner",
        shape_rule: "preserves BCHW input shape for every nonempty rank-two flat kernel",
        dtype_rule: "CPU F32 input, kernel, and output",
        accumulation_dtype: "F32 comparisons",
        layout_rule: "logical BCHW reads and contiguous BCHW output",
        device_rule: "CPU ordinal zero on one stream; other native devices fail typed",
        numeric_rule: "Kornia 0.8.2 flat dilation with the kernel mask flipped on both axes, inactive entries shifted by -1e4, and default geodesic border delegated to native_morphology_exact",
        tolerance: "bit exact for finite fixtures",
        determinism: "fixed batch, channel, pixel, and kernel traversal",
        cancellation_points: "before validation, at bounded pixel intervals, and before publication",
        vjp_rule: "forward-only at the cataloged morphology node inference call site",
        jvp_rule: "forward-only at the cataloged morphology node inference call site",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/dilation.json",
        evidence_fixture_sha256: "7019329d959a699fb3dcd368d2f959bbd88b1c2d84482f0eefa045102dde6cdb",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-9236C1C08976",
        baseline_overload_id: "COMFY-TENSOR-OP-9236C1C08976:blocked",
        baseline_fixture_sha256: "0791514b69530bde28d8f89de5d196d3fa648610b0f6f4b3e7210179faf3937e",
        overload_id: "zed.native.kornia.morphology-erosion-0.8.2-flat-geodesic.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,BCHW>","default":null,"keyword_only":false},{"name":"kernel","kind":"positional_or_keyword","type":"Tensor<F32,HW>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,BCHW>"]"#,
        rust_signature: "fn erosion_with_context_exact_native(backend: &CpuBackend, input: &Tensor, kernel: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output delegated to the sole canonical native morphology traversal owner",
        shape_rule: "preserves BCHW input shape for every nonempty rank-two flat kernel",
        dtype_rule: "CPU F32 input, kernel, and output",
        accumulation_dtype: "F32 comparisons",
        layout_rule: "logical BCHW reads and contiguous BCHW output",
        device_rule: "CPU ordinal zero on one stream; other native devices fail typed",
        numeric_rule: "Kornia 0.8.2 flat erosion with the kernel mask unflipped, inactive entries shifted by +1e4, and default geodesic border delegated to native_morphology_exact",
        tolerance: "bit exact for finite fixtures",
        determinism: "fixed batch, channel, pixel, and kernel traversal",
        cancellation_points: "before validation, at bounded pixel intervals, and before publication",
        vjp_rule: "forward-only at the cataloged morphology node inference call site",
        jvp_rule: "forward-only at the cataloged morphology node inference call site",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/erosion.json",
        evidence_fixture_sha256: "3bf748576b53bfb6d5a56c225bfa7725a3049dd414c8e939f6d259ba7b2b418f",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-AC69F309A190",
        baseline_overload_id: "COMFY-TENSOR-OP-AC69F309A190:blocked",
        baseline_fixture_sha256: "c8ce526359c5048a6c7a33f5b41d847fe5603e1e92b99d542444b40490f6ca83",
        overload_id: "zed.native.kornia.morphology-top-hat-0.8.2-flat-geodesic.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,BCHW>","default":null,"keyword_only":false},{"name":"kernel","kind":"positional_or_keyword","type":"Tensor<F32,HW>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,BCHW>"]"#,
        rust_signature: "fn top_hat_with_context_exact_native(backend: &CpuBackend, input: &Tensor, kernel: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output; delegated erosion and opening intermediates remain private to the canonical morphology owner",
        shape_rule: "preserves BCHW input shape for every nonempty rank-two flat kernel",
        dtype_rule: "CPU F32 input, kernel, and output",
        accumulation_dtype: "F32 comparisons and subtraction",
        layout_rule: "logical BCHW reads and contiguous BCHW output",
        device_rule: "CPU ordinal zero on one stream; other native devices fail typed",
        numeric_rule: "Kornia 0.8.2 flat top-hat as input minus erosion-then-dilation opening with flipped dilation mask and +1e4 or -1e4 inactive-entry geodesic sentinels delegated to native_morphology_exact",
        tolerance: "bit exact for finite fixtures",
        determinism: "fixed batch, channel, pixel, and kernel traversal",
        cancellation_points: "before validation, within delegated primitives, between composition stages, and before publication",
        vjp_rule: "forward-only at the cataloged morphology node inference call site",
        jvp_rule: "forward-only at the cataloged morphology node inference call site",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/top_hat.json",
        evidence_fixture_sha256: "7bde9a0bfcd6521c0788ae0d02b33bb0d1be2a3cd8b31657240cd448fbe702c9",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-638DE6179D46",
        baseline_overload_id: "COMFY-TENSOR-OP-638DE6179D46:blocked",
        baseline_fixture_sha256: "8779d62bb429e6d6b707bbacd0f5b9d5e8df040208feb414bfd2a2fa8b304545",
        overload_id: "zed.native.torchvision.efficientnet-v2-s-0.27.v1",
        ordered_parameters_json: r#"[]"#,
        output_arity: "1",
        output_types_json: r#"["NativeEfficientNetV2S"]"#,
        rust_signature: "fn efficientnet_v2_s_exact_native(cancellation: &CancellationToken) -> Result<NativeEfficientNetV2S, NativeVisionModelError>",
        mutation_rule: "constructs a new unloaded native model; verified state loading and train or eval mode mutate only that model instance",
        alias_rule: "fresh native module tree and state schema with no shared mutable parameter storage",
        shape_rule: "constructs the torchvision 0.27 EfficientNet-V2-S six-stage 40-block architecture with 1000 classifier outputs",
        dtype_rule: "state schema requires canonical F32 parameters and buffers",
        accumulation_dtype: "F32 native convolution, normalization, activation, pooling, and classifier execution",
        layout_rule: "eval-only model forward accepts logical contiguous NCHW F32 images and publishes contiguous native tensors",
        device_rule: "constructor is device-neutral; loaded model execution uses the native CPU backend and rejects unsupported placement typed",
        numeric_rule: "torchvision 0.27 reviewed-source EfficientNet-V2-S architecture, 21,458,488 parameters, atomic verified state loading, deterministic eval-only inference, and no external runtime",
        tolerance: "1e-4 absolute and relative for finite inference fixtures",
        determinism: "fixed module registration and execution order; deterministic native kernels in eval mode",
        cancellation_points: "during schema construction, verified state loading, at native module boundaries, and before output publication",
        vjp_rule: "forward-only at the two cataloged Stable Cascade feature-extractor inference call sites",
        jvp_rule: "forward-only at the two cataloged Stable Cascade feature-extractor inference call sites",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/efficientnet_v2_s.json",
        evidence_fixture_sha256: "7c3ba3a770a9d1eaa4a1184eb78e955dd8117476c90830c157d73e8f2d189999",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-852D8E9DBC9C",
        baseline_overload_id: "COMFY-TENSOR-OP-852D8E9DBC9C:blocked",
        baseline_fixture_sha256: "c91090df11b5e27f80d6d51be74246ab7e1c3cfd5f62ad20136e9a74779c80fe",
        overload_id: "zed.native.torchvision.raft-large-0.27.v1",
        ordered_parameters_json: r#"[{"name":"weights_requested","kind":"keyword_only","type":"bool","default":false,"keyword_only":true},{"name":"progress","kind":"keyword_only","type":"bool","default":true,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeRaftLarge"]"#,
        rust_signature: "fn raft_large_exact_native(weights_requested: bool, progress: bool, cancellation: &CancellationToken) -> Result<NativeRaftLarge, NativeVisionModelError>",
        mutation_rule: "constructs a new unloaded native model; verified state loading and train or eval mode mutate only that model instance",
        alias_rule: "fresh native module tree and state schema with no shared mutable parameter storage",
        shape_rule: "constructs the torchvision 0.27 RAFT-large feature, context, correlation, recurrent update, and flow-head architecture with twelve default updates",
        dtype_rule: "state schema requires canonical F32 parameters and buffers",
        accumulation_dtype: "F32 native encoder, correlation, recurrent update, and upsampling execution",
        layout_rule: "eval-only forward accepts equal contiguous NCHW F32 image pairs divisible by eight and publishes one contiguous N2HW flow tensor per update",
        device_rule: "constructor is device-neutral; loaded model execution uses the native CPU backend and rejects unsupported placement typed",
        numeric_rule: "torchvision 0.27 reviewed-source RAFT-large architecture, 5,257,536 parameters, atomic verified state loading, deterministic eval-only inference with nonzero one-update and successful twelve-update checkpoints, and no downloads or external runtime",
        tolerance: "1e-4 absolute and relative for finite inference fixtures",
        determinism: "fixed module registration, correlation, update, and output order under native kernels with a fixed twelve-update tensor hash",
        cancellation_points: "during schema construction, verified state loading, at every flow update, and before output publication",
        vjp_rule: "forward-only at the cataloged optical-flow loader and node inference path",
        jvp_rule: "forward-only at the cataloged optical-flow loader and node inference path",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/raft_large.json",
        evidence_fixture_sha256: "53147794c771878de08ab379beebeb54cc52caa7c11f9e9ea9fe2809f0563931",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-9E730487CA71",
        baseline_overload_id: "COMFY-TENSOR-OP-9E730487CA71:blocked",
        baseline_fixture_sha256: "7a2c77e724ff5a8cc78be2f2a371179029fe9b65feaaad52cb601df660c4b453",
        overload_id: "zed.native.torchvision.deform-conv2d-0.27-f32.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32,NCHW>","default":null,"keyword_only":false},{"name":"offset","kind":"positional_or_keyword","type":"Tensor<F32,N2GKKHW>","default":null,"keyword_only":false},{"name":"weight","kind":"positional_or_keyword","type":"Tensor<F32,OIKK>","default":null,"keyword_only":false},{"name":"bias","kind":"keyword_only","type":"Option<&Tensor<F32,O>>","default":null,"keyword_only":true},{"name":"configuration","kind":"keyword_only","type":"NativeDeformConv2dConfiguration","default":{"stride":[1,1],"padding":[0,0],"dilation":[1,1]},"keyword_only":true},{"name":"mask","kind":"keyword_only","type":"Option<&Tensor<F32,GKKHW>>","default":null,"keyword_only":true}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor<F32,NOHW>"]"#,
        rust_signature: "fn deform_conv2d_with_context_exact_native(backend: &CpuBackend, input: &Tensor, offset: &Tensor, weight: &Tensor, bias: Option<&Tensor>, configuration: NativeDeformConv2dConfiguration, mask: Option<&Tensor>, context: &ExecutionContext<'_>) -> Result<Tensor, ExternalTensorKernelPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output; input, offset, weight, optional bias, and optional mask remain immutable",
        shape_rule: "validated NCHW grouped convolution geometry derives NOHW; offset has 2 times offset-groups times kernel-area channels and optional mask has offset-groups times kernel-area channels",
        dtype_rule: "all present tensors are colocated CPU F32",
        accumulation_dtype: "F32 bilinear samples and fixed-order multiply-add accumulation",
        layout_rule: "logical input reads and contiguous NOHW output",
        device_rule: "CPU ordinal zero on one stream; other native devices fail typed",
        numeric_rule: "torchvision 0.27 deform_conv2d grouped zero-padded bilinear sampling with y then x offsets, optional modulation mask, and optional bias",
        tolerance: "2e-5 absolute for finite F32 fixtures",
        determinism: "fixed batch, output-channel, output-pixel, input-channel, kernel, and bilinear-neighbor traversal",
        cancellation_points: "before validation, while decoding inputs, at bounded output intervals, and before publication",
        vjp_rule: "analytical transpose accumulation returns gradients for input, offsets, weights, and present bias and mask through the exact bilinear sampling plan",
        jvp_rule: "analytical directional derivative combines optional input, offset, weight, bias, and mask tangents through the exact forward sampling plan",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/deform_conv2d.json",
        evidence_fixture_sha256: "5d099e5597608f27ce8e8e5e5f1580b1445418c3d2c71b263dfd529b1a860114",
    },
    ResolvedOperationContract {
        resolution_module: "external_tensor_kernel_02",
        operation_id: "COMFY-TENSOR-OP-B7926028DA57",
        baseline_overload_id: "COMFY-TENSOR-OP-B7926028DA57:blocked",
        baseline_fixture_sha256: "ae0774c075d86097774dfc788d8895e5c4c1b0878bcb2d9f4c6a616ecbfb6eb8",
        overload_id: "zed.native.torchvision.to-pil-image-0.27-rgb8-boundary.v1",
        ordered_parameters_json: r#"[{"name":"input","kind":"positional_or_keyword","type":"Tensor<F32|U8,CHW>","default":null,"keyword_only":false}]"#,
        output_arity: "1",
        output_types_json: r#"["Rgb8ImageTensor"]"#,
        rust_signature: "fn to_pil_image_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Rgb8ImageTensor, ExternalTensorKernelPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical native RGB8 image boundary value with no retained tensor storage alias",
        shape_rule: "CHW input with exactly three channels maps to a height by width interleaved RGB8 image",
        dtype_rule: "CPU F32 values use torchvision 0.27 byte scaling semantics and CPU U8 values are copied byte-exactly",
        accumulation_dtype: "F32 scaling before U8 conversion for floating input; not applicable for U8 input",
        layout_rule: "logical CHW tensor reads map deterministically to interleaved HWC RGB8 bytes",
        device_rule: "CPU ordinal zero on the input stream; other native devices fail typed",
        numeric_rule: "torchvision 0.27 ToPILImage RGB conversion represented by Zed canonical Rgb8ImageTensor without Python or PIL runtime ownership",
        tolerance: "bit exact RGB8 bytes",
        determinism: "fixed row, column, and channel traversal",
        cancellation_points: "before validation, during bounded image conversion, and before publication",
        vjp_rule: "forward-only non-differentiable media boundary at the cataloged drawing-node inference call site",
        jvp_rule: "forward-only non-differentiable media boundary at the cataloged drawing-node inference call site",
        owner_task_id: "comfy-parity-tensor-ops-external-tensor-kernel-comfy-tensor-op-4f9c05e204d4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/external_tensor_kernel_02/to_pil_image.json",
        evidence_fixture_sha256: "5f287104cedb74eaacf7da30c492c2127d6a4fe56c8216bb607f2b42d0aced80",
    },
]
