&[
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-301932E71E58",
        baseline_overload_id: "COMFY-TENSOR-OP-301932E71E58:blocked",
        baseline_fixture_sha256: "d8f8ace4443694343cdda9dd9ede6ae91497f2b31ab8eb4fe088fccd8f06c599",
        overload_id: "sim.native.torch.gather.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I64>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn gather_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, index: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "delegates the canonical gather owner",
        shape_rule: "canonical gather shape validation",
        dtype_rule: "preserves input dtype and requires I64 index",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "canonical checked gather",
        tolerance: "bit exact forward",
        determinism: "canonical row-major index order",
        cancellation_points: "canonical gather checkpoints",
        vjp_rule: "canonical deterministic scatter-add",
        jvp_rule: "canonical tangent gather",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/gather_function.json",
        evidence_fixture_sha256: "6d69c702624fa790951fc5ccac5705278bb1c4046718e31dfca898eb7e989920",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-650A7E36398C",
        baseline_overload_id: "COMFY-TENSOR-OP-650A7E36398C:blocked",
        baseline_fixture_sha256: "f9d60b4673ce4d9a133ef725c972dd756c3040744c11b36171bf46d9acc5c203",
        overload_id: "sim.native.tensor.gather.method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I64>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn gather_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, index: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "input and index ranks match; output shape equals index shape; non-axis index extents do not exceed input",
        dtype_rule: "preserves input dtype and requires I64 indices",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "checked nonnegative gather indices",
        tolerance: "bit exact forward",
        determinism: "row-major index order",
        cancellation_points: "before validation, bounded traversal, and before publication",
        vjp_rule: "deterministic scatter-add into the input shape",
        jvp_rule: "gathers the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/gather_method.json",
        evidence_fixture_sha256: "8c1b2483e67f7d31841906dfacb70ba8df38283f4a26cdfb306245de0607b496",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-787E82C83CB5",
        baseline_overload_id: "COMFY-TENSOR-OP-787E82C83CB5:blocked",
        baseline_fixture_sha256: "3c3ca7d79341c4580ca200d37311fa7cd3e14b69174e95497fc89f1478bd7b55",
        overload_id: "sim.native.tensor.index-add-in-place.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor<F32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I32 or I64, rank 1>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"source\",\"type\":\"Tensor<F32>\"},{\"default\":1.0,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"alpha\",\"type\":\"f32\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn index_add_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, dimension: i64, index: &Tensor, source: &Tensor, alpha: f32, context: &ExecutionContext<'_>) -> Result<(), IndexingMaskingPartOneError>",
        mutation_rule: "atomic staged receiver replacement",
        alias_rule: "publishes one canonical replacement only after validation and cancellation checks",
        shape_rule: "source matches input except its indexed axis equals index length",
        dtype_rule: "F32 receiver/source and I32 or I64 index",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous published receiver",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "source-order alpha-scaled addition; repeated indices accumulate",
        tolerance: "exact F32 operation order",
        determinism: "source row-major order",
        cancellation_points: "before validation, bounded staging, and before the only publication",
        vjp_rule: "identity input gradient and alpha-scaled indexed source gradient",
        jvp_rule: "applies the same indexed addition to tangents",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/index_add_in_place.json",
        evidence_fixture_sha256: "c2e86aec46936e8bbf834f994dff0ba00c910d7569ba857acbab945427402985",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-923E7CBA8F2A",
        baseline_overload_id: "COMFY-TENSOR-OP-923E7CBA8F2A:blocked",
        baseline_fixture_sha256: "937fec6430795a26017f46ab08235e492d88ddc73808992d306f220ef6314106",
        overload_id: "sim.native.tensor.masked-fill-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"mask\",\"type\":\"Tensor<Bool>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"value\",\"type\":\"Scalar\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn masked_fill_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, mask: &Tensor, value: Scalar, context: &ExecutionContext<'_>) -> Result<(), IndexingMaskingPartOneError>",
        mutation_rule: "atomic staged receiver replacement",
        alias_rule: "no partial receiver publication",
        shape_rule: "boolean mask broadcasts exactly to receiver shape",
        dtype_rule: "preserves receiver dtype and checked scalar coercion",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous published receiver",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "selected elements receive one pre-encoded scalar",
        tolerance: "bit exact",
        determinism: "row-major mask traversal",
        cancellation_points: "before validation, bounded staging, and before publication",
        vjp_rule: "upstream is zeroed where mask is true",
        jvp_rule: "input tangent is zeroed where mask is true",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/masked_fill_in_place.json",
        evidence_fixture_sha256: "7bc1e31ec73b8a99a18aab725a25c43d813354a3e5eb0a3c1a8c74a3af73c2df",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-A29830647789",
        baseline_overload_id: "COMFY-TENSOR-OP-A29830647789:blocked",
        baseline_fixture_sha256: "b452f009af8644a2b66be9edbc7533663b461d2653c4a49f76a170b6c1da02cd",
        overload_id: "sim.native.torch.narrow.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"start\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"length\",\"type\":\"u64\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor read-only view\"]",
        rust_signature: "fn narrow_function_exact_native(input: &Tensor, dimension: i64, start: i64, length: u64, cancellation: &CancellationToken) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "read only",
        alias_rule: "delegates canonical Tensor narrow read-only view",
        shape_rule: "canonical signed-axis and range normalization",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "preserves strides and adjusts offset",
        device_rule: "preserves device and stream",
        numeric_rule: "no numeric transformation",
        tolerance: "bit exact alias",
        determinism: "canonical narrow geometry",
        cancellation_points: "canonical narrow checkpoints",
        vjp_rule: "canonical narrow scatter",
        jvp_rule: "canonical narrow tangent view",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/narrow_function.json",
        evidence_fixture_sha256: "ade232b49e4c1cdecae32b12ae26677b8528600fd13e24d973e266d24c3a66a4",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-006E05C5DAAF",
        baseline_overload_id: "COMFY-TENSOR-OP-006E05C5DAAF:blocked",
        baseline_fixture_sha256: "353e4625e9bd5c1878e8316e5eb38af8e392706162642c7f54f58a6ead7b6216",
        overload_id: "sim.native.tensor.narrow.method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"start\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"length\",\"type\":\"u64\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor read-only view\"]",
        rust_signature: "fn narrow_method_exact_native(input: &Tensor, dimension: i64, start: i64, length: u64, cancellation: &CancellationToken) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "read only",
        alias_rule: "canonical read-only shared-storage view",
        shape_rule: "normalizes signed axis and start; replaces axis extent with checked length",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "preserves strides and adjusts storage offset",
        device_rule: "preserves device and stream",
        numeric_rule: "no numeric transformation",
        tolerance: "bit exact alias",
        determinism: "canonical TensorDescriptor narrow geometry",
        cancellation_points: "before validation and before view publication",
        vjp_rule: "scatters upstream into a zero input-shaped tensor",
        jvp_rule: "narrows the input tangent through the same canonical view owner",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/narrow_method.json",
        evidence_fixture_sha256: "42e403643e355f121288e3d2d4718d8125cd0c96ac9b561f06e81d35d5e51f8a",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-3885D52BE05C",
        baseline_overload_id: "COMFY-TENSOR-OP-3885D52BE05C:blocked",
        baseline_fixture_sha256: "0d985863167df6808ad7673077659afbfafc2b27f8ed80aaf76fbea4aeb1c200",
        overload_id: "sim.native.torch.nonzero.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"as_tuple\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NonzeroOutput\"]",
        rust_signature: "fn nonzero_with_context_exact_native(backend: &CpuBackend, input: &Tensor, as_tuple: bool, context: &ExecutionContext<'_>) -> Result<NonzeroOutput, IndexingMaskingPartOneError>",
        mutation_rule: "read only",
        alias_rule: "matrix is canonical argwhere output; tuple columns are read-only views over it",
        shape_rule: "matrix is [count, rank]; tuple contains rank vectors of length count",
        dtype_rule: "I64 coordinate outputs for every supported input dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "matrix contiguous; tuple projections strided read-only views",
        device_rule: "CPU ordinal zero",
        numeric_rule: "delegates DecodedScalar truth and canonical argwhere coordinate scan",
        tolerance: "exact coordinates",
        determinism: "row-major coordinate order",
        cancellation_points: "canonical argwhere scan and bounded tuple projection",
        vjp_rule: "forward-only discrete coordinate operation",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/nonzero.json",
        evidence_fixture_sha256: "edc233df0f0dbc0331e0b9a819abb73c17b00daab8ab5c38af74bec6c8476a69",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-2CC6738611B8",
        baseline_overload_id: "COMFY-TENSOR-OP-2CC6738611B8:blocked",
        baseline_fixture_sha256: "7b38be71412401db0aef183dda4237c2bfd9b3e2b3d63b18d37ff8029b0d659d",
        overload_id: "sim.native.torch.scatter.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I64>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"source\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn scatter_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, index: &Tensor, source: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical scatter owner",
        shape_rule: "canonical scatter rank and extent validation",
        dtype_rule: "matching receiver/source dtype and I64 index",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "canonical checked replacement",
        tolerance: "bit exact forward",
        determinism: "canonical row-major last-writer order",
        cancellation_points: "canonical scatter checkpoints",
        vjp_rule: "canonical scatter gradients",
        jvp_rule: "canonical tangent scatter",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/scatter_function.json",
        evidence_fixture_sha256: "e0d655f6eac6d8cf9f4d64dcff0c26c27e7c083c34b6e2c00e87ba697bbd2d19",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-6CEB132BD4F8",
        baseline_overload_id: "COMFY-TENSOR-OP-6CEB132BD4F8:blocked",
        baseline_fixture_sha256: "5edb5529f3e4e0bab34b604595e7979db7ef9664dc53d14704303457b8359f58",
        overload_id: "sim.native.tensor.scatter-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I64>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"source\",\"type\":\"Tensor\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn scatter_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, dimension: i64, index: &Tensor, source: &Tensor, context: &ExecutionContext<'_>) -> Result<(), IndexingMaskingPartOneError>",
        mutation_rule: "atomic staged receiver replacement",
        alias_rule: "no partial receiver publication",
        shape_rule: "delegates the checked canonical scatter plan",
        dtype_rule: "matching receiver/source dtype and I64 index",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous published receiver",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "delegates deterministic scatter replacement",
        tolerance: "bit exact",
        determinism: "canonical scatter row-major last-writer order",
        cancellation_points: "canonical scatter checkpoints plus prepublication check",
        vjp_rule: "delegates scatter derivative owner",
        jvp_rule: "delegates scatter derivative owner",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/scatter_in_place.json",
        evidence_fixture_sha256: "4dfcbc596882704788365a76ecb8fbe2dc25977bf1717e62c560d22e5b90b4cf",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-3710A378E57B",
        baseline_overload_id: "COMFY-TENSOR-OP-3710A378E57B:blocked",
        baseline_fixture_sha256: "3542140789bfac94b08544fcf053ff03dcd5a191ef6c994c5603a79193812f77",
        overload_id: "sim.native.tensor.scatter.method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I64>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"source\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn scatter_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, index: &Tensor, source: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "equal ranks; index extents fit source and receiver non-axis extents",
        dtype_rule: "matching receiver/source dtype and I64 index",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "checked replacement; duplicate destinations use last row-major source",
        tolerance: "bit exact forward",
        determinism: "row-major last-writer order",
        cancellation_points: "before validation, bounded staging, and publication",
        vjp_rule: "zeros written input destinations and gathers upstream into source",
        jvp_rule: "scatters source tangent into input tangent",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/scatter_method.json",
        evidence_fixture_sha256: "cbba037da64312569ae28454ee4b17ec751e09a877711255ddaa23e03d575569",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-40CEC38A1D1F",
        baseline_overload_id: "COMFY-TENSOR-OP-40CEC38A1D1F:blocked",
        baseline_fixture_sha256: "d18e1d73cf924eaefd486e49e0f62133ee8db8e5c6a91e46405c78ac5f254954",
        overload_id: "sim.native.torch.where.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"condition\",\"type\":\"Tensor<Bool>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn where_with_context_exact_native(backend: &CpuBackend, condition: &Tensor, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage; one-argument adapter returns nonzero tuple views",
        shape_rule: "condition and both branches use canonical broadcast geometry",
        dtype_rule: "Bool condition and canonical branch dtype promotion",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "branch selection without arithmetic masking",
        tolerance: "bit exact selected value after checked promotion",
        determinism: "row-major broadcast traversal",
        cancellation_points: "before validation, bounded selection, upload, and publication",
        vjp_rule: "mask-splits upstream then delegates canonical broadcast-gradient reduction",
        jvp_rule: "selects between branch tangents",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/where.json",
        evidence_fixture_sha256: "1dcd75522d076ca0292cfc6be48d0714fd03d742ed8f50ec57808fc4941235a6",
    },
]
