&[
    ResolvedOperationContract {
        resolution_module: "indexing_masking_02",
        operation_id: "COMFY-TENSOR-OP-E9A313720D5D",
        baseline_overload_id: "COMFY-TENSOR-OP-E9A313720D5D:blocked",
        baseline_fixture_sha256: "49818b338002ae66fe5eeb2529b0dad0623f13e2251613a63c63be03503b8205",
        overload_id: "zed.native.tensor.masked-fill.method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"mask\",\"type\":\"Tensor<Bool>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"value\",\"type\":\"Scalar\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn masked_fill_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, mask: &Tensor, value: Scalar, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartTwoError>",
        mutation_rule: "out of place",
        alias_rule: "fresh storage delegated through canonical staged masked-fill owner",
        shape_rule: "canonical boolean-mask broadcasting to input shape",
        dtype_rule: "preserves input dtype and canonical checked scalar coercion",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "delegates branch selection and scalar encoding to Task 71",
        tolerance: "bit exact",
        determinism: "canonical row-major mask traversal",
        cancellation_points: "delegates cancellation-before-validation and bounded staging checkpoints to Task 71",
        vjp_rule: "delegates canonical masked-fill upstream selection",
        jvp_rule: "delegates canonical masked-fill tangent selection",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-e9a313720d5d",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_02/masked_fill_method.json",
        evidence_fixture_sha256: "da998ab8370ad10a6b11fc5305eebe86447fda5aaca64929e4702951d0abd2a9",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_02",
        operation_id: "COMFY-TENSOR-OP-F76D5ACB74F3",
        baseline_overload_id: "COMFY-TENSOR-OP-F76D5ACB74F3:blocked",
        baseline_fixture_sha256: "3702b9931722c690a6020f3e89af22d466bb6556861a3a27aa31f90301a9cc0d",
        overload_id: "zed.native.tensor.nonzero.method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"as_tuple\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NonzeroOutput\"]",
        rust_signature: "fn nonzero_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, as_tuple: bool, context: &ExecutionContext<'_>) -> Result<NonzeroOutput, IndexingMaskingPartTwoError>",
        mutation_rule: "read only",
        alias_rule: "delegates Task 71 matrix/tuple projection exactly",
        shape_rule: "matrix [count, rank] or rank tuple columns of length count",
        dtype_rule: "I64 coordinate outputs for every supported input dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical matrix and read-only tuple column views",
        device_rule: "CPU ordinal zero",
        numeric_rule: "delegates canonical scalar truth and argwhere coordinate enumeration",
        tolerance: "exact coordinates",
        determinism: "canonical row-major coordinate order",
        cancellation_points: "delegates canonical nonzero checkpoints to Task 71",
        vjp_rule: "forward-only discrete coordinate operation",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-e9a313720d5d",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_02/nonzero_method.json",
        evidence_fixture_sha256: "9945d3b5a6b3e5c12c66b336e7923a1ecd5b0e60653abae95e9c72dbf379888d",
    },
]
