&[
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-301932E71E58",
        baseline_overload_id: "COMFY-TENSOR-OP-301932E71E58:blocked",
        baseline_fixture_sha256: "38a1fa1e3032f292d6cc344e8f0ff7e2ece71d974218e05067695c9fa2b36788",
        overload_id: "zed.native.torch.gather.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I64>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn gather_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, index: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "delegates the canonical gather owner",
        shape_rule: "canonical gather shape validation",
        dtype_rule: "preserves input dtype and requires I64 index",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "canonical checked gather",
        tolerance: "bit exact forward",
        determinism: "canonical row-major index order",
        cancellation_points: "canonical gather checkpoints",
        vjp_rule: "canonical deterministic scatter-add",
        jvp_rule: "canonical tangent gather",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/gather_function.json",
        evidence_fixture_sha256: "25d7b51a049f1dfed518a20eeed263d51726f8d4943f834e407c5152277e6098",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-650A7E36398C",
        baseline_overload_id: "COMFY-TENSOR-OP-650A7E36398C:blocked",
        baseline_fixture_sha256: "6684d00468a2818121e87d58622a7beed8a41e164e778668a76c1a44b61215d3",
        overload_id: "zed.native.tensor.gather.method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I64>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn gather_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, index: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "input and index ranks match; output shape equals index shape; non-axis index extents do not exceed input",
        dtype_rule: "preserves input dtype and requires I64 indices",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "checked nonnegative gather indices",
        tolerance: "bit exact forward",
        determinism: "row-major index order",
        cancellation_points: "before validation, bounded traversal, and before publication",
        vjp_rule: "deterministic scatter-add into the input shape",
        jvp_rule: "gathers the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/gather_method.json",
        evidence_fixture_sha256: "526dbdad9662d8780d9a7cebe9a9da0843615d08b9a0a62658daed174d31ef8c",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-787E82C83CB5",
        baseline_overload_id: "COMFY-TENSOR-OP-787E82C83CB5:blocked",
        baseline_fixture_sha256: "714c061cdcbb3d24a4def20ace0cf7805917f862583ff6b99765ff58b0f8dd27",
        overload_id: "zed.native.tensor.index-add-in-place.cpu-f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor<F32>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I32 or I64, rank 1>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"source\",\"type\":\"Tensor<F32>\"},{\"default\":1.0,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"alpha\",\"type\":\"f32\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn index_add_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, dimension: i64, index: &Tensor, source: &Tensor, alpha: f32, context: &ExecutionContext<'_>) -> Result<(), IndexingMaskingPartOneError>",
        mutation_rule: "atomic staged receiver replacement",
        alias_rule: "publishes one canonical replacement only after validation and cancellation checks",
        shape_rule: "source matches input except its indexed axis equals index length",
        dtype_rule: "F32 receiver/source and I32 or I64 index",
        accumulation_dtype: "F32",
        layout_rule: "canonical contiguous published receiver",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "source-order alpha-scaled addition; repeated indices accumulate",
        tolerance: "exact F32 operation order",
        determinism: "source row-major order",
        cancellation_points: "before validation, bounded staging, and before the only publication",
        vjp_rule: "identity input gradient and alpha-scaled indexed source gradient",
        jvp_rule: "applies the same indexed addition to tangents",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/index_add_in_place.json",
        evidence_fixture_sha256: "3c1e46a09100efdef1848fbf317b63f2165dd61bc12ce7e6f3871b7eb02342c6",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-923E7CBA8F2A",
        baseline_overload_id: "COMFY-TENSOR-OP-923E7CBA8F2A:blocked",
        baseline_fixture_sha256: "34a4461f463283060df491f660c80d890df265d523f706458b600ebcc54bcd32",
        overload_id: "zed.native.tensor.masked-fill-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"mask\",\"type\":\"Tensor<Bool>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"value\",\"type\":\"Scalar\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn masked_fill_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, mask: &Tensor, value: Scalar, context: &ExecutionContext<'_>) -> Result<(), IndexingMaskingPartOneError>",
        mutation_rule: "atomic staged receiver replacement",
        alias_rule: "no partial receiver publication",
        shape_rule: "boolean mask broadcasts exactly to receiver shape",
        dtype_rule: "preserves receiver dtype and checked scalar coercion",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous published receiver",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "selected elements receive one pre-encoded scalar",
        tolerance: "bit exact",
        determinism: "row-major mask traversal",
        cancellation_points: "before validation, bounded staging, and before publication",
        vjp_rule: "upstream is zeroed where mask is true",
        jvp_rule: "input tangent is zeroed where mask is true",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/masked_fill_in_place.json",
        evidence_fixture_sha256: "f81330f34fbf556684dd6e8d169777db9c52db9c845626af5831a96b2b374ea9",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-A29830647789",
        baseline_overload_id: "COMFY-TENSOR-OP-A29830647789:blocked",
        baseline_fixture_sha256: "147b4b9bcd787a7ba56b472e6402c88200aff4c1d7d02d86c4eb25a5fa9c57c2",
        overload_id: "zed.native.torch.narrow.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"start\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"length\",\"type\":\"u64\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor read-only view\"]",
        rust_signature: "fn narrow_function_exact_native(input: &Tensor, dimension: i64, start: i64, length: u64, cancellation: &CancellationToken) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "read only",
        alias_rule: "delegates canonical Tensor narrow read-only view",
        shape_rule: "canonical signed-axis and range normalization",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "preserves strides and adjusts offset",
        device_rule: "preserves device and stream",
        numeric_rule: "no numeric transformation",
        tolerance: "bit exact alias",
        determinism: "canonical narrow geometry",
        cancellation_points: "canonical narrow checkpoints",
        vjp_rule: "canonical narrow scatter",
        jvp_rule: "canonical narrow tangent view",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/narrow_function.json",
        evidence_fixture_sha256: "f8d6a042f8821bef965e880cf4d6fe8bda225e9e91d1d8f0146832efc95e0cae",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-006E05C5DAAF",
        baseline_overload_id: "COMFY-TENSOR-OP-006E05C5DAAF:blocked",
        baseline_fixture_sha256: "61d9c0bf3c2df4648eaacdac02052eed8acb01e4dac2784770046220891ab270",
        overload_id: "zed.native.tensor.narrow.method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"start\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"length\",\"type\":\"u64\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor read-only view\"]",
        rust_signature: "fn narrow_method_exact_native(input: &Tensor, dimension: i64, start: i64, length: u64, cancellation: &CancellationToken) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "read only",
        alias_rule: "canonical read-only shared-storage view",
        shape_rule: "normalizes signed axis and start; replaces axis extent with checked length",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "preserves strides and adjusts storage offset",
        device_rule: "preserves device and stream",
        numeric_rule: "no numeric transformation",
        tolerance: "bit exact alias",
        determinism: "canonical TensorDescriptor narrow geometry",
        cancellation_points: "before validation and before view publication",
        vjp_rule: "scatters upstream into a zero input-shaped tensor",
        jvp_rule: "narrows the input tangent through the same canonical view owner",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/narrow_method.json",
        evidence_fixture_sha256: "65dc8ff0c0f67e0f60b8365f854049e6a91e6463abe8a63e025b552deb8a69b6",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-3885D52BE05C",
        baseline_overload_id: "COMFY-TENSOR-OP-3885D52BE05C:blocked",
        baseline_fixture_sha256: "c2750b345b58473a7a26bec1e0194844ce5342058c480f2bf19d1c19962d214b",
        overload_id: "zed.native.torch.nonzero.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"as_tuple\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"NonzeroOutput\"]",
        rust_signature: "fn nonzero_with_context_exact_native(backend: &CpuBackend, input: &Tensor, as_tuple: bool, context: &ExecutionContext<'_>) -> Result<NonzeroOutput, IndexingMaskingPartOneError>",
        mutation_rule: "read only",
        alias_rule: "matrix is canonical argwhere output; tuple columns are read-only views over it",
        shape_rule: "matrix is [count, rank]; tuple contains rank vectors of length count",
        dtype_rule: "I64 coordinate outputs for every supported input dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "matrix contiguous; tuple projections strided read-only views",
        device_rule: "CPU ordinal zero",
        numeric_rule: "delegates DecodedScalar truth and canonical argwhere coordinate scan",
        tolerance: "exact coordinates",
        determinism: "row-major coordinate order",
        cancellation_points: "canonical argwhere scan and bounded tuple projection",
        vjp_rule: "forward-only discrete coordinate operation",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/nonzero.json",
        evidence_fixture_sha256: "3395e04b230c95fe6e4025b85e655d851c2d958987b2622320b3379b0f8ac092",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-2CC6738611B8",
        baseline_overload_id: "COMFY-TENSOR-OP-2CC6738611B8:blocked",
        baseline_fixture_sha256: "5a0714a9383840f775164de3e6009f525bb5e0c95149e3820cf7c79131cac20e",
        overload_id: "zed.native.torch.scatter.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I64>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"source\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn scatter_function_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, index: &Tensor, source: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "delegates canonical scatter owner",
        shape_rule: "canonical scatter rank and extent validation",
        dtype_rule: "matching receiver/source dtype and I64 index",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "canonical checked replacement",
        tolerance: "bit exact forward",
        determinism: "canonical row-major last-writer order",
        cancellation_points: "canonical scatter checkpoints",
        vjp_rule: "canonical scatter gradients",
        jvp_rule: "canonical tangent scatter",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/scatter_function.json",
        evidence_fixture_sha256: "59356cdc95e807011d635119aceb328d309dc33bcc715326965f902f04407c6d",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-6CEB132BD4F8",
        baseline_overload_id: "COMFY-TENSOR-OP-6CEB132BD4F8:blocked",
        baseline_fixture_sha256: "f5a803804deab7483fdccc94e52e6d32e47b198ffbad9791f6e36794cf8ba34d",
        overload_id: "zed.native.tensor.scatter-in-place.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"mutable Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I64>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"source\",\"type\":\"Tensor\"}]",
        output_arity: "0",
        output_types_json: "[]",
        rust_signature: "fn scatter_in_place_with_context_exact_native(backend: &CpuBackend, input: &mut Tensor, dimension: i64, index: &Tensor, source: &Tensor, context: &ExecutionContext<'_>) -> Result<(), IndexingMaskingPartOneError>",
        mutation_rule: "atomic staged receiver replacement",
        alias_rule: "no partial receiver publication",
        shape_rule: "delegates the checked canonical scatter plan",
        dtype_rule: "matching receiver/source dtype and I64 index",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical contiguous published receiver",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "delegates deterministic scatter replacement",
        tolerance: "bit exact",
        determinism: "canonical scatter row-major last-writer order",
        cancellation_points: "canonical scatter checkpoints plus prepublication check",
        vjp_rule: "delegates scatter derivative owner",
        jvp_rule: "delegates scatter derivative owner",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/scatter_in_place.json",
        evidence_fixture_sha256: "7cd06d30f981212ecc16089ba945924a1602e05e5936460dd4d35e8f76b03fc4",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-3710A378E57B",
        baseline_overload_id: "COMFY-TENSOR-OP-3710A378E57B:blocked",
        baseline_fixture_sha256: "878f704092c3cf9a697399e5bc583a1bcd9c5c3610d98edda28cbdd0155d7419",
        overload_id: "zed.native.tensor.scatter.method.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"dimension\",\"type\":\"i64\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"index\",\"type\":\"Tensor<I64>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"source\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn scatter_method_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: i64, index: &Tensor, source: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage",
        shape_rule: "equal ranks; index extents fit source and receiver non-axis extents",
        dtype_rule: "matching receiver/source dtype and I64 index",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "checked replacement; duplicate destinations use last row-major source",
        tolerance: "bit exact forward",
        determinism: "row-major last-writer order",
        cancellation_points: "before validation, bounded staging, and publication",
        vjp_rule: "zeros written input destinations and gathers upstream into source",
        jvp_rule: "scatters source tangent into input tangent",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/scatter_method.json",
        evidence_fixture_sha256: "42a0abd52ed58927ab1324be19b2d44f75985018ec7f243d75c0f91a4c4b597e",
    },
    ResolvedOperationContract {
        resolution_module: "indexing_masking_01",
        operation_id: "COMFY-TENSOR-OP-40CEC38A1D1F",
        baseline_overload_id: "COMFY-TENSOR-OP-40CEC38A1D1F:blocked",
        baseline_fixture_sha256: "88ef479bf6f2930692efe4f569b4bfcb2287a5a466865b5139613e2f6ffa7b45",
        overload_id: "zed.native.torch.where.cpu.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"condition\",\"type\":\"Tensor<Bool>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"other\",\"type\":\"Tensor\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn where_with_context_exact_native(backend: &CpuBackend, condition: &Tensor, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, IndexingMaskingPartOneError>",
        mutation_rule: "out of place",
        alias_rule: "fresh canonical storage; one-argument adapter returns nonzero tuple views",
        shape_rule: "condition and both branches use canonical broadcast geometry",
        dtype_rule: "Bool condition and canonical branch dtype promotion",
        accumulation_dtype: "F32 for cataloged derivatives",
        layout_rule: "canonical contiguous output",
        device_rule: "co-located CPU tensors on one stream",
        numeric_rule: "branch selection without arithmetic masking",
        tolerance: "bit exact selected value after checked promotion",
        determinism: "row-major broadcast traversal",
        cancellation_points: "before validation, bounded selection, upload, and publication",
        vjp_rule: "mask-splits upstream then delegates canonical broadcast-gradient reduction",
        jvp_rule: "selects between branch tangents",
        owner_task_id: "comfy-parity-tensor-ops-indexing-masking-comfy-tensor-op-006e05c5daaf",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/indexing_masking_01/where.json",
        evidence_fixture_sha256: "0fe9af3ffffea5529535aaf5b71f6643e2fbad4b6dcad44c2166eec21a22ea29",
    },
]
