&[
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-061170CBB6F7",
        baseline_overload_id: "COMFY-TENSOR-OP-061170CBB6F7:blocked",
        baseline_fixture_sha256: "42522b7c8191a0c0602eacd353118f17a9b2ea288d7e64446a9621611144ccc5",
        overload_id: "zed.native.tensor.einsum.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"equation\",\"type\":\"str\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"operands\",\"type\":\"Sequence<Tensor<F32>>\",\"default\":null,\"keyword_only\":false,\"kind\":\"variadic_positional\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn einsum_with_context_exact_native(backend: &CpuBackend, equation: &str, operands: &[Tensor], context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh contiguous output",
        shape_rule: "ASCII-label Einstein contraction with explicit or implicit output, repeated-label diagonals, and right-aligned ellipsis broadcasting",
        dtype_rule: "F32 inputs and output",
        accumulation_dtype: "F64 workspace then checked F32 publication",
        layout_rule: "arbitrary readable input views; contiguous output",
        device_rule: "co-located CPU ordinal-zero tensors on one stream",
        numeric_rule: "fixed output-label then reduction-label traversal",
        tolerance: "absolute 1e-5 and relative 1e-5",
        determinism: "lexical label and row-major index order",
        cancellation_points: "before validation, bounded contraction iterations, and before publication",
        vjp_rule: "exact product-rule contraction with broadcast and diagonal accumulation",
        jvp_rule: "sum of one contraction per substituted operand tangent",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/einsum.json",
        evidence_fixture_sha256: "3547cd98eba1de1b12c7fe9033c142182341b2b1dd5391f4fe2984ca7a524153",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-4444EA894499",
        baseline_overload_id: "COMFY-TENSOR-OP-4444EA894499:blocked",
        baseline_fixture_sha256: "b5c5d22f12f0fab85f1339e6159e2a3873ad3851cc9afbfa718c5ba5cd1aec68",
        overload_id: "zed.native.tensor.linalg-cross.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"other\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"i64\",\"default\":-1,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn linalg_cross_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "canonical Task 62 fresh output",
        shape_rule: "canonical broadcast with selected extent-three axis",
        dtype_rule: "canonical F32 pair",
        accumulation_dtype: "canonical F32",
        layout_rule: "canonical checked tensor views",
        device_rule: "CPU ordinal zero",
        numeric_rule: "delegates the sole Task 62 cross-product owner",
        tolerance: "absolute 1e-6",
        determinism: "canonical row-major traversal",
        cancellation_points: "before and throughout canonical delegation",
        vjp_rule: "delegates canonical bilinear cross VJP",
        jvp_rule: "delegates canonical bilinear cross JVP",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/linalg_cross.json",
        evidence_fixture_sha256: "5d322a3940c24bb419dff4ec0ebfe87f0ee3fce8e8eb349adfe89249d2975226",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-1D21A20B5805",
        baseline_overload_id: "COMFY-TENSOR-OP-1D21A20B5805:blocked",
        baseline_fixture_sha256: "513ad83a8805dc53f92720d5a2eee1b7d5062ec4a65d3117c5d7d06192040e1f",
        overload_id: "zed.native.tensor.linalg-det.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32,rank>=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn determinant_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh batch-shaped output",
        shape_rule: "[...,n,n] maps to [...] and singular matrices return zero",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F64 pivot workspace",
        layout_rule: "arbitrary readable view",
        device_rule: "CPU ordinal zero",
        numeric_rule: "deterministic column-relative partial-pivot elimination",
        tolerance: "absolute 1e-5 and relative 1e-5",
        determinism: "batch-column-max-pivot order",
        cancellation_points: "before validation, per batch, at bounded elimination loops, and before publication",
        vjp_rule: "cofactor matrix times upstream, including singular inputs",
        jvp_rule: "cofactor inner product with input tangent",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/determinant.json",
        evidence_fixture_sha256: "0f3dd65c852d0bdd445b21a6f0ceb4b537bf26a74213bb989d8cffb09e92df02",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-1B84B4F50448",
        baseline_overload_id: "COMFY-TENSOR-OP-1B84B4F50448:blocked",
        baseline_fixture_sha256: "5f7356681a268ec152cb99d85db496d53e4dbe360ee5d61c9c0db28481b6e9cf",
        overload_id: "zed.native.tensor.linalg-eigh.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32,rank>=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"use_upper_triangle\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor<F32>\",\"Tensor<F32>\"]",
        rust_signature: "fn eigh_with_context_exact_native(backend: &CpuBackend, input: &Tensor, use_upper_triangle: bool, context: &ExecutionContext<'_>) -> Result<EighOutput, LinearAlgebraPartOneError>",
        mutation_rule: "read only; outputs publish after all batches complete",
        alias_rule: "fresh eigenvalue and eigenvector storage",
        shape_rule: "[...,n,n] maps to eigenvalues [...,n] and column eigenvectors [...,n,n]",
        dtype_rule: "F32 input and outputs",
        accumulation_dtype: "F64 Jacobi workspace",
        layout_rule: "selected triangle is mirrored into a symmetric workspace",
        device_rule: "CPU ordinal zero",
        numeric_rule: "Jacobi rotations, ascending eigenvalues, largest-magnitude-positive vector signs",
        tolerance: "absolute 2e-5",
        determinism: "fixed maximum-offdiagonal pivot and stable spectrum order",
        cancellation_points: "before validation, every bounded sweep, each batch, before publication",
        vjp_rule: "forward-only at cataloged inference call sites; later differentiable reachability requires a reopened profile",
        jvp_rule: "forward-only at cataloged inference call sites",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/eigh.json",
        evidence_fixture_sha256: "087133d11849539a85c3846c961fc0c57fe8476b59c35d7e860b518285cba490",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-7DD46810B2C2",
        baseline_overload_id: "COMFY-TENSOR-OP-7DD46810B2C2:blocked",
        baseline_fixture_sha256: "e6c341cc281cee1e6f5a8e3efff092f1e9281614cb6e17186387205561cc6ba9",
        overload_id: "zed.native.tensor.linalg-inv.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32,rank>=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn inverse_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh contiguous output",
        shape_rule: "preserves [...,n,n]; singular matrices return typed errors",
        dtype_rule: "F32",
        accumulation_dtype: "F64 LU workspace",
        layout_rule: "arbitrary readable input view",
        device_rule: "CPU ordinal zero",
        numeric_rule: "partial-pivot LU solves against identity",
        tolerance: "absolute 2e-5",
        determinism: "fixed batch and pivot order",
        cancellation_points: "before validation, per batch, within solves, before publication",
        vjp_rule: "-A^-T upstream A^-T",
        jvp_rule: "-A^-1 tangent A^-1",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/inverse.json",
        evidence_fixture_sha256: "1177089a673694380fb7c993768df2731709abd3664174ff0bae3ab95f5a11ef",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-3FB914121F89",
        baseline_overload_id: "COMFY-TENSOR-OP-3FB914121F89:blocked",
        baseline_fixture_sha256: "3d17167b1bb409cc9cb5bdc2ed9ca9b9d512bf5b8f1c852c9828b64893b1e6e8",
        overload_id: "zed.native.tensor.linalg-qr.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32,rank>=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"mode\",\"type\":\"QrMode\",\"default\":\"Reduced\",\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"QrOutput\"]",
        rust_signature: "fn qr_with_context_exact_native(backend: &CpuBackend, input: &Tensor, mode: QrMode, context: &ExecutionContext<'_>) -> Result<QrOutput, LinearAlgebraPartOneError>",
        mutation_rule: "read only; selected outputs publish after all batches",
        alias_rule: "fresh Q and R storage",
        shape_rule: "PyTorch reduced, complete, and R output ranks for [...,m,n]",
        dtype_rule: "F32",
        accumulation_dtype: "F64 orthogonalization workspace",
        layout_rule: "arbitrary readable input view",
        device_rule: "CPU ordinal zero",
        numeric_rule: "deterministic reorthogonalized column basis with canonical completion",
        tolerance: "reconstruction and orthogonality absolute 2e-5",
        determinism: "column order then canonical basis order",
        cancellation_points: "before validation, per batch and basis column, before publication",
        vjp_rule: "forward-only at the cataloged inference call sites",
        jvp_rule: "forward-only at the cataloged inference call sites",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/qr.json",
        evidence_fixture_sha256: "7bf3391d27d73afca78d426d5d0072437b0f5895c7a8b055837ac826ac7500a5",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-93065313ABB0",
        baseline_overload_id: "COMFY-TENSOR-OP-93065313ABB0:blocked",
        baseline_fixture_sha256: "751ddeec774a64e8749fc06e090336d11c0ee848dffd3375d6ccdb0afa69700d",
        overload_id: "zed.native.tensor.linalg-solve.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"coefficient\",\"type\":\"Tensor<F32,...,n,n>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"right_hand_side\",\"type\":\"Tensor<F32,...,n|n,k>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn solve_with_context_exact_native(backend: &CpuBackend, coefficient: &Tensor, right_hand_side: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh output",
        shape_rule: "right-aligned broadcast batches with vector or matrix right-hand sides",
        dtype_rule: "F32",
        accumulation_dtype: "F64 LU workspace",
        layout_rule: "arbitrary readable views",
        device_rule: "co-located CPU ordinal-zero tensors",
        numeric_rule: "one partial-pivot LU factor per batch",
        tolerance: "absolute 2e-5",
        determinism: "batch, pivot, row, column order",
        cancellation_points: "before validation, per batch and solve rows, before publication",
        vjp_rule: "right gradient A^-T upstream; coefficient gradient -right_gradient solution^T",
        jvp_rule: "A^-1(right_tangent - coefficient_tangent solution)",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/solve.json",
        evidence_fixture_sha256: "76250eaa70e5455da1f014e992939c2121f5f34f506035f464b4a00fd29496cd",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-8E3FD7459720",
        baseline_overload_id: "COMFY-TENSOR-OP-8E3FD7459720:blocked",
        baseline_fixture_sha256: "4883db46bf4cbc7cce706a5b078750275251b58904a7fde13906b3a38a978a41",
        overload_id: "zed.native.tensor.linalg-vector-norm.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"order\",\"type\":\"f64\",\"default\":2,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Sequence<i64>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"keep_dimension\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn vector_norm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, order: f64, dimensions: &[i64], keep_dimension: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh reduced output",
        shape_rule: "one or more unique normalized dimensions removed or retained at extent one",
        dtype_rule: "F32 input/output and absent or F32 dtype override",
        accumulation_dtype: "F64 reduction workspace",
        layout_rule: "arbitrary readable view",
        device_rule: "CPU ordinal zero",
        numeric_rule: "fixed-order p, zero, and positive/negative infinity norms with NaN propagation",
        tolerance: "absolute 1e-6",
        determinism: "row-major reduction and equal-extremum tie split",
        cancellation_points: "before validation, bounded input traversal, before publication",
        vjp_rule: "analytic p-norm derivative with zero-norm convention and equal-extremum tie split",
        jvp_rule: "inner product of analytic derivative and input tangent",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/vector_norm.json",
        evidence_fixture_sha256: "d5c57e34c22f2855d2b1ecffc0dba7d99a6f170f1591faeb941768ab186c12b9",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-98D79FD6A7D2",
        baseline_overload_id: "COMFY-TENSOR-OP-98D79FD6A7D2:blocked",
        baseline_fixture_sha256: "ef4d8856f41e7eb45f1e6c988f5de0474dac37ee36f9222bf79e2933556edcac",
        overload_id: "zed.native.tensor.matmul.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"other\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn matmul_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh contiguous output",
        shape_rule: "PyTorch vector promotion/removal and right-aligned batch broadcasting",
        dtype_rule: "co-located F32",
        accumulation_dtype: "F64 workspace",
        layout_rule: "arbitrary readable views",
        device_rule: "CPU ordinal zero and one stream",
        numeric_rule: "fixed batch-row-column-inner contraction",
        tolerance: "absolute 1e-5",
        determinism: "row-major traversal",
        cancellation_points: "before validation, bounded output elements, before publication",
        vjp_rule: "transpose contractions with broadcast accumulation",
        jvp_rule: "input_tangent@other + input@other_tangent",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/matmul.json",
        evidence_fixture_sha256: "8cc9cb3ade7b6e90dbcdd91f03bebdad2f6d3f5f89eacb5f7746b6b16c83b64c",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-277D4AF43E05",
        baseline_overload_id: "COMFY-TENSOR-OP-277D4AF43E05:blocked",
        baseline_fixture_sha256: "7309c65a5ebbcc5cb84e8da653871c4b8c7e4060e1eef227df3fadef0fd0b423",
        overload_id: "zed.native.tensor.mm.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32,rank=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"mat2\",\"type\":\"Tensor<F32,rank=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn mm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, mat2: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh canonical matmul output",
        shape_rule: "rank-two [m,k] by [k,n] only",
        dtype_rule: "F32",
        accumulation_dtype: "canonical matmul F64 workspace",
        layout_rule: "canonical matmul views",
        device_rule: "co-located CPU ordinal zero",
        numeric_rule: "focused rank guard then canonical matmul owner",
        tolerance: "absolute 1e-5",
        determinism: "canonical matmul",
        cancellation_points: "before guard and canonical bounded checkpoints",
        vjp_rule: "canonical matmul VJP after rank guard",
        jvp_rule: "canonical matmul JVP after rank guard",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/mm.json",
        evidence_fixture_sha256: "5e8746059835fb844133fb1b03b86842a62f245a2aebb6598646a72abbd05186",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-2F913F6635CB",
        baseline_overload_id: "COMFY-TENSOR-OP-2F913F6635CB:blocked",
        baseline_fixture_sha256: "900011970eb6a41e3effc7ea4dbf4b7b38cd9c3f8b403ad658a7d61b458bc03d",
        overload_id: "zed.native.tensor.tensordot.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"other\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_dimensions\",\"type\":\"Sequence<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"other_dimensions\",\"type\":\"Sequence<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn tensordot_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, input_dimensions: &[i64], other_dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh contiguous output",
        shape_rule: "uncontracted input dimensions followed by uncontracted other dimensions",
        dtype_rule: "co-located F32",
        accumulation_dtype: "F64 workspace",
        layout_rule: "arbitrary readable views",
        device_rule: "CPU ordinal zero and one stream",
        numeric_rule: "projects explicit axes into the canonical Einstein contraction owner",
        tolerance: "absolute 1e-5",
        determinism: "canonical contraction traversal",
        cancellation_points: "before validation, bounded contraction iterations, before publication",
        vjp_rule: "canonical contraction gradient for both operands",
        jvp_rule: "sum of the two tangent-substituted contractions",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/tensordot.json",
        evidence_fixture_sha256: "26f3048cd92df484a6b3630da74401816d393753b6652c53fff8fbeb6a550ca2",
    },
]
