&[
    ResolvedOperationContract {
        resolution_module: "linear_algebra_02",
        operation_id: "COMFY-TENSOR-OP-C31767F422EE",
        baseline_overload_id: "COMFY-TENSOR-OP-C31767F422EE:blocked",
        baseline_fixture_sha256: "578a63bc9579ffa17ef7d6314aecbe456c7eec0969a400dbca2b570a9cce8a77",
        overload_id: "zed.native.tensor.bmm.cpu.f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<F32,rank=3>\"},{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"mat2\",\"type\":\"Tensor<F32,rank=3>\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn bmm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, mat2: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartTwoError>",
        mutation_rule: "read only; output published only after canonical kernel completion",
        alias_rule: "fresh contiguous output storage",
        shape_rule: "[batch,m,k] x [batch,k,n] -> [batch,m,n] with exact batch equality and no broadcasting",
        dtype_rule: "F32 inputs and F32 output",
        accumulation_dtype: "F32",
        layout_rule: "arbitrary non-overlapping input views; contiguous output",
        device_rule: "co-located CPU ordinal-zero tensors on one stream",
        numeric_rule: "canonical CpuBackend row-major contracted sum",
        tolerance: "absolute 1e-5 and relative 1e-5",
        determinism: "fixed batch-row-column-inner traversal",
        cancellation_points: "before validation, before dispatch, and canonical per-element/contraction checkpoints",
        vjp_rule: "grad_input = bmm(grad_output, mat2 transpose); grad_mat2 = bmm(input transpose, grad_output)",
        jvp_rule: "bmm(input_tangent, mat2) + bmm(input, mat2_tangent)",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-a5d623c79a18",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_02/bmm.json",
        evidence_fixture_sha256: "aa2453bf81dd945f898b756ae2659d006d7ab92457da8e49b4f3ceebaaa26798",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_02",
        operation_id: "COMFY-TENSOR-OP-A5D623C79A18",
        baseline_overload_id: "COMFY-TENSOR-OP-A5D623C79A18:blocked",
        baseline_fixture_sha256: "b65e6b9fdea45d651da5400b8991a25fa10e2d78c332468c9aaeed0a1050d166",
        overload_id: "zed.native.tensor.linalg-norm.euclidean.cpu.f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<F32>\"},{\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"dim\",\"type\":\"Option<Sequence<i64>>\"},{\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"keepdim\",\"type\":\"bool\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn norm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keepdim: bool, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartTwoError>",
        mutation_rule: "read only",
        alias_rule: "fresh contiguous output storage",
        shape_rule: "dim=None reduces all elements; explicit one or more unique normalized dimensions are removed or retained as size one",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F64 sum of squares",
        layout_rule: "arbitrary non-overlapping input view; contiguous output",
        device_rule: "CPU ordinal zero on the input stream",
        numeric_rule: "Euclidean/Frobenius norm sqrt(sum(x*x)) delegated to Task 72 vector-norm owner",
        tolerance: "absolute 1e-6 and relative 1e-6",
        determinism: "canonical Task 72 reduction order",
        cancellation_points: "before delegation and canonical bounded reduction checkpoints",
        vjp_rule: "input gradient is upstream * input / norm, with zero selected for zero norm",
        jvp_rule: "sum(input * tangent) / norm over reduced dimensions, with zero selected for zero norm",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-a5d623c79a18",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_02/norm.json",
        evidence_fixture_sha256: "b09292dc503b69d8c86e29a7b8d6c0ccfe72fed0dbdc795c02f9cc7223ff30b6",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_02",
        operation_id: "COMFY-TENSOR-OP-B42F17255D7D",
        baseline_overload_id: "COMFY-TENSOR-OP-B42F17255D7D:blocked",
        baseline_fixture_sha256: "9fe1b0dd5de3f45246292dd090c05a51443fc23232670bad2122225d48ab3c45",
        overload_id: "zed.native.tensor.linalg-svd.cpu.f32.v1",
        ordered_parameters_json: "[{\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\",\"name\":\"input\",\"type\":\"Tensor<F32,rank>=2>\"},{\"default\":true,\"keyword_only\":true,\"kind\":\"keyword_only\",\"name\":\"full_matrices\",\"type\":\"bool\"}]",
        output_arity: "3",
        output_types_json: "[\"Tensor<F32>\",\"Tensor<F32>\",\"Tensor<F32>\"]",
        rust_signature: "fn svd_with_context_exact_native(backend: &CpuBackend, input: &Tensor, full_matrices: bool, context: &ExecutionContext<'_>) -> Result<SvdOutput, LinearAlgebraPartTwoError>",
        mutation_rule: "read only; all three outputs publish atomically after every batch succeeds",
        alias_rule: "three fresh contiguous output storages",
        shape_rule: "[...,m,n] -> U [...,m,m or k], S [...,k], Vh [...,n,n or k,n], k=min(m,n)",
        dtype_rule: "F32 input and F32 outputs",
        accumulation_dtype: "F64 decomposition workspace",
        layout_rule: "arbitrary non-overlapping input view; contiguous outputs",
        device_rule: "CPU ordinal zero on the input stream",
        numeric_rule: "Task 72 symmetric eigendecomposition owner plus deterministic orthonormal completion; descending nonnegative singular values and canonical vector signs",
        tolerance: "reconstruction absolute 2e-5 and relative 2e-5; orthogonality 2e-5",
        determinism: "fixed batch order, Task 72 eigensolver order, descending stable spectrum sort, and largest-magnitude-positive sign convention",
        cancellation_points: "before validation, at each batch/decomposition sweep, and before atomic output uploads",
        vjp_rule: "analytic reduced-SVD adjoint for distinct positive singular values; full-matrix null-space gradients are ignored as externally undefined",
        jvp_rule: "analytic reduced-SVD directional derivative for distinct positive singular values; full-matrix null-space tangents are zero",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-a5d623c79a18",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_02/svd.json",
        evidence_fixture_sha256: "47778ea7b37f48a8f08fcd2a1068c50ed30d2660d5f174019067860c2d0fbb9f",
    },
]
