&[
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-061170CBB6F7",
        baseline_overload_id: "COMFY-TENSOR-OP-061170CBB6F7:blocked",
        baseline_fixture_sha256: "59be6a4557ad5129f4595cb12793cd0b17217031103f990d54fac04539869028",
        overload_id: "sim.native.tensor.einsum.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"equation\",\"type\":\"str\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"operands\",\"type\":\"Sequence<Tensor<F32>>\",\"default\":null,\"keyword_only\":false,\"kind\":\"variadic_positional\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn einsum_with_context_exact_native(backend: &CpuBackend, equation: &str, operands: &[Tensor], context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh contiguous output",
        shape_rule: "ASCII-label Einstein contraction with explicit or implicit output, repeated-label diagonals, and right-aligned ellipsis broadcasting",
        dtype_rule: "F32 inputs and output",
        accumulation_dtype: "F64 workspace then checked F32 publication",
        layout_rule: "arbitrary readable input views; contiguous output",
        device_rule: "co-located CPU ordinal-zero tensors on one stream",
        numeric_rule: "fixed output-label then reduction-label traversal",
        tolerance: "absolute 1e-5 and relative 1e-5",
        determinism: "lexical label and row-major index order",
        cancellation_points: "before validation, bounded contraction iterations, and before publication",
        vjp_rule: "exact product-rule contraction with broadcast and diagonal accumulation",
        jvp_rule: "sum of one contraction per substituted operand tangent",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/einsum.json",
        evidence_fixture_sha256: "8c44504e3b59af23be7dc9fb67cbc07650368e4078edd253115fb517738690b7",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-4444EA894499",
        baseline_overload_id: "COMFY-TENSOR-OP-4444EA894499:blocked",
        baseline_fixture_sha256: "410beda6d5c8e3843a37f7b38961ad1636f91194f88b7934c3a4381f59a50642",
        overload_id: "sim.native.tensor.linalg-cross.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"other\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"i64\",\"default\":-1,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn linalg_cross_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "canonical Task 62 fresh output",
        shape_rule: "canonical broadcast with selected extent-three axis",
        dtype_rule: "canonical F32 pair",
        accumulation_dtype: "canonical F32",
        layout_rule: "canonical checked tensor views",
        device_rule: "CPU ordinal zero",
        numeric_rule: "delegates the sole Task 62 cross-product owner",
        tolerance: "absolute 1e-6",
        determinism: "canonical row-major traversal",
        cancellation_points: "before and throughout canonical delegation",
        vjp_rule: "delegates canonical bilinear cross VJP",
        jvp_rule: "delegates canonical bilinear cross JVP",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/linalg_cross.json",
        evidence_fixture_sha256: "cd5613c593a2b6e6f5cda14fbfcd4a63217613fdc6b618005688e8d2e268bf4f",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-1D21A20B5805",
        baseline_overload_id: "COMFY-TENSOR-OP-1D21A20B5805:blocked",
        baseline_fixture_sha256: "e4bb672ec8731b49dcb3759152130153ec1e4fa453e7003ff284ac7eb7e937f6",
        overload_id: "sim.native.tensor.linalg-det.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32,rank>=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn determinant_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh batch-shaped output",
        shape_rule: "[...,n,n] maps to [...] and singular matrices return zero",
        dtype_rule: "F32 input and output",
        accumulation_dtype: "F64 pivot workspace",
        layout_rule: "arbitrary readable view",
        device_rule: "CPU ordinal zero",
        numeric_rule: "deterministic column-relative partial-pivot elimination",
        tolerance: "absolute 1e-5 and relative 1e-5",
        determinism: "batch-column-max-pivot order",
        cancellation_points: "before validation, per batch, at bounded elimination loops, and before publication",
        vjp_rule: "cofactor matrix times upstream, including singular inputs",
        jvp_rule: "cofactor inner product with input tangent",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/determinant.json",
        evidence_fixture_sha256: "ebb4b93d5c0fcfaa433e8725bdc63055bcf7868b9b08f9deb765694147cca74f",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-1B84B4F50448",
        baseline_overload_id: "COMFY-TENSOR-OP-1B84B4F50448:blocked",
        baseline_fixture_sha256: "fef7587f91ab2464a6d92e102b1a835debb48c8b3054a91d83d204d6d3bc1af7",
        overload_id: "sim.native.tensor.linalg-eigh.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32,rank>=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"use_upper_triangle\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor<F32>\",\"Tensor<F32>\"]",
        rust_signature: "fn eigh_with_context_exact_native(backend: &CpuBackend, input: &Tensor, use_upper_triangle: bool, context: &ExecutionContext<'_>) -> Result<EighOutput, LinearAlgebraPartOneError>",
        mutation_rule: "read only; outputs publish after all batches complete",
        alias_rule: "fresh eigenvalue and eigenvector storage",
        shape_rule: "[...,n,n] maps to eigenvalues [...,n] and column eigenvectors [...,n,n]",
        dtype_rule: "F32 input and outputs",
        accumulation_dtype: "F64 Jacobi workspace",
        layout_rule: "selected triangle is mirrored into a symmetric workspace",
        device_rule: "CPU ordinal zero",
        numeric_rule: "Jacobi rotations, ascending eigenvalues, largest-magnitude-positive vector signs",
        tolerance: "absolute 2e-5",
        determinism: "fixed maximum-offdiagonal pivot and stable spectrum order",
        cancellation_points: "before validation, every bounded sweep, each batch, before publication",
        vjp_rule: "forward-only at cataloged inference call sites; later differentiable reachability requires a reopened profile",
        jvp_rule: "forward-only at cataloged inference call sites",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/eigh.json",
        evidence_fixture_sha256: "0918f528e5044c94aec9bfa0ea223c8ca6f350183d3ac0f745e3c405e4eda74e",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-7DD46810B2C2",
        baseline_overload_id: "COMFY-TENSOR-OP-7DD46810B2C2:blocked",
        baseline_fixture_sha256: "bc19be8f77d52eb96aa5281a99598a5c368500fedb18852aa152867f44ed1795",
        overload_id: "sim.native.tensor.linalg-inv.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32,rank>=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn inverse_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh contiguous output",
        shape_rule: "preserves [...,n,n]; singular matrices return typed errors",
        dtype_rule: "F32",
        accumulation_dtype: "F64 LU workspace",
        layout_rule: "arbitrary readable input view",
        device_rule: "CPU ordinal zero",
        numeric_rule: "partial-pivot LU solves against identity",
        tolerance: "absolute 2e-5",
        determinism: "fixed batch and pivot order",
        cancellation_points: "before validation, per batch, within solves, before publication",
        vjp_rule: "-A^-T upstream A^-T",
        jvp_rule: "-A^-1 tangent A^-1",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/inverse.json",
        evidence_fixture_sha256: "26151603d4d2e7f716bbcc04c5dd9408d36a41fd0256085de0a63f0e3a572ab4",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-3FB914121F89",
        baseline_overload_id: "COMFY-TENSOR-OP-3FB914121F89:blocked",
        baseline_fixture_sha256: "d5929c76e01b091ff62d67f89c38153f128ded0780242ce008d86e7970b34491",
        overload_id: "sim.native.tensor.linalg-qr.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32,rank>=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"mode\",\"type\":\"QrMode\",\"default\":\"Reduced\",\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"QrOutput\"]",
        rust_signature: "fn qr_with_context_exact_native(backend: &CpuBackend, input: &Tensor, mode: QrMode, context: &ExecutionContext<'_>) -> Result<QrOutput, LinearAlgebraPartOneError>",
        mutation_rule: "read only; selected outputs publish after all batches",
        alias_rule: "fresh Q and R storage",
        shape_rule: "PyTorch reduced, complete, and R output ranks for [...,m,n]",
        dtype_rule: "F32",
        accumulation_dtype: "F64 orthogonalization workspace",
        layout_rule: "arbitrary readable input view",
        device_rule: "CPU ordinal zero",
        numeric_rule: "deterministic reorthogonalized column basis with canonical completion",
        tolerance: "reconstruction and orthogonality absolute 2e-5",
        determinism: "column order then canonical basis order",
        cancellation_points: "before validation, per batch and basis column, before publication",
        vjp_rule: "forward-only at the cataloged inference call sites",
        jvp_rule: "forward-only at the cataloged inference call sites",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/qr.json",
        evidence_fixture_sha256: "ee27f12908826cb513a72cdadbc598e36b106c02fb9b006836603ced96c2878b",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-93065313ABB0",
        baseline_overload_id: "COMFY-TENSOR-OP-93065313ABB0:blocked",
        baseline_fixture_sha256: "6abd72d4e4757c27ad8454544c248d387e856a119486f2fc8d70111d474b5237",
        overload_id: "sim.native.tensor.linalg-solve.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"coefficient\",\"type\":\"Tensor<F32,...,n,n>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"right_hand_side\",\"type\":\"Tensor<F32,...,n|n,k>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn solve_with_context_exact_native(backend: &CpuBackend, coefficient: &Tensor, right_hand_side: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh output",
        shape_rule: "right-aligned broadcast batches with vector or matrix right-hand sides",
        dtype_rule: "F32",
        accumulation_dtype: "F64 LU workspace",
        layout_rule: "arbitrary readable views",
        device_rule: "co-located CPU ordinal-zero tensors",
        numeric_rule: "one partial-pivot LU factor per batch",
        tolerance: "absolute 2e-5",
        determinism: "batch, pivot, row, column order",
        cancellation_points: "before validation, per batch and solve rows, before publication",
        vjp_rule: "right gradient A^-T upstream; coefficient gradient -right_gradient solution^T",
        jvp_rule: "A^-1(right_tangent - coefficient_tangent solution)",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/solve.json",
        evidence_fixture_sha256: "fc3bc37cfb9a6e385572b70ae665a4e6ba71ac095cba0fa7b273e4270300a07a",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-8E3FD7459720",
        baseline_overload_id: "COMFY-TENSOR-OP-8E3FD7459720:blocked",
        baseline_fixture_sha256: "d81123fb02b8f9575c8d6a3866fb7b4f5b8b5326f6545924eeca4d2650a698d1",
        overload_id: "sim.native.tensor.linalg-vector-norm.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"order\",\"type\":\"f64\",\"default\":2,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Sequence<i64>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"keep_dimension\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn vector_norm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, order: f64, dimensions: &[i64], keep_dimension: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh reduced output",
        shape_rule: "one or more unique normalized dimensions removed or retained at extent one",
        dtype_rule: "F32 input/output and absent or F32 dtype override",
        accumulation_dtype: "F64 reduction workspace",
        layout_rule: "arbitrary readable view",
        device_rule: "CPU ordinal zero",
        numeric_rule: "fixed-order p, zero, and positive/negative infinity norms with NaN propagation",
        tolerance: "absolute 1e-6",
        determinism: "row-major reduction and equal-extremum tie split",
        cancellation_points: "before validation, bounded input traversal, before publication",
        vjp_rule: "analytic p-norm derivative with zero-norm convention and equal-extremum tie split",
        jvp_rule: "inner product of analytic derivative and input tangent",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/vector_norm.json",
        evidence_fixture_sha256: "d9360c86713f7255278803e6b4637c2b2d0122c85b6d327b8a725ebec36f7d9c",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-98D79FD6A7D2",
        baseline_overload_id: "COMFY-TENSOR-OP-98D79FD6A7D2:blocked",
        baseline_fixture_sha256: "3963b4cd0137f283c0d074ca30795a0698cc824c89eccbfaa3093c6ad4a6c9cd",
        overload_id: "sim.native.tensor.matmul.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"other\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn matmul_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh contiguous output",
        shape_rule: "PyTorch vector promotion/removal and right-aligned batch broadcasting",
        dtype_rule: "co-located F32",
        accumulation_dtype: "F64 workspace",
        layout_rule: "arbitrary readable views",
        device_rule: "CPU ordinal zero and one stream",
        numeric_rule: "fixed batch-row-column-inner contraction",
        tolerance: "absolute 1e-5",
        determinism: "row-major traversal",
        cancellation_points: "before validation, bounded output elements, before publication",
        vjp_rule: "transpose contractions with broadcast accumulation",
        jvp_rule: "input_tangent@other + input@other_tangent",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/matmul.json",
        evidence_fixture_sha256: "f19a34d0d6562684428e0521b1153e84e0874376d54e3b0ba7d14467d107d59f",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-277D4AF43E05",
        baseline_overload_id: "COMFY-TENSOR-OP-277D4AF43E05:blocked",
        baseline_fixture_sha256: "95626023b287daf198ef0f045fc581afe84448e36c510352f2fcf3eb1d4f101a",
        overload_id: "sim.native.tensor.mm.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32,rank=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"mat2\",\"type\":\"Tensor<F32,rank=2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn mm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, mat2: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh canonical matmul output",
        shape_rule: "rank-two [m,k] by [k,n] only",
        dtype_rule: "F32",
        accumulation_dtype: "canonical matmul F64 workspace",
        layout_rule: "canonical matmul views",
        device_rule: "co-located CPU ordinal zero",
        numeric_rule: "focused rank guard then canonical matmul owner",
        tolerance: "absolute 1e-5",
        determinism: "canonical matmul",
        cancellation_points: "before guard and canonical bounded checkpoints",
        vjp_rule: "canonical matmul VJP after rank guard",
        jvp_rule: "canonical matmul JVP after rank guard",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/mm.json",
        evidence_fixture_sha256: "e5bae91e11da6eaff3e7aa0f51970d3da562218380635cae1a2a635946fadda0",
    },
    ResolvedOperationContract {
        resolution_module: "linear_algebra_01",
        operation_id: "COMFY-TENSOR-OP-2F913F6635CB",
        baseline_overload_id: "COMFY-TENSOR-OP-2F913F6635CB:blocked",
        baseline_fixture_sha256: "09b24ab605e442a91abfb9f66465df7cdbf98f1b8fc12e3d8ca538b597234422",
        overload_id: "sim.native.tensor.tensordot.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"other\",\"type\":\"Tensor<F32>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_dimensions\",\"type\":\"Sequence<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"other_dimensions\",\"type\":\"Sequence<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<F32>\"]",
        rust_signature: "fn tensordot_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, input_dimensions: &[i64], other_dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, LinearAlgebraPartOneError>",
        mutation_rule: "read only",
        alias_rule: "fresh contiguous output",
        shape_rule: "uncontracted input dimensions followed by uncontracted other dimensions",
        dtype_rule: "co-located F32",
        accumulation_dtype: "F64 workspace",
        layout_rule: "arbitrary readable views",
        device_rule: "CPU ordinal zero and one stream",
        numeric_rule: "projects explicit axes into the canonical Einstein contraction owner",
        tolerance: "absolute 1e-5",
        determinism: "canonical contraction traversal",
        cancellation_points: "before validation, bounded contraction iterations, before publication",
        vjp_rule: "canonical contraction gradient for both operands",
        jvp_rule: "sum of the two tangent-substituted contractions",
        owner_task_id: "comfy-parity-tensor-ops-linear-algebra-comfy-tensor-op-061170cbb6f7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/linear_algebra_01/tensordot.json",
        evidence_fixture_sha256: "51e8e70269355307f1e547101e3eb5e115fbf799192b8b2e35c4095b16f1a882",
    },
]
