&[
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-D1F3FBA7CEDA",
        baseline_overload_id: "COMFY-TENSOR-OP-D1F3FBA7CEDA:blocked",
        baseline_fixture_sha256: "567378d429abca1355603452f3daff3b524b20c4e4a97498e50c083c6dcfb99f",
        overload_id: "zed.native.functional.cosine-similarity.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input_one\",\"type\":\"f32 tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_two\",\"type\":\"f32 tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"i64\",\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"epsilon\",\"type\":\"f32\",\"default\":1e-08,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"FunctionalTensor\"]",
        rust_signature: "fn cosine_similarity_with_context_exact_native(backend: &CpuBackend, input_one: &[f32], input_one_shape: &[usize], input_two: &[f32], input_two_shape: &[usize], dimension: i64, epsilon: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<FunctionalTensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "broadcast inputs then remove the selected dimension",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "row-major",
        device_rule: "CPU",
        numeric_rule: "canonical p=2 normalization followed by fixed-order dot reduction",
        tolerance: "1e-6",
        determinism: "row-major",
        cancellation_points: "before validation and bounded loops",
        vjp_rule: "canonical normalization VJPs plus broadcast reduction",
        jvp_rule: "canonical normalization JVPs plus product rule",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/cosine_similarity.json",
        evidence_fixture_sha256: "ca745667990d94d933cc5d9b1cc1cc4f18923561bee3d8eda8cdbedceb0ecc3f",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-47FEBAD36339",
        baseline_overload_id: "COMFY-TENSOR-OP-47FEBAD36339:blocked",
        baseline_fixture_sha256: "d8c1a93306030f79a2cb1cbf2b89f5bf56e0dfe34b45d19f833d643da2898abf",
        overload_id: "zed.native.functional.embedding.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"indices\",\"type\":\"Tensor<I64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"weight\",\"type\":\"mutable Tensor<F32,rank2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"options\",\"type\":\"EmbeddingOptions\",\"default\":\"PyTorch defaults\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn embedding_with_context_exact_native(backend: &CpuBackend, indices: &Tensor, weight: &mut Tensor, options: EmbeddingOptions, context: &ExecutionContext<'_>) -> Result<Tensor, NeuralNetworkFunctionalError>",
        mutation_rule: "max_norm atomically publishes renormalized weight",
        alias_rule: "fresh index-select output",
        shape_rule: "indices shape plus embedding width",
        dtype_rule: "I64 indices and F32 weight",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "co-located CPU stream",
        numeric_rule: "canonical index-select with checked row renormalization",
        tolerance: "bit exact selection; 1e-6 renormalization",
        determinism: "index order",
        cancellation_points: "before staging, bounded row scan, before publication",
        vjp_rule: "canonical index-select scatter-add with padding/frequency rules",
        jvp_rule: "canonical tangent index-select",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/embedding.json",
        evidence_fixture_sha256: "65b31b62949a5cbae1192f9bb6f4ceacddfc05bdcd3f26cc18eb7f113f3ca928",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-3D194029352B",
        baseline_overload_id: "COMFY-TENSOR-OP-3D194029352B:blocked",
        baseline_fixture_sha256: "020dc9498cee7a5ce958839e475ff2bec98ea7425ef0af6261119f03fb91603b",
        overload_id: "zed.native.functional.fold.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"F32[N,C*kH*kW,L]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_size\",\"type\":\"[usize;2]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"parameters\",\"type\":\"SpatialParameters2d\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"FunctionalTensor\"]",
        rust_signature: "fn fold_with_context_exact_native(backend: &CpuBackend, input: &[f32], input_shape: [usize; 3], output_size: [usize; 2], parameters: SpatialParameters2d, device: DeviceId, context: &ExecutionContext<'_>) -> Result<FunctionalTensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "checked col2im geometry",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "NCHW row-major",
        device_rule: "CPU",
        numeric_rule: "overlapping columns sum in fixed order",
        tolerance: "bit exact order",
        determinism: "batch-channel-kernel-block order",
        cancellation_points: "before and bounded loops",
        vjp_rule: "shared checked im2col geometry",
        jvp_rule: "same col2im transform",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/fold.json",
        evidence_fixture_sha256: "3949352b1966bdbeee449cf2db08244c258f2e7d2429ca08db174b25f8e4bffc",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-BEE0237BCAD2",
        baseline_overload_id: "COMFY-TENSOR-OP-BEE0237BCAD2:blocked",
        baseline_fixture_sha256: "fd8f43db22e9c148895bf0b6242a67fb6b93ea3e9f943585584ab5d363d518f0",
        overload_id: "zed.native.functional.glu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"F32 tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"i64\",\"default\":-1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"FunctionalTensor\"]",
        rust_signature: "fn glu_with_context_exact_native(backend: &CpuBackend, input: &[f32], input_shape: &[usize], dimension: i64, device: DeviceId, context: &ExecutionContext<'_>) -> Result<FunctionalTensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "selected even dimension is halved",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "row-major",
        device_rule: "CPU",
        numeric_rule: "first half times canonical sigmoid of second half",
        tolerance: "1e-6",
        determinism: "row-major",
        cancellation_points: "before and bounded loops",
        vjp_rule: "analytic product/sigmoid VJP",
        jvp_rule: "analytic product/sigmoid JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/glu.json",
        evidence_fixture_sha256: "5d55a76935c9beeb7af6f54c7b8ceffd8f51412e932d01521dc93b5449dfcea4",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-D1BCDE69E795",
        baseline_overload_id: "COMFY-TENSOR-OP-D1BCDE69E795:blocked",
        baseline_fixture_sha256: "d604cc654ca6214fa53b13909d7d09f63eb6b4b0fe84b6950652be4dc02053c7",
        overload_id: "zed.native.functional.linear.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"F32 tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"weight\",\"type\":\"F32[output,input]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"Option<F32[output]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"TensorValues\"]",
        rust_signature: "fn linear_with_context_exact_native(backend: &CpuBackend, input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "canonical linear owner",
        shape_rule: "last dimension contracts weight input",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "row-major",
        device_rule: "CPU",
        numeric_rule: "delegates canonical linear",
        tolerance: "canonical",
        determinism: "canonical",
        cancellation_points: "canonical",
        vjp_rule: "canonical linear VJP",
        jvp_rule: "canonical linear JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/linear.json",
        evidence_fixture_sha256: "ef3e90043de6b2297155343b37a035bd904440dacf3a07c010f2f88c401743a6",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-512C2ADE983A",
        baseline_overload_id: "COMFY-TENSOR-OP-512C2ADE983A:blocked",
        baseline_fixture_sha256: "9fdd5dc6912b735dfc5162f2e9950a3901b5f011ea24276a7f787728dfe29f7a",
        overload_id: "zed.native.functional.one-hot.cpu-i64.v1",
        ordered_parameters_json: "[{\"name\":\"indices\",\"type\":\"I64 tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"number_of_classes\",\"type\":\"i64\",\"default\":-1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"IntegerTensor\"]",
        rust_signature: "fn one_hot_with_context_exact_native(backend: &CpuBackend, indices: &[i64], indices_shape: &[usize], number_of_classes: i64, device: DeviceId, context: &ExecutionContext<'_>) -> Result<IntegerTensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "appends class dimension",
        dtype_rule: "I64",
        accumulation_dtype: "not applicable",
        layout_rule: "row-major",
        device_rule: "CPU",
        numeric_rule: "exact zero/one encoding",
        tolerance: "bit exact",
        determinism: "row-major",
        cancellation_points: "before and bounded loops",
        vjp_rule: "discrete non-differentiable indices",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/one_hot.json",
        evidence_fixture_sha256: "a2c1fd71d1aeffb4891d6f2743e8b88e8ee5ab46ecae1a2a202bbc0330912440",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-56789F9ED09B",
        baseline_overload_id: "COMFY-TENSOR-OP-56789F9ED09B:blocked",
        baseline_fixture_sha256: "60d0a1d42fab1bdbaac2903942082d3cf7840fcc355205a06b58223ffacac8bf",
        overload_id: "zed.native.functional.pixel-shuffle.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"upscale_factor\",\"type\":\"u64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn pixel_shuffle_with_context_exact_native(backend: &CpuBackend, input: &Tensor, upscale_factor: u64, context: &ExecutionContext<'_>) -> Result<Tensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "canonical rearrangement owner",
        shape_rule: "channels divide by factor squared; spatial dimensions multiply",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical rearrangement",
        device_rule: "CPU",
        numeric_rule: "bitwise permutation",
        tolerance: "bit exact",
        determinism: "canonical mapping",
        cancellation_points: "canonical",
        vjp_rule: "inverse canonical rearrangement",
        jvp_rule: "same canonical rearrangement",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/pixel_shuffle.json",
        evidence_fixture_sha256: "2054f928287892dcb71eecc72292358f255ddde7beb1634719933a777f152232",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-5D882CF77D16",
        baseline_overload_id: "COMFY-TENSOR-OP-5D882CF77D16:blocked",
        baseline_fixture_sha256: "b7bfa3fb30118d98a6626bf2af9c21b1268f2c6ca129ec265ad5c6ee64fd72fa",
        overload_id: "zed.native.functional.pixel-unshuffle.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"downscale_factor\",\"type\":\"u64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn pixel_unshuffle_with_context_exact_native(backend: &CpuBackend, input: &Tensor, downscale_factor: u64, context: &ExecutionContext<'_>) -> Result<Tensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "canonical rearrangement owner",
        shape_rule: "channels multiply by factor squared; spatial dimensions divide",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical rearrangement",
        device_rule: "CPU",
        numeric_rule: "bitwise permutation",
        tolerance: "bit exact",
        determinism: "canonical mapping",
        cancellation_points: "canonical",
        vjp_rule: "inverse canonical rearrangement",
        jvp_rule: "same canonical rearrangement",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/pixel_unshuffle.json",
        evidence_fixture_sha256: "149b1d3d89ac17c0186468b171bb2197a12883b9c91c886c5f786be7a65aa011",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-C6DD68C579DD",
        baseline_overload_id: "COMFY-TENSOR-OP-C6DD68C579DD:blocked",
        baseline_fixture_sha256: "2e8b259457d991cde314eb4366c4d48874bf4fe323e14dbc08fc66fc05842d23",
        overload_id: "zed.native.functional.scaled-dot-product-attention.v1",
        ordered_parameters_json: "[{\"name\":\"request\",\"type\":\"AttentionKernelRequest\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"query\",\"type\":\"F32 slice\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"key\",\"type\":\"F32 slice\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"value\",\"type\":\"F32 slice\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"mask\",\"type\":\"Option<AttentionMask>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn scaled_dot_product_attention_with_context_exact_native(backend: &CpuBackend, request: AttentionKernelRequest, query: &[f32], key: &[f32], value: &[f32], mask: Option<AttentionMask<'_>>, context: &ExecutionContext<'_>) -> Result<Vec<f32>, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "canonical attention owner",
        shape_rule: "canonical checked attention request",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "canonical",
        device_rule: "certified native request backend",
        numeric_rule: "delegates CheckedAttentionInvocation",
        tolerance: "canonical",
        determinism: "canonical",
        cancellation_points: "canonical tiles",
        vjp_rule: "canonical attention VJP",
        jvp_rule: "canonical attention JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/scaled_dot_product_attention.json",
        evidence_fixture_sha256: "5f109ef5502a26e3b1f06e5b15b77750bdb23142f37a12ec56c9f418a40141ce",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-5B08F2022527",
        baseline_overload_id: "COMFY-TENSOR-OP-5B08F2022527:blocked",
        baseline_fixture_sha256: "90dfb7a0b33d048304bb57133a4c35afba80503eb887c6f45d33ac6c54713577",
        overload_id: "zed.native.functional.sigmoid.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn sigmoid_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "canonical unary owner",
        shape_rule: "preserves shape",
        dtype_rule: "canonical real dtype preservation",
        accumulation_dtype: "F32 scalar kernel",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU",
        numeric_rule: "delegates UnaryOperation::Sigmoid",
        tolerance: "canonical",
        determinism: "canonical",
        cancellation_points: "canonical",
        vjp_rule: "canonical sigmoid VJP",
        jvp_rule: "canonical sigmoid JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/sigmoid.json",
        evidence_fixture_sha256: "95e6558f89ecf9f7ef8f1c673ad85f6f48941e373cf8df6bd6cc7313304237c6",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-13DF18F5F426",
        baseline_overload_id: "COMFY-TENSOR-OP-13DF18F5F426:blocked",
        baseline_fixture_sha256: "344c466a64a3302e72310c5616e4398dd2d97d04ed7a62fa84c5131e58f427cd",
        overload_id: "zed.native.functional.softplus.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"F32 slice\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"beta\",\"type\":\"f32\",\"default\":1.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"threshold\",\"type\":\"f32\",\"default\":20.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn softplus_with_context_exact_native(backend: &CpuBackend, input: &[f32], beta: f32, threshold: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "preserves element count",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical contiguous",
        device_rule: "CPU",
        numeric_rule: "threshold-stable ln1p(exp(beta*x))/beta",
        tolerance: "1e-6",
        determinism: "input order",
        cancellation_points: "before and bounded loop",
        vjp_rule: "threshold branch or canonical sigmoid derivative",
        jvp_rule: "same derivative times tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/softplus.json",
        evidence_fixture_sha256: "07791edbd64818b6956d3b93169d4e1f43cb28a57786646feee27035f2fcb54b",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-87C10166BCF5",
        baseline_overload_id: "COMFY-TENSOR-OP-87C10166BCF5:blocked",
        baseline_fixture_sha256: "253591cea73663b79d90855b909868d5a5ae461ef21eeb1b65c1a9a8b70dd13d",
        overload_id: "zed.native.functional.unfold.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"F32[N,C,H,W]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"parameters\",\"type\":\"SpatialParameters2d\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"FunctionalTensor\"]",
        rust_signature: "fn unfold_with_context_exact_native(backend: &CpuBackend, input: &[f32], input_shape: [usize; 4], parameters: SpatialParameters2d, device: DeviceId, context: &ExecutionContext<'_>) -> Result<FunctionalTensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh im2col output",
        shape_rule: "checked N,C*kH*kW,L geometry",
        dtype_rule: "F32",
        accumulation_dtype: "not applicable",
        layout_rule: "row-major columns",
        device_rule: "CPU",
        numeric_rule: "zero-padded checked im2col",
        tolerance: "bit exact",
        determinism: "batch-channel-kernel-block order",
        cancellation_points: "before and bounded loops",
        vjp_rule: "shared checked col2im geometry",
        jvp_rule: "same im2col transform",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/unfold.json",
        evidence_fixture_sha256: "f2008c892591d6581de23006d184f37d6e7222e6422e9e5398c8eca3bb092901",
    },
]
