&[
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-D60003AC2B14",
        baseline_overload_id: "COMFY-TENSOR-OP-D60003AC2B14:blocked",
        baseline_fixture_sha256: "a789220f22c71e2b82884f5a491e50429702ec524a67b270448009e4fd8adea0",
        overload_id: "zed.native.module.avg-pool-1d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"Option<usize>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn avg_pool_1d_module_exact_native(layer_name: impl Into<String>, kernel_size: usize, stride: Option<usize>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free pooling configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "CW or NCW pooling with checked canonical geometry",
        dtype_rule: "F32 canonical pooling",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel-first windows",
        device_rule: "CPU certified",
        numeric_rule: "extends Task 77 AveragePoolGeometry at one spatial dimension",
        tolerance: "bit exact",
        determinism: "batch channel output window then kernel order",
        cancellation_points: "before construction and at bounded output windows",
        vjp_rule: "scatter-adds through canonical pooling connections",
        jvp_rule: "pools tangents through canonical connections",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/avg_pool_1d.json",
        evidence_fixture_sha256: "268f9b33237ba8d61ca19f3eddb1f619b9786c8055f3b19812ddec9511ca71af",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-EE80ED2D81B0",
        baseline_overload_id: "COMFY-TENSOR-OP-EE80ED2D81B0:blocked",
        baseline_fixture_sha256: "dd6240eb06436885c52204f7d066fe564d194d9fa81053edde65fc67e767e6d8",
        overload_id: "zed.native.module.dropout.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"probability\",\"type\":\"f32\",\"default\":0.5,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn dropout_module_exact_native(layer_name: impl Into<String>, probability: f32, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "NativeModule owns training state; caller-owned RngTransaction is returned only after complete forward publication",
        alias_rule: "evaluation preserves the Tensor handle; training returns fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical mask application",
        accumulation_dtype: "F32",
        layout_rule: "logical input order",
        device_rule: "CPU certified",
        numeric_rule: "inverted dropout scales retained values by one over keep probability",
        tolerance: "bit exact for a fixed RNG profile",
        determinism: "canonical RngTransaction word order",
        cancellation_points: "before validation and at bounded element checkpoints; failure drops the uncommitted transaction",
        vjp_rule: "applies the saved forward mask and inverse keep scaling",
        jvp_rule: "applies the identical saved mask and scaling",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/dropout.json",
        evidence_fixture_sha256: "bc175b23e1aaf2eaef133bcc1aba25e7f205002c886dc9cba46ed249470ce483",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-F88B1E793668",
        baseline_overload_id: "COMFY-TENSOR-OP-F88B1E793668:blocked",
        baseline_fixture_sha256: "1e829565737d9d2c18f5d4f94757cd7ca87e19bfe8574786deff113b3f9aab12",
        overload_id: "zed.native.module.elu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"alpha\",\"type\":\"f32\",\"default\":1.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn elu_module_exact_native(layer_name: impl Into<String>, alpha: f32, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free configuration and rejects graph-visible in-place mutation",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical input order",
        device_rule: "CPU certified",
        numeric_rule: "delegates the canonical activation owner using x for positive values and alpha times expm1(x) otherwise",
        tolerance: "absolute 1e-6",
        determinism: "logical input order",
        cancellation_points: "before construction and bounded element checkpoints",
        vjp_rule: "uses derivative one above zero and alpha times exp(x) otherwise",
        jvp_rule: "applies the identical analytical derivative to tangents",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/elu.json",
        evidence_fixture_sha256: "b543ff297095ae3107f05c51306b5f79734cebd621c0d88064c64cd632a22c39",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-D8ED4EE63E27",
        baseline_overload_id: "COMFY-TENSOR-OP-D8ED4EE63E27:blocked",
        baseline_fixture_sha256: "aed6798f8b7c4a9a56925f2c37b7d609173bfa003d6aafac68f4a48f811ed102",
        overload_id: "zed.native.module.identity.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn identity_module_exact_native(layer_name: impl Into<String>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free canonical NativeModule",
        alias_rule: "forward returns the same canonical Tensor storage and descriptor handle",
        shape_rule: "preserves shape",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves layout and strides",
        device_rule: "preserves device",
        numeric_rule: "contains no numerical kernel",
        tolerance: "bit and identity exact",
        determinism: "structural identity",
        cancellation_points: "before construction and forward publication",
        vjp_rule: "identity",
        jvp_rule: "identity",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/identity.json",
        evidence_fixture_sha256: "9cc888f1727998bc8412fb6a494f3a8e0f763c6428ebd652e9f98ea8cc8e345a",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-FBA7DB6F71EB",
        baseline_overload_id: "COMFY-TENSOR-OP-FBA7DB6F71EB:blocked",
        baseline_fixture_sha256: "6f468c070d50fe943a0995a2c1a34fd268605bae746af8aa3f4c2da7b681c534",
        overload_id: "zed.native.module.mse-loss.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"reduction\",\"type\":\"LossReduction\",\"default\":\"mean\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn mse_loss_module_exact_native(layer_name: impl Into<String>, reduction: LossReduction, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free loss configuration in canonical NativeModule",
        alias_rule: "fresh scalar or elementwise output",
        shape_rule: "none preserves input shape; sum and mean return scalar",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major reduction",
        device_rule: "CPU certified",
        numeric_rule: "squared input-target difference with exact none sum or mean reduction",
        tolerance: "bit exact fixed reduction order",
        determinism: "logical input order",
        cancellation_points: "before construction and bounded reduction checkpoints",
        vjp_rule: "two times input-target with target negation and reduction scaling",
        jvp_rule: "two times input-target times tangent difference with reduction",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/mse_loss.json",
        evidence_fixture_sha256: "85933b32a807aa1b19db64900f4976bc44994b34b58295f81e90e76140875a90",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-EAF9D9989484",
        baseline_overload_id: "COMFY-TENSOR-OP-EAF9D9989484:blocked",
        baseline_fixture_sha256: "167a48aad2bbe5f0c8c17114f91873e9ce1b7879c24775c8cdac7db1515481ce",
        overload_id: "zed.native.module.base.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn module_exact_native(layer_name: impl Into<String>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs the canonical empty NativeModule lifecycle owner",
        alias_rule: "owns no input or output tensor",
        shape_rule: "base module defines no forward shape",
        dtype_rule: "base module defines no independent dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "stable child insertion order",
        device_rule: "delegates child rules",
        numeric_rule: "contains no numerical kernel",
        tolerance: "structural",
        determinism: "stable lifecycle transitions",
        cancellation_points: "before and after construction",
        vjp_rule: "base module defines no derivative kernel",
        jvp_rule: "base module defines no derivative kernel",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/module.json",
        evidence_fixture_sha256: "aadd5cd9ae62272517df333c7263e31a5528ab35dc2ef4ed7f495c5d3ea1ce78",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-E1CEBEBBCBFE",
        baseline_overload_id: "COMFY-TENSOR-OP-E1CEBEBBCBFE:blocked",
        baseline_fixture_sha256: "548730cb566c0b2a2272320857318cbd145a4c75ac734a83202d2b80750780ca",
        overload_id: "zed.native.module.sigmoid.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn sigmoid_module_exact_native(layer_name: impl Into<String>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "delegates canonical Tensor sigmoid dtype rules",
        accumulation_dtype: "canonical Tensor sigmoid",
        layout_rule: "canonical Tensor traversal",
        device_rule: "canonical certified backend matrix",
        numeric_rule: "delegates Task 50 canonical sigmoid",
        tolerance: "canonical sigmoid tolerance",
        determinism: "canonical Tensor traversal",
        cancellation_points: "before construction and canonical kernel checkpoints",
        vjp_rule: "delegates canonical sigmoid analytical VJP",
        jvp_rule: "delegates canonical sigmoid analytical JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/sigmoid.json",
        evidence_fixture_sha256: "fe398bf22ed8d6c526d223030931156e227563cf23c613fb56d2bc639d6ebce2",
    },
]
