&[
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-378824FF198F",
        baseline_overload_id: "COMFY-TENSOR-OP-378824FF198F:blocked",
        baseline_fixture_sha256: "fa8e05726b0bf267a1483252c8772586001922466156c5d6f9d643a650f6009f",
        overload_id: "zed.native.module.average-pool-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"[usize;2]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"Option<[usize;2]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn average_pool_2d_module_exact_native(layer_name: impl Into<String>, kernel_size: [usize;2], stride: Option<[usize;2]>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs checked canonical module state",
        alias_rule: "fresh module; forward publishes fresh output",
        shape_rule: "CHW or NCHW floor pooling without padding",
        dtype_rule: "F32 module execution",
        accumulation_dtype: "F32",
        layout_rule: "row-major NCHW",
        device_rule: "CPU",
        numeric_rule: "fixed-order arithmetic mean per window",
        tolerance: "bit exact order",
        determinism: "batch-channel-window order",
        cancellation_points: "before and after construction; bounded forward windows",
        vjp_rule: "scatter upstream equally across each window",
        jvp_rule: "same average-pool transform on tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/average_pool_2d.json",
        evidence_fixture_sha256: "0243c457082daa84817a27f1acd7ddb8137cfab77c5fca02ca1cecee151cdd15",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-2B09E55DCFFA",
        baseline_overload_id: "COMFY-TENSOR-OP-2B09E55DCFFA:blocked",
        baseline_fixture_sha256: "8d06a2e25951d540cff113f901f06b1090df3444336726f252e087debfd9c802",
        overload_id: "zed.native.module.buffer.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"tensor\",\"type\":\"Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn buffer_module_exact_native(layer_name: impl Into<String>, tensor: Tensor, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "registers immutable tensor handle in canonical module state",
        alias_rule: "registered handle aliases supplied tensor storage",
        shape_rule: "preserves descriptor exactly",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves strides and offset",
        device_rule: "preserves device",
        numeric_rule: "no numeric transform",
        tolerance: "bit exact",
        determinism: "identity registration",
        cancellation_points: "before and after registration",
        vjp_rule: "buffer registration is state-only and has no forward edge",
        jvp_rule: "buffer registration is state-only and has no forward edge",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/buffer.json",
        evidence_fixture_sha256: "4b440babb936e9e707cccf80f8bd49de001b718ab1339bb0b8de0ad5f45452f5",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-5B3DCD30FC9C",
        baseline_overload_id: "COMFY-TENSOR-OP-5B3DCD30FC9C:blocked",
        baseline_fixture_sha256: "4fb2f7dea0b58269b0a0911c6e3a445a9ae7e8edd6b2c2c85cc99e514c13c02e",
        overload_id: "zed.native.module.conv1d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"usize\",\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"usize\",\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dilation\",\"type\":\"usize\",\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"groups\",\"type\":\"usize\",\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn conv1d_module_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_size: usize, stride: usize, padding: usize, dilation: usize, groups: usize, bias: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs unloaded canonical parameter owner",
        alias_rule: "fresh module and forward output",
        shape_rule: "canonical grouped one-dimensional convolution geometry",
        dtype_rule: "loaded floating dtype with checked compute cast",
        accumulation_dtype: "F32 canonical path",
        layout_rule: "row-major NCW",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical convolution owner",
        tolerance: "canonical convolution tolerance",
        determinism: "canonical connection order",
        cancellation_points: "before and after construction; canonical forward checkpoints",
        vjp_rule: "delegates canonical convolution VJP",
        jvp_rule: "delegates canonical convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/conv1d.json",
        evidence_fixture_sha256: "4865812809b8b488059805f9735ffcd90a776f2eb00877cb420b14371abb41f5",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-4029AD87847D",
        baseline_overload_id: "COMFY-TENSOR-OP-4029AD87847D:blocked",
        baseline_fixture_sha256: "55d63d36d3de47a7e9455d680fb6b0601a40a6c03d7b7cd2afba9ff6a3fd4f53",
        overload_id: "zed.native.module.group-norm.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"groups\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"epsilon\",\"type\":\"f32\",\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"affine\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn group_norm_module_exact_native(layer_name: impl Into<String>, groups: usize, channels: usize, epsilon: f32, affine: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs canonical affine parameter owner",
        alias_rule: "fresh module and output",
        shape_rule: "preserves shape and groups channel axis one",
        dtype_rule: "F32 canonical normalization",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical group-normalization owner",
        tolerance: "1e-5",
        determinism: "group element order",
        cancellation_points: "before construction and canonical reductions",
        vjp_rule: "delegates canonical affine VJP",
        jvp_rule: "delegates canonical affine JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/group_norm.json",
        evidence_fixture_sha256: "c0a773ae4b87d504db88a8ee7f21246d09a46bdcb9a279d6a59bb12ea463f20a",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-36234382A497",
        baseline_overload_id: "COMFY-TENSOR-OP-36234382A497:blocked",
        baseline_fixture_sha256: "0f28ece6cc9d81ccc6ea6b1b898abde914dcbe9a30871d54fb88d7a21bdcf020",
        overload_id: "zed.native.module.layer-norm.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"normalized_shape\",\"type\":\"Vec<usize>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"epsilon\",\"type\":\"f32\",\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"elementwise_affine\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn layer_norm_module_exact_native(layer_name: impl Into<String>, normalized_shape: Vec<usize>, epsilon: f32, elementwise_affine: bool, bias: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs canonical affine parameter owner",
        alias_rule: "fresh module and output",
        shape_rule: "preserves input with checked normalized suffix",
        dtype_rule: "F32 canonical normalization",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical layer-normalization owner",
        tolerance: "1e-5",
        determinism: "normalized suffix order",
        cancellation_points: "before construction and canonical reductions",
        vjp_rule: "delegates canonical affine VJP",
        jvp_rule: "delegates canonical affine JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/layer_norm.json",
        evidence_fixture_sha256: "e7950b36ee2b64f6bc80790eb2b87ee68ebf0fc561e5cada1e308e5711abf7d6",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-5A7C1AC03892",
        baseline_overload_id: "COMFY-TENSOR-OP-5A7C1AC03892:blocked",
        baseline_fixture_sha256: "1c51d120ca69a8c5182ce9f49ec9df3e47c34d8318bc34d3439b3663e2a360d1",
        overload_id: "zed.native.module.prelu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"num_parameters\",\"type\":\"usize\",\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn prelu_module_exact_native(layer_name: impl Into<String>, num_parameters: usize, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs canonical weight parameter owner",
        alias_rule: "fresh module and output",
        shape_rule: "scalar or channel-axis weight broadcasting",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major",
        device_rule: "CPU certified",
        numeric_rule: "positive identity; nonpositive input times channel weight",
        tolerance: "bit exact arithmetic order",
        determinism: "logical input order",
        cancellation_points: "before construction and bounded forward loop",
        vjp_rule: "analytic input slope and channel weight reduction",
        jvp_rule: "analytic product rule on negative branch",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/prelu.json",
        evidence_fixture_sha256: "fc3f61d14c3abdc57fec92075c5605404f01f2e687fa265cb2c3950a6fd880d9",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-163D5E4B774E",
        baseline_overload_id: "COMFY-TENSOR-OP-163D5E4B774E:blocked",
        baseline_fixture_sha256: "b46a9d5282184312ec161352b437b82d28851c07296fd1871ef39ae99f5300ea",
        overload_id: "zed.native.module.sequential.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"children\",\"type\":\"Vec<NativeModule>\",\"default\":null,\"keyword_only\":false,\"kind\":\"variadic_positional\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn sequential_module_exact_native(layer_name: impl Into<String>, children: Vec<NativeModule>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "stages child states and atomically publishes all successful transitions",
        alias_rule: "empty sequence returns input handle; nonempty follows child rules",
        shape_rule: "composes checked child output descriptors in order",
        dtype_rule: "composes child dtype rules",
        accumulation_dtype: "composes child rules",
        layout_rule: "composes child layout rules",
        device_rule: "all children execute on canonical native backends",
        numeric_rule: "strict child insertion order",
        tolerance: "composition of child tolerances",
        determinism: "child order then child kernel order",
        cancellation_points: "before each child and before atomic child-state publication",
        vjp_rule: "the container adds no derivative kernel; autograd records canonical child operations for reverse traversal",
        jvp_rule: "the container adds no derivative kernel; canonical child JVPs compose in forward order",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/sequential.json",
        evidence_fixture_sha256: "b2b268fad1adc63f8cbfb8c80e53b54f45ef4201ee147237c54d346920c6d416",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-46DAF04A6B91",
        baseline_overload_id: "COMFY-TENSOR-OP-46DAF04A6B91:blocked",
        baseline_fixture_sha256: "42eab519c00f221b00ffaaf41a304b3a9c3f75996297d104f2ad4625b2edabaa",
        overload_id: "zed.native.module.silu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn silu_module_exact_native(layer_name: impl Into<String>, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "out of place; in-place construction fails closed",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical x times sigmoid x owner",
        tolerance: "1e-6",
        determinism: "logical input order",
        cancellation_points: "before construction and canonical element loop",
        vjp_rule: "delegates canonical analytic SiLU VJP",
        jvp_rule: "delegates canonical analytic SiLU JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/silu.json",
        evidence_fixture_sha256: "6081bbb642952d22a612000a8a8e35b2d5b38455c3f8c8f538304b70bb5782b0",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-0E92B0EA1CF0",
        baseline_overload_id: "COMFY-TENSOR-OP-0E92B0EA1CF0:blocked",
        baseline_fixture_sha256: "c2d955c7eaaca76df40e9343a315c14ac238c800ab43da15eb77a9a84ec4e315",
        overload_id: "zed.native.module.smooth-l1-loss.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"beta\",\"type\":\"f32\",\"default\":1.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"reduction\",\"type\":\"LossReduction\",\"default\":\"mean\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn smooth_l1_loss_module_exact_native(layer_name: impl Into<String>, beta: f32, reduction: LossReduction, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free loss module; forward is out of place",
        alias_rule: "fresh scalar or elementwise output",
        shape_rule: "none preserves input; sum and mean return scalar",
        dtype_rule: "F32",
        accumulation_dtype: "F32 fixed order",
        layout_rule: "logical row-major",
        device_rule: "CPU certified",
        numeric_rule: "quadratic inside beta and L1 outside",
        tolerance: "1e-6",
        determinism: "logical input reduction order",
        cancellation_points: "before construction and bounded loss loop",
        vjp_rule: "piecewise difference derivative with reduction scale",
        jvp_rule: "piecewise derivative times input-minus-target tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/smooth_l1_loss.json",
        evidence_fixture_sha256: "487e5de5320cfc28c7e3ced41848afcfcc4af94cb9a55a04021ce466139c7d4b",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-0E602E58360A",
        baseline_overload_id: "COMFY-TENSOR-OP-0E602E58360A:blocked",
        baseline_fixture_sha256: "86cc8a56d310b986f78f20f15905a06096905d0835abeb86ad6b716eb63e88fc",
        overload_id: "zed.native.module.softmax.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"isize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn softmax_module_exact_native(layer_name: impl Into<String>, dimension: isize, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free module; forward is out of place",
        alias_rule: "fresh output",
        shape_rule: "preserves shape and normalizes selected axis",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical max-shifted exponential normalization",
        tolerance: "1e-6",
        determinism: "axis order",
        cancellation_points: "before construction and canonical reductions",
        vjp_rule: "delegates canonical softmax Jacobian-vector product",
        jvp_rule: "delegates canonical softmax linearization",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/softmax.json",
        evidence_fixture_sha256: "6850bbdbdabbc8bcee3f525d79babab7a5dcde5884b4f1019ac3e481f391a699",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-1FDC96D7E7C2",
        baseline_overload_id: "COMFY-TENSOR-OP-1FDC96D7E7C2:blocked",
        baseline_fixture_sha256: "9fc8cfb820a266bfc8d01ae1e643a92720980fed4aa6ad507001c0537c4dcb22",
        overload_id: "zed.native.module.tanh.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn tanh_module_exact_native(layer_name: impl Into<String>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free module; forward is out of place",
        alias_rule: "fresh output",
        shape_rule: "preserves descriptor",
        dtype_rule: "F32 canonical tensor activation",
        accumulation_dtype: "F32",
        layout_rule: "canonical tensor traversal",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical hyperbolic tangent owner",
        tolerance: "1e-6",
        determinism: "canonical logical order",
        cancellation_points: "before construction and canonical tensor dispatch",
        vjp_rule: "delegates canonical one-minus-tanh-squared VJP",
        jvp_rule: "delegates canonical one-minus-tanh-squared JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/tanh.json",
        evidence_fixture_sha256: "8fc63745e062f9370fc43cfd8f07daa1b13e3129c5c476885887093a09c2d196",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_01",
        operation_id: "COMFY-TENSOR-OP-3F14ADC9E576",
        baseline_overload_id: "COMFY-TENSOR-OP-3F14ADC9E576:blocked",
        baseline_fixture_sha256: "0486d9b28412ad502baaf0e1144f748685330cd16f35325e79aa4393701194db",
        overload_id: "zed.native.module.upsample.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"scale_factor\",\"type\":\"[f64;2]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"mode\",\"type\":\"UpsampleMode\",\"default\":\"nearest\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"align_corners\",\"type\":\"Option<bool>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn upsample_module_exact_native(layer_name: impl Into<String>, scale_factor: [f64;2], mode: UpsampleMode, align_corners: Option<bool>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free module; forward is out of place",
        alias_rule: "fresh output",
        shape_rule: "floors positive scaled height and width",
        dtype_rule: "preserves canonical resize dtype",
        accumulation_dtype: "F32 interpolation",
        layout_rule: "canonical resize layout",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical nearest-exact or bilinear coordinates including aligned corners",
        tolerance: "1e-6 bilinear; bit exact nearest",
        determinism: "canonical output pixel order",
        cancellation_points: "before construction and canonical resize tiles",
        vjp_rule: "reverse scatter through the selected interpolation weights",
        jvp_rule: "same interpolation transform on tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-0e602e58360a",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_01/upsample.json",
        evidence_fixture_sha256: "05ef11cd9579fb07cd961231e1d390f6432d34d0e29a919d6abc0d39a0d0ebe7",
    },
]
