&[
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-D1F3FBA7CEDA",
        baseline_overload_id: "COMFY-TENSOR-OP-D1F3FBA7CEDA:blocked",
        baseline_fixture_sha256: "666bc641280a29cea873491d200ba7a619a08440fbb51a06489dd9c38c958681",
        overload_id: "sim.native.functional.cosine-similarity.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input_one\",\"type\":\"f32 tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_two\",\"type\":\"f32 tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"i64\",\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"epsilon\",\"type\":\"f32\",\"default\":1e-08,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"FunctionalTensor\"]",
        rust_signature: "fn cosine_similarity_with_context_exact_native(backend: &CpuBackend, input_one: &[f32], input_one_shape: &[usize], input_two: &[f32], input_two_shape: &[usize], dimension: i64, epsilon: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<FunctionalTensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "broadcast inputs then remove the selected dimension",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "row-major",
        device_rule: "CPU",
        numeric_rule: "canonical p=2 normalization followed by fixed-order dot reduction",
        tolerance: "1e-6",
        determinism: "row-major",
        cancellation_points: "before validation and bounded loops",
        vjp_rule: "canonical normalization VJPs plus broadcast reduction",
        jvp_rule: "canonical normalization JVPs plus product rule",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/cosine_similarity.json",
        evidence_fixture_sha256: "dd988e7c835faf22c1646b464008e293ea7e7b2063b6e3008a20b59017881697",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-47FEBAD36339",
        baseline_overload_id: "COMFY-TENSOR-OP-47FEBAD36339:blocked",
        baseline_fixture_sha256: "d7099f7fe03471de998c81dae724455ccb6d5ac4388e15b099ecc6bc2a4f4d46",
        overload_id: "sim.native.functional.embedding.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"indices\",\"type\":\"Tensor<I64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"weight\",\"type\":\"mutable Tensor<F32,rank2>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"options\",\"type\":\"EmbeddingOptions\",\"default\":\"PyTorch defaults\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn embedding_with_context_exact_native(backend: &CpuBackend, indices: &Tensor, weight: &mut Tensor, options: EmbeddingOptions, context: &ExecutionContext<'_>) -> Result<Tensor, NeuralNetworkFunctionalError>",
        mutation_rule: "max_norm atomically publishes renormalized weight",
        alias_rule: "fresh index-select output",
        shape_rule: "indices shape plus embedding width",
        dtype_rule: "I64 indices and F32 weight",
        accumulation_dtype: "F32",
        layout_rule: "contiguous output",
        device_rule: "co-located CPU stream",
        numeric_rule: "canonical index-select with checked row renormalization",
        tolerance: "bit exact selection; 1e-6 renormalization",
        determinism: "index order",
        cancellation_points: "before staging, bounded row scan, before publication",
        vjp_rule: "canonical index-select scatter-add with padding/frequency rules",
        jvp_rule: "canonical tangent index-select",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/embedding.json",
        evidence_fixture_sha256: "272b0bae891727197a5411fe59166838542d838a62cdae6651b95026bd693b83",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-3D194029352B",
        baseline_overload_id: "COMFY-TENSOR-OP-3D194029352B:blocked",
        baseline_fixture_sha256: "fe46341f174b55abb4de643acf1b9e21753d0adef651ca497ccee319044fe1b5",
        overload_id: "sim.native.functional.fold.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"F32[N,C*kH*kW,L]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_size\",\"type\":\"[usize;2]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"parameters\",\"type\":\"SpatialParameters2d\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"FunctionalTensor\"]",
        rust_signature: "fn fold_with_context_exact_native(backend: &CpuBackend, input: &[f32], input_shape: [usize; 3], output_size: [usize; 2], parameters: SpatialParameters2d, device: DeviceId, context: &ExecutionContext<'_>) -> Result<FunctionalTensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "checked col2im geometry",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "NCHW row-major",
        device_rule: "CPU",
        numeric_rule: "overlapping columns sum in fixed order",
        tolerance: "bit exact order",
        determinism: "batch-channel-kernel-block order",
        cancellation_points: "before and bounded loops",
        vjp_rule: "shared checked im2col geometry",
        jvp_rule: "same col2im transform",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/fold.json",
        evidence_fixture_sha256: "0300a29840f084c76335c05ea67cca49002da9f946f2262c71b033d70bb0a605",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-BEE0237BCAD2",
        baseline_overload_id: "COMFY-TENSOR-OP-BEE0237BCAD2:blocked",
        baseline_fixture_sha256: "ff54299627beb70f554a4884877c6b73a81d1447fe143e515be71e2ef349ca96",
        overload_id: "sim.native.functional.glu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"F32 tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"i64\",\"default\":-1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"FunctionalTensor\"]",
        rust_signature: "fn glu_with_context_exact_native(backend: &CpuBackend, input: &[f32], input_shape: &[usize], dimension: i64, device: DeviceId, context: &ExecutionContext<'_>) -> Result<FunctionalTensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "selected even dimension is halved",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "row-major",
        device_rule: "CPU",
        numeric_rule: "first half times canonical sigmoid of second half",
        tolerance: "1e-6",
        determinism: "row-major",
        cancellation_points: "before and bounded loops",
        vjp_rule: "analytic product/sigmoid VJP",
        jvp_rule: "analytic product/sigmoid JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/glu.json",
        evidence_fixture_sha256: "b5607fc5b33f4b7128707c2f7c41c6ed0469f348dc20d66636b3445dcfc2d85b",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-D1BCDE69E795",
        baseline_overload_id: "COMFY-TENSOR-OP-D1BCDE69E795:blocked",
        baseline_fixture_sha256: "75011918072a5c08a2e7da477d6f9e649c8aa0f6e0cc1792e4aa4b37b938edb7",
        overload_id: "sim.native.functional.linear.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"F32 tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"weight\",\"type\":\"F32[output,input]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"Option<F32[output]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"TensorValues\"]",
        rust_signature: "fn linear_with_context_exact_native(backend: &CpuBackend, input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "canonical linear owner",
        shape_rule: "last dimension contracts weight input",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "row-major",
        device_rule: "CPU",
        numeric_rule: "delegates canonical linear",
        tolerance: "canonical",
        determinism: "canonical",
        cancellation_points: "canonical",
        vjp_rule: "canonical linear VJP",
        jvp_rule: "canonical linear JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/linear.json",
        evidence_fixture_sha256: "ac0008738bd61c8339684eb72479cd6380501d33d4428fcf81d8eba95899946a",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-512C2ADE983A",
        baseline_overload_id: "COMFY-TENSOR-OP-512C2ADE983A:blocked",
        baseline_fixture_sha256: "9bbd5db7aeb3929c81c319777c68b82bf45cc50869bddc9f748e105f348a4795",
        overload_id: "sim.native.functional.one-hot.cpu-i64.v1",
        ordered_parameters_json: "[{\"name\":\"indices\",\"type\":\"I64 tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"number_of_classes\",\"type\":\"i64\",\"default\":-1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"IntegerTensor\"]",
        rust_signature: "fn one_hot_with_context_exact_native(backend: &CpuBackend, indices: &[i64], indices_shape: &[usize], number_of_classes: i64, device: DeviceId, context: &ExecutionContext<'_>) -> Result<IntegerTensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "appends class dimension",
        dtype_rule: "I64",
        accumulation_dtype: "not applicable",
        layout_rule: "row-major",
        device_rule: "CPU",
        numeric_rule: "exact zero/one encoding",
        tolerance: "bit exact",
        determinism: "row-major",
        cancellation_points: "before and bounded loops",
        vjp_rule: "discrete non-differentiable indices",
        jvp_rule: "no tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/one_hot.json",
        evidence_fixture_sha256: "912b1f18bfd0314529f1747778c53e5120b2ed28c208adb3be1917a9536a8415",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-56789F9ED09B",
        baseline_overload_id: "COMFY-TENSOR-OP-56789F9ED09B:blocked",
        baseline_fixture_sha256: "330700b3a75dbe1165c2f5dc883e58231e40c0bea9d7b71a8a0f77aa64801da3",
        overload_id: "sim.native.functional.pixel-shuffle.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"upscale_factor\",\"type\":\"u64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn pixel_shuffle_with_context_exact_native(backend: &CpuBackend, input: &Tensor, upscale_factor: u64, context: &ExecutionContext<'_>) -> Result<Tensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "canonical rearrangement owner",
        shape_rule: "channels divide by factor squared; spatial dimensions multiply",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical rearrangement",
        device_rule: "CPU",
        numeric_rule: "bitwise permutation",
        tolerance: "bit exact",
        determinism: "canonical mapping",
        cancellation_points: "canonical",
        vjp_rule: "inverse canonical rearrangement",
        jvp_rule: "same canonical rearrangement",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/pixel_shuffle.json",
        evidence_fixture_sha256: "d4d866afbd7408c4ddf90e510af210eeaab118c2e85456e6ab31e99265d19ae9",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-5D882CF77D16",
        baseline_overload_id: "COMFY-TENSOR-OP-5D882CF77D16:blocked",
        baseline_fixture_sha256: "85f141875614047358c468ea30cccaca325798cbe8302a4b35b6cdfaf79cc411",
        overload_id: "sim.native.functional.pixel-unshuffle.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"downscale_factor\",\"type\":\"u64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn pixel_unshuffle_with_context_exact_native(backend: &CpuBackend, input: &Tensor, downscale_factor: u64, context: &ExecutionContext<'_>) -> Result<Tensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "canonical rearrangement owner",
        shape_rule: "channels multiply by factor squared; spatial dimensions divide",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical rearrangement",
        device_rule: "CPU",
        numeric_rule: "bitwise permutation",
        tolerance: "bit exact",
        determinism: "canonical mapping",
        cancellation_points: "canonical",
        vjp_rule: "inverse canonical rearrangement",
        jvp_rule: "same canonical rearrangement",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/pixel_unshuffle.json",
        evidence_fixture_sha256: "fa9ff14ad5b3a3a7610a8f2061e302594dedc9c4603dc334ded5711c60984803",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-C6DD68C579DD",
        baseline_overload_id: "COMFY-TENSOR-OP-C6DD68C579DD:blocked",
        baseline_fixture_sha256: "e27e767dcd8c9be371284e865cf8a64f504b2257886e085366d1f559298317c7",
        overload_id: "sim.native.functional.scaled-dot-product-attention.v1",
        ordered_parameters_json: "[{\"name\":\"request\",\"type\":\"AttentionKernelRequest\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"query\",\"type\":\"F32 slice\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"key\",\"type\":\"F32 slice\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"value\",\"type\":\"F32 slice\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"mask\",\"type\":\"Option<AttentionMask>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn scaled_dot_product_attention_with_context_exact_native(backend: &CpuBackend, request: AttentionKernelRequest, query: &[f32], key: &[f32], value: &[f32], mask: Option<AttentionMask<'_>>, context: &ExecutionContext<'_>) -> Result<Vec<f32>, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "canonical attention owner",
        shape_rule: "canonical checked attention request",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "canonical",
        device_rule: "certified native request backend",
        numeric_rule: "delegates CheckedAttentionInvocation",
        tolerance: "canonical",
        determinism: "canonical",
        cancellation_points: "canonical tiles",
        vjp_rule: "canonical attention VJP",
        jvp_rule: "canonical attention JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/scaled_dot_product_attention.json",
        evidence_fixture_sha256: "65dc81e0d72414efdf3e448a945d6e57754a6faa2795710d11a900ff1fb67d9c",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-5B08F2022527",
        baseline_overload_id: "COMFY-TENSOR-OP-5B08F2022527:blocked",
        baseline_fixture_sha256: "394a687c782570f544ee5713cd79d418306b956b1182ceb07ad80ba4aebf2d70",
        overload_id: "sim.native.functional.sigmoid.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn sigmoid_with_context_exact_native(backend: &CpuBackend, input: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "canonical unary owner",
        shape_rule: "preserves shape",
        dtype_rule: "canonical real dtype preservation",
        accumulation_dtype: "F32 scalar kernel",
        layout_rule: "canonical contiguous output",
        device_rule: "CPU",
        numeric_rule: "delegates UnaryOperation::Sigmoid",
        tolerance: "canonical",
        determinism: "canonical",
        cancellation_points: "canonical",
        vjp_rule: "canonical sigmoid VJP",
        jvp_rule: "canonical sigmoid JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/sigmoid.json",
        evidence_fixture_sha256: "93d2b7846e38e64a40a9a9ea7c5474d8e3c14254d451468b0482fb41523a78ad",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-13DF18F5F426",
        baseline_overload_id: "COMFY-TENSOR-OP-13DF18F5F426:blocked",
        baseline_fixture_sha256: "6f7fe9f7096ee78e840da0578487688252d9ba5bc338cb8eb8f7447097ac29c8",
        overload_id: "sim.native.functional.softplus.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"F32 slice\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"beta\",\"type\":\"f32\",\"default\":1.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"threshold\",\"type\":\"f32\",\"default\":20.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Vec<f32>\"]",
        rust_signature: "fn softplus_with_context_exact_native(backend: &CpuBackend, input: &[f32], beta: f32, threshold: f32, device: DeviceId, context: &ExecutionContext<'_>) -> Result<Vec<f32>, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh output",
        shape_rule: "preserves element count",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical contiguous",
        device_rule: "CPU",
        numeric_rule: "threshold-stable ln1p(exp(beta*x))/beta",
        tolerance: "1e-6",
        determinism: "input order",
        cancellation_points: "before and bounded loop",
        vjp_rule: "threshold branch or canonical sigmoid derivative",
        jvp_rule: "same derivative times tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/softplus.json",
        evidence_fixture_sha256: "2e51226894c97051ad6eaa553ca0c5884be0a69579775710c546df5566d22db3",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_functional_01",
        operation_id: "COMFY-TENSOR-OP-87C10166BCF5",
        baseline_overload_id: "COMFY-TENSOR-OP-87C10166BCF5:blocked",
        baseline_fixture_sha256: "6bd8155c44e9719f57d187b3d5ab85aa9133be0c85c6a61a59f7c9c49b7ec3ad",
        overload_id: "sim.native.functional.unfold.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"F32[N,C,H,W]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"parameters\",\"type\":\"SpatialParameters2d\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"FunctionalTensor\"]",
        rust_signature: "fn unfold_with_context_exact_native(backend: &CpuBackend, input: &[f32], input_shape: [usize; 4], parameters: SpatialParameters2d, device: DeviceId, context: &ExecutionContext<'_>) -> Result<FunctionalTensor, NeuralNetworkFunctionalError>",
        mutation_rule: "out of place",
        alias_rule: "fresh im2col output",
        shape_rule: "checked N,C*kH*kW,L geometry",
        dtype_rule: "F32",
        accumulation_dtype: "not applicable",
        layout_rule: "row-major columns",
        device_rule: "CPU",
        numeric_rule: "zero-padded checked im2col",
        tolerance: "bit exact",
        determinism: "batch-channel-kernel-block order",
        cancellation_points: "before and bounded loops",
        vjp_rule: "shared checked col2im geometry",
        jvp_rule: "same im2col transform",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-functional-comfy-tensor-op-13df18f5f426",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_functional_01/unfold.json",
        evidence_fixture_sha256: "70987005fc0c2fa1a81ccf4327167f420ffdaa648bd6f9d40ceb80961c79727b",
    },
]
