&[
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-C76DE8CF2CF0",
        baseline_overload_id: "COMFY-TENSOR-OP-C76DE8CF2CF0:blocked",
        baseline_fixture_sha256: "cb4b7ef15d9a024e6072ba5624825d816ea1336b2863d98ded3c07e6a896ecda",
        overload_id: "zed.native.module.conv-3d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"[usize;3]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"[usize;3]\",\"default\":[1,1,1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"[usize;3]\",\"default\":[0,0,0],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dilation\",\"type\":\"[usize;3]\",\"default\":[1,1,1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"groups\",\"type\":\"usize\",\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn conv_3d_module_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_size: [usize;3], stride: [usize;3], padding: [usize;3], dilation: [usize;3], groups: usize, bias: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs an unloaded adapter in the canonical NativeModule parameter lifecycle",
        alias_rule: "fresh module and fresh forward output",
        shape_rule: "canonical grouped NCDHW three-dimensional convolution geometry",
        dtype_rule: "loaded floating dtype with checked F32 compute cast",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major NCDHW",
        device_rule: "CPU certified",
        numeric_rule: "delegates the canonical rank-generic convolution owner",
        tolerance: "canonical convolution tolerance",
        determinism: "canonical connection order",
        cancellation_points: "before construction and canonical kernel checkpoints",
        vjp_rule: "delegates canonical convolution VJP",
        jvp_rule: "delegates canonical convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/conv_3d.json",
        evidence_fixture_sha256: "8d4c7b4249e63ccde642b20a85876afe00fed319720dc9237acff9ce0a0099d7",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-96DE512D2417",
        baseline_overload_id: "COMFY-TENSOR-OP-96DE512D2417:blocked",
        baseline_fixture_sha256: "1ee2a801b41639e8193ba9ee2abc6c6aa500019f7cf4180150dc2f26cd021d3c",
        overload_id: "zed.native.module.gelu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"approximation\",\"type\":\"GeluApproximation\",\"default\":\"none\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn gelu_module_exact_native(layer_name: impl Into<String>, approximation: GeluApproximation, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical input order",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical exact or tanh GELU owner",
        tolerance: "absolute 1e-6",
        determinism: "logical input order",
        cancellation_points: "before construction and canonical element checkpoints",
        vjp_rule: "delegates canonical analytical GELU VJP",
        jvp_rule: "delegates canonical analytical GELU JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/gelu.json",
        evidence_fixture_sha256: "8c7311aa137df6e2b386b039e66ffe1c6424875502104ff53d9ce4b30c76c4c1",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-9FCDF546FE24",
        baseline_overload_id: "COMFY-TENSOR-OP-9FCDF546FE24:blocked",
        baseline_fixture_sha256: "c23b244dbe1e372ddd13540866fb4a4b5ac810e4a835c91be84b7aa0a0637f01",
        overload_id: "zed.native.module.l1-loss.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"reduction\",\"type\":\"LossReduction\",\"default\":\"mean\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn l1_loss_module_exact_native(layer_name: impl Into<String>, reduction: LossReduction, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free loss configuration in canonical NativeModule",
        alias_rule: "fresh scalar or elementwise output",
        shape_rule: "none preserves input shape; sum and mean return scalar",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major reduction",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical smooth-L1 owner with beta zero",
        tolerance: "bit exact canonical branch order",
        determinism: "logical input order",
        cancellation_points: "before construction and canonical reduction checkpoints",
        vjp_rule: "delegates canonical sign VJP including reduction scaling",
        jvp_rule: "delegates canonical directional sign JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/l1_loss.json",
        evidence_fixture_sha256: "5d7481ae12b65eb0f96b25ca50c4cde64a2b73248f0a2863f13602eda96ec5b6",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-A2E5CD9C8E38",
        baseline_overload_id: "COMFY-TENSOR-OP-A2E5CD9C8E38:blocked",
        baseline_fixture_sha256: "e7dcb1278dc9277c130f48c1a7f9d6e8c4626f7beecce2b2da9c62c20a68ba02",
        overload_id: "zed.native.module.max-pool-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"[usize;2]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"Option<[usize;2]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"[usize;2]\",\"default\":[0,0],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dilation\",\"type\":\"[usize;2]\",\"default\":[1,1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"ceil_mode\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn max_pool_2d_module_exact_native(layer_name: impl Into<String>, kernel_size: [usize;2], stride: Option<[usize;2]>, padding: [usize;2], dilation: [usize;2], ceil_mode: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free pooling configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "CHW or NCHW pooling with checked padding dilation and ceil mode",
        dtype_rule: "F32 canonical pooling",
        accumulation_dtype: "F32 gradient scatter",
        layout_rule: "logical row-major channel-first windows",
        device_rule: "CPU certified",
        numeric_rule: "extends the canonical pooling geometry and selects deterministic maxima",
        tolerance: "bit exact",
        determinism: "batch channel output window then kernel order",
        cancellation_points: "before construction and at bounded output windows",
        vjp_rule: "scatter-adds to deterministic selected maxima",
        jvp_rule: "gathers tangent values at deterministic selected maxima",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/max_pool_2d.json",
        evidence_fixture_sha256: "d97c8516b1a0eb34d0a4eb06fb639699109f584e2f7510e3dec25b8413b26177",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-A666696563C8",
        baseline_overload_id: "COMFY-TENSOR-OP-A666696563C8:blocked",
        baseline_fixture_sha256: "3b3c97b0b26f548715ace8a1ff88f293918bf3ab6321c85fc4498db75fef3073",
        overload_id: "zed.native.module.module-dict.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"children\",\"type\":\"Vec<NativeModule>\",\"default\":null,\"keyword_only\":false,\"kind\":\"variadic_positional\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn module_dict_exact_native(layer_name: impl Into<String>, children: Vec<NativeModule>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "owns uniquely named children in the canonical NativeModule lifecycle",
        alias_rule: "children are moved into one authoritative owner",
        shape_rule: "container defines no forward shape",
        dtype_rule: "container defines no independent dtype",
        accumulation_dtype: "delegates child rules",
        layout_rule: "stable insertion order with keyed access",
        device_rule: "delegates child rules",
        numeric_rule: "contains no numeric kernel",
        tolerance: "structural",
        determinism: "stable insertion order",
        cancellation_points: "before and after construction",
        vjp_rule: "contains no derivative kernel",
        jvp_rule: "contains no derivative kernel",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/module_dict.json",
        evidence_fixture_sha256: "cb2e205ba353a22586d141ac0456d42a9395b492cf103b32b99f6587eacbe398",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-D44F00F8A19B",
        baseline_overload_id: "COMFY-TENSOR-OP-D44F00F8A19B:blocked",
        baseline_fixture_sha256: "a5fb3328d9c41b9e84e8d5473369bae629818c4dbef2a4d4148e64f89059b303",
        overload_id: "zed.native.module.module-list.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"children\",\"type\":\"Vec<NativeModule>\",\"default\":null,\"keyword_only\":false,\"kind\":\"variadic_positional\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn module_list_exact_native(layer_name: impl Into<String>, children: Vec<NativeModule>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "owns index-ordered children in the canonical NativeModule lifecycle",
        alias_rule: "children are moved into one authoritative owner",
        shape_rule: "container defines no forward shape",
        dtype_rule: "container defines no independent dtype",
        accumulation_dtype: "delegates child rules",
        layout_rule: "stable index order",
        device_rule: "delegates child rules",
        numeric_rule: "contains no numeric kernel",
        tolerance: "structural",
        determinism: "stable index order",
        cancellation_points: "before and after construction",
        vjp_rule: "contains no derivative kernel",
        jvp_rule: "contains no derivative kernel",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/module_list.json",
        evidence_fixture_sha256: "2fbaa01490297ac9fda78bcaed7f96370d58e89adfa293a2f6381f77b3128d51",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-B122B2B8E01C",
        baseline_overload_id: "COMFY-TENSOR-OP-B122B2B8E01C:blocked",
        baseline_fixture_sha256: "7b4c8cbf2ba522ecd245276a432ae3aecaed2f872dde7c19ae00cc900859a119",
        overload_id: "zed.native.module.parameter.autograd.v1",
        ordered_parameters_json: "[{\"name\":\"tape\",\"type\":\"&mut AutogradTape\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"leaf\",\"type\":\"Option<LeafId>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"requires_grad\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn parameter_exact_native(tape: &mut AutogradTape, input: &Tensor, leaf: Option<LeafId>, requires_grad: bool, cancellation: &CancellationToken) -> Result<Tensor, NeuralNetworkModulePartThreeError>",
        mutation_rule: "delegates checked leaf binding to the caller-owned canonical AutogradTape",
        alias_rule: "returns the same tensor storage handle",
        shape_rule: "preserves shape",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "delegates autograd rules",
        layout_rule: "preserves layout and strides",
        device_rule: "preserves device",
        numeric_rule: "no numeric transformation",
        tolerance: "identity",
        determinism: "single checked tape transition",
        cancellation_points: "before canonical tape mutation",
        vjp_rule: "registers the tensor as a canonical autograd leaf",
        jvp_rule: "parameter construction adds no tangent transform",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/parameter.json",
        evidence_fixture_sha256: "122010adf4cf7e556a70147d19d4da472217279a745e11ec4309df6ead274327",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-9E325E7C79AB",
        baseline_overload_id: "COMFY-TENSOR-OP-9E325E7C79AB:blocked",
        baseline_fixture_sha256: "868916c37dbf66035d05878098ab41f8e00c3548e740c17abca1d326351573aa",
        overload_id: "zed.native.module.pixel-shuffle.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"factor\",\"type\":\"u64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn pixel_shuffle_module_exact_native(layer_name: impl Into<String>, factor: u64, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free configuration in canonical NativeModule",
        alias_rule: "fresh strided tensor view",
        shape_rule: "moves a squared channel factor into the final two spatial dimensions",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "none",
        layout_rule: "canonical pixel-shuffle strided mapping",
        device_rule: "preserves device",
        numeric_rule: "delegates canonical pixel-shuffle view owner",
        tolerance: "bit exact",
        determinism: "descriptor transform only",
        cancellation_points: "before construction and canonical descriptor validation",
        vjp_rule: "delegates inverse pixel-unshuffle mapping",
        jvp_rule: "applies identical descriptor transform to tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/pixel_shuffle.json",
        evidence_fixture_sha256: "2d9921823541b8658d5c922add2adb07123f6ce71e9f7193aece2ef3c4c2b3a0",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-92EB003A2648",
        baseline_overload_id: "COMFY-TENSOR-OP-92EB003A2648:blocked",
        baseline_fixture_sha256: "c7017e580ffc39a3732ad43beca92895fffcd0770e939e5e54d8ffba885c7b1d",
        overload_id: "zed.native.module.pixel-unshuffle.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"factor\",\"type\":\"u64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn pixel_unshuffle_module_exact_native(layer_name: impl Into<String>, factor: u64, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free configuration in canonical NativeModule",
        alias_rule: "fresh strided tensor view",
        shape_rule: "moves a squared factor from final spatial dimensions into channels",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "none",
        layout_rule: "canonical pixel-unshuffle strided mapping",
        device_rule: "preserves device",
        numeric_rule: "delegates canonical pixel-unshuffle view owner",
        tolerance: "bit exact",
        determinism: "descriptor transform only",
        cancellation_points: "before construction and canonical descriptor validation",
        vjp_rule: "delegates inverse pixel-shuffle mapping",
        jvp_rule: "applies identical descriptor transform to tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/pixel_unshuffle.json",
        evidence_fixture_sha256: "1fc151814db031a9dc99e14fec1e043955ada14d07bb87b29b6accf654849883",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-904C1E14BAE4",
        baseline_overload_id: "COMFY-TENSOR-OP-904C1E14BAE4:blocked",
        baseline_fixture_sha256: "41811238db795bea02d3f52d7da5ff7174f8669ab781e400f4b9a2b5d89a3cad",
        overload_id: "zed.native.module.relu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn relu_module_exact_native(layer_name: impl Into<String>, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free module and rejects graph-visible in-place mutation",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical input order",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical ReLU owner and preserves NaN",
        tolerance: "bit exact",
        determinism: "logical input order",
        cancellation_points: "before construction and canonical element checkpoints",
        vjp_rule: "delegates canonical positive-branch VJP",
        jvp_rule: "delegates canonical positive-branch JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/relu.json",
        evidence_fixture_sha256: "02ec4c1d460d1aefbf3bcb603756f4f0d6ce0f9db42dad8b886898c6c587fa8b",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-BF1F1FC66EDA",
        baseline_overload_id: "COMFY-TENSOR-OP-BF1F1FC66EDA:blocked",
        baseline_fixture_sha256: "5e5fcf119cfcffda01575106f70e3c39fb8e910e5a3831d0e1afb02b9e720fe7",
        overload_id: "zed.native.module.relu-6.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn relu_6_module_exact_native(layer_name: impl Into<String>, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free module and rejects graph-visible in-place mutation",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical input order",
        device_rule: "CPU certified",
        numeric_rule: "adapts canonical ReLU with a checked upper cap of six and preserves NaN",
        tolerance: "bit exact",
        determinism: "logical input order",
        cancellation_points: "before construction and bounded element checkpoints",
        vjp_rule: "canonical ReLU gradient masked at inputs greater than or equal to six",
        jvp_rule: "applies the identical branch mask to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/relu_6.json",
        evidence_fixture_sha256: "d1f58f90bd03079c97919cae0144800efe77c0d3a67d3324e31c5f38b88b129c",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-98A798917C70",
        baseline_overload_id: "COMFY-TENSOR-OP-98A798917C70:blocked",
        baseline_fixture_sha256: "3e5b47675d48c010e5ccc83f5f361af1f57524f1449b1446dc7e9994b59ab3f4",
        overload_id: "zed.native.module.zero-pad-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"[usize;4]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn zero_pad_2d_module_exact_native(layer_name: impl Into<String>, padding: [usize;4], cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free padding configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "adds left right top and bottom extents to CHW or NCHW input",
        dtype_rule: "preserves module input dtype through checked F32 execution",
        accumulation_dtype: "F32 reverse scatter",
        layout_rule: "logical row-major channel-first traversal",
        device_rule: "CPU certified",
        numeric_rule: "extends the canonical Pad2dGeometry and zero-coordinate mapper",
        tolerance: "bit exact",
        determinism: "outer row column order",
        cancellation_points: "before construction and at bounded output coordinates",
        vjp_rule: "gathers the unpadded interior gradient",
        jvp_rule: "applies the identical zero-padding map to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/zero_pad_2d.json",
        evidence_fixture_sha256: "cca3d06ade123bb52df7a85e70cdae3706679b913475a695a5c72249b1b45afd",
    },
]
