&[
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-6A8710D48911",
        baseline_overload_id: "COMFY-TENSOR-OP-6A8710D48911:blocked",
        baseline_fixture_sha256: "01ec1771412df652ebb311bb5e5485e6b41565627714a99e9c774e6f692206ab",
        overload_id: "zed.native.module.adaptive-average-pool-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_size\",\"type\":\"[usize;2]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn adaptive_average_pool_2d_module_exact_native(layer_name: impl Into<String>, output_size: [usize;2], cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs checked state in the canonical NativeModule lifecycle",
        alias_rule: "fresh module and fresh forward output",
        shape_rule: "CHW or NCHW input maps to the requested nonzero height and width",
        dtype_rule: "F32 canonical pooling execution",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel-first traversal",
        device_rule: "CPU certified",
        numeric_rule: "delegates the shared adaptive average-pooling geometry owner",
        tolerance: "bit exact fixed arithmetic order",
        determinism: "batch channel output-bin input order",
        cancellation_points: "before and after construction and at bounded output bins",
        vjp_rule: "delegates shared bin scatter with overlap accumulation",
        jvp_rule: "applies the identical adaptive pooling transform to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/adaptive_average_pool_2d.json",
        evidence_fixture_sha256: "d4d5b15f75022805c2afdbd1a932eae8c70449c3893046e2d9c340f3f20c8995",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-835CE6AE654F",
        baseline_overload_id: "COMFY-TENSOR-OP-835CE6AE654F:blocked",
        baseline_fixture_sha256: "e58a83d1cb14afbc5ac48bbf636a0b4e36abe3d11de1d653e541661e29701249",
        overload_id: "zed.native.module.average-pool-3d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"[usize;3]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"Option<[usize;3]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn average_pool_3d_module_exact_native(layer_name: impl Into<String>, kernel_size: [usize;3], stride: Option<[usize;3]>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs checked state in the canonical NativeModule lifecycle",
        alias_rule: "fresh module and fresh forward output",
        shape_rule: "CDHW or NCDHW floor pooling without padding",
        dtype_rule: "F32 canonical pooling execution",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel-first traversal",
        device_rule: "CPU certified",
        numeric_rule: "delegates the shared rank-generic average-pooling geometry owner",
        tolerance: "bit exact fixed arithmetic order",
        determinism: "batch channel window kernel order",
        cancellation_points: "before and after construction and at bounded windows",
        vjp_rule: "scatter upstream equally through each three-dimensional window",
        jvp_rule: "apply the same three-dimensional averaging transform to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/average_pool_3d.json",
        evidence_fixture_sha256: "6de36fe719f27468f8060d21461897d1d6a9c1315c70c39fe66a44c666150c1a",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-7346A72D7D61",
        baseline_overload_id: "COMFY-TENSOR-OP-7346A72D7D61:blocked",
        baseline_fixture_sha256: "d4d3d0be16e2f2a169077daf3a7a4d6965139da860fc6b23f00e715c74b66dd1",
        overload_id: "zed.native.module.batch-norm-1d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"features\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"epsilon\",\"type\":\"f32\",\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"momentum\",\"type\":\"f32\",\"default\":0.1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"affine\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"track_running_stats\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn batch_norm_1d_module_exact_native(layer_name: impl Into<String>, features: usize, epsilon: f32, momentum: f32, affine: bool, track_running_stats: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "stages running statistics and commits them atomically through canonical NativeModule state",
        alias_rule: "fresh module and fresh output; running statistics never alias callers",
        shape_rule: "NC or NCL input preserves shape and normalizes channel axis one",
        dtype_rule: "F32 canonical normalization with checked module casts",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel reductions",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical batch-normalization statistics and affine owner",
        tolerance: "absolute 1e-5",
        determinism: "channel then logical sample order",
        cancellation_points: "before construction, canonical reductions, and atomic state publication",
        vjp_rule: "delegates canonical batch-normalization affine VJP",
        jvp_rule: "delegates canonical batch-normalization affine JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/batch_norm_1d.json",
        evidence_fixture_sha256: "6a0e052e3fbb5bd30313bc8ac72d2584a344327e9a97a516508b3c380499f8ff",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-72C64A93D406",
        baseline_overload_id: "COMFY-TENSOR-OP-72C64A93D406:blocked",
        baseline_fixture_sha256: "fb9b08d54c885d937d516662f2c22477b47ee4f04c67d3f03f9f2ea01ba84430",
        overload_id: "zed.native.module.batch-norm-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"features\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"epsilon\",\"type\":\"f32\",\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"momentum\",\"type\":\"f32\",\"default\":0.1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"affine\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"track_running_stats\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn batch_norm_2d_module_exact_native(layer_name: impl Into<String>, features: usize, epsilon: f32, momentum: f32, affine: bool, track_running_stats: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "stages running statistics and commits them atomically through canonical NativeModule state",
        alias_rule: "fresh module and fresh output; running statistics never alias callers",
        shape_rule: "NCHW input preserves shape and normalizes channel axis one",
        dtype_rule: "F32 canonical normalization with checked module casts",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel reductions",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical batch-normalization statistics and affine owner",
        tolerance: "absolute 1e-5",
        determinism: "channel then logical sample order",
        cancellation_points: "before construction, canonical reductions, and atomic state publication",
        vjp_rule: "delegates canonical batch-normalization affine VJP",
        jvp_rule: "delegates canonical batch-normalization affine JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/batch_norm_2d.json",
        evidence_fixture_sha256: "f59daa45042c9f828de7f3bb93ed5cece442cc2679286d0164f2b3199c88ac61",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-700E959DB8E4",
        baseline_overload_id: "COMFY-TENSOR-OP-700E959DB8E4:blocked",
        baseline_fixture_sha256: "1422d3cc30d6e71c8ab08d7adb517c60280ca9d6e601d38d95b910c14b031e4e",
        overload_id: "zed.native.module.conv-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"[usize;2]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"[usize;2]\",\"default\":[1,1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"[usize;2]\",\"default\":[0,0],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dilation\",\"type\":\"[usize;2]\",\"default\":[1,1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"groups\",\"type\":\"usize\",\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn conv_2d_module_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_size: [usize;2], stride: [usize;2], padding: [usize;2], dilation: [usize;2], groups: usize, bias: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs an unloaded adapter in the canonical NativeModule parameter lifecycle",
        alias_rule: "fresh module and fresh forward output",
        shape_rule: "canonical grouped NCHW two-dimensional convolution geometry",
        dtype_rule: "loaded floating dtype with checked F32 compute cast",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major NCHW",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical convolution owner without copied kernel math",
        tolerance: "canonical convolution tolerance",
        determinism: "canonical connection order",
        cancellation_points: "before and after construction and canonical kernel checkpoints",
        vjp_rule: "delegates canonical convolution VJP",
        jvp_rule: "delegates canonical convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/conv_2d.json",
        evidence_fixture_sha256: "2416fd86a9242776564bffd0927ddf963cd28959d64a3e941fefb71c87af0122",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-690D2FADC241",
        baseline_overload_id: "COMFY-TENSOR-OP-690D2FADC241:blocked",
        baseline_fixture_sha256: "376311239d356dbaf458cd37ba02ff2738d7559584a7003873fdf1e43ad25a8c",
        overload_id: "zed.native.module.embedding.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"embeddings\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"options\",\"type\":\"EmbeddingOptions\",\"default\":\"EmbeddingOptions::default()\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn embedding_module_exact_native(layer_name: impl Into<String>, embeddings: usize, dimensions: usize, options: EmbeddingOptions, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "owns weight in canonical NativeModule and atomically publishes optional max-norm mutation",
        alias_rule: "fresh selected output; dense weight state remains module-owned",
        shape_rule: "appends embedding width to the I64 index shape",
        dtype_rule: "I64 indices and F32 weights",
        accumulation_dtype: "F32 gradient accumulation",
        layout_rule: "logical index order then embedding width",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical embedding selection and renormalization owner",
        tolerance: "bit exact selection; absolute 1e-6 renormalization",
        determinism: "logical index order",
        cancellation_points: "before construction, canonical selection, and weight publication",
        vjp_rule: "delegates canonical indexed scatter with padding and frequency rules",
        jvp_rule: "delegates canonical tangent-row selection",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/embedding.json",
        evidence_fixture_sha256: "006e4b5b37436da9ec099a2187a14fec0506c3f1054b4ef6c1f98c50ae1b1cd2",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-5B8CE1451811",
        baseline_overload_id: "COMFY-TENSOR-OP-5B8CE1451811:blocked",
        baseline_fixture_sha256: "33896fad022ad9dafdf568f953b6bfcd16c2ace9680ed893b5986d4271cb4955",
        overload_id: "zed.native.module.huber-loss.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"delta\",\"type\":\"f32\",\"default\":1.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"reduction\",\"type\":\"LossReduction\",\"default\":\"mean\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn huber_loss_module_exact_native(layer_name: impl Into<String>, delta: f32, reduction: LossReduction, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free loss configuration in canonical NativeModule",
        alias_rule: "fresh scalar or elementwise output",
        shape_rule: "none reduction preserves shape; sum and mean return scalar",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major reduction",
        device_rule: "CPU certified",
        numeric_rule: "equals delta times the canonical smooth-L1 owner with beta equal to delta",
        tolerance: "bit exact adapter scaling order",
        determinism: "canonical smooth-L1 order then output scaling",
        cancellation_points: "before construction, canonical loss checkpoints, and scaling checkpoints",
        vjp_rule: "scales canonical smooth-L1 VJP by delta",
        jvp_rule: "scales canonical smooth-L1 JVP by delta",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/huber_loss.json",
        evidence_fixture_sha256: "769b1725fd91a515cc5c18538d0ce7e8b60d3a0a6b4b966f09957369a8b6451a",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-69EEDCD403B3",
        baseline_overload_id: "COMFY-TENSOR-OP-69EEDCD403B3:blocked",
        baseline_fixture_sha256: "08848f5e8bd4d62d5e73d9d61d5dfb7e03cf2f31c48af4eb8e8a2ccf249cd77f",
        overload_id: "zed.native.module.instance-norm-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"features\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"epsilon\",\"type\":\"f32\",\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"affine\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn instance_norm_2d_module_exact_native(layer_name: impl Into<String>, features: usize, epsilon: f32, affine: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs checked affine state in canonical NativeModule",
        alias_rule: "fresh module and fresh output",
        shape_rule: "NCHW shape is preserved and each batch-channel spatial plane is normalized",
        dtype_rule: "F32 canonical normalization",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel planes",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical group normalization with groups equal to channels",
        tolerance: "absolute 1e-5",
        determinism: "batch channel spatial order",
        cancellation_points: "before construction and canonical normalization checkpoints",
        vjp_rule: "delegates canonical group-normalization affine VJP",
        jvp_rule: "delegates canonical group-normalization affine JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/instance_norm_2d.json",
        evidence_fixture_sha256: "94a0165b0b80f923ba9b10db8c584fb34c674c7da567880cce649db11911525a",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-853B6CAD39A0",
        baseline_overload_id: "COMFY-TENSOR-OP-853B6CAD39A0:blocked",
        baseline_fixture_sha256: "94a12ece08c8220df83097c03975148df5486f0197636c74aff0b8cbdae82e30",
        overload_id: "zed.native.module.leaky-relu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"negative_slope\",\"type\":\"f32\",\"default\":0.01,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn leaky_relu_module_exact_native(layer_name: impl Into<String>, negative_slope: f32, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free module and rejects graph-visible in-place mutation",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical leaky-ReLU owner",
        tolerance: "bit exact branch arithmetic",
        determinism: "logical input order",
        cancellation_points: "before construction and canonical element checkpoints",
        vjp_rule: "delegates canonical branch-slope VJP",
        jvp_rule: "delegates canonical branch-slope JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/leaky_relu.json",
        evidence_fixture_sha256: "ff0e78693b899ebe96dba08f8524228dfdb733f662e3c299a2e839e17bb15666",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-707C3B6AD0B4",
        baseline_overload_id: "COMFY-TENSOR-OP-707C3B6AD0B4:blocked",
        baseline_fixture_sha256: "5d08499df2c0826d84f6b150b251c7c6cef5cead7c5da3c16e62d4c713092240",
        overload_id: "zed.native.module.linear.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_features\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_features\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn linear_module_exact_native(layer_name: impl Into<String>, input_features: usize, output_features: usize, bias: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs an unloaded adapter in the canonical NativeModule parameter lifecycle",
        alias_rule: "fresh module and fresh forward output",
        shape_rule: "replaces the final input dimension with output features",
        dtype_rule: "loaded floating dtype with checked F32 compute cast",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major flattened leading rows",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical linear owner without copied matrix math",
        tolerance: "canonical linear tolerance",
        determinism: "row output-channel input-channel order",
        cancellation_points: "before and after construction and canonical row checkpoints",
        vjp_rule: "delegates canonical input weight and bias VJP",
        jvp_rule: "delegates canonical linear product-rule JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/linear.json",
        evidence_fixture_sha256: "4490248907444d5860ea5dbdd441fc32d03fa71d16ab69ace53803f89655c9f2",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-679C11D943DB",
        baseline_overload_id: "COMFY-TENSOR-OP-679C11D943DB:blocked",
        baseline_fixture_sha256: "5a9e1377b112640b767c80c9e02e2b29223448aad04c3b3bf3fc049c408471dd",
        overload_id: "zed.native.module.multihead-attention.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"embed_dimension\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"heads\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn multihead_attention_module_exact_native(layer_name: impl Into<String>, embed_dimension: usize, heads: usize, bias: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "owns four projection children and publishes all child generations atomically through canonical NativeModule",
        alias_rule: "fresh projected and attention outputs",
        shape_rule: "sequence-major LE or LNE inputs preserve query shape with compatible key and value lengths",
        dtype_rule: "F32 canonical attention compute with checked module casts",
        accumulation_dtype: "F32",
        layout_rule: "explicit sequence-major to canonical NHD adapter and inverse",
        device_rule: "CPU reference SDP certified",
        numeric_rule: "composes canonical linear projections and canonical scaled-dot-product attention",
        tolerance: "absolute 1e-5",
        determinism: "projection order then canonical attention order then output projection",
        cancellation_points: "before each projection, canonical attention tiles, and atomic child publication",
        vjp_rule: "composes canonical attention VJP with canonical projection VJPs",
        jvp_rule: "composes canonical projection JVPs with canonical attention JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/multihead_attention.json",
        evidence_fixture_sha256: "57941c9241d71a98cbe1cb63313bc52d02239eb62b7cd17ab2a40eedb0bc8990",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-7BEE9C744BDC",
        baseline_overload_id: "COMFY-TENSOR-OP-7BEE9C744BDC:blocked",
        baseline_fixture_sha256: "0c68f1c20ddf75b1aa3615aea05b2be73514ee894212b9ad5570642e232e446c",
        overload_id: "zed.native.module.replication-pad-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"[usize;4]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn replication_pad_2d_module_exact_native(layer_name: impl Into<String>, padding: [usize;4], cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free padding configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "adds left right top and bottom extents to CHW or NCHW input",
        dtype_rule: "preserves module input dtype through checked F32 execution",
        accumulation_dtype: "F32 for reverse scatter",
        layout_rule: "logical row-major channel-first traversal",
        device_rule: "CPU certified",
        numeric_rule: "uses the canonical convolution replicate-coordinate mapper and owns only traversal",
        tolerance: "bit exact",
        determinism: "outer row column order",
        cancellation_points: "before construction and at bounded output coordinates",
        vjp_rule: "scatter-adds each padded gradient to its canonical replicated source coordinate",
        jvp_rule: "applies the identical replicated coordinate transform to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/replication_pad_2d.json",
        evidence_fixture_sha256: "5d950d3e6365a2f3a27d0f3cc296246178f32ded783d05d2f080627c04abe996",
    },
]
