&[
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-C76DE8CF2CF0",
        baseline_overload_id: "COMFY-TENSOR-OP-C76DE8CF2CF0:blocked",
        baseline_fixture_sha256: "a6c776cdaea35cda23d16d222c7d00807813b76e2870433213433c6c49d02e73",
        overload_id: "zed.native.module.conv-3d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"[usize;3]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"[usize;3]\",\"default\":[1,1,1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"[usize;3]\",\"default\":[0,0,0],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dilation\",\"type\":\"[usize;3]\",\"default\":[1,1,1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"groups\",\"type\":\"usize\",\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn conv_3d_module_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_size: [usize;3], stride: [usize;3], padding: [usize;3], dilation: [usize;3], groups: usize, bias: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs an unloaded adapter in the canonical NativeModule parameter lifecycle",
        alias_rule: "fresh module and fresh forward output",
        shape_rule: "canonical grouped NCDHW three-dimensional convolution geometry",
        dtype_rule: "loaded floating dtype with checked F32 compute cast",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major NCDHW",
        device_rule: "CPU certified",
        numeric_rule: "delegates the canonical rank-generic convolution owner",
        tolerance: "canonical convolution tolerance",
        determinism: "canonical connection order",
        cancellation_points: "before construction and canonical kernel checkpoints",
        vjp_rule: "delegates canonical convolution VJP",
        jvp_rule: "delegates canonical convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/conv_3d.json",
        evidence_fixture_sha256: "813110521bbc0281ea6c8be825abe38612985824c529497d76b20b9e62f15581",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-96DE512D2417",
        baseline_overload_id: "COMFY-TENSOR-OP-96DE512D2417:blocked",
        baseline_fixture_sha256: "41616d5ec8cdf3974f671db7c847f44764ad0c59604ac95d930d7f009c0c9eb9",
        overload_id: "zed.native.module.gelu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"approximation\",\"type\":\"GeluApproximation\",\"default\":\"none\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn gelu_module_exact_native(layer_name: impl Into<String>, approximation: GeluApproximation, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical input order",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical exact or tanh GELU owner",
        tolerance: "absolute 1e-6",
        determinism: "logical input order",
        cancellation_points: "before construction and canonical element checkpoints",
        vjp_rule: "delegates canonical analytical GELU VJP",
        jvp_rule: "delegates canonical analytical GELU JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/gelu.json",
        evidence_fixture_sha256: "f4e6c6eba91a43a140012d71a778df78aa0fb17d5d257e7d0b944a1a62ef6948",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-9FCDF546FE24",
        baseline_overload_id: "COMFY-TENSOR-OP-9FCDF546FE24:blocked",
        baseline_fixture_sha256: "fb23e87af6c0135677516d20e046ef944035091c81e04c367b6351e064e1d62c",
        overload_id: "zed.native.module.l1-loss.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"reduction\",\"type\":\"LossReduction\",\"default\":\"mean\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn l1_loss_module_exact_native(layer_name: impl Into<String>, reduction: LossReduction, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free loss configuration in canonical NativeModule",
        alias_rule: "fresh scalar or elementwise output",
        shape_rule: "none preserves input shape; sum and mean return scalar",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major reduction",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical smooth-L1 owner with beta zero",
        tolerance: "bit exact canonical branch order",
        determinism: "logical input order",
        cancellation_points: "before construction and canonical reduction checkpoints",
        vjp_rule: "delegates canonical sign VJP including reduction scaling",
        jvp_rule: "delegates canonical directional sign JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/l1_loss.json",
        evidence_fixture_sha256: "5a3db8767d8006d57c53469109c255e551a3c7f5a1a30535b7cc162fac8eeaa9",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-A2E5CD9C8E38",
        baseline_overload_id: "COMFY-TENSOR-OP-A2E5CD9C8E38:blocked",
        baseline_fixture_sha256: "09d82c66f31fbfa5f3b6e4cffc2ced94a32215e50a25a0c061a61796fcce3671",
        overload_id: "zed.native.module.max-pool-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"[usize;2]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"Option<[usize;2]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"[usize;2]\",\"default\":[0,0],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dilation\",\"type\":\"[usize;2]\",\"default\":[1,1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"ceil_mode\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn max_pool_2d_module_exact_native(layer_name: impl Into<String>, kernel_size: [usize;2], stride: Option<[usize;2]>, padding: [usize;2], dilation: [usize;2], ceil_mode: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free pooling configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "CHW or NCHW pooling with checked padding dilation and ceil mode",
        dtype_rule: "F32 canonical pooling",
        accumulation_dtype: "F32 gradient scatter",
        layout_rule: "logical row-major channel-first windows",
        device_rule: "CPU certified",
        numeric_rule: "extends the canonical pooling geometry and selects deterministic maxima",
        tolerance: "bit exact",
        determinism: "batch channel output window then kernel order",
        cancellation_points: "before construction and at bounded output windows",
        vjp_rule: "scatter-adds to deterministic selected maxima",
        jvp_rule: "gathers tangent values at deterministic selected maxima",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/max_pool_2d.json",
        evidence_fixture_sha256: "07c27d5bd10e250eefc58b0ab8dba9cfc255ca7d90f56a8901877140c9e724d0",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-A666696563C8",
        baseline_overload_id: "COMFY-TENSOR-OP-A666696563C8:blocked",
        baseline_fixture_sha256: "6ce8991914ac7642a2ec08f34afb9948e227faced37512c122a7b378591efc16",
        overload_id: "zed.native.module.module-dict.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"children\",\"type\":\"Vec<NativeModule>\",\"default\":null,\"keyword_only\":false,\"kind\":\"variadic_positional\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn module_dict_exact_native(layer_name: impl Into<String>, children: Vec<NativeModule>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "owns uniquely named children in the canonical NativeModule lifecycle",
        alias_rule: "children are moved into one authoritative owner",
        shape_rule: "container defines no forward shape",
        dtype_rule: "container defines no independent dtype",
        accumulation_dtype: "delegates child rules",
        layout_rule: "stable insertion order with keyed access",
        device_rule: "delegates child rules",
        numeric_rule: "contains no numeric kernel",
        tolerance: "structural",
        determinism: "stable insertion order",
        cancellation_points: "before and after construction",
        vjp_rule: "contains no derivative kernel",
        jvp_rule: "contains no derivative kernel",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/module_dict.json",
        evidence_fixture_sha256: "8d775c3ec60adbba5df44e1761d2f7db5f0810e590aeb4dadde4866644b3ac45",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-D44F00F8A19B",
        baseline_overload_id: "COMFY-TENSOR-OP-D44F00F8A19B:blocked",
        baseline_fixture_sha256: "6d73d9f66a29ffbd0faa0f35ac7a90cde705400791ce5d5f83f90438696fbee2",
        overload_id: "zed.native.module.module-list.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"children\",\"type\":\"Vec<NativeModule>\",\"default\":null,\"keyword_only\":false,\"kind\":\"variadic_positional\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn module_list_exact_native(layer_name: impl Into<String>, children: Vec<NativeModule>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "owns index-ordered children in the canonical NativeModule lifecycle",
        alias_rule: "children are moved into one authoritative owner",
        shape_rule: "container defines no forward shape",
        dtype_rule: "container defines no independent dtype",
        accumulation_dtype: "delegates child rules",
        layout_rule: "stable index order",
        device_rule: "delegates child rules",
        numeric_rule: "contains no numeric kernel",
        tolerance: "structural",
        determinism: "stable index order",
        cancellation_points: "before and after construction",
        vjp_rule: "contains no derivative kernel",
        jvp_rule: "contains no derivative kernel",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/module_list.json",
        evidence_fixture_sha256: "2cc0d06bb89dd673b033c10c17ebc387cc521254740611c06e217d005c7fcf66",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-B122B2B8E01C",
        baseline_overload_id: "COMFY-TENSOR-OP-B122B2B8E01C:blocked",
        baseline_fixture_sha256: "780a08e3e21ae13f80966450e4580639aeb2da107975f111276196b86efeb047",
        overload_id: "zed.native.module.parameter.autograd.v1",
        ordered_parameters_json: "[{\"name\":\"tape\",\"type\":\"&mut AutogradTape\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"leaf\",\"type\":\"Option<LeafId>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"requires_grad\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn parameter_exact_native(tape: &mut AutogradTape, input: &Tensor, leaf: Option<LeafId>, requires_grad: bool, cancellation: &CancellationToken) -> Result<Tensor, NeuralNetworkModulePartThreeError>",
        mutation_rule: "delegates checked leaf binding to the caller-owned canonical AutogradTape",
        alias_rule: "returns the same tensor storage handle",
        shape_rule: "preserves shape",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "delegates autograd rules",
        layout_rule: "preserves layout and strides",
        device_rule: "preserves device",
        numeric_rule: "no numeric transformation",
        tolerance: "identity",
        determinism: "single checked tape transition",
        cancellation_points: "before canonical tape mutation",
        vjp_rule: "registers the tensor as a canonical autograd leaf",
        jvp_rule: "parameter construction adds no tangent transform",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/parameter.json",
        evidence_fixture_sha256: "9d70077266a8f2c0beb14d0ca5d2c8745553499f1a35789e006702ce17107af7",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-9E325E7C79AB",
        baseline_overload_id: "COMFY-TENSOR-OP-9E325E7C79AB:blocked",
        baseline_fixture_sha256: "d68f3cf40c1c186b3afd7f20f9193a4ec5a49999bc571bf7323b4944b3d2f358",
        overload_id: "zed.native.module.pixel-shuffle.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"factor\",\"type\":\"u64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn pixel_shuffle_module_exact_native(layer_name: impl Into<String>, factor: u64, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free configuration in canonical NativeModule",
        alias_rule: "fresh strided tensor view",
        shape_rule: "moves a squared channel factor into the final two spatial dimensions",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "none",
        layout_rule: "canonical pixel-shuffle strided mapping",
        device_rule: "preserves device",
        numeric_rule: "delegates canonical pixel-shuffle view owner",
        tolerance: "bit exact",
        determinism: "descriptor transform only",
        cancellation_points: "before construction and canonical descriptor validation",
        vjp_rule: "delegates inverse pixel-unshuffle mapping",
        jvp_rule: "applies identical descriptor transform to tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/pixel_shuffle.json",
        evidence_fixture_sha256: "60d34881e8a22c37f624d29405dceaea0d3face7747addaa5cc898371e43979f",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-92EB003A2648",
        baseline_overload_id: "COMFY-TENSOR-OP-92EB003A2648:blocked",
        baseline_fixture_sha256: "901958539b9bd51ed7972b9d33f26e49e9974cfb06c485d5e0376577cd270ea6",
        overload_id: "zed.native.module.pixel-unshuffle.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"factor\",\"type\":\"u64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn pixel_unshuffle_module_exact_native(layer_name: impl Into<String>, factor: u64, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free configuration in canonical NativeModule",
        alias_rule: "fresh strided tensor view",
        shape_rule: "moves a squared factor from final spatial dimensions into channels",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "none",
        layout_rule: "canonical pixel-unshuffle strided mapping",
        device_rule: "preserves device",
        numeric_rule: "delegates canonical pixel-unshuffle view owner",
        tolerance: "bit exact",
        determinism: "descriptor transform only",
        cancellation_points: "before construction and canonical descriptor validation",
        vjp_rule: "delegates inverse pixel-shuffle mapping",
        jvp_rule: "applies identical descriptor transform to tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/pixel_unshuffle.json",
        evidence_fixture_sha256: "65c4c696efed302b09a18567249cc8b87f86d0d7c4ddd051ef45d246e06e83b5",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-904C1E14BAE4",
        baseline_overload_id: "COMFY-TENSOR-OP-904C1E14BAE4:blocked",
        baseline_fixture_sha256: "9612f563c88f14e2f4d69e1d2c9252a4fbff82126715f4a315678d2d37b1ccdd",
        overload_id: "zed.native.module.relu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn relu_module_exact_native(layer_name: impl Into<String>, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free module and rejects graph-visible in-place mutation",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical input order",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical ReLU owner and preserves NaN",
        tolerance: "bit exact",
        determinism: "logical input order",
        cancellation_points: "before construction and canonical element checkpoints",
        vjp_rule: "delegates canonical positive-branch VJP",
        jvp_rule: "delegates canonical positive-branch JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/relu.json",
        evidence_fixture_sha256: "bf4b15da8916cabeded7e77862ea457abf86fdb70752d726cb381054546f0ad5",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-BF1F1FC66EDA",
        baseline_overload_id: "COMFY-TENSOR-OP-BF1F1FC66EDA:blocked",
        baseline_fixture_sha256: "1181298b5672295cf9990d4da2f4e5779608fb6dac0c258c2510501ef893e0da",
        overload_id: "zed.native.module.relu-6.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn relu_6_module_exact_native(layer_name: impl Into<String>, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free module and rejects graph-visible in-place mutation",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical input order",
        device_rule: "CPU certified",
        numeric_rule: "adapts canonical ReLU with a checked upper cap of six and preserves NaN",
        tolerance: "bit exact",
        determinism: "logical input order",
        cancellation_points: "before construction and bounded element checkpoints",
        vjp_rule: "canonical ReLU gradient masked at inputs greater than or equal to six",
        jvp_rule: "applies the identical branch mask to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/relu_6.json",
        evidence_fixture_sha256: "048b363671ba3ea463e3f848ff09f7316b3f6e2d814f179495b889f863d27a79",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_03",
        operation_id: "COMFY-TENSOR-OP-98A798917C70",
        baseline_overload_id: "COMFY-TENSOR-OP-98A798917C70:blocked",
        baseline_fixture_sha256: "034f5e94f733b15694f130aae62ac4c4c702b78078108a3b1420a2d33b5c0d8b",
        overload_id: "zed.native.module.zero-pad-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"[usize;4]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn zero_pad_2d_module_exact_native(layer_name: impl Into<String>, padding: [usize;4], cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free padding configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "adds left right top and bottom extents to CHW or NCHW input",
        dtype_rule: "preserves module input dtype through checked F32 execution",
        accumulation_dtype: "F32 reverse scatter",
        layout_rule: "logical row-major channel-first traversal",
        device_rule: "CPU certified",
        numeric_rule: "extends the canonical Pad2dGeometry and zero-coordinate mapper",
        tolerance: "bit exact",
        determinism: "outer row column order",
        cancellation_points: "before construction and at bounded output coordinates",
        vjp_rule: "gathers the unpadded interior gradient",
        jvp_rule: "applies the identical zero-padding map to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-904c1e14bae4",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_03/zero_pad_2d.json",
        evidence_fixture_sha256: "93cfe5272432d1a6c2b1ef86d1ef2f15351f0495639449a5099d5947644adf0f",
    },
]
