&[
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-D60003AC2B14",
        baseline_overload_id: "COMFY-TENSOR-OP-D60003AC2B14:blocked",
        baseline_fixture_sha256: "db4238b65ec40e61959d1929d06080286dc5f90e704fd152501a0e8a8c07b369",
        overload_id: "zed.native.module.avg-pool-1d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"Option<usize>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn avg_pool_1d_module_exact_native(layer_name: impl Into<String>, kernel_size: usize, stride: Option<usize>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free pooling configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "CW or NCW pooling with checked canonical geometry",
        dtype_rule: "F32 canonical pooling",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel-first windows",
        device_rule: "CPU certified",
        numeric_rule: "extends Task 77 AveragePoolGeometry at one spatial dimension",
        tolerance: "bit exact",
        determinism: "batch channel output window then kernel order",
        cancellation_points: "before construction and at bounded output windows",
        vjp_rule: "scatter-adds through canonical pooling connections",
        jvp_rule: "pools tangents through canonical connections",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/avg_pool_1d.json",
        evidence_fixture_sha256: "902f2d12b7772a56538aeb9330328ad4686e9ff60e5af8b442e695c2800894ca",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-EE80ED2D81B0",
        baseline_overload_id: "COMFY-TENSOR-OP-EE80ED2D81B0:blocked",
        baseline_fixture_sha256: "deb293d7862721d8913a78015040f2343e3ec6b686b10aa684b75b9f82e6465e",
        overload_id: "zed.native.module.dropout.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"probability\",\"type\":\"f32\",\"default\":0.5,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn dropout_module_exact_native(layer_name: impl Into<String>, probability: f32, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "NativeModule owns training state; caller-owned RngTransaction is returned only after complete forward publication",
        alias_rule: "evaluation preserves the Tensor handle; training returns fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical mask application",
        accumulation_dtype: "F32",
        layout_rule: "logical input order",
        device_rule: "CPU certified",
        numeric_rule: "inverted dropout scales retained values by one over keep probability",
        tolerance: "bit exact for a fixed RNG profile",
        determinism: "canonical RngTransaction word order",
        cancellation_points: "before validation and at bounded element checkpoints; failure drops the uncommitted transaction",
        vjp_rule: "applies the saved forward mask and inverse keep scaling",
        jvp_rule: "applies the identical saved mask and scaling",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/dropout.json",
        evidence_fixture_sha256: "5157fa7d8d131ad0c25d55da25f40ba0e9376ff7723a7df30e966a5f03606777",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-F88B1E793668",
        baseline_overload_id: "COMFY-TENSOR-OP-F88B1E793668:blocked",
        baseline_fixture_sha256: "4f21c93a6fb484e304b752e1e21fa45ad5ab5c1e3db28ce4d0b3818227ce90fd",
        overload_id: "zed.native.module.elu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"alpha\",\"type\":\"f32\",\"default\":1.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn elu_module_exact_native(layer_name: impl Into<String>, alpha: f32, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free configuration and rejects graph-visible in-place mutation",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical input order",
        device_rule: "CPU certified",
        numeric_rule: "delegates the canonical activation owner using x for positive values and alpha times expm1(x) otherwise",
        tolerance: "absolute 1e-6",
        determinism: "logical input order",
        cancellation_points: "before construction and bounded element checkpoints",
        vjp_rule: "uses derivative one above zero and alpha times exp(x) otherwise",
        jvp_rule: "applies the identical analytical derivative to tangents",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/elu.json",
        evidence_fixture_sha256: "7492a76f7aa3b6556e49d1de7691c172c392bc37147619a2d8592e9d6e6f1ee1",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-D8ED4EE63E27",
        baseline_overload_id: "COMFY-TENSOR-OP-D8ED4EE63E27:blocked",
        baseline_fixture_sha256: "318c26788452d3a85dff3655d43eee0151b3efbe32acfb9d48e11d9fa4cc2c36",
        overload_id: "zed.native.module.identity.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn identity_module_exact_native(layer_name: impl Into<String>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free canonical NativeModule",
        alias_rule: "forward returns the same canonical Tensor storage and descriptor handle",
        shape_rule: "preserves shape",
        dtype_rule: "preserves dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "preserves layout and strides",
        device_rule: "preserves device",
        numeric_rule: "contains no numerical kernel",
        tolerance: "bit and identity exact",
        determinism: "structural identity",
        cancellation_points: "before construction and forward publication",
        vjp_rule: "identity",
        jvp_rule: "identity",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/identity.json",
        evidence_fixture_sha256: "4f857a1e3189a3a6ce76372c80d91a493d5e87180871b0631fb33c763952141f",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-FBA7DB6F71EB",
        baseline_overload_id: "COMFY-TENSOR-OP-FBA7DB6F71EB:blocked",
        baseline_fixture_sha256: "038e12f064135fecdd571ea621b611c23a305de08f2eab2130e7873f1369fdfa",
        overload_id: "zed.native.module.mse-loss.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"reduction\",\"type\":\"LossReduction\",\"default\":\"mean\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn mse_loss_module_exact_native(layer_name: impl Into<String>, reduction: LossReduction, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free loss configuration in canonical NativeModule",
        alias_rule: "fresh scalar or elementwise output",
        shape_rule: "none preserves input shape; sum and mean return scalar",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major reduction",
        device_rule: "CPU certified",
        numeric_rule: "squared input-target difference with exact none sum or mean reduction",
        tolerance: "bit exact fixed reduction order",
        determinism: "logical input order",
        cancellation_points: "before construction and bounded reduction checkpoints",
        vjp_rule: "two times input-target with target negation and reduction scaling",
        jvp_rule: "two times input-target times tangent difference with reduction",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/mse_loss.json",
        evidence_fixture_sha256: "335d955324fe40b71e7dab0e655ee28cc74e494781d0cd010abdaf81db146d48",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-EAF9D9989484",
        baseline_overload_id: "COMFY-TENSOR-OP-EAF9D9989484:blocked",
        baseline_fixture_sha256: "d294dff1ad7910fbffc6c7e2865816c6c6a418f39e80820910a7537b6efa284e",
        overload_id: "zed.native.module.base.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn module_exact_native(layer_name: impl Into<String>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs the canonical empty NativeModule lifecycle owner",
        alias_rule: "owns no input or output tensor",
        shape_rule: "base module defines no forward shape",
        dtype_rule: "base module defines no independent dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "stable child insertion order",
        device_rule: "delegates child rules",
        numeric_rule: "contains no numerical kernel",
        tolerance: "structural",
        determinism: "stable lifecycle transitions",
        cancellation_points: "before and after construction",
        vjp_rule: "base module defines no derivative kernel",
        jvp_rule: "base module defines no derivative kernel",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/module.json",
        evidence_fixture_sha256: "272e87db3c680be8c51242242f4fba0932dd5783c75d30f3434da6e5b469f804",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_04",
        operation_id: "COMFY-TENSOR-OP-E1CEBEBBCBFE",
        baseline_overload_id: "COMFY-TENSOR-OP-E1CEBEBBCBFE:blocked",
        baseline_fixture_sha256: "af958327efd72b5d4a5f5ef4a40596dfa427c458c25f453ec600ca57afd8f574",
        overload_id: "zed.native.module.sigmoid.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn sigmoid_module_exact_native(layer_name: impl Into<String>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "delegates canonical Tensor sigmoid dtype rules",
        accumulation_dtype: "canonical Tensor sigmoid",
        layout_rule: "canonical Tensor traversal",
        device_rule: "canonical certified backend matrix",
        numeric_rule: "delegates Task 50 canonical sigmoid",
        tolerance: "canonical sigmoid tolerance",
        determinism: "canonical Tensor traversal",
        cancellation_points: "before construction and canonical kernel checkpoints",
        vjp_rule: "delegates canonical sigmoid analytical VJP",
        jvp_rule: "delegates canonical sigmoid analytical JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-d60003ac2b14",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_04/sigmoid.json",
        evidence_fixture_sha256: "13c87bd5fb0a5be79139981091fe2b13f0fc5c65dcb91e00c16f1a411a6c0444",
    },
]
