&[
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-6A8710D48911",
        baseline_overload_id: "COMFY-TENSOR-OP-6A8710D48911:blocked",
        baseline_fixture_sha256: "53e2f41f5bdb935b15356e9b939f7f634811981b4feb9984b19aa9427b254507",
        overload_id: "zed.native.module.adaptive-average-pool-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_size\",\"type\":\"[usize;2]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn adaptive_average_pool_2d_module_exact_native(layer_name: impl Into<String>, output_size: [usize;2], cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs checked state in the canonical NativeModule lifecycle",
        alias_rule: "fresh module and fresh forward output",
        shape_rule: "CHW or NCHW input maps to the requested nonzero height and width",
        dtype_rule: "F32 canonical pooling execution",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel-first traversal",
        device_rule: "CPU certified",
        numeric_rule: "delegates the shared adaptive average-pooling geometry owner",
        tolerance: "bit exact fixed arithmetic order",
        determinism: "batch channel output-bin input order",
        cancellation_points: "before and after construction and at bounded output bins",
        vjp_rule: "delegates shared bin scatter with overlap accumulation",
        jvp_rule: "applies the identical adaptive pooling transform to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/adaptive_average_pool_2d.json",
        evidence_fixture_sha256: "5d147182ede9715ff26ffdab6566bfde22a57cdbbcbd1360ca072626daa91e8d",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-835CE6AE654F",
        baseline_overload_id: "COMFY-TENSOR-OP-835CE6AE654F:blocked",
        baseline_fixture_sha256: "3eb6669ee2ee1b9c2f1a09cdd143cd2ad736ebed8439721e693f83b54748fa57",
        overload_id: "zed.native.module.average-pool-3d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"[usize;3]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"Option<[usize;3]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn average_pool_3d_module_exact_native(layer_name: impl Into<String>, kernel_size: [usize;3], stride: Option<[usize;3]>, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs checked state in the canonical NativeModule lifecycle",
        alias_rule: "fresh module and fresh forward output",
        shape_rule: "CDHW or NCDHW floor pooling without padding",
        dtype_rule: "F32 canonical pooling execution",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel-first traversal",
        device_rule: "CPU certified",
        numeric_rule: "delegates the shared rank-generic average-pooling geometry owner",
        tolerance: "bit exact fixed arithmetic order",
        determinism: "batch channel window kernel order",
        cancellation_points: "before and after construction and at bounded windows",
        vjp_rule: "scatter upstream equally through each three-dimensional window",
        jvp_rule: "apply the same three-dimensional averaging transform to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/average_pool_3d.json",
        evidence_fixture_sha256: "c8261a546ba626d09b776d96bfe56752fcc1a1c139d8b468f6b1e9246bddd317",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-7346A72D7D61",
        baseline_overload_id: "COMFY-TENSOR-OP-7346A72D7D61:blocked",
        baseline_fixture_sha256: "51389cefb6d48ba441cac4e7bf19ffedb02513f4bb6dd6e71b62c6de1367e78b",
        overload_id: "zed.native.module.batch-norm-1d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"features\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"epsilon\",\"type\":\"f32\",\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"momentum\",\"type\":\"f32\",\"default\":0.1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"affine\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"track_running_stats\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn batch_norm_1d_module_exact_native(layer_name: impl Into<String>, features: usize, epsilon: f32, momentum: f32, affine: bool, track_running_stats: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "stages running statistics and commits them atomically through canonical NativeModule state",
        alias_rule: "fresh module and fresh output; running statistics never alias callers",
        shape_rule: "NC or NCL input preserves shape and normalizes channel axis one",
        dtype_rule: "F32 canonical normalization with checked module casts",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel reductions",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical batch-normalization statistics and affine owner",
        tolerance: "absolute 1e-5",
        determinism: "channel then logical sample order",
        cancellation_points: "before construction, canonical reductions, and atomic state publication",
        vjp_rule: "delegates canonical batch-normalization affine VJP",
        jvp_rule: "delegates canonical batch-normalization affine JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/batch_norm_1d.json",
        evidence_fixture_sha256: "8dd3e8d47dd152b684ff9eb949aea7bf922a8541d5b0003ea9c02055deffd32f",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-72C64A93D406",
        baseline_overload_id: "COMFY-TENSOR-OP-72C64A93D406:blocked",
        baseline_fixture_sha256: "36ad382067d83090844dd2309c5d583b6faf2cc588cdebaf5b88ecf35c9330b4",
        overload_id: "zed.native.module.batch-norm-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"features\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"epsilon\",\"type\":\"f32\",\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"momentum\",\"type\":\"f32\",\"default\":0.1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"affine\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"track_running_stats\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn batch_norm_2d_module_exact_native(layer_name: impl Into<String>, features: usize, epsilon: f32, momentum: f32, affine: bool, track_running_stats: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "stages running statistics and commits them atomically through canonical NativeModule state",
        alias_rule: "fresh module and fresh output; running statistics never alias callers",
        shape_rule: "NCHW input preserves shape and normalizes channel axis one",
        dtype_rule: "F32 canonical normalization with checked module casts",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel reductions",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical batch-normalization statistics and affine owner",
        tolerance: "absolute 1e-5",
        determinism: "channel then logical sample order",
        cancellation_points: "before construction, canonical reductions, and atomic state publication",
        vjp_rule: "delegates canonical batch-normalization affine VJP",
        jvp_rule: "delegates canonical batch-normalization affine JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/batch_norm_2d.json",
        evidence_fixture_sha256: "ebaa1679d2ddba9e2791ef75592dd0fdba97eb2f36b057130734a2c2df92e3f8",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-700E959DB8E4",
        baseline_overload_id: "COMFY-TENSOR-OP-700E959DB8E4:blocked",
        baseline_fixture_sha256: "7e72209dd77028962e45a92fbe7f1c6154bfeae73d89ddbb6070aef79d5b0048",
        overload_id: "zed.native.module.conv-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_channels\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"kernel_size\",\"type\":\"[usize;2]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"stride\",\"type\":\"[usize;2]\",\"default\":[1,1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"[usize;2]\",\"default\":[0,0],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dilation\",\"type\":\"[usize;2]\",\"default\":[1,1],\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"groups\",\"type\":\"usize\",\"default\":1,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn conv_2d_module_exact_native(layer_name: impl Into<String>, input_channels: usize, output_channels: usize, kernel_size: [usize;2], stride: [usize;2], padding: [usize;2], dilation: [usize;2], groups: usize, bias: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs an unloaded adapter in the canonical NativeModule parameter lifecycle",
        alias_rule: "fresh module and fresh forward output",
        shape_rule: "canonical grouped NCHW two-dimensional convolution geometry",
        dtype_rule: "loaded floating dtype with checked F32 compute cast",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major NCHW",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical convolution owner without copied kernel math",
        tolerance: "canonical convolution tolerance",
        determinism: "canonical connection order",
        cancellation_points: "before and after construction and canonical kernel checkpoints",
        vjp_rule: "delegates canonical convolution VJP",
        jvp_rule: "delegates canonical convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/conv_2d.json",
        evidence_fixture_sha256: "baf6675123d36136f7aed48054d6fd8fe6ea47ecefbff5f7a42e46ee80f67e44",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-690D2FADC241",
        baseline_overload_id: "COMFY-TENSOR-OP-690D2FADC241:blocked",
        baseline_fixture_sha256: "9c24c97a687cc0a2217b7d9e4a5d9c7f23fd0eeb485eb7cfc99f59070caab54f",
        overload_id: "zed.native.module.embedding.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"embeddings\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"options\",\"type\":\"EmbeddingOptions\",\"default\":\"EmbeddingOptions::default()\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn embedding_module_exact_native(layer_name: impl Into<String>, embeddings: usize, dimensions: usize, options: EmbeddingOptions, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "owns weight in canonical NativeModule and atomically publishes optional max-norm mutation",
        alias_rule: "fresh selected output; dense weight state remains module-owned",
        shape_rule: "appends embedding width to the I64 index shape",
        dtype_rule: "I64 indices and F32 weights",
        accumulation_dtype: "F32 gradient accumulation",
        layout_rule: "logical index order then embedding width",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical embedding selection and renormalization owner",
        tolerance: "bit exact selection; absolute 1e-6 renormalization",
        determinism: "logical index order",
        cancellation_points: "before construction, canonical selection, and weight publication",
        vjp_rule: "delegates canonical indexed scatter with padding and frequency rules",
        jvp_rule: "delegates canonical tangent-row selection",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/embedding.json",
        evidence_fixture_sha256: "e99f304392e0b5c8af1b906f428dea920f3fc01af1ec63d974eb7ce7dc02a6ba",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-5B8CE1451811",
        baseline_overload_id: "COMFY-TENSOR-OP-5B8CE1451811:blocked",
        baseline_fixture_sha256: "cec128b17de70ff9a125fa1d43622a184a4d5be64a65f749a0fc6ab1c0ab9c6a",
        overload_id: "zed.native.module.huber-loss.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"delta\",\"type\":\"f32\",\"default\":1.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"reduction\",\"type\":\"LossReduction\",\"default\":\"mean\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn huber_loss_module_exact_native(layer_name: impl Into<String>, delta: f32, reduction: LossReduction, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free loss configuration in canonical NativeModule",
        alias_rule: "fresh scalar or elementwise output",
        shape_rule: "none reduction preserves shape; sum and mean return scalar",
        dtype_rule: "F32",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major reduction",
        device_rule: "CPU certified",
        numeric_rule: "equals delta times the canonical smooth-L1 owner with beta equal to delta",
        tolerance: "bit exact adapter scaling order",
        determinism: "canonical smooth-L1 order then output scaling",
        cancellation_points: "before construction, canonical loss checkpoints, and scaling checkpoints",
        vjp_rule: "scales canonical smooth-L1 VJP by delta",
        jvp_rule: "scales canonical smooth-L1 JVP by delta",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/huber_loss.json",
        evidence_fixture_sha256: "e524439b5a04f2664eeac8b9b8cf855058b61943950beef716afe59ccf5c4dc8",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-69EEDCD403B3",
        baseline_overload_id: "COMFY-TENSOR-OP-69EEDCD403B3:blocked",
        baseline_fixture_sha256: "f87ebef6e54e04c3e0b7ec06ddc811a36ca32799514e664de96e575f476006af",
        overload_id: "zed.native.module.instance-norm-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"features\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"epsilon\",\"type\":\"f32\",\"default\":0.00001,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"affine\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn instance_norm_2d_module_exact_native(layer_name: impl Into<String>, features: usize, epsilon: f32, affine: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs checked affine state in canonical NativeModule",
        alias_rule: "fresh module and fresh output",
        shape_rule: "NCHW shape is preserved and each batch-channel spatial plane is normalized",
        dtype_rule: "F32 canonical normalization",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major channel planes",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical group normalization with groups equal to channels",
        tolerance: "absolute 1e-5",
        determinism: "batch channel spatial order",
        cancellation_points: "before construction and canonical normalization checkpoints",
        vjp_rule: "delegates canonical group-normalization affine VJP",
        jvp_rule: "delegates canonical group-normalization affine JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/instance_norm_2d.json",
        evidence_fixture_sha256: "1c5964102086ed092e6a191987b15fd223fdd3fcd0f993a491a86947eccbc642",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-853B6CAD39A0",
        baseline_overload_id: "COMFY-TENSOR-OP-853B6CAD39A0:blocked",
        baseline_fixture_sha256: "13a4dd62d0887a68fbe96d519ceb5920fc46f3f6413d2df7699e7c4270c942a8",
        overload_id: "zed.native.module.leaky-relu.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"negative_slope\",\"type\":\"f32\",\"default\":0.01,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"inplace\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn leaky_relu_module_exact_native(layer_name: impl Into<String>, negative_slope: f32, inplace: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free module and rejects graph-visible in-place mutation",
        alias_rule: "fresh output",
        shape_rule: "preserves shape",
        dtype_rule: "F32 canonical activation",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical leaky-ReLU owner",
        tolerance: "bit exact branch arithmetic",
        determinism: "logical input order",
        cancellation_points: "before construction and canonical element checkpoints",
        vjp_rule: "delegates canonical branch-slope VJP",
        jvp_rule: "delegates canonical branch-slope JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/leaky_relu.json",
        evidence_fixture_sha256: "62af71c0716bac9a2254cfc10698de56ee5d3380972de8fafaa26f42adfdb0b2",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-707C3B6AD0B4",
        baseline_overload_id: "COMFY-TENSOR-OP-707C3B6AD0B4:blocked",
        baseline_fixture_sha256: "0742e49800e69ebd7ef89228952f05349ea7a7685557be2ad4054a40e012afa3",
        overload_id: "zed.native.module.linear.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"input_features\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"output_features\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn linear_module_exact_native(layer_name: impl Into<String>, input_features: usize, output_features: usize, bias: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs an unloaded adapter in the canonical NativeModule parameter lifecycle",
        alias_rule: "fresh module and fresh forward output",
        shape_rule: "replaces the final input dimension with output features",
        dtype_rule: "loaded floating dtype with checked F32 compute cast",
        accumulation_dtype: "F32",
        layout_rule: "logical row-major flattened leading rows",
        device_rule: "CPU certified",
        numeric_rule: "delegates canonical linear owner without copied matrix math",
        tolerance: "canonical linear tolerance",
        determinism: "row output-channel input-channel order",
        cancellation_points: "before and after construction and canonical row checkpoints",
        vjp_rule: "delegates canonical input weight and bias VJP",
        jvp_rule: "delegates canonical linear product-rule JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/linear.json",
        evidence_fixture_sha256: "266be72da15eb8e652814784cc7f745e367a122c631f82a0ab344800a6b3b0e8",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-679C11D943DB",
        baseline_overload_id: "COMFY-TENSOR-OP-679C11D943DB:blocked",
        baseline_fixture_sha256: "6c85e844123fb64491fa1ed7d446a88723623ff1d76dcd1ff4bffc68ec1d8f8a",
        overload_id: "zed.native.module.multihead-attention.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"embed_dimension\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"heads\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"bias\",\"type\":\"bool\",\"default\":true,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn multihead_attention_module_exact_native(layer_name: impl Into<String>, embed_dimension: usize, heads: usize, bias: bool, cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "owns four projection children and publishes all child generations atomically through canonical NativeModule",
        alias_rule: "fresh projected and attention outputs",
        shape_rule: "sequence-major LE or LNE inputs preserve query shape with compatible key and value lengths",
        dtype_rule: "F32 canonical attention compute with checked module casts",
        accumulation_dtype: "F32",
        layout_rule: "explicit sequence-major to canonical NHD adapter and inverse",
        device_rule: "CPU reference SDP certified",
        numeric_rule: "composes canonical linear projections and canonical scaled-dot-product attention",
        tolerance: "absolute 1e-5",
        determinism: "projection order then canonical attention order then output projection",
        cancellation_points: "before each projection, canonical attention tiles, and atomic child publication",
        vjp_rule: "composes canonical attention VJP with canonical projection VJPs",
        jvp_rule: "composes canonical projection JVPs with canonical attention JVP",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/multihead_attention.json",
        evidence_fixture_sha256: "034cffa1a020ae0a12259bc22f5bc84019a919ce35a72a366a0cdeadff1b5f77",
    },
    ResolvedOperationContract {
        resolution_module: "neural_network_module_02",
        operation_id: "COMFY-TENSOR-OP-7BEE9C744BDC",
        baseline_overload_id: "COMFY-TENSOR-OP-7BEE9C744BDC:blocked",
        baseline_fixture_sha256: "79116215326f423e95baa9a98ca291245c477df3404813c6a5e7c8035f12e101",
        overload_id: "zed.native.module.replication-pad-2d.cpu-f32.v1",
        ordered_parameters_json: "[{\"name\":\"layer_name\",\"type\":\"String\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"padding\",\"type\":\"[usize;4]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"NativeModule\"]",
        rust_signature: "fn replication_pad_2d_module_exact_native(layer_name: impl Into<String>, padding: [usize;4], cancellation: &CancellationToken) -> Result<NativeModule, NativeOpsError>",
        mutation_rule: "constructs state-free padding configuration in canonical NativeModule",
        alias_rule: "fresh output",
        shape_rule: "adds left right top and bottom extents to CHW or NCHW input",
        dtype_rule: "preserves module input dtype through checked F32 execution",
        accumulation_dtype: "F32 for reverse scatter",
        layout_rule: "logical row-major channel-first traversal",
        device_rule: "CPU certified",
        numeric_rule: "uses the canonical convolution replicate-coordinate mapper and owns only traversal",
        tolerance: "bit exact",
        determinism: "outer row column order",
        cancellation_points: "before construction and at bounded output coordinates",
        vjp_rule: "scatter-adds each padded gradient to its canonical replicated source coordinate",
        jvp_rule: "applies the identical replicated coordinate transform to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-neural-network-module-comfy-tensor-op-5b8ce1451811",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/neural_network_module_02/replication_pad_2d.json",
        evidence_fixture_sha256: "05203cf3364d7bb47b2b6e41ccdd018442f571e0658fae9425e1e69b84ea8c4f",
    },
]
