&[
    ResolvedOperationContract {
        resolution_module: "random_number_generation_02",
        operation_id: "COMFY-TENSOR-OP-FD729B8A5363",
        baseline_overload_id: "COMFY-TENSOR-OP-FD729B8A5363:blocked",
        baseline_fixture_sha256: "9859b7a115de51af013dce1e7770c77495336ff7a3f0a3b284cbb0aac77a6b1e",
        overload_id: "sim.native.rng.randn.cpu-floating-strided.v1",
        ordered_parameters_json: "[{\"name\":\"shape\",\"type\":\"&[u64]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dtype\",\"type\":\"DType\",\"default\":\"F32\",\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"layout\",\"type\":\"Layout\",\"default\":\"Strided\",\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"device\",\"type\":\"DeviceId\",\"default\":\"CPU\",\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"transaction\",\"type\":\"RngTransaction\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"RngTransaction\"]",
        rust_signature: "fn randn_with_context_exact_native(backend: &CpuBackend, shape: &[u64], dtype: DType, layout: Layout, device: DeviceId, transaction: RngTransaction, context: &ExecutionContext<'_>) -> Result<RandomTensorForward, RandomNumberGenerationPartTwoError>",
        mutation_rule: "fresh Tensor and caller transaction are returned only after complete upload and cancellation checks",
        alias_rule: "fresh canonical Tensor storage with no input alias",
        shape_rule: "checked requested shape including scalar and zero-sized dimensions",
        dtype_rule: "CPU F64, F32, F16, and BF16 outputs; other dtypes fail explicitly",
        accumulation_dtype: "F64 then destination encode",
        layout_rule: "accepts source torch.strided layout and publishes a physically contiguous strided Tensor",
        device_rule: "CPU certified; output and canonical transaction devices must match",
        numeric_rule: "independent standard-normal values from canonical RngTransaction Box-Muller pairs",
        tolerance: "bit exact for a fixed RNG profile and destination dtype",
        determinism: "logical row-major output order with no process-global RNG state",
        cancellation_points: "before validation, at every generated pair, during encoding, and before upload publication",
        vjp_rule: "forward-only entropy creation with no differentiable inputs; leaf registration remains owned by AutogradTape",
        jvp_rule: "forward-only entropy creation with no differentiable inputs",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-fd729b8a5363",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_02/randn.json",
        evidence_fixture_sha256: "83c2b01b02f55dfd68ac5ab052f7cf8a7ce8325280734e7c04d8b1064acae570",
    },
]
