&[
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-CB163DF58130",
        baseline_overload_id: "COMFY-TENSOR-OP-CB163DF58130:blocked",
        baseline_fixture_sha256: "7beb132edeadffedcddcb3a8aa32b324a6dc938b09e2455518c5622b1c07ae4f",
        overload_id: "sim.native.rng.generator.explicit.v1",
        ordered_parameters_json: "[{\"name\":\"profile\",\"type\":\"RngProfileVersion\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"algorithm\",\"type\":\"RngAlgorithm\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"seed\",\"type\":\"u64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"address\",\"type\":\"RngStreamAddress\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"RngStream\"]",
        rust_signature: "fn generator_exact_native(profile: RngProfileVersion, algorithm: RngAlgorithm, seed: u64, address: RngStreamAddress, cancellation: &CancellationToken) -> Result<RngStream, RandomNumberGenerationPartOneError>",
        mutation_rule: "constructs immutable canonical RngStream state",
        alias_rule: "fresh explicit stream value",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "address device is validated by the selected versioned profile",
        numeric_rule: "seed and full stream address select MT19937 or Philox state",
        tolerance: "bit exact within a profile",
        determinism: "no process-global generator state",
        cancellation_points: "before construction",
        vjp_rule: "forward-only entropy state; no differentiable inputs",
        jvp_rule: "forward-only entropy state; no differentiable inputs",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/generator.json",
        evidence_fixture_sha256: "b18178ee195d95f2fa10d18a0621ed8db9cfbfc1bb15ecda23ed314e865dcde7",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-82073E6E054A",
        baseline_overload_id: "COMFY-TENSOR-OP-82073E6E054A:blocked",
        baseline_fixture_sha256: "9ab0dc2eac68e6dd98df3fb9694b32f61d5917f62db82e0a7c68b3155c5a5c27",
        overload_id: "sim.native.rng.generator-manual-seed.explicit.v1",
        ordered_parameters_json: "[{\"name\":\"generator\",\"type\":\"&RngStream\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"seed\",\"type\":\"i128\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"RngStream\"]",
        rust_signature: "fn generator_manual_seed_exact_native(generator: &RngStream, seed: i128, cancellation: &CancellationToken) -> Result<RngStream, RandomNumberGenerationPartOneError>",
        mutation_rule: "returns a reseeded canonical stream and leaves the input stream unchanged",
        alias_rule: "fresh stream value with cloned address",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "preserves the canonical stream address device",
        numeric_rule: "accepts the documented signed-to-unsigned 64-bit seed domain",
        tolerance: "bit exact within a profile",
        determinism: "same stream identity and seed replay the same state",
        cancellation_points: "before seed validation and construction",
        vjp_rule: "forward-only entropy state",
        jvp_rule: "forward-only entropy state",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/generator_manual_seed.json",
        evidence_fixture_sha256: "b6fbde71276c6d58eb9faa52253978c6d91e7adfd0b2d1cf2a2ba6b47cadaeff",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-EA3150484FE4",
        baseline_overload_id: "COMFY-TENSOR-OP-EA3150484FE4:blocked",
        baseline_fixture_sha256: "05769b2afa0a7efdc9ba7d096d7ce5c290d1b83bf50ab0016792496a33b057ac",
        overload_id: "sim.native.rng.manual-seed.explicit.v1",
        ordered_parameters_json: "[{\"name\":\"profile\",\"type\":\"RngProfileVersion\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"algorithm\",\"type\":\"RngAlgorithm\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"seed\",\"type\":\"i128\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"address\",\"type\":\"RngStreamAddress\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"cancellation\",\"type\":\"&CancellationToken\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"}]",
        output_arity: "1",
        output_types_json: "[\"RngStream\"]",
        rust_signature: "fn manual_seed_exact_native(profile: RngProfileVersion, algorithm: RngAlgorithm, seed: i128, address: RngStreamAddress, cancellation: &CancellationToken) -> Result<RngStream, RandomNumberGenerationPartOneError>",
        mutation_rule: "projects source-global seeding into an explicit canonical stream without global mutation",
        alias_rule: "fresh stream value",
        shape_rule: "not applicable",
        dtype_rule: "not applicable",
        accumulation_dtype: "not applicable",
        layout_rule: "not applicable",
        device_rule: "explicit address device",
        numeric_rule: "documented signed-to-unsigned 64-bit seed mapping",
        tolerance: "bit exact within a profile",
        determinism: "explicit seed and address only",
        cancellation_points: "before validation and construction",
        vjp_rule: "forward-only entropy state",
        jvp_rule: "forward-only entropy state",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/manual_seed.json",
        evidence_fixture_sha256: "479b8ea5fded7d7d11e9e43f0df9e127e6c57da455523871bbe95bab6d12e09e",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-46213648166E",
        baseline_overload_id: "COMFY-TENSOR-OP-46213648166E:blocked",
        baseline_fixture_sha256: "e559505f57cebf23d9e8e6de56626f6ca1bd0350dd258489e7481c9a92e09480",
        overload_id: "sim.native.rng.multinomial.cpu-f64-weights.v1",
        ordered_parameters_json: "[{\"name\":\"weights\",\"type\":\"&[f64]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"rows\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"columns\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"sample_count\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"replacement\",\"type\":\"bool\",\"default\":false,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"transaction\",\"type\":\"RngTransaction\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Vec<i64>\",\"RngTransaction\"]",
        rust_signature: "fn multinomial_with_context_exact_native(weights: &[f64], rows: usize, columns: usize, sample_count: usize, replacement: bool, transaction: RngTransaction, device: DeviceId, context: &ExecutionContext<'_>) -> Result<MultinomialForward, RandomNumberGenerationPartOneError>",
        mutation_rule: "returns the caller transaction only after complete sampling",
        alias_rule: "fresh indices",
        shape_rule: "vector yields samples; matrix yields rows by samples",
        dtype_rule: "finite nonnegative F64 weights and I64 indices",
        accumulation_dtype: "F64",
        layout_rule: "row-major weights and draw order",
        device_rule: "CPU certified and transaction device must match the explicit output device",
        numeric_rule: "positive unnormalized weights; replacement is explicit",
        tolerance: "bit exact for a fixed RNG profile",
        determinism: "row then sample then column order",
        cancellation_points: "before validation and at bounded draws",
        vjp_rule: "forward-only discrete sampling",
        jvp_rule: "forward-only discrete sampling",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/multinomial.json",
        evidence_fixture_sha256: "08addc72cb463f7bcf5cf8117326884967d3b9721b8acd67901fd1b24ab07da2",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-3754E9847F8D",
        baseline_overload_id: "COMFY-TENSOR-OP-3754E9847F8D:blocked",
        baseline_fixture_sha256: "39226bb4f8339cb7885a27777445f23fa0a4ff43d9c397b58d64b89f3c6f81dc",
        overload_id: "sim.native.rng.normal-in-place.cpu-floating.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&mut Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"mean\",\"type\":\"f64\",\"default\":0.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"standard_deviation\",\"type\":\"f64\",\"default\":1.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"transaction\",\"type\":\"RngTransaction\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"RngTransaction\"]",
        rust_signature: "fn normal_in_place_exact_native(input: &mut Tensor, mean: f64, standard_deviation: f64, transaction: RngTransaction, cancellation: &CancellationToken) -> Result<RngTransaction, RandomNumberGenerationPartOneError>",
        mutation_rule: "copy-on-write candidate replaces input only after complete fill",
        alias_rule: "preserves aliases through canonical Tensor copy-on-write",
        shape_rule: "preserves shape",
        dtype_rule: "CPU floating Tensor",
        accumulation_dtype: "F64",
        layout_rule: "logical row-major element order",
        device_rule: "CPU Tensor and canonical transaction devices must match",
        numeric_rule: "canonical Box-Muller pairs scaled by mean and standard deviation",
        tolerance: "bit exact for a fixed RNG profile and dtype",
        determinism: "Box-Muller is owned by RngTransaction",
        cancellation_points: "before validation and every 1024 elements",
        vjp_rule: "forward-only in-place initializer",
        jvp_rule: "forward-only in-place initializer",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/normal_initializer.json",
        evidence_fixture_sha256: "324b8935af77e33d278ac34b907735d3f97d2f0fa54e96bd995b2957b12c78fd",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-4A9703265641",
        baseline_overload_id: "COMFY-TENSOR-OP-4A9703265641:blocked",
        baseline_fixture_sha256: "85a37a1b59d8edfab3d805e990a28ed55e6e756bd5b52908080e842c29c86288",
        overload_id: "sim.native.rng.uniform-in-place.cpu-floating.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&mut Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"lower\",\"type\":\"f64\",\"default\":0.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"upper\",\"type\":\"f64\",\"default\":1.0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"transaction\",\"type\":\"RngTransaction\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"RngTransaction\"]",
        rust_signature: "fn uniform_in_place_exact_native(input: &mut Tensor, lower: f64, upper: f64, transaction: RngTransaction, cancellation: &CancellationToken) -> Result<RngTransaction, RandomNumberGenerationPartOneError>",
        mutation_rule: "copy-on-write candidate replaces input only after complete fill",
        alias_rule: "preserves aliases through canonical Tensor copy-on-write",
        shape_rule: "preserves shape",
        dtype_rule: "CPU floating Tensor",
        accumulation_dtype: "F64",
        layout_rule: "logical row-major element order",
        device_rule: "CPU Tensor and canonical transaction devices must match",
        numeric_rule: "half-open finite interval [lower, upper)",
        tolerance: "bit exact for a fixed RNG profile and dtype",
        determinism: "canonical RngTransaction unit-float order",
        cancellation_points: "before validation and every 1024 elements",
        vjp_rule: "forward-only in-place initializer",
        jvp_rule: "forward-only in-place initializer",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/uniform_initializer.json",
        evidence_fixture_sha256: "493586442c5c05e7fe3ea69efda015c67ab86c227324b94cc89dbcde05fbe816",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-7745541008DF",
        baseline_overload_id: "COMFY-TENSOR-OP-7745541008DF:blocked",
        baseline_fixture_sha256: "92a7c2cbc19ec0082a68e51f61f4c4b8699ada36c506e96d0f6f31b2ea759327",
        overload_id: "sim.native.rng.sobol-engine.dimensions-1-3.v1",
        ordered_parameters_json: "[{\"name\":\"dimension\",\"type\":\"usize\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"scramble\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"seed\",\"type\":\"u64\",\"default\":0,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"SobolEngine\"]",
        rust_signature: "fn sobol_engine_exact_native(dimension: usize, scramble: bool, seed: u64, cancellation: &CancellationToken) -> Result<SobolEngine, RandomNumberGenerationPartOneError>",
        mutation_rule: "draw advances only a successful returned engine state",
        alias_rule: "engine state is an owned value",
        shape_rule: "draw returns count by dimension",
        dtype_rule: "F32 draw output",
        accumulation_dtype: "30-bit integer direction state",
        layout_rule: "sample-major then dimension-major",
        device_rule: "CPU certified",
        numeric_rule: "Bratley-Fox direction recurrence with versioned linear scramble",
        tolerance: "bit exact within native Sobol profile v1",
        determinism: "seeded stateful sequence; source dimension 3 certified",
        cancellation_points: "before construction and every 1024 draws",
        vjp_rule: "forward-only quasirandom state",
        jvp_rule: "forward-only quasirandom state",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/sobol_engine.json",
        evidence_fixture_sha256: "13e4ff6f9c0ec01836fe6a8c81434e8bdb7bf7c389a1c9008a6b60a3905770d3",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-19CD261729FC",
        baseline_overload_id: "COMFY-TENSOR-OP-19CD261729FC:blocked",
        baseline_fixture_sha256: "9b44b96adc44b66622b77b5f178b7f1c965f1ef31af2166169de009ab131888b",
        overload_id: "sim.native.rng.rand.cpu-floating.v1",
        ordered_parameters_json: "[{\"name\":\"shape\",\"type\":\"&[u64]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dtype\",\"type\":\"DType\",\"default\":\"F32\",\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"transaction\",\"type\":\"RngTransaction\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"RngTransaction\"]",
        rust_signature: "fn rand_with_context_exact_native(backend: &CpuBackend, shape: &[u64], dtype: DType, transaction: RngTransaction, context: &ExecutionContext<'_>) -> Result<RandomTensorForward, RandomNumberGenerationPartOneError>",
        mutation_rule: "fresh Tensor and transaction returned only after upload succeeds",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "exact checked requested shape",
        dtype_rule: "CPU floating dtypes",
        accumulation_dtype: "F64 then destination encode",
        layout_rule: "contiguous row-major",
        device_rule: "CPU certified and canonical transaction must address CPU",
        numeric_rule: "half-open [0,1) values",
        tolerance: "bit exact for a fixed profile and dtype",
        determinism: "logical output order",
        cancellation_points: "before validation and every 1024 elements",
        vjp_rule: "forward-only random creation",
        jvp_rule: "forward-only random creation",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/rand.json",
        evidence_fixture_sha256: "aee192b4bb8e91867a63f6e7ecf0fb212f106e153c6b2df9d0e58c49a324694c",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-095B3E192800",
        baseline_overload_id: "COMFY-TENSOR-OP-095B3E192800:blocked",
        baseline_fixture_sha256: "bcc22d80240ca4a9d6055ac84440771e800697270f34afd607c26ac4bba1f838",
        overload_id: "sim.native.rng.randint.cpu-i64.v1",
        ordered_parameters_json: "[{\"name\":\"low\",\"type\":\"i64\",\"default\":0,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"high\",\"type\":\"i64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"shape\",\"type\":\"&[u64]\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"transaction\",\"type\":\"RngTransaction\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor<I64>\",\"RngTransaction\"]",
        rust_signature: "fn randint_with_context_exact_native(backend: &CpuBackend, low: i64, high: i64, shape: &[u64], transaction: RngTransaction, context: &ExecutionContext<'_>) -> Result<RandomTensorForward, RandomNumberGenerationPartOneError>",
        mutation_rule: "fresh Tensor and transaction returned only after upload succeeds",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "exact checked requested shape",
        dtype_rule: "I64 output",
        accumulation_dtype: "U64 rejection sampling and checked I64 offset",
        layout_rule: "contiguous row-major",
        device_rule: "CPU certified and canonical transaction must address CPU",
        numeric_rule: "unbiased half-open [low,high) bounded integers",
        tolerance: "bit exact for a fixed RNG profile",
        determinism: "logical output order with rejection retained in checkpoint state",
        cancellation_points: "before validation and every 1024 elements",
        vjp_rule: "forward-only discrete creation",
        jvp_rule: "forward-only discrete creation",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/randint.json",
        evidence_fixture_sha256: "5d270dfb2cba8ace800cb152240563d27d2d3e6b2f6557dcab9682b4049440f4",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-59B309167618",
        baseline_overload_id: "COMFY-TENSOR-OP-59B309167618:blocked",
        baseline_fixture_sha256: "dca91d9dc9511732e9b0258605e0223bedd96f4bb82486410f34101bdd2258ca",
        overload_id: "sim.native.rng.randn-like.cpu-floating.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"transaction\",\"type\":\"RngTransaction\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"RngTransaction\"]",
        rust_signature: "fn randn_like_with_context_exact_native(backend: &CpuBackend, input: &Tensor, transaction: RngTransaction, context: &ExecutionContext<'_>) -> Result<RandomTensorForward, RandomNumberGenerationPartOneError>",
        mutation_rule: "fresh Tensor and transaction returned only after upload succeeds",
        alias_rule: "no input storage alias",
        shape_rule: "preserves input shape",
        dtype_rule: "preserves CPU floating dtype",
        accumulation_dtype: "F64 then destination encode",
        layout_rule: "contiguous source-compatible output",
        device_rule: "CPU certified and canonical transaction device must match the input",
        numeric_rule: "standard normal Box-Muller pairs",
        tolerance: "bit exact for a fixed RNG profile and dtype",
        determinism: "Box-Muller is owned by RngTransaction",
        cancellation_points: "before validation and at bounded pairs",
        vjp_rule: "forward-only random creation",
        jvp_rule: "forward-only random creation",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/randn_like.json",
        evidence_fixture_sha256: "1288bff5c31623c46b8342f987bf6cd2545e5dcd27149d4bfc7a517273945eb7",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-271D62B3F4FF",
        baseline_overload_id: "COMFY-TENSOR-OP-271D62B3F4FF:blocked",
        baseline_fixture_sha256: "afeb48a28663d59005dbc917808094f40d3a9968ab96d61eb392080e23e63439",
        overload_id: "sim.native.rng.randperm.cpu-i64.v1",
        ordered_parameters_json: "[{\"name\":\"count\",\"type\":\"u64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"transaction\",\"type\":\"RngTransaction\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor<I64>\",\"RngTransaction\"]",
        rust_signature: "fn randperm_with_context_exact_native(backend: &CpuBackend, count: u64, transaction: RngTransaction, context: &ExecutionContext<'_>) -> Result<RandomTensorForward, RandomNumberGenerationPartOneError>",
        mutation_rule: "fresh Tensor and transaction returned only after upload succeeds",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "one-dimensional count",
        dtype_rule: "I64 output",
        accumulation_dtype: "U64 bounded draws and I64 values",
        layout_rule: "contiguous",
        device_rule: "CPU certified and canonical transaction must address CPU",
        numeric_rule: "unbiased Fisher-Yates permutation",
        tolerance: "exact permutation and fixed-profile sequence",
        determinism: "descending Fisher-Yates order",
        cancellation_points: "before validation and every 1024 swaps",
        vjp_rule: "forward-only discrete creation",
        jvp_rule: "forward-only discrete creation",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/randperm.json",
        evidence_fixture_sha256: "2374ce1d64c1c49931b8b33156f8b42215513b3f6ac3a81c49e3764c278bbd58",
    },
    ResolvedOperationContract {
        resolution_module: "random_number_generation_01",
        operation_id: "COMFY-TENSOR-OP-E0A9E435AF72",
        baseline_overload_id: "COMFY-TENSOR-OP-E0A9E435AF72:blocked",
        baseline_fixture_sha256: "0c06f1c40a6a66b3aa38955f88e9ff085d368ee8681988bbcd3bb61b3a0eddc8",
        overload_id: "sim.native.rng.brownian-tree.cpu-f64.v1",
        ordered_parameters_json: "[{\"name\":\"start\",\"type\":\"f64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"initial\",\"type\":\"Vec<f64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"end\",\"type\":\"f64\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"entropy\",\"type\":\"u64\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"BrownianTree\"]",
        rust_signature: "fn brownian_tree_exact_native(start: f64, initial: Vec<f64>, end: f64, entropy: u64, cancellation: &CancellationToken) -> Result<BrownianTree, RandomNumberGenerationPartOneError>",
        mutation_rule: "successful interval queries atomically extend owned bridge state",
        alias_rule: "owned bridge vectors",
        shape_rule: "increments preserve initial vector length",
        dtype_rule: "finite F64 time and values",
        accumulation_dtype: "F64",
        layout_rule: "logical vector order",
        device_rule: "CPU certified",
        numeric_rule: "conditionally sampled Brownian bridges with additive cached increments",
        tolerance: "absolute 1e-12 for additivity",
        determinism: "entropy and query-order state select the path, matching torchsde's default order-sensitive contract",
        cancellation_points: "before construction and before every state publication",
        vjp_rule: "forward-only stochastic process state",
        jvp_rule: "forward-only stochastic process state",
        owner_task_id: "comfy-parity-tensor-ops-random-number-generation-comfy-tensor-op-095b3e192800",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/random_number_generation_01/brownian_tree.json",
        evidence_fixture_sha256: "abd816be2760241b84a896f598691f80ab5e3db6397f79886ef239a7e1083a90",
    },
]
