&[
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-36F99E8950F4",
        baseline_overload_id: "COMFY-TENSOR-OP-36F99E8950F4:blocked",
        baseline_fixture_sha256: "758ead0f3484e3832b9d63ea9d861ce97d9e73528b5cda300892349377a5cd7b",
        overload_id: "zed.native.reduction.tensor-all.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn tensor_all_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output is published only after complete canonical reduction and cancellation checks",
        alias_rule: "fresh contiguous boolean storage; input views remain immutable and may be noncontiguous",
        shape_rule: "None reduces every axis; unique signed axes are normalized and removed or retained at extent one",
        dtype_rule: "every canonical CPU dtype is accepted by truth-value decoding and output is bool",
        accumulation_dtype: "boolean conjunction",
        layout_rule: "logical input strides are honored and output is contiguous",
        device_rule: "CPU certified through TensorBackend::reduction; other devices fail explicitly",
        numeric_rule: "zero is false and every nonzero value, including NaN, is true; empty domains return true",
        tolerance: "bit exact",
        determinism: "fixed logical row-major traversal",
        cancellation_points: "before argument validation, at each input element, before allocation, during encoding, and before publication",
        vjp_rule: "forward-only because boolean outputs are nondifferentiable",
        jvp_rule: "forward-only because boolean outputs are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_all.json",
        evidence_fixture_sha256: "8646bee905f74984e74053d1f40869eb519a1a16d3db08b948a42e25061f249e",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-2326740E6353",
        baseline_overload_id: "COMFY-TENSOR-OP-2326740E6353:blocked",
        baseline_fixture_sha256: "0dc0f9da6db1cd89fa4e2cf8584b04ef4b6f7f54408b6b9f2f8bdcf6cb1273d2",
        overload_id: "zed.native.reduction.tensor-any.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn tensor_any_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output is published only after complete canonical reduction and cancellation checks",
        alias_rule: "fresh contiguous boolean storage with no input alias",
        shape_rule: "None reduces every axis; unique signed axes are normalized and removed or retained at extent one",
        dtype_rule: "every canonical CPU dtype is accepted by truth-value decoding and output is bool",
        accumulation_dtype: "boolean disjunction",
        layout_rule: "logical input strides are honored and output is contiguous",
        device_rule: "CPU certified through TensorBackend::reduction; other devices fail explicitly",
        numeric_rule: "zero is false and every nonzero value, including NaN, is true; empty domains return false",
        tolerance: "bit exact",
        determinism: "fixed logical row-major traversal",
        cancellation_points: "before validation, at each input element, before allocation, during encoding, and before publication",
        vjp_rule: "forward-only because boolean outputs are nondifferentiable",
        jvp_rule: "forward-only because boolean outputs are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_any.json",
        evidence_fixture_sha256: "16839f72f9ba6e56dcee65a3fdd5be3b0bcafe50f360237e3f07f1bd41c515e3",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-00E998458E0C",
        baseline_overload_id: "COMFY-TENSOR-OP-00E998458E0C:blocked",
        baseline_fixture_sha256: "9bb9b74ea47826e534d1dcadb367dbf89511599dd1f1ae9f7505cc269fdf045a",
        overload_id: "zed.native.reduction.tensor-argmax.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<i64>\"]",
        rust_signature: "fn tensor_argmax_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous i64 storage with no input alias",
        shape_rule: "None flattens the logical tensor; one normalized axis is removed or retained",
        dtype_rule: "ordered non-complex input dtypes and i64 indices",
        accumulation_dtype: "not applicable",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through TensorBackend::reduction",
        numeric_rule: "NaN wins and the first logical index wins ties; empty reduced domains error",
        tolerance: "bit exact",
        determinism: "stable first-index row-major traversal",
        cancellation_points: "before validation and at every logical element and output boundary",
        vjp_rule: "forward-only because integer indices are nondifferentiable",
        jvp_rule: "forward-only because integer indices are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_argmax.json",
        evidence_fixture_sha256: "61cc87dd3810c68d38071498aa81eca108db1fb18ea3cdbde1a1836b222c386f",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-61B9BB91A65A",
        baseline_overload_id: "COMFY-TENSOR-OP-61B9BB91A65A:blocked",
        baseline_fixture_sha256: "2cf300fcf878c3bfad0e90d433d2b40eb677727ccf11ae2af04f3ae4c19c6ae9",
        overload_id: "zed.native.reduction.tensor-max.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"Option<Tensor<i64>>\"]",
        rust_signature: "fn tensor_max_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<ReductionForward, ReductionPartOneError>",
        mutation_rule: "fresh values and optional indices only",
        alias_rule: "fresh contiguous outputs with no input alias",
        shape_rule: "None returns a scalar value; a dimension returns values and first indices with that axis removed or retained",
        dtype_rule: "values preserve ordered input dtype and indices are i64",
        accumulation_dtype: "input dtype",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through canonical value and arg reduction composition",
        numeric_rule: "NaN propagates and first logical ties supply dimension indices",
        tolerance: "bit exact for stored values",
        determinism: "stable row-major traversal",
        cancellation_points: "before validation and within both canonical reductions",
        vjp_rule: "floating values use selected-extremum gradients; index output is forward-only",
        jvp_rule: "floating values use selected-extremum tangents; index output is forward-only",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_max.json",
        evidence_fixture_sha256: "195f71881edaa5821a47c2fe2c7e7e576644d4bcb09aeecca3124b4ff59460bb",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-7821FE22568F",
        baseline_overload_id: "COMFY-TENSOR-OP-7821FE22568F:blocked",
        baseline_fixture_sha256: "748336e16dfdce42356440ce3fbba1f3a81b14b12d50fc5f6e4a8b98b3b723df",
        overload_id: "zed.native.reduction.tensor-mean.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_mean_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous output",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "F64, F32, F16, and BF16 input and requested output",
        accumulation_dtype: "deterministic f64 accumulation followed by destination encoding",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through TensorBackend::reduction",
        numeric_rule: "fixed-order sum divided by reduced count; empty domains produce NaN",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "fixed row-major accumulation",
        cancellation_points: "before validation and at each logical input and output element",
        vjp_rule: "broadcast output gradient divided by reduced element count",
        jvp_rule: "mean of input tangents over identical axes",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_mean.json",
        evidence_fixture_sha256: "b327ace6a88f179a92af144e97acbd7e50a1a03c290c2a573f3acc550a2be0af",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-5ED308A788FD",
        baseline_overload_id: "COMFY-TENSOR-OP-5ED308A788FD:blocked",
        baseline_fixture_sha256: "8eafb436c0c92bc87624b024ae3f4b17d54673471f61f9dea5c41c480d5ef227",
        overload_id: "zed.native.reduction.tensor-min.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"Option<Tensor<i64>>\"]",
        rust_signature: "fn tensor_min_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<ReductionForward, ReductionPartOneError>",
        mutation_rule: "fresh values and optional indices only",
        alias_rule: "fresh contiguous outputs",
        shape_rule: "None returns a scalar value; dimension overload returns values and first indices",
        dtype_rule: "values preserve ordered input dtype and indices are i64",
        accumulation_dtype: "input dtype",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through canonical value and arg reduction composition",
        numeric_rule: "NaN propagates and first logical ties supply dimension indices",
        tolerance: "bit exact for stored values",
        determinism: "stable row-major traversal",
        cancellation_points: "before validation and within both canonical reductions",
        vjp_rule: "floating values use selected-extremum gradients; index output is forward-only",
        jvp_rule: "floating values use selected-extremum tangents; index output is forward-only",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_min.json",
        evidence_fixture_sha256: "fa939677d2a8f7b2bb514828739fd9a247c65689be00eea7c36474bedf49b4ce",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-37C179735855",
        baseline_overload_id: "COMFY-TENSOR-OP-37C179735855:blocked",
        baseline_fixture_sha256: "4cc557cedf41e146f8797976cdd9d91981abf432994629d3a1c854d8caa1204f",
        overload_id: "zed.native.reduction.tensor-prod.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_prod_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous output",
        shape_rule: "None reduces all axes and one normalized dimension may be removed or retained",
        dtype_rule: "F64, F32, F16, and BF16",
        accumulation_dtype: "deterministic f64 accumulation followed by destination encoding",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through TensorBackend::reduction",
        numeric_rule: "fixed-order multiplication with empty-domain identity one",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "fixed row-major multiplication",
        cancellation_points: "before validation and at every logical input and output",
        vjp_rule: "zero-aware product derivative over the same reduction domain",
        jvp_rule: "sum of local zero-aware product derivatives times input tangents",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_prod.json",
        evidence_fixture_sha256: "33ee6fced089b7b441e4c8fdc348b90cae47203a37135d43f5982e673a2ab6ce",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-228E61E0B93B",
        baseline_overload_id: "COMFY-TENSOR-OP-228E61E0B93B:blocked",
        baseline_fixture_sha256: "d2516bdfc72b1f535063ea38910b987d768687539eaab2209241f5a5b0afcdb0",
        overload_id: "zed.native.reduction.tensor-var.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"correction\",\"type\":\"u64\",\"default\":1,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_var_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, correction: u64, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous output",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "F64, F32, F16, and BF16",
        accumulation_dtype: "f64 Welford mean and squared-deviation state",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through TensorBackend::reduction",
        numeric_rule: "Welford variance divided by count minus correction; nonpositive denominator yields NaN",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "fixed row-major Welford order",
        cancellation_points: "before validation and at every logical input and output",
        vjp_rule: "two times centered input divided by count minus correction times broadcast output gradient",
        jvp_rule: "reduction of the variance local derivative times input tangent",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_var.json",
        evidence_fixture_sha256: "cf1adf0621f0929cfb8999c6099329f0e50773e584ad8a6ef2c89141406c00db",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-7ED5B6B0740C",
        baseline_overload_id: "COMFY-TENSOR-OP-7ED5B6B0740C:blocked",
        baseline_fixture_sha256: "fd114ab43373955e3fcf90d8670ed53097c0591b1f1ce2d3a724a96054bdd45e",
        overload_id: "zed.native.reduction.torch-all.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn torch_all_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "functional facade maps to canonical reduction storage",
        shape_rule: "matches tensor all axis normalization and keepdim behavior",
        dtype_rule: "all canonical CPU input dtypes and boolean output",
        accumulation_dtype: "boolean conjunction",
        layout_rule: "logical strides are honored",
        device_rule: "CPU facade delegates to TensorBackend::reduction",
        numeric_rule: "nonzero truth semantics and empty true identity",
        tolerance: "bit exact",
        determinism: "fixed row-major traversal",
        cancellation_points: "identical to canonical tensor all",
        vjp_rule: "forward-only because boolean outputs are nondifferentiable",
        jvp_rule: "forward-only because boolean outputs are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/torch_all.json",
        evidence_fixture_sha256: "95cfc1d0e674bed9ce26070805c9e5934d45c06bcc1f1e0c8646512e6514b924",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-578E8375BF1C",
        baseline_overload_id: "COMFY-TENSOR-OP-578E8375BF1C:blocked",
        baseline_fixture_sha256: "851345fd119a9e395c72766c0fbf79fdf3879db477eef5ba034415754faadd78",
        overload_id: "zed.native.reduction.torch-argmin.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<i64>\"]",
        rust_signature: "fn torch_argmin_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous i64 storage",
        shape_rule: "None flattens and one normalized axis may be removed or retained",
        dtype_rule: "ordered non-complex input dtypes and i64 output",
        accumulation_dtype: "not applicable",
        layout_rule: "logical strides are honored",
        device_rule: "CPU facade delegates to canonical arg-minimum reduction",
        numeric_rule: "NaN wins and the first logical tie is returned",
        tolerance: "bit exact",
        determinism: "stable first-index traversal",
        cancellation_points: "before validation and at each input and output boundary",
        vjp_rule: "forward-only because integer indices are nondifferentiable",
        jvp_rule: "forward-only because integer indices are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/torch_argmin.json",
        evidence_fixture_sha256: "173792a55eec75919e58fe4b1e055902ce7e6926780e8c65dc930cfeb57393c7",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-5B9E7FC75162",
        baseline_overload_id: "COMFY-TENSOR-OP-5B9E7FC75162:blocked",
        baseline_fixture_sha256: "fb0a912662a3ef84a1c44e9191f09929da7296518b11115beadcee1c3a634b5e",
        overload_id: "zed.native.reduction.torch-max.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"argument\",\"type\":\"TorchMaximumArgument<'_>\",\"default\":\"All\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"Option<Tensor<i64>>\"]",
        rust_signature: "fn torch_max_with_context_exact_native(backend: &CpuBackend, input: &Tensor, argument: TorchMaximumArgument<'_>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<ReductionForward, ReductionPartOneError>",
        mutation_rule: "fresh outputs only",
        alias_rule: "reduction variants compose canonical value and arg owners; binary variant delegates to the established elementwise owner",
        shape_rule: "all, dimension, and broadcast tensor overloads retain their distinct source shapes",
        dtype_rule: "source-used f32 binary overload and ordered canonical reduction dtypes",
        accumulation_dtype: "input dtype",
        layout_rule: "logical strides and binary broadcasting are honored by their authoritative owners",
        device_rule: "CPU certified without a parallel generic max subsystem",
        numeric_rule: "NaN and first-tie reduction semantics; elementwise maximum preserves its existing semantics",
        tolerance: "bit exact for fixtures",
        determinism: "owner-defined deterministic traversal",
        cancellation_points: "before overload dispatch and within the selected authoritative operation",
        vjp_rule: "reduction values use selected-extremum gradients and binary values reuse the elementwise maximum VJP",
        jvp_rule: "reduction values use selected-extremum tangents and binary values reuse the elementwise maximum JVP",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/torch_max.json",
        evidence_fixture_sha256: "36d3e6161f2dea4546ca0fca9c1460e8eded640f9fd2754a281dfb29eaf3c002",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-955EF5B745CE",
        baseline_overload_id: "COMFY-TENSOR-OP-955EF5B745CE:blocked",
        baseline_fixture_sha256: "fc9fd74ebe17752aff87a5c8d89bfcc8460c02734ca9dc280278fab306d48913",
        overload_id: "zed.native.reduction.torch-std.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"correction\",\"type\":\"u64\",\"default\":1,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn torch_std_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, correction: u64, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous output",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "F64, F32, F16, and BF16",
        accumulation_dtype: "f64 Welford state followed by square root and destination encoding",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through TensorBackend::reduction",
        numeric_rule: "square root of Welford variance divided by count minus correction; invalid denominator yields NaN",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "fixed row-major Welford order",
        cancellation_points: "before validation and at every logical input and output",
        vjp_rule: "centered input divided by count minus correction and standard deviation times broadcast gradient",
        jvp_rule: "reduction of the standard-deviation local derivative times input tangent",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/torch_std.json",
        evidence_fixture_sha256: "dd4ff0a362aee8bc9670c2d2db5c70722ddee9b27cd82cf8d3de5783d74c8e7f",
    },
]
