&[
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-C6AA020CA8A9",
        baseline_overload_id: "COMFY-TENSOR-OP-C6AA020CA8A9:blocked",
        baseline_fixture_sha256: "a07984789c2bf4f551704e6ede5dab8b4f51244fd1cd850af756f7331c130073",
        overload_id: "sim.native.reduction.tensor-amax.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_amax_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "maximum over unique normalized axes; axes are removed or retained at extent one",
        dtype_rule: "ordered non-complex input dtype is preserved",
        accumulation_dtype: "input dtype",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "NaN propagates and whole-domain ties share analytical gradients",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "whole-domain maximum ties split the broadcast output gradient",
        jvp_rule: "whole-domain maximum tangents use the same tie split",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/tensor_amax.json",
        evidence_fixture_sha256: "227e525b856aef4c99f348b7345ea2eb19fa16e6196af09f5c30d999e1991281",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-F2192DF5C3E8",
        baseline_overload_id: "COMFY-TENSOR-OP-F2192DF5C3E8:blocked",
        baseline_fixture_sha256: "89eaac08b95d1294fc2e1498a344f0588be26c2f0a60448476e5d97c2b0e0414",
        overload_id: "sim.native.reduction.tensor-amin.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_amin_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "minimum over unique normalized axes; axes are removed or retained at extent one",
        dtype_rule: "ordered non-complex input dtype is preserved",
        accumulation_dtype: "input dtype",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "NaN propagates and whole-domain ties share analytical gradients",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "whole-domain minimum ties split the broadcast output gradient",
        jvp_rule: "whole-domain minimum tangents use the same tie split",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/tensor_amin.json",
        evidence_fixture_sha256: "2e3e91b80e7d7a81ef9769a1dc3419ce2696d3964144e5ef214808686cfa4793",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-E0B19A56E204",
        baseline_overload_id: "COMFY-TENSOR-OP-E0B19A56E204:blocked",
        baseline_fixture_sha256: "e5dda42dd004ec64a4dd2ebf8664603c911b5ad00774beeddb079a5c85145739",
        overload_id: "sim.native.reduction.tensor-argmin.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<i64>\"]",
        rust_signature: "fn tensor_argmin_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "None flattens; one normalized axis is removed or retained",
        dtype_rule: "ordered non-complex input and i64 output",
        accumulation_dtype: "not applicable",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "NaN wins and the first logical minimum index wins ties",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "forward-only because integer indices are nondifferentiable",
        jvp_rule: "forward-only because integer indices are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/tensor_argmin.json",
        evidence_fixture_sha256: "6489945635329d1e4c38ceb042ec76e422843b413b69bf686cb203e39aa73e6b",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-FD8CFCCD7A33",
        baseline_overload_id: "COMFY-TENSOR-OP-FD8CFCCD7A33:blocked",
        baseline_fixture_sha256: "426f00f30b0072f31be1361d98ae079d329374d19698c173096902d70c017eba",
        overload_id: "sim.native.reduction.tensor-std.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"correction\",\"type\":\"u64\",\"default\":1,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_std_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, correction: u64, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "F64, F32, F16, and BF16",
        accumulation_dtype: "f64 Welford state followed by destination encoding",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "square root of Welford variance divided by count minus correction; invalid denominator yields NaN",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "centered input divided by denominator and standard deviation",
        jvp_rule: "reduction of the same local derivative times the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/tensor_std.json",
        evidence_fixture_sha256: "5e7fc013d971114b2d71ccd181fa2731eb677c76b3e6883edd04a3a7d445e844",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-F5FEAF87A86C",
        baseline_overload_id: "COMFY-TENSOR-OP-F5FEAF87A86C:blocked",
        baseline_fixture_sha256: "4defdc7cd1c339c1f7d95b89aba4a7606fa521dd2bf3f9590f76c500cec933d0",
        overload_id: "sim.native.reduction.tensor-sum.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_sum_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "floating inputs preserve dtype; boolean and integral inputs default to i64; optional dtype accepts i64 or a supported floating dtype",
        accumulation_dtype: "deterministic wrapping i64 accumulation for i64 output and f64 accumulation for floating output, followed by destination encoding",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "fixed-order sum with empty-domain identity zero; boolean true values count as one",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "broadcast output gradient",
        jvp_rule: "sum of input tangents over identical axes",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/tensor_sum.json",
        evidence_fixture_sha256: "15f4d1fa3e9bc1bafa8029eefe793f0cb79db43427b75ffc8f84ee0dfe4434fe",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-A7004339E01F",
        baseline_overload_id: "COMFY-TENSOR-OP-A7004339E01F:blocked",
        baseline_fixture_sha256: "f3421749471c501b7ea1e3d04983277a9ed53e62022bfe2d328fbe78bd5b9593",
        overload_id: "sim.native.reduction.torch-amax.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn torch_amax_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "matches tensor amax normalized-axis and keepdim behavior",
        dtype_rule: "ordered non-complex input dtype is preserved",
        accumulation_dtype: "input dtype",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "delegates canonical maximum including NaN and ties",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "whole-domain maximum ties split the broadcast output gradient",
        jvp_rule: "whole-domain maximum tangents use the same tie split",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_amax.json",
        evidence_fixture_sha256: "fb64fb8578f44839461b196c2d925e75aa129bf064c88d911097f9f6df5cd42f",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-9F681B3616F6",
        baseline_overload_id: "COMFY-TENSOR-OP-9F681B3616F6:blocked",
        baseline_fixture_sha256: "11a499ad8ef5540beea7d474a7916aa501f6069e79b7f1976feb5d1f0f1322a9",
        overload_id: "sim.native.reduction.torch-any.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn torch_any_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "all canonical CPU inputs and bool output",
        accumulation_dtype: "boolean disjunction",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "zero is false, nonzero is true, and empty domains are false",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "forward-only because boolean outputs are nondifferentiable",
        jvp_rule: "forward-only because boolean outputs are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_any.json",
        evidence_fixture_sha256: "f655fb053fb42ac9bb75a2de654de4777d80449b0dedaa9d235e45f614f56015",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-C61A44CC6281",
        baseline_overload_id: "COMFY-TENSOR-OP-C61A44CC6281:blocked",
        baseline_fixture_sha256: "eda56a3ab7db0e3d4377493f7c17f0c8a67092c940a227deb63308e0f7f48a9d",
        overload_id: "sim.native.reduction.torch-argmax.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<i64>\"]",
        rust_signature: "fn torch_argmax_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "None flattens; one normalized axis is removed or retained",
        dtype_rule: "ordered non-complex input and i64 output",
        accumulation_dtype: "not applicable",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "NaN wins and the first logical maximum index wins ties",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "forward-only because integer indices are nondifferentiable",
        jvp_rule: "forward-only because integer indices are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_argmax.json",
        evidence_fixture_sha256: "82c9d1c799de1d79dd140f093933ee054403011d03b054d7b1eb45dbe7c8c475",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-FA9A98724D9A",
        baseline_overload_id: "COMFY-TENSOR-OP-FA9A98724D9A:blocked",
        baseline_fixture_sha256: "a88d740d2fa1a1b3dd57129d06443c646a06add99396b1b840c0ff99f2ae53a8",
        overload_id: "sim.native.reduction.torch-mean.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn torch_mean_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "F64, F32, F16, and BF16 input and requested output",
        accumulation_dtype: "deterministic f64 accumulation followed by destination encoding",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "fixed-order sum divided by count; empty domains yield NaN",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "broadcast output gradient divided by reduced count",
        jvp_rule: "mean of input tangents over identical axes",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_mean.json",
        evidence_fixture_sha256: "a8af5b4736db88f042b081dd1be0c8a5e0ee83993a8bfd0d369796a1d90a4efa",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-E430C5E4DFE8",
        baseline_overload_id: "COMFY-TENSOR-OP-E430C5E4DFE8:blocked",
        baseline_fixture_sha256: "f739103cd74a3b735bae07606b464dd2c5c28e9ed9398d62be046826b0101ef7",
        overload_id: "sim.native.reduction.torch-min.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"argument\",\"type\":\"TorchMinimumArgument<'_>\",\"default\":\"All\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"Option<Tensor<i64>>\"]",
        rust_signature: "fn torch_min_with_context_exact_native(backend: &CpuBackend, input: &Tensor, argument: TorchMinimumArgument<'_>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<ReductionForward, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "all, dimension, and broadcast tensor overloads retain distinct source shapes",
        dtype_rule: "source-used f32 binary overload and ordered reduction dtypes",
        accumulation_dtype: "input dtype",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "canonical NaN/tie reduction behavior and canonical binary minimum behavior",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "reduction values use canonical extremum gradients; binary overload delegates canonical minimum",
        jvp_rule: "reduction values use canonical extremum tangents; binary overload delegates canonical minimum",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_min.json",
        evidence_fixture_sha256: "643b97f25099cd6318d20d8d25af4c26423c9f8a5ef88873eeae247e653f8c6d",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-A9FBD2C51ABA",
        baseline_overload_id: "COMFY-TENSOR-OP-A9FBD2C51ABA:blocked",
        baseline_fixture_sha256: "0a536069b715e9f5db21bb59fa43cb2f2b6efda24b8cec071c56f6447db3bc91",
        overload_id: "sim.native.reduction.torch-norm.vector-norm-adapter.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"order\",\"type\":\"f64\",\"default\":2,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn torch_norm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, order: f64, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "None maps to every input axis; explicit axes and keepdim delegate canonical vector norm",
        dtype_rule: "source-used F32 tensors and optional F32 dtype",
        accumulation_dtype: "canonical vector-norm accumulator",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "Task 73 owns finite p, zero, positive infinity, and negative infinity norm behavior",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "delegates Task 73 analytical vector-norm VJP",
        jvp_rule: "delegates Task 73 analytical vector-norm JVP",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_norm.json",
        evidence_fixture_sha256: "ab1bfe13158df93fb415f0bf9cf93855a6f2fcc321fbab19adf2f9665fb76b0e",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-ADA87E1A44AA",
        baseline_overload_id: "COMFY-TENSOR-OP-ADA87E1A44AA:blocked",
        baseline_fixture_sha256: "f9fb6611ce0318bc8b9de1f5997e2d3d7929e56b8da65d1354f31a3ff083e5da",
        overload_id: "sim.native.reduction.torch-sum.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn torch_sum_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "floating inputs preserve dtype; boolean and integral inputs default to i64; optional dtype accepts i64 or a supported floating dtype",
        accumulation_dtype: "deterministic wrapping i64 accumulation for i64 output and f64 accumulation for floating output, followed by destination encoding",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "fixed-order sum with empty-domain identity zero; boolean true values count as one",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "broadcast output gradient",
        jvp_rule: "sum of input tangents over identical axes",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_sum.json",
        evidence_fixture_sha256: "6ace6124c0ae094110120d18b76e59abe77ad0ba5aa2f8a07d3ac7f1c2bf9baa",
    },
]
