&[
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-36F99E8950F4",
        baseline_overload_id: "COMFY-TENSOR-OP-36F99E8950F4:blocked",
        baseline_fixture_sha256: "95eeaa1867513ac2eccfb9a57a153da3e9ef0a74682529deb4b42af9d00e4df3",
        overload_id: "zed.native.reduction.tensor-all.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn tensor_all_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output is published only after complete canonical reduction and cancellation checks",
        alias_rule: "fresh contiguous boolean storage; input views remain immutable and may be noncontiguous",
        shape_rule: "None reduces every axis; unique signed axes are normalized and removed or retained at extent one",
        dtype_rule: "every canonical CPU dtype is accepted by truth-value decoding and output is bool",
        accumulation_dtype: "boolean conjunction",
        layout_rule: "logical input strides are honored and output is contiguous",
        device_rule: "CPU certified through TensorBackend::reduction; other devices fail explicitly",
        numeric_rule: "zero is false and every nonzero value, including NaN, is true; empty domains return true",
        tolerance: "bit exact",
        determinism: "fixed logical row-major traversal",
        cancellation_points: "before argument validation, at each input element, before allocation, during encoding, and before publication",
        vjp_rule: "forward-only because boolean outputs are nondifferentiable",
        jvp_rule: "forward-only because boolean outputs are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_all.json",
        evidence_fixture_sha256: "8ef60abac19d52a03dfe214c47df5e5bafb6702a4286c0338c3e4cbe4e47413e",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-2326740E6353",
        baseline_overload_id: "COMFY-TENSOR-OP-2326740E6353:blocked",
        baseline_fixture_sha256: "11cdc9422fd491f3d56ff2426591f75559b871551a8ed8b30a387ec910714960",
        overload_id: "zed.native.reduction.tensor-any.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn tensor_any_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output is published only after complete canonical reduction and cancellation checks",
        alias_rule: "fresh contiguous boolean storage with no input alias",
        shape_rule: "None reduces every axis; unique signed axes are normalized and removed or retained at extent one",
        dtype_rule: "every canonical CPU dtype is accepted by truth-value decoding and output is bool",
        accumulation_dtype: "boolean disjunction",
        layout_rule: "logical input strides are honored and output is contiguous",
        device_rule: "CPU certified through TensorBackend::reduction; other devices fail explicitly",
        numeric_rule: "zero is false and every nonzero value, including NaN, is true; empty domains return false",
        tolerance: "bit exact",
        determinism: "fixed logical row-major traversal",
        cancellation_points: "before validation, at each input element, before allocation, during encoding, and before publication",
        vjp_rule: "forward-only because boolean outputs are nondifferentiable",
        jvp_rule: "forward-only because boolean outputs are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_any.json",
        evidence_fixture_sha256: "2a9fb6f6aa2a3747410d8503454ef385c06161a9df47ff04739ddce8c116620f",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-00E998458E0C",
        baseline_overload_id: "COMFY-TENSOR-OP-00E998458E0C:blocked",
        baseline_fixture_sha256: "a5792fb959df9d762f7733f296f490a68e2e468616b91712af059891b0a9fba5",
        overload_id: "zed.native.reduction.tensor-argmax.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<i64>\"]",
        rust_signature: "fn tensor_argmax_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous i64 storage with no input alias",
        shape_rule: "None flattens the logical tensor; one normalized axis is removed or retained",
        dtype_rule: "ordered non-complex input dtypes and i64 indices",
        accumulation_dtype: "not applicable",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through TensorBackend::reduction",
        numeric_rule: "NaN wins and the first logical index wins ties; empty reduced domains error",
        tolerance: "bit exact",
        determinism: "stable first-index row-major traversal",
        cancellation_points: "before validation and at every logical element and output boundary",
        vjp_rule: "forward-only because integer indices are nondifferentiable",
        jvp_rule: "forward-only because integer indices are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_argmax.json",
        evidence_fixture_sha256: "52b1a4a921d56be56d916f1bc3ab560ebd881f2deb304e90e02d8e37eeeed0ee",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-61B9BB91A65A",
        baseline_overload_id: "COMFY-TENSOR-OP-61B9BB91A65A:blocked",
        baseline_fixture_sha256: "82fb71d7f94c53cbe8239fd1d03d59fd7f6a5ff5b7bc6e29110960af559b1728",
        overload_id: "zed.native.reduction.tensor-max.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"Option<Tensor<i64>>\"]",
        rust_signature: "fn tensor_max_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<ReductionForward, ReductionPartOneError>",
        mutation_rule: "fresh values and optional indices only",
        alias_rule: "fresh contiguous outputs with no input alias",
        shape_rule: "None returns a scalar value; a dimension returns values and first indices with that axis removed or retained",
        dtype_rule: "values preserve ordered input dtype and indices are i64",
        accumulation_dtype: "input dtype",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through canonical value and arg reduction composition",
        numeric_rule: "NaN propagates and first logical ties supply dimension indices",
        tolerance: "bit exact for stored values",
        determinism: "stable row-major traversal",
        cancellation_points: "before validation and within both canonical reductions",
        vjp_rule: "floating values use selected-extremum gradients; index output is forward-only",
        jvp_rule: "floating values use selected-extremum tangents; index output is forward-only",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_max.json",
        evidence_fixture_sha256: "5f10c5eda09ec61dae72c30fb571890f99c8de66ccc6ae381ba97c231ae012ad",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-7821FE22568F",
        baseline_overload_id: "COMFY-TENSOR-OP-7821FE22568F:blocked",
        baseline_fixture_sha256: "18602e9fad51b59417f9dc7cd06f36ca2807e1cd1bc5b3dc0a2687115fb85421",
        overload_id: "zed.native.reduction.tensor-mean.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_mean_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous output",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "F64, F32, F16, and BF16 input and requested output",
        accumulation_dtype: "deterministic f64 accumulation followed by destination encoding",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through TensorBackend::reduction",
        numeric_rule: "fixed-order sum divided by reduced count; empty domains produce NaN",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "fixed row-major accumulation",
        cancellation_points: "before validation and at each logical input and output element",
        vjp_rule: "broadcast output gradient divided by reduced element count",
        jvp_rule: "mean of input tangents over identical axes",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_mean.json",
        evidence_fixture_sha256: "ae0f7ceae9ff3e92be8352493b4b676fdc9e26410dda0d71368738edb1d0c2f3",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-5ED308A788FD",
        baseline_overload_id: "COMFY-TENSOR-OP-5ED308A788FD:blocked",
        baseline_fixture_sha256: "caed52d8611ce7efbbc11b8d1bdef85668415680a155ee29eec39e1a25f77e0b",
        overload_id: "zed.native.reduction.tensor-min.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"Option<Tensor<i64>>\"]",
        rust_signature: "fn tensor_min_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<ReductionForward, ReductionPartOneError>",
        mutation_rule: "fresh values and optional indices only",
        alias_rule: "fresh contiguous outputs",
        shape_rule: "None returns a scalar value; dimension overload returns values and first indices",
        dtype_rule: "values preserve ordered input dtype and indices are i64",
        accumulation_dtype: "input dtype",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through canonical value and arg reduction composition",
        numeric_rule: "NaN propagates and first logical ties supply dimension indices",
        tolerance: "bit exact for stored values",
        determinism: "stable row-major traversal",
        cancellation_points: "before validation and within both canonical reductions",
        vjp_rule: "floating values use selected-extremum gradients; index output is forward-only",
        jvp_rule: "floating values use selected-extremum tangents; index output is forward-only",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_min.json",
        evidence_fixture_sha256: "1ff8b534778317309254f0fb6458c99bec6d2dba427c0cb0e6e8bd7c9a6118af",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-37C179735855",
        baseline_overload_id: "COMFY-TENSOR-OP-37C179735855:blocked",
        baseline_fixture_sha256: "0c08a8acc26431487073bdd30b45083870d4f53a6fa1729a2fb6da7c59ba5c0e",
        overload_id: "zed.native.reduction.tensor-prod.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_prod_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous output",
        shape_rule: "None reduces all axes and one normalized dimension may be removed or retained",
        dtype_rule: "F64, F32, F16, and BF16",
        accumulation_dtype: "deterministic f64 accumulation followed by destination encoding",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through TensorBackend::reduction",
        numeric_rule: "fixed-order multiplication with empty-domain identity one",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "fixed row-major multiplication",
        cancellation_points: "before validation and at every logical input and output",
        vjp_rule: "zero-aware product derivative over the same reduction domain",
        jvp_rule: "sum of local zero-aware product derivatives times input tangents",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_prod.json",
        evidence_fixture_sha256: "c17678b1003e6f32d21461945ffbddbb0b51b2b89e6443c359daab2a5b3c65c0",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-228E61E0B93B",
        baseline_overload_id: "COMFY-TENSOR-OP-228E61E0B93B:blocked",
        baseline_fixture_sha256: "0a503cee0dd0454f611893b0d7c363e64cbe5eee59c20b4fc2232a8cadb6ba57",
        overload_id: "zed.native.reduction.tensor-var.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"correction\",\"type\":\"u64\",\"default\":1,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_var_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, correction: u64, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous output",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "F64, F32, F16, and BF16",
        accumulation_dtype: "f64 Welford mean and squared-deviation state",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through TensorBackend::reduction",
        numeric_rule: "Welford variance divided by count minus correction; nonpositive denominator yields NaN",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "fixed row-major Welford order",
        cancellation_points: "before validation and at every logical input and output",
        vjp_rule: "two times centered input divided by count minus correction times broadcast output gradient",
        jvp_rule: "reduction of the variance local derivative times input tangent",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/tensor_var.json",
        evidence_fixture_sha256: "c231ab67ff57482b0d6cf371537dfab87e81629f2ac52596ab5250ebd2728f6d",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-7ED5B6B0740C",
        baseline_overload_id: "COMFY-TENSOR-OP-7ED5B6B0740C:blocked",
        baseline_fixture_sha256: "2e58155138adf785333b2c6a13778f7e7b0fdfd059427c40f985f38970e5337e",
        overload_id: "zed.native.reduction.torch-all.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn torch_all_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "functional facade maps to canonical reduction storage",
        shape_rule: "matches tensor all axis normalization and keepdim behavior",
        dtype_rule: "all canonical CPU input dtypes and boolean output",
        accumulation_dtype: "boolean conjunction",
        layout_rule: "logical strides are honored",
        device_rule: "CPU facade delegates to TensorBackend::reduction",
        numeric_rule: "nonzero truth semantics and empty true identity",
        tolerance: "bit exact",
        determinism: "fixed row-major traversal",
        cancellation_points: "identical to canonical tensor all",
        vjp_rule: "forward-only because boolean outputs are nondifferentiable",
        jvp_rule: "forward-only because boolean outputs are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/torch_all.json",
        evidence_fixture_sha256: "37496d7dcbfb5e3983cc82684935bc73a1028a0f054f2bcd36baeab1e8ff80fe",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-578E8375BF1C",
        baseline_overload_id: "COMFY-TENSOR-OP-578E8375BF1C:blocked",
        baseline_fixture_sha256: "76d93e4080332944ebffbb4657cae043325a38ef77de12fca74b5bc092f9430f",
        overload_id: "zed.native.reduction.torch-argmin.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<i64>\"]",
        rust_signature: "fn torch_argmin_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous i64 storage",
        shape_rule: "None flattens and one normalized axis may be removed or retained",
        dtype_rule: "ordered non-complex input dtypes and i64 output",
        accumulation_dtype: "not applicable",
        layout_rule: "logical strides are honored",
        device_rule: "CPU facade delegates to canonical arg-minimum reduction",
        numeric_rule: "NaN wins and the first logical tie is returned",
        tolerance: "bit exact",
        determinism: "stable first-index traversal",
        cancellation_points: "before validation and at each input and output boundary",
        vjp_rule: "forward-only because integer indices are nondifferentiable",
        jvp_rule: "forward-only because integer indices are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/torch_argmin.json",
        evidence_fixture_sha256: "bf226659021136db43c0577ac700bbec8935d4472359b505a53b74c1d8131036",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-5B9E7FC75162",
        baseline_overload_id: "COMFY-TENSOR-OP-5B9E7FC75162:blocked",
        baseline_fixture_sha256: "ef9c2d4c0090dd38f9d4393c87e8b1819c3045657d7625d31e249e16f35f9102",
        overload_id: "zed.native.reduction.torch-max.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"argument\",\"type\":\"TorchMaximumArgument<'_>\",\"default\":\"All\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"Option<Tensor<i64>>\"]",
        rust_signature: "fn torch_max_with_context_exact_native(backend: &CpuBackend, input: &Tensor, argument: TorchMaximumArgument<'_>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<ReductionForward, ReductionPartOneError>",
        mutation_rule: "fresh outputs only",
        alias_rule: "reduction variants compose canonical value and arg owners; binary variant delegates to the established elementwise owner",
        shape_rule: "all, dimension, and broadcast tensor overloads retain their distinct source shapes",
        dtype_rule: "source-used f32 binary overload and ordered canonical reduction dtypes",
        accumulation_dtype: "input dtype",
        layout_rule: "logical strides and binary broadcasting are honored by their authoritative owners",
        device_rule: "CPU certified without a parallel generic max subsystem",
        numeric_rule: "NaN and first-tie reduction semantics; elementwise maximum preserves its existing semantics",
        tolerance: "bit exact for fixtures",
        determinism: "owner-defined deterministic traversal",
        cancellation_points: "before overload dispatch and within the selected authoritative operation",
        vjp_rule: "reduction values use selected-extremum gradients and binary values reuse the elementwise maximum VJP",
        jvp_rule: "reduction values use selected-extremum tangents and binary values reuse the elementwise maximum JVP",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/torch_max.json",
        evidence_fixture_sha256: "4ce13d2944033522eb5dcc71fa7c17626a2310199ab4df169d030158aa22e28a",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_01",
        operation_id: "COMFY-TENSOR-OP-955EF5B745CE",
        baseline_overload_id: "COMFY-TENSOR-OP-955EF5B745CE:blocked",
        baseline_fixture_sha256: "c00a1ec1068e7b6678cbaa86dd3fcfe6358cb4c1e67a403d9000aecdc13bbf25",
        overload_id: "zed.native.reduction.torch-std.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"correction\",\"type\":\"u64\",\"default\":1,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn torch_std_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, correction: u64, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartOneError>",
        mutation_rule: "fresh output only",
        alias_rule: "fresh contiguous output",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "F64, F32, F16, and BF16",
        accumulation_dtype: "f64 Welford state followed by square root and destination encoding",
        layout_rule: "logical strides are honored",
        device_rule: "CPU certified through TensorBackend::reduction",
        numeric_rule: "square root of Welford variance divided by count minus correction; invalid denominator yields NaN",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "fixed row-major Welford order",
        cancellation_points: "before validation and at every logical input and output",
        vjp_rule: "centered input divided by count minus correction and standard deviation times broadcast gradient",
        jvp_rule: "reduction of the standard-deviation local derivative times input tangent",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-00e998458e0c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_01/torch_std.json",
        evidence_fixture_sha256: "8acf522d868cace80e2616b1385220fdf20db12fe85796e4d499a2c764a9e139",
    },
]
