&[
    ResolvedOperationContract {
        resolution_module: "reduction_03",
        operation_id: "COMFY-TENSOR-OP-FF3F06B4B591",
        baseline_overload_id: "COMFY-TENSOR-OP-FF3F06B4B591:blocked",
        baseline_fixture_sha256: "b52d6a11a1bf92369e13e73db7c71d58ab594b0fcee22c3a9c78d35e2fe4b59b",
        overload_id: "zed.native.reduction.tensor-norm.vector-norm-adapter.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"order\",\"type\":\"f64\",\"default\":2,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_norm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, order: f64, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartThreeError>",
        mutation_rule: "fresh output is published only after the Task 73 canonical vector-norm owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "None uses every input axis; explicit negative or positive axes are normalized once by Task 73; keepdim retains reduced axes at extent one",
        dtype_rule: "source-confirmed F32 tensors and optional F32 dtype; other dtypes fail through Task 73",
        accumulation_dtype: "Task 73 canonical vector-norm accumulator",
        layout_rule: "logical input strides are honored and fresh vector-norm outputs are contiguous",
        device_rule: "CPU certified only through Task 73; unsupported devices fail explicitly without fallback",
        numeric_rule: "Task 73 exclusively owns finite p, zero, positive infinity, negative infinity, NaN, Inf, and signed-zero behavior",
        tolerance: "1e-5 for source-used f32 fixtures",
        determinism: "Task 73 canonical fixed traversal",
        cancellation_points: "before boundary adaptation and at Task 73 canonical workspace/traversal checkpoints; cancellation publishes no output",
        vjp_rule: "delegates Task 73 analytical vector-norm VJP",
        jvp_rule: "delegates Task 73 analytical vector-norm JVP",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-ff3f06b4b591",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_03/tensor_norm.json",
        evidence_fixture_sha256: "4805989212c090ef68c576461880e54bcb92f2842fa4a8579d652d5a668123ef",
    },
]
