&[
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-C6AA020CA8A9",
        baseline_overload_id: "COMFY-TENSOR-OP-C6AA020CA8A9:blocked",
        baseline_fixture_sha256: "2ceb4f0b8e2f07e3fba5ee37e15a79ac461d55d360840b2b7af1d337c8a6ff1b",
        overload_id: "zed.native.reduction.tensor-amax.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_amax_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "maximum over unique normalized axes; axes are removed or retained at extent one",
        dtype_rule: "ordered non-complex input dtype is preserved",
        accumulation_dtype: "input dtype",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "NaN propagates and whole-domain ties share analytical gradients",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "whole-domain maximum ties split the broadcast output gradient",
        jvp_rule: "whole-domain maximum tangents use the same tie split",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/tensor_amax.json",
        evidence_fixture_sha256: "ad225dc189bea754cc33f9f1bebbd39c302a112003b8b1095aa1833da88894ad",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-F2192DF5C3E8",
        baseline_overload_id: "COMFY-TENSOR-OP-F2192DF5C3E8:blocked",
        baseline_fixture_sha256: "51807f97f29fb7fecd9fc8fe296c77252ed5a196de7d075592b64ba685963aee",
        overload_id: "zed.native.reduction.tensor-amin.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_amin_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "minimum over unique normalized axes; axes are removed or retained at extent one",
        dtype_rule: "ordered non-complex input dtype is preserved",
        accumulation_dtype: "input dtype",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "NaN propagates and whole-domain ties share analytical gradients",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "whole-domain minimum ties split the broadcast output gradient",
        jvp_rule: "whole-domain minimum tangents use the same tie split",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/tensor_amin.json",
        evidence_fixture_sha256: "1b92b61bdaba767340b767fbd10dd265f0ca8d43271720c56ad70f63708e26e1",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-E0B19A56E204",
        baseline_overload_id: "COMFY-TENSOR-OP-E0B19A56E204:blocked",
        baseline_fixture_sha256: "6d27337ac4d88817473810dcd8b1f3aad2a0176f539414d04d80e2bc709d205b",
        overload_id: "zed.native.reduction.tensor-argmin.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<i64>\"]",
        rust_signature: "fn tensor_argmin_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "None flattens; one normalized axis is removed or retained",
        dtype_rule: "ordered non-complex input and i64 output",
        accumulation_dtype: "not applicable",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "NaN wins and the first logical minimum index wins ties",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "forward-only because integer indices are nondifferentiable",
        jvp_rule: "forward-only because integer indices are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/tensor_argmin.json",
        evidence_fixture_sha256: "0e8118dbe4afbfc84f0a49e106c90868779c7678f65e0bbd3136d0c7f98e59a2",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-FD8CFCCD7A33",
        baseline_overload_id: "COMFY-TENSOR-OP-FD8CFCCD7A33:blocked",
        baseline_fixture_sha256: "ad4b2312a9e28b21c8ef3f852f8a128b3d837fe19455a0ab6684bb5baaa6e8cf",
        overload_id: "zed.native.reduction.tensor-std.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"correction\",\"type\":\"u64\",\"default\":1,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_std_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, correction: u64, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "F64, F32, F16, and BF16",
        accumulation_dtype: "f64 Welford state followed by destination encoding",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "square root of Welford variance divided by count minus correction; invalid denominator yields NaN",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "centered input divided by denominator and standard deviation",
        jvp_rule: "reduction of the same local derivative times the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/tensor_std.json",
        evidence_fixture_sha256: "948736bd7ba87011d24b2c93c86598239d4ea6077f04631ee0bab7587f52ec6f",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-F5FEAF87A86C",
        baseline_overload_id: "COMFY-TENSOR-OP-F5FEAF87A86C:blocked",
        baseline_fixture_sha256: "3307076bc7a862ba73ccee150f5673be34c2f540293ef62c237c9f2ea6d4b935",
        overload_id: "zed.native.reduction.tensor-sum.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn tensor_sum_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "floating inputs preserve dtype; boolean and integral inputs default to i64; optional dtype accepts i64 or a supported floating dtype",
        accumulation_dtype: "deterministic wrapping i64 accumulation for i64 output and f64 accumulation for floating output, followed by destination encoding",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "fixed-order sum with empty-domain identity zero; boolean true values count as one",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "broadcast output gradient",
        jvp_rule: "sum of input tangents over identical axes",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/tensor_sum.json",
        evidence_fixture_sha256: "f909f90f7a98cd2b0c3566e70a826a2cea6a978120fcec8b760a1495af41a53e",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-A7004339E01F",
        baseline_overload_id: "COMFY-TENSOR-OP-A7004339E01F:blocked",
        baseline_fixture_sha256: "6c1a62abfdbe40cdbc4f3ffbca1d2883873d890474ca94a6de2ba06e3807ad92",
        overload_id: "zed.native.reduction.torch-amax.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn torch_amax_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "matches tensor amax normalized-axis and keepdim behavior",
        dtype_rule: "ordered non-complex input dtype is preserved",
        accumulation_dtype: "input dtype",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "delegates canonical maximum including NaN and ties",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "whole-domain maximum ties split the broadcast output gradient",
        jvp_rule: "whole-domain maximum tangents use the same tie split",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_amax.json",
        evidence_fixture_sha256: "b8ffd0afafaa752f0379431bd1ab3ef0d5596ad962258918753fcc1d97836dce",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-9F681B3616F6",
        baseline_overload_id: "COMFY-TENSOR-OP-9F681B3616F6:blocked",
        baseline_fixture_sha256: "ff1c5a028f2f5b425bddfaa676601946dc68628aaa2f26a28a3a4ab313be9c2c",
        overload_id: "zed.native.reduction.torch-any.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<bool>\"]",
        rust_signature: "fn torch_any_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "all canonical CPU inputs and bool output",
        accumulation_dtype: "boolean disjunction",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "zero is false, nonzero is true, and empty domains are false",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "forward-only because boolean outputs are nondifferentiable",
        jvp_rule: "forward-only because boolean outputs are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_any.json",
        evidence_fixture_sha256: "0d2ca43654bced1644c11ea8ec328a12681fc1ddd12422a1fa2158e6ec6928fe",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-C61A44CC6281",
        baseline_overload_id: "COMFY-TENSOR-OP-C61A44CC6281:blocked",
        baseline_fixture_sha256: "a4c2d56d117a08236efa33b9b72430579cf5f8452acadec35a0480d7a34ce9fe",
        overload_id: "zed.native.reduction.torch-argmax.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimension\",\"type\":\"Option<i64>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor<i64>\"]",
        rust_signature: "fn torch_argmax_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimension: Option<i64>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "None flattens; one normalized axis is removed or retained",
        dtype_rule: "ordered non-complex input and i64 output",
        accumulation_dtype: "not applicable",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "NaN wins and the first logical maximum index wins ties",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "forward-only because integer indices are nondifferentiable",
        jvp_rule: "forward-only because integer indices are nondifferentiable",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_argmax.json",
        evidence_fixture_sha256: "f640dcbd1d39731ce65367c22588c0263975693a0e7c161c8647f7b4313ca20a",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-FA9A98724D9A",
        baseline_overload_id: "COMFY-TENSOR-OP-FA9A98724D9A:blocked",
        baseline_fixture_sha256: "6e46e7605c9dc6d9feb579cbb470e9c83782b5b0588157d7dde5679a2a57d11d",
        overload_id: "zed.native.reduction.torch-mean.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn torch_mean_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "F64, F32, F16, and BF16 input and requested output",
        accumulation_dtype: "deterministic f64 accumulation followed by destination encoding",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "fixed-order sum divided by count; empty domains yield NaN",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "broadcast output gradient divided by reduced count",
        jvp_rule: "mean of input tangents over identical axes",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_mean.json",
        evidence_fixture_sha256: "4a42d3be812dc7c417a230b490b5be01d49c5daf2b4899a175530036d3f28189",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-E430C5E4DFE8",
        baseline_overload_id: "COMFY-TENSOR-OP-E430C5E4DFE8:blocked",
        baseline_fixture_sha256: "d45177e4e420de8b469a5776482bdea81a46930dbd3d5401d8e5981a3d3155d0",
        overload_id: "zed.native.reduction.torch-min.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"argument\",\"type\":\"TorchMinimumArgument<'_>\",\"default\":\"All\",\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "2",
        output_types_json: "[\"Tensor\",\"Option<Tensor<i64>>\"]",
        rust_signature: "fn torch_min_with_context_exact_native(backend: &CpuBackend, input: &Tensor, argument: TorchMinimumArgument<'_>, keep_dimensions: bool, context: &ExecutionContext<'_>) -> Result<ReductionForward, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "all, dimension, and broadcast tensor overloads retain distinct source shapes",
        dtype_rule: "source-used f32 binary overload and ordered reduction dtypes",
        accumulation_dtype: "input dtype",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "canonical NaN/tie reduction behavior and canonical binary minimum behavior",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "reduction values use canonical extremum gradients; binary overload delegates canonical minimum",
        jvp_rule: "reduction values use canonical extremum tangents; binary overload delegates canonical minimum",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_min.json",
        evidence_fixture_sha256: "254ebde72eedb56d6968944462d2e7b1172ce7256b6462df98d98bd3a8b9ba11",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-A9FBD2C51ABA",
        baseline_overload_id: "COMFY-TENSOR-OP-A9FBD2C51ABA:blocked",
        baseline_fixture_sha256: "b54cf5ba61fd6711ae5ff881a54f73bedb2c14a37574efc38a537305a9db8a31",
        overload_id: "zed.native.reduction.torch-norm.vector-norm-adapter.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"order\",\"type\":\"f64\",\"default\":2,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn torch_norm_with_context_exact_native(backend: &CpuBackend, input: &Tensor, order: f64, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "None maps to every input axis; explicit axes and keepdim delegate canonical vector norm",
        dtype_rule: "source-used F32 tensors and optional F32 dtype",
        accumulation_dtype: "canonical vector-norm accumulator",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "Task 73 owns finite p, zero, positive infinity, and negative infinity norm behavior",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "delegates Task 73 analytical vector-norm VJP",
        jvp_rule: "delegates Task 73 analytical vector-norm JVP",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_norm.json",
        evidence_fixture_sha256: "3c7c717e7be9cc4c77dfab2091b5732c1080c296d68ca05822cc1eafc087e1e6",
    },
    ResolvedOperationContract {
        resolution_module: "reduction_02",
        operation_id: "COMFY-TENSOR-OP-ADA87E1A44AA",
        baseline_overload_id: "COMFY-TENSOR-OP-ADA87E1A44AA:blocked",
        baseline_fixture_sha256: "fe74066fa9d4af988c8f04d7b2053530c671559c48fa555c4b93d0827f9c5c98",
        overload_id: "zed.native.reduction.torch-sum.cpu.v1",
        ordered_parameters_json: "[{\"name\":\"input\",\"type\":\"&Tensor\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"dimensions\",\"type\":\"Option<&[i64]>\",\"default\":null,\"keyword_only\":false,\"kind\":\"positional_or_keyword\"},{\"name\":\"keep_dimensions\",\"type\":\"bool\",\"default\":false,\"keyword_only\":true,\"kind\":\"keyword_only\"},{\"name\":\"dtype\",\"type\":\"Option<DType>\",\"default\":null,\"keyword_only\":true,\"kind\":\"keyword_only\"}]",
        output_arity: "1",
        output_types_json: "[\"Tensor\"]",
        rust_signature: "fn torch_sum_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: Option<&[i64]>, keep_dimensions: bool, dtype: Option<DType>, context: &ExecutionContext<'_>) -> Result<Tensor, ReductionPartTwoError>",
        mutation_rule: "fresh outputs are published only after the selected canonical owner completes",
        alias_rule: "fresh canonical-owner output with no mutable input alias",
        shape_rule: "unique normalized axes are removed or retained",
        dtype_rule: "floating inputs preserve dtype; boolean and integral inputs default to i64; optional dtype accepts i64 or a supported floating dtype",
        accumulation_dtype: "deterministic wrapping i64 accumulation for i64 output and f64 accumulation for floating output, followed by destination encoding",
        layout_rule: "logical input strides are honored and fresh reduction outputs are contiguous",
        device_rule: "CPU certified only through the pre-existing canonical owner; unsupported devices fail explicitly",
        numeric_rule: "fixed-order sum with empty-domain identity zero; boolean true values count as one",
        tolerance: "1e-5 for f32 fixtures",
        determinism: "canonical owner fixed traversal",
        cancellation_points: "before overload validation and within every selected canonical operation",
        vjp_rule: "broadcast output gradient",
        jvp_rule: "sum of input tangents over identical axes",
        owner_task_id: "comfy-parity-tensor-ops-reduction-comfy-tensor-op-9f681b3616f6",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/reduction_02/torch_sum.json",
        evidence_fixture_sha256: "64e5a10c2a4b44d416018342db7faa6bf557c73da7699ef97e05d8e7373c11ef",
    },
]
