&[
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-71DB8F99EAAC",
        baseline_overload_id: "COMFY-TENSOR-OP-71DB8F99EAAC:blocked",
        baseline_fixture_sha256: "af4c73ad354a7dccbd0508c16a568dec5a6db992de625b5430109fff9c32230b",
        overload_id: "sim.native.shape.einops-repeat.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"pattern","type":"&str"},{"default":{},"keyword_only":true,"kind":"keyword_only","name":"axis_lengths","type":"&BTreeMap<String,u64>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn einops_repeat_with_context_exact_native(backend: &CpuBackend, input: &Tensor, pattern: &str, axis_lengths: &BTreeMap<String, u64>, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation and one fresh output after complete planning",
        alias_rule: "fresh contiguous output without mutable input alias",
        shape_rule: "Task 67 grammar resolves existing and explicit new axes with ellipsis and checked products",
        dtype_rule: "all CPU tensor dtypes are copied byte exactly",
        accumulation_dtype: "f32 for VJP and not applicable to forward",
        layout_rule: "logical input strides are read and output is contiguous",
        device_rule: "CPU certified and other devices return typed unavailable",
        numeric_rule: "byte-exact repeated source mapping and deterministic f32 gradient sums",
        tolerance: "bit exact forward and 1e-6 f32 gradients",
        determinism: "fixed row-major output traversal",
        cancellation_points: "before parsing and at bounded planning and copy intervals",
        vjp_rule: "sum every repeated output gradient into its source element",
        jvp_rule: "apply the identical repeat plan to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/einops_repeat.json",
        evidence_fixture_sha256: "158c87a3850b220fc65402bab95cd18db4c7c69e0728f176843edf2015b3e4cb",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-5A4B8BBBFD81",
        baseline_overload_id: "COMFY-TENSOR-OP-5A4B8BBBFD81:blocked",
        baseline_fixture_sha256: "f1a374ef9cbf38df7c07a3060b9cf512a133eaa73d4c3ff65789937c37efa69f",
        overload_id: "sim.native.shape.tensor-chunk.split-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"chunks","type":"u64"},{"default":0,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn tensor_chunk_exact_native(input: &Tensor, chunks: u64, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no mutation and no partial output vector on failure",
        alias_rule: "Task 60 read-only narrow views share input storage",
        shape_rule: "ceil chunk size may produce fewer outputs and empty axes produce the requested count",
        dtype_rule: "dtype is preserved by views",
        accumulation_dtype: "f32 for VJP and not applicable to forward",
        layout_rule: "Task 60 preserves source strides and offsets",
        device_rule: "Task 60 CPU contract with typed unavailable elsewhere",
        numeric_rule: "no arithmetic in forward and deterministic VJP scatter",
        tolerance: "bit exact",
        determinism: "source-order split boundaries",
        cancellation_points: "before boundary resolution and at Task 60 checkpoints",
        vjp_rule: "Task 60 scatters output gradients into the input shape",
        jvp_rule: "Task 60 applies identical split views to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_chunk.json",
        evidence_fixture_sha256: "e993b80c337aa65e218a602bde50dc8270997de18c0f50e4cb20729f0856b29e",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-3D13DA91C9F3",
        baseline_overload_id: "COMFY-TENSOR-OP-3D13DA91C9F3:blocked",
        baseline_fixture_sha256: "4177935570bf32a2c5710bfaef2a393afe50822314ba2ce49b3a3910b6a257e2",
        overload_id: "sim.native.shape.tensor-expand.broadcast-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"variadic_positional","name":"sizes","type":"&[i64]"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_expand_exact_native(input: &Tensor, sizes: &[i64], cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation",
        alias_rule: "Task 63 read-only zero-stride view shares input storage",
        shape_rule: "right-aligned broadcast with -1 retaining existing dimensions and checked leading axes",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "f32 for VJP and not applicable to forward",
        layout_rule: "Task 63 owns zero-stride descriptor construction",
        device_rule: "view preserves the canonical device and stream",
        numeric_rule: "no forward arithmetic and deterministic broadcast-gradient sums",
        tolerance: "bit exact forward and 1e-6 f32 gradients",
        determinism: "fixed Task 63 traversal",
        cancellation_points: "before validation and before returning the view",
        vjp_rule: "Task 63 sums broadcast axes into the source shape",
        jvp_rule: "Task 63 broadcasts the tangent with the same shape",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_expand.json",
        evidence_fixture_sha256: "bc81a0a28a435a4a28d9e7edf5276cf0fecc6bcee16a75d8d34a07071cdcd47b",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-25362A66A957",
        baseline_overload_id: "COMFY-TENSOR-OP-25362A66A957:blocked",
        baseline_fixture_sha256: "7af781bb06aeb2916c1264c6213b893f79bcb0f34b2d0820805c80f12fc96403",
        overload_id: "sim.native.shape.tensor-expand-as.broadcast-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"&Tensor"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_expand_as_exact_native(input: &Tensor, other: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input or peer mutation",
        alias_rule: "Task 63 read-only zero-stride view shares input storage only",
        shape_rule: "target shape is exactly the peer shape and must be broadcast compatible",
        dtype_rule: "input dtype is preserved and peer dtype is irrelevant",
        accumulation_dtype: "f32 for VJP and not applicable to forward",
        layout_rule: "Task 63 owns zero-stride descriptor construction",
        device_rule: "input and peer device and stream must agree",
        numeric_rule: "no forward arithmetic and deterministic broadcast-gradient sums",
        tolerance: "bit exact forward and 1e-6 f32 gradients",
        determinism: "fixed Task 63 traversal",
        cancellation_points: "before peer validation and before returning the view",
        vjp_rule: "Task 63 sums broadcast axes into the source shape",
        jvp_rule: "Task 63 broadcasts the tangent to the peer shape",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_expand_as.json",
        evidence_fixture_sha256: "5d0f64b9b9d00a2da59ecb9b43afe263caf476071306d9b5c97ea8627b70e65f",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-67D2FDD707E0",
        baseline_overload_id: "COMFY-TENSOR-OP-67D2FDD707E0:blocked",
        baseline_fixture_sha256: "3d09e85402006b23b21e9a72f6fce71a79418b630fad635378bcc1dcb0d1c502",
        overload_id: "sim.native.shape.tensor-flatten.descriptor-view-or-copy.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":0,"keyword_only":false,"kind":"positional_or_keyword","name":"start_dimension","type":"i64"},{"default":-1,"keyword_only":false,"kind":"positional_or_keyword","name":"end_dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_flatten_with_context_exact_native(backend: &CpuBackend, input: &Tensor, start_dimension: i64, end_dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no mutation and copy publication occurs only after completion",
        alias_rule: "compatible strides return a read-only view and incompatible strides return a fresh copy",
        shape_rule: "inclusive normalized dimension interval collapses to its checked product",
        dtype_rule: "dtype is preserved byte exactly",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor alone decides view compatibility and CpuBackend alone copies fallback storage",
        device_rule: "views preserve device while copy fallback is CPU certified",
        numeric_rule: "logical element order is byte exact",
        tolerance: "bit exact",
        determinism: "fixed logical row-major fallback traversal",
        cancellation_points: "before shape resolution and throughout CpuBackend copy",
        vjp_rule: "reshape the output gradient to the input shape",
        jvp_rule: "apply the same flatten view-or-copy rule to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_flatten.json",
        evidence_fixture_sha256: "bc520ef02e159deb24e772bda7642e9cba3988c1364293ca073761b66e44666b",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-73D179A8CEB9",
        baseline_overload_id: "COMFY-TENSOR-OP-73D179A8CEB9:blocked",
        baseline_fixture_sha256: "f763a2aee21f2575cf5b6f964a12b9671c8fa62111f85ee247ba8edf04361688",
        overload_id: "sim.native.shape.tensor-movedim.descriptor-view.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"source","type":"&[i64]"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"destination","type":"&[i64]"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_movedim_exact_native(input: &Tensor, source: &[i64], destination: &[i64], cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation",
        alias_rule: "read-only descriptor view shares input storage",
        shape_rule: "unique normalized source axes are inserted at unique normalized destination axes",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "shape and strides are permuted without materialization",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "stable destination-order insertion",
        cancellation_points: "before axis validation and before returning the view",
        vjp_rule: "move destination axes back to source positions",
        jvp_rule: "apply the identical movement to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_movedim.json",
        evidence_fixture_sha256: "b611d45a63bb8c764957543880888bdcdd27ee2566b5606f4e3e09e6f9b0688d",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-3E6301EB6AA6",
        baseline_overload_id: "COMFY-TENSOR-OP-3E6301EB6AA6:blocked",
        baseline_fixture_sha256: "08da44687a80da9d34585402bd3f992d95e11fb69c4a0917c4cb803f98d516b5",
        overload_id: "sim.native.shape.tensor-repeat-interleave.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"repeats","type":"RepeatInterleaveSpec<'_>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"Option<i64>"},{"default":null,"keyword_only":true,"kind":"keyword_only","name":"output_size","type":"Option<u64>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_repeat_interleave_with_context_exact_native(backend: &CpuBackend, input: &Tensor, repeats: RepeatInterleaveSpec<'_>, dimension: Option<i64>, output_size: Option<u64>, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no mutation and fresh output after complete traversal",
        alias_rule: "fresh contiguous output",
        shape_rule: "scalar, slice, or scalar/one-dimensional integer-tensor counts expand the selected axis and omitted dimension flattens first",
        dtype_rule: "all CPU input dtypes copy byte exactly; tensor repeat counts require an I32 or I64 dtype",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "logical input strides are read and output is contiguous",
        device_rule: "CPU certified and other devices return typed unavailable",
        numeric_rule: "byte-exact forward and fixed source-order gradient sums",
        tolerance: "bit exact forward and 1e-6 f32 gradients",
        determinism: "fixed row-major traversal",
        cancellation_points: "before validation and at bounded traversal intervals",
        vjp_rule: "sum repeated output gradients into each source element",
        jvp_rule: "repeat the tangent with the identical counts",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_repeat_interleave.json",
        evidence_fixture_sha256: "862704fe9c791394baf13575131b58885b8245774e55e9c03216d2bdb7e55704",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-17E7C823A86F",
        baseline_overload_id: "COMFY-TENSOR-OP-17E7C823A86F:blocked",
        baseline_fixture_sha256: "bf685ab46de2b59caa469fb4429988f6dbfe192a170b5116260eb7c14ea9581f",
        overload_id: "sim.native.shape.tensor-unsqueeze.descriptor-view.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_unsqueeze_exact_native(input: &Tensor, dimension: i64, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation",
        alias_rule: "read-only descriptor view shares input storage",
        shape_rule: "one normalized insertion axis is added at extent one",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical descriptor owns checked inserted stride and storage bounds",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "single checked descriptor transformation",
        cancellation_points: "before axis validation and before returning the view",
        vjp_rule: "remove the inserted extent-one axis by a checked view",
        jvp_rule: "insert the same axis into the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_unsqueeze.json",
        evidence_fixture_sha256: "f2de2de77480b9fa9d349674270e7be579887f884ceaf9ed1fe8d930fda7c8d6",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-5380FDF9E668",
        baseline_overload_id: "COMFY-TENSOR-OP-5380FDF9E668:blocked",
        baseline_fixture_sha256: "baabe9083b0919508313a5f9f30b2ef1d86756f469c977e3888251c363bb9acd",
        overload_id: "sim.native.shape.tensor-view.shape-and-dtype.canonical-descriptor.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"specification","type":"TensorViewSpec<'_>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_view_exact_native(input: &Tensor, specification: TensorViewSpec<'_>, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation",
        alias_rule: "read-only compatible-stride shape views and checked dtype reinterpretations share input storage",
        shape_rule: "shape form permits one inferred dimension; dtype form rescales the last dimension, strides, and storage offset under PyTorch alignment rules",
        dtype_rule: "shape form preserves dtype; dtype form reinterprets exact bytes without numeric conversion",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor is the sole compatible-stride, dtype-reinterpretation, alignment, and storage-bounds validator",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic; dtype form is byte exact",
        tolerance: "bit exact",
        determinism: "single canonical descriptor transformation",
        cancellation_points: "before specification validation and before returning the view",
        vjp_rule: "shape view has a checked inverse view; dtype reinterpretation is forward-only and non-differentiable",
        jvp_rule: "shape view applies the identical view to the tangent; dtype reinterpretation is forward-only and non-differentiable",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_view.json",
        evidence_fixture_sha256: "3b1130a82a1dd45075bc3fb5a6a5af096b9d5c9267e680869fecfc406d8e47dc",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-47B154B1D223",
        baseline_overload_id: "COMFY-TENSOR-OP-47B154B1D223:blocked",
        baseline_fixture_sha256: "269a47da038d1fdf78d8619845b9eded1ea8307b9cb68930d706290d915f2d45",
        overload_id: "sim.native.shape.torch-chunk.tensor-chunk-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"chunks","type":"u64"},{"default":0,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn torch_chunk_exact_native(input: &Tensor, chunks: u64, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no mutation and no partial output vector on failure",
        alias_rule: "delegates Tensor.chunk read-only Task 60 split views",
        shape_rule: "identical to Tensor.chunk ceil-size boundaries",
        dtype_rule: "dtype is preserved by views",
        accumulation_dtype: "f32 for VJP and not applicable to forward",
        layout_rule: "Task 60 preserves source strides and offsets",
        device_rule: "Task 60 CPU contract with typed unavailable elsewhere",
        numeric_rule: "no arithmetic in forward and deterministic VJP scatter",
        tolerance: "bit exact",
        determinism: "source-order split boundaries",
        cancellation_points: "before facade delegation and at Task 60 checkpoints",
        vjp_rule: "delegates the canonical chunk gradient path",
        jvp_rule: "delegates the canonical chunk tangent path",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/torch_chunk.json",
        evidence_fixture_sha256: "4079d4531c598041052a01daad18d4b0475ead0fdd89d82edb73169711245357",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-0C2E0712DA68",
        baseline_overload_id: "COMFY-TENSOR-OP-0C2E0712DA68:blocked",
        baseline_fixture_sha256: "5281db6e1cffe1f4f4a03567113b7315220b86ec90d0e17950fb91826a283600",
        overload_id: "sim.native.shape.torch-repeat-interleave.tensor-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"repeats","type":"RepeatInterleaveSpec<'_>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"Option<i64>"},{"default":null,"keyword_only":true,"kind":"keyword_only","name":"output_size","type":"Option<u64>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_repeat_interleave_with_context_exact_native(backend: &CpuBackend, input: &Tensor, repeats: RepeatInterleaveSpec<'_>, dimension: Option<i64>, output_size: Option<u64>, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no mutation and delegates one fresh canonical output",
        alias_rule: "delegates Tensor.repeat_interleave fresh contiguous output",
        shape_rule: "identical scalar, slice, scalar/one-dimensional integer-tensor, optional-axis, and output-size rules",
        dtype_rule: "all CPU input dtypes copy byte exactly; tensor repeat counts require an I32 or I64 dtype",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "logical input strides are read and output is contiguous",
        device_rule: "CPU certified and other devices return typed unavailable",
        numeric_rule: "byte-exact forward and fixed source-order gradient sums",
        tolerance: "bit exact forward and 1e-6 f32 gradients",
        determinism: "fixed row-major traversal",
        cancellation_points: "before facade delegation and at bounded traversal intervals",
        vjp_rule: "delegates the canonical repeated-axis gradient sum",
        jvp_rule: "delegates the canonical repeated tangent path",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/torch_repeat_interleave.json",
        evidence_fixture_sha256: "84b24f30f0b0b1aefb368e128a16ffcd880ba5d587e4d161f9742c57a2b39b3a",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-3E9A0E130935",
        baseline_overload_id: "COMFY-TENSOR-OP-3E9A0E130935:blocked",
        baseline_fixture_sha256: "c8bd9bd12344e8aab11fc75fa3573e12880bca5f26c8b8c304b798ce2c9fdc60",
        overload_id: "sim.native.shape.torch-unsqueeze.tensor-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_unsqueeze_exact_native(input: &Tensor, dimension: i64, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation",
        alias_rule: "delegates Tensor.unsqueeze read-only descriptor view",
        shape_rule: "one normalized insertion axis is added at extent one",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical descriptor owns checked inserted stride and storage bounds",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "single checked descriptor transformation",
        cancellation_points: "before facade delegation and before returning the view",
        vjp_rule: "delegates the canonical checked inverse view",
        jvp_rule: "delegates the canonical tangent unsqueeze",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/torch_unsqueeze.json",
        evidence_fixture_sha256: "62255ce6f5ec3e7770d4f702ecbbb59c7d6476038a5193d41c6db6726ae29406",
    },
]
