&[
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_03",
        operation_id: "COMFY-TENSOR-OP-FC2184DD3E3D",
        baseline_overload_id: "COMFY-TENSOR-OP-FC2184DD3E3D:blocked",
        baseline_fixture_sha256: "e4a74fec8b890892f94d9a381e2d799fa16ca00e05644932555bce605c164792",
        overload_id: "zed.native.shape.tensor-permute.descriptor-view.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"variadic_positional","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_permute_exact_native(input: &Tensor, dimensions: &[i64], cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartThreeError>",
        mutation_rule: "no mutation",
        alias_rule: "read-only view shares input storage",
        shape_rule: "dimensions are a unique complete normalized rank permutation",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor is the sole permutation validator",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "declared permutation order",
        cancellation_points: "before validation and before returning the alias",
        vjp_rule: "apply the inverse canonical permutation",
        jvp_rule: "apply the identical permutation to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-df605ed35114",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_03/tensor_permute.json",
        evidence_fixture_sha256: "7972073c3bd2aad9ce3351d488cb667c750fd7e36998908fc8b671e34b370043",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_03",
        operation_id: "COMFY-TENSOR-OP-E1ADB7F2ED49",
        baseline_overload_id: "COMFY-TENSOR-OP-E1ADB7F2ED49:blocked",
        baseline_fixture_sha256: "66046083cea6c8a0289de3f685e1ec552f9e25cf59e41399adce778955771426",
        overload_id: "zed.native.shape.tensor-split.task60-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"specification","type":"&TensorSplitSpec","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn tensor_split_exact_native_part_three(input: &Tensor, specification: &TensorSplitSpec, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartThreeError>",
        mutation_rule: "no mutation and no partial result on failure",
        alias_rule: "Task 60 read-only narrow views share input storage",
        shape_rule: "positive split size or explicit nonnegative sizes partition the selected extent exactly",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "Task 60 owns boundaries, narrow views, and gradient scatter",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "no forward arithmetic and deterministic scatter",
        tolerance: "bit exact",
        determinism: "source-order segments",
        cancellation_points: "before adapter validation and at Task 60 checkpoints",
        vjp_rule: "Task 60 scatters output gradients to source ranges",
        jvp_rule: "Task 60 splits the tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-df605ed35114",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_03/tensor_split.json",
        evidence_fixture_sha256: "bac958e63b8755d8a2905adc10d19a446b4a693b9acf12e0b5c0c586b4502cf2",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_03",
        operation_id: "COMFY-TENSOR-OP-ED0C08B31410",
        baseline_overload_id: "COMFY-TENSOR-OP-ED0C08B31410:blocked",
        baseline_fixture_sha256: "76885b89b26157b1fc590fb6845c589e0fa817085ebc76b1d0b52f24d57eba5b",
        overload_id: "zed.native.shape.tensor-squeeze.descriptor-view.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"Option<&[i64]>","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_squeeze_exact_native(input: &Tensor, dimensions: Option<&[i64]>, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartThreeError>",
        mutation_rule: "no mutation",
        alias_rule: "read-only view shares input storage",
        shape_rule: "without dimensions remove every singleton axis; selected singleton axes are removed while selected non-singletons remain",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor is the sole squeezed shape/stride validator",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "ascending input-axis order",
        cancellation_points: "before validation and before returning the alias",
        vjp_rule: "Task 86 reshapes the output gradient to the input shape",
        jvp_rule: "squeeze the tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-df605ed35114",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_03/tensor_squeeze.json",
        evidence_fixture_sha256: "c9c4e3fa8239ced427df5d8f0b7dd315493efce1d07c334892ae85da966336c2",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_03",
        operation_id: "COMFY-TENSOR-OP-DF605ED35114",
        baseline_overload_id: "COMFY-TENSOR-OP-DF605ED35114:blocked",
        baseline_fixture_sha256: "e6b1f37fe2a286fc05695eb6705254595c48452555d528e07e5464181c521742",
        overload_id: "zed.native.shape.tensor-transpose.descriptor-view.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"first_dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"second_dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_transpose_exact_native(input: &Tensor, first_dimension: i64, second_dimension: i64, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartThreeError>",
        mutation_rule: "no mutation",
        alias_rule: "read-only view shares input storage",
        shape_rule: "normalize and swap exactly two axes",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor is the sole permutation validator",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "one checked axis swap",
        cancellation_points: "before validation and before returning the alias",
        vjp_rule: "transpose the same axes because the map is self-inverse",
        jvp_rule: "transpose the tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-df605ed35114",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_03/tensor_transpose.json",
        evidence_fixture_sha256: "440b1b412fa9f67ce9b525569d8135d6a51d8652528e88354757e51650e5bba5",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_03",
        operation_id: "COMFY-TENSOR-OP-E867958E2F71",
        baseline_overload_id: "COMFY-TENSOR-OP-E867958E2F71:blocked",
        baseline_fixture_sha256: "f1196fb8fd2392a1db5b504db21914800abbbca8d7561a8e55bf193cac24bc29",
        overload_id: "zed.native.shape.functional-pad.canonical-coordinate-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"padding","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"mode","type":"FunctionalPadMode","kind":"positional_or_keyword","keyword_only":false,"default":"constant"},{"name":"value","type":"Option<DecodedScalar>","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn functional_pad_with_context_exact_native(backend: &CpuBackend, input: &Tensor, padding: &[i64], mode: FunctionalPadMode, value: Option<DecodedScalar>, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartThreeError>",
        mutation_rule: "no mutation and one publication after complete staging",
        alias_rule: "fresh contiguous output",
        shape_rule: "even trailing-axis padding supports checked positive extension and negative crop; nonconstant mode constraints are validated before traversal",
        dtype_rule: "forward preserves every CPU dtype and encodes constant values through the canonical DType codec",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "canonical padding coordinates map logical strided input elements and CpuBackend owns exact workspace and publication",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "byte-exact forward copies and deterministic f32 gradient accumulation",
        tolerance: "bit exact forward and 1e-6 gradients",
        determinism: "fixed row-major output traversal",
        cancellation_points: "before validation, every 64 elements, and before publication",
        vjp_rule: "sum output gradients into every canonical mapped source coordinate and discard constant cells",
        jvp_rule: "pad the tangent identically with zero constant cells",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-df605ed35114",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_03/functional_pad.json",
        evidence_fixture_sha256: "2eb43da6317bbba77f417166250fc602aa0edbb16768800609c350ca6b183f1c",
    },
]
