&[
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-AED8D6D11C0F",
        baseline_overload_id: "COMFY-TENSOR-OP-AED8D6D11C0F:blocked",
        baseline_fixture_sha256: "36d22c2bfe4527c2701cbf927e6acbd143b11b720f445f9e1bef8255b2860c24",
        overload_id: "zed.native.shape.tensor-repeat.tile-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"repeats","type":"&[i64]","kind":"variadic_positional","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_repeat_with_context_exact_native(backend: &CpuBackend, input: &Tensor, repeats: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation and publication only after the canonical tile traversal completes",
        alias_rule: "fresh contiguous output",
        shape_rule: "repeat rank must cover input rank and each output extent is the checked product of its aligned input extent and repeat count",
        dtype_rule: "all CPU dtypes copy byte exactly",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "Task 80 canonical tile owner reads logical strides and publishes contiguous output",
        device_rule: "CPU certified; other devices return typed unavailable",
        numeric_rule: "byte-exact repeat mapping and deterministic f32 gradient sums",
        tolerance: "bit exact forward and 1e-6 gradients",
        determinism: "Task 80 fixed row-major traversal",
        cancellation_points: "before validation and at Task 80 bounded traversal checkpoints",
        vjp_rule: "Task 80 sums repeated output gradients into aligned input elements",
        jvp_rule: "Task 80 repeats the tangent with identical counts",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/tensor_repeat.json",
        evidence_fixture_sha256: "0ebb9504a84309bd5950b13297d230e58f67eab67d1c5907438540d1841f5ffb",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-CBDBBB4DF32F",
        baseline_overload_id: "COMFY-TENSOR-OP-CBDBBB4DF32F:blocked",
        baseline_fixture_sha256: "7445e9b8bb4ac43145844634baf54cd84699a9acb4c0b0b6a0e39279dfb74d9a",
        overload_id: "zed.native.shape.tensor-reshape.task86-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"shape","type":"&[i64]","kind":"variadic_positional","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_reshape_with_context_exact_native(backend: &CpuBackend, input: &Tensor, shape: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "compatible strides return a read-only alias; incompatible strides use one canonical copy",
        shape_rule: "one inferred dimension and exact checked element-count preservation",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor owns compatible reshape validation and CpuBackend owns copy fallback",
        device_rule: "views preserve device; copy fallback is CPU-certified with typed unavailability elsewhere",
        numeric_rule: "no arithmetic and byte-exact copy fallback",
        tolerance: "bit exact",
        determinism: "single descriptor decision followed by fixed copy traversal when required",
        cancellation_points: "before validation and at canonical copy checkpoints",
        vjp_rule: "reshape the output gradient to the input shape",
        jvp_rule: "apply the identical reshape decision to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/tensor_reshape.json",
        evidence_fixture_sha256: "286b0aaa1b8608957992545abe0770f25829851155cf8b59703ed0e5acde10a1",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-CA47A2C1F7CF",
        baseline_overload_id: "COMFY-TENSOR-OP-CA47A2C1F7CF:blocked",
        baseline_fixture_sha256: "72b0c6777ad7abcedddcd69d27a9b0d83aa0b1140b22dd75fd98e2c5cd6f11db",
        overload_id: "zed.native.shape.tensor-unbind.narrow-view-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn tensor_unbind_exact_native(input: &Tensor, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation and no partial output vector on failure",
        alias_rule: "Task 60 narrow views with the selected singleton axis removed share storage read-only",
        shape_rule: "one output per selected-axis element; an empty axis yields no outputs",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "TensorDescriptor validates squeezed strided views",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "no forward arithmetic",
        tolerance: "bit exact",
        determinism: "ascending selected-axis order",
        cancellation_points: "before validation and every 64 outputs",
        vjp_rule: "stack output gradients on the removed axis",
        jvp_rule: "unbind the tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/tensor_unbind.json",
        evidence_fixture_sha256: "02d43c4afd1962d88958903cb70b62fafa4c121fe14fbf6a402a48e82712b20f",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-868899CC3FD0",
        baseline_overload_id: "COMFY-TENSOR-OP-868899CC3FD0:blocked",
        baseline_fixture_sha256: "4a6a1199ba032a0bdd5b22a2c33aeef1587c5167a9f8f120d135ce439c58d3a8",
        overload_id: "zed.native.shape.tensor-view-as.task86-view-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"other","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_view_as_exact_native(input: &Tensor, other: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "read-only alias of input storage only",
        shape_rule: "target shape equals other.shape and must be compatible with input strides and element count",
        dtype_rule: "input dtype is preserved and other dtype is irrelevant",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor is the sole compatible-view validator",
        device_rule: "input device is preserved and streams must agree",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "one descriptor transformation",
        cancellation_points: "before validation and before returning the alias",
        vjp_rule: "inverse view to the input shape",
        jvp_rule: "apply the same view to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/tensor_view_as.json",
        evidence_fixture_sha256: "3d6769f4f32506e5d0182e9a7ed4f7f04d85cd245822d49703679fb525a1220a",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-A125CEF23550",
        baseline_overload_id: "COMFY-TENSOR-OP-A125CEF23550:blocked",
        baseline_fixture_sha256: "81532cefe38b3cc707aec83b18a6ef17691af93a6dbd621a4079f0bd026c2004",
        overload_id: "zed.native.shape.torch-cat.concatenate-adapter.v1",
        ordered_parameters_json: r#"[{"name":"inputs","type":"&[Tensor]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_cat_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no input mutation and one publication after the canonical concatenate traversal",
        alias_rule: "fresh contiguous output",
        shape_rule: "non-axis dimensions match and selected extents sum with overflow checks",
        dtype_rule: "all inputs require one exact dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "Task 64 canonical concatenate owner reads logical strides and publishes contiguous output",
        device_rule: "CPU inputs on one stream; other devices typed unavailable",
        numeric_rule: "byte-exact concatenation",
        tolerance: "bit exact",
        determinism: "input order then row-major element order",
        cancellation_points: "before facade validation and at canonical concatenate checkpoints",
        vjp_rule: "Task 64 slices the output gradient by input extents",
        jvp_rule: "Task 64 concatenates input tangents identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_cat.json",
        evidence_fixture_sha256: "30b038ebe02123c0a0fc4dc72d2be043184ff08a380c3fbfc5507c80a62a78e6",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-B4740B5E4B4D",
        baseline_overload_id: "COMFY-TENSOR-OP-B4740B5E4B4D:blocked",
        baseline_fixture_sha256: "0b83c286f4f998eed1e01b184426cbffb1e59896d77456ab313c2ae5b0528483",
        overload_id: "zed.native.shape.torch-flatten.task86-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"start_dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0},{"name":"end_dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":-1}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_flatten_with_context_exact_native(backend: &CpuBackend, input: &Tensor, start_dimension: i64, end_dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "Task 86 returns a compatible read-only view or one canonical copy fallback",
        shape_rule: "merge the inclusive normalized axis range with checked products",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "Task 86 and TensorDescriptor own view-versus-copy behavior",
        device_rule: "views preserve device; copy fallback is CPU certified",
        numeric_rule: "no arithmetic and byte-exact copy fallback",
        tolerance: "bit exact",
        determinism: "Task 86 canonical path",
        cancellation_points: "Task 86 validation and copy checkpoints",
        vjp_rule: "reshape gradient to the input shape",
        jvp_rule: "flatten tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_flatten.json",
        evidence_fixture_sha256: "78692b537a1f87786f393af9ab4c6f3c3f48a991a11f994a04d875186294f14f",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-A4C280408637",
        baseline_overload_id: "COMFY-TENSOR-OP-A4C280408637:blocked",
        baseline_fixture_sha256: "841093220dfebbac841acaa34c6966faae0b868833f1eb8770726a59a0bf495f",
        overload_id: "zed.native.shape.torch-movedim.task86-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"source","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"destination","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_movedim_exact_native(input: &Tensor, source: &[i64], destination: &[i64], cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "read-only view shares input storage",
        shape_rule: "unique normalized source axes move to unique normalized destinations",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "Task 86 plans the permutation and TensorDescriptor owns its strided view",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "stable unmoved-axis order",
        cancellation_points: "before validation and before returning the view",
        vjp_rule: "swap source and destination",
        jvp_rule: "apply identical movement to tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_movedim.json",
        evidence_fixture_sha256: "94bfa0aa16357902fc6a36f4d7386b57865d20aee4106d3e7542f15e38f7d418",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-890C284C875F",
        baseline_overload_id: "COMFY-TENSOR-OP-890C284C875F:blocked",
        baseline_fixture_sha256: "1dfd5dd4c658904cc8cd98a0a31c4f7d71bd4c3a09faf6c5e526664482aac2a1",
        overload_id: "zed.native.shape.torch-permute.descriptor-view.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_permute_exact_native(input: &Tensor, dimensions: &[i64], cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "read-only view shares input storage",
        shape_rule: "dimensions are a unique complete normalized rank permutation",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor is the sole permutation shape/stride/storage validator",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "declared permutation order",
        cancellation_points: "before validation and before returning the view",
        vjp_rule: "apply the inverse permutation",
        jvp_rule: "apply the same permutation to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_permute.json",
        evidence_fixture_sha256: "09eb5072777fd85c945b290a19a0772a0b17f54498248b9f567bf5007d839eb5",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-B918E3498A97",
        baseline_overload_id: "COMFY-TENSOR-OP-B918E3498A97:blocked",
        baseline_fixture_sha256: "251026e7788e7383ddca433ae836c2c3fe8af7313dcccf3da60d8047b32ab49e",
        overload_id: "zed.native.shape.torch-reshape.task86-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"shape","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_reshape_with_context_exact_native(backend: &CpuBackend, input: &Tensor, shape: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "compatible strides alias read-only; incompatible strides copy once",
        shape_rule: "one inferred dimension and exact checked element count",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "Task 86 and TensorDescriptor own reshape view-or-copy behavior",
        device_rule: "views preserve device; CPU copy fallback only",
        numeric_rule: "no arithmetic and byte-exact copy",
        tolerance: "bit exact",
        determinism: "canonical descriptor decision",
        cancellation_points: "before validation and canonical copy checkpoints",
        vjp_rule: "reshape gradient to input shape",
        jvp_rule: "reshape tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_reshape.json",
        evidence_fixture_sha256: "a87d0270a8a2d88fbf962c0ca4797e7f6e0cc6d7fb439fe68f2b872e50652965",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-D4BF78DE58FC",
        baseline_overload_id: "COMFY-TENSOR-OP-D4BF78DE58FC:blocked",
        baseline_fixture_sha256: "c40c044136e3e04e04e06f0b9ef77dcd37adf26043392fe9cc0e6b09e81f59e8",
        overload_id: "zed.native.shape.torch-split.task60-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"specification","type":"TorchSplitSpec<'_>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn torch_split_exact_native(input: &Tensor, specification: TorchSplitSpec<'_>, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation and no partial vector on failure",
        alias_rule: "Task 60 read-only narrow views share input storage",
        shape_rule: "positive split size yields consecutive chunks with a smaller tail; explicit nonnegative sizes must sum exactly",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "Task 60 owns split boundaries, view construction, and gradient scatter",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "no forward arithmetic and deterministic gradient scatter",
        tolerance: "bit exact",
        determinism: "source-order boundaries",
        cancellation_points: "before facade validation and at Task 60 checkpoints",
        vjp_rule: "Task 60 scatters output gradients to their source ranges",
        jvp_rule: "Task 60 splits the tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_split.json",
        evidence_fixture_sha256: "19ba3261c10b6ec76b182e9a21dfbf6c45fd418af6fa7e9f3c2e57b38d0aec02",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-C99C862C91E1",
        baseline_overload_id: "COMFY-TENSOR-OP-C99C862C91E1:blocked",
        baseline_fixture_sha256: "b49c401da07c66604202e73b4dca060b36c9a89e5890b664e4d6c5583984f2fd",
        overload_id: "zed.native.shape.torch-stack.unsqueeze-concatenate-adapter.v1",
        ordered_parameters_json: r#"[{"name":"inputs","type":"&[Tensor]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_stack_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation and one publication after complete composition",
        alias_rule: "Task 86 temporary read-only unsqueeze views feed a fresh canonical concatenate output",
        shape_rule: "equal input shapes gain one insertion axis whose extent is input count",
        dtype_rule: "all inputs require one exact dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "Task 86 owns unsqueeze views and Task 64 owns concatenate traversal",
        device_rule: "CPU inputs on one stream",
        numeric_rule: "byte-exact composition",
        tolerance: "bit exact",
        determinism: "input order and canonical concatenate traversal",
        cancellation_points: "before composition, per input view, and canonical concatenate checkpoints",
        vjp_rule: "unbind the output gradient along the inserted axis",
        jvp_rule: "stack tangents identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_stack.json",
        evidence_fixture_sha256: "1814f3232bc6fcd117b1eef0b1ec485a97123fc117a5f3ab27995dd47625962f",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-75596B7E1112",
        baseline_overload_id: "COMFY-TENSOR-OP-75596B7E1112:blocked",
        baseline_fixture_sha256: "e3e524e9da3e8095c191c11d88009c4508bd5a1ee02462936be9e4489cf71a1c",
        overload_id: "zed.native.shape.torch-unbind.tensor-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn torch_unbind_exact_native(input: &Tensor, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation and no partial vector on failure",
        alias_rule: "delegates canonical tensor-unbind read-only narrow/squeeze views",
        shape_rule: "one rank-minus-one output per selected-axis element",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "TensorDescriptor owns each resulting strided view",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "no forward arithmetic",
        tolerance: "bit exact",
        determinism: "ascending selected-axis order",
        cancellation_points: "before validation and every 64 outputs",
        vjp_rule: "stack output gradients along the removed axis",
        jvp_rule: "unbind tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_unbind.json",
        evidence_fixture_sha256: "a1dd7cd7fdbfa339ed2fc570a14fdfa8677b12e98e022539a5f991115ef2787e",
    },
]
