&[
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-AED8D6D11C0F",
        baseline_overload_id: "COMFY-TENSOR-OP-AED8D6D11C0F:blocked",
        baseline_fixture_sha256: "a97b6e3549ca5e930865c8c222cc64f5b8cb30952bb17dc48bf0ae113bd669a8",
        overload_id: "zed.native.shape.tensor-repeat.tile-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"repeats","type":"&[i64]","kind":"variadic_positional","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_repeat_with_context_exact_native(backend: &CpuBackend, input: &Tensor, repeats: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation and publication only after the canonical tile traversal completes",
        alias_rule: "fresh contiguous output",
        shape_rule: "repeat rank must cover input rank and each output extent is the checked product of its aligned input extent and repeat count",
        dtype_rule: "all CPU dtypes copy byte exactly",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "Task 80 canonical tile owner reads logical strides and publishes contiguous output",
        device_rule: "CPU certified; other devices return typed unavailable",
        numeric_rule: "byte-exact repeat mapping and deterministic f32 gradient sums",
        tolerance: "bit exact forward and 1e-6 gradients",
        determinism: "Task 80 fixed row-major traversal",
        cancellation_points: "before validation and at Task 80 bounded traversal checkpoints",
        vjp_rule: "Task 80 sums repeated output gradients into aligned input elements",
        jvp_rule: "Task 80 repeats the tangent with identical counts",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/tensor_repeat.json",
        evidence_fixture_sha256: "c2a33148205f49e4ad9608d7bd9d4ea34b7402c99d2d67fe520cb9eca1930852",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-CBDBBB4DF32F",
        baseline_overload_id: "COMFY-TENSOR-OP-CBDBBB4DF32F:blocked",
        baseline_fixture_sha256: "c5ac7ba3e9cef44d8af95da67d21d4260b4ed52a378706532ed9e15e4d25388f",
        overload_id: "zed.native.shape.tensor-reshape.task86-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"shape","type":"&[i64]","kind":"variadic_positional","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_reshape_with_context_exact_native(backend: &CpuBackend, input: &Tensor, shape: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "compatible strides return a read-only alias; incompatible strides use one canonical copy",
        shape_rule: "one inferred dimension and exact checked element-count preservation",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor owns compatible reshape validation and CpuBackend owns copy fallback",
        device_rule: "views preserve device; copy fallback is CPU-certified with typed unavailability elsewhere",
        numeric_rule: "no arithmetic and byte-exact copy fallback",
        tolerance: "bit exact",
        determinism: "single descriptor decision followed by fixed copy traversal when required",
        cancellation_points: "before validation and at canonical copy checkpoints",
        vjp_rule: "reshape the output gradient to the input shape",
        jvp_rule: "apply the identical reshape decision to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/tensor_reshape.json",
        evidence_fixture_sha256: "0e113c1361a9dfc2d32e39a718ce78757c8095288eadc2fd61c97c2be0b9d83c",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-CA47A2C1F7CF",
        baseline_overload_id: "COMFY-TENSOR-OP-CA47A2C1F7CF:blocked",
        baseline_fixture_sha256: "61b6bc1c0f86e47262c55bb6522e2b0953bb254a12c4ddc13289c108f7afcbd4",
        overload_id: "zed.native.shape.tensor-unbind.narrow-view-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn tensor_unbind_exact_native(input: &Tensor, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation and no partial output vector on failure",
        alias_rule: "Task 60 narrow views with the selected singleton axis removed share storage read-only",
        shape_rule: "one output per selected-axis element; an empty axis yields no outputs",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "TensorDescriptor validates squeezed strided views",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "no forward arithmetic",
        tolerance: "bit exact",
        determinism: "ascending selected-axis order",
        cancellation_points: "before validation and every 64 outputs",
        vjp_rule: "stack output gradients on the removed axis",
        jvp_rule: "unbind the tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/tensor_unbind.json",
        evidence_fixture_sha256: "2ef1d16844a032acfba410e7520f578b70d697f1ff91e4c62dcf1a7b749b6c33",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-868899CC3FD0",
        baseline_overload_id: "COMFY-TENSOR-OP-868899CC3FD0:blocked",
        baseline_fixture_sha256: "91576ae8d8933df7cf18522d2a086e5715540be24f94a6c8091bcadaeb0433a9",
        overload_id: "zed.native.shape.tensor-view-as.task86-view-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"other","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_view_as_exact_native(input: &Tensor, other: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "read-only alias of input storage only",
        shape_rule: "target shape equals other.shape and must be compatible with input strides and element count",
        dtype_rule: "input dtype is preserved and other dtype is irrelevant",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor is the sole compatible-view validator",
        device_rule: "input device is preserved and streams must agree",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "one descriptor transformation",
        cancellation_points: "before validation and before returning the alias",
        vjp_rule: "inverse view to the input shape",
        jvp_rule: "apply the same view to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/tensor_view_as.json",
        evidence_fixture_sha256: "031cba3eb98e8da4fd82176910c01e9bb5dcae794d59976f5763fbd1a1a2d941",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-A125CEF23550",
        baseline_overload_id: "COMFY-TENSOR-OP-A125CEF23550:blocked",
        baseline_fixture_sha256: "4c4c9c11153ee98ba76616a8c92c8bd27a5ad7044ce7bcd94259b7a744547aca",
        overload_id: "zed.native.shape.torch-cat.concatenate-adapter.v1",
        ordered_parameters_json: r#"[{"name":"inputs","type":"&[Tensor]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_cat_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no input mutation and one publication after the canonical concatenate traversal",
        alias_rule: "fresh contiguous output",
        shape_rule: "non-axis dimensions match and selected extents sum with overflow checks",
        dtype_rule: "all inputs require one exact dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "Task 64 canonical concatenate owner reads logical strides and publishes contiguous output",
        device_rule: "CPU inputs on one stream; other devices typed unavailable",
        numeric_rule: "byte-exact concatenation",
        tolerance: "bit exact",
        determinism: "input order then row-major element order",
        cancellation_points: "before facade validation and at canonical concatenate checkpoints",
        vjp_rule: "Task 64 slices the output gradient by input extents",
        jvp_rule: "Task 64 concatenates input tangents identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_cat.json",
        evidence_fixture_sha256: "18c6a4677e3332fdc3509c30d4f3bde4164881568533eeeaba241f218af994db",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-B4740B5E4B4D",
        baseline_overload_id: "COMFY-TENSOR-OP-B4740B5E4B4D:blocked",
        baseline_fixture_sha256: "24e979f68952749cf4ceb31615f8b6d53db63523c670bde1930f2f898c4b0015",
        overload_id: "zed.native.shape.torch-flatten.task86-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"start_dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0},{"name":"end_dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":-1}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_flatten_with_context_exact_native(backend: &CpuBackend, input: &Tensor, start_dimension: i64, end_dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "Task 86 returns a compatible read-only view or one canonical copy fallback",
        shape_rule: "merge the inclusive normalized axis range with checked products",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "Task 86 and TensorDescriptor own view-versus-copy behavior",
        device_rule: "views preserve device; copy fallback is CPU certified",
        numeric_rule: "no arithmetic and byte-exact copy fallback",
        tolerance: "bit exact",
        determinism: "Task 86 canonical path",
        cancellation_points: "Task 86 validation and copy checkpoints",
        vjp_rule: "reshape gradient to the input shape",
        jvp_rule: "flatten tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_flatten.json",
        evidence_fixture_sha256: "352292893c556b5df417967000327a9d452a4d48b97a2e66207dbffc64b780ef",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-A4C280408637",
        baseline_overload_id: "COMFY-TENSOR-OP-A4C280408637:blocked",
        baseline_fixture_sha256: "9e2551f1ec541f915a30e8d8467799c274005f845879e9abf7be298754ef655e",
        overload_id: "zed.native.shape.torch-movedim.task86-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"source","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"destination","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_movedim_exact_native(input: &Tensor, source: &[i64], destination: &[i64], cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "read-only view shares input storage",
        shape_rule: "unique normalized source axes move to unique normalized destinations",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "Task 86 plans the permutation and TensorDescriptor owns its strided view",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "stable unmoved-axis order",
        cancellation_points: "before validation and before returning the view",
        vjp_rule: "swap source and destination",
        jvp_rule: "apply identical movement to tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_movedim.json",
        evidence_fixture_sha256: "ac743fb42475867075042b54c9d248349aa07e3df2741401ec896d6d61698e11",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-890C284C875F",
        baseline_overload_id: "COMFY-TENSOR-OP-890C284C875F:blocked",
        baseline_fixture_sha256: "6b7598e2485e076ec471a692f91f26356b2b0af3e3f03d05d753e35b63eb8642",
        overload_id: "zed.native.shape.torch-permute.descriptor-view.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_permute_exact_native(input: &Tensor, dimensions: &[i64], cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "read-only view shares input storage",
        shape_rule: "dimensions are a unique complete normalized rank permutation",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor is the sole permutation shape/stride/storage validator",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "declared permutation order",
        cancellation_points: "before validation and before returning the view",
        vjp_rule: "apply the inverse permutation",
        jvp_rule: "apply the same permutation to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_permute.json",
        evidence_fixture_sha256: "f16cd46a6665a6da29e16e2109db77f29cd0bb114123e25a0637ccecf22b8d8d",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-B918E3498A97",
        baseline_overload_id: "COMFY-TENSOR-OP-B918E3498A97:blocked",
        baseline_fixture_sha256: "c6fa7681c21ba0dac924fa086b4bb331afb33098a95ded939c16d993ddd88717",
        overload_id: "zed.native.shape.torch-reshape.task86-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"shape","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_reshape_with_context_exact_native(backend: &CpuBackend, input: &Tensor, shape: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation",
        alias_rule: "compatible strides alias read-only; incompatible strides copy once",
        shape_rule: "one inferred dimension and exact checked element count",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "Task 86 and TensorDescriptor own reshape view-or-copy behavior",
        device_rule: "views preserve device; CPU copy fallback only",
        numeric_rule: "no arithmetic and byte-exact copy",
        tolerance: "bit exact",
        determinism: "canonical descriptor decision",
        cancellation_points: "before validation and canonical copy checkpoints",
        vjp_rule: "reshape gradient to input shape",
        jvp_rule: "reshape tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_reshape.json",
        evidence_fixture_sha256: "209f82fd077985725368979cd5982241fd93141a79f185add0753923c7220124",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-D4BF78DE58FC",
        baseline_overload_id: "COMFY-TENSOR-OP-D4BF78DE58FC:blocked",
        baseline_fixture_sha256: "a4b334ec7e4b424b0de4540ab564a21a431cbc4e92692887b0f9283b868e7294",
        overload_id: "zed.native.shape.torch-split.task60-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"specification","type":"TorchSplitSpec<'_>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn torch_split_exact_native(input: &Tensor, specification: TorchSplitSpec<'_>, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation and no partial vector on failure",
        alias_rule: "Task 60 read-only narrow views share input storage",
        shape_rule: "positive split size yields consecutive chunks with a smaller tail; explicit nonnegative sizes must sum exactly",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "Task 60 owns split boundaries, view construction, and gradient scatter",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "no forward arithmetic and deterministic gradient scatter",
        tolerance: "bit exact",
        determinism: "source-order boundaries",
        cancellation_points: "before facade validation and at Task 60 checkpoints",
        vjp_rule: "Task 60 scatters output gradients to their source ranges",
        jvp_rule: "Task 60 splits the tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_split.json",
        evidence_fixture_sha256: "da2261d2889e735caac4d8d15479091c6d256f3710fb81541f54235562702a9a",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-C99C862C91E1",
        baseline_overload_id: "COMFY-TENSOR-OP-C99C862C91E1:blocked",
        baseline_fixture_sha256: "817c7e904e621aeedfd4fde27d5afec41fa5da80b7b5f2e88da252e37ded650e",
        overload_id: "zed.native.shape.torch-stack.unsqueeze-concatenate-adapter.v1",
        ordered_parameters_json: r#"[{"name":"inputs","type":"&[Tensor]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_stack_with_context_exact_native(backend: &CpuBackend, inputs: &[Tensor], dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation and one publication after complete composition",
        alias_rule: "Task 86 temporary read-only unsqueeze views feed a fresh canonical concatenate output",
        shape_rule: "equal input shapes gain one insertion axis whose extent is input count",
        dtype_rule: "all inputs require one exact dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "Task 86 owns unsqueeze views and Task 64 owns concatenate traversal",
        device_rule: "CPU inputs on one stream",
        numeric_rule: "byte-exact composition",
        tolerance: "bit exact",
        determinism: "input order and canonical concatenate traversal",
        cancellation_points: "before composition, per input view, and canonical concatenate checkpoints",
        vjp_rule: "unbind the output gradient along the inserted axis",
        jvp_rule: "stack tangents identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_stack.json",
        evidence_fixture_sha256: "6810e1290933b571162d6b1dd5f9bb579cc3f69c13e8b30bf735b3c5f4cc822e",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_02",
        operation_id: "COMFY-TENSOR-OP-75596B7E1112",
        baseline_overload_id: "COMFY-TENSOR-OP-75596B7E1112:blocked",
        baseline_fixture_sha256: "b4884f3c51b494c70df45fe1e6de7fe6f23acfab50d2b3045e5ecfd9ef0cb77e",
        overload_id: "zed.native.shape.torch-unbind.tensor-adapter.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimension","type":"i64","kind":"positional_or_keyword","keyword_only":false,"default":0}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn torch_unbind_exact_native(input: &Tensor, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartTwoError>",
        mutation_rule: "no mutation and no partial vector on failure",
        alias_rule: "delegates canonical tensor-unbind read-only narrow/squeeze views",
        shape_rule: "one rank-minus-one output per selected-axis element",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "TensorDescriptor owns each resulting strided view",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "no forward arithmetic",
        tolerance: "bit exact",
        determinism: "ascending selected-axis order",
        cancellation_points: "before validation and every 64 outputs",
        vjp_rule: "stack output gradients along the removed axis",
        jvp_rule: "unbind tangent identically",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-75596b7e1112",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_02/torch_unbind.json",
        evidence_fixture_sha256: "f86f3a262eff663771e0766fb11d5a02b480ad574b353ce3fcf32babb9f13edb",
    },
]
