&[
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-71DB8F99EAAC",
        baseline_overload_id: "COMFY-TENSOR-OP-71DB8F99EAAC:blocked",
        baseline_fixture_sha256: "0bf97ac13e9f9b01854dd58d67ef6b7f9e1063b6499cfcaed112123029ea364a",
        overload_id: "zed.native.shape.einops-repeat.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"pattern","type":"&str"},{"default":{},"keyword_only":true,"kind":"keyword_only","name":"axis_lengths","type":"&BTreeMap<String,u64>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn einops_repeat_with_context_exact_native(backend: &CpuBackend, input: &Tensor, pattern: &str, axis_lengths: &BTreeMap<String, u64>, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation and one fresh output after complete planning",
        alias_rule: "fresh contiguous output without mutable input alias",
        shape_rule: "Task 67 grammar resolves existing and explicit new axes with ellipsis and checked products",
        dtype_rule: "all CPU tensor dtypes are copied byte exactly",
        accumulation_dtype: "f32 for VJP and not applicable to forward",
        layout_rule: "logical input strides are read and output is contiguous",
        device_rule: "CPU certified and other devices return typed unavailable",
        numeric_rule: "byte-exact repeated source mapping and deterministic f32 gradient sums",
        tolerance: "bit exact forward and 1e-6 f32 gradients",
        determinism: "fixed row-major output traversal",
        cancellation_points: "before parsing and at bounded planning and copy intervals",
        vjp_rule: "sum every repeated output gradient into its source element",
        jvp_rule: "apply the identical repeat plan to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/einops_repeat.json",
        evidence_fixture_sha256: "567544b1017baf74f5335a03af15a1ee788e0dabc4f4074c136f0937af606f8e",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-5A4B8BBBFD81",
        baseline_overload_id: "COMFY-TENSOR-OP-5A4B8BBBFD81:blocked",
        baseline_fixture_sha256: "a52709565a811b236dde45435ffdeec11a8b69ee7d89fd9b5786bf730528241a",
        overload_id: "zed.native.shape.tensor-chunk.split-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"chunks","type":"u64"},{"default":0,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn tensor_chunk_exact_native(input: &Tensor, chunks: u64, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no mutation and no partial output vector on failure",
        alias_rule: "Task 60 read-only narrow views share input storage",
        shape_rule: "ceil chunk size may produce fewer outputs and empty axes produce the requested count",
        dtype_rule: "dtype is preserved by views",
        accumulation_dtype: "f32 for VJP and not applicable to forward",
        layout_rule: "Task 60 preserves source strides and offsets",
        device_rule: "Task 60 CPU contract with typed unavailable elsewhere",
        numeric_rule: "no arithmetic in forward and deterministic VJP scatter",
        tolerance: "bit exact",
        determinism: "source-order split boundaries",
        cancellation_points: "before boundary resolution and at Task 60 checkpoints",
        vjp_rule: "Task 60 scatters output gradients into the input shape",
        jvp_rule: "Task 60 applies identical split views to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_chunk.json",
        evidence_fixture_sha256: "d4ba3ab03cf6f3e5c80aef26f424777fdc7ec53d5e571d69c552276fc75da3c5",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-3D13DA91C9F3",
        baseline_overload_id: "COMFY-TENSOR-OP-3D13DA91C9F3:blocked",
        baseline_fixture_sha256: "eaeef0471503d881d24f05a7babb1b9b18709d3840c88cf42a63b23a6c8147c3",
        overload_id: "zed.native.shape.tensor-expand.broadcast-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"variadic_positional","name":"sizes","type":"&[i64]"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_expand_exact_native(input: &Tensor, sizes: &[i64], cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation",
        alias_rule: "Task 63 read-only zero-stride view shares input storage",
        shape_rule: "right-aligned broadcast with -1 retaining existing dimensions and checked leading axes",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "f32 for VJP and not applicable to forward",
        layout_rule: "Task 63 owns zero-stride descriptor construction",
        device_rule: "view preserves the canonical device and stream",
        numeric_rule: "no forward arithmetic and deterministic broadcast-gradient sums",
        tolerance: "bit exact forward and 1e-6 f32 gradients",
        determinism: "fixed Task 63 traversal",
        cancellation_points: "before validation and before returning the view",
        vjp_rule: "Task 63 sums broadcast axes into the source shape",
        jvp_rule: "Task 63 broadcasts the tangent with the same shape",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_expand.json",
        evidence_fixture_sha256: "0f39d4f58f4e5420fe921da5cd57f34b51cdbeea9d387c299bf7e910c1a7863f",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-25362A66A957",
        baseline_overload_id: "COMFY-TENSOR-OP-25362A66A957:blocked",
        baseline_fixture_sha256: "3e1249a5210ff14e0599207ff96a359e90899bd2f6dcd696b8c1dfe06796ed79",
        overload_id: "zed.native.shape.tensor-expand-as.broadcast-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"other","type":"&Tensor"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_expand_as_exact_native(input: &Tensor, other: &Tensor, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input or peer mutation",
        alias_rule: "Task 63 read-only zero-stride view shares input storage only",
        shape_rule: "target shape is exactly the peer shape and must be broadcast compatible",
        dtype_rule: "input dtype is preserved and peer dtype is irrelevant",
        accumulation_dtype: "f32 for VJP and not applicable to forward",
        layout_rule: "Task 63 owns zero-stride descriptor construction",
        device_rule: "input and peer device and stream must agree",
        numeric_rule: "no forward arithmetic and deterministic broadcast-gradient sums",
        tolerance: "bit exact forward and 1e-6 f32 gradients",
        determinism: "fixed Task 63 traversal",
        cancellation_points: "before peer validation and before returning the view",
        vjp_rule: "Task 63 sums broadcast axes into the source shape",
        jvp_rule: "Task 63 broadcasts the tangent to the peer shape",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_expand_as.json",
        evidence_fixture_sha256: "29a86c4d45df833e165fc1332d5bc04df14a5dc0df56662782518c9005614c6a",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-67D2FDD707E0",
        baseline_overload_id: "COMFY-TENSOR-OP-67D2FDD707E0:blocked",
        baseline_fixture_sha256: "76eb7ccf57520992f255d6c8257f1123f315cfcb1fc9c92053c36f005f0948bb",
        overload_id: "zed.native.shape.tensor-flatten.descriptor-view-or-copy.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":0,"keyword_only":false,"kind":"positional_or_keyword","name":"start_dimension","type":"i64"},{"default":-1,"keyword_only":false,"kind":"positional_or_keyword","name":"end_dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_flatten_with_context_exact_native(backend: &CpuBackend, input: &Tensor, start_dimension: i64, end_dimension: i64, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no mutation and copy publication occurs only after completion",
        alias_rule: "compatible strides return a read-only view and incompatible strides return a fresh copy",
        shape_rule: "inclusive normalized dimension interval collapses to its checked product",
        dtype_rule: "dtype is preserved byte exactly",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor alone decides view compatibility and CpuBackend alone copies fallback storage",
        device_rule: "views preserve device while copy fallback is CPU certified",
        numeric_rule: "logical element order is byte exact",
        tolerance: "bit exact",
        determinism: "fixed logical row-major fallback traversal",
        cancellation_points: "before shape resolution and throughout CpuBackend copy",
        vjp_rule: "reshape the output gradient to the input shape",
        jvp_rule: "apply the same flatten view-or-copy rule to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_flatten.json",
        evidence_fixture_sha256: "6118e65459c71abac9ad762c6a1c5f12a8018ad35af1555e4fcfae7a51bd9f39",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-73D179A8CEB9",
        baseline_overload_id: "COMFY-TENSOR-OP-73D179A8CEB9:blocked",
        baseline_fixture_sha256: "2d5b0d33f2363dae4cae8bcc71b3cf53894561e4ce37f775b7a277079f6cfccc",
        overload_id: "zed.native.shape.tensor-movedim.descriptor-view.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"source","type":"&[i64]"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"destination","type":"&[i64]"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_movedim_exact_native(input: &Tensor, source: &[i64], destination: &[i64], cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation",
        alias_rule: "read-only descriptor view shares input storage",
        shape_rule: "unique normalized source axes are inserted at unique normalized destination axes",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "shape and strides are permuted without materialization",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "stable destination-order insertion",
        cancellation_points: "before axis validation and before returning the view",
        vjp_rule: "move destination axes back to source positions",
        jvp_rule: "apply the identical movement to the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_movedim.json",
        evidence_fixture_sha256: "dcef471212dca303e3da6b1f894326fc828b97dc6b51d21f753aecd54399acc6",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-3E6301EB6AA6",
        baseline_overload_id: "COMFY-TENSOR-OP-3E6301EB6AA6:blocked",
        baseline_fixture_sha256: "dd8c75b921108bf6684bc66e19b2188c62e75ce26c646557e695b3b371e1b7cb",
        overload_id: "zed.native.shape.tensor-repeat-interleave.cpu.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"repeats","type":"RepeatInterleaveSpec<'_>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"Option<i64>"},{"default":null,"keyword_only":true,"kind":"keyword_only","name":"output_size","type":"Option<u64>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_repeat_interleave_with_context_exact_native(backend: &CpuBackend, input: &Tensor, repeats: RepeatInterleaveSpec<'_>, dimension: Option<i64>, output_size: Option<u64>, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no mutation and fresh output after complete traversal",
        alias_rule: "fresh contiguous output",
        shape_rule: "scalar, slice, or scalar/one-dimensional integer-tensor counts expand the selected axis and omitted dimension flattens first",
        dtype_rule: "all CPU input dtypes copy byte exactly; tensor repeat counts require an I32 or I64 dtype",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "logical input strides are read and output is contiguous",
        device_rule: "CPU certified and other devices return typed unavailable",
        numeric_rule: "byte-exact forward and fixed source-order gradient sums",
        tolerance: "bit exact forward and 1e-6 f32 gradients",
        determinism: "fixed row-major traversal",
        cancellation_points: "before validation and at bounded traversal intervals",
        vjp_rule: "sum repeated output gradients into each source element",
        jvp_rule: "repeat the tangent with the identical counts",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_repeat_interleave.json",
        evidence_fixture_sha256: "b9b464137e583aaf0e48682176ced785560077bcf68ec871430f657274c28d79",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-17E7C823A86F",
        baseline_overload_id: "COMFY-TENSOR-OP-17E7C823A86F:blocked",
        baseline_fixture_sha256: "51a294d3597d7acd1484efb184fe3412643f0aa46068f94732f599e1a220061d",
        overload_id: "zed.native.shape.tensor-unsqueeze.descriptor-view.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_unsqueeze_exact_native(input: &Tensor, dimension: i64, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation",
        alias_rule: "read-only descriptor view shares input storage",
        shape_rule: "one normalized insertion axis is added at extent one",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical descriptor owns checked inserted stride and storage bounds",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "single checked descriptor transformation",
        cancellation_points: "before axis validation and before returning the view",
        vjp_rule: "remove the inserted extent-one axis by a checked view",
        jvp_rule: "insert the same axis into the tangent",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_unsqueeze.json",
        evidence_fixture_sha256: "08d02403e18d95597e919e2a95ce12c34412774c00cefed4b26b3b66950d02aa",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-5380FDF9E668",
        baseline_overload_id: "COMFY-TENSOR-OP-5380FDF9E668:blocked",
        baseline_fixture_sha256: "ccfb69776a3aa2e2003a024946dcfb93e5b21b749d5caaf995ffa6b22f09f42a",
        overload_id: "zed.native.shape.tensor-view.shape-and-dtype.canonical-descriptor.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"specification","type":"TensorViewSpec<'_>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_view_exact_native(input: &Tensor, specification: TensorViewSpec<'_>, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation",
        alias_rule: "read-only compatible-stride shape views and checked dtype reinterpretations share input storage",
        shape_rule: "shape form permits one inferred dimension; dtype form rescales the last dimension, strides, and storage offset under PyTorch alignment rules",
        dtype_rule: "shape form preserves dtype; dtype form reinterprets exact bytes without numeric conversion",
        accumulation_dtype: "not applicable",
        layout_rule: "TensorDescriptor is the sole compatible-stride, dtype-reinterpretation, alignment, and storage-bounds validator",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic; dtype form is byte exact",
        tolerance: "bit exact",
        determinism: "single canonical descriptor transformation",
        cancellation_points: "before specification validation and before returning the view",
        vjp_rule: "shape view has a checked inverse view; dtype reinterpretation is forward-only and non-differentiable",
        jvp_rule: "shape view applies the identical view to the tangent; dtype reinterpretation is forward-only and non-differentiable",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/tensor_view.json",
        evidence_fixture_sha256: "5c238f1689e8aeab586c95aad522159e1f296e824632a6da06ad74e6bd1d4f90",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-47B154B1D223",
        baseline_overload_id: "COMFY-TENSOR-OP-47B154B1D223:blocked",
        baseline_fixture_sha256: "1fdbf1a2d5be99b5fe331ad57f69b6949e167eeb394962fd3cd39354116700ae",
        overload_id: "zed.native.shape.torch-chunk.tensor-chunk-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"chunks","type":"u64"},{"default":0,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Vec<Tensor>"]"#,
        rust_signature: "fn torch_chunk_exact_native(input: &Tensor, chunks: u64, dimension: i64, cancellation: &CancellationToken) -> Result<Vec<Tensor>, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no mutation and no partial output vector on failure",
        alias_rule: "delegates Tensor.chunk read-only Task 60 split views",
        shape_rule: "identical to Tensor.chunk ceil-size boundaries",
        dtype_rule: "dtype is preserved by views",
        accumulation_dtype: "f32 for VJP and not applicable to forward",
        layout_rule: "Task 60 preserves source strides and offsets",
        device_rule: "Task 60 CPU contract with typed unavailable elsewhere",
        numeric_rule: "no arithmetic in forward and deterministic VJP scatter",
        tolerance: "bit exact",
        determinism: "source-order split boundaries",
        cancellation_points: "before facade delegation and at Task 60 checkpoints",
        vjp_rule: "delegates the canonical chunk gradient path",
        jvp_rule: "delegates the canonical chunk tangent path",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/torch_chunk.json",
        evidence_fixture_sha256: "9ac46855af3970a6bc45d9d4fbf4de14f44d1e363b4f6184513b5c7a52a4cf1c",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-0C2E0712DA68",
        baseline_overload_id: "COMFY-TENSOR-OP-0C2E0712DA68:blocked",
        baseline_fixture_sha256: "fb3abb8d4c81cfe85bda0ef71dd880f82c649441f3e801503cab78429907dd5e",
        overload_id: "zed.native.shape.torch-repeat-interleave.tensor-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"repeats","type":"RepeatInterleaveSpec<'_>"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"Option<i64>"},{"default":null,"keyword_only":true,"kind":"keyword_only","name":"output_size","type":"Option<u64>"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_repeat_interleave_with_context_exact_native(backend: &CpuBackend, input: &Tensor, repeats: RepeatInterleaveSpec<'_>, dimension: Option<i64>, output_size: Option<u64>, context: &ExecutionContext<'_>) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no mutation and delegates one fresh canonical output",
        alias_rule: "delegates Tensor.repeat_interleave fresh contiguous output",
        shape_rule: "identical scalar, slice, scalar/one-dimensional integer-tensor, optional-axis, and output-size rules",
        dtype_rule: "all CPU input dtypes copy byte exactly; tensor repeat counts require an I32 or I64 dtype",
        accumulation_dtype: "f32 for VJP",
        layout_rule: "logical input strides are read and output is contiguous",
        device_rule: "CPU certified and other devices return typed unavailable",
        numeric_rule: "byte-exact forward and fixed source-order gradient sums",
        tolerance: "bit exact forward and 1e-6 f32 gradients",
        determinism: "fixed row-major traversal",
        cancellation_points: "before facade delegation and at bounded traversal intervals",
        vjp_rule: "delegates the canonical repeated-axis gradient sum",
        jvp_rule: "delegates the canonical repeated tangent path",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/torch_repeat_interleave.json",
        evidence_fixture_sha256: "84b976ca3d1d375d84eb73e2ff8845b2fc0d2d80d53b651cf1d450632055ffa6",
    },
    ResolvedOperationContract {
        resolution_module: "shape_layout_transform_01",
        operation_id: "COMFY-TENSOR-OP-3E9A0E130935",
        baseline_overload_id: "COMFY-TENSOR-OP-3E9A0E130935:blocked",
        baseline_fixture_sha256: "55373c178bef0233c881f59b6f3ff33bcfef88ac09585cb78fecf5b2ae37fde3",
        overload_id: "zed.native.shape.torch-unsqueeze.tensor-adapter.v1",
        ordered_parameters_json: r#"[{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"input","type":"&Tensor"},{"default":null,"keyword_only":false,"kind":"positional_or_keyword","name":"dimension","type":"i64"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn torch_unsqueeze_exact_native(input: &Tensor, dimension: i64, cancellation: &CancellationToken) -> Result<Tensor, ShapeLayoutTransformPartOneError>",
        mutation_rule: "no input mutation",
        alias_rule: "delegates Tensor.unsqueeze read-only descriptor view",
        shape_rule: "one normalized insertion axis is added at extent one",
        dtype_rule: "dtype is preserved",
        accumulation_dtype: "not applicable",
        layout_rule: "canonical descriptor owns checked inserted stride and storage bounds",
        device_rule: "device and stream are preserved",
        numeric_rule: "no arithmetic",
        tolerance: "bit exact",
        determinism: "single checked descriptor transformation",
        cancellation_points: "before facade delegation and before returning the view",
        vjp_rule: "delegates the canonical checked inverse view",
        jvp_rule: "delegates the canonical tangent unsqueeze",
        owner_task_id: "comfy-parity-tensor-ops-shape-layout-transform-comfy-tensor-op-0c2e0712da68",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/shape_layout_transform_01/torch_unsqueeze.json",
        evidence_fixture_sha256: "a7e99dd9faf53d3a763f7a8e774e5bb12e079191c3e5dc45e90dc7dcd99f852c",
    },
]
