&[
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-5F86004D9BDA",
        baseline_overload_id: "COMFY-TENSOR-OP-5F86004D9BDA:blocked",
        baseline_fixture_sha256: "16796b98bf13b35e48c5414a8940c1d33aa7180a109eb6b670fca60f52d525e9",
        overload_id: "sim.native.spatial.avg-pool1d.average-pool-geometry.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&AveragePoolConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn average_pool_1d_with_context_exact_native(input: &[f32], input_shape: &[usize], configuration: &AveragePoolConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "NCL or CL with checked kernel, default stride, padding, ceil mode, and PyTorch-compatible terminal-window removal",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "row-major logical traversal owned by AveragePoolGeometry",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "fixed-order mean with explicit count_include_pad and divisor_override",
        tolerance: "1e-6",
        determinism: "fixed plane, output, then kernel order",
        cancellation_points: "before validation, every output tile, and before publication",
        vjp_rule: "scatter each output cotangent through the identical canonical divisor map",
        jvp_rule: "pool the input tangent with the identical geometry",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/avg_pool1d.json",
        evidence_fixture_sha256: "e300fd6c3d44dc6c26a2b9ebce7d879ff05b58c8f86461735c94ecaafb2e0c43",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-60B322636602",
        baseline_overload_id: "COMFY-TENSOR-OP-60B322636602:blocked",
        baseline_fixture_sha256: "004e3d303d6b54594a46177173320510b78cbde986410ef3d751d0cd3c549941",
        overload_id: "sim.native.spatial.avg-pool2d.average-pool-geometry.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&AveragePoolConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn average_pool_2d_with_context_exact_native(input: &[f32], input_shape: &[usize], configuration: &AveragePoolConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "NCHW or CHW with checked two-axis pooling geometry and explicit ceil semantics",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 77 AveragePoolGeometry is the sole window owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "fixed-order mean with explicit padding divisor semantics",
        tolerance: "1e-6",
        determinism: "fixed plane, output, then kernel order",
        cancellation_points: "before validation, every output tile, and before publication",
        vjp_rule: "canonical window scatter with identical divisor",
        jvp_rule: "canonical pooling of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/avg_pool2d.json",
        evidence_fixture_sha256: "4c01d01f3c272c767fbaee9a09821094717c3585883c5016213151f2a5fe2141",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-6BFAEF690071",
        baseline_overload_id: "COMFY-TENSOR-OP-6BFAEF690071:blocked",
        baseline_fixture_sha256: "6a4c56780d77afa789ce4e1c46056f65708fa5aafc0d62c0c699bb81226c74ba",
        overload_id: "sim.native.spatial.avg-pool3d.average-pool-geometry.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&AveragePoolConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn average_pool_3d_with_context_exact_native(input: &[f32], input_shape: &[usize], configuration: &AveragePoolConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "NCDHW or CDHW with checked three-axis pooling geometry",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 77 AveragePoolGeometry is the sole window owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "fixed-order mean and exact configured divisor",
        tolerance: "1e-6",
        determinism: "fixed plane, output, then kernel order",
        cancellation_points: "before validation, every output tile, and before publication",
        vjp_rule: "canonical window scatter with identical divisor",
        jvp_rule: "canonical pooling of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/avg_pool3d.json",
        evidence_fixture_sha256: "2de2a5cebda2118130d79a7d091c86b97569a597458c5239ca9710ecfb46f9e5",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-DC56DB93077F",
        baseline_overload_id: "COMFY-TENSOR-OP-DC56DB93077F:blocked",
        baseline_fixture_sha256: "e143905a602a5096081040b44e0e6357a8724729cf780e33048cc7a860934967",
        overload_id: "sim.native.spatial.conv1d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_1d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped 1D convolution geometry validates NCL, OIK, stride, padding, dilation, and groups",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry is the sole connection owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical output then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical input, weight, and optional bias VJP",
        jvp_rule: "Task 42 bilinear convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv1d.json",
        evidence_fixture_sha256: "a633a8091b768b8d651f89e018f51d6df7e56e90f0c0504ed77ec7bd39c953c6",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-A31AEBE72455",
        baseline_overload_id: "COMFY-TENSOR-OP-A31AEBE72455:blocked",
        baseline_fixture_sha256: "70b39425c6a2c6e3d4c69184321b332d7eb822755d0e0f87c2ff5f7eb2bee8c5",
        overload_id: "sim.native.spatial.conv2d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_2d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped 2D convolution geometry validates NCHW and OIHW",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry is the sole connection owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical output then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical input, weight, and optional bias VJP",
        jvp_rule: "Task 42 bilinear convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv2d.json",
        evidence_fixture_sha256: "d80f5de156590852947ac39e8c354dcbedc75c10ba6e388a3fc9619867f7c581",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-FE03423D60DA",
        baseline_overload_id: "COMFY-TENSOR-OP-FE03423D60DA:blocked",
        baseline_fixture_sha256: "03650cba73f2cccc6d7603b1d46bba99e67009b2b2d4f14ef9cbf88d26186c4f",
        overload_id: "sim.native.spatial.conv3d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_3d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped 3D convolution geometry validates NCDHW and OIDHW",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry is the sole connection owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical output then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical input, weight, and optional bias VJP",
        jvp_rule: "Task 42 bilinear convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv3d.json",
        evidence_fixture_sha256: "8c331012885263f0663991ea77a9a74af313da1acf81d681a0b10f6ab0bf0e81",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-341577A45D6B",
        baseline_overload_id: "COMFY-TENSOR-OP-341577A45D6B:blocked",
        baseline_fixture_sha256: "b106cd20357cd9793c991b49327dd6c073a9e71db63637404b9ba113c3871873",
        overload_id: "sim.native.spatial.conv-transpose1d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_transpose_1d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped transposed 1D geometry validates stride, padding, dilation, and output_padding",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry owns transposed connectivity",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical input then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical transposed-convolution VJP",
        jvp_rule: "Task 42 canonical transposed-convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv_transpose1d.json",
        evidence_fixture_sha256: "bfa415d86e6517288cdb1e8c6e9a9bd6c14c3036e99624d2734b3cbbd32cc82a",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-5A5F8349A130",
        baseline_overload_id: "COMFY-TENSOR-OP-5A5F8349A130:blocked",
        baseline_fixture_sha256: "49a40f508c5cffe028cf7891e9a1826a2e52bf1770fe27c39c003dc10e425315",
        overload_id: "sim.native.spatial.conv-transpose2d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_transpose_2d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped transposed 2D geometry validates NCHW and IOHW",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry owns transposed connectivity",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical input then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical transposed-convolution VJP",
        jvp_rule: "Task 42 canonical transposed-convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv_transpose2d.json",
        evidence_fixture_sha256: "d338aabfead4178cc0c5fb9cd017e2cd56766cd4b73c63bee0320ea713871c9f",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-5A6A586CC551",
        baseline_overload_id: "COMFY-TENSOR-OP-5A6A586CC551:blocked",
        baseline_fixture_sha256: "dc1f44936fed4a5a4622d16eec25e978f5c541b46f3e499730b2be3e2becd5d8",
        overload_id: "sim.native.spatial.conv-transpose3d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_transpose_3d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped transposed 3D geometry validates NCDHW and IODHW",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry owns transposed connectivity",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical input then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical transposed-convolution VJP",
        jvp_rule: "Task 42 canonical transposed-convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv_transpose3d.json",
        evidence_fixture_sha256: "1256dec312ace287adec1ce100f8f1c096be98b0ec257bb23a43c9524f92e8a3",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-A90AB43A3320",
        baseline_overload_id: "COMFY-TENSOR-OP-A90AB43A3320:blocked",
        baseline_fixture_sha256: "3883b3c9d0d01acee3edf22a42d7a6fbe1fac12ea2ac320c6a844f358791b504",
        overload_id: "sim.native.spatial.grid-sample.checked-sampling-owner.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"grid","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"grid_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"GridSampleConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn grid_sample_with_context_exact_native(input: &[f32], input_shape: &[usize], grid: &[f32], grid_shape: &[usize], configuration: GridSampleConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous NCHW values",
        shape_rule: "NCHW input and NHW2 normalized grid with nearest, bilinear, or bicubic sampling and zeros, border, or reflection padding",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 67 checked sampling weights own bounds; this adapter owns normalized-grid projection",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "PyTorch coordinate transforms, Keys cubic coefficient -0.75, and fixed channel traversal",
        tolerance: "1e-5 forward and gradients",
        determinism: "batch, output-y, output-x, channel, then sample order",
        cancellation_points: "before validation, every 64 outputs, and before publication",
        vjp_rule: "scatter to input and analytically differentiate normalized grid coordinates",
        jvp_rule: "sample the input tangent plus coordinate Jacobian applied to grid tangent",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/grid_sample.json",
        evidence_fixture_sha256: "1183f698ac8f29b01c5f81b9a14a89826fcca8a5bc571bc3635bbfa9d556609b",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-B0F801006375",
        baseline_overload_id: "COMFY-TENSOR-OP-B0F801006375:blocked",
        baseline_fixture_sha256: "0bd20a243eb23beb5328683c2f94053d6fd78c47640c944459e2e68a97d25203",
        overload_id: "sim.native.spatial.interpolate.canonical-sampling-extension.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&InterpolateConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn interpolate_with_context_exact_native(input: &[f32], input_shape: &[usize], configuration: &InterpolateConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "N,C plus one to three spatial axes; exactly one checked size or scale; mode-specific rank and align_corners validation",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 67 checked linear sampling owns boundaries; adapter extends separable sampling to one and three dimensions",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "nearest, nearest-exact, linear, bilinear, bicubic, trilinear, area, and normalized antialias kernels",
        tolerance: "1e-5",
        determinism: "plane, row-major output, then Cartesian axis-weight order",
        cancellation_points: "before validation, every 64 outputs, and before publication",
        vjp_rule: "transpose the exact separable sampling map",
        jvp_rule: "apply the exact sampling map to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/interpolate.json",
        evidence_fixture_sha256: "22bdbfd653bd624574191ec8cdaf246912900ff31fd38277bae4d262ee5ec733",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-1F9D23F3B331",
        baseline_overload_id: "COMFY-TENSOR-OP-1F9D23F3B331:blocked",
        baseline_fixture_sha256: "3200a8f318bb0a04939f2c6e74ae9799a2ff1e3b604a2f4afbaec1fc937e1b1f",
        overload_id: "sim.native.spatial.max-pool2d.task79-selection-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"kernel_size","type":"[usize;2]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"stride","type":"Option<[usize;2]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"padding","type":"[usize;2]","kind":"positional_or_keyword","keyword_only":false,"default":"[0,0]"},{"name":"dilation","type":"[usize;2]","kind":"positional_or_keyword","keyword_only":false,"default":"[1,1]"},{"name":"ceil_mode","type":"bool","kind":"positional_or_keyword","keyword_only":false,"default":false}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn max_pool_2d_with_context_exact_native(input: &[f32], input_shape: &[usize], kernel_size: [usize; 2], stride: Option<[usize; 2]>, padding: [usize; 2], dilation: [usize; 2], ceil_mode: bool, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "Task 79 canonical NCHW/CHW geometry with default stride, padding, dilation, and ceil mode",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32 gradients",
        layout_rule: "Task 79 is sole maximum-selection and tie-breaking owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "exact maximum with first canonical connection selected on ties",
        tolerance: "bit exact forward and 1e-6 gradients",
        determinism: "canonical window traversal and stable first tie",
        cancellation_points: "before validation, canonical output checkpoints, and before publication",
        vjp_rule: "scatter cotangent to the selected canonical input",
        jvp_rule: "select the input tangent at the primal argmax",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/max_pool2d.json",
        evidence_fixture_sha256: "d258cb0ca1560ea9d20ebcca802ce93ddb1e5aac56876d33bb86ea501379ac0c",
    },
]
