&[
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-5F86004D9BDA",
        baseline_overload_id: "COMFY-TENSOR-OP-5F86004D9BDA:blocked",
        baseline_fixture_sha256: "6a7c743a76e7c97f0a06aabe66caf90768e3d26b58d717d058ea72e41a5933c4",
        overload_id: "zed.native.spatial.avg-pool1d.average-pool-geometry.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&AveragePoolConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn average_pool_1d_with_context_exact_native(input: &[f32], input_shape: &[usize], configuration: &AveragePoolConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "NCL or CL with checked kernel, default stride, padding, ceil mode, and PyTorch-compatible terminal-window removal",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "row-major logical traversal owned by AveragePoolGeometry",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "fixed-order mean with explicit count_include_pad and divisor_override",
        tolerance: "1e-6",
        determinism: "fixed plane, output, then kernel order",
        cancellation_points: "before validation, every output tile, and before publication",
        vjp_rule: "scatter each output cotangent through the identical canonical divisor map",
        jvp_rule: "pool the input tangent with the identical geometry",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/avg_pool1d.json",
        evidence_fixture_sha256: "db1dab3d388c7fcb4116667fb87345ee7abea69f4441d401c15bc9cab5979a42",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-60B322636602",
        baseline_overload_id: "COMFY-TENSOR-OP-60B322636602:blocked",
        baseline_fixture_sha256: "6925a5482cf8f248b58c0d8b7ccec093a1ccdb77de55ab82bbefc41c9fa219d0",
        overload_id: "zed.native.spatial.avg-pool2d.average-pool-geometry.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&AveragePoolConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn average_pool_2d_with_context_exact_native(input: &[f32], input_shape: &[usize], configuration: &AveragePoolConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "NCHW or CHW with checked two-axis pooling geometry and explicit ceil semantics",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 77 AveragePoolGeometry is the sole window owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "fixed-order mean with explicit padding divisor semantics",
        tolerance: "1e-6",
        determinism: "fixed plane, output, then kernel order",
        cancellation_points: "before validation, every output tile, and before publication",
        vjp_rule: "canonical window scatter with identical divisor",
        jvp_rule: "canonical pooling of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/avg_pool2d.json",
        evidence_fixture_sha256: "258fc6595cb5ade613d50f314f0a9f5b211b6e566d00de3fde6cd2948fecfd9b",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-6BFAEF690071",
        baseline_overload_id: "COMFY-TENSOR-OP-6BFAEF690071:blocked",
        baseline_fixture_sha256: "2aa1e3106cd6b71494668246b68ded32134c698460fdd3b21892bae6a532f821",
        overload_id: "zed.native.spatial.avg-pool3d.average-pool-geometry.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&AveragePoolConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn average_pool_3d_with_context_exact_native(input: &[f32], input_shape: &[usize], configuration: &AveragePoolConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "NCDHW or CDHW with checked three-axis pooling geometry",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 77 AveragePoolGeometry is the sole window owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "fixed-order mean and exact configured divisor",
        tolerance: "1e-6",
        determinism: "fixed plane, output, then kernel order",
        cancellation_points: "before validation, every output tile, and before publication",
        vjp_rule: "canonical window scatter with identical divisor",
        jvp_rule: "canonical pooling of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/avg_pool3d.json",
        evidence_fixture_sha256: "eb8093eac9c224cfeeeadf463b238dd38278c94f7f94a0271aec2af781f8663c",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-DC56DB93077F",
        baseline_overload_id: "COMFY-TENSOR-OP-DC56DB93077F:blocked",
        baseline_fixture_sha256: "e99e1982314ff6c1edd71a381ab5a1703a2b78aa9e850600b08a5e87fc283b52",
        overload_id: "zed.native.spatial.conv1d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_1d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped 1D convolution geometry validates NCL, OIK, stride, padding, dilation, and groups",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry is the sole connection owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical output then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical input, weight, and optional bias VJP",
        jvp_rule: "Task 42 bilinear convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv1d.json",
        evidence_fixture_sha256: "676d1eafef164ccb628bba3965de6ac3f10e13b20e4a6c602188a87a1c31ff6a",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-A31AEBE72455",
        baseline_overload_id: "COMFY-TENSOR-OP-A31AEBE72455:blocked",
        baseline_fixture_sha256: "296219687360f5c202ccdb9ade7a9f72be62a09df286a93aa9ebfde62fde6458",
        overload_id: "zed.native.spatial.conv2d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_2d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped 2D convolution geometry validates NCHW and OIHW",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry is the sole connection owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical output then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical input, weight, and optional bias VJP",
        jvp_rule: "Task 42 bilinear convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv2d.json",
        evidence_fixture_sha256: "dba30f7b503b78b9e8a37d7508db0f8080cbff8d6046d347f328007161618627",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-FE03423D60DA",
        baseline_overload_id: "COMFY-TENSOR-OP-FE03423D60DA:blocked",
        baseline_fixture_sha256: "12bb2b011f95da9d75298b4b9c30f9b0b28eae045cec11056388ef3ed992719c",
        overload_id: "zed.native.spatial.conv3d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_3d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped 3D convolution geometry validates NCDHW and OIDHW",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry is the sole connection owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical output then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical input, weight, and optional bias VJP",
        jvp_rule: "Task 42 bilinear convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv3d.json",
        evidence_fixture_sha256: "976e9d22f112a10d59493ae7740d10e09c2d29180966f8b9476cdc42868cc833",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-341577A45D6B",
        baseline_overload_id: "COMFY-TENSOR-OP-341577A45D6B:blocked",
        baseline_fixture_sha256: "43304af2c0846c463fc3b9f5880b3d3088c7c7c207dff0509341e50e21a4fe78",
        overload_id: "zed.native.spatial.conv-transpose1d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_transpose_1d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped transposed 1D geometry validates stride, padding, dilation, and output_padding",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry owns transposed connectivity",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical input then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical transposed-convolution VJP",
        jvp_rule: "Task 42 canonical transposed-convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv_transpose1d.json",
        evidence_fixture_sha256: "502f58d83348298a7b21c8f31c0c4e716f867b1c5ee730673afa3fe16825580c",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-5A5F8349A130",
        baseline_overload_id: "COMFY-TENSOR-OP-5A5F8349A130:blocked",
        baseline_fixture_sha256: "f525d9a31c7d11989a3ae7435f6199f4a30eb52af3a4dec14b8a1f17cb7127a2",
        overload_id: "zed.native.spatial.conv-transpose2d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_transpose_2d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped transposed 2D geometry validates NCHW and IOHW",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry owns transposed connectivity",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical input then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical transposed-convolution VJP",
        jvp_rule: "Task 42 canonical transposed-convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv_transpose2d.json",
        evidence_fixture_sha256: "68d2fd8b9978364ea28642dad45ce3929db1c374735fda146facaa8883010c93",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-5A6A586CC551",
        baseline_overload_id: "COMFY-TENSOR-OP-5A6A586CC551:blocked",
        baseline_fixture_sha256: "d122fc3a332529262b9b29e69138bd992c89a12d1bf36698bdfffcd96cc9f1ab",
        overload_id: "zed.native.spatial.conv-transpose3d.convolution-geometry-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"weight_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"bias","type":"Option<&[f32]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&ConvolutionConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn conv_transpose_3d_with_context_exact_native(input: &[f32], input_shape: &[usize], weight: &[f32], weight_shape: &[usize], bias: Option<&[f32]>, configuration: &ConvolutionConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "canonical grouped transposed 3D geometry validates NCDHW and IODHW",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 42 ConvolutionGeometry owns transposed connectivity",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical fixed-order fused multiply-add accumulation",
        tolerance: "1e-5",
        determinism: "canonical input then connection order",
        cancellation_points: "before dispatch, at canonical kernel boundaries, and before publication",
        vjp_rule: "Task 42 canonical transposed-convolution VJP",
        jvp_rule: "Task 42 canonical transposed-convolution JVP",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/conv_transpose3d.json",
        evidence_fixture_sha256: "9395cf2fe488cfea2d4add471d14e93319951dd6fe4adf89c8937fea022608e2",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-A90AB43A3320",
        baseline_overload_id: "COMFY-TENSOR-OP-A90AB43A3320:blocked",
        baseline_fixture_sha256: "781d85f85a2e01e66db82890f06b5eaac596b06468624d88584800555b4eb3c5",
        overload_id: "zed.native.spatial.grid-sample.checked-sampling-owner.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"grid","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"grid_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"GridSampleConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn grid_sample_with_context_exact_native(input: &[f32], input_shape: &[usize], grid: &[f32], grid_shape: &[usize], configuration: GridSampleConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous NCHW values",
        shape_rule: "NCHW input and NHW2 normalized grid with nearest, bilinear, or bicubic sampling and zeros, border, or reflection padding",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 67 checked sampling weights own bounds; this adapter owns normalized-grid projection",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "PyTorch coordinate transforms, Keys cubic coefficient -0.75, and fixed channel traversal",
        tolerance: "1e-5 forward and gradients",
        determinism: "batch, output-y, output-x, channel, then sample order",
        cancellation_points: "before validation, every 64 outputs, and before publication",
        vjp_rule: "scatter to input and analytically differentiate normalized grid coordinates",
        jvp_rule: "sample the input tangent plus coordinate Jacobian applied to grid tangent",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/grid_sample.json",
        evidence_fixture_sha256: "fe6c530a71e6abecdd52cb546f3f88f278aa90827769c9ccae254727d713700b",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-B0F801006375",
        baseline_overload_id: "COMFY-TENSOR-OP-B0F801006375:blocked",
        baseline_fixture_sha256: "89b34b36154b0eea7550b1f61479b98bda55f772a6e1988bc32b8c9264a1ba58",
        overload_id: "zed.native.spatial.interpolate.canonical-sampling-extension.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"configuration","type":"&InterpolateConfiguration","kind":"positional_or_keyword","keyword_only":false,"default":null}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn interpolate_with_context_exact_native(input: &[f32], input_shape: &[usize], configuration: &InterpolateConfiguration, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "N,C plus one to three spatial axes; exactly one checked size or scale; mode-specific rank and align_corners validation",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32",
        layout_rule: "Task 67 checked linear sampling owns boundaries; adapter extends separable sampling to one and three dimensions",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "nearest, nearest-exact, linear, bilinear, bicubic, trilinear, area, and normalized antialias kernels",
        tolerance: "1e-5",
        determinism: "plane, row-major output, then Cartesian axis-weight order",
        cancellation_points: "before validation, every 64 outputs, and before publication",
        vjp_rule: "transpose the exact separable sampling map",
        jvp_rule: "apply the exact sampling map to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/interpolate.json",
        evidence_fixture_sha256: "bafd5f26897a0ed94a0a4cf3ddf0d46da2584f6bd381a045d79a66f0e3ae4dea",
    },
    ResolvedOperationContract {
        resolution_module: "spatial_functional_kernel_01",
        operation_id: "COMFY-TENSOR-OP-1F9D23F3B331",
        baseline_overload_id: "COMFY-TENSOR-OP-1F9D23F3B331:blocked",
        baseline_fixture_sha256: "0b3741d1e572c3e09360efa552ff85d4539064469ee81f319c3cdd6f47ccb90d",
        overload_id: "zed.native.spatial.max-pool2d.task79-selection-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&[f32]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"input_shape","type":"&[usize]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"kernel_size","type":"[usize;2]","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"stride","type":"Option<[usize;2]>","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"padding","type":"[usize;2]","kind":"positional_or_keyword","keyword_only":false,"default":"[0,0]"},{"name":"dilation","type":"[usize;2]","kind":"positional_or_keyword","keyword_only":false,"default":"[1,1]"},{"name":"ceil_mode","type":"bool","kind":"positional_or_keyword","keyword_only":false,"default":false}]"##,
        output_arity: "1",
        output_types_json: r##"["TensorValues"]"##,
        rust_signature: "fn max_pool_2d_with_context_exact_native(input: &[f32], input_shape: &[usize], kernel_size: [usize; 2], stride: Option<[usize; 2]>, padding: [usize; 2], dilation: [usize; 2], ceil_mode: bool, device: DeviceId, context: &ExecutionContext<'_>) -> Result<TensorValues, SpatialFunctionalKernelError>",
        mutation_rule: "no mutation and no partial result",
        alias_rule: "fresh contiguous values",
        shape_rule: "Task 79 canonical NCHW/CHW geometry with default stride, padding, dilation, and ceil mode",
        dtype_rule: "certified f32 native path",
        accumulation_dtype: "f32 gradients",
        layout_rule: "Task 79 is sole maximum-selection and tie-breaking owner",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "exact maximum with first canonical connection selected on ties",
        tolerance: "bit exact forward and 1e-6 gradients",
        determinism: "canonical window traversal and stable first tie",
        cancellation_points: "before validation, canonical output checkpoints, and before publication",
        vjp_rule: "scatter cotangent to the selected canonical input",
        jvp_rule: "select the input tangent at the primal argmax",
        owner_task_id: "comfy-parity-tensor-ops-spatial-functional-kernel-comfy-tensor-op-1f9d23f3b331",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spatial_functional_kernel_01/max_pool2d.json",
        evidence_fixture_sha256: "96aad556f02604851b57dcf7fb60311ed314c04b0e8db3b3958173c557fe8438",
    },
]
