&[
    ResolvedOperationContract {
        resolution_module: "spectral_transform_01",
        operation_id: "COMFY-TENSOR-OP-7EC1A794152D",
        baseline_overload_id: "COMFY-TENSOR-OP-7EC1A794152D:blocked",
        baseline_fixture_sha256: "d6a521a413b20c708c928de9fec1b4eb2acd7578eba660a927f98433e45bcf89",
        overload_id: "zed.native.spectral.fftn.task55-complex-fft-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":"[-2,-1]"}]"##,
        output_arity: "1",
        output_types_json: r##"["Tensor"]"##,
        rust_signature: "fn fftn_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, SpectralTransformError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "fresh contiguous complex64 Tensor",
        shape_rule: "shape-preserving transform over a unique checked ordered axis list",
        dtype_rule: "f32 promotes to complex64 and complex64 remains complex64",
        accumulation_dtype: "complex f32",
        layout_rule: "logical strided input traversal and fresh row-major output",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "Task 55 canonical unnormalized forward complex DFT on each selected axis",
        tolerance: "2e-5",
        determinism: "selected axis order then outer, inner, frequency, and sample order",
        cancellation_points: "before validation, each line and tile, canonical FFT stages, encoding, and publication",
        vjp_rule: "unnormalized inverse transform with real projection for f32 primal inputs",
        jvp_rule: "forward transform of the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-spectral-transform-comfy-tensor-op-2c39e32acd3c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spectral_transform_01/fftn.json",
        evidence_fixture_sha256: "5aa8d824ea6be17c98bed2b340ccff97960ca23ee98f1b0343814f6a4265b44b",
    },
    ResolvedOperationContract {
        resolution_module: "spectral_transform_01",
        operation_id: "COMFY-TENSOR-OP-2C39E32ACD3C",
        baseline_overload_id: "COMFY-TENSOR-OP-2C39E32ACD3C:blocked",
        baseline_fixture_sha256: "a8e14311ba2c801e4bbed663a8c82d17c6bc24e2cc82dfd3ca659aa239b7ddb4",
        overload_id: "zed.native.spectral.fftshift.checked-roll-permutation.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":"[-2,-1]"}]"##,
        output_arity: "1",
        output_types_json: r##"["Tensor"]"##,
        rust_signature: "fn fftshift_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, SpectralTransformError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "fresh contiguous Tensor",
        shape_rule: "shape-preserving permutation over unique checked dimensions",
        dtype_rule: "byte-exact preservation of every native Tensor dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "logical strided input traversal and fresh row-major output",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "per-axis positive floor(n/2) roll including exact odd-length placement",
        tolerance: "bit exact",
        determinism: "row-major output coordinate order",
        cancellation_points: "before validation, every coordinate tile, and publication",
        vjp_rule: "inverse ifftshift permutation",
        jvp_rule: "identical fftshift permutation of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-spectral-transform-comfy-tensor-op-2c39e32acd3c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spectral_transform_01/fftshift.json",
        evidence_fixture_sha256: "c3af37751b368efc99f102f43a747d64c0fed8565ff5964962eb6bf7704b7246",
    },
    ResolvedOperationContract {
        resolution_module: "spectral_transform_01",
        operation_id: "COMFY-TENSOR-OP-E4297F97AD47",
        baseline_overload_id: "COMFY-TENSOR-OP-E4297F97AD47:blocked",
        baseline_fixture_sha256: "65e0cd70f26174e71b2619bdb344d38ef9d9001efdcf50b54efe69715fbe23ec",
        overload_id: "zed.native.spectral.ifftn.task55-complex-fft-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":"[-2,-1]"}]"##,
        output_arity: "1",
        output_types_json: r##"["Tensor"]"##,
        rust_signature: "fn ifftn_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, SpectralTransformError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "fresh contiguous complex64 Tensor",
        shape_rule: "shape-preserving transform over a unique checked ordered axis list",
        dtype_rule: "certified complex64 input and output",
        accumulation_dtype: "complex f32",
        layout_rule: "logical strided input traversal and fresh row-major output",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "Task 55 canonical positive-phase complex DFT divided once by the selected-axis extent product",
        tolerance: "2e-5",
        determinism: "selected axis order then outer, inner, frequency, and sample order",
        cancellation_points: "before validation, each line and tile, canonical FFT stages, normalization, encoding, and publication",
        vjp_rule: "forward transform divided by the selected-axis extent product",
        jvp_rule: "normalized inverse transform of the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-spectral-transform-comfy-tensor-op-2c39e32acd3c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spectral_transform_01/ifftn.json",
        evidence_fixture_sha256: "66622662f5be23df73060ecc949ce00ca845a5b463d984eb4ff05470c1c89558",
    },
    ResolvedOperationContract {
        resolution_module: "spectral_transform_01",
        operation_id: "COMFY-TENSOR-OP-D94BAB2BAD78",
        baseline_overload_id: "COMFY-TENSOR-OP-D94BAB2BAD78:blocked",
        baseline_fixture_sha256: "39fad8f07ca9c85caf55be931206b40fa4af51f8ab1546ea974a140e87f07aae",
        overload_id: "zed.native.spectral.ifftshift.checked-roll-permutation.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":"[-2,-1]"}]"##,
        output_arity: "1",
        output_types_json: r##"["Tensor"]"##,
        rust_signature: "fn ifftshift_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, SpectralTransformError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "fresh contiguous Tensor",
        shape_rule: "shape-preserving permutation over unique checked dimensions",
        dtype_rule: "byte-exact preservation of every native Tensor dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "logical strided input traversal and fresh row-major output",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "per-axis negative floor(n/2) roll including exact odd-length inverse placement",
        tolerance: "bit exact",
        determinism: "row-major output coordinate order",
        cancellation_points: "before validation, every coordinate tile, and publication",
        vjp_rule: "inverse fftshift permutation",
        jvp_rule: "identical ifftshift permutation of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-spectral-transform-comfy-tensor-op-2c39e32acd3c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spectral_transform_01/ifftshift.json",
        evidence_fixture_sha256: "4d956f6d6c9970e86645d2e6739b6d2a82516cd78662a5f2e35f45051a7a2d7d",
    },
]
