&[
    ResolvedOperationContract {
        resolution_module: "spectral_transform_01",
        operation_id: "COMFY-TENSOR-OP-7EC1A794152D",
        baseline_overload_id: "COMFY-TENSOR-OP-7EC1A794152D:blocked",
        baseline_fixture_sha256: "ef0a3878da1573a87bef266db4dac0a5d865fa2a2669288a85f8e76421847934",
        overload_id: "zed.native.spectral.fftn.task55-complex-fft-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":"[-2,-1]"}]"##,
        output_arity: "1",
        output_types_json: r##"["Tensor"]"##,
        rust_signature: "fn fftn_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, SpectralTransformError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "fresh contiguous complex64 Tensor",
        shape_rule: "shape-preserving transform over a unique checked ordered axis list",
        dtype_rule: "f32 promotes to complex64 and complex64 remains complex64",
        accumulation_dtype: "complex f32",
        layout_rule: "logical strided input traversal and fresh row-major output",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "Task 55 canonical unnormalized forward complex DFT on each selected axis",
        tolerance: "2e-5",
        determinism: "selected axis order then outer, inner, frequency, and sample order",
        cancellation_points: "before validation, each line and tile, canonical FFT stages, encoding, and publication",
        vjp_rule: "unnormalized inverse transform with real projection for f32 primal inputs",
        jvp_rule: "forward transform of the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-spectral-transform-comfy-tensor-op-2c39e32acd3c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spectral_transform_01/fftn.json",
        evidence_fixture_sha256: "04d0c5210f7dae09f105663afe19789260a4b5dc4cf2522166ee0a26e3ea64a8",
    },
    ResolvedOperationContract {
        resolution_module: "spectral_transform_01",
        operation_id: "COMFY-TENSOR-OP-2C39E32ACD3C",
        baseline_overload_id: "COMFY-TENSOR-OP-2C39E32ACD3C:blocked",
        baseline_fixture_sha256: "002b0e1477d2b7fcf73780862f76d85202940bfea4ddeb08ce024359513ab305",
        overload_id: "zed.native.spectral.fftshift.checked-roll-permutation.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":"[-2,-1]"}]"##,
        output_arity: "1",
        output_types_json: r##"["Tensor"]"##,
        rust_signature: "fn fftshift_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, SpectralTransformError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "fresh contiguous Tensor",
        shape_rule: "shape-preserving permutation over unique checked dimensions",
        dtype_rule: "byte-exact preservation of every native Tensor dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "logical strided input traversal and fresh row-major output",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "per-axis positive floor(n/2) roll including exact odd-length placement",
        tolerance: "bit exact",
        determinism: "row-major output coordinate order",
        cancellation_points: "before validation, every coordinate tile, and publication",
        vjp_rule: "inverse ifftshift permutation",
        jvp_rule: "identical fftshift permutation of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-spectral-transform-comfy-tensor-op-2c39e32acd3c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spectral_transform_01/fftshift.json",
        evidence_fixture_sha256: "6851503f6acc59f24084ee647d2450cacb44456c59e801d7ce98542335312a0b",
    },
    ResolvedOperationContract {
        resolution_module: "spectral_transform_01",
        operation_id: "COMFY-TENSOR-OP-E4297F97AD47",
        baseline_overload_id: "COMFY-TENSOR-OP-E4297F97AD47:blocked",
        baseline_fixture_sha256: "1e3963f788a8c702b68eacf00f128c382860cdfb0d9b6d06c7a1bb113dc40b89",
        overload_id: "zed.native.spectral.ifftn.task55-complex-fft-adapter.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":"[-2,-1]"}]"##,
        output_arity: "1",
        output_types_json: r##"["Tensor"]"##,
        rust_signature: "fn ifftn_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, SpectralTransformError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "fresh contiguous complex64 Tensor",
        shape_rule: "shape-preserving transform over a unique checked ordered axis list",
        dtype_rule: "certified complex64 input and output",
        accumulation_dtype: "complex f32",
        layout_rule: "logical strided input traversal and fresh row-major output",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "Task 55 canonical positive-phase complex DFT divided once by the selected-axis extent product",
        tolerance: "2e-5",
        determinism: "selected axis order then outer, inner, frequency, and sample order",
        cancellation_points: "before validation, each line and tile, canonical FFT stages, normalization, encoding, and publication",
        vjp_rule: "forward transform divided by the selected-axis extent product",
        jvp_rule: "normalized inverse transform of the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-spectral-transform-comfy-tensor-op-2c39e32acd3c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spectral_transform_01/ifftn.json",
        evidence_fixture_sha256: "9ba7d57ae974f34728d0ce0ff49b3a103954ab230898495084d1438b2a5ddfb1",
    },
    ResolvedOperationContract {
        resolution_module: "spectral_transform_01",
        operation_id: "COMFY-TENSOR-OP-D94BAB2BAD78",
        baseline_overload_id: "COMFY-TENSOR-OP-D94BAB2BAD78:blocked",
        baseline_fixture_sha256: "b1e757710e660ab8b13559793e947059256396f9349cc956e8bb476181f6c0c3",
        overload_id: "zed.native.spectral.ifftshift.checked-roll-permutation.v1",
        ordered_parameters_json: r##"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dimensions","type":"&[i64]","kind":"positional_or_keyword","keyword_only":false,"default":"[-2,-1]"}]"##,
        output_arity: "1",
        output_types_json: r##"["Tensor"]"##,
        rust_signature: "fn ifftshift_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dimensions: &[i64], context: &ExecutionContext<'_>) -> Result<Tensor, SpectralTransformError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "fresh contiguous Tensor",
        shape_rule: "shape-preserving permutation over unique checked dimensions",
        dtype_rule: "byte-exact preservation of every native Tensor dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "logical strided input traversal and fresh row-major output",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "per-axis negative floor(n/2) roll including exact odd-length inverse placement",
        tolerance: "bit exact",
        determinism: "row-major output coordinate order",
        cancellation_points: "before validation, every coordinate tile, and publication",
        vjp_rule: "inverse fftshift permutation",
        jvp_rule: "identical ifftshift permutation of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-spectral-transform-comfy-tensor-op-2c39e32acd3c",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/spectral_transform_01/ifftshift.json",
        evidence_fixture_sha256: "c0ec118ef2ef0ab13a26cce3ee8bfe67efe87f9631474603da6978a0994cca8b",
    },
]
