&[
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-4FE9C7A46973",
        baseline_overload_id: "COMFY-TENSOR-OP-4FE9C7A46973:blocked",
        baseline_fixture_sha256: "2f9533f8cddafa427ae7a7b9bcca7bc015225bea61fe28d405c9b0007c723cc8",
        overload_id: "zed.native.tensor.clone.canonical-storage-copy.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"PreserveFormat"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn clone_with_context_exact_native(backend: &CpuBackend, input: &Tensor, memory_format: MemoryFormatReference, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "fresh canonical storage allocation",
        shape_rule: "shape preserving",
        dtype_rule: "dtype preserving",
        accumulation_dtype: "not applicable",
        layout_rule: "preserve-format retains non-overlapping strides; named formats use TensorDescriptor validation",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "bit-exact logical element copy",
        tolerance: "bit exact",
        determinism: "canonical logical index order",
        cancellation_points: "before validation and throughout CpuBackend copy before publication",
        vjp_rule: "identity copied into primal layout",
        jvp_rule: "clone of the tangent with the same memory format",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/clone.json",
        evidence_fixture_sha256: "a3d3ec615c5ba284c7ca19e1f4758f41b92df2318f8f45c5ee4eed4e27e0904d",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-B044D0F40FCE",
        baseline_overload_id: "COMFY-TENSOR-OP-B044D0F40FCE:blocked",
        baseline_fixture_sha256: "f85cff1c6789aad123a757d2e868617a64e725ff75dcb8a060cb38c0ba558e66",
        overload_id: "zed.native.tensor.contiguous.conditional-alias.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"Layout(Contiguous)"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn contiguous_with_context_exact_native(backend: &CpuBackend, input: &Tensor, memory_format: MemoryFormatReference, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "returns the canonical input storage alias when already matching, otherwise fresh storage",
        shape_rule: "shape preserving",
        dtype_rule: "dtype preserving",
        accumulation_dtype: "not applicable",
        layout_rule: "named format validated by TensorDescriptor; arbitrary Strided is rejected",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "bit-exact logical element copy when conversion is required",
        tolerance: "bit exact",
        determinism: "canonical logical index order",
        cancellation_points: "before alias decision and throughout CpuBackend copy before publication",
        vjp_rule: "identity copied into primal layout",
        jvp_rule: "contiguous conversion of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/contiguous.json",
        evidence_fixture_sha256: "859fb7fc1f57d3acce93d86fe5775490f1c70957bf922eec4cc90b8c1ea60e8f",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-243D55E505F5",
        baseline_overload_id: "COMFY-TENSOR-OP-243D55E505F5:blocked",
        baseline_fixture_sha256: "9217c4a9887c8a2b5893fe98533a3457439b9757f2d1562362136329f4982c31",
        overload_id: "zed.native.tensor.copy-inplace.transactional-broadcast.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"destination","type":"&mut Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"source","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"non_blocking","type":"bool","kind":"keyword_only","keyword_only":true,"default":"false"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn copy_with_context_exact_native(backend: &CpuBackend, destination: &mut Tensor, source: &Tensor, non_blocking: bool, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "stage the complete broadcast and cast before one canonical destination write lease; failures publish no mutation",
        alias_rule: "returns an alias of the committed destination storage",
        shape_rule: "source trailing dimensions broadcast to destination shape",
        dtype_rule: "source scalars convert through the canonical DType codec to destination dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "logical source and destination strides are honored",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical scalar conversion including checked unsupported conversions",
        tolerance: "dtype conversion exactness",
        determinism: "destination row-major logical order",
        cancellation_points: "before validation, at staging tiles, and immediately before the non-cancellable commit",
        vjp_rule: "destination history is overwritten; differentiable source VJP is the broadcast reduction in the canonical autograd composition",
        jvp_rule: "broadcast and cast the source tangent",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/copy.json",
        evidence_fixture_sha256: "c2a739414c3ac27b5519df7a0b2b92552612520b811b62ce1e8be2c4f578e756",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-A59F2D9336D7",
        baseline_overload_id: "COMFY-TENSOR-OP-A59F2D9336D7:blocked",
        baseline_fixture_sha256: "ee16f6f6fc510e00614257e7beb4e2111e80a67fc1d7d77b38025ef83869664a",
        overload_id: "zed.native.tensor.cpu.canonical-to-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"PreserveFormat"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn cpu_with_context_exact_native(backend: &CpuBackend, input: &Tensor, memory_format: MemoryFormatReference, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation",
        alias_rule: "aliases an already matching CPU tensor, otherwise follows canonical transfer copy semantics",
        shape_rule: "shape preserving",
        dtype_rule: "dtype preserving",
        accumulation_dtype: "not applicable",
        layout_rule: "requested format is validated by TensorDescriptor",
        device_rule: "targets canonical CPU device zero",
        numeric_rule: "bit-exact transfer",
        tolerance: "bit exact",
        determinism: "canonical cast/copy order",
        cancellation_points: "canonical to and backend transfer points",
        vjp_rule: "identity transfer to the primal device",
        jvp_rule: "CPU transfer of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/cpu.json",
        evidence_fixture_sha256: "783f5eeec56cf5c8d8bfdb91695df53b7bee6dd91ce7a67f58d6907ac5a9105e",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-03EA795D0AC8",
        baseline_overload_id: "COMFY-TENSOR-OP-03EA795D0AC8:blocked",
        baseline_fixture_sha256: "3968b54940df3fe27b53a94e1f15ba356d5ccfe42518c28315de7ae0b8aa59b0",
        overload_id: "zed.native.tensor.cuda.typed-unavailable-boundary.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"ordinal","type":"Option<u32>","kind":"positional_or_keyword","keyword_only":false,"default":"None"},{"name":"non_blocking","type":"bool","kind":"keyword_only","keyword_only":true,"default":"false"},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"PreserveFormat"},{"name":"cancellation","type":"&CancellationToken","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn cuda_with_context_exact_native(input: &Tensor, ordinal: Option<u32>, non_blocking: bool, memory_format: MemoryFormatReference, cancellation: &CancellationToken) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no mutation",
        alias_rule: "no output is published without a certified CUDA backend",
        shape_rule: "shape preserving when a CUDA backend is certified",
        dtype_rule: "dtype preserving",
        accumulation_dtype: "not applicable",
        layout_rule: "preserve or named format",
        device_rule: "returns typed CUDA unavailability in the current CPU certification instead of falling back",
        numeric_rule: "no CPU emulation or external-server fallback",
        tolerance: "not applicable",
        determinism: "cancellation precedes availability diagnostics",
        cancellation_points: "before backend availability resolution",
        vjp_rule: "identity transfer only when the backend is certified",
        jvp_rule: "CUDA transfer only when the backend is certified",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/cuda.json",
        evidence_fixture_sha256: "94c1cdda6efd94a46b7c366cc9b498e128d7e301af2aa4b6b43e9666f8be7a04",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-99D902CE1938",
        baseline_overload_id: "COMFY-TENSOR-OP-99D902CE1938:blocked",
        baseline_fixture_sha256: "5178e31940c3c3d35cb1e6d182f2fc744c344d5c87b68d6c41b078cc932824f4",
        overload_id: "zed.native.tensor.float.canonical-cast-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"PreserveFormat"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn float_with_context_exact_native(backend: &CpuBackend, input: &Tensor, memory_format: MemoryFormatReference, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation",
        alias_rule: "aliases an already matching tensor unless a format copy is required",
        shape_rule: "shape preserving",
        dtype_rule: "canonical conversion to float32",
        accumulation_dtype: "float32",
        layout_rule: "preserve or named format through TensorDescriptor",
        device_rule: "input device preserving within certified CPU",
        numeric_rule: "DType codec conversion",
        tolerance: "float32 representability",
        determinism: "canonical logical element order",
        cancellation_points: "canonical cast and backend copy points",
        vjp_rule: "cast output gradient back to the differentiable primal dtype",
        jvp_rule: "cast the input tangent to float32",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/float.json",
        evidence_fixture_sha256: "f147f6d83494dcd32fc9d6845d490a1f7b630551b0e2f3855b622cf04ccd9ab6",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-CFD813E3EE51",
        baseline_overload_id: "COMFY-TENSOR-OP-CFD813E3EE51:blocked",
        baseline_fixture_sha256: "deddf86cf5506430c1d6893cfa8e7af63a12b0116a85cf72fc1278014bac5cfd",
        overload_id: "zed.native.tensor.half.canonical-cast-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"PreserveFormat"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn half_with_context_exact_native(backend: &CpuBackend, input: &Tensor, memory_format: MemoryFormatReference, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation",
        alias_rule: "aliases an already matching tensor unless a format copy is required",
        shape_rule: "shape preserving",
        dtype_rule: "canonical conversion to float16",
        accumulation_dtype: "float16 conversion",
        layout_rule: "preserve or named format through TensorDescriptor",
        device_rule: "input device preserving within certified CPU",
        numeric_rule: "IEEE binary16 conversion through the DType codec",
        tolerance: "float16 representability",
        determinism: "canonical logical element order",
        cancellation_points: "canonical cast and backend copy points",
        vjp_rule: "cast output gradient back to the differentiable primal dtype",
        jvp_rule: "cast the input tangent to float16",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/half.json",
        evidence_fixture_sha256: "a4969ede4f4f8d4b10bc3f9c27e5887110be5a6d1e091278c3592e2358b3af6b",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-00F639D6C8A7",
        baseline_overload_id: "COMFY-TENSOR-OP-00F639D6C8A7:blocked",
        baseline_fixture_sha256: "4260875d6311cab50dfe1eb1bff9eeea338dc056aefd2d5a220f9d2d2049642c",
        overload_id: "zed.native.tensor.numpy.immutable-native-array-borrow.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"cancellation","type":"&CancellationToken","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeArrayView<'_>"]"#,
        rust_signature: "fn numpy_exact_native<'a>(input: &'a Tensor, cancellation: &CancellationToken) -> Result<NativeArrayView<'a>, StorageDTypeDeviceError>",
        mutation_rule: "immutable borrow only",
        alias_rule: "borrows canonical host storage without copying or creating a second storage owner",
        shape_rule: "exposes exact shape, element offset, and signed byte strides",
        dtype_rule: "exposes the canonical DType directly",
        accumulation_dtype: "not applicable",
        layout_rule: "arbitrary valid logical strides remain visible",
        device_rule: "CPU host storage only with typed rejection elsewhere",
        numeric_rule: "byte-exact native array access; no Python or NumPy process executes",
        tolerance: "bit exact",
        determinism: "metadata-only adapter",
        cancellation_points: "before host storage admission",
        vjp_rule: "forward-only host interoperability boundary",
        jvp_rule: "forward-only host interoperability boundary",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/numpy.json",
        evidence_fixture_sha256: "bebadbf671132b3dfbb7a0f8f981f6937858c00164a38b00ff18146137061c15",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-D9F653A3B821",
        baseline_overload_id: "COMFY-TENSOR-OP-D9F653A3B821:blocked",
        baseline_fixture_sha256: "40a726d5ff71cef9dc13f0297de8d8a87e57ee27cd179ba4c60df322fe5c9a5e",
        overload_id: "zed.native.tensor.to.task46-cast-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dtype","type":"Option<DType>","kind":"keyword_only","keyword_only":true,"default":"None"},{"name":"device","type":"Option<DeviceId>","kind":"keyword_only","keyword_only":true,"default":"None"},{"name":"non_blocking","type":"bool","kind":"keyword_only","keyword_only":true,"default":"false"},{"name":"copy","type":"bool","kind":"keyword_only","keyword_only":true,"default":"false"},{"name":"memory_format","type":"Option<MemoryFormatReference>","kind":"keyword_only","keyword_only":true,"default":"None"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn to_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dtype: Option<DType>, device: Option<DeviceId>, non_blocking: bool, copy: bool, memory_format: Option<MemoryFormatReference>, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "aliases only when dtype, device, and format match and copy is false",
        shape_rule: "shape preserving",
        dtype_rule: "delegates all scalar conversion to Task 46 and DType",
        accumulation_dtype: "target dtype conversion",
        layout_rule: "TensorDescriptor owns preserve and named format validation",
        device_rule: "certified CPU only with typed accelerator unavailability and no fallback",
        numeric_rule: "Task 46 canonical codec conversion",
        tolerance: "target dtype representability",
        determinism: "canonical Task 46 logical element order",
        cancellation_points: "before validation and at every canonical cast/copy boundary",
        vjp_rule: "cast output gradient back to the differentiable primal dtype and device",
        jvp_rule: "apply the same differentiable cast to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/to.json",
        evidence_fixture_sha256: "cab39ab3ac556e5a2d454e8eba6fa5c4ea1d88df44ec8aedff7553d4385f4dd0",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-90C921ECD7A0",
        baseline_overload_id: "COMFY-TENSOR-OP-90C921ECD7A0:blocked",
        baseline_fixture_sha256: "e4ae3bcb283a47d49217f5abd598a8327d4405e6632678b77afb6489a6ab215a",
        overload_id: "zed.native.tensor.type.query-or-cast.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"request","type":"TensorTypeRequest","kind":"positional_or_keyword","keyword_only":false,"default":"Query"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["TensorTypeResult"]"#,
        rust_signature: "fn tensor_type_with_context_exact_native(backend: &CpuBackend, input: &Tensor, request: TensorTypeRequest, context: &ExecutionContext<'_>) -> Result<TensorTypeResult, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation",
        alias_rule: "query returns static metadata; conversion follows canonical to alias/copy rules",
        shape_rule: "conversion is shape preserving",
        dtype_rule: "query exposes the canonical legacy CPU type name; conversion uses DType",
        accumulation_dtype: "target dtype conversion",
        layout_rule: "conversion preserves format",
        device_rule: "legacy names are certified for CPU; unsupported device/type combinations are typed errors",
        numeric_rule: "query is metadata-only and conversion delegates to Task 46",
        tolerance: "target dtype representability",
        determinism: "closed legacy name table or canonical conversion",
        cancellation_points: "before query or conversion dispatch and canonical conversion points",
        vjp_rule: "conversion uses the cast VJP; query is forward-only metadata",
        jvp_rule: "conversion uses the cast JVP; query is forward-only metadata",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/type.json",
        evidence_fixture_sha256: "bbf71af1146776d8634999e0a88bad1a3076b1362dee2af60145447aa4ad2eb0",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-B3036C455992",
        baseline_overload_id: "COMFY-TENSOR-OP-B3036C455992:blocked",
        baseline_fixture_sha256: "efc64f8d86c827926d4349499f18f34c21cd7f3a7280f35d5a44ed092d19e728",
        overload_id: "zed.native.tensor.type-as.canonical-to-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"other","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn type_as_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input or reference mutation",
        alias_rule: "canonical to alias/copy behavior against the reference dtype and device",
        shape_rule: "input shape preserving; reference shape is irrelevant",
        dtype_rule: "target dtype is the reference tensor dtype",
        accumulation_dtype: "target dtype conversion",
        layout_rule: "input format preserving",
        device_rule: "target device is the reference device within certified backends",
        numeric_rule: "Task 46 canonical codec conversion",
        tolerance: "target dtype representability",
        determinism: "canonical Task 46 logical element order",
        cancellation_points: "before dispatch and canonical cast/copy points",
        vjp_rule: "cast output gradient back to the differentiable primal dtype and device",
        jvp_rule: "cast the input tangent to the reference dtype and device",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/type_as.json",
        evidence_fixture_sha256: "1a49035c4c78225086553d210401b39605f42e48d455d64cfb58c5b536df2cd8",
    },
]
