&[
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-4FE9C7A46973",
        baseline_overload_id: "COMFY-TENSOR-OP-4FE9C7A46973:blocked",
        baseline_fixture_sha256: "f8e9523ffab5cf7d93276716942b63e795e5177fdf4bbc11a420fa4d5207e1ff",
        overload_id: "sim.native.tensor.clone.canonical-storage-copy.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"PreserveFormat"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn clone_with_context_exact_native(backend: &CpuBackend, input: &Tensor, memory_format: MemoryFormatReference, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "fresh canonical storage allocation",
        shape_rule: "shape preserving",
        dtype_rule: "dtype preserving",
        accumulation_dtype: "not applicable",
        layout_rule: "preserve-format retains non-overlapping strides; named formats use TensorDescriptor validation",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "bit-exact logical element copy",
        tolerance: "bit exact",
        determinism: "canonical logical index order",
        cancellation_points: "before validation and throughout CpuBackend copy before publication",
        vjp_rule: "identity copied into primal layout",
        jvp_rule: "clone of the tangent with the same memory format",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/clone.json",
        evidence_fixture_sha256: "5b18a667357d16b776c8b63ebd3b7e194e683a44a59e022fd6566c9525b4a74a",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-B044D0F40FCE",
        baseline_overload_id: "COMFY-TENSOR-OP-B044D0F40FCE:blocked",
        baseline_fixture_sha256: "8c8634ca3cbd68ecc5c2ea33308cadbb7179e220d4013513b407960b093a0819",
        overload_id: "sim.native.tensor.contiguous.conditional-alias.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"Layout(Contiguous)"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn contiguous_with_context_exact_native(backend: &CpuBackend, input: &Tensor, memory_format: MemoryFormatReference, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "returns the canonical input storage alias when already matching, otherwise fresh storage",
        shape_rule: "shape preserving",
        dtype_rule: "dtype preserving",
        accumulation_dtype: "not applicable",
        layout_rule: "named format validated by TensorDescriptor; arbitrary Strided is rejected",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "bit-exact logical element copy when conversion is required",
        tolerance: "bit exact",
        determinism: "canonical logical index order",
        cancellation_points: "before alias decision and throughout CpuBackend copy before publication",
        vjp_rule: "identity copied into primal layout",
        jvp_rule: "contiguous conversion of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/contiguous.json",
        evidence_fixture_sha256: "ece8e84f49320f0514ed3d4a76b48306f83aab4054e326cfa49d410b4cd44fd3",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-243D55E505F5",
        baseline_overload_id: "COMFY-TENSOR-OP-243D55E505F5:blocked",
        baseline_fixture_sha256: "1bcde662b381bccccc9d95ee0e8de50db4c5aabd97c40551aa80954fb0bea94e",
        overload_id: "sim.native.tensor.copy-inplace.transactional-broadcast.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"destination","type":"&mut Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"source","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"non_blocking","type":"bool","kind":"keyword_only","keyword_only":true,"default":"false"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn copy_with_context_exact_native(backend: &CpuBackend, destination: &mut Tensor, source: &Tensor, non_blocking: bool, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "stage the complete broadcast and cast before one canonical destination write lease; failures publish no mutation",
        alias_rule: "returns an alias of the committed destination storage",
        shape_rule: "source trailing dimensions broadcast to destination shape",
        dtype_rule: "source scalars convert through the canonical DType codec to destination dtype",
        accumulation_dtype: "not applicable",
        layout_rule: "logical source and destination strides are honored",
        device_rule: "CPU certified with typed unavailability elsewhere",
        numeric_rule: "canonical scalar conversion including checked unsupported conversions",
        tolerance: "dtype conversion exactness",
        determinism: "destination row-major logical order",
        cancellation_points: "before validation, at staging tiles, and immediately before the non-cancellable commit",
        vjp_rule: "destination history is overwritten; differentiable source VJP is the broadcast reduction in the canonical autograd composition",
        jvp_rule: "broadcast and cast the source tangent",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/copy.json",
        evidence_fixture_sha256: "c560079c8eb87758e9437d764d90ccd4ef62fcbaa345924cbca9fa398d38e3d3",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-A59F2D9336D7",
        baseline_overload_id: "COMFY-TENSOR-OP-A59F2D9336D7:blocked",
        baseline_fixture_sha256: "1eb29d7eaa3fee21b849c99a9e6c6cfd90389bbfac0266ad64e15c95630066c8",
        overload_id: "sim.native.tensor.cpu.canonical-to-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"PreserveFormat"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn cpu_with_context_exact_native(backend: &CpuBackend, input: &Tensor, memory_format: MemoryFormatReference, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation",
        alias_rule: "aliases an already matching CPU tensor, otherwise follows canonical transfer copy semantics",
        shape_rule: "shape preserving",
        dtype_rule: "dtype preserving",
        accumulation_dtype: "not applicable",
        layout_rule: "requested format is validated by TensorDescriptor",
        device_rule: "targets canonical CPU device zero",
        numeric_rule: "bit-exact transfer",
        tolerance: "bit exact",
        determinism: "canonical cast/copy order",
        cancellation_points: "canonical to and backend transfer points",
        vjp_rule: "identity transfer to the primal device",
        jvp_rule: "CPU transfer of the tangent",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/cpu.json",
        evidence_fixture_sha256: "e85bf5eb2641d57d3d0431c39f16a1286046ea61171aca66a955c82a513b0e6b",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-03EA795D0AC8",
        baseline_overload_id: "COMFY-TENSOR-OP-03EA795D0AC8:blocked",
        baseline_fixture_sha256: "788cf284ccf569a6c10ba3d580543fdbafc1847e7dd713bab43a80ac86fc0d21",
        overload_id: "sim.native.tensor.cuda.typed-unavailable-boundary.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"ordinal","type":"Option<u32>","kind":"positional_or_keyword","keyword_only":false,"default":"None"},{"name":"non_blocking","type":"bool","kind":"keyword_only","keyword_only":true,"default":"false"},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"PreserveFormat"},{"name":"cancellation","type":"&CancellationToken","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn cuda_with_context_exact_native(input: &Tensor, ordinal: Option<u32>, non_blocking: bool, memory_format: MemoryFormatReference, cancellation: &CancellationToken) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no mutation",
        alias_rule: "no output is published without a certified CUDA backend",
        shape_rule: "shape preserving when a CUDA backend is certified",
        dtype_rule: "dtype preserving",
        accumulation_dtype: "not applicable",
        layout_rule: "preserve or named format",
        device_rule: "returns typed CUDA unavailability in the current CPU certification instead of falling back",
        numeric_rule: "no CPU emulation or external-server fallback",
        tolerance: "not applicable",
        determinism: "cancellation precedes availability diagnostics",
        cancellation_points: "before backend availability resolution",
        vjp_rule: "identity transfer only when the backend is certified",
        jvp_rule: "CUDA transfer only when the backend is certified",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/cuda.json",
        evidence_fixture_sha256: "4f13b19bbf2f37d4dc6ed645984c869a1badea0e0364f82fa211eb9a4a8a3d4c",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-99D902CE1938",
        baseline_overload_id: "COMFY-TENSOR-OP-99D902CE1938:blocked",
        baseline_fixture_sha256: "b80b45908e86ac406ea7db8af31c7682b9af8a705213d3a420de1ab3258ea2ba",
        overload_id: "sim.native.tensor.float.canonical-cast-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"PreserveFormat"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn float_with_context_exact_native(backend: &CpuBackend, input: &Tensor, memory_format: MemoryFormatReference, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation",
        alias_rule: "aliases an already matching tensor unless a format copy is required",
        shape_rule: "shape preserving",
        dtype_rule: "canonical conversion to float32",
        accumulation_dtype: "float32",
        layout_rule: "preserve or named format through TensorDescriptor",
        device_rule: "input device preserving within certified CPU",
        numeric_rule: "DType codec conversion",
        tolerance: "float32 representability",
        determinism: "canonical logical element order",
        cancellation_points: "canonical cast and backend copy points",
        vjp_rule: "cast output gradient back to the differentiable primal dtype",
        jvp_rule: "cast the input tangent to float32",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/float.json",
        evidence_fixture_sha256: "56d03f96751ed875b2ec5acbee70d4de97921da25379f9ddfa7ac1884fd5173e",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-CFD813E3EE51",
        baseline_overload_id: "COMFY-TENSOR-OP-CFD813E3EE51:blocked",
        baseline_fixture_sha256: "c157baa4287735a8b95ed7d4dc4b0e9c8c600243725cfd25debb56a58212bcfb",
        overload_id: "sim.native.tensor.half.canonical-cast-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"memory_format","type":"MemoryFormatReference","kind":"keyword_only","keyword_only":true,"default":"PreserveFormat"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn half_with_context_exact_native(backend: &CpuBackend, input: &Tensor, memory_format: MemoryFormatReference, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation",
        alias_rule: "aliases an already matching tensor unless a format copy is required",
        shape_rule: "shape preserving",
        dtype_rule: "canonical conversion to float16",
        accumulation_dtype: "float16 conversion",
        layout_rule: "preserve or named format through TensorDescriptor",
        device_rule: "input device preserving within certified CPU",
        numeric_rule: "IEEE binary16 conversion through the DType codec",
        tolerance: "float16 representability",
        determinism: "canonical logical element order",
        cancellation_points: "canonical cast and backend copy points",
        vjp_rule: "cast output gradient back to the differentiable primal dtype",
        jvp_rule: "cast the input tangent to float16",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/half.json",
        evidence_fixture_sha256: "4915f7643095ca0c38fcd150e56d15dd3fca13b3836239067c6ffa81a2090558",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-00F639D6C8A7",
        baseline_overload_id: "COMFY-TENSOR-OP-00F639D6C8A7:blocked",
        baseline_fixture_sha256: "013b96f04e5aff99e1e06399e5f4b0e7b5370c99aa9d9ebf3cbdb7009f95494b",
        overload_id: "sim.native.tensor.numpy.immutable-native-array-borrow.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"cancellation","type":"&CancellationToken","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["NativeArrayView<'_>"]"#,
        rust_signature: "fn numpy_exact_native<'a>(input: &'a Tensor, cancellation: &CancellationToken) -> Result<NativeArrayView<'a>, StorageDTypeDeviceError>",
        mutation_rule: "immutable borrow only",
        alias_rule: "borrows canonical host storage without copying or creating a second storage owner",
        shape_rule: "exposes exact shape, element offset, and signed byte strides",
        dtype_rule: "exposes the canonical DType directly",
        accumulation_dtype: "not applicable",
        layout_rule: "arbitrary valid logical strides remain visible",
        device_rule: "CPU host storage only with typed rejection elsewhere",
        numeric_rule: "byte-exact native array access; no Python or NumPy process executes",
        tolerance: "bit exact",
        determinism: "metadata-only adapter",
        cancellation_points: "before host storage admission",
        vjp_rule: "forward-only host interoperability boundary",
        jvp_rule: "forward-only host interoperability boundary",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/numpy.json",
        evidence_fixture_sha256: "4323b3c6f4ba2d7acfceb0148e9195ed15abc8139d6e7bb133a4eee6ae62d9e8",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-D9F653A3B821",
        baseline_overload_id: "COMFY-TENSOR-OP-D9F653A3B821:blocked",
        baseline_fixture_sha256: "b51d8c2d29262512ec2440c57a42d7add6b382cdd7d77e601a595d022e775871",
        overload_id: "sim.native.tensor.to.task46-cast-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"dtype","type":"Option<DType>","kind":"keyword_only","keyword_only":true,"default":"None"},{"name":"device","type":"Option<DeviceId>","kind":"keyword_only","keyword_only":true,"default":"None"},{"name":"non_blocking","type":"bool","kind":"keyword_only","keyword_only":true,"default":"false"},{"name":"copy","type":"bool","kind":"keyword_only","keyword_only":true,"default":"false"},{"name":"memory_format","type":"Option<MemoryFormatReference>","kind":"keyword_only","keyword_only":true,"default":"None"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn to_with_context_exact_native(backend: &CpuBackend, input: &Tensor, dtype: Option<DType>, device: Option<DeviceId>, non_blocking: bool, copy: bool, memory_format: Option<MemoryFormatReference>, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation and no partial publication",
        alias_rule: "aliases only when dtype, device, and format match and copy is false",
        shape_rule: "shape preserving",
        dtype_rule: "delegates all scalar conversion to Task 46 and DType",
        accumulation_dtype: "target dtype conversion",
        layout_rule: "TensorDescriptor owns preserve and named format validation",
        device_rule: "certified CPU only with typed accelerator unavailability and no fallback",
        numeric_rule: "Task 46 canonical codec conversion",
        tolerance: "target dtype representability",
        determinism: "canonical Task 46 logical element order",
        cancellation_points: "before validation and at every canonical cast/copy boundary",
        vjp_rule: "cast output gradient back to the differentiable primal dtype and device",
        jvp_rule: "apply the same differentiable cast to the input tangent",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/to.json",
        evidence_fixture_sha256: "2fd954e9382cace3346adf84b3c6762091b0517d5b20b1f2db558153a36b6fe1",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-90C921ECD7A0",
        baseline_overload_id: "COMFY-TENSOR-OP-90C921ECD7A0:blocked",
        baseline_fixture_sha256: "5ab44a842eb00848ad2eae3825c4f26ff5dc0f417bf8ef3f278197fe333f7820",
        overload_id: "sim.native.tensor.type.query-or-cast.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"request","type":"TensorTypeRequest","kind":"positional_or_keyword","keyword_only":false,"default":"Query"},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["TensorTypeResult"]"#,
        rust_signature: "fn tensor_type_with_context_exact_native(backend: &CpuBackend, input: &Tensor, request: TensorTypeRequest, context: &ExecutionContext<'_>) -> Result<TensorTypeResult, StorageDTypeDeviceError>",
        mutation_rule: "no input mutation",
        alias_rule: "query returns static metadata; conversion follows canonical to alias/copy rules",
        shape_rule: "conversion is shape preserving",
        dtype_rule: "query exposes the canonical legacy CPU type name; conversion uses DType",
        accumulation_dtype: "target dtype conversion",
        layout_rule: "conversion preserves format",
        device_rule: "legacy names are certified for CPU; unsupported device/type combinations are typed errors",
        numeric_rule: "query is metadata-only and conversion delegates to Task 46",
        tolerance: "target dtype representability",
        determinism: "closed legacy name table or canonical conversion",
        cancellation_points: "before query or conversion dispatch and canonical conversion points",
        vjp_rule: "conversion uses the cast VJP; query is forward-only metadata",
        jvp_rule: "conversion uses the cast JVP; query is forward-only metadata",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/type.json",
        evidence_fixture_sha256: "c40956b26df948fc8c67ed3f82f3ae4b3b130165ffd8cccba3615e798402a8ca",
    },
    ResolvedOperationContract {
        resolution_module: "storage_dtype_device_01",
        operation_id: "COMFY-TENSOR-OP-B3036C455992",
        baseline_overload_id: "COMFY-TENSOR-OP-B3036C455992:blocked",
        baseline_fixture_sha256: "bf2445fbd2be8594ff520841ba6735c185ddea6ebd074d4e2a7186125e939316",
        overload_id: "sim.native.tensor.type-as.canonical-to-adapter.v1",
        ordered_parameters_json: r#"[{"name":"backend","type":"&CpuBackend","kind":"positional_only","keyword_only":false,"default":null},{"name":"input","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"other","type":"&Tensor","kind":"positional_or_keyword","keyword_only":false,"default":null},{"name":"context","type":"&ExecutionContext<'_>","kind":"positional_only","keyword_only":false,"default":null}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn type_as_with_context_exact_native(backend: &CpuBackend, input: &Tensor, other: &Tensor, context: &ExecutionContext<'_>) -> Result<Tensor, StorageDTypeDeviceError>",
        mutation_rule: "no input or reference mutation",
        alias_rule: "canonical to alias/copy behavior against the reference dtype and device",
        shape_rule: "input shape preserving; reference shape is irrelevant",
        dtype_rule: "target dtype is the reference tensor dtype",
        accumulation_dtype: "target dtype conversion",
        layout_rule: "input format preserving",
        device_rule: "target device is the reference device within certified backends",
        numeric_rule: "Task 46 canonical codec conversion",
        tolerance: "target dtype representability",
        determinism: "canonical Task 46 logical element order",
        cancellation_points: "before dispatch and canonical cast/copy points",
        vjp_rule: "cast output gradient back to the differentiable primal dtype and device",
        jvp_rule: "cast the input tangent to the reference dtype and device",
        owner_task_id: "comfy-parity-tensor-ops-storage-dtype-device-comfy-tensor-op-00f639d6c8a7",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/storage_dtype_device_01/type_as.json",
        evidence_fixture_sha256: "10eebe2078ab49ccf7602380722318b55b597b7660ded3a8d66649237db2a10a",
    },
]
