&[
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-583EFBAFDD35",
        baseline_overload_id: "COMFY-TENSOR-OP-583EFBAFDD35:blocked",
        baseline_fixture_sha256: "771215c62015a209d342c8dc5a4d97c120c1d41156853101deb5839b44786ed8",
        overload_id: "zed.native.tensor.arange.cpu-real-strided.v1",
        ordered_parameters_json: r#"[{"name":"start","type":"Scalar","default":0,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"end","type":"Scalar","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"step","type":"Scalar","default":1,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"Option<DType>","default":null,"keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn arange_with_context_exact_native(backend: &CpuBackend, start: Scalar, end: Scalar, step: Scalar, dtype: Option<DType>, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh output published only after complete checked generation and upload",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "rank-one ceil-divided half-open range including empty direction mismatch",
        dtype_rule: "defaults to I64 for integral scalars and F32 when any scalar is floating; explicit real numeric dtype is checked",
        accumulation_dtype: "I128 for integral bounds and F64 for floating bounds",
        layout_rule: "source torch.strided request maps to physically contiguous row-major storage",
        device_rule: "CPU certified; every other device returns a typed unavailable error",
        numeric_rule: "start plus logical index times step with exact integer arithmetic and finite floating bounds",
        tolerance: "bit exact for integers and destination-dtype rounding for floating values",
        determinism: "ascending logical index traversal",
        cancellation_points: "before validation, every 1024 values, during upload, and before publication",
        vjp_rule: "forward-only discrete sequence creation with no differentiable tensor input",
        jvp_rule: "forward-only discrete sequence creation with no differentiable tensor input",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/arange.json",
        evidence_fixture_sha256: "b4ae28c242c7cae3a7371934bca2faab25e402cf8a4d52adca367cc56dd3cddd",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-1D3DBB9A17A7",
        baseline_overload_id: "COMFY-TENSOR-OP-1D3DBB9A17A7:blocked",
        baseline_fixture_sha256: "a1fb1399865c0e19a988be1ebae21c512d0a85cca423cb68064d48ac7f2449fe",
        overload_id: "zed.native.tensor.as-tensor.checked-input.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"NativeTensorInput<'_>","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"Option<DType>","default":null,"keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"Option<DeviceId>","default":null,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn as_tensor_with_context_exact_native(backend: &CpuBackend, input: NativeTensorInput<'_>, dtype: Option<DType>, device: Option<DeviceId>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "input is never mutated and conversion publishes only after the canonical cast completes",
        alias_rule: "same dtype and device Tensor input aliases canonical storage; literals allocate and conversions copy",
        shape_rule: "preserves Tensor and native-array shape; literal shape must exactly match value count",
        dtype_rule: "preserves Tensor or native-array dtype, infers literal Bool/I64/F32, or applies an explicit canonical cast",
        accumulation_dtype: "canonical dtype codec and cast traversal",
        layout_rule: "preserves an exact alias or publishes a contiguous conversion",
        device_rule: "CPU certified with typed errors for unavailable devices",
        numeric_rule: "canonical checked scalar encoding and dtype conversion",
        tolerance: "bit exact for aliases and integers; destination-dtype rounding for casts",
        determinism: "logical row-major literal and cast traversal",
        cancellation_points: "before validation, throughout conversion, and before publication",
        vjp_rule: "identity for aliases and canonical cast VJP for differentiable conversions",
        jvp_rule: "identity for aliases and canonical cast JVP for differentiable conversions",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/as_tensor.json",
        evidence_fixture_sha256: "232ab61bc27db5f02f5daa181d71a37e8ad23f48c7f62d80774cddcd988488b5",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-9FE84462B357",
        baseline_overload_id: "COMFY-TENSOR-OP-9FE84462B357:blocked",
        baseline_fixture_sha256: "60e3cb040dc47ab18f6395651604cb18e7ba07c6dbd7476a04ef4d21e4143e98",
        overload_id: "zed.native.tensor.empty.cpu-strided.v1",
        ordered_parameters_json: r#"[{"name":"shape","type":"&[u64]","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"DType","default":"F32","keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn empty_with_context_exact_native(backend: &CpuBackend, shape: &[u64], dtype: DType, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh canonical allocation with no externally defined element values",
        alias_rule: "fresh writable Tensor storage",
        shape_rule: "exact checked requested shape including scalar and zero-sized dimensions",
        dtype_rule: "any CPU backend dtype; requires_grad is restricted to floating or complex dtype",
        accumulation_dtype: "not applicable to allocation",
        layout_rule: "source torch.strided request maps to physically contiguous storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "element values are unspecified by the operation contract; safe backing bytes are owned by the CPU allocator",
        tolerance: "structural shape, dtype, access, and allocation identity only",
        determinism: "descriptor and allocation ownership are deterministic while element values are outside the contract",
        cancellation_points: "before validation, during allocation, and before publication",
        vjp_rule: "fresh leaf registration is owned by the canonical AutogradTape",
        jvp_rule: "fresh leaf registration is owned by the canonical AutogradTape",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/empty.json",
        evidence_fixture_sha256: "eba5348b19ad2079ee6607477db875189dc197b6793a3613c0226f6282f3601d",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-CA2E738EA0EF",
        baseline_overload_id: "COMFY-TENSOR-OP-CA2E738EA0EF:blocked",
        baseline_fixture_sha256: "aaa63886b7313e0b6aaae7ec8ef1c4afa7a1bfba0c7f1f2416f4b5f8ac3b4e77",
        overload_id: "zed.native.tensor.eye.cpu-real-strided.v1",
        ordered_parameters_json: r#"[{"name":"rows","type":"u64","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"columns","type":"Option<u64>","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"DType","default":"F32","keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn eye_with_context_exact_native(backend: &CpuBackend, rows: u64, columns: Option<u64>, dtype: DType, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh matrix published only after complete checked generation",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "rank-two rows by columns, with omitted columns equal to rows and zero dimensions supported",
        dtype_rule: "checked scalar encoding to the selected CPU dtype; requires_grad only for floating or complex dtype",
        accumulation_dtype: "exact Boolean diagonal predicate before destination encoding",
        layout_rule: "source torch.strided request maps to contiguous row-major storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "one exactly where row equals column and zero elsewhere",
        tolerance: "bit exact after destination encoding",
        determinism: "row-major logical traversal",
        cancellation_points: "before validation, every 1024 elements, during upload, and before publication",
        vjp_rule: "forward-only constant creation with no differentiable input",
        jvp_rule: "forward-only constant creation with no differentiable input",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/eye.json",
        evidence_fixture_sha256: "924df8a84bb2891654a46f1f11e5a96dc1ede54bb782c8df65bee770102dacac",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-AB3BD8938087",
        baseline_overload_id: "COMFY-TENSOR-OP-AB3BD8938087:blocked",
        baseline_fixture_sha256: "a6ba93e802f092e89be9464251cf2229e50514b2e5bae6a3913318fff7832152",
        overload_id: "zed.native.tensor.from-numpy.immutable-array-alias.v1",
        ordered_parameters_json: r#"[{"name":"array","type":"&NativeArray","default":null,"keyword_only":false,"kind":"positional_or_keyword"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn from_numpy_exact_native(array: &NativeArray, cancellation: &CancellationToken) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "immutable native-array storage is never mutated",
        alias_rule: "zero-copy read-only Tensor view aliases the Arc-backed native-array bytes",
        shape_rule: "preserves checked shape, signed element strides, and storage offset",
        dtype_rule: "preserves the native-array canonical DType",
        accumulation_dtype: "not applicable to zero-copy aliasing",
        layout_rule: "preserves exact strided metadata as Layout::Strided",
        device_rule: "immutable host arrays map to CPU only",
        numeric_rule: "native-endian bytes are interpreted exclusively through the canonical dtype codec",
        tolerance: "bit exact zero-copy storage alias",
        determinism: "descriptor and byte identity are preserved",
        cancellation_points: "before descriptor publication and after canonical storage construction",
        vjp_rule: "external native-array data is a forward-only leaf",
        jvp_rule: "external native-array data is a forward-only leaf",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/from_numpy.json",
        evidence_fixture_sha256: "e3ff781868acad4eab1ab45461f7e3ecea14079e278d912c3bf1dff0ff5ad846",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-80ED45644147",
        baseline_overload_id: "COMFY-TENSOR-OP-80ED45644147:blocked",
        baseline_fixture_sha256: "59f787efaccc5f851ed80d21a8905a9f4224b22a6a737547ff41d483a9f36d8e",
        overload_id: "zed.native.tensor.full.cpu-scalar-strided.v1",
        ordered_parameters_json: r#"[{"name":"shape","type":"&[u64]","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"fill_value","type":"Scalar","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"Option<DType>","default":null,"keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn full_with_context_exact_native(backend: &CpuBackend, shape: &[u64], fill_value: Scalar, dtype: Option<DType>, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh output published only after canonical fill completion",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "exact checked requested shape including scalar and zero-sized dimensions",
        dtype_rule: "infers Bool, I64, or F32 from fill_value unless explicit dtype is supplied; conversion is checked",
        accumulation_dtype: "canonical scalar codec",
        layout_rule: "source torch.strided request maps to contiguous physical storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "every logical element is the destination-dtype encoding of fill_value",
        tolerance: "bit exact after destination encoding",
        determinism: "canonical CPU fill traversal",
        cancellation_points: "before validation, throughout fill, and before publication",
        vjp_rule: "forward-only scalar constant creation",
        jvp_rule: "forward-only scalar constant creation",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/full.json",
        evidence_fixture_sha256: "3cfa23106bc5f824d0e941657493b08a8d379cad0c6bfb20f96fde08d2288cb2",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-00009BB729DF",
        baseline_overload_id: "COMFY-TENSOR-OP-00009BB729DF:blocked",
        baseline_fixture_sha256: "e65d0087bab7b749fd5b4aa24de4e1653a35480b17bec27411861a8f72192d52",
        overload_id: "zed.native.tensor.linspace.cpu-real-strided.v1",
        ordered_parameters_json: r#"[{"name":"start","type":"f64","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"end","type":"f64","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"steps","type":"u64","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"DType","default":"F32","keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn linspace_with_context_exact_native(backend: &CpuBackend, start: f64, end: f64, steps: u64, dtype: DType, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh output published only after complete checked generation",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "rank-one length steps; zero steps is empty and one step contains start",
        dtype_rule: "real integer or floating destination dtype with checked encoding",
        accumulation_dtype: "F64 interpolation before destination encoding",
        layout_rule: "source torch.strided request maps to contiguous row-major storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "inclusive affine interpolation with the final element assigned exactly to end",
        tolerance: "destination-dtype rounding; analytical derivatives use F64 accumulation",
        determinism: "ascending logical index traversal with exact endpoint assignment",
        cancellation_points: "before validation, every 1024 values, during upload, and before publication",
        vjp_rule: "start receives sum gradient times one minus interpolation weight; end receives sum gradient times weight",
        jvp_rule: "affine interpolation of start and end tangents",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/linspace.json",
        evidence_fixture_sha256: "ebfc64825e3ff7da77ec9a9bd480bc6e7e7c3ffee0bf9b21d00361ecc5a9625e",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-67746161BCEF",
        baseline_overload_id: "COMFY-TENSOR-OP-67746161BCEF:blocked",
        baseline_fixture_sha256: "006499287badb4e2663f0a0f820778dacf11b4eeb17589b6e1d0d36538793932",
        overload_id: "zed.native.tensor.ones.cpu-strided.v1",
        ordered_parameters_json: r#"[{"name":"shape","type":"&[u64]","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"DType","default":"F32","keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn ones_with_context_exact_native(backend: &CpuBackend, shape: &[u64], dtype: DType, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh output published only after canonical fill completion",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "exact checked requested shape including scalar and zero-sized dimensions",
        dtype_rule: "one is checked through the canonical destination dtype codec",
        accumulation_dtype: "canonical scalar codec",
        layout_rule: "source torch.strided request maps to contiguous physical storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "every logical element is exactly one in the selected dtype",
        tolerance: "bit exact after destination encoding",
        determinism: "canonical CPU fill traversal",
        cancellation_points: "before validation, throughout fill, and before publication",
        vjp_rule: "forward-only constant creation with canonical leaf registration",
        jvp_rule: "forward-only constant creation with canonical leaf registration",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/ones.json",
        evidence_fixture_sha256: "d7f803a4928a4c66b77ebb2bffdc41ab3587c71a3b7c5e75e3105313b6aee184",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-C82C17577549",
        baseline_overload_id: "COMFY-TENSOR-OP-C82C17577549:blocked",
        baseline_fixture_sha256: "d78d552d5b05b8585feaaa3423d591ef8b913881199ba3fe38ef34f0fec85c5e",
        overload_id: "zed.native.tensor.tensor.detached-copy.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"NativeTensorInput<'_>","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"Option<DType>","default":null,"keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_with_context_exact_native(backend: &CpuBackend, input: NativeTensorInput<'_>, dtype: Option<DType>, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "input is never mutated; complete detached copy is published after conversion",
        alias_rule: "always fresh canonical Tensor storage even for Tensor or native-array input",
        shape_rule: "preserves Tensor and native-array shape; literal shape must exactly match value count",
        dtype_rule: "preserves source dtype or infers literal Bool/I64/F32 unless explicit checked dtype is supplied",
        accumulation_dtype: "canonical dtype codec and cast traversal",
        layout_rule: "fresh physically contiguous output",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "logical values are copied through canonical checked scalar conversion",
        tolerance: "bit exact without conversion and destination-dtype rounding with conversion",
        determinism: "logical row-major traversal",
        cancellation_points: "before validation, throughout copy or conversion, and before publication",
        vjp_rule: "detached constructor input has no gradient edge; requires_grad registers the fresh output leaf in AutogradTape",
        jvp_rule: "detached constructor input has no tangent edge",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/tensor.json",
        evidence_fixture_sha256: "e92b3bf42aafca511e6d4007304641b4409a3fd60023e9e5edff3d1e60a3be6e",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-4D196D1FC26D",
        baseline_overload_id: "COMFY-TENSOR-OP-4D196D1FC26D:blocked",
        baseline_fixture_sha256: "1af3c0a5c4cb085c53d4818af0934e9fd7a42f7d270a451793aade0f526912e3",
        overload_id: "zed.native.tensor.zeros.cpu-strided.v1",
        ordered_parameters_json: r#"[{"name":"shape","type":"&[u64]","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"DType","default":"F32","keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn zeros_with_context_exact_native(backend: &CpuBackend, shape: &[u64], dtype: DType, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh output published only after canonical fill completion",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "exact checked requested shape including scalar and zero-sized dimensions",
        dtype_rule: "zero is checked through the canonical destination dtype codec",
        accumulation_dtype: "canonical scalar codec",
        layout_rule: "source torch.strided request maps to contiguous physical storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "every logical element is positive zero in the selected dtype",
        tolerance: "bit exact after destination encoding",
        determinism: "canonical CPU fill traversal",
        cancellation_points: "before validation, throughout fill, and before publication",
        vjp_rule: "forward-only constant creation with canonical leaf registration",
        jvp_rule: "forward-only constant creation with canonical leaf registration",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/zeros.json",
        evidence_fixture_sha256: "ad8cf0dca20a572f10f2377eb9d6ffd86d63a42430ab251455b78e58179608f5",
    },
]
