&[
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-583EFBAFDD35",
        baseline_overload_id: "COMFY-TENSOR-OP-583EFBAFDD35:blocked",
        baseline_fixture_sha256: "07e1d81a2606652fed0922c31a8b8333def99ca1f47e1880dc2da03e92f6f0d1",
        overload_id: "zed.native.tensor.arange.cpu-real-strided.v1",
        ordered_parameters_json: r#"[{"name":"start","type":"Scalar","default":0,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"end","type":"Scalar","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"step","type":"Scalar","default":1,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"Option<DType>","default":null,"keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn arange_with_context_exact_native(backend: &CpuBackend, start: Scalar, end: Scalar, step: Scalar, dtype: Option<DType>, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh output published only after complete checked generation and upload",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "rank-one ceil-divided half-open range including empty direction mismatch",
        dtype_rule: "defaults to I64 for integral scalars and F32 when any scalar is floating; explicit real numeric dtype is checked",
        accumulation_dtype: "I128 for integral bounds and F64 for floating bounds",
        layout_rule: "source torch.strided request maps to physically contiguous row-major storage",
        device_rule: "CPU certified; every other device returns a typed unavailable error",
        numeric_rule: "start plus logical index times step with exact integer arithmetic and finite floating bounds",
        tolerance: "bit exact for integers and destination-dtype rounding for floating values",
        determinism: "ascending logical index traversal",
        cancellation_points: "before validation, every 1024 values, during upload, and before publication",
        vjp_rule: "forward-only discrete sequence creation with no differentiable tensor input",
        jvp_rule: "forward-only discrete sequence creation with no differentiable tensor input",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/arange.json",
        evidence_fixture_sha256: "545b475b61ad9127e5afed8773f2ae45d9920d7a04db202173b80de70bd99499",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-1D3DBB9A17A7",
        baseline_overload_id: "COMFY-TENSOR-OP-1D3DBB9A17A7:blocked",
        baseline_fixture_sha256: "c40b3a338890ae79e929f9f207284668a61211ba78489632072366bfe2a464bf",
        overload_id: "zed.native.tensor.as-tensor.checked-input.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"NativeTensorInput<'_>","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"Option<DType>","default":null,"keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"Option<DeviceId>","default":null,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn as_tensor_with_context_exact_native(backend: &CpuBackend, input: NativeTensorInput<'_>, dtype: Option<DType>, device: Option<DeviceId>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "input is never mutated and conversion publishes only after the canonical cast completes",
        alias_rule: "same dtype and device Tensor input aliases canonical storage; literals allocate and conversions copy",
        shape_rule: "preserves Tensor and native-array shape; literal shape must exactly match value count",
        dtype_rule: "preserves Tensor or native-array dtype, infers literal Bool/I64/F32, or applies an explicit canonical cast",
        accumulation_dtype: "canonical dtype codec and cast traversal",
        layout_rule: "preserves an exact alias or publishes a contiguous conversion",
        device_rule: "CPU certified with typed errors for unavailable devices",
        numeric_rule: "canonical checked scalar encoding and dtype conversion",
        tolerance: "bit exact for aliases and integers; destination-dtype rounding for casts",
        determinism: "logical row-major literal and cast traversal",
        cancellation_points: "before validation, throughout conversion, and before publication",
        vjp_rule: "identity for aliases and canonical cast VJP for differentiable conversions",
        jvp_rule: "identity for aliases and canonical cast JVP for differentiable conversions",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/as_tensor.json",
        evidence_fixture_sha256: "c4ee9b98c297cfcd5112d572da78bb1d5e7aef2b80aec3f98a68a4c5ccfe90bc",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-9FE84462B357",
        baseline_overload_id: "COMFY-TENSOR-OP-9FE84462B357:blocked",
        baseline_fixture_sha256: "c3b9130dc16c958d8c36475c023e47b25fcdfa99f707e08cdfbfde0cebc74780",
        overload_id: "zed.native.tensor.empty.cpu-strided.v1",
        ordered_parameters_json: r#"[{"name":"shape","type":"&[u64]","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"DType","default":"F32","keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn empty_with_context_exact_native(backend: &CpuBackend, shape: &[u64], dtype: DType, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh canonical allocation with no externally defined element values",
        alias_rule: "fresh writable Tensor storage",
        shape_rule: "exact checked requested shape including scalar and zero-sized dimensions",
        dtype_rule: "any CPU backend dtype; requires_grad is restricted to floating or complex dtype",
        accumulation_dtype: "not applicable to allocation",
        layout_rule: "source torch.strided request maps to physically contiguous storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "element values are unspecified by the operation contract; safe backing bytes are owned by the CPU allocator",
        tolerance: "structural shape, dtype, access, and allocation identity only",
        determinism: "descriptor and allocation ownership are deterministic while element values are outside the contract",
        cancellation_points: "before validation, during allocation, and before publication",
        vjp_rule: "fresh leaf registration is owned by the canonical AutogradTape",
        jvp_rule: "fresh leaf registration is owned by the canonical AutogradTape",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/empty.json",
        evidence_fixture_sha256: "31eedb1c4ee5960f6933acf568fb8163e07090e996dc81c70502f278d985cde5",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-CA2E738EA0EF",
        baseline_overload_id: "COMFY-TENSOR-OP-CA2E738EA0EF:blocked",
        baseline_fixture_sha256: "f8be1378f8491a1987f3f581d752dcbd4f61ffc027b213a6d8e937da1b5dfe56",
        overload_id: "zed.native.tensor.eye.cpu-real-strided.v1",
        ordered_parameters_json: r#"[{"name":"rows","type":"u64","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"columns","type":"Option<u64>","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"DType","default":"F32","keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn eye_with_context_exact_native(backend: &CpuBackend, rows: u64, columns: Option<u64>, dtype: DType, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh matrix published only after complete checked generation",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "rank-two rows by columns, with omitted columns equal to rows and zero dimensions supported",
        dtype_rule: "checked scalar encoding to the selected CPU dtype; requires_grad only for floating or complex dtype",
        accumulation_dtype: "exact Boolean diagonal predicate before destination encoding",
        layout_rule: "source torch.strided request maps to contiguous row-major storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "one exactly where row equals column and zero elsewhere",
        tolerance: "bit exact after destination encoding",
        determinism: "row-major logical traversal",
        cancellation_points: "before validation, every 1024 elements, during upload, and before publication",
        vjp_rule: "forward-only constant creation with no differentiable input",
        jvp_rule: "forward-only constant creation with no differentiable input",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/eye.json",
        evidence_fixture_sha256: "b83e2fe8aad0bd04880aa86b29df2a325b1a06934645c0c106d05603c82ffc99",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-AB3BD8938087",
        baseline_overload_id: "COMFY-TENSOR-OP-AB3BD8938087:blocked",
        baseline_fixture_sha256: "49bb96cf447ec4ce575127b58c59edaf10237995209da2e03fc0c933c91b7ad8",
        overload_id: "zed.native.tensor.from-numpy.immutable-array-alias.v1",
        ordered_parameters_json: r#"[{"name":"array","type":"&NativeArray","default":null,"keyword_only":false,"kind":"positional_or_keyword"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn from_numpy_exact_native(array: &NativeArray, cancellation: &CancellationToken) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "immutable native-array storage is never mutated",
        alias_rule: "zero-copy read-only Tensor view aliases the Arc-backed native-array bytes",
        shape_rule: "preserves checked shape, signed element strides, and storage offset",
        dtype_rule: "preserves the native-array canonical DType",
        accumulation_dtype: "not applicable to zero-copy aliasing",
        layout_rule: "preserves exact strided metadata as Layout::Strided",
        device_rule: "immutable host arrays map to CPU only",
        numeric_rule: "native-endian bytes are interpreted exclusively through the canonical dtype codec",
        tolerance: "bit exact zero-copy storage alias",
        determinism: "descriptor and byte identity are preserved",
        cancellation_points: "before descriptor publication and after canonical storage construction",
        vjp_rule: "external native-array data is a forward-only leaf",
        jvp_rule: "external native-array data is a forward-only leaf",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/from_numpy.json",
        evidence_fixture_sha256: "5e7bbd2874f2c7ebab487054fa64aca8456ec4fc9461b79765960200dc5a6624",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-80ED45644147",
        baseline_overload_id: "COMFY-TENSOR-OP-80ED45644147:blocked",
        baseline_fixture_sha256: "79b369e655284b0478338ea1b4ee8729118b9ec8d862a539423f56fe5d4d3919",
        overload_id: "zed.native.tensor.full.cpu-scalar-strided.v1",
        ordered_parameters_json: r#"[{"name":"shape","type":"&[u64]","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"fill_value","type":"Scalar","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"Option<DType>","default":null,"keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn full_with_context_exact_native(backend: &CpuBackend, shape: &[u64], fill_value: Scalar, dtype: Option<DType>, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh output published only after canonical fill completion",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "exact checked requested shape including scalar and zero-sized dimensions",
        dtype_rule: "infers Bool, I64, or F32 from fill_value unless explicit dtype is supplied; conversion is checked",
        accumulation_dtype: "canonical scalar codec",
        layout_rule: "source torch.strided request maps to contiguous physical storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "every logical element is the destination-dtype encoding of fill_value",
        tolerance: "bit exact after destination encoding",
        determinism: "canonical CPU fill traversal",
        cancellation_points: "before validation, throughout fill, and before publication",
        vjp_rule: "forward-only scalar constant creation",
        jvp_rule: "forward-only scalar constant creation",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/full.json",
        evidence_fixture_sha256: "7432dda9dfcdca0ce0020022fae317891d9ece8b102aa88024438540408ae227",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-00009BB729DF",
        baseline_overload_id: "COMFY-TENSOR-OP-00009BB729DF:blocked",
        baseline_fixture_sha256: "586d5567306f49f279f32f29616e6d3756d84b63d89f7d7ed9f0bd34e57ca0ed",
        overload_id: "zed.native.tensor.linspace.cpu-real-strided.v1",
        ordered_parameters_json: r#"[{"name":"start","type":"f64","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"end","type":"f64","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"steps","type":"u64","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"DType","default":"F32","keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn linspace_with_context_exact_native(backend: &CpuBackend, start: f64, end: f64, steps: u64, dtype: DType, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh output published only after complete checked generation",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "rank-one length steps; zero steps is empty and one step contains start",
        dtype_rule: "real integer or floating destination dtype with checked encoding",
        accumulation_dtype: "F64 interpolation before destination encoding",
        layout_rule: "source torch.strided request maps to contiguous row-major storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "inclusive affine interpolation with the final element assigned exactly to end",
        tolerance: "destination-dtype rounding; analytical derivatives use F64 accumulation",
        determinism: "ascending logical index traversal with exact endpoint assignment",
        cancellation_points: "before validation, every 1024 values, during upload, and before publication",
        vjp_rule: "start receives sum gradient times one minus interpolation weight; end receives sum gradient times weight",
        jvp_rule: "affine interpolation of start and end tangents",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/linspace.json",
        evidence_fixture_sha256: "5b858c015071847d915fc5d7cf2de1da26be7df762ac9ef99c432a4e13e174b0",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-67746161BCEF",
        baseline_overload_id: "COMFY-TENSOR-OP-67746161BCEF:blocked",
        baseline_fixture_sha256: "ca67230fdee52f9e3ff320ceb83be071cd43ea16ce8bfd2023f2576fc16e711f",
        overload_id: "zed.native.tensor.ones.cpu-strided.v1",
        ordered_parameters_json: r#"[{"name":"shape","type":"&[u64]","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"DType","default":"F32","keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn ones_with_context_exact_native(backend: &CpuBackend, shape: &[u64], dtype: DType, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh output published only after canonical fill completion",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "exact checked requested shape including scalar and zero-sized dimensions",
        dtype_rule: "one is checked through the canonical destination dtype codec",
        accumulation_dtype: "canonical scalar codec",
        layout_rule: "source torch.strided request maps to contiguous physical storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "every logical element is exactly one in the selected dtype",
        tolerance: "bit exact after destination encoding",
        determinism: "canonical CPU fill traversal",
        cancellation_points: "before validation, throughout fill, and before publication",
        vjp_rule: "forward-only constant creation with canonical leaf registration",
        jvp_rule: "forward-only constant creation with canonical leaf registration",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/ones.json",
        evidence_fixture_sha256: "10a460e469661337928e7028135253205de0ed75351f48a0395e20478aa04c7e",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-C82C17577549",
        baseline_overload_id: "COMFY-TENSOR-OP-C82C17577549:blocked",
        baseline_fixture_sha256: "7f9b7f79b6ea5af801d7dfd58905852cfa0a60adc04da85ba8724f9e692cbb38",
        overload_id: "zed.native.tensor.tensor.detached-copy.v1",
        ordered_parameters_json: r#"[{"name":"input","type":"NativeTensorInput<'_>","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"Option<DType>","default":null,"keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn tensor_with_context_exact_native(backend: &CpuBackend, input: NativeTensorInput<'_>, dtype: Option<DType>, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "input is never mutated; complete detached copy is published after conversion",
        alias_rule: "always fresh canonical Tensor storage even for Tensor or native-array input",
        shape_rule: "preserves Tensor and native-array shape; literal shape must exactly match value count",
        dtype_rule: "preserves source dtype or infers literal Bool/I64/F32 unless explicit checked dtype is supplied",
        accumulation_dtype: "canonical dtype codec and cast traversal",
        layout_rule: "fresh physically contiguous output",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "logical values are copied through canonical checked scalar conversion",
        tolerance: "bit exact without conversion and destination-dtype rounding with conversion",
        determinism: "logical row-major traversal",
        cancellation_points: "before validation, throughout copy or conversion, and before publication",
        vjp_rule: "detached constructor input has no gradient edge; requires_grad registers the fresh output leaf in AutogradTape",
        jvp_rule: "detached constructor input has no tangent edge",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/tensor.json",
        evidence_fixture_sha256: "87c8f52f79d548ff681dd7420e88a2857a992a5057aa7eb592bb6c87136d44db",
    },
    ResolvedOperationContract {
        resolution_module: "tensor_creation_01",
        operation_id: "COMFY-TENSOR-OP-4D196D1FC26D",
        baseline_overload_id: "COMFY-TENSOR-OP-4D196D1FC26D:blocked",
        baseline_fixture_sha256: "40a4fd908aa12f19dee7de2ff2e9b37fb9f9a3d99c815fbedf043e59c6443b62",
        overload_id: "zed.native.tensor.zeros.cpu-strided.v1",
        ordered_parameters_json: r#"[{"name":"shape","type":"&[u64]","default":null,"keyword_only":false,"kind":"positional_or_keyword"},{"name":"dtype","type":"DType","default":"F32","keyword_only":true,"kind":"keyword_only"},{"name":"layout","type":"Layout","default":"Strided","keyword_only":true,"kind":"keyword_only"},{"name":"device","type":"DeviceId","default":"CPU","keyword_only":true,"kind":"keyword_only"},{"name":"requires_grad","type":"bool","default":false,"keyword_only":true,"kind":"keyword_only"}]"#,
        output_arity: "1",
        output_types_json: r#"["Tensor"]"#,
        rust_signature: "fn zeros_with_context_exact_native(backend: &CpuBackend, shape: &[u64], dtype: DType, layout: Layout, device: DeviceId, requires_grad: bool, autograd_registration: Option<(&mut AutogradTape, LeafId)>, context: &ExecutionContext<'_>) -> Result<Tensor, TensorCreationPartOneError>",
        mutation_rule: "fresh output published only after canonical fill completion",
        alias_rule: "fresh canonical Tensor storage",
        shape_rule: "exact checked requested shape including scalar and zero-sized dimensions",
        dtype_rule: "zero is checked through the canonical destination dtype codec",
        accumulation_dtype: "canonical scalar codec",
        layout_rule: "source torch.strided request maps to contiguous physical storage",
        device_rule: "CPU certified with typed unavailable-device errors",
        numeric_rule: "every logical element is positive zero in the selected dtype",
        tolerance: "bit exact after destination encoding",
        determinism: "canonical CPU fill traversal",
        cancellation_points: "before validation, throughout fill, and before publication",
        vjp_rule: "forward-only constant creation with canonical leaf registration",
        jvp_rule: "forward-only constant creation with canonical leaf registration",
        owner_task_id: "comfy-parity-tensor-ops-tensor-creation-comfy-tensor-op-00009bb729df",
        evidence_fixture: "crates/comfy_test_support/fixtures/tensor_operations/tensor_creation_01/zeros.json",
        evidence_fixture_sha256: "86cad92ca05c48023f94292c0f106ac5ad92c6fc4061da0a6f00c94e408465e2",
    },
]
