[package]
name = "baymax_server"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "baymax_server.rs"

[dependencies]
anyhow.workspace = true
axum = { version = "0.6", features = ["json", "headers"] }
futures.workspace = true
recipe.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
tower-http = { workspace = true, features = ["cors"] }

[dev-dependencies]
tower = "0.4"
