#!/usr/bin/env bash

set -euo pipefail

all_features=true
filtered_arguments=()
for argument in "$@"; do
    case "$argument" in
        --no-all-features) all_features=false ;;
        *) filtered_arguments+=("$argument") ;;
    esac
done
set -- "${filtered_arguments[@]}"

if [[ ! " $* " == *" -p "* && ! " $* " == *" --package "* ]]; then
    set -- "$@" --workspace
fi

set -x
if [[ "$all_features" = true ]]; then
    "${CARGO:-cargo}" clippy "$@" --release --all-targets --all-features -- --deny warnings
else
    "${CARGO:-cargo}" clippy "$@" --release --all-targets -- --deny warnings
fi

# If local, run other checks if we have the tools installed.
if [[ -z "${GITHUB_ACTIONS+x}" ]]; then
    which cargo-machete >/dev/null 2>&1 || exit 0
    cargo machete

    which typos >/dev/null 2>&1 || exit 0
    typos --config typos.toml

    which buf >/dev/null 2>&1 || exit 0
    buf lint crates/proto/proto
    buf format --diff --exit-code crates/proto/proto
fi
