#!/usr/bin/env bash

set -euxo pipefail

rust_tools=false
if [[ "${1:-}" == "--rust-tools" ]]; then
  rust_tools=true
  shift
fi

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs sim onto your system into ~/.local, making it available as ~/.local/bin/sim.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export SIM_CHANNEL=$(<crates/sim/RELEASE_CHANNEL)
export SIM_UPDATE_EXPLANATION="You need to fetch and rebuild sim in $(pwd)"
if [[ "$rust_tools" = true ]]; then
  script/bundle-linux --rust-tools
else
  script/bundle-linux
fi

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="sim-linux-${arch}.tar.gz"
export SIM_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
