#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs baymax onto your system into ~/.local, making it available as ~/.local/bin/baymax.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export BAYMAX_CHANNEL=$(<crates/baymax/RELEASE_CHANNEL)
export BAYMAX_UPDATE_EXPLANATION="You need to fetch and rebuild baymax in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="baymax-linux-${arch}.tar.gz"
export BAYMAX_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
