CREATE TABLE public.channel_join_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id integer NOT NULL REFERENCES public.channels(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    reason text,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    UNIQUE (channel_id, user_id)
);

CREATE INDEX index_channel_join_requests_on_channel_id
    ON public.channel_join_requests USING btree (channel_id);

CREATE INDEX index_channel_join_requests_on_created_at
    ON public.channel_join_requests USING btree (created_at);
