CREATE TABLE public.channel_bookmarks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id integer NOT NULL REFERENCES public.channels(id) ON DELETE CASCADE,
    label text NOT NULL,
    description text,
    bookmark_type smallint NOT NULL,
    url text NOT NULL,
    file_id text,
    message_id integer REFERENCES public.channel_messages(id) ON DELETE SET NULL,
    created_by integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    sort_order integer NOT NULL
);

CREATE INDEX index_channel_bookmarks_on_channel_id_and_sort_order
    ON public.channel_bookmarks USING btree (channel_id, sort_order);
