ALTER TABLE public.channel_messages
    ADD COLUMN scheduled_at TIMESTAMP WITHOUT TIME ZONE;

CREATE TABLE public.scheduled_messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id integer NOT NULL REFERENCES public.channels(id) ON DELETE CASCADE,
    sender_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    scheduled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    state SMALLINT NOT NULL DEFAULT 0,
    nonce BYTEA NOT NULL,
    mentions JSONB NOT NULL DEFAULT '[]'::jsonb,
    delivered_message_id integer REFERENCES public.channel_messages(id) ON DELETE SET NULL,
    failure_reason TEXT,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX index_scheduled_messages_on_pending_delivery
    ON public.scheduled_messages (state, scheduled_at)
    WHERE state = 0;

CREATE INDEX index_scheduled_messages_on_sender_channel_pending
    ON public.scheduled_messages (sender_id, channel_id)
    WHERE state = 0;

CREATE UNIQUE INDEX index_scheduled_messages_on_channel_sender_nonce
    ON public.scheduled_messages (channel_id, sender_id, nonce);
