CREATE TABLE public.channel_messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id integer NOT NULL REFERENCES public.channels(id) ON DELETE CASCADE,
    sender_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    body text NOT NULL,
    nonce bytea NOT NULL,
    reply_to_message_id integer REFERENCES public.channel_messages(id) ON DELETE SET NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    edited_at timestamp without time zone,
    deleted_at timestamp without time zone
);

CREATE INDEX index_channel_messages_on_channel_id_and_id
    ON public.channel_messages USING btree (channel_id, id);

CREATE INDEX index_channel_messages_on_reply_to_message_id
    ON public.channel_messages USING btree (reply_to_message_id);

CREATE TABLE public.channel_message_mentions (
    message_id integer NOT NULL REFERENCES public.channel_messages(id) ON DELETE CASCADE,
    range_start bigint NOT NULL,
    range_end bigint NOT NULL,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    PRIMARY KEY (message_id, range_start, range_end, user_id)
);

CREATE INDEX index_channel_message_mentions_on_user_id
    ON public.channel_message_mentions USING btree (user_id);

CREATE TABLE public.channel_message_reads (
    channel_id integer NOT NULL REFERENCES public.channels(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    message_id integer NOT NULL REFERENCES public.channel_messages(id) ON DELETE CASCADE,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (channel_id, user_id)
);

CREATE INDEX index_channel_message_reads_on_message_id
    ON public.channel_message_reads USING btree (message_id);
