[package]
name = "git_credential_nostr"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/git_credential_nostr.rs"

[[bin]]
name = "git-credential-nostr"
path = "src/main.rs"

[dependencies]
base64.workspace = true
nostr = { workspace = true, features = ["nip98"] }
serde_json.workspace = true
smol.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation.workspace = true
core-foundation-sys.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
oo7 = { version = "0.6", default-features = false, features = ["async-std", "native_crypto"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true
